### ISSUE TITLE
Warp does not save custom size when closed and opened again

### ISSUE THREAD

**Issue by gustavoabel** [warpdotdev/Warp#4572] opened 2024-03-16 23:39 UTC
### Describe the bug

Warp does not maintain the custom size when closed on MacOS, only when we close the window without closing the application.

### To reproduce

Steps to reproduce:

1. Open Warp
2. Quit Warp application
3. Open again

**Comment by dannyneira** [comment] 2024-05-24 20:39
Thanks for letting us know @gustavoabel 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/4011 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-24 20:39
Duplicate of https://github.com/warpdotdev/Warp/issues/4011

**Closed by dannyneira** 2024-05-24 20:39 UTC
Labels: Bugs
