### ISSUE TITLE
Unable to run true fish by default

### ISSUE THREAD

**Issue by DoctorRyner** [warpdotdev/Warp#5385] opened 2024-10-16 12:46 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

 I want a checkbox or something similar to start with true shell and not Warp's wrapper around shell

### Is your feature request related to a problem? Please describe.

I want an option to use Warp as a Terminal Emulator without some excessive features for me. But when for example I disable Warp completions, I don't get fish completions. I have to enter `fish` to get that. And doing it every time for every tab is madness

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-10-16 22:49
Hi @DoctorRyner Thanks for submitting this!

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1811

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-10-16 22:49
Duplicate of https://github.com/warpdotdev/Warp/issues/1811

**Closed by dannyneira** 2024-10-16 22:49 UTC
Labels: Feature requests

**Comment by DoctorRyner** [comment] 2024-10-16 22:53
@dannyneira oh, it was over 2 years ago 💀

I hope it'll get fixed

**Comment by dannyneira** [comment] 2024-10-16 23:00
The more 👍 on the request the better chance. To be fully transparent this may be technically challenging to support. Since Warp has created a wrapper around the shell, to enable certain features like the Blocks and IDE-like input we've also had to [implement our own completions spec](https://github.com/warpdotdev/Warp/discussions/434#discussioncomment-1667723). That being said, we hope to open source our completions spec in the near future which should allow for more/improved 3rd party completion support in Warp.
