### ISSUE TITLE
Zoomed Pane / Fullscreen Pane

### ISSUE THREAD

**Issue by johndagostino** [warpdotdev/Warp#685] opened 2022-01-26 21:14 UTC
### Describe the solution you'd like?

iTerm/tmux both have the ability to make a pane zoom into a single pane

iTerm: command + shift + enter
tmux: -Z, the active pane is toggled between zoomed (occupying the whole of the window) and unzoomed (its normal position in the layout).

**Comment by elviskahoro** [comment] 2022-01-28 05:24
Duplicate of:
- #417

**Closed by elviskahoro** 2022-01-28 05:24 UTC
