### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by GnaixEuy** [warpdotdev/Warp#4049] opened 2024-01-10 02:36 UTC
### Describe the solution you'd like?

we need Chinese support, If there is anything I can help, please feel free to contact me

### Additional context

we need Chinese support, If there is anything I can help, please feel free to contact me

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by XYZliang** [comment] 2024-01-10 09:17
＃1194

**Comment by dannyneira** [comment] 2024-01-10 18:37
Thanks for letting us know @GnaixEuy!

We're tracking this issue over at #1823 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-10 18:37
Duplicate of #1823

**Closed by dannyneira** 2024-01-10 18:37 UTC
Labels: Feature
