### ISSUE TITLE
Some keys' combination doesn't work as expected - vim shift-tab

### ISSUE THREAD

**Issue by ales-tsurko** [warpdotdev/Warp#903] opened 2022-04-06 07:53 UTC
### Describe the bug

In neovim I have a shortcut `Shift + Tab` to toggle the integrated terminal window. It works well on different emulators on macOS as well as on Linux. But it doesn't work in Warp. Instead of toggling the window, it's just moving the cursor up.

### To Reproduce

1. Configure `Shift + Tab` for some action in neovim
2. Try to use it inside Warp

### Operating System

MacOS

### OS Version

12.3.1

**Comment by cfurrow** [comment] 2022-06-25 01:52
I think I've most recently seen Shift+Tab sending Control+Y

From the [original `vi` manual](https://vi.stackexchange.com/a/5197/29622)
> The command ^Y (which is hopelessly non-mnemonic, but next to ^U on the keyboard) exposes one more line at the top of the screen.

🤷‍♂️

**Comment by elviskahoro** [comment] 2022-07-08 15:43
Sorry again for the trouble. Will let you know once it's a WIP

**Comment by elviskahoro** [comment] 2022-07-09 06:02
Also from @cfurrow:

> I've had a similar experience with neovim, where I use `<S-Tab>` to move to the previous buffer, and `<Tab>` to go to the next buffer. `<Tab>` works fine, but `<S-Tab>` seems to scroll the current buffer up a line or to until it reaches the top of the buffer. 

In other terminals this same mapping is working with the same neovim config.

I wondered if it was possibly a Warp keymap, but there were none for "shift + tab". 

Outside of neovim, "shift+tab" does not seem to behave the same way as it does within neovim. Doesn't seem to do anything at all, which is expected.

Update: It seems like Shift+Tab is sending Control+Y instead. At least in neovim.

**Comment by PhilBookst** [comment] 2023-01-24 17:42
Hey, any progress on this issue yet? 

This is crucial for the majority of vim users wanting to use warp!

**Comment by dannyneira** [comment] 2023-04-07 19:56
Hey Folks! There are a number of users in #2357 that also experienced this issue, I've marked that one as a duplicate of this issue.

**Comment by kyle-fredrickson** [comment] 2023-04-10 19:58
I'm having the same issue. Discovered it in neovim, but it seems like it isn't a problem with some interaction between Warp and nvim, but strictly an issue with Warp-- I tried mapping <s-tab> in the warp keybindings, and it also failed to recognize when it gets pressed.

Hoping this gets fixed soon.

**Comment by AeolusLau** [comment] 2023-04-25 06:29
Got the same problem...
It seems to have been hung for more than a year now. Any progress now?

**Comment by elviskahoro** [comment] 2023-06-01 23:53
this should be out by now gonna close out this issue!

**Closed by elviskahoro** 2023-06-01 23:53 UTC
Labels: Bug

**Comment by jakubdonovan** [comment] 2024-05-16 06:35
> this should be out by now gonna close out this issue!

2024, still experiencing this issue. Just downloaded WezTerm to see that it is indeed a problem with warp and not my configuration.

**Comment by empz** [comment] 2026-01-14 11:48
This should not be closed, it's still happening. I can't use Shift+TAB in Claude Code CLI.

**Comment by h1048576** [comment] 2026-01-16 01:03
> This should not be closed, it's still happening. I can't use Shift+TAB in Claude Code CLI.这不应该关闭，问题仍然存在。我在 Claude Code CLI 中无法使用 Shift+TAB。

me too
