### ISSUE TITLE
Workflows can't be used when remote host is not accessed via ssh

### ISSUE THREAD

**Issue by zxaos** [warpdotdev/Warp#4103] opened 2024-01-24 18:35 UTC
### Describe the bug

Invoking a workflow when connected to a remote host via something other than ssh, such as Teleport's tsh, fails with "A command in this session is still running"

### To reproduce

1. Define a workflow
2. Connect to a remote host using teleport: `tsh ssh alice@example.com`
3. Invoke the workflow by clicking on it in the sidebar
4. See the warning `A command in this session is still running`

### Expected behavior

The workflow should run

### Operating system

MacOS

### Operating system and version

macOS 14.2.1

### Shell Version

zsh 5.9 (arm-apple-darwin22.1.0)

### Current Warp version

v0.2024.01.16.16.31.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-26 23:04
hey @zxaos sorry about this blocker but `tsh` isn't supporting warp features at this time. This is a request we're tracking here https://github.com/warpdotdev/Warp/issues/4067

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment] 2024-01-26 23:05
Duplicate of https://github.com/warpdotdev/Warp/issues/4067

**Closed by dannyneira** 2024-01-26 23:05 UTC
Labels: Bugs
