### ISSUE TITLE
Feature Request: Delete Block

### ISSUE THREAD

**Issue by wesbos** [warpdotdev/Warp#4817] opened 2024-04-24 16:08 UTC
### Discord username (optional)

wesbos

### Describe the solution you'd like?

This might be slightly niche, so feel free to say no :) 

As a content creator, I often screenshot or record myself using a terminal. Would love to be able to just delete or hide a blocks in a few situations:

1. If I goof up, I often want to cut the error'd result out of the final output - but that isn't really possible. 
2. Sometimes I also want to run a command to touch a file or check if a file exists, but can't because the output would be in the video or screenshot.
3. If I forget to clear my terminal before running a command, learners will see previous outputs

<img width="934" alt="Screenshot 2024-04-24 at 12 02 08 PM" src="https://github.com/warpdotdev/Warp/assets/176013/360f458d-959c-461d-8b15-e7912e9b327a">

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-24 19:49
Thanks for submitting this @wesbos, we've had others request this for similar reasons. Unfortunately, there isn't a decent workaround or stopgap at this time (other than to clear the blocks with CMD-K and run the commands again ).

That being said, we already have a request tracking block deletion over at #50 ( we also have a related one for block folding which may also meet your use case at #23 ). We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-04-24 19:49
Duplicate of #50

**Comment by wesbos** [comment] 2024-04-24 19:50
thanks Danny!

**Closed by dannyneira** 2024-04-24 19:49 UTC
Labels: enhancement
