### ISSUE TITLE
Token limit reached after 4 or 5 queries

### ISSUE THREAD

**Issue by lincoln-nocapinc** [warpdotdev/Warp#5075] opened 2024-06-28 22:12 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Big fan of your features! Just tried out the natural language feature... after a couple queries getting "I'm sorry, I can't complete that request. You've reached the monthly token limit. Your token limit resets on July 28."

### To reproduce

Try entering agent mode - after 4 or 5 queries, reach token limit. 

### Expected behavior

Token limit is supposedly generous - so shouldn't hit this after 5 queries.

### Operating system

MacOS

### Operating system and version

13.5.0

### Current Warp version

v0.2024.06.25.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-07-02 22:51
Hi @lincoln-nocapinc sorry to hear about this Monthly token limit exceeded error. You can learn more about the limits in our [docs](https://docs.warp.dev/features/warp-ai/agent-mode#exceeding-agent-mode-limits).

Warp has set an extremely high token limit on users to prevent abuse. We do not anticipate any user hitting this limit. If you hit this limit and are interested in getting it lifted, please contact us with your use case at [feedback@warp.dev](mailto:feedback@warp.dev)

Closing as this is not a bug.

**Closed by dannyneira** 2024-07-02 22:51 UTC
Labels: Bugs

**Comment by lincoln-nocapinc** [comment] 2024-07-03 01:31
Hey Danny, I believe this is a bug. I just tried out the feature and sent a couple (as stated 4 or 5) queries to it. These were very short. If Warp is saying that there is "an extremely high token limit" I would expect that 5 queries would not suffice that usage limit.

Again, I only used this feature 5 times in the span of a few minutes and was suddenly met with a token limit error. Could you please explain how this is possible if not for a bug?

**Comment by appscaptain** [comment] 2025-04-12 17:18
I just ran one large rsync command as part of a plan the AI helped me with (restoring a crashed machine over SSH). After this my monthly token limit was used (resetting in 27 days) :-O Isn't there a way to not have it send the entire command to Claude. t doesn't make sense that one large rsync command is sent to the AI when it isn't relevant for the troubleshooting. How about for commands like this that it sends a subset somehow.
