### ISSUE TITLE
Warp not offering completions for user defined completions

### ISSUE THREAD

**Issue by jimcornmell** [warpdotdev/Warp#4345] opened 2024-02-26 09:46 UTC
### Describe the bug

No completions offered for user defined ones

### To reproduce

hit tab after command, incorrect list displayed

### Expected behavior

Correct completions offerec

### Screenshots

Warp completion example, it incorrectly offers files in current folder:

![warp-user-completion](https://github.com/warpdotdev/Warp/assets/7923416/4d5a623b-2a0a-4f81-97d6-e94cdd560862)

Another terminal example.

![kitty-user-completion](https://github.com/warpdotdev/Warp/assets/7923416/e66de832-8637-4a52-8d3e-f83e15ead3d5)

### Operating system

Linux

### Operating system and version

Kubuntu 23.10

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

NA

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment] 2024-03-01 22:30
Marking as a duplicate of https://github.com/warpdotdev/Warp/issues/1811 for now. 

As an update: we are working on allowing users to define their own completion signatures, but we don't yet have an update of when that will be available.

**Closed by alokedesai** 2024-03-01 22:30 UTC
Labels: Bugs
