### ISSUE TITLE
Open prelaunch configuration in current window

### ISSUE THREAD

**Issue by LiranBri** [warpdotdev/Warp#4586] opened 2024-03-19 07:01 UTC
### Describe the solution you'd like?

When i open a prelaunch configuration, it's always opening a new Warp window.
I would like to have an ability to open it in the current alread-opened warp window.
moreover, there is no way for me to drag those opened tabs to merge between windows.

### Is your feature request related to a problem? Please describe.

I'm frustrated when warp forces me to work with many opened Warp windows, instead of single window and many tabs.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-19 21:54
Thanks for submitting this @LiranBri 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2490

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-19 21:54
Duplicate of https://github.com/warpdotdev/Warp/issues/2490

**Closed by dannyneira** 2024-03-19 21:54 UTC
Labels: Feature requests
