### ISSUE TITLE
Two line Starship prompt displaying as 1 line

### ISSUE THREAD

**Issue by 13zebras** [warpdotdev/Warp#3981] opened 2023-12-16 20:56 UTC
### Describe the bug

Upon initial setup of warp the dialog asks to choose existing prompt or Warp prompt. Warp is showing me a prompt that looks similar to my existing Starship prompt that I have configured and working in other terminals (Kitty, MacOS). However, the Starship prompt is displaying as 1 line instead of 2. Also, the current working directory is not displaying. 

After setup, while using warp, the Starship prompt is still displaying as 1 line, but warp has the command entry on the 2nd line. 

See screenshots.

### To reproduce

1. Launch warp.
2. Login.
3. Setup begins

### Expected behavior

See kitty screenshot. The Starship prompt is a 2 line prompt, and the terminal should take input immediately after the "lambda" symbol. 

### Screenshots

<img width="958" alt="warp-screenshot- 2023-12-16 at 2 39 37 PM" src="https://github.com/warpdotdev/Warp/assets/17152930/63e33a32-036e-45cb-aede-3c5f6b1ec95f">
<img width="1189" alt="kitty-screenshot- 2023-12-16 at 2 41 35 PM" src="https://github.com/warpdotdev/Warp/assets/17152930/20d40fca-b184-40ea-a50b-486c861a7272">

### Operating system

MacOS

### Operating system and version

Sonoma 14.2

### Shell Version

fish 3.6.2

### Current Warp version

v0.2023.12.12.08.02.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

recently installed and updated.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Advait-M** [comment] 2023-12-16 23:38
@13zebras thanks for reporting! As a note, part of this issue will be resolved by #2304 which we're currently working on adding support for!

However, separately from that, I do see that there seems to be a bug with both lines appearing on the same line from your screenshots. I just tried a Starship 2-line prompt config with Fish and I'm seeing this behavior, which is the expected current result:
![image](https://github.com/warpdotdev/Warp/assets/12927474/9fb5039e-a3a6-45be-a315-da2885d7dc82)

Could you please provide your `starship.toml` to help debug this further?

**Comment by 13zebras** [comment] 2023-12-17 05:25
> @13zebras thanks for reporting! As a note, part of this issue will be resolved by #2304 which we're currently working on adding support for! Feel free to 👍 that to indicate interest as well!

Glad to hear! I will have a look at that issue.
 
> Could you please provide your `starship.toml` to help debug this further?

Attached. Thanks for taking a look at this!
[starship.toml.zip](https://github.com/warpdotdev/Warp/files/13694835/starship.toml.zip)

**Comment by dannyneira** [comment] 2023-12-18 16:37
Hey @13zebras Thanks for submitting. Currently, the `line_break` setting is broken in the `fish` shell + starship prompt. Please [see our docs for more](https://docs.warp.dev/appearance/prompt#starship-settings), but the current workaround is to add the following to your config. 
```
[line_break]
disabled = true
```

**Comment by Advait-M** [comment] 2023-12-18 21:36
Thanks for the info @13zebras - yep, what Danny said 😄 ! 

As I mentioned, I believe #2304 will definitely solve part of your issue but maybe not the entire issue. However, I think the secondary issue might be fixed as a side-effect of the underlying implementation changes. We'll keep you updated on that issue thread!

**Comment by 13zebras** [comment] 2024-02-01 00:41
Hey Warp folks! One thought for you:  while I do love Starship, I'm not wedded to it. What I'm wedded to is INFORMATION in my terminal. I love the 2 line prompt because I can have a line of info and a line mostly free upon which to type sometimes very long commands with flags, etc. 

If Warp provided some of the same functionality as Starship, it would be a winner to use your prompt. Have you considered providing more than the limited things you offer in your prompt? Just a thought. Thanks!

**Comment by Advait-M** [comment] 2024-02-01 00:47
> Hey Warp folks! One thought for you: while I do love Starship, I'm not wedded to it. What I'm wedded to is INFORMATION in my terminal. I love the 2 line prompt because I can have a line of info and a line mostly free upon which to type sometimes very long commands with flags, etc.
> 
> If Warp provided some of the same functionality as Starship, it would be a winner to use your prompt. Have you considered providing more than the limited things you offer in your prompt? Just a thought. Thanks!

Thanks for the thoughts! Definitely agree with that!

We're actually working on expanding our collection of "context chips" over time! We recently added a Kubernetes context chip and an SVN context chip (similar to the Git one) is going to be added soon! 

I'm curious what context chips you particularly find helpful from Starship i.e. pieces of information? Can perhaps create an issue for each one of those and we can track interest with :+1: to prioritize it on our side!

Just to clarify - these are the current context chips we have:

![image](https://github.com/warpdotdev/Warp/assets/12927474/a599e6cd-a7ca-4faf-90de-b75a75e2b068)

**Comment by dannyneira** [comment] 2024-02-27 21:21
Thanks for submitting this @13zebras 

We already have a request tracking this over at #2304

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate. If you have any ideas for custom context chips in Warps prompt, please open a new feature request.

Thanks for your interest in Warp!

**Comment by dannyneira** [comment] 2024-02-27 21:21
Duplicate of #2304

**Closed by dannyneira** 2024-02-27 21:21 UTC
Labels: Bugs
