### ISSUE TITLE
Install Warp WSL2

### ISSUE THREAD

**Issue by aroldobossoni** [warpdotdev/Warp#5298] opened 2024-09-10 23:35 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

19:51:20 [INFO] Spawning terminal server process...
thread 'main' panicked at /home/runner/work/warp-internal/warp-internal/ui/src/windowing/winit/app.rs:167:14:
should be able to create event loop: Os(OsError { line: 81, file: "/home/runner/.cargo/git/checkouts/winit-3c8ffa8180ed95ae/fd5ff18/src/platform_impl/linux/wayland/event_loop/mod.rs", error: WaylandError(Connection(NoCompositor)) })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
19:51:20 [INFO] Received empty message; assuming the connection has been closed.

### To reproduce

sudo apt update && sudo apt upgrade
wget https://releases.warp.dev/stable/v0.2024.09.03.08.02.stable_03/warp-terminal_0.2024.09.03.08.02.stable.03_amd64.deb
sudo dpkg -i warp-terminal_0.2024.09.03.08.02.stable.03_amd64.deb
sudo apt --fix-broken install
export WARP_ENABLE_WAYLAND=1
export MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
WARP_ENABLE_WAYLAND=1 MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA warp-terminal

### Expected behavior

Versão do WSL: 2.2.4.0
Versão do kernel: 5.15.153.1-2
Versão do WSLg: 1.0.61
Versão do MSRDC: 1.2.5326
Versão do Direct3D: 1.611.1-81528511
Versão do DXCore: 10.0.26091.1-240325-1447.ge-release
Versão do Windows: 10.0.22631.4112

OS: Ubuntu 24.04.1 LTS on Windows 10 x86_64
Kernel: 5.15.153.1-microsoft-standard-WSL2
Packages: 684 (dpkg)
Shell: zsh 5.9
Theme: Adwaita [GTK3]
Icons: Adwaita [GTK3]
Terminal: Relay(719)
CPU: 12th Gen Intel i5-12450H (12) @ 2.495GHz
Memory: 491MiB / 7809MiB

sudo lshw -c video                                                                                                                                    ─╯
  *-display:0
       description: 3D controller
       product: Basic Render Driver
       vendor: Microsoft Corporation
       physical id: 3
       bus info: pci@ba85:00:00.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: bus_master cap_list
       configuration: driver=dxgkrnl latency=0
       resources: irq:0
  *-display:1
       description: 3D controller
       product: Basic Render Driver
       vendor: Microsoft Corporation
       physical id: 4
       bus info: pci@f423:00:00.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: bus_master cap_list
       configuration: driver=dxgkrnl latency=0
       resources: irq:0

Hardware:
Notebook Lenovo LOQ 15IRH8
CPU: Intel Core i5-12450H
GPU: NVIDIA GeForce RTX 2050, 4 GB GDDR6
RAM: 16 GB DDR5
Windows 11 Pro 22621.1.amd64fre.ni_release.220506-1250

### Operating system

Linux

### Operating system and version

Ubuntu 24.04.1

### Shell Version

zsh 5.9

### Current Warp version

0.2024.09.03.08.02.stable.03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

never

### Additional context

WARP_ENABLE_WAYLAND=1 MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-09-11 22:39
Hi @aroldobossoni thanks for submitting this. I wasn't able to reproduce the issue on my machine, but may have different GPU or other factors in play. We've added a list of workarounds which may be helpful here: https://docs.warp.dev/help/known-issues#linux-workarounds

Also, make sure to [download the latest version](https://warp.dev/linux-terminal) as we release fixes every week. https://docs.warp.dev/getting-started/changelog

Finally, we're tracking this issue over at #4240 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

Please let me know if any of those helped or if you still see the issue.

**Comment by dannyneira** [comment] 2024-09-17 20:04
Closing as duplicate of #4240  as we will be tracking WSL Support there.

**Closed by dannyneira** 2024-09-17 20:04 UTC
Labels: Bugs
