### ISSUE TITLE
Command Palette gets stuck when opening a new tab

### ISSUE THREAD

**Issue by kendallm** [warpdotdev/warp#38] opened 2021-07-20 22:29 UTC
**Describe the bug**
When the command palette is open and you create a new tab with the keyboard shortcut it remains stuck on the screen. 

**To Reproduce**
1. Start warp
2. Type `CMD+P` to open the command palette
3. Type `CMD+T` to open a new tab
4. Command palette is now stuck on the screen. Pressing `CMD+P` again does not put you back in the command palette.

**Expected behavior**
The command palette should close when opening a new tab.

**Screenshots**
![o](https://user-images.githubusercontent.com/1841529/126403213-932db166-cf69-484a-adb9-0dd7810a4f19.gif)

**Desktop (please complete the following information):**
 - MacOS 11.4

**Additional context**
I have been able to close the palette by switching back and forth between tabs randomly. It hasn't required me to close the app to fix, but is a bit more than a minor annoyance to get rid of.

**Comment by gagata** [comment] 2021-07-21 18:16
hey! thanks for the report, I think it's the duplicate of #29 - added it to our task list!

**Comment by zheng** [comment] 2021-07-26 19:52
This is fixed & released!

**Closed by zheng** 2021-07-26 19:52 UTC
Labels: bug
