### ISSUE TITLE
Grpcurl requests never complete

### ISSUE THREAD

**Issue by countingtoten** [warpdotdev/Warp#727] opened 2022-02-04 16:50 UTC
### Describe the bug

Using grpcurl installed via home-brew, none of the requests complete. Grpcurl will display the request being made. The response never completes. Retrying in the same tab never works. Opening a new tab and making the exact same request will complete. Any tabs that were open when the first request was made will never complete the request.

### To Reproduce

Steps to reproduce:
1. Open two tabs.
2. Make a grpcurl request to any service.
3. Observe the request hangs.
4. Switch to the other tab that is already open.
5. Make a grpcurl request to any service.
6. Observe the request hangs.
7. Open a new tab.
8. Make a grpcurl request to any service.
9. Observe the request completes successfully.

### Operating System

MacOS

### OS Version

12.2

**Comment by tiero** [comment] 2022-05-23 08:34
Same happens to me with `grpcurl`. Lost half of a day looking into infrastructure/server problems, instead was my terminal 🤦

**Comment by mrnonz** [comment] 2022-06-02 02:45
The latest version `v0.2022.05.30.09.10.stable_01` still hang.

Simple reproduce

```bash
go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
grpcurl \
    -d '{"sentence": "I feel happy."}' \
    demo.connect.build:443 \
    buf.connect.demo.eliza.v1.ElizaService/Say
```

Hang..

**Comment by mrnonz** [comment] 2022-07-06 04:32
Can we find solid solution for this?

**Comment by elviskahoro** [comment] 2022-07-07 19:30
I think we have someone looking at this now actually!

**Comment by alokedesai** [comment] 2022-08-09 15:52
Closing this one out since we fixed it last week. Feel free to reopen if you are still experiencing it!

**Closed** 2022-08-10 14:07 UTC

**Comment by mrnonz** [comment] 2022-08-10 14:46
Yeah, It's work fine on `v0.2022.08.01.09.12.stable_02` !
