### ISSUE TITLE
Unwanted newline between prompt and command output in Warp terminal

### ISSUE THREAD

**Issue by ryoryotaro** [warpdotdev/Warp#4766] opened 2024-04-16 16:02 UTC
### Describe the bug

An unwanted newline is automatically inserted between the terminal prompt and command output. Normally, after entering a command, its output is expected to appear directly below the prompt. However, the current behavior inserts an empty line between the prompt and the output, which I find inconvenient. When I launch zsh via the terminal in VScode, this issue does not occur.

### To reproduce

1.     Open the Warp terminal.
2. Execute any command (for example: ls, date).
3. An empty line is inserted before the command output is displayed.

### Expected behavior

When executing commands in the terminal, the output should appear immediately below the prompt without any intervening empty lines. This ensures a compact and efficient display of information, facilitating quicker reading and interpretation of command results. In other environments, such as the terminal in VScode using zsh, this is the standard behavior, where no additional newline is inserted between the prompt and the command output.

### Screenshots

In Warp term
![スクリーンショット 2024-04-17 1 00 18](https://github.com/warpdotdev/Warp/assets/16929973/7d289fe8-1279-48ca-a301-e9906cf601ab)
inal

In VSCode terminal
![スクリーンショット 2024-04-17 0 59 43](https://github.com/warpdotdev/Warp/assets/16929973/ecb3041b-2668-4a37-afa9-4c392dac7fdc)

### Operating system

MacOS

### Operating system and version

Sonoma 14.4.1

### Shell Version

zsh 5.9 (arm-apple-darwin23.0.0)

### Current Warp version

v0.2024.04.09.08.01.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Advait-M** [comment] 2024-04-16 16:07
Hey @ryoryotaro ! Thanks for raising! I'm actually actively working on this and we hope to release this soon 😄 - you can follow along for updates in #2304. If interested, some of the technical complexity involved here is outlined here: https://github.com/warpdotdev/Warp/issues/2304#issuecomment-1907563006

(for GitHub label) Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Closed** 2024-04-16 16:07 UTC
Labels: Bugs

**Comment by dannyneira** [comment] 2024-04-16 16:09
Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Comment by Advait-M** [comment] 2024-04-17 00:57
> Thank you so much for the quick response and for actively working on this issue! I'm really grateful for the effort and am looking forward to the upcoming fix. Also, thanks for sharing the details in #2304—it's incredibly helpful to understand the technical complexities involved. Keep up the great work!

Thank you for the kind words 😄 ! Haha yes, it's been quite a journey to rework the internals behind-the-scenes to get this working 😅, but we're close hopefully!
