### ISSUE TITLE
Taskfile autocompletion support

### ISSUE THREAD

**Issue by pbourdet** [warpdotdev/Warp#1688] opened 2022-08-05 14:10 UTC
### Describe the solution you'd like?

```text
It would be nice for project using taskfiles (https://taskfile.dev/) to have autocompletion like makefile
```

### Is your feature request related to a problem? Please describe.

Not a problem but a slight inconvenience

### How important is this feature to you?

3

**Comment by sheldonhull** [comment] 2022-08-09 16:49
@pbourdet i think this is more a function of Taskfile than warp, unless I'm missing something. 

Take a look here: https://github.com/sawadashota/go-task-completions
You'd set this in your profile and completions should work from there. That's a function of the autocomplete suggestions with zsh/bash and I don't think has anything to do with the terminal.

**Comment by elviskahoro** [comment] 2022-08-13 23:43
Warp by design, does not leverage the shell's completions. The plan is top have an open source spec that people can contribute to. Currently we bootstrap off of Fig's completion specs. These are in the process of being updated but I'm not sure if this will include the tool you're requesting.

The updated specs should be coming out over the next few weeks. Gonna close this in favor of this discussion: #434

**Closed by elviskahoro** 2022-08-13 23:43 UTC
