### ISSUE TITLE
Allow Full Scroll-back / setting the number of max lines

### ISSUE THREAD

**Issue by obie** [warpdotdev/Warp#5505] opened 2024-11-23 00:23 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

The lack of full-scroll back or at least being able to set the lines retained in buffer much higher is disastrous and forcing me to go back to iTerm2. I'm aware that there is an old locked issue pertaining to this problem, but it has not seen any significant activity or progress this year despite the team's promises to ship a solution in 2024. Well, we're almost at the end of 2024. At least give us an update about why this feature is such a big problem and/or let us enable it and deal with the memory issues ourselves.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-11-25 16:50
Duplicate of #610

**Closed by dannyneira** 2024-11-25 16:50 UTC
Labels: Feature requests

**Comment by obie** [comment] 2024-11-25 17:01
610 is locked so can’t be upvoted. You should unlock it

__



Obie Fernandez
obiefernandez.com
Electronic Music Producer, DJ,
Author, Consultant, Entrepreneur

+1 404 934 9201 US / WhatsApp

Book a meeting with me on Calendly
Listen to my music on Spotify

**Comment by dannyneira** [comment] 2024-11-25 19:40
thanks unlocked, will lock it again if the comments get too spicy
