### ISSUE TITLE
Horizontal scroll/no word wrap for wide output

### ISSUE THREAD

**Issue by tomasz-sroka** [warpdotdev/Warp#2158] opened 2022-11-17 09:44 UTC
### Describe the solution you'd like?

```text
Hi Warp Team
It would be great to have a horizontal scroll integrated with the warp terminal. As far as I can see whenever there is a very wide output, warp by default wraps the line. It'd be great to have something like a horizontal scroll rather than line wrapping.
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment] 2022-11-17 23:05
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by tomasz-sroka** [comment] 2022-12-07 21:43
Please have a look at https://github.com/software-jessies-org/jessies/wiki/Terminator.
As per the Terminator feature description:
Horizontal Scrolling - Most terminal emulators wrap text when it intrudes upon the right margin. Terminator doesn't --- it instead provides a horizontal scrollbar when necessary (hold down shift to make your scroll wheel scroll horizontally). This brings clear benefits in terms of readability of program output, or text files sent to the display with cat(1).

**Comment by dannyneira** [comment] 2024-03-06 21:16
Hi folks, we have a request tracking this over at https://github.com/warpdotdev/Warp/issues/4008

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-06 21:16
Duplicate of https://github.com/warpdotdev/Warp/issues/4008

**Closed by dannyneira** 2024-03-06 21:16 UTC
Labels: Feature requests
