### ISSUE TITLE
Warp crashes a number of times

### ISSUE THREAD

**Issue by tonyltf** [warpdotdev/Warp#4440] opened 2024-03-02 02:04 UTC
### Discord username (optional)

tonyttff#8644

### Describe the bug

Warp terminal "random" crashes / closed itself, it does not limited to what I am doing

### To reproduce

I don't have exact steps

### Operating system

Linux

### Operating system and version

PopOS 22.04

### Shell Version

zsh 5.8.1

### Current Warp version

v0.2024.02.27.08.01.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8188 MB
    Total available memory: 8188 MB
    Currently available dedicated video memory: 7088 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 550.54.14
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 550.54.14
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 550.54.14
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-02 04:47
Hey @tonyltf thanks for letting us know. Sorry to hear about this blocker. This may have to do with the Nvidia drivers so make sure those are up to date and the latest available. Also update Xorg and see if that helps, finally download the latest version released yesterday at https://warp.dev/linux-terminal and let us know if the issue persists.

**Comment by alokedesai** [comment] 2024-03-04 21:21
Hey @tonyltf, sorry for the issues here. This is due to an issue with a Rust crate we depend on that is segfaulting. We're actively working on a fix and should have it released shortly.

**Comment by alokedesai** [comment] 2024-03-04 21:23
Marking as a duplicate of https://github.com/warpdotdev/Warp/issues/4428

**Closed by alokedesai** 2024-03-04 21:23 UTC
Labels: Bugs, Platform > Linux, GitHub - User reported - GHUR
