### ISSUE TITLE
Clear doesn't work

### ISSUE THREAD

**Issue by vicyyn** [warpdotdev/Warp#687] opened 2022-01-27 12:52 UTC
### Describe the bug

```shell
Machine : Mac m1 pro
```

### To Reproduce

type `clear`

### Expected behaviour

```shell
Clears the terminal
```

### Screenshots

![image](https://user-images.githubusercontent.com/55297234/151362340-58ad180b-ee9c-40e6-b706-2ecebc251fde.png)

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment] 2022-01-28 05:26
Can you send a video?

**Comment by vicyyn** [comment] 2022-01-31 13:17
Uploading Screen Recording 2022-01-31 at 2.15.13 PM.mov…

**Comment by vicyyn** [comment] 2022-01-31 13:18
https://user-images.githubusercontent.com/55297234/151800347-e6b51ccf-6591-431d-be8d-6941d61a31bb.mov

**Comment by elviskahoro** [comment] 2022-02-01 05:26
What does pressing CTRL-L do in your Warp?
Which shell are you using?
Does this happen when you have clean dotfiles?
You can quickly set up clean configs by putting ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs.

**Comment by vicyyn** [comment] 2022-02-01 09:20
ctrl-l works, it clears the terminal
I am using bash

**Comment by elviskahoro** [comment] 2022-04-15 08:18
Duplicate of #008

**Closed by elviskahoro** 2022-04-15 08:18 UTC
