### ISSUE TITLE
Render images in Markdown View

### ISSUE THREAD

**Issue by brucevoin** [warpdotdev/Warp#4002] opened 2023-12-27 03:32 UTC
### Describe the bug

Markdown View doesn't render image

### To reproduce

like this :

![[The principles of  design computer system.png]]

### Operating system

MacOS

### Operating system and version

12.7.2

### Current Warp version

v0.2023.12.19.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2023-12-27 22:59
Thanks for letting us know, given image support is still not in Warp, I'll mark this as a feature request to support images in MD files. There is also a related request tracking support for images in general here: https://github.com/warpdotdev/Warp/issues/26

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-06-14 15:54
Duplicate of #26

**Closed by dannyneira** 2024-06-14 15:54 UTC
Labels: Feature requests
