### ISSUE TITLE
Bug with spaceship prompt theme at v0.2024.01.09.08.02.stable_01

### ISSUE THREAD

**Issue by lgcmotta** [warpdotdev/Warp#4063] opened 2024-01-12 14:53 UTC
### Describe the bug

Since version `v0.2024.01.09.08.02.stable_01` warp starts to add 4 extra lines on the spaceship prompt and one ghost line prompt at the top

The `.zshrc` file has `SPACESHIP_PROMPT_ASYNC` set to `false`:

```.zshrc
SPACESHIP_PROMPT_ASYNC=false
SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "
```

### To reproduce

- Use spaceshipt with `SPACESHIP_PROMPT_ASYNC` set to false
- Bump Warp to version `v0.2024.01.09.08.02.stable_01`

### Expected behavior

Expected to see one single line promp 

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/33238105/888ef05a-c702-407e-b8f6-d80ffa09a843)

### Operating system

MacOS

### Operating system and version

MacOS Sonoma 14.1.2

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.01.09.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Jan, 11th 2024

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dgonzalezr** [comment] 2024-01-12 16:02
I can confirm the issue, I just upgraded and boom 💥 , there is 😕 

https://github.com/warpdotdev/Warp/assets/328492/e602f847-a4bb-45dd-a901-0b1d0002a80e

**Comment by dannyneira** [comment] 2024-01-12 17:28
Hey Folks, thanks for letting us know. We'll be tracking this issue on #4057 going forward and are actively working on reverting the change that may have caused the prompt to repeat. We'll post updates on the parent issue above.

**Comment by dannyneira** [comment] 2024-01-12 17:28
Duplicate of #4057

**Closed by dannyneira** 2024-01-12 17:28 UTC
Labels: Bug

**Comment by dannyneira** [comment] 2024-01-12 18:46
hey Folks, Warp version `v0.2024.01.09.08.02.stable_02` has been released which reverts the change that caused this regression. Please update and stay tuned for the fix.

**Comment by lgcmotta** [comment] 2024-01-12 19:12
hey @dannyneira thank you so much!
