### ISSUE TITLE
Support for fontLinguatures

### ISSUE THREAD

**Issue by sanibalakrishna** [warpdotdev/Warp#4657] opened 2024-03-29 05:01 UTC
### Discord username (optional)

sanibalakrishna

### Describe the solution you'd like?

Add support for the fontLinguatues if some one is using vim in the wrap like ->,=> etc...

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-29 15:54
Thanks for submitting this @sanibalakrishna we already have a request tracking this over at #239 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-29 15:54
Duplicate of #239

**Closed by dannyneira** 2024-03-29 15:54 UTC
Labels: Feature requests
