### ISSUE TITLE
Ability to disable Warp AI (or configure which character triggers Warp AI)

### ISSUE THREAD

**Issue by vrutberg** [warpdotdev/Warp#4080] opened 2024-01-17 09:16 UTC
### Describe the solution you'd like?

I would like the ability to either disable Warp AI completely, or configure which character triggers it. 

### Is your feature request related to a problem? Please describe.

I have a workflow where I want to use the pound/hash sign (#) as the first character of my terminal commands, this clashes with the Warp AI feature (which I don't use).

For reference, this is my workflow:

1. I enter a terminal command in the command input window
2. I realize I want to do something else first
3. I go to the beginning of the line (Ctrl+A), and enter a pound/hash sign (#) and press enter. This way, I basically input a comment, which will do nothing.
4. I do the thing I wanted to do
5. I use history search (Ctrl+R) or the arrow keys to get back to my commented-out command
6. I delete the pound/hash sign, and run the command

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-17 18:04
Hey @vrutberg Thanks for submitting this. There isn't option to disable or change the keybind for Warp AI Command suggestions at this time, but as a workaround, you can press `ESC` after `#` to cancel the Warp AI search. That being said, we have a request tracking this here. https://github.com/warpdotdev/Warp/issues/2227

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-17 18:04
Duplicate of https://github.com/warpdotdev/Warp/issues/2227

**Comment by vrutberg** [comment] 2024-01-17 18:45
Hey @dannyneira, thanks for responding. Oh crap, I thought I searched properly before creating this issue. Apparently I didn't. :-) I'll be sure to do that!

Regarding your workaround, that's exactly what I do now. While it works, but it's a small annoyance to have to press Esc every time I do this (if there ever was a 1st world problem...).

**Closed** 2024-01-18 16:05 UTC
Labels: Feature
