### ISSUE TITLE
kubectl --context Auto-Completion Not Working with Zsh

### ISSUE THREAD

**Issue by navesim** [warpdotdev/Warp#5382] opened 2024-10-15 09:04 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When using the Warp terminal with kubectl and the --context flag, the auto-completion feature does not work for Kubernetes contexts when pressing TAB. This behavior is specific to the Warp terminal. The same kubectl command auto-completes contexts successfully in the default terminal (also running Zsh). Notably, in Warp, auto-completion works correctly for Kubernetes resources, just not for contexts.

### To reproduce

1. Open Warp terminal with Zsh.
2. Run a kubectl command with the --context flag.
3. Press TAB to auto-complete the available contexts.
4. Notice that no auto-completion occurs for the context, though resource completion works as expected.

### Operating system

MacOS

### Operating system and version

Darwin Kernel Version 23.6.0

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

v0.2024.10.08.08.02.stable_02

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-10-15 23:27
Hi @navesim Thanks for submitting. This is a known issue since Warp currently doesn't support shell based auto-completion's, like the one for kubectl commands. In order to enable the features in Warp, we've build a wrapper around the shell and so had to build our own completion specs. We are tracking support for shell based completions here https://github.com/warpdotdev/Warp/discussions/434

Also this has been reported before and we are tracking it here. https://github.com/warpdotdev/Warp/issues/5186

Closing as a duplicate

**Comment by dannyneira** [comment] 2024-10-15 23:27
Duplicate of https://github.com/warpdotdev/Warp/issues/5186

**Closed by dannyneira** 2024-10-15 23:27 UTC
Labels: Bugs
