### ISSUE TITLE
Terminal in tab is broken after ssh disconnected or killed

### ISSUE THREAD

**Issue by nan0desu** [warpdotdev/Warp#2476] opened 2023-01-11 20:03 UTC
### Discord username (optional)

nanodesu#0206

### Describe the bug

SSH wrapper is off. After disconnecting ssh with certain commands terminal left in broken state, in which "reset" does not work. May be similar with #2475 

### To Reproduce

1. Open a new tab
2. Run ssh to Linux host
3. Execute something interactive what affects terminal, e.g. "watch"
4. Kill the ssh client process or make it disconnect with timeout (turn off wi-fi for example) 
5. Now the tab is broken, there are no prompt. "clear" does nothing and "reset" just clears the screen

### Expected behaviour

Hope to have a working terminal with command history and prompt, or at least recoverable to such state with "reset" command.

### Screenshots

<img width="1292" alt="Screenshot 2023-01-11 at 21 47 07" src="https://user-images.githubusercontent.com/1218842/211905787-5f1bd661-9c69-4dce-ad90-c9ea14d6352d.png">

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.03.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment] 2023-01-11 20:21
@nan0desu You're correct. Our SSH management needs some improvement. Sorry about this!

**Comment by metalbreeze** [comment] 2023-07-13 03:09
similar issue.
after ssh connection was killed.
![image](https://github.com/warpdotdev/Warp/assets/12639549/fabf61d6-1be7-4db9-909f-b6c8d8cdd576)
warp version v0.2023.07.04.08.03.stable_02
but my default shell is bash.

1. Open a new tab
2. Run ssh to Linux host (some linux servers work perfect, but other linux servers  met issue. )
3. Kill the ssh client process or make it disconnect with timeout (turn off wi-fi for example)

**Comment by ellerychan** [comment] 2023-09-21 13:55
I experience the same issue with `00~`...`01~` surrounding every command I enter after an ssh disconnect.  Also using bash.

**Comment by swinis** [comment] 2024-01-10 17:17
Same for me on v0.2024.01.02.08.02.stable_02
Thanks in advance for fixing.

**Comment by dataslayermedia** [comment] 2024-01-23 10:59
Also seeing this issue every time I reboot my Raspberry Pi I need to manually exit and restart Warp which messes with my mac work spaces... 
<img width="538" alt="issue" src="https://github.com/warpdotdev/Warp/assets/731746/2e18cc31-5bc7-4520-8915-40b37e25e94e">

**Comment by Ash-Stuart** [comment] 2024-04-03 09:14
Can this bug be prioritized please? This is a very basic daily blocker, not sure why it's still not been looked into more than a year after?

Thanks.
<img width="362" alt="image" src="https://github.com/warpdotdev/Warp/assets/132663269/ca5da147-c22d-4a19-8970-87c46a4a16e8">

**Comment by Ash-Stuart** [comment] 2024-04-09 08:42
Please can we prioritize this @elviskahoro

**Comment by therohan21** [comment] 2024-04-21 17:08
+1 Facing the same issue. This happens after a remote connection is disconnected and been idle for a while.
![Screenshot 2024-04-21 at 8 55 21 AM](https://github.com/warpdotdev/Warp/assets/46622522/dba410e2-e789-4475-a2d4-3958de5826f5)

**Comment by dannyneira** [comment] 2024-05-23 15:42
Hi Folks, we'll be tracking remote connection management in Warp for SSH here. https://github.com/warpdotdev/Warp/discussions/442

Please continue to track and subscribe to that request for updates.

**Comment by dannyneira** [comment] 2024-05-23 15:42
Duplicate of https://github.com/warpdotdev/Warp/discussions/442

**Closed by dannyneira** 2024-05-23 15:42 UTC
Labels: Bugs, SSH
