### ISSUE TITLE
Double click not able to select word between « and » characters

### ISSUE THREAD

**Issue by crisguitar** [warpdotdev/Warp#3720] opened 2023-10-03 09:38 UTC
### Describe the bug

In Catalan, `«` and `»` are used instad of `'` to highlight an important word. I use git in Catalan and can't select many commands, branch names and other important words because of this limitation. This works fine in other terminals like iTerm.

Warp:
![Captura de pantalla 2023-10-02 a les 19 44 42](https://github.com/warpdotdev/Warp/assets/2355302/4e06b637-96dc-4cfa-a6b7-d3db8f66cea6)

iTerm:
![Captura de pantalla 2023-10-03 a les 11 36 25](https://github.com/warpdotdev/Warp/assets/2355302/2d7d0824-198c-4b7b-b7af-ef5234d8a217)

### To reproduce

1. `echo "«origin/main»"`
2. double click the word origin
3. warp selects `«origin/mai`

### Expected behavior

`origin/master` is selected

### Operating system

MacOS

### Operating system and version

13.5.2

### Shell Version

fish, version 3.5.1

### Current Warp version

v0.2023.09.26.08.09.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-10-03 16:41
Hi @crisguitar Thanks for letting us know. I was able to reproduce this issue, as a workaround, you can select the text with the mouse instead of double-clicking. We'll post any updates on this thread.

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2023-11-21 16:24
@crisguitar We've added some improvements to the double-click selection, Please test and let us know if that helps with your issue.

**Comment by crisguitar** [comment] 2023-11-22 10:22
Hey @dannyneira, thanks for the update. I tested in version `v0.2023.11.14.08.02.stable_02`  and unfortunately I still have the issue 😞. It is a bit better because now it selects until the end of the word `main` but the character `«` should not be selected.
![imatge](https://github.com/warpdotdev/Warp/assets/2355302/dd05f6b2-9378-44c3-9385-e75a2276ac44)

**Comment by dannyneira** [comment] 2023-11-22 13:44
Heard, it's being worked on, no firm eta on the release but we'll post further updates on this thread.

**Comment by crisguitar** [comment] 2023-12-18 14:36
hey @dannyneira, it looks like this has been fixed. Not sure exactly when but I am using `v0.2023.12.12.08.02.stable_04` and it works perfectly.

**Comment by dannyneira** [comment] 2023-12-18 15:37
Awesome! Closing but please let us know if the issue is persistent.

**Closed by dannyneira** 2023-12-18 15:37 UTC
Labels: Bug
