### ISSUE TITLE
Add an option to disable text wrapping.

### ISSUE THREAD

**Issue by david9991** [warpdotdev/Warp#3420] opened 2023-07-26 03:10 UTC
### Describe the solution you'd like?

```Text
Add an option to disable text wrapping.
```

### Is your feature request related to a problem? Please describe.

```Text
Tabular text and long text look awful with text wrapping enabled.
```

### Additional context

<img width="1105" alt="Screenshot 2023-07-26 at 11 03 04" src="https://github.com/warpdotdev/Warp/assets/123219/504550e9-3455-4ca9-9378-152378404279">

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-07-26 17:29
Thanks for this feature request @david9991!

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-03-06 21:15
We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/4008

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-06 21:16
Duplicate of https://github.com/warpdotdev/Warp/issues/4008

**Closed by dannyneira** 2024-03-06 21:16 UTC
Labels: Feature requests
