### ISSUE TITLE
enbable proxy in setting 

### ISSUE THREAD

**Issue by edisonX-sudo** [warpdotdev/Warp#4884] opened 2024-05-07 06:51 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

forwarding req via proxy like codes below do
export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-07 17:43
Thanks for submitting this @edisonX-sudo 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/705

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-07 17:43
Duplicate of https://github.com/warpdotdev/Warp/issues/705

**Closed by dannyneira** 2024-05-07 17:43 UTC
Labels: Feature requests
