### ISSUE TITLE
Enabling macOS's "Full Keyboard Access" breaks the space bar 

### ISSUE THREAD

**Issue by dvdplm** [warpdotdev/Warp#5358] opened 2024-10-04 07:03 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When the "Full Keyboard Access" is enabled in Sequoia 15.0.0 and. Sequoia 15.0.1, the space bar no longer work in Warp. Rendering is also broken: "Full Keyboard Access" highlights the current UI element and when switching to Warp the highlight is still drawn on top of Warp.

### To reproduce

1. Go to macOS settings
2. Search for "Full Keyboard Access" and enable it
3. Switch to Warp
4. Notice how the space bar no longer works
5. Notice the rendering artifacts  from the previous window is now drawn on top of Warp's window

### Screenshots

![image](https://github.com/user-attachments/assets/da039cc1-65f0-4b67-95f8-c9791104adc3)

### Operating system

MacOS

### Operating system and version

Sequoia 15

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

The problem is also present with WezTerminal. Not present with iTerm2 or Apple Terminal.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-10-04 21:59
Hi Folks, we'll be tracking this issue here https://github.com/warpdotdev/Warp/issues/2734 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-10-04 21:59
Duplicate of https://github.com/warpdotdev/Warp/issues/2734

**Closed by dannyneira** 2024-10-04 21:59 UTC
Labels: Bugs
