### ISSUE TITLE
Preview pane

### ISSUE THREAD

**Issue by Integralist** [warpdotdev/Warp#2664] opened 2023-02-17 10:41 UTC
### Describe the solution you'd like?

The Zellij multiplexer https://zellij.dev/ has an awesome feature I use _a lot_ which is their 'preview pane'. It's a floating terminal pane that sits above any other split panes. It's something you can toggle on/off and create multiple instances of (although just a single instance that can be toggled is really what I'm after).

### Is your feature request related to a problem? Please describe.

The reason I like having a preview pane is for all sorts of things that are related to a task that I'm working on. 

Typically my main terminal pane will contain Neovim with project code I'm working on, and I like to toggle open a floating preview pane so that I can run tests in the background, or do some git commands etc and then toggle it off again and be straight back at my code.

I appreciate that you can sort of get a similar workflow with a split pane and then you maximize your code editor pane, but I frequently like to have multiple panes open and still have a floating preview pane that sits on top of the other panes that I can quickly toggle on/off.

### Additional context

I've marked this as "can't work without it" because I literally do LOVE this feature from Zellij and it's a game changer for my workflow productivity. I appreciate not everyone will feel as strongly about it 🙂 

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-02-17 18:37
Thanks for submitting this @Integralist, We'll post any updates on this thread.

In the meantime, we have a couple of features that may help with your use case, in particular, the hotkey window ( a separate Warp window that can pop-up over existing Warp windows ) https://docs.warp.dev/features/windows/hotkey-window

We also have normal split panes. https://docs.warp.dev/features/windows/split-panes

**Comment by dannyneira** [comment] 2024-02-28 18:33
Closing as duplicate of https://github.com/warpdotdev/Warp/issues/3935, which is a request for Zellij support.

**Closed** 2024-02-28 18:33 UTC
Labels: Feature requests
