### ISSUE TITLE
(Regression) Warp duplicating custom prompt on latest stable

### ISSUE THREAD

**Issue by GregoryConrad** [warpdotdev/Warp#4057] opened 2024-01-11 23:46 UTC
### Describe the bug

Just updated to the latest stable, and my shell prompt is getting duplicated several times. This did not happen on the previous stable release.

Side question: how can I rollback my warp client to the previous release?

### To reproduce

Use a custom prompt in zsh. At least, mine is causing this duplication issue:
https://github.com/GregoryConrad/dotfiles/blob/master/.zshrc

### Expected behavior

Prompt not being duplicated as it is shown below.

### Screenshots

![Screenshot 2024-01-11 at 6 41 34 PM](https://github.com/warpdotdev/Warp/assets/15874617/55267806-a39e-41f0-a62a-b429a6d705d8)

### Operating system

MacOS

### Operating system and version

macOS 14.2.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.01.09.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Few days ago, before this most recent update

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by pereirinha** [comment] 2024-01-12 00:23
Same here.

**Comment by luis-neira** [comment] 2024-01-12 04:34
Same. Any recommendations.

**Comment by verheyenkoen** [comment] 2024-01-12 09:58
Same issue since latest update.

**Comment by jeffdesign** [comment] 2024-01-12 10:45
Same here

**Comment by kcculhwch** [comment] 2024-01-12 12:53
Seeing the same thing on my terminal too. (using oh-my-posh)

**Comment by dannyneira** [comment] 2024-01-12 17:22
Hey folks, we're aware of this issue and are working to revert the change that may have caused this. It primarily looks to be affecting custom prompts, not the Warp prompt. 

We'll post any further updates on this thread.

**Comment by dannyneira** [comment] 2024-01-12 18:45
hey Folks, Warp version `v0.2024.01.09.08.02.stable_02` has been released which reverts the change that caused this regression. Please update and stay tuned for the fix.

**Comment by verheyenkoen** [comment] 2024-01-12 19:01
@dannyneira Brilliant! Thanks.

**Comment by yousecjoe** [comment] 2024-01-13 16:27
I updated it to v0.2024.01.09.08.02.stable_02, and the issue is fixed. 
Thanks for fixing it so fast!

**Comment by dannyneira** [comment] 2024-01-18 23:36
Nice! closing as resolved

**Closed by dannyneira** 2024-01-18 23:36 UTC
Labels: Bug
