### ISSUE TITLE
Exporting Session Logs

### ISSUE THREAD

**Issue by ishmam999** [warpdotdev/Warp#4198] opened 2024-02-20 03:06 UTC
### Describe the solution you'd like?

I believe one of the mandatory feature that a terminal should have is to save the session logs.

### Additional context

The feature should also contain saving the logs in different file types. 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-20 23:43
Thanks for this feature request @ishmam999! As a possible stopgap, you can run any command you want to save and pipe into `tee` to save the output `echo hello | tee <filename>`.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-07-03 22:24
Hey folks, closing in favor of https://github.com/warpdotdev/Warp/issues/2394

**Comment by dannyneira** [comment] 2024-07-03 22:24
Duplicate of https://github.com/warpdotdev/Warp/issues/2394

**Closed by dannyneira** 2024-07-03 22:24 UTC
Labels: Feature requests
