### ISSUE TITLE
Disabling automatic updates and update reporting in Warp Essentials

### ISSUE THREAD

**Issue by drewdsaur** [warpdotdev/Warp#4119] opened 2024-02-01 22:25 UTC
### Describe the solution you'd like?

I would like the ability to disable update notifications. I would also like the ability to disable Warp Essentials from automatically appearing after an update.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-02 22:50
Thanks for submitting this @

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1991

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-02 22:50
Duplicate of #1991

**Closed by dannyneira** 2024-02-02 22:50 UTC
Labels: Feature

**Comment by drewdsaur** [comment] 2024-02-03 01:15
Perfect. Thanks. I had been using the web form to request this on your website 2 or 3 times in the past 6 months and nobody responded even once so I suspected nobody cared but at least I found the people who do. Thanks!

Drew


--
Drew D. Saur
Adjunct Faculty
RIT Department of Software Engineering
585-281-0014 (cell)
https://www.rit.edu/computing/directory/ddsvse-drew-saur


On Feb 2, 2024, at 5:50 PM, Danny Neira ***@***.***> wrote:



Thanks for submitting this @drewdsaur<https://github.com/drewdsaur>!

We already have a request tracking this over at #1991<https://github.com/warpdotdev/Warp/issues/1991>

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.
