### ISSUE TITLE
When using git, you will get a sed: RE error: an illegal byte sequence error in the Chinese context

### ISSUE THREAD

**Issue by PandaLIU-1111** [warpdotdev/Warp#4601] opened 2024-03-20 10:27 UTC
### Describe the bug

When using git, you will get a sed: RE error: an illegal byte sequence error in the Chinese context

<img width="630" alt="image" src="https://github.com/warpdotdev/Warp/assets/26201936/ed7ee1c9-2ff2-4313-8392-60fbaa7383ff">

Repeat step：

```shell
mkdir ~/test

git init

git checkout -b saas-feat-公
```

### To reproduce

When using git, you will get a sed: RE error: an illegal byte sequence error in the Chinese context

<img width="630" alt="image" src="https://github.com/warpdotdev/Warp/assets/26201936/ed7ee1c9-2ff2-4313-8392-60fbaa7383ff">

### Expected behavior

sed: RE error: an illegal byte sequence does not appear

### Screenshots

<img width="815" alt="image" src="https://github.com/warpdotdev/Warp/assets/26201936/872bfc46-59d0-4d50-9065-fb6f76eac60f">

### Operating system

MacOS

### Operating system and version

Apple M1 Max 14.1.1 (23B81)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0) 

### Current Warp version

v0.2024.03.12.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment] 2024-03-20 16:16
Hi @PandaLIU-1111 thanks for reporting. It looks like this is another instance of #1431. We'll take another look.

**Comment by dannyneira** [comment] 2024-03-20 16:37
Duplicate of #1431

**Closed by dannyneira** 2024-03-20 16:37 UTC
Labels: Bugs

**Comment by acarl005** [comment] 2024-03-20 17:03
@PandaLIU-1111 Can you run the `locale` command in Warp and also another terminal and post the output? The issue is likely that Warp failed to determine your system's locale.

**Comment by PandaLIU-1111** [comment] 2024-03-21 01:53
> @PandaLIU-1111 Can you run the `locale` command in Warp and also another terminal and post the output? The issue is likely that Warp failed to determine your system's locale.您可以在 Warp 和另一个终端中运行该 `locale` 命令并发布输出吗？问题可能是 Warp 无法确定系统的区域设置。

<img width="403" alt="image" src="https://github.com/warpdotdev/Warp/assets/26201936/900aadcf-4bd1-4e89-a7fb-0bd0b057f34e">
