### ISSUE TITLE
SSH RemoteCommand

### ISSUE THREAD

**Issue by ghost** [warpdotdev/Warp#4941] opened 2024-05-22 12:07 UTC
### Dupe Check

- [X] I have [searched Warp SSH issues](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ASSH) and there are no duplicates

### Operating System

MacOS

### Operating System and Version

14.4.1

### Local Shell Version

5.9

### Remote Shell Version

5.9

### Warp Version

v0.2024.05.14.08.01.stable_04

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/38129911/13868dd8-ca29-455b-83e7-df99a17b191f)
"Remote Command cd /path" doesn't work for the ssh connection, but the navite terminal does.

### Include shell xtrace output

"Remote Command cd /path" doesn't work for the ssh connection, but the navite terminal does.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2024-05-22 21:04
Hi @TristanSurGithub sorry about this blocker. A similar issue has been reported in the past which we are tracking here. https://github.com/warpdotdev/Warp/issues/1171

Warp has an SSH Wrapper that enables features (like the blocks, prompt, completions, etc.) on remote machines requiring the default prompt on the remote machine to be either `bash` or `zsh`, but it has some known limitations you're seeing now.

As a workaround you can add `command ssh` to your `Settings > Subshells > Added commands` menu, then run `command ssh <user@server>` to connect to remote session, this will attempt to enable Warp features as a subshell.

You can also try disabling the SSH Wrapper by navigating to `Settings > Features`. Blocks will stop working but with it disabling, SSH should work as normal.

Related docs:
https://docs.warp.dev/features/ssh
https://docs.warp.dev/features/subshells

If those don't work, please let us know.

**Comment by dannyneira** [comment] 2024-05-22 21:04
Duplicate of #1711

**Closed as completed by dannyneira** 2024-05-22 21:04 UTC
Labels: bug, SSH
