### ISSUE TITLE
Dropped ssh->tmux session permanently loses local block and prompt

### ISSUE THREAD

**Issue by sdorr0** [warpdotdev/Warp#1798] opened 2022-09-03 00:08 UTC
### Discord username (optional)

myrddin#4194

### Describe the bug

If I'm ssh'd to a remote host, using tmux, and then have an ungraceful drop of connection (e.g., loss of LAN/WAN connection), Warp loses it's block context (ie. it doesn't appear to be in a block anymore, and I can't seem to restore it to that state) and all I have to interact with is a lone cursor on the far left of the screen.  The prompt is missing.  I can issue shell commands as normal, but no context, no block, no prompt.

### To Reproduce

1. ssh to remote host
2. attach to a tmux session (eg. `tmux`, `tmux a -d`, etc)
3. kill the connection (shut off wifi, use the `<enter>~.` key combo, etc)
4. you are now back in your shell on your local machine
5. be sad that you've lost your prompt, block, etc :(

### Expected behaviour

I would expect when returning to the shell on my local machine to have a prompt and be in a block mode.

### Screenshots

Recorded a loom that demonstrates the issue.

https://www.loom.com/share/4b77121cd7f740e5a61684e7de3f6d74

### Operating System

MacOS

### OS Version

13.0 Beta (22A5331f)  (this is the most current dev beta of Ventura)

### Shell Version

On my local machine: zsh 5.8.1 (x86_64-apple-darwin22.0)
On the remote machine that I'm ssh'ing to: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Warp Version

v0.2022.08.31.18.11.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by warpdotdev-dx** [comment] 2022-09-06 15:03
Hi @sdorr0, I'm Danny, Support Engineer @ Warp. Unfortunately, we don't currently support TMUX integration but feel free to +1 this issue > #501, to help us gauge interest.


As a possible stopgap, have a look at [Split Panes](https://docs.warp.dev/features/split-panes), it allows you to right-click split any Warp tab/window or use the Control Palette `CMD-P` and find other **pane** commands.

__
Danny Neira (he/him/his)
Support Engineer
www.warp.dev

--- original message ---
On September 2, 2022 at 6:08 PM MDT ***@***.*** wrote:



Discord username (optional)

Myrddin#4194

Describe the bug

If I'm ssh'd to a remote host, using tmux, and then have an ungraceful drop of connection (e.g., loss of LAN/WAN connection), Warp loses it's block context (ie. it doesn't appear to be in a block anymore, and I can't seem to restore it to that state) and all I have to interact with is a lone cursor on the far left of the screen. The prompt is missing. I can issue shell commands as normal, but no context, no block, no prompt.

To Reproduce

ssh to remote host

attach to a tmux session (eg. tmux, tmux a -d, etc)

kill the connection (shut off wifi, use the <enter>~. key combo, etc)

you are now back in your shell on your local machine

be sad that you've lost your prompt, block, etc :(


Expected behaviour

I would expect when returning to the shell on my local machine to have a prompt and be in a block mode.

Screenshots

Recorded a loom that demonstrates the issue.

https://www.loom.com/share/4b77121cd7f740e5a61684e7de3f6d74

Operating System

MacOS

OS Version

13.0 Beta (22A5331f) (this is the most current dev beta of Ventura)

Shell Version

On my local machine: GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin20.2.0), on the remote machine that I'm ssh'ing to: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

Warp Version

v0.2022.08.31.18.11.stable_00

Additional context

No response

Does this block you from using Warp daily?

Yes

Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

No response

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by sdorr0** [comment] 2022-09-06 18:24
Thanks for the feedback!  Unfortunately tmux is integral to the way I work and split-panes won't take its place.
Also, thanks for pointing out that existing issue.  I've given my +1 to it.  Hopefully you guys add that support soon!

**Comment by dannyneira** [comment] 2022-09-28 17:17
Closing in favor of [#501](https://github.com/warpdotdev/Warp/discussions/501). Thanks for your patience with us @sdorr0

**Closed by dannyneira** 2022-09-28 17:17 UTC
