### ISSUE TITLE
Hotkey Window CMD +§ does work

### ISSUE THREAD

**Issue by Froelund** [warpdotdev/Warp#966] opened 2022-04-08 08:31 UTC
### Describe the bug

```text
When changing the changing the Hotkey Window keybinding to `CMD + §` the window does not appear. I've tested with `CMD + -` which works fine.
```

### To Reproduce

Steps to reproduce:
1. Go to 'Settings -> Features'
2. Enable 'Hotkey Window'
3. Change Keybinding to 'CMD + §', and Save

Now when pressing `CMD + §`, nothing happens

### Expected behaviour

```text
When pressing `CMD + §`, there should appear a window
```

### Screenshots

![image](https://user-images.githubusercontent.com/2089088/162397371-d4b1cffb-0c2c-4e2e-a9db-597da3032538.png)

### Operating System

MacOS

### OS Version

12.2.1

**Comment by baadc0de** [comment] 2022-04-08 19:52
There's also a problem with command + double quote character left of number one on apple keyboards.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/15308543/162516899-da8993cd-5522-4663-8605-60deb59cbcfa.png">

**Comment by Froelund** [comment] 2022-04-10 06:05
That is the key I'm using as well. Mac with `ABC` layout.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/2089088/162604686-304cb0b7-885b-4a70-8a89-c4fc30af7b52.png">

**Comment by elviskahoro** [comment] 2022-04-12 18:09
Duplicate of:
- #856

**Closed by elviskahoro** 2022-04-12 18:09 UTC
