### ISSUE TITLE
Hotkey window doesn't respect Dock position

### ISSUE THREAD

**Issue by rbell-mfj** [warpdotdev/Warp#1929] opened 2022-10-06 16:06 UTC
### Describe the bug

When the hotkey window appears, the prompt or other important parts of the window can easily end up underneath the macOS Dock

### To Reproduce

1. set macOS system default of dock on bottom, not auto-hiding
2. enable hotkey window in warp, with pin left/right/bottom, and keep the default width and height %
3. trigger the hotkey window

result: prompt ends up under the dock

### Expected behaviour

The available area that the hotkey window uses to compute its configured width % and height % (and potentially anchor point) should exclude the Dock

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.27.08.11.stable_00

### Additional context

A workaround for left or right pinning with bottom dock is to set the height % of the hotkey window to about 85%

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment] 2022-10-27 22:13
Hi @rbell-mfj , I'm Danny, a Support Engineer at Warp. Thanks for letting us know!
We're sorry about this, this is not an ideal experience. We've made some changes to the hotkey window and can't reproduce this issue in the latest version. Can you please update Warp and let us know if the issue persists?

**Comment by rbell-mfj** [comment] 2022-10-28 01:19
Yes, it seems to automatically avoid the Dock now with version `v0.2022.10.25.08.06.stable_02`. Thanks!

**Comment by dannyneira** [comment] 2022-11-04 17:30
Great! thanks for the update @rbell-mfj closing this one.

**Closed by dannyneira** 2022-11-04 17:30 UTC
