### ISSUE TITLE
Please allow selecting and copying prompts as normal text

### ISSUE THREAD

**Issue by dgobera-humane** [warpdotdev/Warp#3986] opened 2023-12-19 07:51 UTC
### Describe the solution you'd like?

```Text
Please allow selecting text in the prompt to copy it. Selection doesn't need to be continuous with neighboring blocks. It would be sufficient to allow selecting the prompt only in isolation.
```

### Is your feature request related to a problem? Please describe.

```Text
Prompts seem to be handled differently than other text content in warp windows. It can't be selected, mainly to copy it. I know there's support to copy a prompt with a dedicated command, and even one to copy the git branch added recently.

However, these are not always enough. Often I need to select a previous prompt to copy a file path I was in before, or the branch name I switched away from. Or sometimes it's a long path and you just need to extract a portion of it to use it as part of another command.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2023-12-19 22:20
Thanks for submitting this @dgobera-humane 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/36

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2023-12-19 22:22
Duplicate of #36

**Closed** 2024-01-02 00:13 UTC
Labels: Feature
