### ISSUE TITLE
Can't set another keyboard layout

### ISSUE THREAD

**Issue by igomonteiro** [warpdotdev/Warp#4975] opened 2024-06-02 06:09 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I'm trying to set my keyboard layout as br abnt2 (brazilian layout), I tried using both commands `loadkeys br `and `setxkbmap -layout br -variant abnt2`, but the keyboard layout doesn't changes.
I also tried changing mannualy the XKBLAYOUT line to br in the file /etc/default/keyboard.
It's only happening in warp terminal, on windows terminal is working as expected.

### To reproduce

1. Just installed Warp terminal using .deb in the WSL
2. Open the warp terminal in windows startup menu

### Screenshots

Warp terminal installed on WSL:

![image](https://github.com/warpdotdev/Warp/assets/58708551/b5dce064-ad3c-4bb6-a7c1-080871276f7b)

Trying to type "ç" in my keyboard:

![image](https://github.com/warpdotdev/Warp/assets/58708551/f203c75f-8dc9-4d1a-a657-dbbaae0f2cd6)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04.4 LTS

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.05.28.08.02.stable.00_amd64

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-06-03 20:33
Hi @igomonteiro This may be related to the lack of IME support in Warp.

We're tracking this issue over at #341 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-03 20:33
Duplicate of #341

**Closed by dannyneira** 2024-06-03 20:33 UTC
Labels: Bugs

**Comment by lwives** [comment] 2024-10-17 14:24
I´m having the same issue. Will check #341
