### ISSUE TITLE
Saving permissions problem when update available

### ISSUE THREAD

**Issue by VanWieren** [warpdotdev/Warp#5434] opened 2024-11-01 16:41 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When I am running jupyter notebooks via warp, I am always unable to save the notebook when there is a warp update available. This was not always the case. The error is something like this: File Save Error for notebook.ipynb Permission denied. 

### To reproduce

Open jupyter server in warp with `jupyter lab`,  edit notebook, hit save (while there is an available update for warp), get error

### Expected behavior

I should not be forced to update warp every time I want to save a notebook file, especially when notebooks can take a long time to run. There should be something in the permissions that is not reset until the update is applied.

### Operating system

MacOS

### Operating system and version

15.0.1

### Shell Version

bash 3.2.57

### Current Warp version

v0.2024.10.23.14.49.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment] 2024-11-01 16:58
Hi @VanWieren - did you update to macOS 15 recently?  We've received a handful of reports of this and are trying to understand if it regressed in Sequoia.

**Comment by VanWieren** [comment] 2024-11-01 17:03
I updated to 15.0 on Sept 18, which probably does align with around when the issue started

**Comment by vorporeal** [comment] 2024-11-01 20:38
Ack; thanks.  We're working on a fix and will have it out in the next release (some time next week).

@dannyneira can you dupe this against our canonical tracking issue?

**Comment by dannyneira** [comment] 2024-11-01 20:46
@VanWieren We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/3009 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-11-01 20:46
Duplicate of https://github.com/warpdotdev/Warp/issues/3009

**Closed by dannyneira** 2024-11-01 20:46 UTC
Labels: Bugs
