### ISSUE TITLE
DUP: Duplicate of #064 - Enable Blocks on subshells

### ISSUE THREAD

**Issue by michlimlim** [warpdotdev/Warp#201] opened 2021-09-15 19:35 UTC
### Describe the solution you'd like?

```shell
It will be cool if Warp Blocks are enabled on subshells.
```

### Is your feature request related to a problem? Please describe.

```shell
A user's company spawns a subshell for their internal CLI. The lack of Blocks means the user loses all the benefits of Warp. 

It is also common for users to open subshells while working, e.g. needing to run a bash-specific command from online documentation. They lose the benefits of Warp blocks when using them.
```

**Comment by elviskahoro** [comment] 2021-09-16 04:06
relates to this: https://github.com/warpdotdev/warp/issues/183

**Comment by elviskahoro** [comment] 2021-12-17 15:02
Closing this in favor of:
- DUP: Duplicate of #064 - Enable Blocks on subshells

**Closed** 2022-01-20 07:25 UTC
