### ISSUE TITLE
tab autocomplete not working for bash complete scripts

### ISSUE THREAD

**Issue by peeyush18** [warpdotdev/Warp#4802] opened 2024-04-22 08:44 UTC
### Describe the bug

tab autocomplete does not work for scripts that use bash complete features.

### To reproduce

**Step 1**
create file `mytabcompletion.sh` with the content

```
#!/bin/bash

# A fictional command "foo" with tab completion
_foo_completion() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="bar baz qux"  # List of possible options for "foo"

    case "$prev" in
        foo)
            COMPREPLY=($(compgen -W "$opts" -- "$cur"))
            return 0
            ;;
        *)
            ;;
    esac
}

complete -F _foo_completion foo
```

**Step 2**
then make the bash script executable by running the command `chmod +x mytabcompletion.sh` .

**Step 3**
source bash script to use autocomplete, you can use the command `. ./mytabcompletion.sh` .

**Step 4**
type `foo` and the then press `TAB` on your keyboard

### Expected behavior

it output should be
```
pi:~$ foo 
bar  baz  qux  
````

### Screenshots

the warp output
![image](https://github.com/warpdotdev/Warp/assets/1012500/3b5ccf81-7969-4fcf-885a-e6dfdab198ab)

the expected output from terminator
![image](https://github.com/warpdotdev/Warp/assets/1012500/c8c3e79c-a3e8-406a-9f62-c9511d7fc8c9)

### Operating system

Linux

### Operating system and version

Linux LLHN80KR3 6.5.0-27-generic #28~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 15 10:51:06 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Shell Version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.04.09.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-24 23:05
Hi @peeyush18 sorry to hear about this issue. From what I understand shell completions arent supported in Warp at this time. It's something we're tracking here #434. As a possible workaround, you can run `bash` and enter a subshell to use the custom completions/script. This will not have Blocks and other Warp features, but should work as in a normal terminal.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-06-26 21:42
Duplicate of https://github.com/warpdotdev/Warp/discussions/434

**Closed by dannyneira** 2024-06-26 21:42 UTC
Labels: Bugs
