### ISSUE TITLE
Accept pasting with the middle button (scrolling wheel) of the mouse in Linux

### ISSUE THREAD

**Issue by poldap** [warpdotdev/Warp#4499] opened 2024-03-07 12:25 UTC
### Describe the solution you'd like?

Within the Linux desktop experience, selecting any text imports it into a clipboard, and clicking anywhere else with the middle button on the mouse will paste it. 

### Is your feature request related to a problem? Please describe.

I am very frustrated when I explicitly have to issue commands to copy and paste, when everywhere else in the Linux desktop this is not needed. Thank you!

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-07 22:54
Hi @poldap Thanks for submitting.

We already have a request tracking this over at #4329

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-07 22:54
Duplicate of #4329

**Closed by dannyneira** 2024-03-07 22:54 UTC
Labels: Feature requests
