### ISSUE TITLE
Formatting lost when pasting into nano

### ISSUE THREAD

**Issue by Rhainland** [warpdotdev/Warp#465] opened 2021-11-29 23:06 UTC
### Describe the bug
 
When copying text from websites, text editor or other locations, sometimes the text does not maintain its formatting when pasting into files opened through warp. 

The image added, shows the current json copied from a text editor, entered in a file created using Nano, the result of the paste is shown both using Warp, and iTerm 2. As can be seen in the image, text formatting in Warp is non-existent in this case, while iTerm2 maintains the format of the copy pasted text.

The text;

{
"bus": "greyhound",
"car": "prius"
}

### To Reproduce

Steps to replicate:

1. Open warp terminal
2. Nano somefile
3. Copy the text above and paste it into the file opened by nano, in warp terminal
4. Result will look like the nano window in the warp terminal, in my image.

Do the same in iTerm2, result will look like the iTerm2 window in my image(correctly formatted)

I have additional examples where this format issue happens with just line by line text(no json) where empty spaces are added between each line etc.

### Expected behaviour

shell
Expect text to maintain formatting when pasting

### Screenshots

<img width="663" alt="Screenshot 2021-11-29 at 23 01 54" src="https://user-images.githubusercontent.com/7574288/143949862-4080aa22-cfaf-4913-b258-7547498dd48b.png">

### Operating System

MacOS

### OS Version

12.0.1

**Comment by Ryang20718** [comment] 2022-04-18 01:50
I usually workaround this via
`cat > filename.txt`

(paste into stdin enter newline & then Ctrl + c) , but would be nice to have this native feature!

**Comment by ahoiroman** [comment] 2022-04-28 08:59
Working with VI using WARP is not working well, too... I'll create a screencast about that in the future, but until this is fixed, warp is almost useless for me.

**Comment by elviskahoro** [comment] 2022-07-06 14:11
Gonna follow up with team regarding this

**Comment by bericp1** [comment] 2022-09-30 20:03
Any update here @elviskahoro ? This is the only reason I have to not use Warp day-to-day. Every time I paste anything into warp into nano, it does something unpredictable with line breaks and even corrupts existing file contents :/

Seems to do something weird with Justify/Unjustify commands in nano during the paste, maybe warp is sending weird control sequences during pasting?

![](https://d.pr/i/Ez6vI3.gif)

**Comment by sinejoe** [comment] 2022-10-07 18:25
Seems to be the bracketed paste feature of terminal emulators missing or not implemented properly... https://cirw.in/blog/bracketed-paste

**Comment by doouz** [comment] 2022-11-09 15:23
Some news about this @elviskahoro ?

Thank you a lot.

**Comment by XuNiLuS** [comment] 2022-11-16 11:22
I just discovered Warp and I love the idea, but it's unusable for me because of this bug...
Do you have any news on the fix?

**Comment by simonlaw0711** [comment] 2023-01-06 06:31
May i know is this fixed yet?

**Comment by XuNiLuS** [comment] 2023-01-07 16:20
still no progress on this...

**Comment by 5aberd2** [comment] 2023-02-08 21:09
I can confirm this still doesn't work on both vi and nano, so basically I'll have to keep an iterm2 session just to paste stuff.

**Comment by vorporeal** [comment] 2023-02-15 22:11
Quick question: can you share what shell you're using, and what version?  Also, can you confirm that the issue is inconsistent (i.e.: sometimes pasting preserves formatting, but other times it doesn't)?

**Comment by 5aberd2** [comment] 2023-02-16 20:29
> Quick question: can you share what shell you're using, and what version?  Also, can you confirm that the issue is inconsistent (i.e.: sometimes pasting preserves formatting, but other times it doesn't)?

    After too many testing with this on the machine that is affected, the problem appears to be related to nano 2.9.3 which ships as default on Ubuntu 20.04, so I tried on the same machine running nano 2.9.3 (results in scrambled format) and then on the same machine nano 7.2 (format was well kept)

**Comment by vorporeal** [comment] 2023-02-16 22:24
Looks like this is the same issue as was reported for Hyper here: https://github.com/vercel/hyper/issues/1448

The fix described there also seems to fix the issue in Warp; I'm sending out a change today and it should be fixed in next week's release. :)

**Comment by bericp1** [comment] 2023-02-16 22:31
> Looks like this is the same issue as was reported for Hyper here: [vercel/hyper#1448](https://github.com/vercel/hyper/issues/1448)
> 
> The fix described there also seems to fix the issue in Warp; I'm sending out a change today and it should be fixed in next week's release. :)

Great news! Thanks!

**Comment by dannyneira** [comment] 2023-03-02 23:29
Hey Folks, this fix is out on today's release v0.2023.02.28.08.03.stable_01.

Closing as completed but please let us know if the issue persists.

**Closed by dannyneira** 2023-03-02 23:29 UTC
Labels: Bug
