### ISSUE TITLE
Solid pink UI after latest update

### ISSUE THREAD

**Issue by nickcheek** [warpdotdev/Warp#3552] opened 2023-08-17 21:59 UTC
### Describe the bug

After updating, all I now see is a pink UI with no inputs.

### To reproduce

Update on m1 mac

### Screenshots

![Screenshot 2023-08-17 at 5 55 32 PM](https://github.com/warpdotdev/Warp/assets/7572691/b05ef4ce-e76b-4d51-8790-64ae5e475264)

### Operating system

MacOS

### Operating system and version

Ventura 13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

Latest?  Can't see anything but a pink screen.

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

8-17-23

### Additional context

I've removed warp from my system and redownloaded, still have the same issue.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment] 2023-08-17 22:03
Hey @nickcheek, sorry for the issues here after the latest update and thanks for flagging! 

We've seen this issue exactly once before (https://github.com/warpdotdev/Warp/issues/1450). Could you try deleting Warp and reinstalling to see if this fixes the issue?

**Comment by nickcheek** [comment] 2023-08-17 22:06
So I did delete warp and reinstall and the issue persisted.  Literally as I was typing this, It just switched to how it's supposed to look right in front of me.
![Screenshot 2023-08-17 at 6 05 52 PM](https://github.com/warpdotdev/Warp/assets/7572691/97675485-bc4b-45cc-b61b-62232aaad646)

**Comment by nickcheek** [comment] 2023-08-17 22:16
I'm thinking this is more of a mac issue than a warp issue.  I just noticed this in my messages app.

![Screenshot 2023-08-17 at 6 16 05 PM](https://github.com/warpdotdev/Warp/assets/7572691/188ed056-8fd0-4f01-ad87-85ae490da766)

**Comment by alokedesai** [comment] 2023-08-17 22:24
That's a great callout! It seems like it could be an issue with your graphics card  https://setapp.com/how-to/pink-screen-of-death#:~:text=Check%20and%20reset%20the%20GPU,to%20accurately%20display%20an%20image.

**Comment by alokedesai** [comment] 2023-08-17 22:25
I'm going to close this out as I'm not entirely sure it's a Warp issue, but will reopen if other users report they are facing it.

**Comment by alokedesai** [comment] 2023-08-30 13:25
Marking this as a dupe of https://github.com/warpdotdev/Warp/issues/3604

**Closed by alokedesai** 2023-08-30 13:25 UTC
Labels: Bug
