### ISSUE TITLE
App Updates

### ISSUE THREAD

**Issue by nilay1808** [warpdotdev/Warp#3945] opened 2023-12-07 20:30 UTC
### Describe the solution you'd like?

```Text
I have Warp added to the Dock on my Mac, whenever there's a new version of Warp available and I click on the button to update, it does the update but opens Warp as a new item on the Dock and the older version stays on the Dock which is weird I have to remove it from the dock and move the newer app there
Could it just update the existing one?
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-12-07 21:31
Thanks for submitting this @nilay1808 We already have a request tracking the Warp icon after app updates over at #2824

Please give it a :+1: and subscribe to that request; it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment] 2023-12-07 21:31
Duplicate of #2824

**Closed by dannyneira** 2023-12-07 21:31 UTC
Labels: Feature
