### ISSUE TITLE
Toggle Warp

### ISSUE THREAD

**Issue by SolaKabuta** [warpdotdev/Warp#3698] opened 2023-09-22 22:08 UTC
### Discord username (optional)

sshhaannkkss

### Describe the solution you'd like?

```Text
It would be nice to be able to toggle Warp whatever we are doing. By double-tapping a key or by defining a shortcut of our choice.
Then a new tab will open directly with the code ready to be typed.
```

### Additional context

<img width="1792" alt="Capture d’écran 2023-09-23 à 00 06 25" src="https://github.com/warpdotdev/Warp/assets/125527131/810bce62-e8cc-45a9-844e-8dba170f40a0">
![Capture d’écran 2023-09-23 à 00 06 25 (2)](https://github.com/warpdotdev/Warp/assets/125527131/6fe28f77-c1f3-4cc3-bde2-425e080d046b)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-09-25 20:04
Hi @SolaKabuta There is a feature in Warp, [Global Hotkey](https://docs.warp.dev/features/windows/hotkey-window), which allows you to set a keyboard shortcut to toggle a dedicated window or show/hide all Warp windows.

I hope this helps with your use case. Closing as the feature already exists, but please let us know if any issues with it.

**Closed by dannyneira** 2023-09-25 20:04 UTC
Labels: Feature

**Comment by chrishiste** [comment] 2024-02-06 20:30
@dannyneira We still cannot set a double tap on Ctrl/Option/Command like iTerm allows. 

This feature as been requested many times:
- https://github.com/warpdotdev/Warp/issues/2809
- https://github.com/warpdotdev/Warp/issues/1915
- https://github.com/warpdotdev/Warp/issues/1803
- https://github.com/warpdotdev/Warp/issues/1410
- https://github.com/warpdotdev/Warp/issues/1221

**Comment by dannyneira** [comment] 2024-02-06 20:44
Hi @chrishiste Thanks for letting us know. It's a doable feature, but we have no ETA on the release of this feature. I've closed all the other issues and marked them as duplicate of #2809

**Comment by dannyneira** [comment] 2024-02-06 20:44
Duplicate of #2809
