### ISSUE TITLE
Starship prompt newline is not honored

### ISSUE THREAD

**Issue by hpohlmeyer** [warpdotdev/Warp#765] opened 2022-02-19 11:27 UTC
### Describe the bug

```shell
When using the starship prompt with the default config, the ❯ symbol is on the same line as the prompt info. In other terminals it is located on the same line as the command you enter
```

### To Reproduce

Steps to reproduce:
1. Install starship prompt
2. Enable prompt support in warp
3. Restart the terminal
4. See the ❯ symbol appear in the wrong place

### Expected behaviour

```shell
The ❯ should be on the next line like in other terminals
```

### Screenshots

Left: Warp
Right: Terminal

<img width="390" alt="image" src="https://user-images.githubusercontent.com/6564077/154798895-496a2939-d74d-4995-90fd-6aa00d7097fa.png">

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment] 2022-03-31 07:36
From @[mikrostew](https://github.com/mikrostew) via #845

### Describe the bug

```text
For a `PS1` with multiple lines (using newline `\n`), Warp only shows the second line of the prompt.

This has also surfaced in the PS1 discussion: https://github.com/warpdotdev/Warp/discussions/422#discussioncomment-2234174
```


### To Reproduce

Steps to reproduce:
1. Setup a `.bashrc` containing `PS1="username\n$"`
2. In Warp, enable "Honor user's custom prompt (PS1) setting" in Settings > Features
3. Open a new tab, and see that the prompt only shows the `$`, and the username is not visible


### Expected behaviour

```text
Either
a) render multiline prompts on multiple lines, or
b) concatenate multiline prompts to a single line, stripping out the newlines
```


### Screenshots

In Warp:
<img width="178" alt="Screen Shot 2022-03-28 at 2 01 44 PM" src="https://user-images.githubusercontent.com/190129/160459051-59b0211c-88bd-4531-b595-8f8dbe8c30f9.png">

In iTerm2:
<img width="190" alt="Screen Shot 2022-03-28 at 2 01 24 PM" src="https://user-images.githubusercontent.com/190129/160459089-cd596895-5054-4641-b312-269b0bd37b46.png">



### Operating System

MacOS

### OS Version

12.3

### Additional context

```text
I have worked around this by checking `$TERM_PROGRAM`, and setting PS1 appropriately, since Warp already puts some spacing around the prompt (which is why I had newlines in there).
```

**Comment by DacoDev** [comment] 2022-04-09 02:13
Ran into an issue related to this, if your bash_profile/bashrc requires an input on entry, Warp returns the input line inside the previous block and the block you're dropped in to sticks at "Starting shell..." and does not respond to input. Weirdly, I can click inside of the previous block and hit enter until the prompt (for auth on an on that host) fails and I'm dropped into the terminal like normal. This entry process works as expected in other terminals.

![warp-765](https://user-images.githubusercontent.com/20329637/162552693-3e3bd426-f600-46ea-835f-70f678dcd4ef.png)

**Comment by kyle-west** [comment] 2022-04-23 11:49
I would also very much appreciate having my prompt and input on the same line.

**Comment by elviskahoro** [comment] 2022-07-07 19:45
The reason we can't support this is because the Input Editor and the prompt are completely separate UI elements. This is one of the reasons the IE can support a modern text editing experience. The eventual plan is to build a native prompt so we can support actions like mouse interaction, etc. 

Some ideas here:
https://twitter.com/warpdotdev/status/1496263490491023362

**Comment by dannyneira** [comment] 2023-08-18 16:01
Closing as Warp now supports multi-line prompts in zsh/fish, But with the caveat that the new line will not be in the input editor, as with other terminals.

https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts

![CleanShot 2023-08-18 at 10 01 14](https://github.com/warpdotdev/Warp/assets/16809145/208b0592-b9f1-4623-b803-072197bf59ae)


BTW, we're working on the prompt in same area as input, you can track here: https://github.com/warpdotdev/Warp/issues/2304

**Closed by dannyneira** 2023-08-18 16:01 UTC
Labels: Bug

**Comment by wmcnamee-coreweave** [comment] 2024-07-11 17:22
Time to reopen possibly. Warp `v0.2024.07.09.08.01.stable_00` just made an update.

![image](https://github.com/warpdotdev/Warp/assets/167125312/9a91d7ae-8372-40f6-926e-76e6619f0b31)

**Comment by pauliesnug** [comment] 2024-07-22 07:19
yeah, the new update reintroduced this issue, its quite annoying, since everything was working fine before

**Comment by OlafHaalstra** [comment] 2024-07-25 11:17
> Adding this `PROMPT="${PROMPT}"$'\n'` at the end of my `.zshrc` file solve the problem for me. [#5052 (comment)](https://github.com/warpdotdev/Warp/issues/5052#issuecomment-2225843500)

This fixed it for me
