### ISSUE TITLE
Title: Zoom Functionality Issue in Warp Terminal 

### ISSUE THREAD

**Issue by sachin3973** [warpdotdev/Warp#4706] opened 2024-04-05 19:51 UTC
### Discord username (optional)

s4ch1n

### Describe the bug

When zooming in the Warp Terminal using the Ctrl+Shift+Plus keyboard shortcut, the Warp AI pane does not scale proportionately with the terminal. This results in a mismatch between the terminal and the Warp AI pane, potentially impacting user experience.
![Screenshot from 2024-04-06 01-08-33](https://github.com/warpdotdev/Warp/assets/54833388/46d0c92d-4841-462b-a9a0-329e8c8c4337)

### Expected behavior

When using the Ctrl+Shift+Plus keyboard shortcut to zoom in on the Warp Terminal, I expect both the terminal and the Warp AI pane to scale proportionately. This would maintain the relative size and readability of the Warp AI pane in relation to the rest of the terminal, ensuring a consistent and user-friendly experience.

### Screenshots

[Screencast from 2024-04-06 01-16-23.webm](https://github.com/warpdotdev/Warp/assets/54833388/55627832-f1b7-4cf5-b915-978614c15cc1)

### Operating system

Linux

### Operating system and version

Zorin OS 17.1

### Shell Version

zsh 5.8.1

### Current Warp version

v2024.04.02.08.02 .stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

06 April 2024

### Additional context

No, that's pretty much it.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-05 21:24
Hey @sachin3973 this may be related to lack of native Wayland support which we are working on\ #4628

**Comment by dannyneira** [comment] 2024-04-05 21:29
Duplicate of https://github.com/warpdotdev/Warp/issues/1443

**Closed by dannyneira** 2024-04-05 21:29 UTC
Labels: Bugs

**Comment by mar-robba** [comment] 2025-03-15 14:26
if i press ctrl + + it does't zomm, why. how i do for zoom the visual
