### ISSUE TITLE
Custom layout ( Pin the Input to the top

### ISSUE THREAD

**Issue by RSoraM** [warpdotdev/Warp#1268] opened 2022-05-04 19:47 UTC
### Describe the solution you'd like?

```text
Provide more options for ui layout in the settings, the input box can be fixed at the top while the Block grows from top to bottom.
```

### Is your feature request related to a problem? Please describe.

```text
But when I opened Warp for the first time, I encountered a very awkward problem. Why is the input box designed at the bottom, but the tabs are still at the top?

In the past, I basically only used the terminal program that comes with the system, and they never put the input box at the bottom without exception.

I often use the terminal in full screen, so I need to look down at the input box. The design of tabs at the top and input boxes at the bottom increases the burden on the eyes to find content. I don't think it's very ergonomic.
```

**Comment by dev4joel** [comment] 2022-05-17 07:38
Thanks for the feedback and sorry it wasn't an awesome experience!

DUP: Duplicate of https://github.com/warpdotdev/Warp/issues/22 - Allow terminal input pane to be pinned to top (vs bottom) + ergonomics

**Closed** 2022-06-21 16:51 UTC
