### ISSUE TITLE
Git commit -am completion not fully working

### ISSUE THREAD

**Issue by pavlovic265** [warpdotdev/warp#545] opened 2021-12-23 08:41 UTC
### Describe the bug

```shell
When I want to do `git commit -am "some task I am working on"` it just stay without running a command. 
Then I have to cancel it with `ctrl + C` to exit.
```

### To Reproduce

Steps to reproduce:
1. Run `git commit -am "some text"`

### Expected behaviour

```shell
To execute the git commit command
```

### Screenshots

Video

https://user-images.githubusercontent.com/92149469/147212827-8df8e154-dc00-4334-a9db-bb0cd790d990.mov

Image
<img width="605" alt="Screenshot 2021-12-23 at 09 38 00" src="https://user-images.githubusercontent.com/92149469/147212632-d92a6260-9132-46ac-9a33-e04dd3723fa7.png">

### Operating System

MacOS

### OS Version

11.6.1

### Additional context

```shell
I am currently using macOS Big Sur with apple chip M1.
```

**Comment by elviskahoro** [comment] 2021-12-23 15:56
@pavlovic265 I think you're missing the closing double quotation marks.

"wip" instead of "wip

I can't reproduce this bug. 
Just double checking, you've already staged the files with git add?

**Comment by fishcharlie** [comment] 2021-12-23 19:13
@elviskahoro 

> Just double checking, you've already staged the files with git add

The `-a` flag in @pavlovic265's command automatically stages the files. (https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--a).

> I think you're missing the closing double quotation marks.

Correct. This is the problem.

**Comment by elviskahoro** [comment] 2021-12-23 19:17
i don't think it stages untracked files though.

**Comment by fishcharlie** [comment] 2021-12-23 19:33
> i don't think it stages untracked files though.

You are correct.

The issue here tho is the missing `"` closing quote. I've run into this issue multiple times, and that is for sure the issue here.

**Comment by pavlovic265** [comment] 2021-12-24 04:00
🤦 well this was stupid of me... 😅 

Thanks for help 🙏

**Comment by elviskahoro** [comment] 2021-12-31 21:10
reopening because tab completion doesn't work work with this properly

**Closed** 2022-01-04 21:12 UTC
Labels: bug, Completions
