### ISSUE TITLE
**<TAB> fzf expansion doesn't work in warp terminal

### ISSUE THREAD

**Issue by seraphniu** [warpdotdev/Warp#5100] opened 2024-07-06 13:10 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

**<TAB> fzf expansion doesn't work in warp terminal, but it works in standard terminal and iterm2.

in iterm2:
<img width="982" alt="image" src="https://github.com/warpdotdev/Warp/assets/8098243/75427e08-c786-413c-9aed-797bcc2c54b4">

in warp:
nothing happens.

### To reproduce

- install fuzzy
- add below into ~/.zshrc:

`source <(fzf --zsh)`

- try `vi **` and press <TAB>

### Expected behavior

**<TAB> triggers fuzzy search.

### Screenshots

refer to above screeshot.

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.06.25.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

7/5

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-07-10 22:43
Thanks for letting us know @seraphniu 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/1647 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-07-10 22:43
Duplicate of https://github.com/warpdotdev/Warp/issues/1647

**Closed by dannyneira** 2024-07-10 22:43 UTC
Labels: Bugs

**Comment by defyned-matt** [comment] 2025-06-04 21:17
also having this issue. +1 to have fzf-tab work in warp
