### ISSUE TITLE
the custom prompt p10k not load when start the app

### ISSUE THREAD

**Issue by leobip** [warpdotdev/Warp#3777] opened 2023-10-14 22:18 UTC
### Describe the bug

Hello ..... I still have the problem.....  

I configured the prompt follow the instructions (https://github.com/warpdotdev/Warp/issues/3598)  but still the prompt appear in the botton of the screen ... I have to run: exec zsh and the it work ... but the prompt not blinking anymore....

### To reproduce

Go to the 'Setting'
Go to the 'Appearance'
Scroll down to prompt
Click the prompt and you should see the 'PS1' under it

### Screenshots

![Screen Shot 2023-10-15 at 00 16 22 AM](https://github.com/warpdotdev/Warp/assets/50139505/624ba256-9012-4d83-b802-ba6db32a1ea1)

![Screen Shot 2023-10-15 at 00 07 00 AM](https://github.com/warpdotdev/Warp/assets/50139505/db6a1523-4432-48ab-8411-cfd883166142)

![Screen Shot 2023-10-15 at 00 08 04 AM](https://github.com/warpdotdev/Warp/assets/50139505/ecbdba02-3886-4b42-99c3-f23171c8e201)

### Operating system

MacOS

### Operating system and version

sonoma 14.0 (23A344)

### Current Warp version

v0.2023.10.10.08.06.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-10-16 23:05
Hi @leobip Sorry to hear about this. I think this may have to do with the second line in your p10k prompt and Warp currently doesn't support the prompt in the same line (but we're working on this and you can track it here #2304). As a workaround, you can try running `p10k configure` to disable the second line, but Warps prompt will still be in a separate line, as the input is separate from the prompt.

Closing as a duplicate of #2304, please follow the progress on that thread.

**Closed by dannyneira** 2023-10-16 23:05 UTC
Labels: Bug
