### ISSUE TITLE
Tmux integration or Tmuxinator project setup

### ISSUE THREAD

**Issue by SC7639** [warpdotdev/Warp#680] opened 2022-01-26 12:45 UTC
### Describe the solution you'd like?

```shell
I'd like to have all the awesome features of warp but either within Tmux or have support a config file for projects (like tmuxinator) to open and run all the commands I need in windows or tabs and panes for developing each project with a single command. Then another command to bring it all down
```

### Is your feature request related to a problem? Please describe.

```shell
No
```

### Additional context

When using tmux / tminuxinator you loose all of the awsome features which is a shame

<img width="1399" alt="Screenshot 2022-01-26 at 12 45 05" src="https://user-images.githubusercontent.com/6049560/151165238-0bd2eaa2-3032-4091-9bfe-dbaa8c6637fb.png">

**Comment by elviskahoro** [comment] 2022-01-28 05:22
Closing as it's duplicate of:
- #501

**Closed by elviskahoro** 2022-01-28 05:22 UTC
