### ISSUE TITLE
Executing `exec fish` or any shell 

### ISSUE THREAD

**Issue by edheltzel** [warpdotdev/Warp#4542] opened 2024-03-12 13:05 UTC
### Describe the bug

When executing `exec fish` or any shell, the block feature breaks... every command after this "reloading" of the shell puts everything in the same block, including the prompt. 

### To reproduce

run `exec fish` or `exec zsh` or any shell.

### Expected behavior

blocks are separated by each command.

### Screenshots

https://github.com/warpdotdev/Warp/assets/402910/9c8dda6a-6125-4ef9-b983-4ebb8f43f224

### Operating system

MacOS

### Operating system and version

14.3.1

### Shell Version

fish, version 3.7.0

### Current Warp version

v0.2024.03.05.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

na

### Additional context

using fish shell and custom prompt - starship 

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-12 16:33
Hi @edheltzel Yes this is expected behaviour since running `exec zsh/fish/bash` (or other commands like `sudo su`) creates a subshell within the current session. Please look into our docs on how you can "Warpify" (enable blocks and warp features) on the subshell. https://docs.warp.dev/features/subshells

Hope this helps. Closing as the feature exists, but please let us know of any issues with the feature.

**Closed by dannyneira** 2024-03-12 16:33 UTC
Labels: Bugs

**Comment by edheltzel** [comment] 2024-03-12 17:25
> Hi @edheltzel Yes this is expected behaviour since running `exec zsh/fish/bash` (or other commands like `sudo su`) creates a subshell within the current session. Please look into our docs on how you can "Warpify" (enable blocks and warp features) on the subshell. https://docs.warp.dev/features/subshells
> 
> Hope this helps. Closing as the feature exists, but please let us know of any issues with the feature.

OOOH Thanks for the quick reply and response - sometimes thing's area always as they seem.
