### ISSUE TITLE
Warp cutoff with no other setting

### ISSUE THREAD

**Issue by uriariel** [warpdotdev/Warp#4101] opened 2024-01-24 10:01 UTC
### Describe the bug

I've encountered an issue with Warp where the terminal cuts off without any additional settings for scroll-back. This limitation restricts the ability to review past output, which is crucial for various tasks.

### To reproduce

1. use a lot of history

### Expected behavior

Don't cutoff history without warning or any other signs

### Operating system

MacOS

### Operating system and version

11.2

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-26 17:50
hey @uriariel Sorry if this is a blocker for you. We have a long request tracking this issue over at #610 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue.

**Comment by dannyneira** [comment] 2024-01-26 18:11
Duplicate of #610.

**Closed by dannyneira** 2024-01-26 18:11 UTC
Labels: Bug
