### ISSUE TITLE
Close button position on tabs

### ISSUE THREAD

**Issue by ghall89** [warpdotdev/Warp#3177] opened 2023-06-04 23:27 UTC
### Describe the solution you'd like?

```Text
It's an extremely minor nitpick but I would love if the close button on tabs at least had the option to be on the left side of the tab. I generally use cmd + w to close a tab but on the occasion I use the mouse it throws me off since it's counter to the norm on Mac OS.
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by Z2Flow** [comment] 2023-11-17 16:45
To me, it's important.
It's cognitive dissonance every time I use Warp.
That this could have been implemented this way is very puzzling.

**Comment by dannyneira** [comment] 2024-06-20 23:17
Hey folks

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1847

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-20 23:17
Duplicate of https://github.com/warpdotdev/Warp/issues/1847

**Closed by dannyneira** 2024-06-20 23:17 UTC
Labels: Feature requests
