### ISSUE TITLE
Removing border around Vim/Neovim window

### ISSUE THREAD

**Issue by SUPERustam** [warpdotdev/Warp#3904] opened 2023-11-24 17:52 UTC
### Discord username (optional)

superustam

### Describe the solution you'd like?

```Text
Just remove border from left, bottom, right around vim window in both modes (full-screen and floating window). 

My problem showed in my screenshots.
```

### Additional context

![image](https://github.com/warpdotdev/Warp/assets/64551202/33ca4de2-6dfa-433f-b7e2-6ac5c87023dc)
![image](https://github.com/warpdotdev/Warp/assets/64551202/354f6314-b762-489d-a689-4ae2256a2eb0)

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-11-29 18:15
Thanks for letting us know @SUPERustam. We originally added the padding in order to improve issues with [alt-screens like nvim](https://github.com/warpdotdev/Warp/issues/833) in Warp.

We already have a request tracking this over at #2373

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.

**Closed** 2023-11-29 18:15 UTC
Labels: Feature

**Comment by dannyneira** [comment] 2023-12-06 03:18
Duplicate of #2373

**Comment by SUPERustam** [comment] 2023-12-06 21:00
Thanks!
