### ISSUE TITLE
Getting a ParseError when trying to warpify Powershell

### ISSUE THREAD

**Issue by florianpeschke** [warpdotdev/Warp#4199] opened 2024-02-20 16:12 UTC
### Describe the bug

Getting a ParseError when trying to warpify Powershell (pwsh).

--

ParserError:
Line |
   1 |   [ -z $WARP_BOOTSTRAPPED ] && echo $0 | command -p grep -q zsh && uns …
     |    ~
     | Missing type name after '['.

### To reproduce

install PowerShell on MacOS 14.2.1 (23C71) via:

brew install --cask powershell

then open the subshell in Warp by calling pwsh and try to warpify it

### Operating system

MacOS

### Operating system and version

14.2.1

### Current Warp version

v0.2024.02.13.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-02-20 19:02
Hey @florianpeschke unfortunately `pwsh` warpification isn't supported at this time. You can still run `pwsh`, but Warp features (i.e. Blocks, autocomplete, etc. ) won't work within that session and it'll run similar to in a normal terminal.

Warp currently supports `bash|zsh|fish` shells. Please see more in our docs:
https://docs.warp.dev/features/subshells
https://docs.warp.dev/getting-started/using-warp-with-shells

![CleanShot 2024-02-20 at 12 01 55](https://github.com/warpdotdev/Warp/assets/16809145/325aab10-bce6-44e3-ae8f-20920fde61d2)

That being said, we're tracking this GitHub issue for support for other shells including here #880. We would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-20 19:04
Duplicate of #880.

**Closed** 2024-02-29 21:45 UTC
Labels: Bugs
