### ISSUE TITLE
DUP: Duplicate of #190 - Add option to set custom shell

### ISSUE THREAD

**Issue by lessless** [warpdotdev/warp#563] opened 2022-01-05 16:33 UTC
### Describe the solution you'd like?

```shell
Hi, 

I'd love to be able to use another shell, not the one that is attached by the system to a user.

For example, the system shell is zsh, and I would love to use fish. 

If I just type `fish` in the Warp it considers it as a command and I'm losing access to blocks.
```

**Comment by elviskahoro** [comment] 2022-01-05 16:56
Closing this as it's a duplicate of:
- https://github.com/warpdotdev/warp/issues/190

**Closed by elviskahoro** 2022-01-05 16:57 UTC
