### ISSUE TITLE
Focus Follows Mouse

### ISSUE THREAD

**Issue by BonesyWonesy** [warpdotdev/Warp#4464] opened 2024-03-04 20:53 UTC
### Describe the solution you'd like?

I'd like there to be an option 'Focus follows mouse' such that when enabled, whenever the mouse cursor moves from one panel to another, the focus of the panel the mouse moves into becomes the active input area.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-04 21:37
Thanks for submitting this @BonesyWonesy 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2551

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-04 21:37
Duplicate of https://github.com/warpdotdev/Warp/issues/2551

**Closed by dannyneira** 2024-03-04 21:37 UTC
Labels: enhancement
