### ISSUE TITLE
repeat 

### ISSUE THREAD

**Issue by m5ultra** [warpdotdev/Warp#4060] opened 2024-01-12 07:44 UTC
### Describe the bug

repeat

### To reproduce

repeat

### Screenshots

<img width="1024" alt="image" src="https://github.com/warpdotdev/Warp/assets/26688426/49302044-e776-4523-a143-88ba81a92c01">

### Operating system

MacOS

### Operating system and version

macos 13.6.3

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

<img width="1024" alt="image" src="https://github.com/warpdotdev/Warp/assets/26688426/fd8bbdc4-ebe7-4b98-8175-3d0bd34e2ae3">

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

Ignore

**Comment by mdonef** [comment] 2024-01-12 08:54
I have the same issue

**Comment by verheyenkoen** [comment] 2024-01-12 09:56
Same 
<img width="202" alt="image" src="https://github.com/warpdotdev/Warp/assets/599538/9d751b89-c5de-41c7-94de-de900a3d85a8">

**Comment by dannyneira** [comment] 2024-01-12 17:23
Hey Folks, thanks for letting us know. We'll be tracking this issue on #4057 going forward and are actively working on reverting the change that may have caused the prompt to repeat. We'll post updates on the parent issue above.

**Comment by dannyneira** [comment] 2024-01-12 17:24
Duplicate of #4057

**Closed by dannyneira** 2024-01-12 17:24 UTC
Labels: Bug
