### ISSUE TITLE
function keys not recognized in pgcli

### ISSUE THREAD

**Issue by edgarngg** [warpdotdev/Warp#3028] opened 2023-05-05 21:23 UTC
### Describe the bug

Entering the cli F3 for instance, activates multiline, but the key press is not recognized.

### To Reproduce

```sh
brew install pgcli
access a db with username and password
press fn+f3 key to activate multiline
```

### Expected behavior

Multiline indicator being highlighted

### Operating System

MacOS

### Operating System and Version

13.3.1

### Shell Version

fish

### Warp Version

v0.2023.05.02.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-05-05 22:12
Hey thanks for letting us know, I'll need to setup a testing pg dB in order to try and reproduce this issue. Are you noticing that this happens with any other  db cli tools? (if you even have others you may use)

**Comment by edgarngg** [comment] 2023-05-05 23:05
Hi Danny

I don't actually work with any other cli tool for dbs, but I work with rails console a lot, and although there's no actual action for function keys in rails console, I can tell warp doesn't recognize them because in iTerm2-rails console it does.

I hope that helps.

________________________________
De: Danny Neira ***@***.***>
Enviado: viernes, 5 de mayo de 2023 03:12 p. m.
Para: warpdotdev/Warp ***@***.***>
Cc: edgarngg ***@***.***>; Author ***@***.***>
Asunto: Re: [warpdotdev/Warp] function keys not recognized in pgcli (Issue #3028)


Hey thanks for letting us know, I'll need to setup a testing pg dB in order to try and reproduce this issue. Are you noticing that this happens with any other db cli tools? (if you even have others you may use)

**Comment by noorigami** [comment] 2023-12-27 22:29
Hi
Did this receive any update, facing same issue.

**Comment by mikenerone** [comment] 2023-12-29 20:19
Same problem in many apps. E.g. my current source of annoyance is that in IPython, F2 fails to open the current input cell in a text editor. Not having function keys is generally pretty disruptive - I'm honestly surprised that more people haven't complained.

Examples off the top of my head:

Common terminal apps that have function key bindings by default:
- nano
- htop
- Midnight Commander
- alpine (mail client)
- vim/vi, though only F1 (Help) by default

Common terminal apps that are frequently customized with function key bindings by users:
- vim/vi
- emacs
- tmux
- screen
- ranger (file manager)
- lynx & links (text-based web browsers)
- mutt & elm (mail clients)
- weechat & irssi (IRC clients)

**Comment by mbusch-regis** [comment] 2024-01-26 02:17
Same problem for me with the PTPython REPL. Several features, including the configuration menu, rely on F-keys. These functions are completely inaccessible in Warp. 

Is it a deal breaker? No, I do 99.9% of my Python in VSCode. 

It IS a disappointing and very basic oversight that calls the rest of the application quality into question (what else was overlooked that we can't see).

**Comment by alokedesai** [comment] 2024-05-02 14:22
What keyboard layout and locale are you using? I've been actively looking into this but haven't been able to reproduce yet; function keys work correctly for me on both Mac and Linux.

**Comment by mbusch-regis** [comment] 2024-05-02 14:27
US locale, Colemak keyboard layout on MacBook Pro with the touchbar function keys. Colemak doesn't do any weird mapping of functions keys, so maybe it's the touchbar?

**Comment by alokedesai** [comment] 2024-05-02 14:35
Interesting, I also can't repro with the Colemak keyboard layout but I'd be surprised if this were an issue with the touchbar. 

Two followups:
1) Any chance you have an external keyboard handy to test if this is specifically related to the Mac touchbar?
2) Could you share a snippet of your [Warp logs](https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs) so we can what happens when you press the function keys?

**Comment by mbusch-regis** [comment] 2024-05-02 14:38
I can try my Apple wireless keyboard later today (memory serves, that may have been what I was using before?).

Maybe the issue magically fixed itsefl in one of the latest releases.

**Comment by alokedesai** [comment] 2024-05-02 15:00
Ah so I see the issue, I'll draft a fix for this today. It should be released in next Thursday's release. Thank you for your patience here!

**Comment by mbusch-regis** [comment] 2024-05-02 15:02
Thanks for response to the issue! I look forward to the update.

**Comment by ckblockit** [comment] 2024-05-22 07:46
Hi, any update on this issue?

**Comment by alokedesai** [comment] 2024-05-24 16:11
Hi there, we believe this is now fixed. Could you try on the latest version of Warp and verify its working correctly? Thank you!

**Comment by dannyneira** [comment] 2024-05-30 21:27
@edgarngg any luck with the latest update? The issue been resolved, please update to the latest version of Warp and verify its working.

**Comment by mbusch-regis** [comment] 2024-05-30 21:34
Limited testing with the application I originally noticed the problem in looks like it is fixed. 

Thanks!

**Comment by alokedesai** [comment] 2024-05-30 21:44
Awesome! Thanks for your patience here and really appreciate you filing this issue!

**Closed by alokedesai** 2024-05-30 21:44 UTC
Labels: Bugs
