### ISSUE TITLE
Commands in the config.fish file don't run on startup of a new Warp session

### ISSUE THREAD

**Issue by randreu28** [warpdotdev/Warp#5235] opened 2024-08-18 08:24 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When using fish as shell, the commands on the `config.fish` don't run on startup of a new Warp session. Or at least their output don't appear on startup. 

A typical example is having neofetch/fastfetch for displaying PC info when starting a new shell, but this does not happen on warp. But i've tried with a simple echo "hello world" and it doesn't work either. 

There's an issue in the official discord server that was not resolved, that I reference [here](https://discord.com/channels/851854972600451112/1225176556364628100), where @dannyneira was able to reproduce the bug. 

### To reproduce

1. Start a shell in warp

### Expected behavior

To see the output of the commands specified in `config.fish`

### Operating system

Linux

### Operating system and version

Arch linux 2024.08.01 

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by szgupta** [comment] 2024-09-23 17:48
I think this is a duplicate of https://github.com/warpdotdev/Warp/issues/1869. Feel free to re-open if you believe this is a separate issue!

**Closed by szgupta** 2024-09-23 17:48 UTC
Labels: Bugs
