### ISSUE TITLE
Copy and paste any part of response from warp AI

### ISSUE THREAD

**Issue by Ghilt** [warpdotdev/Warp#4038] opened 2024-01-08 09:47 UTC
### Describe the solution you'd like?

```Text
I would like to be able to highlight (with my mouse cursor) and copy parts of the suggested code blocks warp AI provides. The built in 'copy entire code block' button is only useful in a fraction of my use cases.
```

### Is your feature request related to a problem? Please describe.

```Text
I'm always frustrated when i can't copy freely bits and pieces from the responses Warp Ai gives me.
```

### Additional context

I do ask the warp AI code questions unrelated to terminal work

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-09 01:11
Hey @Ghilt Thanks for submitting!

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2553

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-09 01:11
Duplicate of https://github.com/warpdotdev/Warp/issues/2553

**Closed by dannyneira** 2024-01-09 01:11 UTC
Labels: Feature
