### ISSUE TITLE
New Tab should open or add after the current active tab on pressing CMD + t

### ISSUE THREAD

**Issue by khanakia** [warpdotdev/Warp#3323] opened 2023-07-07 11:59 UTC
### Describe the bug

On pressing `CMD + T` it creates a new tab at the end. But if you check the other terminals it they open the tab just after the current tab. It's annoying when you have 10 Tabs opened and you want a new one just after the current tab instead of adding it to the end.

### To reproduce

1. Open 4 tabs
2. Click the 2 tabs
3. Press `CMD + t` it will add the tab to the end.

### Expected behavior

Tab must always create after the current active tab

### Operating system

MacOS

### Operating system and version

13.4 (22F66)

### Shell Version

version 3.2.57(1)-release

### Current Warp version

v0.2023.07.04.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

7 July 2023

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

Ignore

**Comment by dannyneira** [comment] 2023-07-11 22:05
Thanks for this feature request! 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by khanakia** [comment] 2023-07-12 05:48
It's the default feature in OSX Terminal you can check.

**Comment by dannyneira** [comment] 2024-01-03 17:23
Hey @khanakia This feature has been added to the latest version of Warp. Please update and let us know of any issues with the feature.

Closing as completed

**Closed by dannyneira** 2024-01-03 17:23 UTC
Labels: Feature

**Comment by timkley** [comment] 2024-01-26 08:25
@dannyneira is there a setting for this? I'd rather have the tab be opened at the end of all my other tabs as I often have 3 or 4 "pinned" sessions open.

Thanks for considering :)

**Comment by tomeresk** [comment] 2024-01-30 10:37
I think #4106 is related/caused by this feature (couldn't find any option in settings to disable this behavior)

**Comment by khanakia** [comment] 2024-01-30 11:26
I prefer to open tabs next to the current tab and this is the default behavior of macOS terminal too

So I think adding a configuration option would be better.
