### ISSUE TITLE
Rearranging tabs using a mouse 

### ISSUE THREAD

**Issue by rootex-** [warpdotdev/Warp#2156] opened 2022-11-17 09:26 UTC
### Describe the solution you'd like?

```text
Rearranging tabs using a mouse
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment] 2022-11-18 00:34
Hi @rootex-, Thanks for this feature request! 

It's actually a duplicate of an existing request #58. Closing this one, but please +1 that request as it helps us gauge interest. We will post any updates there.

**Closed by dannyneira** 2022-11-18 00:34 UTC
