### ISSUE TITLE
Multiline prompt doesn't display correctly

### ISSUE THREAD

**Issue by fj** [warpdotdev/Warp#5034] opened 2024-06-17 16:54 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

My prompt is three lines. A typical example looks like this:
![Screenshot from 2024-06-17 12-50-51](https://github.com/warpdotdev/Warp/assets/57813/a62e3e65-6bf7-4674-ba5e-fd1ee2c4618a)

Warp renders this as one line:
![image](https://github.com/warpdotdev/Warp/assets/57813/9471c7b7-0530-474a-a8c2-f4e0eeb1223d)

### To reproduce

Configure your shell to have multiple lines as an output prompt with an intermediate right-alignment.

Run Warp. Select the shell prompt.

The shell prompt will be displayed incorrectly.

### Expected behavior

The prompt displays correctly, on multiple lines, as in my first screenshot.

### Operating system

Linux

### Operating system and version

Ubuntu 24.04 LTS. The uname -a output is: `Linux starlight 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`.

### Shell Version

fish, version 3.7.0

### Current Warp version

v0.2024.06.11.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

N/A

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-06-19 00:13
Thanks for submitting this @fj 

We already have a request tracking this over at #2304 same line prompt support. Warp currently renders the input and the prompt in separate lines.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-19 00:13
Duplicate of #2304

**Closed by dannyneira** 2024-06-19 00:13 UTC
Labels: Bugs

**Comment by fj** [comment] 2024-06-19 00:24
Hi Danny — I think #2304 is not a duplicate. For me it's not that the
prompt and the input are on separate lines. It's that the prompt is
incorrectly forced into one line.

In other words, if you resolved #2304 by putting the input right after the
prompt, that would not resolve this. Similarly, if you were able to render
my multiline prompt correctly, that would solve this issue but would not
resolve #2304 (and based on the comments from @Advait-M it looks like #2304
might be tricky in that regard).

Does that make sense? Happy to elaborate further if that'd be helpful.

**Comment by thehedgefrog** [comment] 2024-06-20 21:57
@dannyneira I have the same issue as @fj as explained in the last comment.

**Comment by dannyneira** [comment] 2024-06-20 22:11
Thanks for your patience folks. The new prompt work would include the support for 3 lines or a single line, however you setup the PS1 prompt in traditional terminals is how it should show up in Warp. 

Here's a quick demo of our Dev build (yellow terminal) vs stable build (white terminal). We're still working on the feature and should be rolling it out soon!

https://github.com/warpdotdev/Warp/assets/16809145/f58133dc-e678-4516-8b36-dea231e51863

**Comment by fj** [comment] 2024-06-24 22:35
Thanks @dannyneira -- I agree with your comment that if this makes it to the main build, it would resolve this issue. Thanks for your work on Warp!

**Comment by dannyneira** [comment] 2024-06-24 22:38
It's coming soon! We have a partial rollout now (in case there are any major bugs) and are looking to do the full rollout in July 2024. Thanks for your patience folks!

**Comment by Advait-M** [comment] 2024-06-24 22:39
Yep 😄, we'll support multiline prompts as a part of #2304's rollout (currently at 10%, ramping up later as Danny mentioned)! This was specifically something we wanted to support - hence we're terming this "same line prompt" rather than "single line prompt" haha i.e. command on the same line as the last line of the prompt 👀 !

As a sidenote, this will also help support more prompt plugins (such as Starship) in bash and fish since we've reworked how we pass prompt bytes from the shell (we'd already done this earlier for zsh)!

**Comment by Advait-M** [comment] 2024-06-24 22:41
I think the issue you were originally seeing here is actually caused by how we pass prompt bytes in fish (as you noted the fish shell above). See here for an example of tide + fish with same line prompt @fj : https://github.com/warpdotdev/Warp/issues/2304#issuecomment-2187369212
