### ISSUE TITLE
Can't install on Ubuntu 24.04.1 TLS

### ISSUE THREAD

**Issue by psantosl** [warpdotdev/Warp#5373] opened 2024-10-11 21:32 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I installed it using sudo dpkg -i ./warp-terminal_0.2024.10.08.08.02.stable.02_amd64.deb

But then I see nothing, blank weird screen:
![image](https://github.com/user-attachments/assets/067b8265-45c5-4154-b614-31a99ca22e58)

### To reproduce

Install it with sudo dpkg -i ./warp-terminal_0.2024.10.08.08.02.stable.02_amd64.deb (or with the default instructions) and start warp.

### Operating system

Linux

### Operating system and version

Ubuntu 24.04.1 TLS

### Current Warp version

GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-10-11 22:15
Hi @psantosl sorry to hear about this, can you try installing warp with the following command on your regular terminal?
```
sudo apt update && sudo apt install warp-terminal
```

**Comment by pablosantosluaces** [comment] 2024-10-11 22:34
Same issue.

Here go the logs.
[warp-logs.zip](https://github.com/user-attachments/files/17347853/warp-logs.zip)

**Comment by aminya** [comment] 2024-10-13 09:07
If it fails to open, the issue is Wayland. See the solution here:
https://github.com/warpdotdev/Warp/issues/5367#issuecomment-2408890422

**Comment by pablosantosluaces** [comment] 2024-10-16 20:03
I tried

WAYLAND_DISPLAY=Z warp-terminal

from a terminal, but exactly the same behavior, I just see a blank window:
![image](https://github.com/user-attachments/assets/13e58fb6-66fd-4be0-9a1e-9917b36e28fc)

What I'm supposed to do?

**Comment by yajkotak** [comment] 2024-10-19 02:50
I tried installing the ARM64 version of Warp on Ubuntu, which I’m running on VMware Fusion Pro for my M1 Mac. After going through the whole setup, I ended up with the same issue—a blank screen. Everything seemed fine during the installation, but once I launched it, nothing showed up. I’m guessing it has something to do with compatibility between the ARM architecture and the virtual machine on the M1, but I’m not entirely sure what’s causing it to hang like that.

<img width="1317" alt="Screenshot 2024-10-18 at 7 48 14 PM" src="https://github.com/user-attachments/assets/ddbd02b7-c78d-4710-b9a0-9eeb9f3dae6d">

**Comment by dannyneira** [comment] 2024-10-25 19:41
Thanks for letting us know @psantosl 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/4598 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Closed by dannyneira** 2024-10-25 19:41 UTC
Labels: Bugs
