### ISSUE TITLE
Unexpected loss of permission on MacOS

### ISSUE THREAD

**Issue by jordanwegener** [warpdotdev/Warp#5415] opened 2024-10-24 23:28 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

There are closed issues to do with this, but I wanted to share as I found a solution.

I've been seeing Warp, seemingly at random, lose permission to execute anything to do with the filesystem - even `ls` is not permitted. Typically restarting Warp will fix this. But I found a solution that seemed to fix it without having to restart Warp.

There is a second executable listed in Privacy & Security settings called 'old' which appears to be associated with Warp. Giving this full disk access appears to solve the issue.

![image](https://github.com/user-attachments/assets/eb1e5497-cec8-49d5-aabe-5293c6be17cf)

### To reproduce

1. Use Warp for an extended period of time without closing/reopening on MacOS
2. Try to use commands like `ls`

### Expected behavior

The command executes as expected

### Operating system

MacOS

### Operating system and version

macOS 15.0.1 (24A348)

### Current Warp version

v0.2024.10.15.08.02.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-10-31 20:22
Hi @jordanwegener Sorry to hear about this, do you still see the same issue if you grant Warp `Full Disk Access`?

**Comment by dannyneira** [comment] 2024-10-31 21:31
Duplicate of https://github.com/warpdotdev/Warp/issues/3009

**Closed by dannyneira** 2024-10-31 21:31 UTC
Labels: Bugs
