### ISSUE TITLE
Window size customization

### ISSUE THREAD

**Issue by Zaberahmed** [warpdotdev/Warp#5080] opened 2024-07-01 05:58 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Currently in the settings I can set the new window size width and height which is great but it only works if I open another window instance at that time. If I reopen warp, I get warp default size window not my custom size. Also, when I 'exit' a window session, it resets to default size.

### Is your feature request related to a problem? Please describe.

Sometimes I want to exit the session to not continue with further, but it resets to default size. I want to keep my customized window size untill and unless I change it.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-07-01 22:11
Thanks for letting us know @Zaberahmed 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/4011 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-07-01 22:12
Duplicate of https://github.com/warpdotdev/Warp/issues/4011

**Closed by dannyneira** 2024-07-01 22:12 UTC
Labels: Feature requests

**Comment by Zaberahmed** [comment] 2024-07-04 19:05
@dannyneira thanks for letting me know. I checked the video provided in #4011 and I have the same issue.
