### ISSUE TITLE
Print ALL output

### ISSUE THREAD

**Issue by Integralist** [warpdotdev/Warp#4040] opened 2024-01-08 16:15 UTC
### Describe the solution you'd like?

I would like Warp to print ALL the output from my programs.

### Is your feature request related to a problem? Please describe.

It's very frustrating when I have a program providing large amount of output and as I jump back to the top of the command execution I find it'll be half way through what _was_ the output because of some kind of buffer scroll limit has been reached.

### Additional context

When possible (which isn't always possible due to idempotency reasons) I have to re-run my command and tee output to a file instead.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-09 00:44
Thanks for submitting this @Integralist!

We already have a request tracking this over at #610 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-09 00:44
Duplicate of #610

**Closed by dannyneira** 2024-01-09 00:44 UTC
Labels: Feature
