### ISSUE TITLE
Focus follow mouse / activate the split pane under mouse cursor

### ISSUE THREAD

**Issue by ryenus** [warpdotdev/Warp#4827] opened 2024-04-26 05:36 UTC
### Describe the solution you'd like?

Always having to click on a split pane to make it focused feels annoying ;-)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-26 21:38
Thanks for submitting this!
We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2551

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-04-26 21:38
Duplicate of https://github.com/warpdotdev/Warp/issues/2551

**Closed by dannyneira** 2024-04-26 21:38 UTC
Labels: Feature requests
