### ISSUE TITLE
Add ability to disable blocks entirely

### ISSUE THREAD

**Issue by x48115** [warpdotdev/Warp#3227] opened 2023-06-21 06:37 UTC
### Describe the solution you'd like?

Expected results: Click anywhere in a pane to active command input.
Actual results: If a pane I clicked on is already active a block is selected instead.

My use case:
I am often context switching between warp and other apps. I don't always remember what pane was active last. To make sure, when I command tab back to warp I click the pane I want to work in. If the pane is already active though a block is selected. In order to actually get to the text input I either need to double click the block again or press tab which is an annoyance because this happens all the time/constantly.

I have no use case for blocks. All I want is a simple pane that shows all historical results. To me blocks over-complicate terminal (I already have tabs and panes, why do I need another subdivider?) and I would prefer an option to disable them completely. Blocks don't make things easier for me, they crowd the UI and I prefer something more simple.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-06-21 15:44
Thanks for submitting this @x48115 At this time there is no intention to disable Blocks as it's an integral part of Warp and would require significant refactoring of the codebase. Regarding your pain point of having to click on the input twice there a request tracking this over at https://github.com/warpdotdev/Warp/issues/739 it's being worked on and should be fixed in an upcoming build.

As a workaround, you can also click on Warp and press `CMD-L` to quickly jump to the [input editor](`CMD-L` to quickly jump to the input editor).

We'll be closing this as a duplicate of the foregrounding issue and there is no intention to disable Blocks in the near future.

**Closed by dannyneira** 2023-06-21 15:44 UTC
Labels: Feature
