### ISSUE TITLE
Add ability to integrate with additional large language models (LLMs)

### ISSUE THREAD

**Issue by davefollett** [warpdotdev/Warp#3442] opened 2023-07-28 04:28 UTC
### Discord username (optional)

davefollett#1510

### Describe the solution you'd like?

```Text
Currently the AI feature is great, but its limited to only working with OpenAI. It would be great if warp could integrate with additional services as well.  Perhaps this could be an extension point for a plugin at some point.
```

### Is your feature request related to a problem? Please describe.

Not all folks can use OpenAI due to corporate policies.  This feature could allow those folks to chose and AI solution that is approved.  Or even allow them to use a locally running AI service.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2024-02-08 18:24
Thanks for submitting this @davefollett 

We will be tracking this over at #3779

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-08 18:24
Duplicate of #3779

**Closed by dannyneira** 2024-02-08 18:24 UTC
Labels: enhancement
