### ISSUE TITLE
Client referral count stays at 0 - not accounting for referrals properly

### ISSUE THREAD

**Issue by glensargent** [warpdotdev/Warp#3270] opened 2023-06-28 08:46 UTC
### Discord username (optional)

glenfs

### Describe the bug

I've done referrals for warp before, only 1 or 2, but the referral count in the client says 0. I've provided proof of a referral in the screenshot section but had to cut it short to censor the email, I can provide more if needed

### To reproduce

Steps unclear, I've done a referral before and there's no progress or state change on the client

### Expected behavior

Display current number of referrals in the warp client

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/10516792/8dc3e570-b411-47a6-b977-abf27122ab4f)
![image](https://github.com/warpdotdev/Warp/assets/10516792/8b11b4f3-6c96-4fc5-bd88-84ccb21168a3)

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-06-28 16:09
Thanks for letting us know @glensargent I wasn't able to reproduce this issue. 

Just to clarify, we now only count a user who onboards onto Warp as a real referral. So the referrals would need to onboard ( login and create a block ) for it to count. Im not sure that the issue you're facing here, but you can learn more about the program here: https://docs.warp.dev/getting-started/refer-a-friend

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by dannyneira** [comment] 2023-07-06 16:50
Closing this one as we can't reproduce or find an issue with the referral counting logic.

**Closed by dannyneira** 2023-07-06 16:50 UTC
Labels: Bug
