### ISSUE TITLE
DUP: Duplicate of #544 - ^W default behavior with clipboard

### ISSUE THREAD

**Issue by gmiam** [warpdotdev/Warp#757] opened 2022-02-17 13:49 UTC
### Describe the solution you'd like?

```shell
Today the ^W shortcut (which delete the word on the left) replace the clipboard by the cut word. As far as I know this is not the default behavior on any terminal I used in the past.

Is it possible to change that? Or make it optional?

Thanks!
```

### Is your feature request related to a problem? Please describe.

```shell
Often I just want to reuse an old command and just replace one word in it. So I have something in my clipboard, I just want to delete the word with a shortcut and then paste what I have in my clipboard. So I need to keep my clipboard as it is.
```

**Comment by elviskahoro** [comment] 2022-02-18 05:23
Closing as it's a duplicate of:
- #544

**Closed by elviskahoro** 2022-02-18 05:23 UTC

**Comment by dannyneira** [comment] 2023-04-28 16:43
Hey Folks! Just wanted to give you a quick update - as @akwodkiewicz mentioned, we've fixed the issue with the latest version of Warp `v0.2023.04.25.08.05.stable_00`.

I'll go ahead and mark this task as complete, but if you notice anything else, feel free to give us a heads-up. Thanks!
