### ISSUE TITLE
Font size change in both the emulator and the desktop app.

### ISSUE THREAD

**Issue by mugiwara-katta** [warpdotdev/Warp#4968] opened 2024-05-31 12:32 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

In the appearance section under the text sub-section the font is only being affected to the font in the emmulator not the app. The app font that is visible when we hover over the settings icon or the Warp essentials icon is too small to read. it would be great if we can increase the font size of these texts as well. 

### Is your feature request related to a problem? Please describe.

I am unable to view the text when I hover over the buttons or icons in warp app. it is too small for me to read. 
![warp_font_issue](https://github.com/warpdotdev/Warp/assets/86163387/17d88982-a1ec-4697-ac36-0df16a2695c8)

### Additional context

The font rendering in Linux is too bad. The fonts are not clear at all. No matter how much I zoom in these fonts while i hover over the buttons and icons are too bad, 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-31 22:55
Thanks for submitting this @

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1443

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-31 22:55
Duplicate of https://github.com/warpdotdev/Warp/issues/1443

**Closed by dannyneira** 2024-05-31 22:55 UTC
Labels: enhancement
