### ISSUE TITLE
cannot select current command if still running and there's no output

### ISSUE THREAD

**Issue by hferreiro** [warpdotdev/Warp#3709] opened 2023-09-27 09:35 UTC
### Describe the bug

When executing a long-running command, if there's no output, the command text cannot be selected in order to copy it.
I have to wait until there's output or the command finishes to be able to do that.

### To reproduce

1. Run `sleep 10`.
2. Try to select the command text.

### Expected behavior

It should be possible to select the current command just after pressing enter.

### Operating system

MacOS

### Operating system and version

macOS 13.5.2

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-09-27 16:33
Hi @hferreiro thanks for letting us know. I wasn't able to reproduce this issue on my end. Could you please provide a video of the issue along with a redacted (personal info removed) copy of your `.zshrc` file(or bashrc/fish.config)? This will help us with narrowing down the root of the issue.

**Comment by hferreiro** [comment] 2023-09-29 13:07
I emptied my `.zshrc` to record the video.

https://github.com/warpdotdev/Warp/assets/984737/56878f0f-8140-43e1-ac0c-d269700994b7

**Comment by zachlloyd** [comment] 2023-10-17 16:12
This repros for me and seems to be a bug related to pinning input at the top + compact mode.  Thanks for the report.  @dannyneira mind tracking internally?

**Comment by dannyneira** [comment] 2023-10-17 17:29
Sure thing, added to triage queue

**Comment by dannyneira** [comment] 2023-12-15 20:11
Hi @hferreiro This issue should be fixed in this week's release, please update to `v0.2023.12.12.08.02.stable_04` and above.

Closing as resolved, but please let us know of any further issues.

**Closed by dannyneira** 2023-12-15 20:11 UTC
Labels: Bug
