### ISSUE TITLE
Truncating bash history to 500 items

### ISSUE THREAD

**Issue by pocketpixels** [warpdotdev/Warp#1262] opened 2022-05-04 04:16 UTC
### Describe the bug

```text
Warp appears to truncate the bash history to 500 items? 
Truncating the user's history like this causes data loss that I consider very serious. 
My bash command history is a hugely valuable store of information to me. 
Luckily I have backups of my .bash_history from before I tried out Warp.
```

### To Reproduce

Steps to reproduce:
1. Configure bash to keep a large history (see Additional Context section below)
2. Create a .bash_history file with (for example) 3000 lines
3. Open Warp
4. Run `history`

### Expected behaviour

```text
The history should still contain 3000 commands. 
Instead it has been truncated to the most recent 500.
```

### Operating System

MacOS

### Additional context

```text
I have configured bash's history via my .bashrc as follows: 
shopt -s histappend 
export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=5000
export HISTFILESIZE=100000
```

**Comment by Ahnfelt** [comment] 2022-05-11 09:22
> Truncating the user's history like this causes data loss that I consider very serious. 
> My bash command history is a hugely valuable store of information to me. 
> Luckily I have backups of my .bash_history from before I tried out Warp.

I lost my history as well, and I agree it's a pretty serious issue. 

I had to uninstall Warp after that, because I no longer trust it with my data.

**Comment by bdashrad** [comment] 2022-06-20 18:05
I just ran into this when I attempted to try warp. Luckily I had another session open in iTerm, where I restored my history and uninstalled Warp.

**Comment by bntzio** [comment] 2022-08-30 19:08
I lost my history too, sad day, uninstalling it now.

**Comment by Soromeister** [comment] 2022-09-15 20:44
I can confirm that this bug also happened to me. This is rather serious and should be treated accordingly!

Tagging @warpdotdev-dx and @dannyneira

**Comment by dannyneira** [comment] 2022-09-15 21:01
Thanks for bringing this up all, so sorry that you're having this issue. We're aware and looking into a fix. Will post updates here once resolved.

**Comment by derlin** [comment] 2022-10-11 08:26
Still nothing ? I will also have to uninstall warp if this is not taken seriously. Terminal history is of outmost importance, and should not be altered with.

**Comment by vorporeal** [comment] 2022-11-14 18:11
Hey all - sorry again that this has been an issue for a while.  We've identified a fix; I'll post an update here when it's live.

**Comment by vorporeal** [comment] 2022-12-20 18:41
This should be fixed now; please re-open this issue and let me know if you're still seeing your history truncated!

**Closed by vorporeal** 2022-12-20 18:41 UTC
