### ISSUE TITLE
Use high-contrast foreground color under block cursor

### ISSUE THREAD

**Issue by SethGunnells** [warpdotdev/Warp#2181] opened 2022-11-18 15:02 UTC
### Describe the solution you'd like?

```text
It seems iTerm2 (I haven't compared how other terminal apps do this) causes the foreground color of any character under a block cursor to be some high-contrast opposite color for legibility. (See the screenshots.) Without this feature, using nvim (my editor-of-choice) in Warp is essentially not possible. Unless I'm missing some way to configure this either in Neovim or in Warp.
```

### Is your feature request related to a problem? Please describe.

```text
Without this feature, any character close to the background color of the block cursor is virtually unreadable.
```

### Additional context

# iTerm2 Behavior
![Screen Shot 2022-11-18 at 8 55 57 AM](https://user-images.githubusercontent.com/245822/202734563-9067b0ff-e681-482d-bb15-b82bc8aa2eb7.png)
![Screen Shot 2022-11-18 at 8 56 34 AM](https://user-images.githubusercontent.com/245822/202734577-29d02cd9-49aa-432c-8c89-4a93276686a2.png)

# Warp Behavior
![Screen Shot 2022-11-18 at 9 02 04 AM](https://user-images.githubusercontent.com/245822/202734949-4df3202e-f36f-4b1d-91f6-f8efb339efb7.png)

### How important is this feature to you?

4

**Comment by dannyneira** [comment] 2022-11-18 18:26
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

As a possible workaround, please go to `Settings > Appearance` and tweak the contrast settings at the bottom. I hope that helps!

![CleanShot 2022-11-18 at 11 24 43](https://user-images.githubusercontent.com/16809145/202776495-8e896c10-c5c1-41f8-9a24-87bd602ae9ac.png)

**Comment by SethGunnells** [comment] 2022-11-18 18:32
Thanks for the tip @dannyneira, but it doesn't seem to do me any good in this case. Might be because I have neovim configured to allow 256-bit colors rather than restricting only to the named ones.

**Comment by dannyneira** [comment] 2022-11-29 23:04
Can also try the 'Always' setting for the minimum contrast regardless of named colors. we'll update here if this is being worked on, Thanks!

**Comment by Imericxu** [comment] 2023-02-07 16:31
Having the ability to change the cursor color would also be nice.

**Comment by dannyneira** [comment] 2023-02-07 21:12
@Imericxu The cursor color can be set by the theme or by creating a custom theme.

https://docs.warp.dev/appearance/themes
https://docs.warp.dev/appearance/custom-themes / https://warp-themes.com/

![CleanShot 2023-02-07 at 14 10 21](https://user-images.githubusercontent.com/16809145/217366672-09e50cc6-8e1d-47c0-9f9c-b0bdc810f957.gif)

**Comment by Imericxu** [comment] 2023-02-07 21:30
@dannyneira Thanks for the reply! The issue is just that I can barely see the cursor in my Neovim setup and I was looking for settings like in iTerm2. I could be just missing some highlight/color settings…

**Comment by jinwik** [comment] 2023-02-11 15:35
iTerm2 has two options (cursor color and cursor text color), how do I set it in warp ?
<img width="148" alt="image" src="https://user-images.githubusercontent.com/8286212/218266923-0e2ca0fc-773f-4877-9702-acde2d9883d1.png">

**Comment by dannyneira** [comment] 2023-02-13 16:53
@Imericxu as a workaround, you may need to set the cursor color in neovim specifically. see: https://codeberg.org/dnkl/foot/issues/463

**Comment by cross-cisco** [comment] 2023-06-27 13:36
I have the same issue as noted in #3210, difficult to see the grey cursor on dark background, and nearly impossible if it's positioned over a light character.  Is there a workaround?  I notice it mostly in vim, where seeing the cursor is more important, but I have the same issue at shell prompt too.
I thumbs-up the original issue here.

**Comment by Ashkin** [comment] 2023-11-27 18:28
Also thumbs-up'd here.

This issue can be more frustrating than the screenshots above indicate.  While this mostly happens in vim, it is occasionally extremely frustrating in the shell, repl's, etc. as well.   Example: find the cursor in this (hopefully tiny) screenie
<img width="738" alt="Screenshot 2023-11-27 at 11 24 31 AM" src="https://github.com/warpdotdev/Warp/assets/931712/171e338a-cb2a-41ea-b8f4-ae4068ab92f6">  (It's on the Z)

**Comment by csangonzo** [comment] 2024-02-26 20:40
Same here, using lunarvim, I can barely see the cursor.
<img width="309" alt="image" src="https://github.com/warpdotdev/Warp/assets/76699502/9200f148-93a0-46fc-a1d9-ee6594610fc9">

**Comment by acarl005** [comment] 2024-07-10 21:00
Warp now automatically changes the foreground color for the glyph over the cursor. Closing this issue!

I notice that others have mentioned a related issue: cursors having insufficient contrast compared to the background color (different from the text color's contrast compared to the cursor color). For updates/discussions on that, please see #3210.

**Closed by acarl005** 2024-07-10 21:00 UTC
Labels: Feature requests
