### ISSUE TITLE
workflow command does not work when  screen  attached after log into Ubuntu from mac os.

### ISSUE THREAD

**Issue by bkr-JNPR** [warpdotdev/Warp#4822] opened 2024-04-25 03:59 UTC
### Describe the bug

log in to linux from macbook,  ssh test@192.168.64.2 ,  run screen -x on ubuntu, now try to run any workflow commands, it will fail saying command already running

### To reproduce

just run work flow command attaching scree.

### Operating system

MacOS

### Operating system and version

ubuntu 22.04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-25 23:29
since `screen` is an alt-screen app (like vim, nano, emacs, tmux, etc.) that takes up the entire view, it doesn't quite fully support all the normal Warp features like workflows and completions.

**Comment by dannyneira** [comment] 2024-05-21 21:11
Duplicate of https://github.com/warpdotdev/Warp/issues/4938

**Closed** 2024-05-21 21:17 UTC
Labels: Bugs
