### ISSUE TITLE
Starship Prompt doesn't render properly.

### ISSUE THREAD

**Issue by akashdiphazra** [warpdotdev/Warp#4907] opened 2024-05-12 06:44 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I am using fedora 40 and Starship Gruvbox Rainbow Preset is not rendering properly in warp terminal but is rendering properly on gnome terminal

### Warp Terminal 
![Screenshot from 2024-05-12 12-09-57](https://github.com/warpdotdev/Warp/assets/61003681/43eefab4-0e99-4825-87a1-8bea3cd36753)

### Gnome Terminal
![Screenshot from 2024-05-12 12-10-28](https://github.com/warpdotdev/Warp/assets/61003681/4ca103f3-9516-40b0-9cc1-57b8670e5084)

### To reproduce

Download Starship prompt  and use  Gruvbox Rainbow Preset theme in bash terminal on fedora 40.

### Operating system

Linux

### Operating system and version

Fedora 40

### Shell Version

5.2.26

### Current Warp version

2024.05.07.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Advait-M** [comment] 2024-05-12 20:30
Thanks for reporting @akashdiphazra! So, I believe part of this stems from #2304 and part of this is due to how we handle prompts in Bash. I'm actively working on addressing 2304 and the changes I have _should_ fix these prompt issues 😄 ! No concrete ETA but getting closer to a release-ready state (https://github.com/warpdotdev/Warp/issues/2304#issuecomment-1907563006 has some context on the technical complexity here)!

Could you provide your `~/.config/starship.toml` perhaps? Is it just using this: https://github.com/fang2hou/starship-gruvbox-rainbow? I'd love to confirm my thinking above! Thanks!

**Comment by akashdiphazra** [comment] 2024-05-12 20:39
Yes, It's the default starship theme, nothing has been changed.

**Comment by a1401358759** [comment] 2024-05-13 04:59
![image](https://github.com/warpdotdev/Warp/assets/15830146/f8f97941-4aa9-4801-9a75-bf5fe1212852)
+1

**Comment by nylqd** [comment] 2024-05-17 03:06
same issue in p10k theme with hack nerd font, line height is wired

**Comment by dannyneira** [comment] 2024-05-23 21:57
Hey Folks, We'll be closing this in favor of  https://github.com/warpdotdev/Warp/issues/2304 as this issue is related to the same-line prompt work we're actively working on addressing.

Please follow that issue for updates, we have no firm eta but stay tuned as this is coming soon!

**Comment by dannyneira** [comment] 2024-05-23 21:57
Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Closed by dannyneira** 2024-05-23 21:57 UTC
Labels: Bugs
