### ISSUE TITLE
SSH: Introducing commands that I did not type

### ISSUE THREAD

**Issue by noahprime** [warpdotdev/Warp#2325] opened 2022-12-10 00:42 UTC
### Describe the bug

Only when using ssh, I type a command and lines are input. Ex.) This is the command input copied from Warp. The only thing I typed was 'module purge', which you see on the last line.

```
channel 3: bad ext data
channel 3: bad ext data
channel 5: bad ext data
channel 5: bad ext data
channel 17: bad ext data
channel 12: bad ext data
channel 18: bad ext data
channel 13: bad ext data
channel 16: bad ext data
channel 17: bad ext data
channel 18: bad ext data
channel 19: bad ext data
channel 19: bad ext data
channel 3: bad ext data
channel 3: bad ext data
channel 3: bad ext data
channel 3: bad ext data
module purge
```

This only happens in ssh. This behavior is not happening when using ssh from macOS terminal.

### To Reproduce

1. ssh into some remote machine
2. type anything...

### Operating System

MacOS

### OS Version

macOS 12.6.1

### Shell Version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

### Warp Version

v0.2022.12.06.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by aliayubi** [comment] 2022-12-10 18:39
Have same problem, can't use Warp anymore for the work

**Comment by Yarden-zamir** [comment] 2022-12-12 14:23
Have the exact same problem, it is horrible

**Comment by szgupta** [comment] 2022-12-12 15:53
Hey, sorry about the inconvenience here. We're actively investigating this. Could you confirm the following:
1. Which version of SSH are you using? (`ssh -V`)
2. Did this problem start to happen on the latest version of Warp? Or was it reproducible (or never-tested) with an older version of Warp?

**Comment by noahprime** [comment] 2022-12-12 21:01
> Hey, sorry about the inconvenience here. We're actively investigating this. Could you confirm the following:
> 
> 1. Which version of SSH are you using? (`ssh -V`)
> 2. Did this problem start to happen on the latest version of Warp? Or was it reproducible (or never-tested) with an older version of Warp? Here's an older version to test with: [v0.2022.11.29.08.03.stable_06](https://storage.googleapis.com/warp-releases/stable/v0.2022.11.29.08.03.stable_06/Warp.dmg)

1. OpenSSH_8.6p1, LibreSSL 3.3.6
2. Warp works as expected with the older version. No issues on [v0.2022.11.29.08.03.stable_06](https://storage.googleapis.com/warp-releases/stable/v0.2022.11.29.08.03.stable_06/Warp.dmg)

**Comment by szgupta** [comment] 2022-12-12 21:45
@noahprime are you able to reproduce consistently? If so, would you mind testing a potential fix on a custom build?

**Comment by threevi** [comment] 2022-12-12 23:36
In case it's helpful, I'm seeing the same issue with Warp `v0.2022.12.06.08.03.stable_01`. Using `OpenSSH_8.4p1 Debian-5+deb11u1, OpenSSL 1.1.1n  15 Mar 2022` on the remote machine.

**Comment by aliayubi** [comment] 2022-12-12 23:44
Same issue with `OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017` on remote machine

**Comment by szgupta** [comment] 2022-12-12 23:47
@aliayubi would you be able to test a potential fix? If so, I can email you a custom build to try out. Unfortunately, I haven't been able to reproduce on my end, but still investigating potential causes

**Comment by aliayubi** [comment] 2022-12-12 23:50
@szgupta Yes of course

**Comment by szgupta** [comment] 2022-12-12 23:55
@aliayubi sent an email!

**Comment by aliayubi** [comment] 2022-12-13 00:00
@szgupta Tested the custom built that you sent me and it works fine now & bug as been solved 🥳

**Comment by szgupta** [comment] 2022-12-13 00:30
@aliayubi thanks! I just sent another build to help narrow down the issue further, if you have a sec to test it!

**Comment by gzlkylin** [comment] 2022-12-13 03:17
Same issue

remote machine
> OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013
 
warp 
> v0.2022.12.06.08.03.stable_01

warp run MacOS 13.0.1 (22A400)

**Comment by szgupta** [comment] 2022-12-13 15:05
Sorry for the inconvenience folks. We're going to try to get an update out later today that fixes the issue. 

Thank you for your patience!

**Comment by szgupta** [comment] 2022-12-13 20:42
Hey folks, we just released an update for to address this: `v0.2022.12.06.08.03.stable_02`. Please let me know if you're still seeing the issue.

**Comment by threevi** [comment] 2022-12-13 20:46
@szgupta That seems to have fixed the issue for me! Thank you so much for the incredibly quick resolution!

**Comment by noahprime** [comment] 2022-12-13 21:57
@szgupta The update appears to work for me as well. Appreciate the effort! Sorry I wasn't around to try the test build :/

**Comment by szgupta** [comment] 2022-12-14 00:59
Given a few folks have confirmed the issue is fixed, I'll go ahead and close this out for now. Please feel free to re-open if you're still seeing the problem.

**Closed by szgupta** 2022-12-14 00:59 UTC
Labels: Bug, SSH

**Comment by gzlkylin** [comment] 2022-12-19 03:20
> Same issue
> 
> remote machine
> 
> > OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013
> 
> warp
> 
> > v0.2022.12.06.08.03.stable_01
> 
> warp run MacOS 13.0.1 (22A400)

v0.2022.12.13.08.04.stable_01 has same problem

**Comment by szgupta** [comment] 2022-12-19 03:42
Hey @gzlkylin, is the problem as persistent as before? Also, could you attach a video of the repro so I can get a better understanding of what's occurring in this case?

**Comment by noahprime** [comment] 2023-01-09 18:50
This issue is back again. Warp version `v0.2023.01.03.08.03.stable_01`. macOS Monterey Version `12.6.1`. I can't capture my screen on my work machine but perhaps I can recreate it on my personal laptop later. But also perhaps not, different macOS.
