### ISSUE TITLE
Warp clipboard similar to terminals on Linux and Mac

### ISSUE THREAD

**Issue by kiranb83** [warpdotdev/Warp#2737] opened 2023-03-03 11:59 UTC
### Describe the solution you'd like?

```text
Most terminals in Linux and the default Terminal app in Mac have an internal clipboard. Any text selected using the mouse gets copied here and can be pasted within the terminal by a middle click or using `Cmd + Shift + V` on Mac (I don't know if there's an equivalent keyboard shortcut on Linux).
I find a very nifty way to copy text quickly inside the terminal without worrying about the system clipboard. I was wondering if Warp already has something similar. If not, would it be possible to introduce such a feature?
```

### Is your feature request related to a problem? Please describe.

```text
I wouldn't say this is a problem, but once you're used to this feature in terminals, it feels a bit of a miss not having it.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by igorsantos07** [comment] 2024-02-26 01:26
This actually looks like a dupe of #416? Although the Linux behavior is still absent, see #4329

**Comment by dannyneira** [comment] 2024-03-14 22:27
Hey Folks, we've released middle-click paste support in today's release [v0.2024.03.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.03.14-v0.2024.03.12.08.02).

Closing as resolved, but please let us know of any issues with the improvement.

**Closed by dannyneira** 2024-03-14 22:27 UTC
Labels: Feature requests

**Comment by kiranb83** [comment] 2024-03-19 16:07
Thanks a lot, Danny! Seems to work well atm.
