### ISSUE TITLE
Maximize pane within window

### ISSUE THREAD

**Issue by mirichan** [warpdotdev/Warp#810] opened 2022-03-14 17:12 UTC
### Describe the solution you'd like?

```text
A common workflow for me is to have a handful of panes for logs and one or two interactive ones, all in one window. Occasionally when I want to do heavier terminal work, it's valuable to have a bit more real estate for those interactive panes.

iTerm has a feature where cmd+shift+enter in a pane will maximize it within a window. The interface updates to indicate this, and hitting the same hotkey again will toggle back to the tiled view.

I've been really enjoying Warp, but this feature would help solve some minor friction for me! :)
```

**Comment by elviskahoro** [comment] 2022-03-22 17:44
Duplicate of:
- #417

**Closed by elviskahoro** 2022-03-22 17:44 UTC
