### ISSUE TITLE
✨ Provide completion like fig in VSCode terminal

### ISSUE THREAD

**Issue by jd-solanki** [warpdotdev/Warp#4558] opened 2024-03-14 05:25 UTC
### Describe the solution you'd like?

I would like WARP to bring the completion in vscode terminal like fig does.

### Is your feature request related to a problem? Please describe.

Hi 👋🏻 

Thanks for WARP, I'm replacing linux terminal & iterm2 in my mac with WARP. I noticed when I run commands in VSCode terminal I don't get completion like Fig in my VSCode terminal by WARP.

Below is screenshot of completion when i use VSCode terminal by fig:
<img width="821" alt="image" src="https://github.com/warpdotdev/Warp/assets/47495003/106330c6-bb5d-423a-97dc-67e838f43cb8">

**Don't get confused because this screenshot is taken from my mac system and I also use the linux system.**

### Additional context

I'm using warp on linux and mac both.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-14 19:45
Thanks for submitting this @jd-solanki 

We already have a request tracking this over at #257 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-14 19:45
Duplicate of #257

**Closed by dannyneira** 2024-03-14 19:45 UTC
Labels: Feature requests
