### ISSUE TITLE
Too many arguments error

### ISSUE THREAD

**Issue by moisesrodriguez** [warpdotdev/Warp#2254] opened 2022-11-29 19:16 UTC
### Describe the bug

The warp terminal on intialization tris to execute a welcome message (I think) and it always show the following message:

```
warp_precmd:cd:24: too many arguments
warp_precmd:cd:24: too many argumentsecho -e "$(cat "/Applications/Warp.app/Contents/Resources/assets/onboarding/welcome_to_warp.txt")"
zsh: command not found: warp_precmd:cd:24:
```

The annoying part is that after every command it appends the following error

```
warp_precmd:cd:24: too many arguments
```

### To Reproduce

1. Open Warp
2. Enter any commands

### Screenshots

On app initialization:
![Screenshot 2022-11-29 at 13 14 08](https://user-images.githubusercontent.com/3869040/204624219-d92e7d4d-3b4b-4514-8b64-43b9e8efd4a4.png)

Typing a command: 
![Screenshot 2022-11-29 at 13 09 55](https://user-images.githubusercontent.com/3869040/204623456-aa2c27fa-911b-4330-bf5a-7e0dc95cac65.png)

Another command:
![Screenshot 2022-11-29 at 13 12 43](https://user-images.githubusercontent.com/3869040/204623990-b355574a-dbeb-42db-afcc-5a6b8ec0ea7a.png)

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.1.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment] 2022-11-29 19:57
Hi Sorry about this, we're looking into this issue and trying to reproduce it. We'll post any updates here.

**Comment by dannyneira** [comment] 2022-11-29 20:47
@moisesrodriguez You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs.

**Comment by moisesrodriguez** [comment] 2022-11-29 21:01
Hi @dannyneira that did the trick. I had to restart for the changes to take effect

![Screenshot 2022-11-29 at 14 57 13](https://user-images.githubusercontent.com/3869040/204646046-ac5c85b2-a56c-410c-aced-c203ec273c94.png)

Reading the [known issues](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files) I do have Powerlevel10K configured in my machine. When I have time will apply `if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then` to figure out the culprits if any other than Powerlevel10K

**Comment by dannyneira** [comment] 2022-11-29 21:08
Great to hear! thanks for letting us know. P10k one is not supported right now, and there may be others like oh-my-zsh plugins/themes, so be on the lookout for those. 

Also, for a custom prompt workaround, I recommend starship.rs which is currently [supported](https://docs.warp.dev/features/appearance/prompt) in Warp.

**Comment by dannyneira** [comment] 2022-11-29 21:11
closing as resolved due to unsupported plugin

**Closed by dannyneira** 2022-11-29 21:11 UTC
Labels: Bug
