### ISSUE TITLE
add tmux support

### ISSUE THREAD

**Issue by sachinchaudhary1808** [warpdotdev/Warp#4887] opened 2024-05-07 16:46 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

pls add tmux support 

### Is your feature request related to a problem? Please describe.

yeah tmux dosen't work 

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-07 17:30
Duplicate of #501

**Closed by dannyneira** 2024-05-07 17:30 UTC
Labels: Feature requests
