### ISSUE TITLE
Starship design broken at v0.2024.07.09.08.01.stable_00

### ISSUE THREAD

**Issue by nyxb** [warpdotdev/Warp#5123] opened 2024-07-13 13:45 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The design is broken after i updated to the latest version. the carret is not on the right position.

### To reproduce

idk use starhip with nerdfonts and update warp?

### Screenshots

![NyxbShot-2024-07-13-at-15 42 21@2x](https://github.com/user-attachments/assets/683954b7-9f0a-4ef6-8bd1-d9ea5a89d21d)

### Operating system

MacOS

### Operating system and version

14.5 (23F79)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.07.09.08.01.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment] 2024-07-15 13:31
Hey @nyxb, thanks for filing! Could you elaborate on exactly what's wrong in the screenshot above? A before and after screenshot would especially be useful. Thank you!

**Comment by nyxb** [comment] 2024-07-15 13:42
> Hey @nyxb, thanks for filing! Could you elaborate on exactly what's wrong in the screenshot above? A before and after screenshot would especially be useful. Thank you!

oh I just see you can't see the carret on the screenshot. A before and after picture would probably not help either. I can visualize it again in a moment. The fact is that the carret is no longer under the Apple sign but 5px further to the right and now there is no more space. In other words, he has a top-5 so to speak

**Comment by Advait-M** [comment] 2024-07-15 14:54
> > Hey @nyxb, thanks for filing! Could you elaborate on exactly what's wrong in the screenshot above? A before and after screenshot would especially be useful. Thank you!
> 
> oh I just see you can't see the carret on the screenshot. A before and after picture would probably not help either. I can visualize it again in a moment. The fact is that the carret is no longer under the Apple sign but 5px further to the right and now there is no more space. In other words, he has a top-5 so to speak
> 
> ok here is a screenshot normally the carret is on the red position but the green carret is the real carret now ![NyxbShot-2024-07-15-at-16 24 08@2x](https://private-user-images.githubusercontent.com/98586665/348741161-a592e0a8-b3b5-4903-8d14-a85af0eeaa03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTU0MzgsIm5iZiI6MTcyMTA1NTEzOCwicGF0aCI6Ii85ODU4NjY2NS8zNDg3NDExNjEtYTU5MmUwYTgtYjNiNS00OTAzLThkMTQtYTg1YWYwZWVhYTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE0NTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNDRkNWYwODQ0NjUwOTJjOTVlMzc1MzQ1MjFmNjYyYzZlYTllNGQwNWU0MTYwY2ZlMDlmMTY1YzdlMjY5MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcGndlCkpflKrfK7i-z_1XQDSBBKVowtabDfMx6bxx4)

Thanks for elaborating @nyxb - to confirm, the issue is that the red "cursor" is not aligned correctly with the green cursor for text? 

Could you please provide your Starship toml config file and which nerdfont you're using in Warp + what line height & font size you're using? Looking to repro this issue so we can help debug it!

**Comment by Advait-M** [comment] 2024-07-15 16:32
Or do you mean that there's essentially an extra space (or two) on the second line (before the command)? With the red bit being a screenshot annotation/edit that you added @nyxb?

**Comment by nyxb** [comment] 2024-07-15 16:49
> Or do you mean that there's essentially an extra space (or two) on the second line (before the command)? With the red bit being a screenshot annotation/edit that you added @nyxb?

I painted the red line. It is supposed to symbolize where the carret should actually be and where it was before the update. The green one is the current status. My configs have remained the same. Before the last update, everything worked. abwr i like to share the configs

**Comment by iurigustavo** [comment] 2024-07-16 04:27
Same here:

<img width="283" alt="image" src="https://github.com/user-attachments/assets/115e8ff9-f3db-4d84-b65b-6ffb75e0c911">

no new line

**Comment by Advait-M** [comment] 2024-07-17 17:42
> > Or do you mean that there's essentially an extra space (or two) on the second line (before the command)? With the red bit being a screenshot annotation/edit that you added @nyxb?
> 
> I painted the red line. It is supposed to symbolize where the carret should actually be and where it was before the update. The green one is the current status. My configs have remained the same. Before the last update, everything worked. But i like to share the configs

Got it - yep, could you please share your Starship toml config? Didn't see it here, but let me know if I missed it! I currently haven't been able to repro this issue

**Comment by Advait-M** [comment] 2024-07-17 17:43
> Same here:
> 
> <img alt="image" width="283" src="https://private-user-images.githubusercontent.com/4990899/348940228-115e8ff9-f3db-4d84-b65b-6ffb75e0c911.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMzgzNjAsIm5iZiI6MTcyMTIzODA2MCwicGF0aCI6Ii80OTkwODk5LzM0ODk0MDIyOC0xMTVlOGZmOS1mM2RiLTRkODQtYjY1Yi02ZmZiNzVlMGM5MTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMTc0MTAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGRjYjljZDNmOTkyOTkwOThkZGM5Y2JlZTc5NDQ1NTY5Y2QyMGUyYWU3MWY4ZDBkODNlN2ZkNTVjN2Q5ZThiMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1WOTn_ZHibC2BjX9k6lY-nHqz20SJJAzLFOenHFUdmY">
> no new line

I think you're referring to a different topic here - please see https://github.com/warpdotdev/Warp/issues/2304#issuecomment-2223352668 for context here on the recent update. And https://github.com/warpdotdev/Warp/issues/5052 might be helpful for you too.

**Comment by nyxb** [comment] 2024-07-17 17:58
> > > Or do you mean that there's essentially an extra space (or two) on the second line (before the command)? With the red bit being a screenshot annotation/edit that you added @nyxb?
> 
> > 
> 
> > I painted the red line. It is supposed to symbolize where the carret should actually be and where it was before the update. The green one is the current status. My configs have remained the same. Before the last update, everything worked. But i like to share the configs
> 
> 
> 
> Got it - yep, could you please share your Starship toml config? Didn't see it here, but let me know if I missed it! I currently haven't been able to repro this issue

I share my conf next days

**Comment by nyxb** [comment] 2024-07-18 06:28
@Advait-M here are my configs: https://github.com/nyxb/dotfiles

**Comment by Advait-M** [comment] 2024-07-22 22:43
> https://github.com/nyxb/dotfiles

Thanks! I can repro this. Taking a deeper look.

**Comment by Advait-M** [comment] 2024-07-22 22:47
Though, I'm seeing the 1 cell space in iTerm and the default Mac terminal too. @nyxb are you sure this space doesn't exist in your prompt configuration itself 🤔 ? Curious which terminal you were using where this worked correctly?

![image](https://github.com/user-attachments/assets/6d078949-c29d-41df-a06a-82e2dcb71e14)

![image](https://github.com/user-attachments/assets/732fea42-02ba-4d9c-a3d5-322922121ea2)

**Comment by Advait-M** [comment] 2024-07-22 22:54
I wonder if this is related to this bit
```
# Drop ugly default prompt characters
[character]
success_symbol = ""
error_symbol = ""
```

i.e. Starship allows you to override the symbols for this, but it's not overidding the space between the `>` and the command, which leads to the 1 extra space.

Here's a workaround for the Starship behavior that I found, which should get the outcome you want:

in zshrc:
```
eval "$(starship init zsh)"
PROMPT="${PROMPT}"$'\n'
```

in starship.toml:
```
# Drop ugly default prompt characters
[character]
success_symbol = ""
error_symbol = ""
format = ""

[line_break]
disabled = false
```

This gets me this in Warp:
![image](https://github.com/user-attachments/assets/a1994336-8fbf-42e7-8a64-0f26cc076b89)


Hope this helps @nyxb !

**Comment by nyxb** [comment] 2024-07-23 04:39
> I wonder if this is related to this bit
> 
> ```
> # Drop ugly default prompt characters
> [character]
> success_symbol = ""
> error_symbol = ""
> ```
> 
> i.e. Starship allows you to override the symbols for this, but it's not overidding the space between the `>` and the command, which leads to the 1 extra space.
> 
> Here's a workaround for the Starship behavior that I found, which should get the outcome you want:
> 
> in zshrc:
> 
> ```
> eval "$(starship init zsh)"
> PROMPT="${PROMPT}"$'\n'
> ```
> 
> in starship.toml:
> 
> ```
> # Drop ugly default prompt characters
> [character]
> success_symbol = ""
> error_symbol = ""
> format = ""
> 
> [line_break]
> disabled = false
> ```
> 
> This gets me this in Warp: ![image](https://private-user-images.githubusercontent.com/12927474/351133757-a1994336-8fbf-42e7-8a64-0f26cc076b89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MDkwNzQsIm5iZiI6MTcyMTcwODc3NCwicGF0aCI6Ii8xMjkyNzQ3NC8zNTExMzM3NTctYTE5OTQzMzYtOGZiZi00MmU3LThhNjQtMGYyNmNjMDc2Yjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA0MjYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNGM3OGZmY2JhMDk2ZGRmMDIwZjc0NmU0NmViOTUyODliYzNjNTU4OThiMDIxNzdjZTE3NGIyYjE0YzgyN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gAoMcijjpUXkf_WdN3Gcjs0dXOdROzs8wsgsmN3_zqc)
> 
> Hope this helps @nyxb !

First of all, thank you very much. Yes that solves the problem with the space on the left but since your update there is hardly any space from top to bottom, it's very narrow, how do we solve that?

![NyxbShot-2024-07-23-at-06 39 21@2x](https://github.com/user-attachments/assets/d002604e-9bc2-4b8f-a64c-617ec0f6af6c)

**Comment by Advait-M** [comment] 2024-07-23 14:51
Glad to hear that helped!

Ah, you're referring to between the prompt and command @nyxb ? So, we're now more closely matching the "normal/true" custom prompt/PS1 experience from other terminals and inter-mixing the Grid and Input Editor.

As such, we've removed padding here, to allow both to be right beside each other.

I've seen a couple other requests for this - could you perhaps open a new GH issue focused on this and we can use that to gauge interest? What I imagine we could do in the future:
1. Add configuration to introduce padding between the n-1'th line of the prompt and nth line (which is what would help here)
2. Add configuration to introduce padding between the nth line of the prompt and the command

Note that we can only really do this in the Input Editor (not in finished blocks, where the prompt and command are now part of the same grid).

**Comment by Advait-M** [comment] 2024-07-23 14:54
Ah https://github.com/warpdotdev/Warp/issues/5159 looks like this issue actually @nyxb ! I'll follow up there too

**Comment by Advait-M** [comment] 2024-08-02 03:08
I'm going to close this in favour of #5159 to track padding!

**Closed by Advait-M** 2024-08-02 03:08 UTC
Labels: Bugs
