### ISSUE TITLE
Support emacs keybindings throughout the terminal

### ISSUE THREAD

**Issue by chriskrycho** [warpdotdev/Warp#100] opened 2021-08-06 14:35 UTC
**Describe the bug**
Regardless of the setting of the "(Left|Right) Option Key is Meta", <kbd>⌥</kbd> rarely works for me.

**To Reproduce**
1. Enable either or both of the "(Left|Right) Option Key is Meta" options
2. Try to use <kbd>⌥</kbd>-powered commands for navigating, kill, yank, etc.
3. Observe that it doesn't consistently work.

Annoyingly, it works *sometimes*, but I haven't been able to identify under what conditions it does/n't work.

**Expected behavior**
Optimally, a Mac terminal editor should support *all* the features that CoreText supports out of the box. (I understand that that's a lot of work!)

**Screenshots**

Just to verify I have the setting turned on:

<img width="292" alt="Option Key is Meta" src="https://user-images.githubusercontent.com/2403023/128526715-983a504d-0dde-4bb0-9c3a-ef4d04cd1f00.png">

**Desktop (please complete the following information):**

- OS Version: macOS Version 11.5.1
- iMac (Retina 5K, 27-inch, 2019)

**Additional context**

**Comment by gagata** [comment] 2021-08-13 21:24
Hi @chriskrycho! The recent stable release should contain the updated handling of the meta key. Since I was not able to repro your issue, do you mind giving it another try? I hope it's resolved, but let me know if not - happy to take another look at this

**Comment by chriskrycho** [comment] 2021-08-16 13:53
Giving it a look now!

**Comment by chriskrycho** [comment] 2021-08-16 13:57
Still broken, alas. Hitting <kbd>⌥</kbd><kbd>B</kbd>, which should be "move back by a word", just inserts ∫; and hitting <kbd>⌥</kbd><kbd>←</kbd>, which should *also* be "move back by a word", does nothing. Here's an example of the first:

https://user-images.githubusercontent.com/2403023/129575122-dff8e69c-6920-4876-ab0d-b249f388218f.mov

**Comment by gagata** [comment] 2021-08-16 17:47
ooh I see! thanks a lot for the video, it's super helpful - the fix enabled `meta` keybindings in emacs, but not in the rest of the terminal. will take a look at this this week then, just bear with me :)

**Comment by zachlloyd** [comment] 2021-08-16 17:50
Changed the title to reflect what I think the underlying issue is, namely that we don't support emacs keybindings in our input area right now.

I think if you are in a focused emacs session, option as meta works as intended.

**Comment by zheng** [comment] 2021-09-01 16:04
We added a number of emacs bindings to all the editors in our app. We support most "motion" https://www.gnu.org/software/emacs/refcards/pdf/refcard.pdf keybindings now, but not the goto ones. From killing & deleting, we also do support  C-y.

We specifically just added these motion keybindings ones in the last release:
meta-f
meta-backspace
meta-b
meta-a
meta-e
meta-shift-{
meta-shift-}
meta-shift-<
meta-shift->

**Comment by zheng** [comment] 2021-09-02 16:50
From rnp on discord:
It's very nice to see some emacs bindings, but they're really incomplete - I use ^B, ^F, ^P, ^N (and their various shift- and meta- variants), and none of those work.
^A, ^E, and ^K work as expected, so I find missing the back/fwd/prev/next bindings even more jarring

**Comment by elviskahoro** [comment] 2021-12-25 07:07
From @LitoMore
Via #292

### Describe the solution you'd like?

In most place of macOS, we can use Emacs-like keymaps to control our cursor. Such as moving cursor, deleting characters...

But in Warp. I cannot use <kbd>control + n</kbd> and <kbd>control + p</kbd> to replace arrow keys.

Here is some information about the macOS built-in Emacs-like keymaps: https://jblevins.org/log/kbd

Here is a simple list to let you understand the habits of Emacs users:

> _`Any textarea` means any textarea on macOS, such as the textarea in browser, Notes app..._

| Keymap | Function | Any textarea | iTerm / Terminal.app | Warp |
|:-:|:-:|:-:|:-:|:-:|
| <kbd>control + n</kbd> | Down arrow | Yes | Yes | No |
| <kbd>control + p</kbd> | Up arrow | Yes | Yes | No |
| <kbd>control + b</kbd> | Left arrow | Yes | Yes | No |
| <kbd>control + f</kbd> | Right arrow | Yes | Yes | No |
| <kbd>control + t</kbd> | Switch characters | Yes | Yes | No |
| <kbd>control + d</kbd> | Delete right side character | Yes | Yes | No |
| <kbd>control + g</kbd> | Cancel / ESC | Yes | Yes | No |
| <kbd>control + h</kbd> | Delete left side character | Yes | Yes | Yes |
| <kbd>control + a</kbd> | Move to start of line | Yes | Yes | Yes |
| <kbd>control + e</kbd> | Move to end of line | Yes | Yes | Yes |
| <kbd>control + u</kbd> | Delete line | Yes | Yes | Yes |
| <kbd>control + j</kbd> | Return | No | Yes | No |

### Is your feature request related to a problem? Please describe.

I strongly recommend finding an Emacs and Vim expert in your team to be a consultant for this feature.

If there is not. I would like to help.


### Additional context

_No response_

**Comment by elviskahoro** [comment] 2021-12-25 07:07
From @srl295
Via - #292

complete blocker for me. I had to repeat my workflow several times in slow motion to figure out what of my ingrained muscle memory was telling Warp to suddenly shut the tab.

Control-P, Control-A, Control-F, Control-D

I'll come back and try Warp again when this is fixed!

**Comment by elviskahoro** [comment] 2022-01-17 00:11
Moving to #579 so all keybinding related issues are in one place:
- #579

**Closed by elviskahoro** 2022-01-17 00:11 UTC
