### ISSUE TITLE
DUP: Duplicate of #017 - Transparent background

### ISSUE THREAD

**Issue by ghuh** [warpdotdev/Warp#773] opened 2022-02-22 04:41 UTC
### Describe the solution you'd like?

```shell
I love the themes, but it would be nice to also have the option to set a partially transparent background.
```

### Is your feature request related to a problem? Please describe.

```shell
I often put my terminal over a webpage that I want to be able to read while I'm typing in the terminal.  That can't be done currently in Warp.
```

**Comment by elviskahoro** [comment] 2022-02-25 05:23
Duplicate of:
- #017

**Closed by elviskahoro** 2022-02-25 05:23 UTC
