### ISSUE TITLE
Using warp:// makes Warp to crash

### ISSUE THREAD

**Issue by skydiver** [warpdotdev/Warp#3293] opened 2023-07-02 00:02 UTC
### Describe the bug

When trying to launch Warp by using the warp:// protocol, an error message is displayed and app crashes.

This happens only if Warp is not running.

If running, functionality works as expected.

### To reproduce

Open following url: `warp://action/new_window?path=/tmp`

### Expected behavior

When launching Warp with provided url, should open a new window with given path.

### Screenshots

![Screenshot 2023-07-01 at 20 59 01](https://github.com/warpdotdev/Warp/assets/578784/ef6314a1-b9b2-4c9a-9293-d9d6f19dd3b1)

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.06.27.19.34.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-07-07 16:34
Thanks for letting us know @skydiver! Sorry about this blocker. I was able to reproduce the issue, I'll let the team know and we'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by FelixLisczyk** [comment] 2023-07-09 11:53
I encounter the same issue when I try to open Warp from GitHub Desktop. Here is the crash report:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               stable [49574]
Path:                  /Applications/Warp.app/Contents/MacOS/stable
Identifier:            dev.warp.Warp-Stable
Version:               0.1.0 (20230706.152730)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-07-09 13:50:15.4856 +0200
OS Version:            macOS 13.4.1 (22F82)
Report Version:        12
Anonymous UUID:        A118B909-F856-B290-8367-7532812B9512

Sleep/Wake UUID:       1BD9F706-4135-42FB-9511-20C06D627AE8

Time Awake Since Boot: 27000 seconds
Time Since Wake:       16187 seconds

System Integrity Protection: enabled

Crashed Thread:        0  main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called


Kernel Triage:
VM - (arg = 0x0) pmap_enter retried due to resource shortage
VM - (arg = 0x0) pmap_enter retried due to resource shortage


Thread 0 Crashed:: main Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1aa6b8724 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1aa6efc28 pthread_kill + 288
2   libsystem_c.dylib             	       0x1aa5fdae8 abort + 180
3   libc++abi.dylib               	       0x1aa6a8b84 abort_message + 132
4   libc++abi.dylib               	       0x1aa6982f8 demangling_terminate_handler() + 132
5   libc++abi.dylib               	       0x1aa6a7f48 std::__terminate(void (*)()) + 16
6   libc++abi.dylib               	       0x1aa6a7ed8 std::terminate() + 36
7   libobjc.A.dylib               	       0x1aa381670 objc_exception_rethrow + 44
8   Foundation                    	       0x1ab71cbc8 -[NSAppleEventManager dispatchRawAppleEvent:withRawReply:handlerRefCon:] + 416
9   Foundation                    	       0x1ab71c9c4 _NSAppleEventManagerGenericHandler + 80
10  AE                            	       0x1b0af5518 0x1b0ae9000 + 50456
11  AE                            	       0x1b0af4e44 0x1b0ae9000 + 48708
12  AE                            	       0x1b0aedf18 aeProcessAppleEvent + 488
13  HIToolbox                     	       0x1b4026b44 AEProcessAppleEvent + 68
14  AppKit                        	       0x1ad9ee048 _DPSNextEvent + 1408
15  AppKit                        	       0x1ad9ecee0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
16  AppKit                        	       0x1ad9e1344 -[NSApplication run] + 464
17  stable                        	       0x100bd39a4 _RINvMNtNtCsbRx7s1OeyKL_6warpui8platform3appNtB3_10AppBuilder3runNCNvCsc3rkVPGp65w_4warp12run_internals_0EB14_ + 812
18  stable                        	       0x100d9e604 _RNvCsc3rkVPGp65w_4warp12run_internal + 1540
(many more identical lines)
```

**Comment by dannyneira** [comment] 2023-07-10 15:29
Hey Folks, We're working on a fix and should have updates soon! Appreciate your patience while we're working to improve this.

**Comment by ifshizuku** [comment] 2023-07-19 23:33
@skydiver by the way, where can I found the interface usage of the warp:// protocol, thx

**Comment by dannyneira** [comment] 2023-08-11 17:44
@skydiver We've documented the URI scheme here: https://docs.warp.dev/features/uri-scheme

Closing as resolved since this fixed was released in the latest version of Warp.

**Closed by dannyneira** 2023-08-11 17:44 UTC
Labels: Bug
