### ISSUE TITLE
Number of git changes is blocking

### ISSUE THREAD

**Issue by tsatke** [warpdotdev/Warp#2066] opened 2022-11-08 13:22 UTC
### Describe the bug

I love the feature that I can see the amount of changes in the prompt.
However, getting that number seems blocking, and I can't fire any command until it is completed.
I have a huge repo with over 20 years of history, and when working in that directory, I have to wait several seconds after every command before I can fire another command.

<img width="240" alt="Screenshot 2022-11-08 at 14 18 44" src="https://user-images.githubusercontent.com/48135919/200574981-c9669f52-5130-47d7-98bc-badd98f1723f.png">

I've had this issue with iTerm + omz, too, but there I can customize it away. This is not the case here.

### To Reproduce

1. Get a git repo with a huge history.
2. `cd` into it.
3. `echo hello`
4. You have to wait for the prompt to be loaded (see picture above)

### Expected behaviour

I would like to see the prompt immediately without the numbers of git changes.
Then the number should be loaded asynchronously.

### Screenshots

<img width="240" alt="Screenshot 2022-11-08 at 14 18 44" src="https://user-images.githubusercontent.com/48135919/200574981-c9669f52-5130-47d7-98bc-badd98f1723f.png">

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.11.01.08.03.stable_00

### Additional context

Reporting this as error because it's heavily impacting UX and productivity.

### Does this block you from using Warp daily?

Yes

**Comment by szgupta** [comment] 2022-11-08 15:31
Hey @tsatke, sorry to hear that this is blocking you. The new "changed file count" was designed to be loaded asynchronously -- to confirm this, could you turn off the feature (right-click the prompt -> select "Hide changed file count") and confirm if this still repros? 

Currently, the git branch _isn't_ loaded asynchronously, and that might be the underlying cause of the latency (we have plans to improve this)

**Comment by tsatke** [comment] 2022-11-08 16:21
Unfortunately hiding it doesn't change anything about the behaviour (still reproducible).

This issue occurs only in that large repo (other git repos and normal directories are no problem) to emphasise.

(I can only assume that it's related to the changed file count, especially because I had the same issue with other terminal emulators before Warp.)

**Comment by szgupta** [comment] 2022-11-08 16:22
After some more investigation, we believe the latency might actually be coming from your custom PS1 -- currently, we evaluate the shell's PS1 even if the default Warp prompt is being used (we're having internal discussions on how to mitigate this). To confirm this, could you try resetting your PS1 to the default shell PS1 and trying to reproduce the original issue? To reset your PS1, the easiest way might be to add the following to the end of your `zshrc` file:
```
export PS1=""
```

**Comment by tsatke** [comment] 2022-11-08 16:30
That solves the problem. Although `PS1` is empty (also no whitespaces) even if I don't set it in the `.zshrc` file.

Thanks a lot!
Feel free to close this ticket if you think that is an appropriate solution to the problem.

**Comment by szgupta** [comment] 2022-11-08 16:58
Awesome, thanks for confirming! I'll close this ticket since the new `Changed file count` feature hasn't degraded this -- but our team is going to actively work on fixing the underlying issue so that users don't have to reset their PS1 manually to avoid this latency with the default Warp prompt!

**Closed by szgupta** 2022-11-08 16:58 UTC
