### ISSUE TITLE
ambiguous keystroke prompt for warpify shell

### ISSUE THREAD

**Issue by caic99** [warpdotdev/Warp#4644] opened 2024-03-27 03:18 UTC
### Describe the bug

I can't tell whether the key is command + "L", "i" or "|" under the default font. Since this key actually is "i", maybe presenting in lowercase would be better?

### To reproduce

`docker run -it ubuntu`, and waiting for the prompt

### Screenshots

<img width="210" alt="image" src="https://github.com/warpdotdev/Warp/assets/78061359/b1e693c9-e596-488f-86e6-e8537f6f007d">

### Operating system

MacOS

### Operating system and version

14.3.1

### Current Warp version

v0.2024.03.19.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-27 17:16
Hi @caic99 Thanks for the feedback, to keep it consistent all of Warps [Keyboard Shortcuts](https://docs.warp.dev/features/keyboard-shortcuts) are noted in Capital case in the app and our docs. You can change the keybind for "Warpify subshell" to something less ambiguous like `CTRL-Y`, and the update will reflect in the UI.
![CleanShot 2024-03-27 at 11 13 26](https://github.com/warpdotdev/Warp/assets/16809145/4f798e67-5c30-4f7a-8f20-8f3f5a140044)

Hope this helps!

**Comment by caic99** [comment] 2024-03-28 02:32
Hi @dannyneira ,
Using capital cased characters for keyboard shortcut is indeed a common understanding. However, how about using a serif/monospace font for the shortcut?
Thanks!

**Comment by dannyneira** [comment] 2024-03-28 16:32
Thats certainly something to consider. We have a related request tracking that here https://github.com/warpdotdev/Warp/issues/1443

Closing as this is not a bug, and the keybinding can be changed, but please let us know of any issues with the keybind.

**Closed by dannyneira** 2024-03-28 16:32 UTC
Labels: Bugs

**Comment by drwl** [comment] 2024-10-16 02:13
Not contributing value here but I had to google `warpify shell hotkey` and find this thread to understand what the hot key is, very ambiguous
