### ISSUE TITLE
Copy block as image

### ISSUE THREAD

**Issue by arunsathiya** [warpdotdev/Warp#4105] opened 2024-01-25 05:17 UTC
### Describe the solution you'd like?

I really like the block sharing feature! Besides the embed and link options, it'd be nice to copy the block as an image.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-26 19:18
Thanks for this feature request @arunsathiya!

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-01-26 19:19
Duplicate of #3065

**Closed by dannyneira** 2024-01-26 19:19 UTC
Labels: Feature

**Comment by arunsathiya** [comment] 2024-01-26 19:21
Ah, thanks for tracking down the dupe! I should have searched earlier. 😬
