### ISSUE TITLE
Losing wrap functionality after doing a sudo (inside a ssh connection) 

### ISSUE THREAD

**Issue by khoude24** [warpdotdev/Warp#2362] opened 2022-12-14 15:05 UTC
### Describe the bug

Losing wrap functionality after doing a sudo (inside a ssh connection) 

### To Reproduce

- ssh [username]@[server].com  -p  ( the wrap functionality work after the ssh connection ) 
- sudo su
- try to use Wrap feature it dosent't work

### Expected behaviour

Wrap feature should work over sudo on a ssh connection

### Screenshots

![CleanShot 2022-12-14 at 10 01 33](https://user-images.githubusercontent.com/4171752/207630883-83d0c0c1-78bf-49b3-b20e-3d7391ec307f.png)

I don't have the option to switch the prompt when I do a right click

![CleanShot 2022-12-14 at 10 02 39](https://user-images.githubusercontent.com/4171752/207631101-050084b7-1c99-49bc-9586-5eec1c6554ce.png)

### Operating System

MacOS

### OS Version

12.4

### Shell Version

GNU bash, version 4.4.20(1)-release / zsh 5.4.2

### Warp Version

v0.2022.12.06.08.03.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2022-12-14 19:47
Thanks for this, I think it's related/duplicate of #64 Since we don't support Warp functionality like blocks in subshells yet ( sudo su, bash, python, sql, etc. )
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge impact of the bug.

Closing as duplicate.

**Closed by dannyneira** 2022-12-14 19:47 UTC
Labels: Bug
