### ISSUE TITLE
Default window size and position

### ISSUE THREAD

**Issue by tigerkzr** [warpdotdev/Warp#2192] opened 2022-11-20 18:04 UTC
### Discord username (optional)

crashtest#9222

### Describe the solution you'd like?

```text
Ability to set default window size and position for new windows. Or an option to always start new windows with last window size/position.  Including remembering size/position with the "restore windows..." option.
```

### Is your feature request related to a problem? Please describe.

```text
More annoyance than problem, but I am constantly having to resize and reposition the terminal window every time I restart or close all windows and open new.  My personal preference is aligned top left corner ~80% vert screen and ~40% horizontal screen on my laptop. Having new windows start dead center every time is not ideal.  I have tried the hotkey window, but it aligns center horizontally and is set always on top of other windows.
```

### How important is this feature to you?

4

**Comment by elviskahoro** [comment] 2022-11-22 05:54
There should be an open issue for this already, if so, will try to merge this into the other at some point in the future.

**Comment by dannyneira** [comment] 2022-11-24 00:22
Thanks for this feature request!
Closing as a duplicate of https://github.com/warpdotdev/Warp/issues/1399
Please +1 that request as it helps us gauge interest. We will post any updates there.

**Closed by dannyneira** 2022-11-24 00:22 UTC

**Comment by tigerkzr** [comment] 2022-11-24 00:39
Thanks. Whatever I searched for didn't find it. Plus 1'ed
