### ISSUE TITLE
Blocks in language REPLs

### ISSUE THREAD

**Issue by JonathanDCohen** [warpdotdev/Warp#4052] opened 2024-01-10 15:02 UTC
### Discord username (optional)

bbqchickennn

### Describe the solution you'd like?

A common workflow for me is to ssh into a remote VM, where I get my full Warp goodness.  I work in Python a lot these days and often want to spin up a Python REPL to quickly test out ideas.

  While I can use `ipython` to get something like blocks, they aren't as full featured as Warp blocks and this doesn't exist for every language.  It would be amazing if Warp could recognize language REPLs like `python` and`node` and display the sessions in Blocks, with bonus points for Language Server support so they can be syntax highlighted.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-11 21:59
hi @JonathanDCohen Thanks for taking the time to submit. We already have a request tracking this over at #64

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-11 21:59
Duplicate of #64

**Closed by dannyneira** 2024-01-11 21:59 UTC
Labels: Feature

**Comment by dannyneira** [comment] 2024-01-17 22:33
Duplicate of https://github.com/warpdotdev/Warp/issues/4082
