### ISSUE TITLE
Toooo slow to open (M2 chip)

### ISSUE THREAD

**Issue by namasikanam** [warpdotdev/Warp#1751] opened 2022-08-23 03:15 UTC
### Describe the bug

Tooooo slow to open (several minutes)...

### To Reproduce

Just open Warp...

### Expected behaviour

Stuck for several minutes.

### Screenshots

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/22532925/186061146-287c22c6-494c-4b5f-a2ae-68ac679dc9fa.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment] 2022-08-23 13:36
Hey @namasikanam, thank you for filling! Is the delay you are seeing related to a window opening or with an actual session starting (e.g. the "starting zsh..." text appears for a while)?

If it's the latter, are you able to repro with your `zshrc` file commented out? It's possible something in your RC file could be causing the slowness

**Comment by namasikanam** [comment] 2022-08-23 16:15
Thanks @alokedesai 

Both the window opening and the actual session starting are slow, the former may cost less than 1min, the latter may cost several minutes.

[This](https://paste.ubuntu.com/p/zhMs2VpS3H/) is my `zshrc` file.

**Comment by alokedesai** [comment] 2022-08-23 17:20
Thanks @namasikanam! Would you also be able to provide a video from the moment you launch Warp to the moment the session has fully started to help us debug futher?

**Comment by namasikanam** [comment] 2022-08-24 02:29
All right, @alokedesai 

https://user-images.githubusercontent.com/22532925/186304247-9b899674-edb5-445f-914f-99b0be2796d8.mp4

**Comment by qcjackman** [comment] 2022-08-25 03:52
![image](https://user-images.githubusercontent.com/12554120/186570632-e41fba30-1bb7-4475-9718-331a1ad57eef.png)
me too, this is my mac, slowly too! how to resolve?

**Comment by dannyneira** [comment] 2022-08-25 05:55
@namasikanam @qcjackman

Our team is prioritizing fixing this. Would you be willing to share your dotfiles to help us reproduce the slowness? If so, please remove any personal information and email them to [`feedback@warp.dev`](mailto:feedback@warp.dev?subject=slow profile&body=slow rc files.)

config file locations by shell are:

Bash = `~/.bashrc` and `~/.bash_profile`
Zsh = `~/.zshrc` and `~/.zprofile`

**Comment by songxianj** [comment] 2022-08-27 04:19
Experiencing the same thing on my M2 MacBook Air (also my first time using Warp). I added `ZDOTDIR=/` in my `~/.zshenv` as guided in the manual but still, every action from starting up the app is insanely slow and triggers the spinning wheel every time, notably in the preferences panel. The only exception is the terminal area, which runs fairly smoothly when I enter and execute commands.

**Comment by GankLi** [comment] 2022-09-09 03:18
Me to.
Very slow
<img width="233" alt="image" src="https://user-images.githubusercontent.com/11990976/189264982-d311f531-b1b7-445c-86e9-4d45ff1c0d3c.png">

**Comment by dannyneira** [comment] 2022-09-09 19:54
@namasikanam recent update has resolved a lot of slow startup issues, are you still experiencing the same as of the new build v0.2022.09.07.14.56?

**Comment by songxianj** [comment] 2022-09-10 09:06
> @namasikanam recent update has resolved a lot of slow startup issues, are you still experiencing the same as of the new build `v0.2022.09.07.14.56`?

Thanks for your work. Personally, I'm still having the same issues as before. Could it possibly be a problem with Chinese language support? As far as I can tell, all the users who are reporting slowness in this issue are using Simplified Chinese as their OS's display language, me included.

**Comment by namasikanam** [comment] 2022-09-11 18:15
Thanks @dannyneira 

It starts a little quicklier for me (~1min), but still not at a tolerable speed.

**Comment by alokedesai** [comment] 2022-09-12 12:43
@songxianj That's an interesting theory--as a followup what country are you (and other users who are experiencing this issue) based in? If it's all China, there also could be a network request hanging for some reason

**Comment by songxianj** [comment] 2022-09-13 02:05
> @songxianj That's an interesting theory--as a followup what country are you (and other users who are experiencing this issue) based in? If it's all China, there also could be a network request hanging for some reason

That could be a reason why. I am indeed based in China, for your information. I also have a VPN/proxy enabled at all times to connect faster to servers in other countries.

**Comment by alokedesai** [comment] 2022-09-19 12:41
Does this repro if you turn your wifi off?

**Comment by namasikanam** [comment] 2022-09-19 12:59
> Does this repro if you turn your wifi off?

No! It is indeed the reason of the Great Firewall in China!

**Comment by namasikanam** [comment] 2022-09-19 13:01
@alokedesai Is it a way to close automatic network connecting in settings of Warp?

**Comment by alokedesai** [comment] 2022-09-19 13:09
There isn't unfortunately. The fact that the Warp is hanging based on a network request hanging is definitely an issue on our end. 

Do you see anything in the Mac console app for Warp when the hang occurs? See [here](https://macpaw.com/how-to/use-mac-console-app#:~:text=Here%27s%20how%20to%20open%20Console,in%20to%20your%20Apple%20ID.) for details on how to open the Console app. Once it's open, click on "Log reports" and then search for "warp.log".

**Comment by GankLi** [comment] 2022-09-20 02:16
02:06:52 [ERROR] Couldn't download & process file /Users/mac/Library/Application Support/dev.warp.Warp-Stable/AItbvmnKHwoKd73RYsI-gw_TnwEZDKzMKNTXZrKcQQZX=s96-c, error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("**_lh3.googleusercontent.com_**")), port: None, path: "/a/AItbvmnKHwoKd73RYsI-gw_TnwEZDKzMKNTXZrKcQQZX=s96-c", query: None, fragment: None }, source: TimedOut } -- **The Great Firewall in China!**

**Comment by alokedesai** [comment] 2022-09-20 13:25
Thanks @GankLi! We'll get this fixed

**Comment by azouever** [comment] 2022-09-26 01:55
log detail 
01:52:54 [INFO] window resized
01:52:54 [INFO] dispatching global action for workspace:save_app
01:52:54 [WARN] Expected to have session for session ID None, but doesn't exist
01:52:55 [WARN] Failed to record time "sample value too large"
01:53:24 [ERROR] Couldn't download & process file /Users/xukaixuan/Library/Application Support/dev.warp.Warp-Stable/AFdZucp_isGUeTYxFnkUmzapY_Fj9HOyTRXSIC05v-h0fw=s96-c, error: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lh3.googleusercontent.com")), port: None, path: "/a-/AFdZucp_isGUeTYxFnkUmzapY_Fj9HOyTRXSIC05v-h0fw=s96-c", query: None, fragment: None }, source: TimedOut }
01:53:25 [INFO] Start to flush telemetry events to Segment
01:53:54 [ERROR] Couldn't download & process file /Users/xukaixuan/Library/Application Support/dev.warp.Warp-Stable/AFdZucp_isGUeTYxFnkUmzapY_Fj9HOyTRXSIC05v-h0fw=s96-c, error: reqwest::Error { kind
: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("lh3.googleusercontent.com")), port: None, path: "/a-/AFdZucp_isGUeTYxFnkUmzapY_Fj9HOyTRXSIC05v-h0fw=s96-c", query: None, fragment: None }, source: TimedOut }

**Comment by Songwaitter** [comment] 2022-10-10 04:08
It is determined that the problem is GFW, and the previous issue is found.
resolvent
`cd /Applications/Warp.app/Contents/MacOS
export https_ proxy= http://127.0.0.1:7890  http_ proxy= http://127.0.0.1:7890  all_ proxy=socks5://127.0.0.1:7890; ./ stable`

**Comment by vorporeal** [comment] 2022-10-13 19:52
I've submitted a change that I believe should fix this issue (or at least fix part of it); the change will go out in next week's release.

**Comment by GankLi** [comment] 2022-10-24 02:56
@namasikanam 
v0.2022.10.18.08.10.stable_01 is ok.

**Comment by alokedesai** [comment] 2022-10-24 13:30
Great! We'll go ahead and close this issue, please reopen if you're still experiencing this

**Closed by alokedesai** 2022-10-24 13:30 UTC

**Comment by dimitur2204** [comment] 2023-02-22 19:41
I am having the same problem on M1 Pro Macbook Pro 16", with the latest version. For me it's never even starting it just stays on `Starting zsh...` and I also get the `Seems like your shell is taking a while to start...`.

It usually happens on the 2nd tab I open

**Comment by songxianj** [comment] 2023-02-23 02:46
> I am having the same problem on M1 Pro Macbook Pro 16", with the latest version. For me it's never even starting it just stays on `Starting zsh...` and I also get the `Seems like your shell is taking a while to start...`.
> 
> It usually happens on the 2nd tab I open. This is my: .zshrc:
> 
> ```
> export NVM_DIR="$HOME/.nvm"
> [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
> [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
> 
> export PATH="/Users/dimitar.nizamov/Library/Python/3.8/bin:$PATH"
> 
> export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
> export PUPPETEER_EXECUTABLE_PATH=`which chromium`
> 
> export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
> ```
> 
> .zshprofile:
> 
> ```
> eval "$(/opt/homebrew/bin/brew shellenv)"
> export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
> # Add Visual Studio Code (code)
> export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
> # Add Visual Studio Code (code)
> export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
> 
> export PATH="$PATH:$(yarn global bin)"
> ```

This seems like a separate issue. What we experienced before was that the entire app felt sluggish and was not related to the number of tabs opened or the zsh shell starting.

**Comment by dimitur2204** [comment] 2023-02-23 08:20
> This seems like a separate issue. What we experienced before was that the entire app felt sluggish and was not related to the number of tabs opened or the zsh shell starting

Should I create an issue then?

**Comment by gabrielccarvalho** [comment] 2023-03-02 12:52
is this specific bug still happening or got fixed? because my warp don't even open on m2 macbook air... every time I have to force quit the app...

![Screenshot 2023-03-02 at 09 51 51](https://user-images.githubusercontent.com/47671243/222433954-5f5d425f-bf9a-4500-a00e-b7e168b98595.png)

**Comment by abubakar2000** [comment] 2023-03-23 00:30
I even tried updating and removing unnecessary env vars. But still it takes long to open up.
In my case it opens up instantly but is very slow to start.

**Comment by say8425** [comment] 2023-06-16 05:54
same here very slow to start
