### ISSUE TITLE
Docker Warpify doesn't work for sub-shell created from a script or an alias command

### ISSUE THREAD

**Issue by bartosik-hep** [warpdotdev/Warp#4076] opened 2024-01-16 15:54 UTC
### Describe the bug

After I launch a sub-shell in a running Docker container, with an explicit command in the terminal:
```shell
docker exec -it container-name /bin/bash
```
I get a suggestion to **Warpify** this sub-shell, making it identical to launching it from `Docker Desktop > Extensions > Warp` interface, but faster, without the need to choose the Shell command by hand each time.

Yet this **Warpify** suggestion doesn't work if exactly the same command is called from inside another Shell script or via an alias. The corresponding `Ctrl + I` shortcut also doesn't do anything in this case.

This bug forces one to either type the whole command each time or use the Docker GUI, which is suboptimal when opening multiple shells under the same container.

### To reproduce

This works as expected, allowing to Warpify the sub-shell:
```shell
docker exec -it <container ID> /bin/bash
```

In the following cases Warp doesn't detect the sub-shell as Warpifiable:

```shell
alias dshell="docker exec -it <container ID> /bin/bash"
dshell
```

Same when command is put in a script:

```shell
echo "docker exec -it <container ID> /bin/bash" > run.sh
source run.sh
```

### Expected behavior

I would expect Warp to allow worpifying a sub-shell regardless of the exact command used in the console.

### Screenshots

This works:
<img width="390" alt="Screenshot 2024-01-16 at 16 50 37" src="https://github.com/warpdotdev/Warp/assets/5139705/07308d70-0466-4563-a2ab-a917bf681503">

This doesn't work:
<img width="432" alt="Screenshot 2024-01-16 at 16 51 03" src="https://github.com/warpdotdev/Warp/assets/5139705/3a2dd86d-54c5-4315-95a3-c7c27ff7033b">

### Operating system

MacOS

### Operating system and version

Sonoma 14.2.1

### Shell Version

bash 3.2.57(1)-release (arm64-apple-darwin23)

### Current Warp version

v0.2024.01.09.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-16 22:54
hey @bartosik-hep the subshell feature is set up to recognize many commands by default ( like `docker`), but since you're using the alias and scripts to run the commands, you'll have to add them to your Settings > Subshells > "Added commands" menu for them to be recognized for "Warpification". See more in our docs https://docs.warp.dev/features/subshells and my demo of this below:

https://github.com/warpdotdev/Warp/assets/16809145/923a4ee0-e54b-4006-8d5a-9c27fdfdc91c

This way you can work in the docker container while using an alias. Another option would be to use [docker desktop](https://www.docker.com/products/docker-desktop/) + the [Warp extension](https://hub.docker.com/extensions/warpdotdev/warp) which we've made to help launch sessions into containers much easier.

Please let me know if the above was helpful, or if you're still seeing issues with enabling subshell sessions.

**Comment by bartosik-hep** [comment] 2024-01-17 09:43
Thank you for the very comprehensive answer, @dannyneira! It does the trick.
In fact for my specific case, where I have control over the `.bashrc` of the Docker container I'm running, adding the corresponding automatic command to it, as mentioned in the [Warp documentation](https://docs.warp.dev/features/subshells#automatically-warpify-subshells) is the most elegant solution.

If I can suggest one improvement to the Warp extension for  Docker Desktop: it's rare that one uses different shells (and users) for the same container, so it would be great if the last choice for the `User` and `Shell` were remembered by the extensions, saving 2-4 clicks every time a new shell is opened.

There is one more issue, with `TAB` autocompletion for paths starting with `/` in a warpified sub-shell, like shown in the screenshot. Is this known?

<img width="844" alt="Screenshot 2024-01-17 at 10 40 01" src="https://github.com/warpdotdev/Warp/assets/5139705/857b7a6f-9d00-48fc-8d62-eb1b53d233ae">

**Comment by dannyneira** [comment] 2024-01-19 21:01
Hey @bartosik-hep Thanks for the feedback. I'll closed this as resolved since the issue with the alias/script has a workaround. 

Regarding the improvement, docker extension does remember the User/Shell for any existing containers, but doesn't apply those settings by default to new containers. If you can please [submit a feature request](https://github.com/warpdotdev/Warp/issues/new/choose) for that.

Also for the issue with the TAB in a subshell, I'm not seeing what the problem is, you'd see the same running `cd / + TAB` in a local Mac system as well. It normally shows the subdirectories in the parent folder `/`.

Example Ubuntu Subshell:

![CleanShot 2024-01-19 at 14 00 03](https://github.com/warpdotdev/Warp/assets/16809145/65a5cc41-e664-43e6-88ce-50c1ba17af6d)

Example Mac local:
![CleanShot 2024-01-19 at 14 00 39](https://github.com/warpdotdev/Warp/assets/16809145/b10f1219-1684-4db9-bb44-f056fd46365e)

**Closed by dannyneira** 2024-01-19 21:01 UTC
Labels: Bug

**Comment by bartosik-hep** [comment] 2024-01-19 21:06
@dannyneira the problem that it doesn't fetch the subfolders for the root `/` folder in the sub-shell.  If compare what `ls /` shows and what the TAB completion shows in the screenshot, you can see that in the TAB completion case it shows folders from the current directory (`dev/`, `work/`) rather than from the `/` directory (`afs/`, `bin/`, ...).

**Comment by dannyneira** [comment] 2024-01-19 21:11
oh I see, I wonder if the user you're logged into on that subshell has full permissions over the folders in `/`. That may be part of why the completions aren't loading entirely compared to the result of ls. If you can please open a new bug for that as it appears to be a separate issue from the original one (aliases). https://github.com/warpdotdev/Warp/issues/new/choose

**Comment by genzorr** [comment] 2025-04-04 11:19
I ran into the same issue: when using "Warpify subshell" command after entering docker container e.g. using `docker exec -it <container_name> bash`, sometimes tab completion shows paths from the host system and not from inside the container.

The video example [here](https://docs.warp.dev/features/warpify/subshells) shows that this feature can work correctly, and running both `docker run -it ubuntu:latest /bin/bash` or `docker exec` on the same (already running) container does work.

I found that in my case the issue is caused by usage of `--net=host` flag, and removing it leads to tab completion working correctly inside the container.

Not bumping this thread for a fix, but hope this helps someone.
