### ISSUE TITLE
Support "ESC" hotkey binding

### ISSUE THREAD

**Issue by digitalmaster** [warpdotdev/Warp#2109] opened 2022-11-14 15:45 UTC
### Describe the solution you'd like?

I use CMD + ESC to launch iTerm. It's a pretty important habit at this point. When I tried to configure this in Warp it wouldn't let me bind ESC. Did some digging and [looks like](https://docs.warp.dev/features/hotkey-window#how-to-access-it) this is intentional: 

> Also,ESC, BACKTICK, TAB , SHIFT, CAPS are not supported keyboard shortcuts.

Why is that so? iTerm let's me do it and there doesn't seem to be something else bound to it.

### How important is this feature to you?

4

**Comment by patrick-elmquist** [comment] 2022-11-18 07:47
I would like to add a vote for this, also used to CMD+ESC for quake mode in iTerm, would love to be able to use the same for Warp

**Comment by dannyneira** [comment] 2022-12-01 22:43
Thanks for this feature request! Its actually a duplicate of #1851,

Please :+1: and sub to that request as it helps us gauge interest. We will post any updates there.

**Closed by dannyneira** 2022-12-01 22:43 UTC
