### ISSUE TITLE
grpcurl hangs

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#747] opened 2022-02-13 08:59 UTC
### Describe the bug

```shell
From higherkindedtype via Discord: https://discord.com/channels/851854972600451112/940753513221349426/940753514412531773
> [grpcurl](https://github.com/fullstorydev/grpcurl) commands just hangs and never returns
https://github.com/fullstorydev/grpcurl
```

**Comment by countingtoten** [comment] 2022-02-14 16:01
Duplicate of #727

**Closed** 2022-02-16 00:35 UTC
