### ISSUE TITLE
Please, lords, let your people have a single line prompt

### ISSUE THREAD

**Issue by technocrat** [warpdotdev/Warp#4115] opened 2024-01-31 10:53 UTC
### Discord username (optional)

technocrat#3308

### Describe the solution you'd like?

The default prompt
```
~
whoami
```

is inalterable, engraved in stone, a One True Way. That's not you. You've got ideas about how a terminal should work, and they are brilliant. But you also know that one user's delicacy is another's composting.

### Is your feature request related to a problem? Please describe.

I'm unable to undo four decades of
```
$ whoami
```

### Additional context

It comes *this* close to being a deal breaker. Not quite enough, and perfection offends the Buddha says my brother, but it mars an otherwise blissful experience. Please provide an option for the minimalists that don't need space for a tickertape parade.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by Advait-M** [comment] 2024-01-31 20:25
🤣 I truly enjoyed reading this issue - thank you for the poetic flair ❤️. Glad to say **we're actively working on this - #2304 is the canonical issue tracking this 👀** (see there for more detailed updates)!

_Here's a response matching that tone for some fun_ 😛:

Ah, @technocrat, your message strikes a chord in the symphony of our development endeavors! 🌌

Indeed, the quest you've embarked upon, switching to Warp as your daily-driver, challenging the tides of time and tradition, resonates deeply within the hallowed halls of our coding sanctuary. As you rightly pointed out, the single line `$ whoami` of yesteryears, a steadfast rock in the raging river of terminals, calls for a renaissance, a rebirth in the hands of those who dare to dream differently.

And yes, Issue #2304 is the scroll where this epic tale is being chronicled, a saga of reimagining and reinvention!

Under the hood, our wizards are weaving their magic, reworking the core terminal and shell logic, akin to alchemists transforming lead into gold. It's a Herculean task, akin to rerouting the course of a mighty river. But fear not, for we are close to beholding the dawn of this new era.

In the immortal words you've graced us with, we too believe in honoring the "delicacy" of each user's preference, steering clear of the "composting" of rigid convention. We're crafting a space not just for minimalists but for all who seek a canvas to paint their unique command-line experiences.

Stay tuned, noble traveler, for the winds of change are blowing, and soon, you shall steer your terminal ship into uncharted waters, under skies limited only by imagination! The _One True Way_ is within reach, hopefully tis only a few fortnights more 🤞.  

With bated breath and fingers poised over keyboards,
Your Warp Lords 👑 ✨

**Comment by dannyneira** [comment] 2024-01-31 21:01
I express my gratitude for the submission, @technocrat!

Verily, a request akin to this hath already been recorded and is under scrutiny at #2304.

Should thou deign to bestow upon it a gesture of approval (👍) and subscribe to the aforesaid request, it would greatly assist us in measuring the extent of interest. Any further developments shall be communicated in that quarter, hence I bid thee stay tuned!

With due respect, we are inclined to close this matter as a duplicate.

**Comment by dannyneira** [comment] 2024-01-31 21:01
Duplicate of #2304

**Closed by dannyneira** 2024-01-31 21:01 UTC
Labels: Feature requests

**Comment by Advait-M** [comment] 2024-07-11 22:18
@technocrat - a special comment for you since you're featured in this video haha 😄 ! We really appreciated the humour 😂 😍 
_Main thread: https://github.com/warpdotdev/Warp/issues/2304#issuecomment-2223352668_

Today’s the day you have been waiting for :tada:... **The lords have answered the people... the One True Way is now possible 😛** 

<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGpoYjFueDhzd2F3cTFvbmd4endncHE3cjJuZnhyM3cwdHFlNmRuaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5GoVLqeAOo6PK/giphy.gif"/>

**Same Line Prompt (SLP) is officially rolling out to 100% of Warp users!!** Here’s a video commemorating the release… GET HYPED!! 😀

https://github.com/warpdotdev/Warp/assets/12927474/b48e43ca-1dad-4eb7-a62b-b6fef85fe96b

**Please update to `v0.2024.07.09.08.01.stable_00` (latest Warp) to see the changes.** Note that SLP is enforced for shell prompts (PS1) and it is opt-in for Warp prompt (via the Edit Prompt modal). Check out **[docs.warp.dev/appearance/prompt#same-line-prompt](https://docs.warp.dev/appearance/prompt#same-line-prompt)** for our documentation on this.

Thanks for your patience on this - it’s truly been an adventure 🫡 ❤️!

**We’ll also have a long-form YouTube video + blog post coming out next week that goes into a bit of a technical deep-dive into this project.** Keep an eye out for that (I’ll update the thread at #2304 as well)! 👀

**Comment by technocrat** [comment] 2024-07-11 22:41
Wow! Age me 40 years and you’re spot on, only I don’t move that fast.
