### ISSUE TITLE
PATHAN

### ISSUE THREAD

**Issue by Malakmursaleenkhan** [warpdotdev/Warp#3874] opened 2023-11-16 14:23 UTC
### Discord username (optional)

Mursaleen#9595

### Describe the bug

will tell later...now I am kinda tired

### To reproduce

1

### Expected behavior

my bank balance

### Screenshots

hmmmmmmmm

### Operating system

MacOS

### Operating system and version

monterey12.6.8 but now updating to 17 something

### Shell Version

5.8.1

### Current Warp version

v0.2023.11.07.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

16/nov/2023

### Additional context

I am worried about my bank balance...haha-hehe-hooo

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-11-16 22:03
Not clear what the issue is here, closing, but please feel free to open a new bug report with more details on the issue.

**Closed by dannyneira** 2023-11-16 22:03 UTC
Labels: Bug
