### ISSUE TITLE
Support the fallback font

### ISSUE THREAD

**Issue by SimFG** [warpdotdev/Warp#4005] opened 2023-12-28 02:33 UTC
### Discord username (optional)

simfg

### Describe the solution you'd like?

```Text
Sometimes some fonts do not support some special characters, which will cause display errors. We hope that fallback fonts can be supported.
```

### Additional context

![image](https://github.com/warpdotdev/Warp/assets/21985684/047f3c65-f5f6-4fe9-8ccd-9b5c06d4a9d6)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2023-12-28 16:45
Thanks for this feature request @SimFG! 

I found we already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/789

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate, but I added some of your details to that request.

**Comment by dannyneira** [comment] 2023-12-28 16:46
Duplicate of https://github.com/warpdotdev/Warp/issues/789

**Closed by dannyneira** 2023-12-28 16:46 UTC
Labels: Feature
