### ISSUE TITLE
Separate Text vs. Foreground Colour

### ISSUE THREAD

**Issue by Jtango18** [warpdotdev/Warp#3966] opened 2023-12-14 02:27 UTC
### Describe the solution you'd like?

```Text
I'd ideally like to be able to specify a default text colour independently of the foreground colour.
```

### Is your feature request related to a problem? Please describe.

```Text
Currently to get Green text as my text colour in the terminal I need to set foreground to Green. However this has the added (unwanted) effect of applying to the rest of the UI so I end up with the app looking bright green (see attached screenshot)
```

### Additional context

![CleanShot 2023-12-14 at 13 24 39](https://github.com/warpdotdev/Warp/assets/801539/bbc255e3-efa1-4681-8f05-77cb1db26ec1)

![CleanShot 2023-12-14 at 13 25 18](https://github.com/warpdotdev/Warp/assets/801539/ea0de514-0705-4de1-9339-1f344e0d0a5c)

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-12-14 21:21
Thanks for submitting this @Jtango18 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2019

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment] 2023-12-14 21:21
Duplicate of #2019

**Closed by dannyneira** 2023-12-14 21:21 UTC
Labels: Feature

**Comment by Jtango18** [comment] 2023-12-14 22:14
Done. Sorry for the dupe, didn't find 2019 when I was looking 😑

**Comment by dannyneira** [comment] 2023-12-15 23:34
No worries, happy to help!
