### ISSUE TITLE
Flatpack (and snap) packages support

### ISSUE THREAD

**Issue by PieroSimonet** [warpdotdev/Warp#4487] opened 2024-03-06 09:11 UTC
### Describe the solution you'd like?

Some terminal implementations, such as [blackbox](https://flathub.org/apps/com.raggesilver.BlackBox) are already ported to the flatpack package that removes the dependency on a particular distro. Also, it does not require that the app to be open source, but only the build process 

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-07 00:41
Thanks for this feature request @PieroSimonet!

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-04-05 15:52
Hi folks, we'll be tracking support for Flatpak here: https://github.com/warpdotdev/Warp/issues/4662

Please continue to 👍  the topline request there.

Closing as duplicate

**Comment by dannyneira** [comment] 2024-04-05 15:52
Duplicate of https://github.com/warpdotdev/Warp/issues/4662

**Closed by dannyneira** 2024-04-05 15:52 UTC
Labels: Feature requests
