### ISSUE TITLE
Hotkey terminal does not go to the right window

### ISSUE THREAD

**Issue by pierorex** [warpdotdev/Warp#5352] opened 2024-10-03 15:46 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

1. When I have selected the option to show the hotkey window in the active monitor:
If I lock and unlock my Mac, then invoking the hotkey window will place it in a random monitor instead of going to the active one.

2. When I have selected the option to show the hotkey window in a specific monitor:
If I lock and unlock my Mac, then invoking the hotkey window will always place it in my laptop screen instead of the connected monitor I had specified before.

### To reproduce

explained above

### Expected behavior

explained above too

### Operating system

MacOS

### Operating system and version

MacOS Sonoma 14.7

### Shell Version

bash 5.2.26(1)-release (aarch64-apple-darwin23.2.0)

### Current Warp version

v0.2024.09.24.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

never

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-10-04 22:07
Hi @pierorex sorry to hear about this. You may need to go to Mac > System Settings > Desktop & Dock , then enable "Displays have separate Spaces" and the "Active" screen hotkey settings should work after sleep. Please let us know if that helps with your issue.

**Comment by dannyneira** [comment] 2024-10-04 22:16
Duplicate of https://github.com/warpdotdev/Warp/issues/3275

**Closed by dannyneira** 2024-10-04 22:16 UTC
Labels: Bugs

**Comment by pierorex** [comment] 2024-10-07 09:53
But doing that, it only works properly if I have nothing in fullscreen mode
on the Active screen. At the moment that I open an App in fullscreen, then
using the hotkey opens the Warp terminal in the other screen.
