### ISSUE TITLE
Performance slowdown lately

### ISSUE THREAD

**Issue by lucianthorr** [warpdotdev/Warp#4786] opened 2024-04-19 12:54 UTC
### Describe the bug

I habitually keep my Warp terminal up-to-date and I feel like within the last two updates, like in the last week or so, it's having frequent momentary freezes.
Typing commands can have a half second lag before showing up in the UI, Cmd+Q doesn't quit and if I go to the title bar > File > Quit is disabled.
It seems to be caused by event and then things start slowing down or freezing and then I restart and it's fine.  It's very unlike Warp in the past though, which has always been consistently reactive.

### To reproduce

I'm still working on finding a reproducible cause.
My only hint is that maybe it starts happening after an ssh session times out or fails.  But even in this case, when the slowdown happens, it effects all tabs, not just the one handling ssh.

### Expected behavior

The usual snappy response of Warp.

### Operating system

MacOS

### Operating system and version

Ventura

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2024.04.16.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by t-var-s** [comment] 2024-04-19 21:58
I seem to be having the same issue recently with Warp becoming unresponsive. Seems to happen when the terminal has been left open and not used for a while. Or it may be an issue with how updates are being received, this bug does not happen every day. 

I'm currently on Sonoma 14.4.1 and using zsh 5.9 
Warp is on v0.2024.04.16.08.02.stable_00

**Comment by alokedesai** [comment] 2024-04-22 20:06
@lucianthorr @t-var-s Thanks for filing and sorry for the issues here--this definitely isn't how Warp should work.

Do the lags occur only when typing into the input editor or do they occur when using any part of the app? Could you share a video next time you see the behavior?

**Comment by t-var-s** [comment] 2024-04-22 21:15
> Do the lags occur only when typing into the input editor or do they occur when using any part of the app? Could you share a video next time you see the behavior?

I've noticed it as I start to type into the prompt. Warp becomes unresponsive and the option to quit becomes disabled. Since I usually don't have the time to wait, I have to force kill the process and run Warp again. 

BTW, it might also be relevant that I always run Warp full screen on macOS. I'll try to record a video if the bug happens again. Let's see if it coincides with some update dropping.

**Comment by alokedesai** [comment] 2024-04-24 16:04
Thanks! A video here next time you see this would be really useful so we can debug further.

**Comment by t-var-s** [comment] 2024-04-25 20:04
At least in my case, it does seem related to getting an update. After Warp updates, instead of showing the usual What's New panel, the terminal stops at loading the prompt and the option to quit is disabled. Here's a video:

https://github.com/warpdotdev/Warp/assets/6660327/fd983995-522d-48a8-a4cd-b67e484716d8

If I force quit and restart Warp, it now behaves normally and shows what's new.

**Comment by lucianthorr** [comment] 2024-04-25 20:37
Apologies for the silence here.  I haven't needed SSH much this week so I haven't had the opportunity to test.
I can confirm that the disabled Quit shown above was present during my freezes also though.  Thanks @t-var-s

**Comment by lucianthorr** [comment] 2024-04-26 13:58
Not exactly the same thing but evidence of something weird going on.
Warp was left in full screen last night.  When I plugged my external monitor back in and opened the laptop this morning, the desktop that should've been Warp was a black screen, that disappeared when I pressed Fn+f to disable fullscreen.
Then, as captured, you can see that I can go to Warp but none of the toolbar functions work.  Also, Cmd+Q wasn't working to quit Warp. 
If there's a log somewhere that I can grab, just let me know.  Hope this helps.
https://github.com/warpdotdev/Warp/assets/5907505/57bd58ab-4b54-497a-9e8d-6b0c3ec18c69

**Comment by TowhidKashem** [comment] 2024-04-28 06:43
I came here to look up if anyone else is having issues as of late too! In the past I never dif but as of the last few weeks warp is freezing, the fans are going off and if I open activity monitor it appears at the top of the list. I suspect there is a memory leak somewhere that got merged with a recent commit..

**Comment by alokedesai** [comment] 2024-04-29 14:01
@t-var-s Just to confirm, you don't see a [beach ball](https://en.wikipedia.org/wiki/Spinning_pinwheel) when this happens, right?

When you get into the state where you can't quit Warp and the prompt is stuck at "loading prompt", does every session have the same issue or is it only specific sessions? Would be able to share your [Warp logs](https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs) with us so we can debug further?

**Comment by TowhidKashem** [comment] 2024-04-29 20:02
> @TowhidKashem When you say "Warp is freezing" are you seeing the same issue @t-var-s mentions above or is Warp completely unresponsive for you? Could you share a video of what you're seeing?

I just remember it being unresponsive and having to force quit it from activity monitor. If it happens again I'll try to take a video.

**Comment by lucianthorr** [comment] 2024-05-02 18:03
Was able to capture the freezing.  I updated today while ssh'd in and it handled the connection during the upgrade but a few minutes later, I was starting to see the slowdown described above.
You can see it effects both the ssh'd shell tab and the local tab.

https://github.com/warpdotdev/Warp/assets/5907505/cb60405b-ed01-4731-839d-52c56470ac4d

**Comment by t-var-s** [comment] 2024-05-04 18:48
Just happened again with the latest update to v0.2024.04.30.08.02.stable_01

> @t-var-s Just to confirm, you don't see a [beach ball](https://en.wikipedia.org/wiki/Spinning_pinwheel) when this happens, right?

Right, dont' think I've ever seen a beach ball on warp.

> When you get into the state where you can't quit Warp and the prompt is stuck at "loading prompt", does every session have the same issue or is it only specific sessions?

Every session gets stuck. Here are the logs from the latest frozen state:

```
2024-05-04T18:38:08Z [INFO] Starting shell /bin/zsh
2024-05-04T18:38:08Z [INFO] Successfully spawned tty with pid: 94194
2024-05-04T18:38:08Z [INFO] Successfully spawned child zsh process with pid 94194
2024-05-04T18:38:08Z [INFO] dispatching global action for workspace:save_app
2024-05-04T18:38:08Z [INFO] dispatching global action for workspace:save_app
2024-05-04T18:38:08Z [WARN] Tried to update block filter query without active_filter_editor_block_index set
2024-05-04T18:38:08Z [WARN] Tried to render share modal without a model
2024-05-04T18:38:08Z [WARN] redraw_frame was called 2 times before the frame was drawn
2024-05-04T18:38:11Z [WARN] redraw_frame was called 3 times before the frame was drawn
2024-05-04T18:38:20Z [WARN] redraw_frame was called 2 times before the frame was drawn
2024-05-04T18:38:20Z [WARN] redraw_frame was called 4 times before the frame was drawn
2024-05-04T18:38:30Z [INFO] dispatching global action for root_view:update_quake_mode_state
```

**Comment by t-var-s** [comment] 2024-05-10 19:44
For this latest update, I uninstalled warp, kept its files and downloaded it again from the website. Let's see if the issue persists now.

**Comment by t-var-s** [comment] 2024-05-17 22:45
> Let's see if the issue persists now.

Still happening when updating to v0.2024.05.14.08.01.stable_04

**Comment by Yoni-apex** [comment] 2024-05-26 07:56
I was looking for issues to find something similar and this is it. I have the same issue:

When I update, nothing happens. The settings show "Updating...". I have to Force Quit and when I open it again, it shows the "What's New". Regular quit is not working either.

System is:
Macbook Pro
14-inch, Nov 2023
M3 Pro
Sonoma 14.1

Warp is now:
v0.2024.05.21.16.09.stable_02

**Comment by alokedesai** [comment] 2024-05-27 20:17
@Yoni-apex @t-var-s Does `cmd-q` work to quit or is that also broken?

**Comment by alokedesai** [comment] 2024-05-27 20:18
@Yoni-apex Do you also see the performance issues that the author of this issue is experiencing?

**Comment by Yoni-apex** [comment] 2024-05-28 04:26
Yes, after trying to update only.

**Comment by Yoni-apex** [comment] 2024-05-28 04:27
> @Yoni-apex @t-var-s Does `cmd-q` work to quit or is that also broken? 

Broken, Force Quit only...

**Comment by alokedesai** [comment] 2024-05-28 14:13
What version of MacOs are you using? Do you have any security software installed on your machine, by chance?

**Comment by Yoni-apex** [comment] 2024-05-29 07:35
> What version of MacOs are you using? Do you have any security software installed on your machine, by chance?

Sonoma 14.1 and no security software. Without FileVault either. And used to work before. Maybe before the next update we could do something to get precise logs of the update?

Let me know how I can help :)

**Comment by t-var-s** [comment] 2024-05-30 17:41
> @Yoni-apex @t-var-s Does `cmd-q` work to quit or is that also broken?

The issue persists when updating to v0.2024.05.21.16.09.stable_02 
Cmd-q is also broken.

**Comment by alokedesai** [comment] 2024-05-31 21:37
Hi all, thanks for your patience here.  We're still trying to better understand why this is happening.

I'm looking for someone who would be willing to spend ~30 minutes in a Zoom call with me to debug this further. If you're interested (and based in a time zone that has overlap with the US East Coast) please email me at aloke@warp.dev. We would send you Warp swag as a thank you for your time.

**Comment by alokedesai** [comment] 2024-06-11 00:53
Just an update here. This happens when you try to update when Warp is fullscreen. I recently merged a fix for this and it should be available next week. Thanks again for your patience is here.

**Comment by t-var-s** [comment] 2024-06-11 10:38
> This happens when you try to update when Warp is fullscreen.

Can confirm that this should be the cause 👍 I always have Warp in fullscreen.

**Comment by t-var-s** [comment] 2024-06-27 22:53
Have the fix 👍 Warp in fullscreen now updates normally.

**Comment by alokedesai** [comment] 2024-06-27 22:59
Great to hear. Thanks for everyone’s patience here. Going to go ahead and close this out.

**Closed by alokedesai** 2024-06-27 22:59 UTC
Labels: Bugs

**Comment by DouglasDev** [comment] 2025-09-06 16:23
@alokedesai I'm still having serious performance issues using warp on a mac book pro. Would be willing to zoom if it would help.

**Comment by GoodwillAmbiguous** [comment] 2025-09-21 21:52
Same issue, M1 MacBook Pro latest OS latest version of Warp. If I leave Warp open after about a day or two it starts acting super sluggish and is consuming a ton of resources. I exit and reopen and everything is fine.
