### ISSUE TITLE
Impossible to assign Ctrl + Tab as keyboard shortcut

### ISSUE THREAD

**Issue by jonas-spiideo** [warpdotdev/Warp#3051] opened 2023-05-11 12:01 UTC
### Describe the bug

When setting custom keyboard shortcuts, using Ctrl + Tab is not recognized.

### To Reproduce

Edit any keyboard shorcut

### Expected behavior

I want to be able to use Ctrl + Tab (for cycling between tabs)

### Operating System

MacOS

### Operating System and Version

13.3.1

### Warp Version

v0.2023.05.02.08.03.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-05-12 20:13
@jonas-spiideo Please confirm if the above was helpful in resolving your issue, if not we'd appreciate it if you provide some detailed reproduction steps along with a video of the issue.

**Comment by dannyneira** [comment] 2023-05-17 20:39
Closing as I can't reproduce this issue, but please feel free to let us know if the issue persists along with detailed reproduction steps and a video of the issue.

**Comment by pierrelefevre** [comment] 2024-02-28 09:56
Hey @dannyneira, got the same issue. In the video you're binding Opt+tab not Ctrl+tab.

See example below, binding opt+tab (⌥ + →) works but for ctrl+tab (^ + →), nothing happens

https://github.com/warpdotdev/Warp/assets/35996839/e624ab0c-a879-4a14-b979-bfdcd49d37cc

**Comment by dannyneira** [comment] 2024-02-28 16:55
You're correct @pierrelefevre, sorry if this is a blocker, reopening but there is no eta on a fix.

As a workaround, I recommend you try another combo like CTRL-<LETTER/NUM/SYMBOL> or just TAB, it seems like TAB cannot be combined with other keys since it's defaulted for the Completions Menu. You can search for CTRL in the keyboard shortcuts menu to make sure there isn't a conflict.

**Comment by dannyneira** [comment] 2024-10-29 22:00
Hi @jonas-spiideo and folks on this thread, we already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1851

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Closed by dannyneira** 2024-10-29 22:00 UTC
Labels: Bugs
