### ISSUE TITLE
Allow text selection to copy prompt text

### ISSUE THREAD

**Issue by MelanieCrissey** [warpdotdev/Warp#3943] opened 2023-12-07 15:18 UTC
### Discord username (optional)

melaniecrissey_warp

### Describe the solution you'd like?

```Text
Allow text selection for Warp prompts
```

### Is your feature request related to a problem? Please describe.

```Text
Right now, you can use "Copy Prompt" to copy the prompt text if you've already run a command, but otherwise text selection doesn't work as you'd expect for any text in the Warp prompt
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-12-07 21:19
Hey @MelanieCrissey! There are some slight workarounds I can suggest. First while using a custom prompt, run the command then the prompt is selectable/copyable from previous blocks, or if you're using the Warp prompt, right-click the prompt in the input editor or previous blocks and click "Copy Prompt".

We have a request tracking this request for a selectable Warp prompt over at #36. We'll post any updates there.

**Comment by dannyneira** [comment] 2023-12-07 21:19
Duplicate of #36

**Closed by dannyneira** 2023-12-07 21:19 UTC
Labels: Feature
