### ISSUE TITLE
DUP: Duplicate of #069 - Drag and Drop files

### ISSUE THREAD

**Issue by stianrincon** [warpdotdev/warp#108] opened 2021-08-07 21:59 UTC
I'd like to be able to drug and drop files

https://user-images.githubusercontent.com/2531975/128614857-065c1d0e-8779-4784-81c0-ab8797e04c88.mov

**Comment by mittalyashu** [comment] 2021-08-08 05:10
@stianrincon How did you made those icons available in Finder?

**Comment by stianrincon** [comment] 2021-08-08 20:12
> @stianrincon How did you made those icons available in Finder?

From Applications you can drag and drop those, the key thing is to drag and drop making sure you are pressing command

**Comment by saket** [comment] 2021-08-08 20:18
+1

**Comment by gagata** [comment] 2021-08-20 23:41
Duplicate of #69 

Just marking as duplicate, so we consolidate the conversation in one place :) Thanks for reporting this and the screencast!

**Comment by elviskahoro** [comment] 2021-11-07 23:03
Should stay reopen until it's actually finished.

**Comment by elviskahoro** [comment] 2021-11-10 16:51
Linking:
- #069

**Comment by elviskahoro** [comment] 2021-11-17 22:44
v0.2021.11.16.20.05.stable_01

**Closed by elviskahoro** 2021-11-17 22:44 UTC
Labels: feature-request
