### ISSUE TITLE
“<script>.command/sh” can’t be opened because (null) is not allowed to open documents in Terminal.

### ISSUE THREAD

**Issue by elrony** [warpdotdev/Warp#2587] opened 2023-01-31 06:35 UTC
### Describe the bug

Using the open shell command to start a terminal script (.command/.sh) fails with this error:

“XXXX.sh” can’t be opened because (null) is not allowed to open documents in Terminal.

I have tried setting up Warp as an "Open with" target for command/sh scripts but Warp does not support that (maybe this is another bug/feature?)

### To Reproduce

`
touch test.command

open test.command
`

### Expected behaviour

the open command should either open Terminal or whatever terminal app is associated with the script.

### Screenshots

![warpissue](https://user-images.githubusercontent.com/5883791/215683941-73bd7763-02c8-47f2-8309-ee9751b5aeb4.png)

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.24.08.03.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment] 2023-01-31 15:05
Hey @elrony, thanks for reporting this!  I'm not able to reproduce:
* When I do `touch test.sh; open test.sh` Xcode launches and opens the file
* When I do `touch test.command; open test.command` I get a different error than you saying I don't have permissions (presumably because it's not marked as executable).
* When I do `touch test.command; chmod +x test.command; open test.command` the script opens in Terminal.app successfully.

This is my error dialog for the second case:
![image](https://user-images.githubusercontent.com/211194/215795851-e89a579a-48d5-4820-9cef-f1d8a3a05b86.png)

Mind right-clicking on the `test.sh` file in Finder, clicking "Get Info", and sending a screenshot of the "Open with" section (like the screenshot below)?

![image](https://user-images.githubusercontent.com/211194/215797008-8f52feb4-8b85-4d06-a1c8-9cbef2a2f8e0.png)

**Comment by elrony** [comment] 2023-02-02 05:04
Hello and thanks for your reply!

Sorry I forgot to mention the chmod command.

This is happening for me on Mac OS Ventura 13.1, .sh and .command scripts are both associated with Terminal.app for me.
I just tested this on my old mac running Monterey 12.6.1 and Warp works as expected. So the issue affects the latest OS only I guess.

On Ventura:
![image](https://user-images.githubusercontent.com/5883791/216233967-ea425f44-74bb-406b-a592-ad47dc70bf22.png)

If I use Terminal.app or iTerm2 and run `open file.sh/command` they both open a new Terminal.app window. But when I use Warp I get that error message.

**Comment by vorporeal** [comment] 2023-02-03 17:21
I did some searching on Google for the error message in your initial dialog box, and it seems like this is a known issue with opening things in Terminal.app on Ventura. :(

Examples:
https://stackoverflow.com/questions/74931019/1-cannot-be-opened-because-null-is-not-allowed-to-open-documents-in-termin
https://community.localwp.com/t/null-is-not-allowed-to-open-documents-in-terminal-when-trying-to-open-site-shell/34977

Closing this out for now as it doesn't seem to be a Warp-specific issue.

**Closed by vorporeal** 2023-02-03 17:21 UTC
Labels: Bug
