### ISSUE TITLE
terminal stopped pasting in copied lines

### ISSUE THREAD

**Issue by yotamguttman** [warpdotdev/Warp#4799] opened 2024-04-21 11:32 UTC
### Discord username (optional)

yotamguttman

### Describe the bug

I've been testing warp in the past 3-4 days and did not experience anything as such. only today the terminal stopped pasting in any information copied from another window. I found that what might resolve it is when you close and reopen Warp terminal but today it also started freeze crashing.

which is weird because it doesn't actually freeze. I'd try pasting something, via shortcut then rightclick menu, it won't work even though the software would be running in order, so I'd try to close Warp terminal and then it'd freeze...

### To reproduce

1. copy command line on browser
2. ctrl+shift+v / rightclick menu+paste
3. nothing gets pasted (terminal is running properly and text can be manually typed in)
4. click X to close terminal window.
5. terminal freezes and crashes

### Operating system

Linux

### Operating system and version

Fedora 39 (Gnome 45.5, Wayland)

### Current Warp version

v0.2024.04.16.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

20/04/24

### Additional context

wrap is so convenient. you very quickly get used to the features such as auto completing and such, and they become a second nature you quickly forget about. only at the moment it no longer works and you have to fall back on your built in terminal, you realise how much it's missing.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-26 23:06
Hi @yotamguttman thanks for your patience and sorry to hear about this. I cant reproduce this issue, can you please download the latest version of Warp and provide a video of the issue to help us better understand the bug?

**Comment by dannyneira** [comment] 2024-06-26 21:45
@yotamguttman any updates? does this issue persist? Can you please provide a video or screen share of the issue

**Comment by yotamguttman** [comment] 2024-06-27 07:08
hi, I no longer use warp. reverted back to my good old open source terminal emulator configed with fish on it and it works just as well :)

**Comment by dannyneira** [comment] 2024-07-02 22:54
Thanks for letting us know and for trying Warp! We're actively working on native Wayland support which may alleviate the issue for you and other users that had the same. We're tracking this here. https://github.com/warpdotdev/Warp/issues/4234

**Comment by dannyneira** [comment] 2024-07-02 22:55
Duplicate of https://github.com/warpdotdev/Warp/issues/4234

**Closed by dannyneira** 2024-07-02 22:55 UTC
Labels: Bugs
