### ISSUE TITLE
Allow starting line to be the first line and not the second with p10k.

### ISSUE THREAD

**Issue by ColeBlender** [warpdotdev/Warp#4563] opened 2024-03-15 00:23 UTC
### Describe the solution you'd like?

I'm using Powerlevel10k with warp and I need my starting line to be on the same line as the pwd. It's very annoying and may honestly prevent me from using it.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-15 06:21
Thanks for submitting this @ColeBlender 

We already have a request tracking this over at #2304. It's actively being worked on and we're working out some bugs with p10k in particular at the moment.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-15 06:21
Duplicate of #2304

**Closed by dannyneira** 2024-03-15 06:21 UTC
Labels: Feature requests
