### ISSUE TITLE
Give users the ability the whitelist processes that should block Warp from quitting

### ISSUE THREAD

**Issue by westernwontons** [warpdotdev/Warp#3106] opened 2023-05-23 18:17 UTC
### Describe the solution you'd like?

```Text
Add the ability to whitelist applications by providing their names in settings and if those applications are running, give users the same or similar pop up that would normally open when there are background processes running.
```

### Is your feature request related to a problem? Please describe.

```Text
When I'm running Vim and I accidentally fat finger cmd+w it closes the window and there we're some times when I lost some work because of it.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-05-23 19:39
Thank you for submitting this feature request! We appreciate your suggestion.

We currently have the [Quit Warning](https://docs.warp.dev/features/quit-warning) feature in place for sessions that are still running, but we do not have a whitelist feature. Nevertheless, we value your idea and will consider it for future enhancements.

To show your support for this feature request, please consider adding 👍 to the original post at the top. This will help us gauge the level of interest among our users.

If you would like to stay updated and receive notifications about any developments regarding this feature, please click on the subscribe button. We'll make sure to keep you informed of any updates.

**Comment by westernwontons** [comment] 2023-06-20 20:19
I've been testing some more and I was wondering if it would be possible to extend the Quit Warning to closing tabs, not just closing Warp itself

**Comment by dannyneira** [comment] 2024-08-23 17:28
yes it does warn on closing tabs, but only if there is a running process currently.

**Comment by dannyneira** [comment] 2024-08-23 17:31
We'll be tracking the request for quit warning here https://github.com/warpdotdev/Warp/issues/1887

Please subscribe to that request for updates

**Comment by dannyneira** [comment] 2024-08-23 17:31
Duplicate of https://github.com/warpdotdev/Warp/issues/1887

**Closed by dannyneira** 2024-08-23 17:31 UTC
Labels: Feature requests
