### ISSUE TITLE
Prompt in one line / Cursor in the same line with the prompt

### ISSUE THREAD

**Issue by justdan0227** [warpdotdev/Warp#4960] opened 2024-05-29 15:56 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I know this has been asked before and I thought I saw a discussion on its implementation, but can not find it.

Can we get a one-line prompt or at least can show something like ">" on the input line to let us know that all previous commands have been completed?

### Is your feature request related to a problem? Please describe.

You don't know when all of the previous commands have completed as the default terminal does 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-29 17:15
Hi @justdan0227 Thanks for submitting this request. We're actively working on implementing this and we already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2304

It's a bit tricky given all the refactoring it's requiring and the possible edge cases, etc. but we're making progress and you can find the latest update [here](https://github.com/warpdotdev/Warp/issues/2304#issuecomment-1907563006).

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-29 17:15
Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Closed by dannyneira** 2024-05-29 17:15 UTC
Labels: Feature requests
