### ISSUE TITLE
DUP: #776 - Swish window manager not working

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#797] opened 2022-03-09 20:19 UTC
### Describe the bug

```shell
Root issue likely similar to Magnet via:
- #776
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

**Comment by gnapse** [comment] 2022-03-19 14:29
Duplicate of #806 (or that's a duplicate of this one, either way)

**Closed** 2022-03-22 17:49 UTC
