### ISSUE TITLE
Terragrunt init pauses at initializing module step

### ISSUE THREAD

**Issue by itsjamie** [warpdotdev/Warp#674] opened 2022-01-25 20:51 UTC
### Describe the bug

Running `terragrunt init --terragrunt-log-level debug` shows commands running initializing and parsing Terraform commands. However, at the point where it goes to initialize modules in the current HCL level, it pauses, and never finishes.

```
command: terraform init <snip>
Initializing modules...
```

At which point it is stalled here, running `ps` shows an executing task.

`88978 ttys001    0:00.21 /opt/homebrew/Cellar/tfenv/2.2.2/versions/1.0.9/terraform init <snip>`

However, the CPU time doesn't increase.

### To Reproduce

Steps to reproduce:
1. Use Terragrunt to manage a AWS cloud environment.
2. Run `terragrunt init`.
3. Freeze at `Initializing Modules` step of the initialization process.

### Expected behaviour

The expected behaviour would be that running in Warp would work just as executing in Terminal or iTerm works.

### Operating System

MacOS

### OS Version

12.1

**Comment by mgainhao** [comment] 2022-02-01 09:40
Hi,
I faced the same issue, first time running terraform init is ok.
But the second time it hangs and had to kill the process:
`
terraform init
Initializing modules...`

No issue with the mac terminal.
Operating system: Macos 11.6.1

Thanks

**Comment by zrzka** [comment] 2022-03-25 11:21
Same here. `terraform init` just hangs in Warp. Works in macOS terminal application & iTerm.

**Comment by sidpremkumar** [comment] 2022-04-18 09:08
Same issue here, confirmed that this issue is fixed by moving to another terminal (i.e. `hyper.js`)

**Comment by azt3k** [comment] 2022-05-01 23:17
Also have this issue, had to go back to iTerm

**Comment by Livven** [comment] 2022-07-27 15:12
I'm experiencing similar hangs with Bazel and some internal tooling. Suspect these are all related so did not want to open a new issue, but let me know if you would prefer that.

What I see with Bazel is that some targets that download files will randomly get stuck after a different amount of time and bytes downloaded each time, so it seems to be related to network/IO in some way.

#1388 and #1658 also sound similar.

**Comment by warpdotdev-dx** [comment] 2022-07-27 22:41
Aloke has been working on Bazel. We think we have a fix for it but it's still being tested.

**Comment by Livven** [comment] 2022-08-04 09:23
Seems to work for me now with the latest update, thanks!

Wondering if you could share any information on what caused the issue and how it was fixed? This has shaken my trust in Warp to be honest, since I didn't really expect issues like this from a terminal app. Makes me question if I can trust that commands are being executed correctly at all times, especially if there could be less noticeable issues causing e.g. silent corruption.

**Comment by zoispag** [comment] 2022-08-04 09:25
I can confirm it is now working for `terraform init` too.

**Comment by alokedesai** [comment] 2022-08-05 16:22
Closing this out as as we believe this issue is now fixed. Please reopen if you're still experiencing this issue!

**Closed by alokedesai** 2022-08-05 16:22 UTC
