### ISSUE TITLE
On first run, the welcome line wrap breaks a word across two lines 

### ISSUE THREAD

**Issue by dwlf** [warpdotdev/Warp#3174] opened 2023-06-02 19:43 UTC
### Describe the bug

On first run, the welcome line wrap breaks a word across two lines on my MacBook Air M2, 2022 built-in screen 13.6-inch (2560 × 1664).

See attached screenshots.

### To reproduce

See attached screenshot.

### Screenshots

<img width="1024" alt="20230602-warp-welcome-wordbreak" src="https://github.com/warpdotdev/Warp/assets/962387/b2b3d7e4-c7eb-43dd-b017-b51134617763">

<img width="1024" alt="20230602-warp-welcome-wordbreak-annotated-2" src="https://github.com/warpdotdev/Warp/assets/962387/a56312f9-6f13-4ead-ad0f-d2d89c222173">

### Operating system

MacOS

### Operating system and version

13.4 (22F66)

### Current Warp version

v0.2023.05.30.08.03.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-06-02 21:28
Thanks for letting us know @dwlf I've noticed the same happens when you run `echo -e "$(cat '/Applications/Warp.app/Contents/Resources/assets/onboarding/welcome_to_warp.txt')"` in iTerm2 and Terminal.app. I know the welcome message is warp specific, but since we're just using standard terminal commands echo the message, the output should behave the same across all terminals. I think we should close this since it's not a bug and standard behavior across other terminals.

**Closed** 2023-06-02 21:29 UTC
Labels: Bug

**Comment by dwlf** [comment] 2023-06-02 22:14
@dannyneira thank you for the timely feedback, though bizarre. It is an acceptable first-run experience to have broken words?

**Comment by dannyneira** [comment] 2023-06-02 22:27
Not really. But since the current welcome message all depends on the size of the terminal window which can vary based in the users screen or if they had a side panel open, etc. I don't think we should change common terminal behavior to 'fix' it. But for sure we will take your feedback on board and come up with a better, responsive, welcome experience.
