### ISSUE TITLE
Warp crashes immediately on Mac OS 13 Ventura beta

### ISSUE THREAD

**Issue by GQAdonis** [warpdotdev/Warp#1482] opened 2022-06-09 19:17 UTC
### Describe the bug

```text
After reinstalling Warp via Homebrew the application crashes and terminates without an error on launch.
```

### To Reproduce

Steps to reproduce:
1. Go to 'Applications' folder
2. Click on 'Warp'
3. Application crashes

### Expected behaviour

```text
I expected the application to open.
```

### Operating System

MacOS

### OS Version

13.0 beta

### Shell Version

Bash 5.0

### Warp Version

Latest

**Comment by ryanmagoon** [comment] 2022-06-09 23:13
Duplicate of https://github.com/warpdotdev/Warp/issues/1463

**Comment by elviskahoro** [comment] 2022-06-14 15:54
Tracking this in #1463

**Closed by elviskahoro** 2022-06-14 15:54 UTC
