### ISSUE TITLE
About tool language support

### ISSUE THREAD

**Issue by larkzhang** [warpdotdev/Warp#4940] opened 2024-05-22 08:33 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Will the menu Settings in languages other than English be considered in the future, or will the menu language selection be opened up to support other developers to provide their own language Settings files

### Is your feature request related to a problem? Please describe.

Will the menu Settings in languages other than English be considered in the future, or will the menu language selection be opened up to support other developers to provide their own language Settings files

### Additional context

Will the menu Settings in languages other than English be considered in the future, or will the menu language selection be opened up to support other developers to provide their own language Settings files

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-22 21:54
Thanks for submitting this @larkzhang 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1194

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-22 21:54
Duplicate of https://github.com/warpdotdev/Warp/issues/1194

**Closed by dannyneira** 2024-05-22 21:54 UTC
Labels: Feature requests
