### ISSUE TITLE
Warp does not support ssh:// url scheme

### ISSUE THREAD

**Issue by cbrassel** [warpdotdev/Warp#3083] opened 2023-05-18 17:09 UTC
### Discord username (optional)

cbrassel

### Operating System

MacOS

### Operating System and Version

Darwin Kernel Version 22.4.0

### Local Shell Version

ZSH 5.9

### Remote Shell Version

N/A

### Warp Version

v0.2023.05.09.08.03.stable_01

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

in my workflow i'm relying on the mac os url scheme for ssh, as of today i'm using iterm2 which works fine, when i'm calling "open ssh://remote_host" it open's a new tab in iterm with the ssh connection executed.
I have tried to swith the default app for the ssh url scheme from iterm2 to warp .. 
When I launch the "open ssh://remote_host" command from another terminal it switches to warp but nothing append .. 
Any idea ?

### Include shell xtrace output

Unable to provide the trace

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vorporeal** [comment] 2023-05-18 19:08
We don't support this yet, unfortunately.  Thanks for reporting it, though - we'll track it as a feature request. :)

**Comment by dannyneira** [comment] 2023-05-19 15:58
@cbrassel No warp cli tool exists at this time, the closest feature we have to this is [Launch Configurations](https://docs.warp.dev/features/sessions/launch-configurations#commands) which can open SSH sessions, but in new windows/tabs/panes, not the existing ones.

**Comment by dannyneira** [comment] 2024-01-03 22:42
Hey folks, since we already have a request tracking this over at  https://github.com/warpdotdev/Warp/issues/1741

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-03 22:43
Duplicate of https://github.com/warpdotdev/Warp/issues/1741

**Closed by dannyneira** 2024-01-03 22:43 UTC
Labels: SSH, enhancement
