### ISSUE TITLE
DUP: Duplicate of #017 - Add Support for Transparent Terminal Window

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/Warp#767] opened 2022-02-19 20:14 UTC
### Describe the solution you'd like?

```shell
In Terminal.app there is a `Pro` theme that has a transparent background, so you can kinda see content underneath the Terminal window.

It would be great if Warp added this as well.
```

### Additional context

<img width="713" alt="Screen Shot 2022-02-19 at 1 11 47 PM" src="https://user-images.githubusercontent.com/860375/154817492-a8302189-761d-40c3-8472-348b99c0e2db.png">

**Comment by elviskahoro** [comment] 2022-02-25 05:22
Duplicate of:
- #017

**Closed by elviskahoro** 2022-02-25 05:22 UTC
