### ISSUE TITLE
Commands in config.fish are run twice

### ISSUE THREAD

**Issue by mkenigs** [warpdotdev/Warp#5297] opened 2024-09-10 17:48 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Commands in config.fish are run twice, and this doubles startup time.

### To reproduce

1. Set `fish` to startup shell in `Settings > Features`
2. Add `echo "Starting fish" >> /tmp/fish` to `~/.config/fish/config.fish`. Alternatively add a `sleep 5`
3. Open a new tab with command D.
4. `cat /tmp/fish` and see `Starting fish` is echoed twice. Or if the sleep was added, startup takes 10 seconds.

### Expected behavior

`Starting fish` should only be echoed once, or if the sleep was added startup should only take 5 seconds.

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

fish, version 3.7.1

### Current Warp version

v0.2024.09.03.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-09-11 16:59
Thanks for letting us know @mkenigs I was able to reproduce this issue and will let the team know. We'll post any updates on this thread.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by nikitavoloboev** [comment] 2024-09-11 17:02
It’s major issue for me. Upvoted. Hope you can fix it. ♥️

**Comment by szgupta** [comment] 2024-09-23 16:04
Hey y'all, sorry for the inconvenience caused by this bug. A fix for this will be live in this week's release.

**Comment by szgupta** [comment] 2024-09-30 18:47
This should be fixed in `v0.2024.09.24.08.02.stable_01`. Please re-open if you're still facing issues!

**Closed by szgupta** 2024-09-30 18:47 UTC
Labels: Bugs
