### ISSUE TITLE
DUP: Duplicate of #102 - Open warp here ...

### ISSUE THREAD

**Issue by abbasmousavi** [warpdotdev/warp#539] opened 2021-12-18 01:06 UTC
### Describe the solution you'd like?

```shell
I would like to have an option when I ctrl-click on a folder in finder to open warp at that folder.
```

**Comment by elviskahoro** [comment] 2021-12-20 01:31
Closing as it's duplicate of:
- https://github.com/warpdotdev/warp/issues/102

**Closed by elviskahoro** 2021-12-20 01:31 UTC
