### ISSUE TITLE
Custom Prompt Repeated 4 Times

### ISSUE THREAD

**Issue by huangdarz** [warpdotdev/Warp#4061] opened 2024-01-12 11:57 UTC
### Discord username (optional)

darin465

### Describe the bug

My custom prompt shown in the terminal is repeated 4 times. I am using Oh My Posh as my prompt theme engine. 
![Screenshot 2024-01-12 at 9 34 47 pm](https://github.com/warpdotdev/Warp/assets/31122258/ab84a5fa-13aa-42b4-9c4d-1735445591b2)

### To reproduce

1. Install Oh My Posh using Homebrew (`brew install jandedobbeleer/oh-my-posh/oh-my-posh`) 
2. Update to v0.2024.01.09.08.02.stable_01
3. Go to Settings
4. Go to Appearance
5. Under 'Prompt' select "Current prompt: Shell prompt (PS1)"

### Expected behavior

I expect to only see my custom prompt once in the terminal. 

### Screenshots

![Screenshot 2024-01-12 at 9 34 47 pm](https://github.com/warpdotdev/Warp/assets/31122258/ab84a5fa-13aa-42b4-9c4d-1735445591b2)

### Operating system

MacOS

### Operating system and version

14.2.1

### Current Warp version

v0.2024.01.09.08.02.stable_01

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-12 17:24
Hey Folks, thanks for letting us know. We'll be tracking this issue on #4057 going forward and are actively working on reverting the change that may have caused the prompt to repeat. We'll post updates on the parent issue above.

**Comment by dannyneira** [comment] 2024-01-12 17:24
Duplicate of #4057

**Comment by dannyneira** [comment] 2024-01-12 17:24
Duplicate of #4057

**Closed by dannyneira** 2024-01-12 17:24 UTC
Labels: Bug

**Comment by dannyneira** [comment] 2024-01-12 18:46
hey Folks, Warp version `v0.2024.01.09.08.02.stable_02` has been released which reverts the change that caused this regression. Please update and stay tuned for the fix.
