### ISSUE TITLE
Memory leak on macOS?

### ISSUE THREAD

**Issue by MuhammedKpln** [warpdotdev/Warp#733] opened 2022-02-05 17:56 UTC
### Describe the bug

```
Memory usage get higher and higher after using 2-3 days in a row, even after you kill the process inside terminal.
```

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment] 2022-03-09 18:34
From @kodeninja via Discord:
https://discord.com/channels/851854972600451112/851854972600451115/950912557504430140
> Hey, everyone. Been using warp for a month or so now. Question about its memory usage. Just today I noticed that even though I only have one window opened, warp's using 1.8G of memory!

> Is that normal/expected? I'm on an Apple M1 (Monterey), and the latest warp. 

Note:
This seems to happen when the Warp app has been left open for multiple days.
> Checking htop it seems to have been running since March 04th.

**Comment by halathamneh** [comment] 2022-03-17 08:17
I am also having this issue.
I have MacBook Air M1 16GB, when I keep Warp running for more than one day, memory usage reaches 3~4GB.

**Comment by ramzzzay** [comment] 2022-04-20 17:04
Same story on MacBook Pro m1 pro 16gb ram macOS 12.3

**Comment by dupu222** [comment] 2022-05-07 02:42
![image](https://user-images.githubusercontent.com/13982466/167234768-0167842c-355c-4e7a-bca5-2346ccd89a63.png)
MacBook Pro 2018 Intel Core i5 16gb macOS 12.3.1

**Comment by luizfonseca** [comment] 2022-05-17 09:26
MacBook Pro (16-inch, 2019)

Having the same issue as well, basically caused by long-running commands (e.g. compiling output from web pack, compiling output from storybook)

I only have 2 tabs:

<img width="881" alt="Screenshot 2022-05-17 at 11 25 07" src="https://user-images.githubusercontent.com/249782/168778034-d5b68a43-d6c6-4a5d-9ab3-1526f23a37e4.png">

**Comment by elviskahoro** [comment] 2022-05-30 20:58
Does CMD-K help?

**Comment by acarl005** [comment] 2022-06-01 05:39
I had the same issue. I had a `psql` session running for several days and the memory usage hit 3GB.

**Comment by mowchan** [comment] 2022-06-16 18:56
> Does CMD-K help?

This instantly reduced memory usage for me from >4GB to 200MB

**Comment by gawry** [comment] 2022-07-17 00:35
> Does CMD-K help?

Helped here too. Looks like Warp need a better way to manage history without keeping everything in memory.

**Comment by silenceleaf** [comment] 2022-07-29 21:31
If my understanding right, warp is written in Rust which is less likely have memory leak issue. But, ...  Hopefully this can be addressed soon!

**Comment by gnattu** [comment] 2022-09-16 01:44
A late follow up because I am in a situation that CMD+K does not help(much)

This is what I got before taking any actions with 3 tabs and a couple of history:

<img width="537" alt="Screen Shot 2022-09-16 at 09 35 18" src="https://user-images.githubusercontent.com/12995396/190537788-38d2c3d4-de92-410b-b50e-6366142b8397.png">

----

After CMD+K, open a new tab and close all previous ones, I still got >4GB , although reduced memory footprint:
 
<img width="1060" alt="Screen Shot 2022-09-16 at 09 36 47" src="https://user-images.githubusercontent.com/12995396/190537982-ef9aaf29-3009-40b7-a438-710498bab16a.png">

----

Now, if CMD+Q to quit Warp and open it again, I got <200MB memory usage:
<img width="788" alt="Screen Shot 2022-09-16 at 09 40 09" src="https://user-images.githubusercontent.com/12995396/190538106-839111b2-787b-4977-a2d5-c090c9297b31.png">

----

One potential reason I could think of is that, I had opened other tabs, performing some tasks and then closed them, but warp keeps the history of already-closed tabs as well and there is no way( I know) to clear the history for those closed tabs.

**Comment by dannyneira** [comment] 2022-10-04 20:40
@MuhammedKpln We've made a number of performance improvements, are you still experiencing this issue?

**Comment by luizfonseca** [comment] 2022-10-06 09:09
On my side I haven't seen it crossing the GB mark anymore and I have been running it with a lot of tabs/commands/history

<img width="591" alt="Screenshot 2022-10-06 at 11 09 53" src="https://user-images.githubusercontent.com/249782/194273646-443e49c1-7ece-4363-a31f-533375c5b9ec.png">

**Comment by MuhammedKpln** [comment] 2022-10-06 09:51
> @MuhammedKpln I'm Danny, the Support Engineer at Warp. We've made a number of performance improvements, are you still experiencing this issue?

It has improved a lot since then, 400mb is the maximum usage what i have been seen for the last weeks.

**Comment by nguyenlamzx** [comment] 2022-11-24 13:05
From my mac:
<img width="649" alt="Screenshot 2022-11-24 at 17 57 40" src="https://user-images.githubusercontent.com/570048/203791533-102c0afe-c6ca-4ee0-a958-f5a46c4bbcf1.png">
 > 800MB

**Comment by cvanhorn09** [comment] 2022-11-30 12:35
Same result here, single tab, single window, memory usage grows ~1GB every 36 hours (caught it at around the 4GB utilization mark) and goes back down to ~200MB after a quit and re-open.

16-inch M1 Pro Macbook Pro, 16GB RAM, Ventura 13.0.1
zsh 5.8.1 (x86_64-apple-darwin22.0)
Warp v0.2022.11.14.14.55.stable_01

**Comment by andreasvirkus** [comment] 2022-12-10 06:12
I use Warp usually with 2-3 tabs in a single window, only the first tab uses split panes. The RAM usage ramps up pretty quickly for me, having to restart Warp once a week...

5GB with 2 tabs (3 panes in total)
![Screenshot 2022-12-10 at 08 01 50](https://user-images.githubusercontent.com/9140811/206835003-36ff4624-3810-485b-9de3-dbcd431017ff.png)

When trying out the `Cmd + K` shortcut, it first hangs for ~2 minutes for me:
![Screenshot 2022-12-10 at 08 02 44](https://user-images.githubusercontent.com/9140811/206835006-8194fa06-55db-4ea4-9153-2cab68e3bb93.png)

And then reduces memory usage by roughly half
![Screenshot 2022-12-10 at 08 09 13](https://user-images.githubusercontent.com/9140811/206835007-2f464bc6-bd5b-462e-96d7-98213d082bc5.png)

**Comment by vorporeal** [comment] 2022-12-20 18:46
We rolled out a significant improvement for memory usage in the 2022.12.06 release; please update to the latest version (currently 2022.12.13) and let me know how things are!

**Comment by andreasvirkus** [comment] 2023-01-05 10:35
Things have been significantly better for me! Currently on 2022.12.13 and haven't had to restart a single time 😍

**Comment by vorporeal** [comment] 2023-01-05 17:06
Awesome!  I'm going to close this issue for now; please re-open it if necessary!

**Closed by vorporeal** 2023-01-05 17:06 UTC

**Comment by donCarlosOne** [comment] 2023-02-13 09:49
I am still seeing a large amount of memory usage.  Cmd-K helps somewhat.  I have around 14 tabs open, most of them tailing logs on various systems, and it doesn't take long to bring my 8 core 64GB MacBook Pro to a crawl.  I don't believe this is entirely memory related as Warp has 60+ threads active.
