### ISSUE TITLE
DUP: Duplicate of #058 - Support drag-and-drop to rearrange tabs

### ISSUE THREAD

**Issue by rvlasveld** [warpdotdev/warp#119] opened 2021-08-11 11:21 UTC
**Is your feature request related to a problem? Please describe.**

When opening multiple tabs, it becomes hard to know which tab refers to what exactly. When opening multiple tabs from different locations, they become unorganised. 

**Describe the solution you'd like**
Support drag-and-drop behaviour on the tabs, similar to how other apps (e.g. Mac Terminal, Chrome) allow this.

Bonus point: dragging a tab _out_ of the window to create a new window for that tab, and dragging a tab/window _in_ one to embed it.

**Comment by zachlloyd** [comment] 2021-08-16 14:39
Agreed on this being desirable.  Duplicate of #58

**Closed** 2021-12-07 02:42 UTC
Labels: feature-request
