### ISSUE TITLE
Support to Warp for Linux on Asahi Linux (Apple Silicon)

### ISSUE THREAD

**Issue by unnamedd** [warpdotdev/Warp#4239] opened 2024-02-22 20:17 UTC
### Describe the solution you'd like?

Hello folks,

I apologize for submitting this issue as a Bug Report, but regrettably, I don't believe my problem is either a bug or a feature request. Nevertheless, I would like to suggest to the team to cross-compile Warp for Asahi Linux, a Fedora distribution that runs on Apple Silicon (ARM). I have downloaded the Fedora build, but due to the architecture, I encountered difficulties in installing it.

Operating System: **Linux**
Version: **Fedora Linux Asahi Remix 39 (Thirty Nine) aarch64**
Architecture: **ARM (Apple Silicon)**
Kernel: **6.6.3-413.asahi.fc39.aarch64+16k**
Shell version: **zsh 5.9 (aarch64-redhat-linux-gnu)**
Laptop: **Apple MacBook Pro (14-inch, M2 Pro, 2023)**

### Additional context

Here's the log
```log
Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - package warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline does not have a compatible architecture
  - nothing provides libc.so.6(GLIBC_2.14)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libdl.so.2(GLIBC_2.2.5)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libpthread.so.0(GLIBC_2.2.5)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides ld-linux-x86-64.so.2()(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libm.so.6(GLIBC_2.2.5)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libpthread.so.0(GLIBC_2.12)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libpthread.so.0(GLIBC_2.3.2)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides librt.so.1(GLIBC_2.2.5)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libutil.so.1(GLIBC_2.2.5)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.15)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.2.5)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.3)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.3.2)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.3.4)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.4)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.7)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.8)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
  - nothing provides libc.so.6(GLIBC_2.9)(64bit) needed by warp-terminal-v0.2024.02.20.08.01.stable_01-1.x86_64 from @commandline
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-23 06:14
Hi @unnamedd We're tracking support for ARM Warp on Linux here: https://github.com/warpdotdev/Warp/issues/4213

It should be possible to make Linux binaries for ARM (given its already running on M1 macs). We'll post updates on that thread. 

Closing as duplicate

**Comment by unnamedd** [comment] 2024-02-23 06:17
> Hi @unnamedd We're tracking support for ARM Warp on Linux here: https://github.com/warpdotdev/Warp/issues/4213
> 
> 
> 
> It should be possible to make Linux binaries for ARM (given its already running on M1 macs). We'll post updates on that thread. 
> 
> 
> 
> Closing as duplicate

Thanks @dannyneira, just realised about the other issue when I had already submitted this one here, as it has some other details that perhaps might be useful, I didn't want to close this one here.

**Comment by dannyneira** [comment] 2024-02-23 20:44
Thanks for that extra context, this issue is linked as a duplicate of the other so we'll have the extra details if needed. No worries, we'll also be targeting Asahi Linux on Mac directly as part of ARM support. We'll be posting updates on that ARM thread so stay tuned!

**Closed** 2024-02-29 21:50 UTC
Labels: Feature requests

**Comment by dannyneira** [comment] 2024-06-10 17:08
Hey Folks, thanks for your patience here. I am happy to announce that you can now download arm64 versions of Warp at https://warp.dev/download.
