### ISSUE TITLE
Lock tabs

### ISSUE THREAD

**Issue by flippy27** [warpdotdev/Warp#5090] opened 2024-07-02 20:51 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

please add a "lock tab" button

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-07-02 22:26
Thanks for submitting this @flippy27 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2314 for Pinned or Locked tabs. As a possible stopgap to this, we do have the ability for Warp to show a warning when you're quitting a running session. https://docs.warp.dev/features/quit-warning

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-07-02 22:26
Duplicate of #2314

**Comment by dannyneira** [comment] 2024-07-02 22:27
Duplicate of #2314

**Closed by dannyneira** 2024-07-02 22:27 UTC
Labels: Feature requests
