### ISSUE TITLE
Pixel based hotkey window width/height settings

### ISSUE THREAD

**Issue by that70schris** [warpdotdev/Warp#5119] opened 2024-07-12 13:17 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

would be great if each of the width/height settings had an option to be based on a pixel count.

I'm constantly plugging into and disconnecting from a large monitor and using 40% width means that it's too wide on my large monitor but not wide enough on my laptop screen.  having a fixed width would mean that the content inside the terminal window always appears the same and it just takes up more of my laptop screen than my large monitor, which I would prefer.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-07-15 22:53
Thanks for submitting this @

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/876

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-07-15 22:53
Duplicate of https://github.com/warpdotdev/Warp/issues/876

**Closed by dannyneira** 2024-07-15 22:53 UTC
Labels: Feature requests
