### ISSUE TITLE
SSH config's 'Include' directive is not working

### ISSUE THREAD

**Issue by vladimirtemnikov** [warpdotdev/Warp#4758] opened 2024-04-14 22:22 UTC
### Describe the bug

Hello.
Currently Warp does not parse ssh config files which are linked to main `~/.ssh/config` file with `Include` keyword when I use `oh-my-zsh`.
I already saw https://github.com/warpdotdev/Warp/issues/4072, but I think it's more like a bug, because standard terminal with `oh-my-zsh` works with `Include` directive.

### To reproduce

1. touch `~/.ssh/foo`
2. add `foo-host` host into `foo`
3. add `Include ~/.ssh/foo` row to `~/.ssh/config`
4. try to autocomplete: `foo` -> Tab

### Expected behavior

All included files and nested included files should be parsed. 

### Operating system

MacOS

### Operating system and version

Sonoma 14.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.04.09.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-16 22:44
Hi @vladimirtemnikov the main issue is that Warp doesn't adhere to the include directive currently. Its a limitation with Warps SSH Wrapper implementation which we plan to improve later this year. We will be tracking it at https://github.com/warpdotdev/Warp/issues/4072 and post updates on there.

We thank you for your patience as we work to improve Warp.

Closing as a duplicate, I'll mark the other as a bug for clarity if you like.

**Comment by dannyneira** [comment] 2024-04-16 22:44
Duplicate of https://github.com/warpdotdev/Warp/issues/4072

**Closed by dannyneira** 2024-04-16 22:44 UTC
Labels: Bugs
