### ISSUE TITLE
shell prompt looks bad

### ISSUE THREAD

**Issue by willypaz243** [warpdotdev/Warp#4248] opened 2024-02-22 23:31 UTC
### Describe the bug

![image](https://github.com/warpdotdev/Warp/assets/26907682/8a7832f2-335b-4c40-86fd-de8ef5ae1977)

### To reproduce

does not represent line breaks in shell prompt

### Operating system

Linux

### Operating system and version

Debian 12

### Shell Version

fish, version 3.7.0

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-02-22 23:49
hey @willypaz243 thanks for submitting. Although Warp does support multi-line prompts for fish. Make sure your custom prompt is supported here: https://docs.warp.dev/appearance/prompt#custom-prompt-compatibility-table
If you're using starship.rs you may have to put the following in your `~/.config/starship.toml` to fix the issue.
```
[line_break]
disabled = true
```

Also, if you expect the prompt to be in the same line as the input, we're tracking it here https://github.com/warpdotdev/Warp/issues/2304.

**Comment by willypaz243** [comment] 2024-02-23 00:04
```

```

**Comment by dannyneira** [comment] 2024-02-27 21:23
Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Closed** 2024-02-29 21:52 UTC
Labels: Bugs
