### ISSUE TITLE
Ability to select text in Warp AI

### ISSUE THREAD

**Issue by feuersteiner** [warpdotdev/Warp#3395] opened 2023-07-20 07:51 UTC
### Describe the solution you'd like?

```Text
would be nice to be able to select specific text generated by warp AI for copy paste.
Also, the fact that it doesn't render code correctly (i.e. with colours) makes it super hard to read.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-07-24 19:53
Thanks for this feature request! 
To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified. There are also some related requests you can also track here #2553 & #2952

**Comment by dannyneira** [comment] 2024-01-18 23:34
hey folks, since we already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2553 we'll be closing this as a duplicate.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment] 2024-01-18 23:34
Duplicate of https://github.com/warpdotdev/Warp/issues/2553

**Closed by dannyneira** 2024-01-18 23:34 UTC
Labels: Feature
