### ISSUE TITLE
Unable to scroll to the bottom of the input area with extremely long text inputs

### ISSUE THREAD

**Issue by KevinWang15** [warpdotdev/Warp#5094] opened 2024-07-04 05:56 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

https://github.com/warpdotdev/Warp/assets/10173472/6661eef4-7bfa-4e46-92a4-a0c498bc5a12

If I paste some extremely long command into the input area, and try to scroll down (swipe down with two fingers on a MacBook trackpad), the content just bounces back, and I can never scroll to the bottom of the text.

### To reproduce

1. paste long input into text area
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel pretium lectus quam id leo in. Posuere morbi leo urna molestie. Elit eget gravida cum sociis natoque penatibus. Convallis tellus id interdum velit laoreet id donec ultrices tincidunt. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Lobortis mattis aliquam faucibus purus in. Pellentesque massa placerat duis ultricies lacus. Vulputate sapien nec sagittis aliquam. Nisi scelerisque eu ultrices vitae auctor eu augue ut. Dignissim suspendisse in est ante in. Tempor commodo ullamcorper a lacus vestibulum sed. Ac tortor vitae purus faucibus ornare suspendisse. Tempor orci eu lobortis elementum nibh tellus molestie. Cras ornare arcu dui vivamus arcu felis bibendum ut tristique. Leo vel orci porta non pulvinar neque laoreet suspendisse. Est sit amet facilisis magna etiam tempor orci eu. Urna nec tincidunt praesent semper feugiat nibh sed pulvinar proin.

Lacus vel facilisis volutpat est velit egestas dui id. Odio eu feugiat pretium nibh ipsum consequat. Id diam vel quam elementum pulvinar etiam. Nam aliquam sem et tortor consequat id. Tempor orci eu lobortis elementum nibh tellus. Ullamcorper morbi tincidunt ornare massa eget egestas. Nisi quis eleifend quam adipiscing vitae proin. Euismod quis viverra nibh cras pulvinar. Aliquet bibendum enim facilisis gravida neque convallis a cras semper. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Dui nunc mattis enim ut. Massa tincidunt dui ut ornare lectus. Consectetur a erat nam at. Pharetra massa massa ultricies mi. Porttitor leo a diam sollicitudin tempor. Et malesuada fames ac turpis egestas maecenas pharetra.

Commodo ullamcorper a lacus vestibulum sed arcu non odio. Nunc sed id semper risus in. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Erat velit scelerisque in dictum non consectetur. Sem integer vitae justo eget magna fermentum iaculis eu. Risus nullam eget felis eget nunc. Netus et malesuada fames ac turpis. Sit amet dictum sit amet justo donec enim diam vulputate. Lobortis mattis aliquam faucibus purus in massa tempor nec feugiat. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. In ornare quam viverra orci sagittis eu volutpat odio. Ultrices eros in cursus turpis. Pellentesque nec nam aliquam sem et tortor consequat id.

Amet nisl suscipit adipiscing bibendum. Consequat interdum varius sit amet. Risus commodo viverra maecenas accumsan. Faucibus vitae aliquet nec ullamcorper sit amet risus. Congue nisi vitae suscipit tellus mauris a diam maecenas sed. At auctor urna nunc id cursus. Bibendum est ultricies integer quis auctor elit sed vulputate. Lorem mollis aliquam ut porttitor leo a. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Tempus imperdiet nulla malesuada pellentesque elit. Elementum nibh tellus molestie nunc non blandit massa enim nec.

Egestas diam in arcu cursus euismod quis. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Enim nunc faucibus a pellentesque sit amet. Integer feugiat scelerisque varius morbi enim. Iaculis urna id volutpat lacus laoreet non curabitur gravida arcu. Vestibulum sed arcu non odio euismod. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Quam id leo in vitae turpis massa sed. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Arcu dui vivamus arcu felis bibendum ut. Sit amet purus gravida quis blandit turpis cursus in. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Mauris pharetra et ultrices neque ornare aenean. In fermentum posuere urna nec tincidunt praesent. Ipsum a arcu cursus vitae.

Quam id leo in vitae turpis massa sed elementum tempus. Felis imperdiet proin fermentum leo. Sit amet venenatis urna cursus eget nunc scelerisque viverra. Condimentum id venenatis a condimentum vitae sapien. Placerat in egestas erat imperdiet sed euismod nisi. Massa eget egestas purus viverra. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor. Egestas diam in arcu cursus euismod quis. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Cursus risus at ultrices mi tempus.

Arcu cursus euismod quis viverra. Nunc id cursus metus aliquam. Erat velit scelerisque in dictum. Neque viverra justo nec ultrices dui. Lorem ipsum dolor sit amet consectetur adipiscing elit. Urna nunc id cursus metus aliquam eleifend mi in. Consectetur a erat nam at lectus. Auctor neque vitae tempus quam pellentesque nec. Proin libero nunc consequat interdum varius sit. Quam quisque id diam vel quam. Amet consectetur adipiscing elit ut aliquam purus sit amet luctus. Duis convallis convallis tellus id interdum velit laoreet. Purus semper eget duis at tellus. Luctus accumsan tortor posuere ac ut consequat semper viverra.

Blandit libero volutpat sed cras ornare arcu dui vivamus. Varius sit amet mattis vulputate enim nulla aliquet. Malesuada fames ac turpis egestas integer eget. Ut aliquam purus sit amet luctus venenatis lectus magna fringilla. Eget lorem dolor sed viverra ipsum. Aliquam etiam erat velit scelerisque in dictum non consectetur. Turpis massa sed elementum tempus egestas. Enim sit amet venenatis urna cursus eget nunc. Ultricies integer quis auctor elit sed vulputate. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida. Cursus mattis molestie a iaculis at. Adipiscing tristique risus nec feugiat. Convallis tellus id interdum velit laoreet id donec. Massa sed elementum tempus egestas sed sed risus pretium quam. At imperdiet dui accumsan sit amet nulla facilisi morbi. Luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Pharetra et ultrices neque ornare aenean euismod elementum. Ac turpis egestas sed tempus urna et pharetra pharetra. Turpis massa tincidunt dui ut.

Facilisis magna etiam tempor orci eu lobortis elementum. Pretium fusce id velit ut tortor pretium. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Facilisi morbi tempus iaculis urna id volutpat. Neque volutpat ac tincidunt vitae semper. Sagittis eu volutpat odio facilisis mauris sit. Cursus risus at ultrices mi. Nisl condimentum id venenatis a. Vestibulum lectus mauris ultrices eros. Pulvinar mattis nunc sed blandit libero volutpat sed. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Bibendum neque egestas congue quisque.

Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Eget sit amet tellus cras adipiscing. Ornare arcu odio ut sem nulla pharetra. Eget nunc scelerisque viverra mauris. Elit ut aliquam purus sit amet luctus. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Ipsum dolor sit amet consectetur. Ut enim blandit volutpat maecenas. Vivamus arcu felis bibendum ut tristique et. In dictum non consectetur a erat nam. A diam sollicitudin tempor id eu nisl. Volutpat commodo sed egestas egestas fringilla phasellus. Praesent semper feugiat nibh sed. Facilisis magna etiam tempor orci.

Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Elit pellentesque habitant morbi tristique senectus et netus. Cursus euismod quis viverra nibh cras pulvinar mattis nunc. Ullamcorper malesuada proin libero nunc consequat interdum. Laoreet id donec ultrices tincidunt arcu non sodales. Consequat mauris nunc congue nisi. In cursus turpis massa tincidunt dui ut ornare lectus. Ac turpis egestas sed tempus urna et. Felis donec et odio pellentesque diam volutpat commodo sed. Ut morbi tincidunt augue interdum velit euismod in. Vestibulum morbi blandit cursus risus at ultrices mi tempus. Nibh venenatis cras sed felis eget velit aliquet sagittis id. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Ultrices dui sapien eget mi proin sed. Maecenas volutpat blandit aliquam etiam erat. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. At quis risus sed vulputate odio ut. Nunc aliquet bibendum enim facilisis gravida neque. Sapien eget mi proin sed libero.

Dui faucibus in ornare quam. Nibh cras pulvinar mattis nunc sed blandit libero. Ac placerat vestibulum lectus mauris ultrices eros. Libero id faucibus nisl tincidunt eget nullam non nisi est. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus. Lectus arcu bibendum at varius vel. Purus semper eget duis at. Pharetra massa massa ultricies mi quis hendrerit dolor. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Morbi tristique senectus et netus et malesuada fames ac. Nunc sed velit dignissim sodales ut. Sagittis orci a scelerisque purus semper. Euismod in pellentesque massa placerat duis. Neque ornare aenean euismod elementum nisi quis. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Tincidunt vitae semper quis lectus nulla at volutpat diam ut. Dignissim convallis aenean et tortor.

Massa sapien faucibus et molestie ac. Pharetra convallis posuere morbi leo urna molestie at elementum eu. Cursus sit amet dictum sit amet justo donec enim diam. Scelerisque varius morbi enim nunc. Sed felis eget velit aliquet sagittis id. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Orci sagittis eu volutpat odio facilisis mauris. Adipiscing tristique risus nec feugiat. Morbi quis commodo odio aenean sed adipiscing. Aliquam id diam maecenas ultricies. Velit egestas dui id ornare arcu odio ut sem nulla. Vulputate mi sit amet mauris commodo. Magna sit amet purus gravida quis.

Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien nec. Augue eget arcu dictum varius duis at consectetur lorem donec. Vitae et leo duis ut diam quam nulla. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Tristique sollicitudin nibh sit amet commodo nulla facilisi. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Eget nunc lobortis mattis aliquam. Id diam maecenas ultricies mi. Orci nulla pellentesque dignissim enim sit amet venenatis urna. Risus ultricies tristique nulla aliquet enim tortor at auctor. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum est.

Massa enim nec dui nunc mattis enim ut. Maecenas ultricies mi eget mauris pharetra. Nisl purus in mollis nunc sed id semper. Dolor sit amet consectetur adipiscing elit. Pellentesque id nibh tortor id aliquet lectus. At varius vel pharetra vel turpis. Facilisis magna etiam tempor orci eu lobortis elementum. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sodales neque sodales ut etiam. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Risus sed vulputate odio ut enim blandit volutpat. Bibendum at varius vel pharetra vel. Penatibus et magnis dis parturient montes. Convallis a cras semper auctor neque vitae tempus quam pellentesque. Aenean vel elit scelerisque mauris pellentesque. Bibendum at varius vel pharetra vel turpis nunc. Turpis tincidunt id aliquet risus.

Odio facilisis mauris sit amet massa vitae. In fermentum et sollicitudin ac orci phasellus egestas. Ultricies mi quis hendrerit dolor magna eget est. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Tellus integer feugiat scelerisque varius morbi enim. Proin libero nunc consequat interdum varius sit amet. Nisl vel pretium lectus quam id leo in. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. Urna nunc id cursus metus aliquam eleifend mi in. Hendrerit dolor magna eget est lorem ipsum dolor sit. Consequat nisl vel pretium lectus quam id. In fermentum posuere urna nec tincidunt praesent semper. Facilisis mauris sit amet massa vitae tortor.
```

2. try to scroll down

### Operating system

MacOS

### Operating system and version

14.5.0

### Current Warp version

v0.2024.06.25.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Advait-M** [comment] 2024-07-08 02:47
Thanks for reporting this!

This is actually a duplicate of #2400, I believe 👀 . I'd actually looked briefly into fixing this particular issue earlier though there's some added complexity behind-the-scenes. It's good to know that other folks are running into this as well - I hope we'll be able to re-prioritize this soon, though can't give a concrete ETA here!

Curious @KevinWang15 - what sort of use case necessitates such very long inputs in the terminal context? Just to better inform us of what set of users might be impacted here.

**Comment by KevinWang15** [comment] 2024-07-08 03:16
> Thanks for reporting this!
> 
> This is actually a duplicate of #2400, I believe 👀 . I'd actually looked briefly into fixing this particular issue earlier though there's some added complexity behind-the-scenes. It's good to know that other folks are running into this as well - I hope we'll be able to re-prioritize this soon, though can't give a concrete ETA here!
> 
> Curious @KevinWang15 - what sort of use case necessitates such very long inputs in the terminal context? Just to better inform us of what set of users might be impacted here.

Hi @Advait-M , one use case for this is transfering files. Sometimes we would do 

```
echo ...(very long text).... | base64 -d > file
```

Thanks

**Comment by dannyneira** [comment] 2024-07-10 19:58
Thanks for letting us know @KevinWang15 . We'll be tracking this issue on #2400 to subscribe there for any future updates.

**Comment by dannyneira** [comment] 2024-07-10 19:59
Duplicate of #2400

**Closed by dannyneira** 2024-07-10 19:59 UTC
Labels: Bugs

**Comment by Advait-M** [comment] 2024-07-10 20:05
> Hi @Advait-M , one use case for this is transfering files. Sometimes we would do
> 
> ```
> echo ...(very long text).... | base64 -d > file
> ```
> 
> Thanks

Gotcha - that makes sense; thanks for the example!
