### ISSUE TITLE
Non consistent font customization

### ISSUE THREAD

**Issue by freizl** [warpdotdev/Warp#4651] opened 2024-03-28 05:20 UTC
### Describe the solution you'd like?

I customized the font in the settings. It works great at console but not other places like Warp Driver, Warp AI, Warp essentials pane.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-28 17:06
Duplicate of https://github.com/warpdotdev/Warp/issues/1443

**Closed by dannyneira** 2024-03-28 17:06 UTC
Labels: Feature requests
