### ISSUE TITLE
Adjust Font size in Warp AI panel

### ISSUE THREAD

**Issue by jiangyewen** [warpdotdev/Warp#4531] opened 2024-03-11 03:25 UTC
### Describe the solution you'd like?

Font size in Warp AI panel is currently too small and can't be changed. 

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-12 17:20
Thanks for submitting this @

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1443

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-12 17:21
Duplicate of https://github.com/warpdotdev/Warp/issues/1443

**Closed by dannyneira** 2024-03-12 17:21 UTC
Labels: Feature requests
