### ISSUE TITLE
Using too much memory

### ISSUE THREAD

**Issue by aksbaih** [warpdotdev/Warp#4544] opened 2024-03-12 17:36 UTC
### Describe the bug

With 6 tabs, long running commands over ssh, memory usage is going up to 3.2GB which is significant.. even more than Google Chrome with hundreds of tabs open hehe

### To reproduce

With 6 tabs, long running commands over ssh,

### Operating system

MacOS

### Operating system and version

14.2.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-12 21:09
We're tracking this issue over at #2611 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-12 21:09
Duplicate of #2611

**Closed by dannyneira** 2024-03-12 21:09 UTC
Labels: Bugs
