### ISSUE TITLE
Warp + asdf + neovide issue (mac)

### ISSUE THREAD

**Issue by gorkunov** [warpdotdev/Warp#3180] opened 2023-06-06 09:54 UTC
### Describe the bug

I found very strange issue somewhere in connection between warp, [asdf](https://github.com/asdf-vm/asdf) and [neovide](https://neovide.dev/). 

I'm using asdf for managing elixir, erlang and nodejs for projects. I'm working with the code using nvim (neovide) which is relaying on binaries of elixir/nodejs etc provided by asdf. Which binary is used depends on directory where I run neovide.
Sounds like a standard approach nowadays.  

The issue that if I run neovide (but not a terminal nvim) from warp (`neovide` command) then it fully brakes connection with binaries. All elixir/nodejs and other binaries provided by asdf fully broken. 

E.g. if I run `!node --version` I see this:
<img width="533" alt="Screenshot 2023-06-06 at 10 47 41@2x" src="https://github.com/warpdotdev/Warp/assets/378207/3da73754-7876-424c-ab4f-f7a9fe94bdb8">
and this for elixir:
<img width="763" alt="Screenshot 2023-06-06 at 10 48 18@2x" src="https://github.com/warpdotdev/Warp/assets/378207/17d23629-ba66-4b00-9bd7-874a168e590e">.

However if I do the same from standard terminal.app everything works fine.
This issue doesn't reproduce in nvim (terminal). For neovide it doesn't matter if I run it in detached mode (by default) or not (`--nofork`).
 

### To reproduce

1. Install asdf, warp and neovide
2. Install any tool using asdf (e.g. nodejs, elixir)
3. Run neovide from warp
4.  run `:!node --version` in neovide.

### Operating system

MacOS

### Operating system and version

Catalina 10.15.7

### Current Warp version

v0.2023.05.30.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-06-06 22:07
Hi @gorkunov Thanks for letting us know. I wasn't able to reproduce the error when I tried with node.
 
![CleanShot 2023-06-06 at 16 05 17](https://github.com/warpdotdev/Warp/assets/16809145/c9fceb67-0bf1-48fa-a26c-0898f59d191b)
 
 Is it possible you have another plugin or tool that Warp doesn't support? You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```
We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by gorkunov** [comment] 2023-06-07 08:41
hey @dannyneira thanks for the response. Could you check in neovide with command `:!which node` where the source of node binary? I just want to confirm that you are using shims from asdf.

**Comment by dannyneira** [comment] 2023-06-07 15:21
Same, my `which node == /opt/homebrew/bin/node`, I'll surface this with the team as it seems like neovide isn't being passed the appropriate information from asdf. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by gorkunov** [comment] 2023-06-07 15:53
I guess this is not a neovide specific but rather the way how neovide forks/runs from terminal. B/c if I run it from my dock it works fine.

**Comment by dannyneira** [comment] 2023-06-08 19:52
@gorkunov If you're comfortable with sharing, please let us know the result of `echo $PATH` both inside neovide and within the Warp session that launched it. Also, a redacted version of your rc files ( .zshrc, .bashrc, etc. ). This will help us in narrowing down the possible root of the issue.

**Comment by charlespierce** [comment] 2023-06-09 16:50
@gorkunov Thanks, that's helpful! Which version of `asdf` are you using? It looks like this may be some changed behavior in their setup (see https://github.com/asdf-vm/asdf/issues/1550) that has subsequently been fixed / updated (though it doesn't appear that fix has been released yet).

**Comment by gorkunov** [comment] 2023-06-10 08:52
I'm using `v0.11.0`

**Comment by dannyneira** [comment] 2023-06-12 16:16
Try upgrading to asdf `0.11.3` and see if that helps with the issue

**Comment by gorkunov** [comment] 2023-06-15 17:17
installed `0.12.0` - same issue.

**Comment by dannyneira** [comment] 2023-06-22 18:52
Thanks for letting us know! We'll close this issue, but feel free to shout open a new bug for any issues with Warp.

**Closed by dannyneira** 2023-06-22 18:52 UTC
Labels: Bug
