### ISSUE TITLE
warp doesn't retain theme across quit / restart / upgrades

### ISSUE THREAD

**Issue by rohany** [warpdotdev/Warp#557] opened 2022-01-02 15:49 UTC
### Describe the bug

```shell
Warp does not retain a user selected theme across closing of the terminal.
```

### To Reproduce

1) pick a theme in the theme picker
2) quit warp (on Mac force quit it)
3) Re-open warp -- the chosen theme will be gone

### Expected behaviour

```shell
I expect that the theme I selected before should be retained when I re-open warp.
```

### Operating System

MacOS

### OS Version

10.15.7

**Comment by elviskahoro** [comment] 2022-01-20 08:43
@rohany I can't reproduce this. Is this still happening for you? Gonna close, please reopen if it is.

**Comment by rohany** [comment] 2022-01-21 05:42
This didn't work for me just now after a restart, on v0.2022.01.17.08.48.stable_01.

**Comment by elviskahoro** [comment] 2022-01-21 18:05
@rohany can you send me a video? elvis@warp.dev

**Comment by rohany** [comment] 2022-01-22 01:14
I don't know how to take a video, it only happens when my computer or warp restart due to an update.

**Comment by elviskahoro** [comment] 2022-01-22 02:00
Which number(s) is it?
1. Machine restarts and Warp theme disappears.
2. Warp restarts because of an update and loses theme.
3. Everytime you close warp it loses theme.

Also:
A. is it any theme?
B. One of the built in themes?
C. A custom theme?


It also happens when Warp restart

**Comment by rohany** [comment] 2022-01-23 07:54
I've seen 1 and 2 happen -- 1 just happened to me which is why I reopened the issue. I only use the builtin-solarized theme, so I can't comment about the other two options.

**Comment by elviskahoro** [comment] 2022-01-24 18:42
Can you remove Warp application support files?
remove: ~/<USER>/Application Support/warp
remove: ~/<USER>/Application Support/dev.warp

**Comment by rohany** [comment] 2022-01-24 23:29
Those files (and the Application Support directory) do not exist on my machine

**Comment by elviskahoro** [comment] 2022-01-24 23:31
Ugh. GitHub

~/ <YOUR USER NAME> / Application Support / warp

CMD-SHIFT-. should show your hidden folders in Finder. They should exist!

**Comment by elviskahoro** [comment] 2022-01-24 23:32
You should be able to see them in terminal with `ls -a`

**Comment by elviskahoro** [comment] 2022-01-24 23:33
Do these directories exist:

`~/Library/Application Support/warp`
`~/Library/Application Support/dev.Warp-Stable`

If so can you delete them?
Try CMD-SHIFT-. in finder (as they are hidden folders) or `ls -a` in terminal

**Comment by rohany** [comment] 2022-01-24 23:35
The dev.Warp-Stable directory existed, and I've deleted it now.

**Comment by elviskahoro** [comment] 2022-01-24 23:36
Hopefully this fixes it.

**Comment by rohany** [comment] 2022-01-24 23:37
OK, I'll close the issue after the next update and see if the profile is retained!

**Comment by elviskahoro** [comment] 2022-01-25 22:50
@rohany is warp installed in the Applications directory btw?

**Comment by elviskahoro** [comment] 2022-01-25 22:52
I'll close the issue now and then u can reopen if it doesn't retain!

**Closed by elviskahoro** 2022-01-25 22:52 UTC
