### ISSUE TITLE
fix(shortcut): "Activate Previous/Next Tab" does not work with `cmd + opt + ←/→`

### ISSUE THREAD

**Issue by jjangga0214** [warpdotdev/Warp#2984] opened 2023-04-26 02:52 UTC
### Describe the bug

Though the shortcut work with the default setting, it doesn't with the shortcut below.
(Some applications (e.g. web browser) use `cmd + opt + ←/→` as a shortcut for activating Previous/Next tab by default. So I want to configure the shortcut coherently. Note that Tabby supports this configuration)

Sincerely,

### To Reproduce

<img width="473" alt="스크린샷 2023-04-26 오전 11 44 44" src="https://user-images.githubusercontent.com/28584151/234453732-c3d3eac6-c751-46cf-a073-8687b63047e2.png">

### Operating System

MacOS

### Operating System and Version

13.3.1(22E261)

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-04-26 17:27
Hi @jjangga0214 Thanks for submitting. So the problem appears to be that the Activate Left/Right pane is currently the default for `OPT-CMD-LEFT/RIGHT`, once you "Clear" those key binds and "Save" you should be able to use those bindings for activate previous/next tabs. In general, if you ever see a yellow highlight around a key bind, that means it conflicts with another existing one and will not work correctly until the conflict is resolved.

**Comment by dannyneira** [comment] 2023-04-26 17:44
Hi @jjangga0214 Thanks for submitting! 

So the problem appears to be that the "switch pane Left/Right" is currently the default for `OPT-CMD-LEFT/RIGHT`, once you "Clear" those key binds you should be able to use those bindings to activate previous/next tabs. In general, if you ever see a yellow highlight around a key bind, that means it conflicts with another existing one and will not work correctly until the conflict is resolved.

https://user-images.githubusercontent.com/16809145/234659586-1dd7465f-486a-4259-a12d-0ced2ce76e61.mp4

Closing as resolved, since the issue isn't a bug.

**Closed by dannyneira** 2023-04-26 17:44 UTC
Labels: Bug
