### ISSUE TITLE
Custom increase/decrease font size in Warp AI block

### ISSUE THREAD

**Issue by eduardsantamaria** [warpdotdev/Warp#4121] opened 2024-02-02 10:08 UTC
### Describe the solution you'd like?

Is possible to increase o decrease o set a different font size for Warp AI block. Current font size in this block ar too small.
![image](https://github.com/warpdotdev/Warp/assets/63660928/ccd32bde-9a57-43ec-a58a-52006fc273d1)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-02 23:26
Thanks for submitting this @eduardsantamaria 

We already have a request tracking this over at #1443

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-02 23:26
Duplicate of #1443

**Closed by dannyneira** 2024-02-02 23:26 UTC
Labels: Feature
