### ISSUE TITLE
Open at folder.

### ISSUE THREAD

**Issue by akshat-cldcvr** [warpdotdev/Warp#2295] opened 2022-12-05 07:37 UTC
### Describe the solution you'd like?

```text
There should be an "open warp at folder" menu option like Terminal and iTerm2.
```

### Is your feature request related to a problem? Please describe.

```text
Not a power user so not have option to directly open it from menu is a deal breaker.
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2022-12-05 17:00
Hi @akshat-cldcvr Thanks for this request! It's a duplicate of #102. 

Please :+1:  and subscribe to that request as it helps us gauge interest. We will post any updates there.

**Comment by dannyneira** [comment] 2022-12-05 17:00
Closing as duplicate

**Comment by dannyneira** [comment] 2022-12-05 17:00
Hi @akshat-cldcvr Thanks for this request! It's a duplicate of #102. 

Please :+1:  and subscribe to that request as it helps us gauge interest. We will post any updates there.

Closing this one as a duplicate.

**Closed by dannyneira** 2022-12-05 17:00 UTC
Labels: Feature
