### ISSUE TITLE
Wrap AI chat history like Chat GPT chat history

### ISSUE THREAD

**Issue by AndrewAi** [warpdotdev/Warp#4165] opened 2024-02-10 18:16 UTC
### Describe the solution you'd like?

Hi, 

Warp is really cool just started using it yesterday Thank you for creating it! 
I build apps, most of my experience is frontend with react and vue.

I dislike the terminal, as I always forget the commands, and find the terminal a bit too technical for what I like.

Warp is great, because I'm trying for it to do all the terminal tasks for me! 

It would be great if I could see the recent chats I've had with warp ai, as again I forget where I was/ doing, and can pick up where I left off.

Is this a feature that you can include? 

Thanks very much,

Andrew 

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-12 18:34
Thanks for submitting this @AndrewAi. We're glad you're enjoying Warp!

We already have a request tracking this over at #3838

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-12 18:34
Duplicate of #3838

**Comment by AndrewAi** [comment] 2024-02-12 20:05
Thanks Danny sorry for creating a duplicate.Regards Andrew On 12 Feb 2024, at 18:35, Danny Neira ***@***.***> wrote:﻿
Thanks for submitting this @AndrewAi. We're glad you're enjoying Warp!
We already have a request tracking this over at #3838
If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!
We'll be closing this as a duplicate.

**Closed** 2024-02-29 21:43 UTC
Labels: Feature requests
