### ISSUE TITLE
why can't I collapse blocks?

### ISSUE THREAD

**Issue by fredzannarbor** [warpdotdev/Warp#4931] opened 2024-05-19 08:24 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I want to be able to scan blocks, but some of mine have very long output that takes up the entire screen.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-20 20:12
Duplicate of #23

**Closed by dannyneira** 2024-05-20 20:12 UTC
Labels: enhancement

**Comment by fredzannarbor** [comment] 2024-05-20 20:25
I am not a big fan of relying on thumbs up symbols when deciding whether to
fix an issue that confronts users with numerous large blocks of
unskimmable text. Some things should be done simply because they are the
right thing to do.

**Comment by dannyneira** [comment] 2024-05-20 20:55
It on our radar as a possible fix, but we're a small team so it's a challenge to prioritize many things at once so we appreciate your patience. For the time being, you can hopefully use the [Find](https://docs.warp.dev/features/find) feature to search through the blocks more efficiently. Also, consider using [Block Bookmarks](https://docs.warp.dev/features/blocks/block-actions#bookmarking-a-block) for important blocks you need to reference later. Hope this helps!
