### ISSUE TITLE
Respect SSH "Include" directive for SSH host name autocompletion

### ISSUE THREAD

**Issue by solus-hq** [warpdotdev/Warp#4109] opened 2024-01-29 13:39 UTC
### Describe the solution you'd like?

Make Warp respect the SSH "Include" directive in `~/.ssh/config`

### Is your feature request related to a problem? Please describe.

Since I use Warp most of the time it's quite sad to see it doesn't respect the SSH "Include" directive in `~/.ssh/config` leaving only one file to be scanned for host entries.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-29 21:29
Thanks for submitting @solus-hq. We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/4072

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-29 21:29
Duplicate of https://github.com/warpdotdev/Warp/issues/4072

**Closed by dannyneira** 2024-01-29 21:29 UTC
Labels: Feature
