### ISSUE TITLE
DUP: #501 - Tmux native support

### ISSUE THREAD

**Issue by HognGa4z** [warpdotdev/Warp#1002] opened 2022-04-11 03:46 UTC
### Discord username (optional)

hankinzhang

### Describe the solution you'd like?

```text
Hope warp would support tmux native, like `tmux -CC session`.
```

**Comment by elviskahoro** [comment] 2022-04-11 17:52
Duplicate of:
- #501

**Closed** 2022-04-11 17:52 UTC
