### ISSUE TITLE
Option in the context menu to save output of block to file

### ISSUE THREAD

**Issue by assayire** [warpdotdev/Warp#3733] opened 2023-10-05 14:58 UTC
### Describe the solution you'd like?

```Text
It would be handy if the right click context menu of a block has an entry to save the output directly to a file (instead of having to copy and go through the hassles of creating a file and pasting the content)
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-10-10 20:36
Hey @assayire Thanks for the feature request, That would be a cool idea for sure. As a possible stopgap, when you run a command you can`>` the output into a file (i.e. `echo "Hello" > hello.txt`).

To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by assayire** [comment] 2023-10-11 04:10
Yes I am using the stopgap solution (redirection) in the cases when I know before hand. Would be lovely to see this in Warp in the near future.

**Comment by dannyneira** [comment] 2024-01-30 20:57
We already have a request tracking this over at #2330.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-30 20:57
Duplicate of #2330

**Closed by dannyneira** 2024-01-30 20:57 UTC
Labels: Feature
