### ISSUE TITLE
kubectl resource name completion

### ISSUE THREAD

**Issue by karimeid-is** [warpdotdev/Warp#5091] opened 2024-07-03 05:52 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When trying to use any of the following commands:

- kubectl get (pod, node ,service, ...)
- kubectl describe (pod, node ,service, ...)
- kubectl log 

Warp is not able to query the actual resource names instead it shows a menu with other flags/options.

Example:
![image](https://github.com/warpdotdev/Warp/assets/170401694/b8986929-bc25-48fe-a778-b841f9fe8107)

### To reproduce

Run any of the above commands while authenticated to a kubernetes cluster and try to press the Tab key twice on your keyboard.

### Expected behavior

Resource/s name should be displayed as a suggestion to be autofilled.

for example this is the default terminal behavior:  
![image](https://github.com/warpdotdev/Warp/assets/170401694/708ac456-7a38-4839-9469-486b71c59f47)

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.06.25.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-07-03 15:45
Thanks for letting us know @karimeid-is Thanks for letting us know. There is a workaround for this [here](https://github.com/warpdotdev/Warp/issues/3929#issuecomment-1839681947). Essentially if you put the namespace first, then the command like `log` the completions menu should show up properly. If any issues you can also just run your shell `zsh` in a subshell and fallback to the shell completions for kubectl.

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/3929 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-07-03 15:45
Duplicate of https://github.com/warpdotdev/Warp/issues/3929

**Closed by dannyneira** 2024-07-03 15:45 UTC
Labels: Bugs
