### ISSUE TITLE
i18n Support multiple languages and localizations

### ISSUE THREAD

**Issue by JuHyung-Son** [warpdotdev/Warp#473] opened 2021-12-01 12:14 UTC
### Describe the solution you'd like?

```shell
Support multiple language
```

### Is your feature request related to a problem? Please describe.

```shell
If computer language setting is not english, (like korean, japanese) shortcut does not work.
```

**Comment by mirkhosro** [comment] 2022-08-25 17:28
a related issue is that shell key commands (like ctrl+a for going to the beginning of the line or ctrl+l to clear the screen) do not work when the keyboard layout is set to a non-Latin language.

**Comment by dannyneira** [comment] 2023-12-26 19:06
Hey Folks, We're closing this as a duplicate since there are more 👍's on a similar request. https://github.com/warpdotdev/Warp/issues/1194

**Comment by dannyneira** [comment] 2023-12-26 19:06
Duplicate of https://github.com/warpdotdev/Warp/issues/1194

**Closed by dannyneira** 2023-12-26 19:06 UTC
Labels: enhancement
