### ISSUE TITLE
Issues with z

### ISSUE THREAD

**Issue by lukaskretzschmer** [warpdotdev/Warp#4721] opened 2024-04-09 16:19 UTC
### Describe the bug

I am trying to use z but autocompletion takes over.
![image](https://github.com/warpdotdev/Warp/assets/29391908/5464e849-2381-4482-b8f1-d3e64dc0ce6a)
If I press space or anything it will autocomplete, so I am unable to use just z.
https://github.com/rupa/z

### To reproduce

Idk, activate it as a zsh plugin
![image](https://github.com/warpdotdev/Warp/assets/29391908/bf8d4f86-e36f-406a-8022-bf321957d3f2)

### Expected behavior

To allow me to use z and not take over with autocompletion.

### Operating system

Linux

### Operating system and version

PopOs latest

### Shell Version

zsh 

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-09 16:33
Hi @lukaskretzschmer Sorry about this, but `z` is on the list on incompatible tools. As a workaround, you can run `zsh` in a subshell and fall-back to plugins like `z`. Blocks and Warp completions will stop working, but you can use the other autocompletion plugins. 

You can also disable just that of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > z autocompletion code goes here <
fi
```

https://docs.warp.dev/help/known-issues#list-of-incompatible-tools

Closing as this is a known issue we are tracking the ability to use shell based completions like `z` here #434

**Comment by dannyneira** [comment] 2024-04-09 16:33
Duplicate of #434

**Closed by dannyneira** 2024-04-09 16:33 UTC
Labels: Bugs
