### ISSUE TITLE
Custom Bash shell prompt looks wrong.

### ISSUE THREAD

**Issue by toastdevv** [warpdotdev/Warp#4885] opened 2024-05-07 13:08 UTC
### Dupe Check

- [x] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I just installed Warp and it's asking me to choose a prompt. While looking at the "Shell prompt" option I noticed that it looks wrong. I will send images to explain further:

**On a normal terminal:**
![image](https://github.com/warpdotdev/Warp/assets/92093881/c2804414-ea9e-48df-bfba-dd5e3df8d505)

**On Warp:**
![image](https://github.com/warpdotdev/Warp/assets/92093881/a04d71a3-dd76-45af-9a50-a1187278bbb9)
![image](https://github.com/warpdotdev/Warp/assets/92093881/6862784d-ddda-482f-b6b8-9aa2d1af448f)

I think the issue may have to do with newlines in the prompt.

### To reproduce

1. Modify your PS1 variable in your .bashrc file to have more than one line.
2. Switch to the shell prompt on Warp.

### Expected behavior

My expectations would be for the shell prompt to be rendered correctly the same way it looks on normal terminals including the newlines.

### Operating system

Linux

### Operating system and version

Linux Mint 21.3

### Shell Version

bash 5.1.16

### Current Warp version

v0.2024.04.30.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-05-07 20:13
Duplicate of #2304

**Closed by dannyneira** 2024-05-07 20:13 UTC
Labels: Bugs
