### ISSUE TITLE
OSX Window hotkey not working

### ISSUE THREAD

**Issue by randomradio** [warpdotdev/Warp#3257] opened 2023-06-25 14:58 UTC
### Describe the bug

On osx Ventura 13.4 (22F66)

I set global hotkey to CMD + \

<img width="556" alt="image" src="https://github.com/warpdotdev/Warp/assets/2393895/8fab25c1-a617-4098-8145-1494de0f49a8">

But it does not taking effect at all. 

### To reproduce

Set CMD+\ key as window hotkey as instructed.

<img width="556" alt="image" src="https://github.com/warpdotdev/Warp/assets/2393895/b7aee108-5451-4776-8112-f267e8d52dcb">

### Expected behavior

Able to activate/call out Warp terminal window

### Screenshots

<img width="556" alt="image" src="https://github.com/warpdotdev/Warp/assets/2393895/b02dd06d-c4be-4c1a-8427-65cf10a49d97">

### Operating system

MacOS

### Operating system and version

Ventura 13.4 (22F66)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-06-26 18:10
Thanks for letting us know @randomradio Unfortunately I can't reproduce this issue. I was able to set `CMD-\` shortcut and it's working correctly. Are you by any chance using an international keyboard instead of US?

**Comment by randomradio** [comment] 2023-06-27 04:18
hmm. interesting, this hotkey setting works for iTerm2.
I'm using a FILCO Majestouch MINILA-R Convertible keyboard. I'll  post a screencast for you to debug. I'm wondering if there's any other app hijacked the key events. But as far as I know, I don't have anything that captures the event..


https://github.com/warpdotdev/Warp/assets/2393895/361f3e71-f89f-4f33-a62e-6bd61438f42e

**Comment by randomradio** [comment] 2023-07-02 13:01
@dannyneira I think I've found the issue. When my system input source changed to other language, in my case Chinese. Such key combination will not work.

**Comment by dannyneira** [comment] 2023-07-05 18:21
Thanks for letting us know @randomradio 

We're tracking this issue over at #341  and would appreciate it if you could :+1: and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Closed by dannyneira** 2023-07-05 18:21 UTC
Labels: Bug
