### ISSUE TITLE
display abnormally with powerlevel10k

### ISSUE THREAD

**Issue by CyrilTaylor** [warpdotdev/Warp#3253] opened 2023-06-24 15:30 UTC
### Describe the bug

![image](https://github.com/warpdotdev/Warp/assets/12631466/c7721487-f237-4f48-922a-bf8d1ebeaff6)

### To reproduce

1. update to lastest powerlevel10k
2. config p10k with two-line
3. custom the prompt
```diff
diff --git a/.p10k.zsh b/.p10k.zsh
index 9fb0e29..9d1d905 100644
--- a~/.p10k.zsh
+++ b~/.p10k.zsh
@@ -37,6 +37,7 @@
     vcs                     # git status
     # =========================[ Line #2 ]=========================
     newline                 # \n
+    context                 # user@hostname
     prompt_char             # prompt symbol
   )

@@ -85,11 +86,10 @@
     gcloud                  # google cloud cli account and project (https://cloud.google.com/)
     google_app_cred         # google application credentials (https://cloud.google.com/docs/authentication/production)
     toolbox                 # toolbox name (https://github.com/containers/toolbox)
-    context                 # user@hostname
+    # context                 # user@hostname
     nordvpn                 # nordvpn connection status, linux only (https://nordvpn.com/)
     ranger                  # ranger shell (https://github.com/ranger/ranger)
     nnn                     # nnn shell (https://github.com/jarun/nnn)
@@ -102,8 +102,7 @@
     todo                    # todo items (https://github.com/todotxt/todo.txt-cli)
     timewarrior             # timewarrior tracking status (https://timewarrior.net/)
     taskwarrior             # taskwarrior task count (https://taskwarrior.org/)
     # cpu_arch              # CPU architecture
     time                    # current time
+    # time                    # current time
     # =========================[ Line #2 ]=========================
     newline
     # ip                    # ip address and bandwidth usage for a specified network interface
@@ -111,6 +110,7 @@
     # proxy                 # system-wide http/https/ftp proxy
     # battery               # internal battery
     # wifi                  # wifi speed
+    time                    # current time
     # example               # example user-defined segment (see prompt_example function below)
   )
```

### Operating system

MacOS

### Operating system and version

MacOS 13.4

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by ipfans** [comment] 2023-06-25 06:43
I have the same issue with my own theme :(

**Comment by dannyneira** [comment] 2023-06-26 16:56
Hey Folks, thanks for submitting this. We're working on some of the issues with p10k support and tracking them here: https://github.com/warpdotdev/Warp/issues/2851

I'll mark this one as a related issue.

**Comment by dannyneira** [comment] 2023-08-30 20:59
@ipfans Warp recently added support for right-side and multi-line prompts. Are you still seeing this issue with the latest updates?

**Comment by ipfans** [comment] 2023-08-31 14:34
@dannyneira thanks for your update. But the issue is still there...

**Comment by dannyneira** [comment] 2023-08-31 15:26
@ipfans Would you mind providing a copy of your `.zshrc` along with your `.p10k.zsh` file? Please make sure there is no personal info in there. This will help us with reproducing the issue on our end.

**Comment by Advait-M** [comment] 2023-12-16 23:41
Hey @CyrilTaylor @ipfans thanks for reporting - we're actively working on this in #2304, closing this issue in favour of that one! Feel free to 👍 that issue to indicate interest as well!

**Closed by Advait-M** 2023-12-16 23:41 UTC
Labels: Bug

**Comment by dannyneira** [comment] 2024-02-27 21:25
Duplicate of https://github.com/warpdotdev/Warp/issues/2304
