### ISSUE TITLE
In emacs, M-backspace sends M-b "ackspace"

### ISSUE THREAD

**Issue by jinschoi** [warpdotdev/Warp#1860] opened 2022-09-21 18:53 UTC
### Describe the bug

Running emacs -nw (version 28.2) and hitting META-backspace (using option key with "option as meta" turned on), the cursor goes back one word and then "ackspace" is inserted into the buffer.

Typing "C-h k M-backspace" (describe-key) shows that what is being sent is M-b (backward-word) and then the string "ackspace". Similar for M-enter, it sends M-e nter (forward-sentence then "nter").

### To Reproduce

1. In Settings/Features, turn on both Left Option key is Meta and Right Option Key is Meta.
2. Run emacs -nw
3. Switch to the scratch buffer.
4. Type META-backspace. The cursor will jump back one word and "ackspace" will be inserted.

### Expected behaviour

The previous word should be deleted (i.e., META-backspace should be sent).

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.09.13.08.15.stable_03

### Does this block you from using Warp daily?

Yes

**Comment by szgupta** [comment] 2022-09-21 19:16
Hey @jinschoi, thanks for reporting. I was able to repro this. We'll look into this!

**Comment by rlanday** [comment] 2022-12-14 17:30
Hi, do you have any updates on this? This is pretty annoying for me and I imagine several dozen other emacs users as well.

**Comment by samv** [comment] 2023-04-15 04:16
This isn't limited to emacs.  Whenever Warp is in [alternate screen](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer), it sends this amusing and bizarro sequence.

This script enters alternate screen, and then I used a couple of arrow keys, hit backspace (which shows as ^?) and you can see it then send ESC "backspace" (ESC+b is Meta-b, and ESC shows as "^[")

[check-term-keybind.tgz](https://github.com/warpdotdev/Warp/files/11238224/check-term-keybind.tgz)

Emacs keybindings entered widespread use through their default availability in GNU bash, and many sequences have found their way into other applications, sometimes in a misconceived way.

The one I miss most is `^_`, 0x1F or Ctrl+Shift+Minus on US keyboards, which is Undo in Emacs.  That sequence doesn't send anything.  You know, you can look at the lower parts of the ASCII table:

```
@ABCDEFGHIJKLMNO
PQRSTUVWXYZ[\]^_ 
```
The escape code when you hit Control + the Letter is the same code but minus 0x40.  The ones that aren't letters might involve Shift as well, but they all work.  Emacs uses ^@ for "Set Mark" (starting a selection region at the current point, like you'd do with a mouse) and ^_ for Undo.

If you use `bind -P | less` in `bash`, you can see even more keystroke bindings you might not know about.  I've blown people's minds before using things like Undo, Cut and Paste (including cycling through the "kill ring" with M-y) or Reverse Searching with ^R: these all come from Emacs. 

Anyway, hope this helps and I'm happy to give feedback/testing if you want to sent me a branch build or something.

**Comment by tylerFowler** [comment] 2023-07-25 00:12
Also seeing this in tmux (unsurprisingly given the above), can we please get an update on this?

**Comment by ejoubaud** [comment] 2023-08-19 16:38
+1, in tmux

**Comment by zachbai** [comment] 2023-09-07 17:01
Hey all, we merged a fix for this a couple releases ago -- is the issue resolved on your end?

**Comment by JackYansongLi** [comment] 2023-09-23 05:15
> The one I miss most is `^_`, 0x1F or Ctrl+Shift+Minus on US keyboards, which is Undo in Emacs (and by extension Bash). That sequence doesn't send anything in Warp. This seems like an oversight/omission, too; and you know, you can look at the lower parts of the ASCII table:

I got a similar issue, when I use option+e in emacs, it prints out ´ instead of jumping to the end of the paragraph, I turned on "left option and right option as meta key" in warp

**Comment by zachbai** [comment] 2023-09-25 17:29
@JackYansongLi mind filing a separate issue? Sounds like the cause might be slightly different.

I'm going to close this one since the fix seems to have worked (at least, to stop sending that bizarre M-b 'ackspace' sequence

**Closed by zachbai** 2023-09-25 17:29 UTC
Labels: Bug
