### ISSUE TITLE
Two things holding me back

### ISSUE THREAD

**Issue by sktzofrenic** [warpdotdev/Warp#4754] opened 2024-04-14 10:10 UTC
### Describe the solution you'd like?

Need a full screen mode for terminal apps like vim. Also need to support nerd fonts for icons. 
![warp](https://github.com/warpdotdev/Warp/assets/11902047/616b3142-a324-4951-9423-b23711560745)

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-15 21:50
Thanks for submitting this @sktzofrenic 

We already have a related request tracking this over to remove padding #2373 for alt-screen apps like neovim.

Regarding the Font, just make sure you have nerd font installed, restart Warp, then select in the Settings > Appearance menu.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-04-15 21:50
Duplicate of #2373

**Closed by dannyneira** 2024-04-15 21:50 UTC
Labels: enhancement

**Comment by HaxagonusD** [comment] 2024-05-04 22:29
> Thanks for submitting this @sktzofrenic
> 
> We already have a related request tracking this over to remove padding #2373 for alt-screen apps like neovim.
> 
> Regarding the Font, just make sure you have nerd font installed, restart Warp, then select in the Settings > Appearance menu.
> 
> If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!
> 
> We'll be closing this as a duplicate.

The Nerd Fonts don't show up. We want to be able to to use Nerd Fonts for the Icons
