### ISSUE TITLE
Adding Photos to Warp Drive notebooks

### ISSUE THREAD

**Issue by Firstoften** [warpdotdev/Warp#4881] opened 2024-05-06 22:03 UTC
### Dupe Check

- [x] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I really don't know if this would legit be a feature request cuz I don't know maybe there is such feature, but googling haven't got me anything, so yeah. I'm a pentester and I really love writing up my CTF solutions somewhere. Recently I found out about notebooks in Warp Drive, which are really cool way of sharing writeups with my team in Warp Drive. But unfortunately I also found out you can't put screenshots or any kind of files and photos there. So If there would be such feature, it would really be nice :)

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-07 17:41
Thanks for submitting this @Firstoften 

We already have a request tracking this over at #26 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-07 17:41
Duplicate of #26

**Closed by dannyneira** 2024-05-07 17:41 UTC
Labels: Feature requests
