### ISSUE TITLE
Warp doesn't detect process termination when exiting `info` by typing `q`

### ISSUE THREAD

**Issue by yossizahn** [warpdotdev/Warp#2589] opened 2023-01-31 19:59 UTC
### Describe the bug

Warp doesn't detect process termination when exiting `info` by typing `q`

### To Reproduce
- Install `brew install texinfo`
- Run the `info` command.
- Quit by pressing `q`
- Warp doesn't seem to detect that info has been quit, it doesn't show the shell prompt, and warns before cmd+q quitting that info is still running
- Press UP key to go back in history and the Enter to run `info` again
- Quit again using `q`
- Magically this works.
Every second time Warp detects the process termination, and every other time not.

### Expected behaviour

Warp should detect process termination

### Screenshots

![CleanShot 2023-01-31 at 21 54 58](https://user-images.githubusercontent.com/19174667/215868367-7125a0ea-8e2d-44e8-99a7-3931fe74cbe2.gif)

### Operating System

MacOS

### OS Version

13.2

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.01.24.08.03.stable_01

### Additional context

```
$ which info
/opt/homebrew/bin/info

$ info --version
info (GNU texinfo) 7.0.1

Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-01-31 22:16
Thanks for submitting, I was unable to reproduce this since I don't have `info` installed, which brew formulae did you use
to install /opt/homebrew/bin/info?

![CleanShot 2023-01-31 at 15 14 56](https://user-images.githubusercontent.com/16809145/215896082-563e8485-1558-4a80-bc83-3ffeb713a611.png)

**Comment by yossizahn** [comment] 2023-01-31 23:08
```
brew install texinfo
```

**Comment by dannyneira** [comment] 2023-02-01 17:00
Thanks for this, it repros as you mentioned and i wonder if just with info or affecting other alt-screen apps. We'll investigate and let you know any updates.

**Comment by dannyneira** [comment] 2023-03-02 23:28
Hey Folks, this fix is out on today's release v0.2023.02.28.08.03.stable_01.

Closing as completed but please let us know if the issue persists.

**Closed by dannyneira** 2023-03-02 23:28 UTC
Labels: Bug

**Comment by shumkov** [comment] 2023-05-04 12:40
This issue persist for me using with fish. Brew, Ansible and some other apps are not terminating properly with warp.

**Comment by dannyneira** [comment] 2023-05-04 21:55
Hey @shumkov sorry to hear about this, are you using fish version 3.4 or below by any chance? If so there is a [known issue with it and Warp](https://docs.warp.dev/help/known-issues#fish-shell-read-command) and we recommend upgrading.
