### ISSUE TITLE
Display images

### ISSUE THREAD

**Issue by antares667367** [warpdotdev/Warp#2467] opened 2023-01-10 12:53 UTC
### Discord username (optional)

antares667367

### Describe the solution you'd like?

```text
Display images in terminal like terminology
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment] 2023-01-11 20:11
@antares667367 we have an open github issue for this. I'll mark this as a duplicate once I have some free time! stay tuned!

**Comment by aMediocreDad** [comment] 2023-12-12 18:42
Duplicate of #26. This can be closed.

**Comment by dannyneira** [comment] 2024-06-14 15:55
Duplicate of #26

**Closed by dannyneira** 2024-06-14 15:55 UTC
Labels: enhancement
