### ISSUE TITLE
Any prospect of getting #5198 addressed?

### ISSUE THREAD

**Issue by orome** [warpdotdev/Warp#5561] opened 2024-12-11 20:16 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Any prospect of getting #5198 addressed?

### To reproduce

Launch Warp

### Operating system

MacOS

### Operating system and version

15.2

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-12-11 20:30
Hi @orome it's not clear at this time, but i'll follow up with the team and see if we can get you that special build of Warp that will generate the `warp.pty.recording` file we would need to debug further. As a possible stopgap, I recommend you try using `zsh` as its the default for Mac and functions very much in the same way as bash as far as i know its all backwards compatible. We'll post further updates on #5198.

**Comment by dannyneira** [comment] 2024-12-11 20:31
Duplicate of #5198

**Closed by dannyneira** 2024-12-11 20:31 UTC
Labels: Bugs
