### ISSUE TITLE
Can't backward search command "%paste" in IPython on Mac

### ISSUE THREAD

**Issue by caoyue12151011** [warpdotdev/Warp#4983] opened 2024-06-04 10:09 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

When I type "%" and upper arrow key in IPython on my Mac, I expected that Warp gives me the lastly used command "%paste". However it gives me some other commands starting with % every time. "%paste" seems not in its command history. Works for Linux systems though.

### To reproduce

1. Open IPython in Warp: `ipython`.
2. Type `%paste` and press Return. It should run the code in your clipboard.
3. Type `%` and press the upper arrow key. It should show the command you just typed `%paste` but it doesn't.

### Screenshots

![Screenshot 2024-06-04 at 18 07 54](https://github.com/warpdotdev/Warp/assets/145730845/12f4cf3b-ada7-458d-b65b-7a9226c43f8e)

### Operating system

MacOS

### Operating system and version

14.3.0

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23) | zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.05.07.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-06-04 17:14
Hi @caoyue12151011 There is a lack of support for REPLs like ipython at this time. We are tracking support for ipython here. https://github.com/warpdotdev/Warp/issues/4082

**Comment by dannyneira** [comment] 2024-06-04 17:14
Duplicate of https://github.com/warpdotdev/Warp/issues/4082

**Closed by dannyneira** 2024-06-04 17:14 UTC
Labels: Bugs
