### ISSUE TITLE
direct download link request

### ISSUE THREAD

**Issue by abielamrati** [warpdotdev/Warp#4973] opened 2024-06-01 09:46 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

due to a proxy rule, i can't download warp from https://app.warp.dev/get_warp?package=dmg
the download simply stops 2 seconds after it starts, is there any direct download link to the dmg file ?

### Is your feature request related to a problem? Please describe.

proxy closes the download right after it starts

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-06-03 20:21
Hi @bigeyesbeats thanks for submitting. To solve this your proxy will need grant access to `app.warp.dev` and `*.googleapis.com` to download and log in to Warp. As a workaround, you may install the latest version with homebrew `brew install --cask warp`.

That being said, we're tracking this request for Proxy support here https://github.com/warpdotdev/Warp/issues/705

We'll close this request as duplicate, please track the other one for updates.

**Comment by dannyneira** [comment] 2024-06-03 20:21
Duplicate of https://github.com/warpdotdev/Warp/issues/705

**Closed** 2024-06-03 20:22 UTC
Labels: enhancement
