### ISSUE TITLE
Give users more control over in-app update

### ISSUE THREAD

**Issue by jab** [warpdotdev/Warp#1904] opened 2022-10-01 13:45 UTC
### Describe the solution you'd like?

Warp should provide the ability to check for updates and upgrade from within the app:
* manually, via the standard "Check for updates" menu item, in addition to the nonstandard button in the less expected location of "Settings > Account" (which contains an unexpected "About Warp" section, given there is a top-level "Settings > About" section, which is what Warp opens up to when you choose the menu item "Warp > About Warp", and where there is no similar "check for updates" button nor a "copy version" button??)
* automatically at a periodic interval, via a setting *that can be disabled*

à la iTerm2 et al.

Currently, users cannot check manually via menu item, nor disable the built-in automatic checking.

### How important is this feature to you?

3

**Comment by dannyneira** [comment] 2022-10-03 16:53
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by warpdotdev-dx** [comment] 2022-10-04 16:50
You can manually check for an update through the Settings > Account page.

**Comment by elviskahoro** [comment] 2022-10-04 16:53
<img width="515" alt="CleanShot 2022-10-04 at 12 49 55@2x" src="https://user-images.githubusercontent.com/29553206/193879937-97936edf-4999-4082-9380-878dbea2a253.png">

**Comment by jab** [comment] 2022-10-04 17:10
I know. This ticket is requesting that there also be a menu item for manually checking for updates, to better match macOS conventions.

It’s also raising issues with the current information hierarchy in the settings UI, where there is confusing duplication between the Account and About sections (see updated ticket description). Thanks for your consideration

**Comment by dannyneira** [comment] 2024-06-28 16:28
Hi Folks, we will be tracking this request over at https://github.com/warpdotdev/Warp/issues/1991

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-28 16:28
Duplicate of https://github.com/warpdotdev/Warp/issues/1991

**Closed by dannyneira** 2024-06-28 16:28 UTC
Labels: Feature requests
