### ISSUE TITLE
Option to remove padding/margin from alt screen apps like vim/nvim

### ISSUE THREAD

**Issue by untimated** [warpdotdev/Warp#2373] opened 2022-12-16 03:32 UTC
### Describe the bug

after updates to **2022.12.06 (v0.2022.12.06.08.03)** 
vim/nvim suddenly have padding/margin that makes it smaller in view. It wasn't like this before.

### To Reproduce

1. Update to 2022.12.06 (v0.2022.12.06.08.03)

### Expected behaviour

1. Vim/Nvim span across the parent container

### Screenshots

![image](https://user-images.githubusercontent.com/7563893/208015454-0be6fada-6f2d-496b-b225-5d1685ba5e18.png)
![image](https://user-images.githubusercontent.com/7563893/208015514-a16374ae-1b41-4179-a81b-92194367c573.png)

### Operating System

MacOS

### OS Version

Catalina 10.15.7 

### Shell Version

zsh 5.7.1 (x86_64-apple-darwin19.0)

### Warp Version

v0.2022.12.06.08.03

### Additional context

Not sure if this is a bug, haven't tested it in newer OS. I would be okay with just a response. Thank You!

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by iwfan** [comment] 2022-12-16 07:23
I also encountered the same issue.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/28853200/208044457-7637f3f8-7750-4f0f-9bd5-3dd02a3a40c3.png">

**Mac OS Version**: Ventura 13.1 (22C65)

**Warp Version**: v0.2022.12.13.08.04.stable_01

**Comment by Ganitzsh** [comment] 2022-12-16 09:24
Same here, updated Warp just now.

<img width="918" alt="Screenshot 2022-12-16 at 10 22 41" src="https://user-images.githubusercontent.com/2302338/208066099-0141a9d2-dec6-4bfa-a46b-29a27580f04e.png">

macOS version: 13.0 (22A380)
Warp version: v0.2022.12.13.08.04.stable_01

**Comment by dannyneira** [comment] 2022-12-16 16:25
Thanks for the feedback all, We made some changes to the Alt Screen in order to improve [reliability and compatibility](https://github.com/warpdotdev/Warp/issues/833) with Warp, and we'll continue to monitor and adjust as needed.

**Comment by dannyneira** [comment] 2022-12-21 23:14
Thanks for the feedback all, We made some changes to the Alt Screen apps rendering in order to improve [reliability and compatibility](https://github.com/warpdotdev/Warp/issues/833) with Warp, and we'll continue to monitor and adjust as needed.

As a workaround, many alt-screen apps allow you to set a background to `None` or `Transparent`, and that should help with the border color difference. 
https://user-images.githubusercontent.com/16809145/209020841-1df910f3-0465-4fbc-ad65-4fb0fb880aef.mp4
Demo of this working in `vim`

**Comment by dannyneira** [comment] 2022-12-21 23:15
Thanks for the feedback all, We made some changes to the Alt Screen apps rendering in order to improve [reliability and compatibility](https://github.com/warpdotdev/Warp/issues/833) with Warp, and we'll continue to monitor and adjust as needed.

As a workaround, many alt-screen apps allow you to set a background to `None` or `Transparent`, and that should help with the border color difference. 
https://user-images.githubusercontent.com/16809145/209020841-1df910f3-0465-4fbc-ad65-4fb0fb880aef.mp4
Demo of this working in `vim`

**Comment by dannyneira** [comment] 2022-12-21 23:15
Thanks for the feedback all, We made some changes to the Alt Screen apps rendering in order to improve [reliability and compatibility](https://github.com/warpdotdev/Warp/issues/833) with Warp, and we'll continue to monitor and adjust as needed.

As a workaround, many alt-screen apps allow you to set a background to `None` or `Transparent`, and that should help with the border color difference. 

https://user-images.githubusercontent.com/16809145/209021050-280b9141-5209-407d-9660-f574e7b33b93.mp4

Demo of this working in `vim`

**Comment by andrewstonedev** [comment] 2023-01-21 03:49
this is also an deal-breaker issue for me, keep up the great work warp team, some day you'll be my daily driver

**Comment by siukalov** [comment] 2023-03-15 02:38
Any plans to work on this issue in the near future?

**Comment by incafox** [comment] 2023-03-18 19:43
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/4401153/226134023-3781591c-3fa3-4943-857d-8de1b8a59642.png">

**Comment by kamalkech** [comment] 2023-07-05 18:20
there is no solution to remove padding/margin ???

**Comment by lighter** [comment] 2023-10-14 04:53
![test](https://github.com/warpdotdev/Warp/assets/480133/293f0199-1811-41a8-aea7-825dbe17cf6d)

os: macOS Sonoma 14.0
warp version: v0.2023.10.10.08.06.stable_02
NVIM: v0.9.4

I have related similar questions. The command block will display at the top. How can I fix it? Thanks.

**Comment by oiwn** [comment] 2023-11-06 13:15
yes same issue, a lot of people using tmux or zellij with tabs configured per project basis. this padding is super-annoying

**Comment by jyrodrigues** [comment] 2023-11-06 20:32
+1

**Comment by diegoulloao** [comment] 2023-11-17 04:47
no update on this after almost 1 year? I'm not using warp only because this, and others vim/nvim users too.

**Comment by oiwn** [comment] 2023-11-17 06:08
padding is super annoying. really there should be an option to disable all this fancy too-much-smart things.

And it's not about padding only for nvim/helix etc need to remove it for everything.

**Comment by duong-vo** [comment] 2023-11-22 21:24
+1, just checked out Warp today and this is the only thing that still keeps me using iTerm.

**Comment by lishaowen0426** [comment] 2023-11-25 23:43
the only thing that stops me from using warp. I'm quite astonished that a terminal cannot work well with these editors.

**Comment by StillFantastic** [comment] 2023-12-01 09:32
#3904 just closed as not planned, it seems like we will have to wait for a long time.

**Comment by zachbai** [comment] 2023-12-01 16:19
Sorry for the long silence on this one. Warp's original behavior was to render alt screen apps with the full width/height of the container, as the issue description here alludes to. And as an implementation detail, this mean the shell's window size differed between the main blocks view and the alt screen view; the terminal window size used for the main blocks view includes padding for the sake of the block UI -- so this meant we had to report terminal window size updates to the shell when switching to/from the alt screen. Unfortunately, some alt screen apps weren't properly responding to terminal resize events, causing more serious issues like #934 and #1710. Hence the current behavior, which is caused by using the same terminal window size for both the blocks view and altscreen view.

The feedback around the annoyingly large padding is heard and this issue is still on our radar (#3904 was closed as not planned because it's a dupe of this issue, not because we aren't ever planning to take a look at this). The fix isn't trivial though; we can't revert back to the old approach given the issues I linked above. 

One hacky workaround might be to infer the main bg color of the altscreen app and paint the padding that same color, at least to reduce the visual ugliness. Thoughts on that?

Otherwise, we can re-open an investigation into the original resizing issue, given it's not totally unlikely we land on the today's solution being the best tradeoff.

**Comment by zenonparker** [comment] 2023-12-01 17:03
Reporting terminal size updates to the shell _seems_ like the correct solution. Surprised you noticed many issues with it especially considering how often users already use these apps (tmux, vim) in terminals that adjust size (resizing iTerm2 windows, adjusting font sizes, etc.) fairly often.

**Comment by oiwn** [comment] 2023-12-02 06:41
@zachbai Thank you for explanation!

For me it's not about color difference (minor thing) but about paddings stealing priceless screen width.

**Comment by kamalkech** [comment] 2023-12-02 11:39
@zachbai but you can inspect experience of others terminal like kitty about this topic ! for first step is just space padding margin not color difference

**Comment by zachbai** [comment] 2023-12-05 01:59
The reason why this is uniquely a challenge for Warp is because it warrants different terminal sizes between the blocks view and the alt screen.

As soon as you start any alt screen program, the shell emits a control sequence indicating that the emulator (Warp) should switch to the alt screen. And for Warp, specifically, when Warp realizes we're switching to the alt screen, we'd also have to tell the shell that it should be resized (to the bigger alt screen size, eliminating the padding). For some reason this resize message caused some weird rendering issues with a few CLIs (like #1710). But you're right, that emacs responds to terminal resizing generally, so I'm not sure what the root cause was.

**Comment by venjiang** [comment] 2024-01-15 03:55
Any news?

**Comment by kamalkech** [comment] 2024-01-15 10:32
@venjiang forget that probably in year 3000.

**Comment by RaederDev** [comment] 2024-01-23 18:45
Could you just add a config option to make the padding removable for everything? Either a px value selector or a toggle for on/off. As far as I understood the issue is that the "view" would get resized if you only want no padding inside vim/other apps. Personally I don't care about padding at all and run my other terminal emulators with 0 padding anyway. If removing the padding in blocks via configuration would allow no padding inside vim that would be a good tradeoff imo.

**Comment by finalclass** [comment] 2024-02-22 16:23
This is my workaround:

```bash
#!/bin/bash

FILE=$1

if [[ "$FILE" != /* ]]; then
	FILE=$PWD/$1
fi

echo "Opening $FILE"

i3 exec "terminator -p tokyonight -e \"nvim $FILE\""
```

basically it opens a new window for nvim using terminator instead of warp.

**Comment by rsantos16** [comment] 2024-03-13 03:52
Hello, 

I have been watching Typecraft's YouTube channel and noticed that for him this behavior does not happen. What I noticed is that he installed the catppuccin theme for Warp https://github.com/catppuccin/warp
and also used the same theme for Neovim too. 

It's hacky but at least your don't noticed the padding. This works for me for now. 

It would be nice to have the option to:

1) set margin
2) Disable the AI stuff

Great work guys!

**Comment by a14d** [comment] 2024-03-14 15:07
+1

**Comment by hlpd-pham** [comment] 2024-03-15 16:06
+1

**Comment by lyonsun** [comment] 2024-03-16 18:10
+1

**Comment by lyonsun** [comment] 2024-03-16 19:26
> Hello,
> 
> I have been watching Typecraft's YouTube channel and noticed that for him this behavior does not happen. What I noticed is that he installed the catppuccin theme for Warp https://github.com/catppuccin/warp and also used the same theme for Neovim too.
> 
> It's hacky but at least your don't noticed the padding. This works for me for now.
> 
> It would be nice to have the option to:
> 
> 1. set margin
> 2. Disable the AI stuff
> 
> Great work guys!

Thanks for sharing. Looks like the same applies to tokyo night theme if you use the same for Warp: https://github.com/bart-krakowski/warp-tokyo-night.

**Comment by AugustDev** [comment] 2024-03-20 19:04
Warp is no go for neovim users currently. Crazy that this issue been open since 2022.

**Comment by Melvin-Abraham** [comment] 2024-03-23 07:33
> Sorry for the long silence on this one. Warp's original behavior was to render alt screen apps with the full width/height of the container, as the issue description here alludes to. And as an implementation detail, this mean the shell's window size differed between the main blocks view and the alt screen view; the terminal window size used for the main blocks view includes padding for the sake of the block UI -- so this meant we had to report terminal window size updates to the shell when switching to/from the alt screen. Unfortunately, some alt screen apps weren't properly responding to terminal resize events, causing more serious issues like #934 and #1710. Hence the current behavior, which is caused by using the same terminal window size for both the blocks view and altscreen view.
> 
> The feedback around the annoyingly large padding is heard and this issue is still on our radar (#3904 was closed as not planned because it's a dupe of this issue, not because we aren't ever planning to take a look at this). The fix isn't trivial though; we can't revert back to the old approach given the issues I linked above.
> 
> One hacky workaround might be to infer the main bg color of the altscreen app and paint the padding that same color, at least to reduce the visual ugliness. Thoughts on that?
> 
> Otherwise, we can re-open an investigation into the original resizing issue, given it's not totally unlikely we land on the today's solution being the best tradeoff.

There are some programs which don't seem to show issues when resizing. Like in my case, `nvim` is able to resize without much of an issue especially when opening a split pane. Can we maybe allow users to configure padding for selected programs by adding them to a whitelist of some sort? This way atleast some programs could leverage that feature without affecting other alt screen programs which could be beneficial especially if a user runs those programs quite often.

**Comment by oncet** [comment] 2024-04-01 16:35
Been using Warp for some time, and although some times lags in opening new tabs, it requires you to signup/login, I still loved it. But this here is kind of a deal breaker, really wish there would be an option to disable this margin/padding.

**Comment by a1401358759** [comment] 2024-04-05 03:20
Any news? It's 2024！

**Comment by gczgcz2015** [comment] 2024-04-15 07:23
+1

**Comment by jakubdonovan** [comment] 2024-05-04 17:15
> Sorry for the long silence on this one. Warp's original behavior was to render alt screen apps with the full width/height of the container, as the issue description here alludes to. And as an implementation detail, this mean the shell's window size differed between the main blocks view and the alt screen view; the terminal window size used for the main blocks view includes padding for the sake of the block UI -- so this meant we had to report terminal window size updates to the shell when switching to/from the alt screen. Unfortunately, some alt screen apps weren't properly responding to terminal resize events, causing more serious issues like #934 and #1710. Hence the current behavior, which is caused by using the same terminal window size for both the blocks view and altscreen view.
> 
> The feedback around the annoyingly large padding is heard and this issue is still on our radar (#3904 was closed as not planned because it's a dupe of this issue, not because we aren't ever planning to take a look at this). The fix isn't trivial though; we can't revert back to the old approach given the issues I linked above.
> 
> One hacky workaround might be to infer the main bg color of the altscreen app and paint the padding that same color, at least to reduce the visual ugliness. Thoughts on that?
> 
> Otherwise, we can re-open an investigation into the original resizing issue, given it's not totally unlikely we land on the today's solution being the best tradeoff.

Hello, have there been any updates?

**Comment by thearyadev** [comment] 2024-05-15 03:06
i use neovim   .

**Comment by TENX-S** [comment] 2024-05-17 03:15
The warp team seems complete ignore this issue. What's the benefit to do? All we want is a switch to enable/disable padding.

**Comment by Freakqency** [comment] 2024-05-19 14:35
+1

**Comment by bybruno** [comment] 2024-05-20 14:45
+1

**Comment by kryptamine** [comment] 2024-05-25 08:32
+1

**Comment by CoconutTheSlayer** [comment] 2024-06-06 14:17
+1

**Comment by DanielRasho** [comment] 2024-06-13 03:36
+1

**Comment by ElrohirGT** [comment] 2024-06-13 03:41
I honestly loved the warp experience on my M1 Mac, particularly the autocomplete of common issued commands, although I do agree having borders with your nvim configuration sucks, changed to kitty since I don't really use that much of the AI.

**Comment by screw-hand** [comment] 2024-06-17 03:20
I encountered this issue after updating NVIM to v0.10.0.

Although the text highlighting with vim is not exactly the same, I have achieved the desired effect.

```shell
echo 'highlight Normal ctermfg=black guifg=black ctermbg=NONE guibg=NONE' >> ~/.config/nvim/init.vim && nvim ~/.config/nvim/init.vim
```

PS: If you are using a dark theme background, you should change ctermfg=black guifg=black to white to ensure text visibility.

<img width="647" alt="image" src="https://github.com/warpdotdev/Warp/assets/26453811/b16045ca-a7d1-4685-affb-7347eb3138d4">


<img width="647" alt="image" src="https://github.com/warpdotdev/Warp/assets/26453811/9743fc8c-96b7-414e-a6de-36d01d1b6dd8">

**Comment by claydugo** [comment] 2024-06-20 16:07
Oh man its never good to find issues like these...

Its probably a total blocker for myself if I am going to lose this much screen real estate to some decorative border.

![borders](https://github.com/warpdotdev/Warp/assets/14915070/70d42626-acc3-4d65-9c35-451ea0d4042f)

I love the terminal so far but this is very annoying.  Guess I'll subscribe and pray like the other hundreds here

**Comment by darkgraycat** [comment] 2024-06-21 23:23
Not a workaround, but makes it look less annoying.
```lua
-- define your hi groups  that needs to be transparent, our just use my list
local bg_higroups = {
    "Normal", "SignColumn", "SignColumnSB", "CursorLineNr", "LineNr", "LineNrAbove", "LineNrBelow",
    "DiagnosticSignHint", "DiagnosticSignInfo", "DiagnosticSignWarn", "DiagnosticSignError",
    "GitSignsAdd", "GitSignsAddPreview", "GitSignsStagedAdd",
    "GitSignsChange", "GitSignsChangePreview", "GitSignsStagedChange",
    "GitSignsDelete", "GitSignsDeletePreview", "GitSignsStagedDelete",
    "GitSignsStagedTopdelete", "GitSignsStagedChangedelete",
}
-- add new global function
function NoneBg()
    for _, higroup in pairs(bg_higroups) do vim.cmd("hi " .. higroup .. " guibg=none") end
end
-- add new command
vim.cmd[[ command! -nargs=0 MVNoneBg :lua NoneBg() ]]
-- or execute function at the end of config
NoneBg()
```

Dont be upset and have a nice day!

**Comment by chadlangston** [comment] 2024-06-29 10:50
Love the warp terminal, but the padding takes way too much screen real estate and k9s looks. Hope there is an option to disable it sometime soon.

**Comment by a7mdAli** [comment] 2024-07-06 01:44
### Workaround for the background color
> [!Important]
You won't be able to get rid of the padding with this. This will only help you achieve a consistent background color between Warp and your alt-screen (nvim in my case).

Some comments above mentioned that if you use the same theme on both nvim and Warp, you would have a consistent background color, making it look less bad. However, this only works if the same theme exists for both.

Another way to achieve this is to simply take a screenshot of your background in nvim and use that to create a new theme on Warp. This will create a theme with the same background color as the screenshot.

1. Open Warp.
2. Go to: Settings > Appearance > Current theme.
3. Tap on the + button at the top of the list.
4. Select your image.

> [!Note]
The created theme will have the same name as the screenshot filename.

Waiting for the padding fix🤞

**Comment by dexwert85** [comment] 2024-07-06 21:44
me too I have the same issue
<img width="1624" alt="Screenshot 2024-07-07 at 0 44 12" src="https://github.com/warpdotdev/Warp/assets/101828140/b33b0524-c5fb-4070-b284-2c0e9abf0fd5">

**Comment by dexwert85** [comment] 2024-07-06 21:45
I have the same issue:
<img width="1624" alt="Screenshot 2024-07-07 at 0 44 52" src="https://github.com/warpdotdev/Warp/assets/101828140/df758eda-2e31-4dcc-ab7d-75696c605dcd">

**Comment by sohaha** [comment] 2024-07-11 11:51
Is there no one to follow up on this?

**Comment by venjiang** [comment] 2024-07-12 03:26
+1

**Comment by almcr** [comment] 2024-07-12 20:09
+1

**Comment by zulfiqarlaili** [comment] 2024-07-13 10:48
Hey there, i was looking for the padding issue on warp terminal when using neovim. I too have the same issue with the padding its a real deal breaker for me. I really love the terminal hope that the developer will find the solution some how

**Comment by chadlangston** [comment] 2024-07-13 12:05
I spend much of my time in K9s. So, I don't have any usability issues. I am using Warp and loving it, but the padding takes up so much space. Having an option to disable it would help me out, especially when I am working from my laptop:

<img width="344" alt="image" src="https://github.com/user-attachments/assets/3dee10b1-204d-4a32-b860-66b7a81c6f7d">

**Comment by dexwert85** [comment] 2024-07-14 20:37
so what happend

**Comment by dexwert85** [comment] 2024-07-14 20:37
so is there any updates?

**Comment by danyalutsevich** [comment] 2024-07-15 17:35
please guys remove this padding

![gates](https://github.com/user-attachments/assets/7a952fc2-3ac6-4870-87ca-3df28ba5273b)

**Comment by luwenxull** [comment] 2024-07-23 07:22
+1

**Comment by dichowie** [comment] 2024-07-23 14:25
+1

Very annoying.  Especially since this has been a known issue for years now.  I've been using Warp for a few months now and have liked it a lot but haven't been seeing the padding issue until just the past few days.  Very annoying.

**Comment by tyrelh** [comment] 2024-07-23 16:55
+1 Would love an advanced settings option that let me customize the padding width. I really love the clean look possible with terminal emulators like Alacritty.

Related to this, would love the ability to essentially disable all (or most) window chrome including the title bar like you can with Alacritty. Aint nobody pushing that tiny little red dot to close a window.

**Comment by felipe-rodriguez-parra** [comment] 2024-07-25 09:13
+1

**Comment by outwittester** [comment] 2024-08-02 02:24
+1

**Comment by Masstronaut** [comment] 2024-08-02 17:13
@dannyneira is this simply a prioritization issue and something the warp team would be happy to accept a community PR for, or are there deeper considerations here that are blocking this from getting resolved?

**Comment by dannyneira** [comment] 2024-08-02 17:18
@Masstronaut There are deeper considerations with regard to compatibility of Alt-screen apps. Previously without the padding, there were known issues with returning from or rendering alt-screens. Please note this comment from our eng team on the matter. https://github.com/warpdotdev/Warp/issues/2373#issuecomment-1836395125

**Comment by Masstronaut** [comment] 2024-08-02 20:43
@dannyneira thanks for linking the context from @zachbai!

@zachbai you concluded with a question:

> One hacky workaround might be to infer the main bg color of the altscreen app and paint the padding that same color, at least to reduce the visual ugliness. Thoughts on that?
> 
> Otherwise, we can re-open an investigation into the original resizing issue, given it's not totally unlikely we land on the today's solution being the best tradeoff.

This is an okay workaround for the aesthetic issue, and something I'm currently doing. IMO it does a fine job on the visual ugliness.

The larger issue here IMO is the screen real estate cost. Warp's padding appears to be ~5-6 characters worth of horizontal space. That might not sound like a lot, but it makes a setup like browser side-by-side with a warp/nvim window on my 13 inch macbook feel pretty cramped. Absent neovim I wouldn't mind and have been really happy with warp. I can empathize with many of the other commenters who have considered or decided to give up warp over this issue though.

If terminal power users are part of your target audience (which they very well may not be!) I'd encourage you to consider revisiting this decision, or at least provide an option to switch between behaviors for the people who want it. I assume there any many users who aren't bothered by the padding as it exists today; perhaps the alt screen app users would be happy with no padding in warp blocks nor alt screen apps?

**Comment by chadlangston** [comment] 2024-08-02 21:19
If removing the padding from everywhere in warp solves the issue, this would be my vote. In fact, I would prefer this. Not sure I'm understanding the issue fully, but in every other terminal I've used there's no padding at the command line or in the alt screen apps and they all work without issue.

**Comment by ktappdev** [comment] 2024-08-14 20:06
I guess nothing can really ever be perfect in this world

**Comment by zer0wiz** [comment] 2024-08-21 17:19
I understand why patting is bound to exist.
Then please at least create a way to change the padding size.

**Comment by rrojan** [comment] 2024-08-24 10:38
+1. Please change this.

**Comment by rrojan** [comment] 2024-08-31 06:14
> Looks ugly indeed, nvim seems to work best with iterm for me.. I guess this does hurt UX a lot.
Moved back to Kitty and never looked back at Warp since.

**Comment by rasmus-rudling** [comment] 2024-09-05 12:43
+1

**Comment by DavidCarrNz** [comment] 2024-09-12 01:36
+1 Please set us free

**Comment by Josh-Liddell** [comment] 2024-09-14 00:18
+1 would love to use warp with neovim without the padding

**Comment by alpavlovweb** [comment] 2024-09-20 13:44
+1

**Comment by ShawnAbshire** [comment] 2024-09-23 00:42
Wish this feature would be prioritized... +1

**Comment by RoXuS** [comment] 2024-09-24 21:17
+1

**Comment by ibnusyawall** [comment] 2024-10-19 19:01
Is this a issue or feature of Warp? lol, 2 years passed is not always a priority issue that needs to be fixed.
+1

**Comment by mertkaradayi** [comment] 2024-10-19 20:55
At first, I thought I was the only person in the world who could be bothered by this. But after reading the comments, I felt a mix of joy and amusement, haha. I’m also quite surprised that a community could want something so much, yet it’s been ignored for two years. Since it’s a closed-source product, the developers should be more attentive to what their users want. Small details can make a huge difference, which is what I’ve come to understand about this issue. I used to recommend and rely on Warp as my go-to emulator, but now I’m switching to Kitty. Not just because of the 5px margin, but because it feels like nobody cares about the users’ needs.

**Comment by LosFarmosCTL** [comment] 2024-10-19 21:29
> I’ve come to understand about this issue. I used to recommend and rely on Warp as my go-to emulator, but now I’m switching to Kitty.

I’m on Kitty as well for everything expect quake-style terminal but as soon as ghostty (check it out, really amazing, closed open source beta rn though) launches sometime this year I’ll be gone completely, this is just something I can’t work with as a terminal focused dev…

**Comment by oiwn** [comment] 2024-10-20 02:38
Still getting regular updates about this issue on my gmail haha, it's way too long. Is it that difficult to add option to remove padding?

**Comment by littleblack111** [comment] 2024-10-20 03:11
> Still getting regular updates about this issue on my gmail haha, it's way too long. Is it that difficult to add option to remove padding?

Same here. Really hope they just push that feat so I can unsubscribe

**Comment by Keremimo** [comment] 2024-10-25 07:17
I don't understand how this is not an option and how it got ignored for almost 2 years. Installed today, found out, uninstalled as I write this.

**Comment by adrianlamdev** [comment] 2024-11-06 16:54
Subscribing to this as it came up. +1 for getting this fixed since the padding is probably the only reason I won't be fully switching to Warp

**Comment by rpanachi** [comment] 2024-11-12 22:34
Same here:
<img width="717" alt="image" src="https://github.com/user-attachments/assets/04eecd95-9817-40cc-b00d-fc141b512104">

Any good solution or workaround for that?

**Comment by Keremimo** [comment] 2024-11-13 15:42
> One workaround is the use a nvim theme that has transparent background.

The margins are still there, how's that supposed to help

**Comment by rpanachi** [comment] 2024-11-13 20:10
Using a transparent background didn't work for me. I want to "remove" the margins (like margin: 0), not just make them "invisible". Think of something like "unstyle this tab" menu option.

**Comment by ktappdev** [comment] 2024-11-13 22:42
Then there really is nothing, I love warp with all AI turned off and out the way. If I could edit this padding then i think it would be the best terminal period.
With Ghosty about to be released I think stuff like this will get addressed soon.

**Comment by szgupta** [comment] 2024-11-21 23:48
Hey y'all, Suraj here from the Warp engineering team. Apologies for the radio silence on this issue.

I wanted to share that I've been working on a fix for this and it's close to release. But to avoid regressing Warp's compatibility with alt-screen apps, we've first introduced an explicit opt-in for the fix. On `v0.2024.11.19.08.02.stable_01` and greater, you can run
```
# on MacOS
defaults write dev.warp.Warp-Stable AltScreenPaddingOverride true

# on Linux, add a new kvp ("AltScreenPaddingOverride": true) to ~/.config/warp-terminal/user_preferences.json
```

and this will eliminate the alt-screen padding. You will also notice a new setting to control the amount of padding, or to revert back to match the blocklist padding. The latter is provided as a fallback in case you use a particular alt-screen application that does not respond well to resize (we'd love to know which apps these are):
<img width="1155" alt="custom_alt_screen_padding_setting" src="https://github.com/user-attachments/assets/8991fee6-4dfc-47b6-8b17-bcdd145aca9c">

Once we have confidence that this solution works, I'll fully roll it out and no-padding will be the default. In the meantime, please try it out and let me know if you run into any problems! And sorry again about the delay here ❤️

**Comment by siddarthkay** [comment] 2024-11-22 01:38
@szgupta : Looks much better, Thanks for your work!
Now I may consider going back to using warp again.
Cheers!

![Screenshot 2024-11-22 at 7 06 55 AM](https://github.com/user-attachments/assets/7ce13dc2-87de-4bfe-ad1b-4dac9a13da81)

**Comment by rpanachi** [comment] 2024-11-22 16:21
Yeah, much better. Thanks

**Comment by ShawnAbshire** [comment] 2024-11-22 16:35
Radio silence is a word to use heh, but tested this last night on both my mac and linux machine and worked great!  Thanks for resolving this issue!

**Comment by darkgraycat** [comment] 2024-11-23 14:35
Much better! Thank you!
MacOS: 14.7.1 (23H222) (Sonoma)
<img width="466" alt="image" src="https://github.com/user-attachments/assets/d65f7cb9-c79b-43f6-b2a1-b75d0f4b6566">

**Comment by mertkaradayi** [comment] 2024-11-24 11:53
> Hey y'all, Suraj here from the Warp engineering team. Apologies for the radio silence on this issue.
> 
> I wanted to share that I've been working on a fix for this and it's close to release. But to avoid regressing Warp's compatibility with alt-screen apps, we've first introduced an explicit opt-in for the fix. On `v0.2024.11.19.08.02.stable_01` and greater, you can run
> 
> ```
> # on MacOS
> defaults write dev.warp.Warp-Stable AltScreenPaddingOverride true
> 
> # on Linux, add a new kvp ("AltScreenPaddingOverride": true) to ~/.config/warp-terminal/user_preferences.json
> ```
> 
> and this will eliminate the alt-screen padding. You will also notice a new setting to control the amount of padding, or to revert back to match the blocklist padding. The latter is provided as a fallback in case you use a particular alt-screen application that does not respond well to resize (we'd love to know which apps these are): <img alt="custom_alt_screen_padding_setting" width="1155" src="https://private-user-images.githubusercontent.com/39461854/388733076-8991fee6-4dfc-47b6-8b17-bcdd145aca9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0NDk0MzcsIm5iZiI6MTczMjQ0OTEzNywicGF0aCI6Ii8zOTQ2MTg1NC8zODg3MzMwNzYtODk5MWZlZTYtNGRmYy00N2I2LThiMTctYmNkZDE0NWFjYTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDExNTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZDkyNjFiMzg2ZDhlYjAxNmU2Y2YyNDVjMWVhODQ1MGQwNzBjODk2OWNlMDM4ODA0Mjg2ZWQ4NmFiY2M5NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JvxDzqZ4DtAcs7_9B00o-m1RXkmbFwWytcPbyEQS_rA">
> 
> Once we have confidence that this solution works, I'll fully roll it out and no-padding will be the default. In the meantime, please try it out and let me know if you run into any problems! And sorry again about the delay here ❤️

<img width="861" alt="Screenshot 2024-11-24 at 2 52 43 PM" src="https://github.com/user-attachments/assets/3e8cce10-e508-405c-8876-2965e96185fd">
Sweet fix ! 
Back to Warp !

**Comment by SureshPradhana** [comment] 2024-11-24 14:26
Thanks

**Comment by somtooo** [comment] 2024-11-24 16:47
@mertkaradayi 
how did you make your theme match the tab bar

**Comment by mertkaradayi** [comment] 2024-11-26 18:23
> @mertkaradayi @darkgraycat how did you guys make your theme match the tab/top bar

Hey, I think it's just a coincidence because I was using the Light mode.
<img width="803" alt="Screenshot 2024-11-26 at 9 22 21 PM" src="https://github.com/user-attachments/assets/1df7d88a-0785-493f-b50c-ae3891594cf7">
As you can see now it's not fully same with the top bar.
Also, if you wonder.
I am using transparency in my Warp.

**Comment by somtooo** [comment] 2024-12-05 07:31
@szgupta 
Hi im on v0.2024.11.19.08.02.stable_03 but cant see the padding option
added the extra key to the json file yet nothing. How to download v0.2024.11.19.08.02.stable_01?

**Comment by dannyneira** [comment] 2024-12-05 19:10
@somtooo We will be releasing it in soon to everyone. The option should be in Settings > Appearance> Full screen apps. See more in the [docs](https://docs.warp.dev/features/full-screen-apps#padding).

![CleanShot 2024-12-05 at 12 09 36](https://github.com/user-attachments/assets/1d21090d-4600-4cb4-af48-8ea1a86a2422)

**Comment by somtooo** [comment] 2024-12-05 19:57
@dannyneira 
Thanks for replying. but is this just on mac rn. Cause im on the latest on linux and cannot see the option
![Screenshot From 2024-12-05 14-55-52](https://github.com/user-attachments/assets/406c8423-a8bf-41a8-9fce-9adb4be54070)

**Comment by dannyneira** [comment] 2024-12-05 20:23
@somtooo you need to add the `("AltScreenPaddingOverride": true)` option to your `~/.config/warp-terminal/user_preferences.json` file on Linux, and until the release later today, the option will be in Features not Appearance. After the new release, the option will be in Appearance, sorry for any confusion there.

**Comment by szgupta** [comment] 2024-12-05 22:29
Hey folks, on the latest version of Warp (`v0.2024.12.03.08.02.stable_04` and beyond), there will be no padding in the alt-screen by default. You can adjust this by following the steps here: https://docs.warp.dev/features/full-screen-apps#padding

Thank you all for your patience and feedback! I'll leave this ticket open for a couple of days in case folks have any further feedback.

**Comment by szgupta** [comment] 2024-12-10 15:12
Going to close out this issue. Please feel free to open up a new issue if you're running into any problems / have more feedback about the change!

**Closed by szgupta** 2024-12-10 15:12 UTC
Labels: Feature requests

**Comment by sergeyzwezdin** [comment] 2024-12-12 04:34
@szgupta I still have the issue, so opened #5563

**Comment by chadlangston** [comment] 2025-01-18 16:58
Still doesn't work in k9s
