### ISSUE TITLE
Copy shell prompt when copying command

### ISSUE THREAD

**Issue by michael-bennett-ionos** [warpdotdev/Warp#3831] opened 2023-11-02 14:49 UTC
### Describe the solution you'd like?

```Text
Often I copy and share blocks with my team at work (the ease of doing this is one of the many reasons I love Warp!) but when I do, it doesn't copy the shell prompt. As we work with servers, this is often really useful information for my team. Knowing what server I have ran a command on adds helpful context. 

Please make it that copying a command, or copying "both" (i.e. command and output) includes this shell prompt! Or at least make this an option.
```

### Is your feature request related to a problem? Please describe.

```Text
Copying the output of a block doesn't include the shell prompt.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-11-02 20:42
Hey @michael-bennett-ionos The [block sharing](https://docs.warp.dev/features/blocks/block-sharing#how-to-share-blocks) modal includes a checkbox for including the prompt. Check out my shared blocking using this option. https://app.warp.dev/block/ICN111bKJaAlIMKiBkIWKj

![CleanShot 2023-11-02 at 14 38 32](https://github.com/warpdotdev/Warp/assets/16809145/a8db83a6-a08a-441f-9a72-c570debfe2e9)

Hope this helps with your use case. Closing as this feature already exists, but please let me know of any issues.

**Closed by dannyneira** 2023-11-02 20:42 UTC
Labels: Feature

**Comment by michael-bennett-ionos** [comment] 2024-02-13 15:12
Hi @dannyneira thank you for the response and I'm sorry for my several months late one! 

While what you shared is certainly a cool feature and does to an extent answer my question, what I had in mind was more of a basic text that I could paste to a chat app as a code block, or paste to something like Jira.

So for example:

```
user@server ~ ls /home/user
file1 file2 file3
```

With warp I can effectively link to a pretty website, or I can copy the text but without a prompt. However it would be nice to be able to copy the text and have that include the prompt.

**Comment by dannyneira** [comment] 2024-02-13 16:09
Thanks for followup @michael-bennett-ionos.

We have a request tracking the ability to select/copy prompt text here. https://github.com/warpdotdev/Warp/issues/36

You can also right-click on any block and select "Copy" which should copy the prompt/input/output all together.

**Comment by dannyneira** [comment] 2024-02-13 16:09
Duplicate of https://github.com/warpdotdev/Warp/issues/36

**Comment by michael-bennett-ionos** [comment] 2024-02-13 16:26
Okay thank you I will follow that thread.

Unfortunately from my experience selecting "Copy" copies the input and output but not the prompt :(

**Comment by dannyneira** [comment] 2024-02-13 16:29
My mistake, you're correct you can also right-click and "copy prompt" separately. We're also working on being able to select the prompt and that update will be posted on the Github thread #36

![CleanShot 2024-02-13 at 09 27 34](https://github.com/warpdotdev/Warp/assets/16809145/f406507c-270e-4cc1-92cf-35f71e3a52b8)
