### ISSUE TITLE
id like to be able to select and copy paste the current path

### ISSUE THREAD

**Issue by juancresc** [warpdotdev/Warp#5001] opened 2024-06-07 17:52 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I cant select / copy from the current terminal title / path

### Is your feature request related to a problem? Please describe.

no

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by juancresc** [comment] 2024-06-07 17:53
<img width="988" alt="image" src="https://github.com/warpdotdev/Warp/assets/2141907/8e08aaed-9869-4683-9cab-d31b7c0ea757">
this precise spot where the cursor is, so annoying

**Comment by dannyneira** [comment] 2024-06-07 20:49
hi @juancresc thanks for submitting. So with Warps native prompt it can't be select/copied since its a separate UI element than the input or terminal blocks, this is a known limitation, but what you can do as a workaround is right-click and copy the path (or working directory) on the current path or any previous blocks. 

https://github.com/warpdotdev/Warp/assets/16809145/8d335db7-b8f4-431f-a792-418c6a756f49

Please see out docs for more https://docs.warp.dev/appearance/prompt#how-to-access-it

**Comment by dannyneira** [comment] 2024-06-10 15:42
Thanks for submitting this @juancresc 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/36

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-10 15:42
Duplicate of https://github.com/warpdotdev/Warp/issues/36

**Closed by dannyneira** 2024-06-10 15:42 UTC
Labels: Feature requests

**Comment by Dock-Yard** [comment] 2024-08-06 17:56
@dannyneira Its not just the path. If I want to copy the current git branch name, cannot do it either. And theres no way to do it other than do a 'git status' and have the branch name as o/p and copy that

**Comment by dannyneira** [comment] 2024-08-06 18:30
Hi @Dock-Yard right-clickng on an existing block or the input prompt should allow you to copy the working directory, branch, prompt, command, output, etc. 

![CleanShot 2024-08-06 at 12 26 50](https://github.com/user-attachments/assets/614f49e7-7ca9-4d64-88eb-425890ee5e95)

An alternative is to use a custom prompt like starship.rs, or a [supported prompt](https://docs.warp.dev/appearance/prompt#custom-prompt-compatibility-table), and then you can copy on select on existing blocks, although the current input prompt is not selectable, you can still use the right-click method to copy the entire prompt.

https://github.com/user-attachments/assets/a315a67a-6e95-4100-91bc-dd176126e97a

I hope this helps with your issue.
