### ISSUE TITLE
Minimalist window without tabs and top bars

### ISSUE THREAD

**Issue by NehGuk** [warpdotdev/Warp#5016] opened 2024-06-11 17:56 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

There should be an option of making the Warp window minimal, without all the distractions of the top bar (tabs, search, icons etc).

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-06-11 21:03
Thanks for submitting this @NehGuk 

We already have a request tracking this over at #1009 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-11 21:04
Duplicate of #1009

**Closed** 2024-06-11 21:04 UTC
Labels: Feature requests
