### ISSUE TITLE
Startup window does not respect "Open new windows with custom size" settings

### ISSUE THREAD

**Issue by rvanderfeer** [warpdotdev/Warp#4950] opened 2024-05-24 08:00 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The window that is presented when launching the app has a fixed size.
I would expect this window to respect the settings given when 'Open new windows with custom size' is enabled and configured.

### To reproduce

1. Enable 'Open new windows with custom size' in Appearance/Settings
2. Configure Columns & Rows as desired (in my case 147x43, for 'full screen' display on an MBP)
3. Open a new window, verify that it's size is as desired (it is)
4. Close the app
5. Launch the app
6. The first window presented does not conform to these settings

### Expected behavior

I would expect the first window presented upon app launch to respect the settings given in the custom window size appearance settings.

### Operating system

MacOS

### Operating system and version

Sonoma 14.5

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.05.21.16.09.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-05-24 20:39
Thanks for letting us know @rvanderfeer 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/4011 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-24 20:39
Duplicate of https://github.com/warpdotdev/Warp/issues/4011

**Closed by dannyneira** 2024-05-24 20:39 UTC
Labels: Bugs

**Comment by garyjkuehn** [comment] 2024-06-22 20:08
Experiencing the same. Ensured Feature Restored Window size... is off.  v0.2024.06.18.08.02.stable_03.  This doesn't look to be resolved.

**Comment by dannyneira** [comment] 2024-07-01 22:13
Hi @garyjkuehn yes, we havent implemented this yet. We are tracking it at https://github.com/warpdotdev/Warp/issues/4011
