### ISSUE TITLE
Neovim theme looks different in iTerm2 and Warp

### ISSUE THREAD

**Issue by bookercodes** [warpdotdev/Warp#1110] opened 2022-04-18 15:27 UTC
### Describe the bug

```text
My Neovim theme looks different (especially the pink) in Warp compare to Iterm2.
```

### To Reproduce

Steps to reproduce:
1. Install https://github.com/wadackel/vim-dogrun
2. Set `colorscheme dogrun` and `set termguicolors`
3. Open a JavaScript file in iTerm and in Warp
4. Compare

### Expected behaviour

```text
I expect Hyper to look like iTerm (which looks like the screenshots of the theme)
```

### Screenshots

<img width="1364" alt="CleanShot 2022-04-18 at 16 23 29@2x" src="https://user-images.githubusercontent.com/11927968/163831091-9b2768eb-5a50-4f3a-875c-7c599f3d800f.png">

### Operating System

MacOS

### OS Version

12.0.1

### Additional context

```text
Hi team 👋! I wouldn't expect someone to go to the trouble of installing a Vim theme here! Just wondering what the likely suspect is?
```

**Comment by bijancn** [comment] 2022-04-20 14:36
I can confirm that colors are very much off. I suspect 256 color support is not there

**Comment by wkei** [comment] 2022-05-03 02:58
same issue with [ayu](https://github.com/ayu-theme/ayu-vim) theme

Hyper vs Warp

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/25525563/166399708-a65b5209-c831-4cff-9956-10d8d1362fc6.png">

**Comment by hzb-ykpcx** [comment] 2022-06-18 09:27
I have the same issue

**Comment by elviskahoro** [comment] 2022-07-08 19:46
Does it still look off for yall?

**Comment by hzb-ykpcx** [comment] 2022-07-12 03:14
No, I am using v0.2022.07.04.09.08.stable_02 and I still have the same issue

**Comment by Brendonovich** [comment] 2022-07-19 19:28
Yeah, I'm not sure that this is fixed yet. iTerm2 and Alacritty both look normal, Warp looks desaturated. Could it be related to lack of P3 gamut support?
<img width="2560" alt="Screen Shot 2022-07-20 at 3 27 11 am" src="https://user-images.githubusercontent.com/14191578/179832609-e59d20a0-4bc4-4feb-972c-a6310f8281f7.png">

**Comment by jordanbrauer** [comment] 2022-07-26 17:01
> Does it still look off for yall?

Unfortunately, yes @elviskahoro 😞 .. It seems that 256 is supported & consistent, but anything outside of those colours (using hexcodes) is washed/desaturated or simply does not render :(

### Comparisons

Warp (left) and Kitty (right) both running Neovim and [the same colour scheme](https://github.com/jordanbrauer/citylights.nvim).

- note the grey text is not working in Warp (directory names, line numbers, text, file info, etc.)
- the dark green colour is not correct in Warp (branch name along the bottom, `func` keyword..)

<img width="580" alt="Screen Shot 2022-07-26 at 11 54 19 AM" src="https://user-images.githubusercontent.com/18744334/181065320-207edc6b-83a2-4adc-a908-23809c89b9e8.png">
<img width="719" alt="image" src="https://user-images.githubusercontent.com/18744334/181066255-7b4398d0-b349-4c3b-b48d-2cb56549d8e7.png">

**Comment by elviskahoro** [comment] 2022-07-26 18:18
Going to CC @vorporeal and @gagata

**Comment by bfulop** [comment] 2022-10-02 07:59
It looks like Warp has no issues displaying all the colors, see the left side of my screenshot. I'm using a color highlighter plugin inside Neovim, and all the colors are properly showing. 

It somehow then overrides the theme colors with some random ones. Maybe it's trying to apply it's own color highlighting over Neovim (treesitter)?
It looks like (vim) background colors are shown OK (e.g. the blue background under Strings), but when they are set for the foreground, they are being overwritten.

![BalintFulop 02-10 at 09 41@2x](https://user-images.githubusercontent.com/1718128/193443797-a144eb6b-0458-4470-80f0-fde4c1db14cd.png)

Same code in Kitty:

<img width="614" alt="BalintFulop 02-10 at 09 43@2x" src="https://user-images.githubusercontent.com/1718128/193443806-e20d2818-abcc-4b1d-9f76-13b3898665e2.png">


It's a pity because in my own, subjective tests, **Warp is the fastest** among all the terminal emulators, even Neovim some GUIs! 🚀  👏 

To test, I used a [Neovim smooth scrolling plugin](https://github.com/declancm/cinnamon.nvim), on a 4K screen, created  vertical window splits _inside_ Neovim and tested (smooth) scrolling in the middle one. It was only in Warp where the scrolling stayed smooth no matter how many splits I created. Kitty, Alacritty, Fvim were all slower to begin with (one split, Fvim) or started to drop frames when adding new (vertical) splits (e.g. Kitty).

**Comment by vorporeal** [comment] 2022-10-03 15:25
@bfulop Thanks for the detailed comment!  We've identified the source of the problem and have a fix in the works; we're aiming to get it out in next week's release. :)

**Comment by elviskahoro** [comment] 2022-11-10 23:29
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">

**Closed by elviskahoro** 2022-11-10 23:29 UTC

**Comment by bfulop** [comment] 2022-11-11 09:58
Working great for me! Thank you for the fix!
