### ISSUE TITLE
Warp does not accept Cyrillic paths correctly (possibly other national alphabets as well)

### ISSUE THREAD

**Issue by vvzvlad** [warpdotdev/Warp#209] opened 2021-09-22 13:55 UTC
### Describe the bug

```shell
Unlike the native macOS terminal, in warp I can not go to the address "~/Downloads/Тестовое название на русском/Test ", because it contains the directory name in Cyrillic. I recorded a short video: https://disk.yandex.ru/i/hgyDt7MOxcvEuQ
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### Operating System

MacOS

### OS Version

11.6

**Comment by zheng** [comment] 2021-09-22 19:17
Thanks for the video! Definitely agree this should get fixed.

**Comment by aozisik** [comment] 2021-12-24 15:49
Having a similar issue.

Folder name: `über`

I can cd into the directory alright, but while showing the active dir, Warp will omit `ü`. (And probably other non-latin characters like ö, ı, ç, etc.).

<img width="346" alt="Screenshot 2021-12-24 at 17 46 55" src="https://user-images.githubusercontent.com/735011/147363012-cf7c200f-db4f-41e2-b647-f20362b92996.png">

**Comment by elviskahoro** [comment] 2022-01-28 05:16
From @AndreasHeintze via #675

### Describe the bug

```shell
Just downloaded Warp and testing it out, looks promising, but immediately discovered that it seems to fail at handling folders with swedish characters. If I try to cd into a folder called Källs, it shows Klls instead. Has this been reported before? I am in the correct folder after the cd Källs, but it does not write out the correct path, it's missing the swedish chars and I can't cd deeper into subfolders.
```


### To Reproduce

1. mkdir Källs
2. cd Källs

### Expected behaviour

```shell
I expect it to write out the correct path I am in, Källs, not Klls.
```


### Screenshots

![2022-01-25 at 22 21](https://user-images.githubusercontent.com/2219544/151061978-abcc9eb9-7a58-484e-ba7d-ab336c31cd67.jpg)


### Operating System

MacOS

### OS Version

12.1

### Additional context

_No response_

**Comment by AndreasHeintze** [comment] 2022-02-18 18:11
I hope someone can fix this soon, since it prevents me from using Warp. It's not just a visual bug, since I can't cd any deeper down into subfolders.

**Comment by Otogra** [comment] 2022-04-11 08:06
It's really annoying.

**Comment by elviskahoro** [comment] 2022-04-12 06:56
From [teenjuna](https://github.com/teenjuna) via #568

### Describe the bug

So, when I type a command with some Cyrillic input, it works just fine: the command executes properly, the history looks good. Then I relaunch the app and press the up arrow to get the last command, which now looks broken.



### To Reproduce

Steps to reproduce:
1. Type `echo "Привет, мир!"` ("Hello, world!" in Russian)
2. Close the terminal and open it again
3. Press the up arrow and observe broken encoding


### Expected behaviour

The encoding should not be broken.


### Screenshots

<img width="1021" alt="Screenshot 2022-01-07 at 12 31 58" src="https://user-images.githubusercontent.com/53595243/148497315-38e6ff3c-d043-4dc7-a688-705a819d2783.png">
<img width="1023" alt="Screenshot 2022-01-07 at 12 32 24" src="https://user-images.githubusercontent.com/53595243/148497329-0a580e38-ef69-4e74-8bd7-b3b7427de352.png">

After relaunching:

<img width="1021" alt="Screenshot 2022-01-07 at 12 32 50" src="https://user-images.githubusercontent.com/53595243/148497366-d08a22c0-effb-4c29-8224-8bd5bac64ab0.png">



### Operating System

MacOS

### OS Version

12.0.1

### Additional context

The binary was downloaded yesterday, the version is said to (up-to-date). I would paste it here, but unfortunately the text is unselectable.

**Comment by elviskahoro** [comment] 2022-07-05 04:48
This should be fixed now! Please comment on this if you find bugs

**Closed by elviskahoro** 2022-07-05 04:48 UTC

**Comment by Alex063** [comment] 2024-12-23 18:55
I get the same error if Cyrillic characters are present in the names of my directories.
Link to the [video showing the screen](https://drive.google.com/file/d/1cJpkavupodzLrPteoGwXAHcJw90Vca5T/view?usp=sharing)
