### ISSUE TITLE
Framed multiline prompt from powerlevel10k doesn't quite work

### ISSUE THREAD

**Issue by JonathanDCohen** [warpdotdev/Warp#4015] opened 2024-01-03 04:39 UTC
### Describe the bug

<img width="695" alt="Screenshot 2024-01-02 at 11 37 08 PM" src="https://github.com/warpdotdev/Warp/assets/3297872/c2068123-eee9-4c89-800f-6abe57be8934">

My command should be in line with teh second line of the prompt

### To reproduce

Set up a multi-line prompt and use the terminal

### Operating system

MacOS

### Operating system and version

MacOS 13.2.1 (22D68)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.12.19.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-03 22:38
Thanks for submitting this @JonathanDCohen 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2304

It's something we're working on that will enable the right behavior in the multi-line prompt you have setup in p10k. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-03 22:38
Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Closed by dannyneira** 2024-01-03 22:38 UTC
Labels: Bug
