### ISSUE TITLE
`fzf`

### ISSUE THREAD

**Issue by Dogacel** [warpdotdev/Warp#2420] opened 2022-12-29 15:59 UTC
### Discord username (optional)

Dogacel#2714

### Describe the bug

Shell is not rendering properly

### To Reproduce

1. Go to a folder that is a `git` repository.
2. `git checkout "$(git branch --sort=-committerdate | fzf | tr -d '[:space:]')"`.
3. Enter some random text and press enter.

### Screenshots

https://user-images.githubusercontent.com/7023385/209978333-3963067a-231f-400d-be00-673f21c8b243.mov

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2022-12-29 17:39
Thanks for submitting @Dogacel, I think this has to do with the lack of [full support for fzf](https://docs.warp.dev/help/known-issues#list-of-incompatible-tools). 

Marking this as a duplicate of #https://github.com/warpdotdev/Warp/issues/1647 for general FZF support. Please :+1: that issue if you're interested in this feature/support.

**Closed by dannyneira** 2022-12-29 17:39 UTC
Labels: Bug
