### ISSUE TITLE
Ability to draw a current terminal tab as a new window or split left/right

### ISSUE THREAD

**Issue by seankzw** [warpdotdev/Warp#2135] opened 2022-11-16 15:28 UTC
### Discord username (optional)

ElReino#8374

### Describe the solution you'd like?

```text
Love Warp terminal but realise that there isn't a feature or maybe I didn't find a way, to drag or make a current using terminal to a new window, or make it split side-by-side to another tab.
```

### Is your feature request related to a problem? Please describe.

```text
Not really a very big problem, but it'll definitely be useful when it comes to debugging or comparing.
```

### How important is this feature to you?

2

**Comment by elviskahoro** [comment] 2022-11-18 19:42
@seankzw you're correct! We should have an open issue that has keywords like "detach" or something along these lines. Will try to merge this into that one soon.

**Comment by dannyneira** [comment] 2022-11-28 23:50
Closing as duplicate of https://github.com/warpdotdev/Warp/issues/56

**Closed by dannyneira** 2022-11-28 23:50 UTC
