### ISSUE TITLE
ssh tab autocomplete doesn't work when suing `Include config.d/*` in ssh config file.

### ISSUE THREAD

**Issue by Nishan-Vivek** [warpdotdev/Warp#4545] opened 2024-03-13 00:03 UTC
### Describe the bug

Ubuntu 22.04 workstation. Warp v0.2024.03.05.08.02.stable_01
ssh tab auto-completion not sourcing hosts from .ssh/config or .ssh/config.d/* (when  `Include config.d/*` is present in .ssh/config). 

Instead it only presents hashed entries from .ssh/known_hosts which are unusable.

### To reproduce

have a populated .ssh/config/config.d and .ssh/known_hosts

type `ssh` and the start of a configured ssh host. Hit tab to autocomplete. Instead of seeing hosts defined in .ssh/config (or .ssh/config.d/* only hashed entries that look like `|1|+1/wu0urf3Ln6HZ2Qs69B5BawbI=|THlE/Lji4PFMmNtZontPUCcHwF8=` are present in autocomplete menu. 

### Operating system

Linux

### Operating system and version

Ubutu 22.04

### Shell Version

bash 5.1.16

### Current Warp version

v0.2024.03.05.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-13 16:43
Hi @Nishan-Vivek you should be able to use the entries in `/etc/hosts` as well for autocompletion of SSH.

Also we're tracking a duplicate here: https://github.com/warpdotdev/Warp/issues/4072

**Comment by dannyneira** [comment] 2024-03-13 16:43
Duplicate of https://github.com/warpdotdev/Warp/issues/4072

**Closed by dannyneira** 2024-03-13 16:43 UTC
Labels: Bugs
