### ISSUE TITLE
Exclude 127.0.0.1 and 0.0.0.0 from the IPv4 secret regex

### ISSUE THREAD

**Issue by mquinnv** [warpdotdev/Warp#4947] opened 2024-05-23 15:50 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

i feel like it is probably uncontroversial that the non-identifying ipv4 network addresses for localhost (127.0.0.1) and all interfaces (0.0.0.0) shouldn't be treated as secrets. while i might be able to think of a scenario in which i didn't want it revealed that the service i was using was on localhost, i feel like it would be reasonable to require that user to add 127.0.0.1 specifically to his custom regex

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by mquinnv** [comment] 2024-05-23 15:57
autoregex.xyz says this works, and it seems right: `^(?!127\.0\.0\.1$|0\.0\.0\.0$)((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$`

**Comment by dannyneira** [comment] 2024-05-23 19:38
Hey @mquinnv Thanks for inquiring about this.

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/4455

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-05-23 19:46
Duplicate of #4455

**Closed by dannyneira** 2024-05-23 19:46 UTC
Labels: Feature requests
