### ISSUE TITLE
Cursor color cannot be changed within the themes.yaml

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#3965] opened 2023-12-14 00:31 UTC
### Describe the bug

The cursor color cannot be changed within the themes YAML which leads to some themes having a cursor color that matches the character color.

### To reproduce

https://github.com/warpdotdev/themes/blob/main/standard/catppuccin.yaml

### Screenshots

from @vneogi199 via https://github.com/warpdotdev/themes/issues/72

With catppuccin theme here: https://github.com/warpdotdev/themes/blob/main/standard/catppuccin.yaml

![image](https://github.com/warpdotdev/Warp/assets/29553206/c548c3db-a49e-43fa-88f3-a85c60518718)
Cursor is at line 2 column 3

With default dark theme:
![image](https://github.com/warpdotdev/Warp/assets/29553206/d4c31c92-0816-4b45-b7cc-e557c898aa36)

### Operating system

MacOS

### Operating system and version

MAC

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment] 2023-12-14 00:32
@4rc0s noted that:
> I've noticed this on some of my image-generated themes as well. I was looking for a way to change the cursor color in the YAML file but didn't see one.

via: https://github.com/warpdotdev/themes/issues/72#issuecomment-1807482084

**Comment by dannyneira** [comment] 2023-12-14 17:11
Thanks for submitting, we have a related request to allow for explicit cursor colors in Warp. https://github.com/warpdotdev/Warp/issues/3210

To anyone else facing this issue, please add a :+1: to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-03-07 19:59
Duplicate of https://github.com/warpdotdev/Warp/issues/3210

**Comment by dannyneira** [comment] 2024-08-22 21:54
Hey Folks, this feature has launched with the latest release of Warp.
You can now add `cursor: '#<hex color value>'` to your custom theme yaml files to customize your cursor! Please see an example in our [docs](https://docs.warp.dev/appearance/custom-themes#create-your-custom-theme-manually).

Closing as resolved, but please update and let us know what you think or any issues.

**Closed** 2024-08-23 17:08 UTC
Labels: Bugs
