### ISSUE TITLE
cd autocomplete directory on a symbolic link

### ISSUE THREAD

**Issue by guilhermefeitosa66** [warpdotdev/Warp#4536] opened 2024-03-11 20:24 UTC
### Describe the bug

I have created a symbolic link in my home to a folder inside my dropbox folder.
when I try to get in this folder through my link with the cd command, the autocomplete does not works

### To reproduce

cd ~
cd mkdir -p ~/foo/long-bar-name
ln -s ~/foo/long-bar-name long-bar-name
cd long... (press tab to autocomplete or double tab)

### Expected behavior

the autocomplete should complete de path name, or list the link in options list

### Operating system

MacOS

### Operating system and version

v0.2024.03.05.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

i have tested in both systems, linux and macos, the same bug happens

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-13 16:46
Hi this is a known issue, please see the following request to support sym/soft-links on autocompletion https://github.com/warpdotdev/Warp/issues/4498

As a workaround, please enter the first part of the symlink path manually, then Tab completion should work for the remaining sub-folders.

Closing as duplicate.

**Comment by dannyneira** [comment] 2024-03-13 16:46
Duplicate of #4498

**Closed by dannyneira** 2024-03-13 16:46 UTC
Labels: Bugs
