### ISSUE TITLE
Color rendering incorrect in Warp - Tmux, Mutt, Midnight Commander, etc.

### ISSUE THREAD

**Issue by AngerM** [warpdotdev/Warp#362] opened 2021-11-05 19:06 UTC
### Describe the bug

The color rendering of tmux in warp seems to not be properly setting colors. The same settings work fine in iterm2 or alacritty.

example .tmux.conf:
```
set -g status on
set -g status-interval 2
set -g status-fg colour231
set -g status-bg colour234
set -g status-left-length 20
set -g status-left '#[fg=green,bg=colour234,nobold] #(whoami)  '
set -g status-right "#[fg=yellow] %d %b %Y #[fg=green]:: %l:%M %p"
set -g status-right-length 150
set -g window-status-format "#[fg=colour234,bg=colour234]#[fg=colour244,bg=colour234](#I)#[default] #W #[fg=colour234,bg=colour234]"
set -g window-status-current-format "#[fg=colour4,bg=colour234]#[fg=colour0,bg=colour4](#I) #W #[fg=colour4,bg=colour234,nobold]"
```

### To Reproduce

use the above settings in tmux, and start a session. 

### Expected behaviour

Colors should be rendered correctly

### Screenshots

Warp's rendering:
![image](https://user-images.githubusercontent.com/1715525/140564898-fb7c3242-ecd4-4e1f-ba28-82f88701e6f5.png)

Alacritty rendering:
![image](https://user-images.githubusercontent.com/1715525/140564984-db7d8a99-30ee-47dc-b0de-2889e44df683.png)

### Operating System

MacOS

### OS Version

11.6.1

### Additional context

```shell
~ tmux -V
tmux 3.2a
~ zsh --version
zsh 5.8 (x86_64-apple-darwin19.6.0)
```
```

**Comment by elviskahoro** [comment] 2022-07-05 05:48
Hey! I think the underlying issue is that we added support for enforcing contrast but should put it behind a toggle. Idk when the toggle will come out though tbh

**Comment by elviskahoro** [comment] 2022-09-30 17:23
From #453 via @xorik
### Describe the bug

```shell
No colors in midnight commander (mc in brew)
```


### To Reproduce

Steps to reproduce:
1. Open `mc`

### Expected behaviour

```shell
Files and folders has colors
```


### Screenshots

Warp VS iterm2
![Screen Shot 2021-11-22 at 22 01 07](https://user-images.githubusercontent.com/347044/142934816-a861b7f3-34ef-4f9b-94df-a624c55f856c.png)


### Operating System

MacOS

### OS Version

12.0

### Additional context

_No response_

**Comment by elviskahoro** [comment] 2022-09-30 17:30
From #837 via @ttunguz
### Describe the bug

```text
- pick a standard color scheme in mutt
- pick a standard color scheme in warp
- compare mutt colors in Terminal.app and Warp; they will be different in unexpected ways
```


### To Reproduce

- pick a standard color scheme in mutt
- pick a standard color scheme in warp
- compare mutt colors in Terminal.app and Warp; they will be different in unexpected ways


### Expected behaviour

```text
The color scheme in mutt should reflect the .muttrc configuration
```


### Screenshots

<img width="1297" alt="Screen Shot 2022-03-24 at 11 29 58" src="https://user-images.githubusercontent.com/458598/159952249-f8dafac5-494c-487e-bec5-46868af86179.png">
<img width="1303" alt="Screen Shot 2022-03-24 at 11 28 40" src="https://user-images.githubusercontent.com/458598/159952251-41054bcc-3850-4644-aba5-b879530fbded.png">


### Operating System

MacOS

### OS Version

12.2.1

### Additional context

_No response_

**Comment by elviskahoro** [comment] 2022-09-30 17:42
From #1835 via @buesing
### Discord username (optional)

_No response_

### Describe the bug

Compare this (warp):
<img width="988" alt="image" src="https://user-images.githubusercontent.com/1181371/190447698-67131c52-9e4a-401a-bbf5-7a37ef4981e9.png">

To this (iTerm2):
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1181371/190447752-a57dced2-d572-4ac9-a51b-155fdb960be4.png">

Some colors seem to be switched around in the solarized color scheme. What's normally grey is white in warp, and vice versa, other colors are changed too. I don't mind putting a spin on color schemes but solarized specifically has been popular due to it's precision, so I think it should be used as-is.
In my example what is specifically questionable is that the comments are a lighter shade than the actual code, which is confusing in terms of visual hierarchy.

Another example from within zsh:
warp:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/1181371/190451414-41a0936c-04dd-4112-840c-005d6cc78d42.png">

iterm2:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/1181371/190451477-14a48383-c97f-4a4e-9aeb-60d6a3e80093.png">

Terminal.app
<img width="670" alt="image" src="https://user-images.githubusercontent.com/1181371/190451535-af392545-2b16-4ff7-b25f-0503ade8b48e.png">


### To Reproduce

Open warp with solarized dark, observe a different color scheme than in other terminal emulators.

### Expected behaviour

_No response_

### Screenshots

_No response_

### Operating System

MacOS

### OS Version

12.0

### Shell Version

zsh 5.8

### Warp Version

v0.2022.09.07.14.56.stable_00

### Additional context

_No response_

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

_No response_

**Comment by elviskahoro** [comment] 2022-11-10 23:27
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">

**Comment by rive-n** [comment] 2023-01-03 22:03
This is not fixed.

**Comment by dannyneira** [comment] 2023-01-04 22:11
Thanks for the heads up @rive-n, can you please post a copy of your theme .yml file, we don't need the background image.

**Comment by rive-n** [comment] 2023-01-05 08:59
> Thanks for the heads up @rive-n, can you please post a copy of your theme .yml file, we don't need the background image.

Sure thing! 

```
details: "lighter"
############################################################### SEE BELOW
background_image:
  path: .warp/themes/cyberpunk.JPG
  opacity: 30
############################################################### SEE ABOVE

terminal_colors:
  normal:
    black: "#000000"
    cyan: "#d0d1fe"
    blue: "#a5d5fe"
    white: "#ffffff"
    yellow: "#c2c2c2"
    green: "#e67018"
    red: "#ff705d"
    magenta: "#cacaca"
  bright:
    yellow: "#fefdd5"
    red: "#ffc4bd"
    blue: "#c1e3fe"
    green: "#d6fcb9"
    black: "#555555"
    cyan: "#e5e6fe"
    magenta: "#ffb1fe"
    white: "#ffffff"
accent: "#6959ff"
foreground: "#ffffff"
background: "#000000"
```

**Comment by ViktorQvarfordt** [comment] 2023-02-18 12:03
The problem persists for me as well. Text colors are rendered more dimly than what is specified in the theme.yaml file. I am on version `v0.2023.02.14.08.05.stable_01`. I think this issue should be reopened.

**Comment by mdonato-fn** [comment] 2023-06-23 20:58
Ha, I have the same issue, curious. No other terminal app shows dim colors.

**Comment by strokirk** [comment] 2023-11-06 10:32
@elviskahoro @dannyneira This issue is still present in `v0.2023.10.31.08.03.stable_02`.

Yellow: 9f9d02

Green: 4dc752

**Comment by zachbai** [comment] 2023-11-06 23:30
Reopening since the issue isn't fixed

**Comment by liuzhch-Orka** [comment] 2023-11-23 03:50
Same issue.
Version: v0.2023.11.14.08.02.stable_02
Themes: `Dracula` without additional config.
![WarpDimmed](https://github.com/warpdotdev/Warp/assets/112841608/663350ce-3ad3-48e2-956f-01fc404fc1a7)

https://github.com/warpdotdev/Warp/assets/112841608/45f94996-2f18-4120-9157-917bdfce322b

**Comment by levito** [comment] 2024-03-16 22:37
I think the way how the minimum contrast setting of Warp works could be improved. Currently, it will render very dark text on bright colored background when active (which is default), which results in [something like this](https://github.com/warpdotdev/Warp/issues/362#issuecomment-1263828991) (dark text on bright blue).

iTerm2 does a very good job there: You can set the minimum contrast with a slider there. The background color is kept, the foreground color is brightened or darkened, depending on its brightness compared to the background, to meet the desired contrast if needed.

The default theme having a very bright blue is something I also don't like since it causes problems in many applications which blue as a background color, but this is a matter of taste and can be simply changed by the user if needed.

**Comment by dannyneira** [comment] 2024-05-21 20:36
hey folks, we're working on a fix for this.

![CleanShot 2024-05-21 at 14 24 03](https://github.com/warpdotdev/Warp/assets/16809145/37af3638-7ad4-4444-8dd4-f5e64ef7858b)

**Comment by azat-io** [comment] 2024-05-22 19:42
@dannyneira Awesome. I'm looking forward to it! ❤️

**Comment by dannyneira** [comment] 2024-05-30 20:38
Hey Folks, As of the [latest release](https://docs.warp.dev/getting-started/changelog#id-2024.05.30-v0.2024.05.28.08.02),  Warp now renders terminal text ANSI colors as specified by the theme without any dimming. 

Closing as resolved, but please update and let us know if the issue persists.

**Closed by dannyneira** 2024-05-30 20:38 UTC
Labels: Bugs

**Comment by wassson** [comment] 2025-07-28 03:27
@dannyneira Not sure if anyone is watching this anymore, but for what it's worth, I think I still have this issue. I'm on the latest stable (v0.2025.07.23.08.12.stable_02) and I do have "Enforce minimum contrast" set to "Never" if that's still relevant. Here's a screenshot to show the same theme in Warp vs Ghostty. 

<img width="1456" height="192" alt="Image" src="https://github.com/user-attachments/assets/232c4558-5926-4739-9c41-bdbc91ae7148" />

**Comment by dannyneira** [comment] 2025-07-28 14:08
@wassson We've removed the "filter" applied to colors so they not render "True" to the colors intendid, that being said, i've noticed that other terminals render the colors differently, try iTerm2, Mac Terminal, etc and see the differences. I believe this issue is fixed since we no longer "filter" the colors before rendering them. I'm guessing they render differently due to the underlying libraries that different terminals use being different (Warp uses Rust vs Ghostty uses Zig for example)
