### ISSUE TITLE
Navigating through and opening links within a block with keyboard shortcuts

### ISSUE THREAD

**Issue by notrev** [warpdotdev/Warp#4718] opened 2024-04-09 08:26 UTC
### Discord username (optional)

.notrev

### Describe the solution you'd like?

I would like to be able to navigate through the links contained inside a block and be able to open the focused/selected one by using just the keyboard.

### Is your feature request related to a problem? Please describe.

Not a problem, just a nice to have.

### Additional context

Currently, opening links can be done by using the mouse, hovering over the link and pressing `CMD` + left click (on MacOS). It would be great to be able to do that using the keyboard.

A suggestion is having a Block Action that highlights the links inside of it and allows for navigating through them, similar to the `Find Within Block` action, and a keyboard shortcut (maybe `CMD` + `Enter`) to open the highlighted link

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-09 16:29
Hi @notrev thanks for submitting.  We have a related request here : https://github.com/warpdotdev/Warp/issues/3093

**Comment by dannyneira** [comment] 2024-04-09 16:40
Duplicate of https://github.com/warpdotdev/Warp/issues/3093

**Closed by dannyneira** 2024-04-09 16:40 UTC
Labels: Feature requests
