### ISSUE TITLE
fzf-enabled ctrl-r search does not work (even after remapping Command Search)

### ISSUE THREAD

**Issue by scubbo** [warpdotdev/Warp#3645] opened 2023-09-08 03:57 UTC
### Describe the bug

Even after remapping Command Search (usually assigned to `ctrl-r`) to a different shortcut chord, `ctrl-r` does not trigger usual `fzf`-enabled command search from Warp.

(Not known whether this is unique to `fzf`-enabled search, or if "basic" history search would also be affected - I don't want to uninstall `fzf` to test)

### To reproduce

* Fresh install of Warp (`v0.2023.09.06.18.09.stable_00`)
* `fzf` installed (`0.38.0 (brew)`)
* Remap "Command Search" in Warp to a different chord than `ctrl-r` (and double-check that that chord _does_ trigger Command Search!)

### Expected behavior

`ctrl-r` should trigger `fzf`-enabled history search as in other terminals.

### Operating system

MacOS

### Operating system and version

Monterey 12.6.8

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Current Warp version

v0.2023.09.06.18.09.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

From conversation with a Warp employee, apparently this _is_ a regression - but since I just started using Warp today, I can't give details on _when_ it regressed.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment] 2023-09-11 14:34
hey @scubbo thanks for sharing this feedback with us. there should be an open issue for this IIRC
I'll look for it and erge this their

**Comment by dannyneira** [comment] 2023-09-11 23:45
fzf is currently an incompatible tool at the moment. https://docs.warp.dev/help/known-issues#list-of-incompatible-tools

You can disable it just for Warp with the following conditional
```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
    # fzf code
fi
```

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
    # fzf code
end
```

Closing this one as duplicate of #1647

**Closed** 2023-09-11 23:46 UTC
Labels: Bug

**Comment by socay1** [comment] 2024-06-20 08:15
enter `ps` command, show `zsh` with `--no_rcs`
```
  PID TTY           TIME CMD
60895 ttys001    0:00.48 -zsh -g --no_rcs
```

in warp, enter `zsh`(without --no_rcs), that is ok, fzf work correctly.

**Comment by ajatkj** [comment] 2024-07-12 12:18
> enter `ps` command, show `zsh` with `--no_rcs`
> 
> ```
>   PID TTY           TIME CMD
> 60895 ttys001    0:00.48 -zsh -g --no_rcs
> ```
> 
> in warp, enter `zsh`(without --no_rcs), that is ok, fzf work correctly.

This only works if you don't `warpify` the subshell i.e. you don't get any warp subshell's benefits.
