### ISSUE TITLE
Updates mess up "Keep in Dock"

### ISSUE THREAD

**Issue by michael-card-vizit** [warpdotdev/Warp#4175] opened 2024-02-14 14:33 UTC
### Describe the bug

When you install an update for Warp, it creates a new image that appears to be an entirely different app which means that the "old" version has to be removed from the Dock and the new version has to be re-added to the Dock via Options->Keep In Dock. Most Mac apps are not like this, you can update them and the original Dock icon remains usable you don't have to do Reove From Dock/Keep In Dock after every update.

### To reproduce

Install Warp and select t Keep In Dock to keep it available in the Mac OS Dock. Then apply an update. Th updated Warp terminal will appear in the far right on the Dock and will not be accessible under the old Warp icon, which you must remove from the Dock and then select Keep In Dock for the new icon.

### Expected behavior

When you update Warp the updated version launches in the Dock with the original Warp icon.

### Operating system

MacOS

### Operating system and version

14.2.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.06.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-02-14 17:22
Thanks for letting us know @michael-card-vizit 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/2824 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-14 17:23
Duplicate of https://github.com/warpdotdev/Warp/issues/2824

**Closed** 2024-02-29 21:44 UTC
Labels: Bugs
