### ISSUE TITLE
Make workflows work with Elixir/Erlang repl

### ISSUE THREAD

**Issue by lessless** [warpdotdev/Warp#3377] opened 2023-07-17 22:18 UTC
### Discord username (optional)

lessless_

### Describe the solution you'd like?

```Text
I want to be able to use workflows with Elixir and other REPLs.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-07-17 23:56
Thanks for this feature request! We have a related request for non-shell-based REPL support you can track here #64, as Warp would ultimately have to support elixir/erlang first.

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

**Comment by lessless** [comment] 2023-07-18 08:55
Hey,

Thank you for the prompt reply, @dannyneira. For some reason, I can't thumb up the original post - it looks like the number of reactions is capped at 280, although it shouldn't be the case 😅 

Best,
Yevhenii

**Comment by dannyneira** [comment] 2023-07-25 20:35
@lessless Thanks for pointing that out, the issue is locked since we are aware of the interest in non-shell based REPLs. But realistically speaking this is unlikely to be resolved soon given the complexity and amount of REPLs that exist. Currently, Warp does work with them, just doesn't provide the Warp features in those REPLs.
Please continue to track issue #64  for any updates to this.

Closing as a duplicate for REPL support, once those are supported workflows should automatically work within them.

**Closed by dannyneira** 2023-07-25 20:35 UTC
Labels: Feature
