### ISSUE TITLE
support for persistent process over ssh 

### ISSUE THREAD

**Issue by joihn** [warpdotdev/Warp#5104] opened 2024-07-09 13:21 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

If a linux user wants to launch a long running process on a distant machine via SSH, and disconnect while the process is running, linux user will usually use one of these tools:
- tmux
- screen

AFAIK, both of them are incompatible with wap, therefore there no support for persistent process over SSH

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-07-11 00:23
Hi @joihn we're tracking support for tmux here: https://github.com/warpdotdev/Warp/discussions/501

We'll also be working on some further SSH improvements to help with this issue.

**Comment by dannyneira** [comment] 2024-07-11 00:24
Duplicate of https://github.com/warpdotdev/Warp/discussions/501

**Closed by dannyneira** 2024-07-11 00:24 UTC
Labels: Feature requests
