### ISSUE TITLE
New Icon after update

### ISSUE THREAD

**Issue by zydeico** [warpdotdev/Warp#1617] opened 2022-07-14 22:59 UTC
### Describe the bug

When I have Warp in MacOS dock, after every update of warp, the icon doesn't be replaced 

### To Reproduce

Steps to reproduce:
1. Add warp to MacOS dock
2. Update Warp
3. See old warp icon access on pinned icon dock

### Screenshots
![image](https://user-images.githubusercontent.com/6290292/179251886-301d9641-a713-4946-8bcb-14b919d14568.png)

### Operating System

MacOS

### OS Version

12.4 (21F79)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.07.11.09.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment] 2022-07-19 19:53
Thanks for flagging!

**Comment by ciyer64** [comment] 2022-07-22 16:51
@zydeico thanks again for reporting this. We'll be closing this one as a duplicate of [#1535](https://github.com/warpdotdev/Warp/issues/1535) - check there for updates.

**Closed by ciyer64** 2022-07-22 16:51 UTC
