### ISSUE TITLE
Add an option to keep outputs prior to the clear screen command

### ISSUE THREAD

**Issue by hclihn** [warpdotdev/Warp#2607] opened 2023-02-03 22:22 UTC
### Describe the solution you'd like?

```text
Add a preference option to keep outputs prior to the clean screen command.
```

### Is your feature request related to a problem? Please describe.

```text
When I run qemu to load a Linux kernel image, half way through the kernel loading process, the kernel issues a clean screen command and the kernel outputs prior to it are all cleared up by Warp. There is no way to inspect/debug cleaned up kernel outputs.

When I used Iterm2, I did not have the same problem since it kept all prior outputs. 

I wished in Warp that there is an option to keep contents prior to the clear screen command for debug.
```

### Additional context

Environment: MacOS
```
# cab_img_test uses qemu to load a Linux kernel image
./cab_img_test.sh
# All kernel outputs prior to this point are cleared by Warp because the kernel issued a clear screen command
# So there is no way to debug kernel output prior to it. :-( 
[   75.008687] IPMI message handler: version 39.2
[   75.020553] ipmi device interface
[   75.126101] ipmi_si: IPMI System Interface driver
[   75.126848] ipmi_si: Unable to find any System Interface(s)
modprobe: ERROR: could not insert 'ipmi_si': No such device
[   75.724479] linuxrc: Set up serial console ttyS0...
...
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-02-03 22:27
I've noticed this only to be the case when you run clear in the same input along with another command
As a workaround, I recommend you run clear on its own and then run your other commands.

**Comment by hclihn** [comment] 2023-02-03 23:00
Unfortunately, I don't have the control of it. It's the kernel which issued the command during its loading process.

**Comment by felipeparaujo** [comment] 2023-05-30 09:47
Same as @hclihn, I don't have control of the clear commands. Is there another workaround?

**Comment by dannyneira** [comment] 2024-01-05 22:20
Hey Folks, we're tracking this issue over at https://github.com/warpdotdev/Warp/issues/2607 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-05 22:21
Duplicate of https://github.com/warpdotdev/Warp/issues/2382

**Closed by dannyneira** 2024-01-05 22:21 UTC
Labels: Feature

**Comment by hclihn** [comment] 2024-01-05 23:17
Personally, I don't think this is a duplicate of #2382.

In #2382, the user has control over the issuing of the Clear command. Here is the opposite: in QEMU, the kernel issued the clean screen ANSI sequence which the user has no control over. We are asking if Warp can disable the emulation of the ANSI clear screen sequence when the user specifically configure the session to do so. 

If Warp can disable the emulation of the ANSI clear screen sequence based on the user's configuration, then the user can see the content before the ANSI clear screen sequence which is very usful for debugging.
