### ISSUE TITLE
Close Warp on last terminal close

### ISSUE THREAD

**Issue by silly-git** [warpdotdev/Warp#4493] opened 2024-03-06 23:15 UTC
### Describe the solution you'd like?

iTerm2 has a nifty feature that closes iTerm2 completely when the last terminal closes. I miss it badly, it probably sounds odd but it's the main reason I go back to iTerm2. It just leaves my dock clean and I don't have to click on Warp and cmd+q to close it.

### Is your feature request related to a problem? Please describe.

No, not related to a problem

### Additional context

![CleanShot 2024-03-07 at 10 13 48@2x](https://github.com/warpdotdev/Warp/assets/16648168/4208b87c-dcde-4cc2-914c-dbcc93437cb9)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-06 23:24
We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/395

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-06 23:24
Duplicate of https://github.com/warpdotdev/Warp/issues/395

**Closed by dannyneira** 2024-03-06 23:24 UTC
Labels: Feature requests

**Comment by silly-git** [comment] 2024-03-06 23:26
Oops, sorry about that.
