### ISSUE TITLE
Ability to use system tab behavior

### ISSUE THREAD

**Issue by joezhouchenye** [warpdotdev/Warp#4340] opened 2024-02-26 07:52 UTC
### Describe the solution you'd like?

For example, I want to uninstall a flatpak application from the terminal. If using gnome-terminal, I can get a list of them by double-pressing the tab key. However, this seems impossible in warp.

![image](https://github.com/warpdotdev/Warp/assets/59191277/530be7f0-dea8-4a4f-a89c-bf4695968dcc)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by alokedesai** [comment] 2024-03-01 22:31
Marking as a duplicate of https://github.com/warpdotdev/Warp/issues/1811

**Closed by alokedesai** 2024-03-01 22:31 UTC
Labels: Feature requests
