### ISSUE TITLE
Shortcut can not set 

### ISSUE THREAD

**Issue by zeroskylian** [warpdotdev/Warp#4050] opened 2024-01-10 03:19 UTC
### Describe the bug

I want to set open warp drive‘s  shortcut to commad + `, And I have no shortcuts use
But when I press two button,  shortcut have no response 
warp version v0.2024.01.02.08.02.stable_02

<img width="755" alt="iShot_2024-01-10_11 15 42" src="https://github.com/warpdotdev/Warp/assets/7043428/84caddad-b462-4d17-a426-b0cbc8651c65">

<img width="800" alt="iShot_2024-01-10_11 16 22" src="https://github.com/warpdotdev/Warp/assets/7043428/ad38b9af-c5e5-4d6a-9df9-425b0e87f746">

### To reproduce

open setting, select configure keyboard shortcut, search drive

### Operating system

MacOS

### Operating system and version

macos 13.6.3

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-11 21:26
Duplicate of #1851

**Comment by dannyneira** [comment] 2024-01-11 21:26
Duplicate of https://github.com/warpdotdev/Warp/issues/1851

**Closed by dannyneira** 2024-01-11 21:26 UTC
Labels: Bug
