### ISSUE TITLE
pyenv name injected to text input

### ISSUE THREAD

**Issue by ziehlke** [warpdotdev/Warp#2775] opened 2023-03-14 19:36 UTC
### Describe the bug

Hi!
When I enter to a directory with an active pyenv setting I get it's name in the prompt. Then when I then start a new tab (command+T) a new session is created in the same directory. At first everything looks fine but after first call pyenv name is being injected to the text input.
This only happens if I start a new tab (ctrl+n) from a directory with an active pyenv.

### To Reproduce

1. mkdir testdir
2. cd testdir
3. pyenv virtualenv 3.9 test39
4. pyenv local test39
5. ctrl+n to create new tab
6. echo test

### Expected behaviour

do not inject pyenv name to text input (dah, captain obvious ;) )
as a temporarily fix - would that be possible to start each session at $HOME, can't see if it's configurable.

### Screenshots

https://user-images.githubusercontent.com/10786117/225114737-134e535c-4a58-4df9-8251-aba5df9b472d.mp4

### Operating System

MacOS

### OS Version

13.2.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.07.08.02.stable_01

### Additional context

pyenv 2.3.14

part of .zshrc
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-03-14 20:13
Hi @ziehlke We appreciate you submitting this. It seems related to #1142. In essence, the main issue appears to be that any tool that hooks into `PROMPT_COMMAND` has this issue where it inputs text into the prompt.

We'll post any updates on this thread. In the meantime, anyone else having this issue, please :+1:  and comment if you're also seeing this bug as it helps us gauge impact.

**Comment by mikeharding** [comment] 2023-04-16 07:03
I'm getting the exact same behavior.

**Comment by dannyneira** [comment] 2024-01-05 18:57
Hey Folks, We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/2713 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-05 18:57
Duplicate of https://github.com/warpdotdev/Warp/issues/2713

**Closed by dannyneira** 2024-01-05 18:57 UTC
Labels: Bug
