### ISSUE TITLE
test linear issue

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#4143] opened 2024-02-05 23:50 UTC
### Describe the solution you'd like?

teast

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-07 16:25
testing

**Comment by dannyneira** [comment] 2024-02-07 16:26
Duplicate of #2586

**Closed** 2024-02-29 21:40 UTC
Labels: Feature requests
