### ISSUE TITLE
Some Emoji Chars Like ⭐ Are not rendered correctly

### ISSUE THREAD

**Issue by Trendinao** [warpdotdev/Warp#4848] opened 2024-04-29 05:46 UTC
### Describe the bug

On macOS with M1 chip, emojis like ⭐ are rendered as wire frame, not 3D chars like other Terminal e..g. iTerm2.

![image](https://github.com/warpdotdev/Warp/assets/100587254/89f2fcbd-673e-4ae2-b819-1bca9cf03821)

### To reproduce

Try to type `echo "⭐"`

Before the Enter it looks correct, after then, it's in the block, it becomes the wireframe.

### Operating system

MacOS

### Operating system and version

Darwin Kernel Version 23.4.0

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by adolfo-ab** [comment] 2024-04-29 12:46
I've reproduced this in Linux as well (Fedora 39). Emojis in prompt are displayed as wireframes too.

**Comment by dannyneira** [comment] 2024-04-30 22:44
Hi folks, this is a known issue we're tracking here #239.

Since Warp doesn't yet support multi-byte chars like ligatures and emoji, it falls back to text-based "emojis" instead like the little star in your screenshot.

We'll be tracking this known request in the GitHub thread above.

**Comment by dannyneira** [comment] 2024-05-03 17:31
Duplicate of #239

**Closed by dannyneira** 2024-05-03 17:31 UTC
Labels: Bugs
