### ISSUE TITLE
Remember Window Position in macOS

### ISSUE THREAD

**Issue by dlm6693** [warpdotdev/Warp#2465] opened 2023-01-09 16:20 UTC
### Describe the solution you'd like?

```text
Most applications I use 'remember' their window size and position when connected to other displays. More specifically: if I unplugged my monitors from my Macbook Pro and came back and plugged them in again, the applications that are still open would position themselves in the same place they were before and resume the window size they had when previously connected to my external displays. 

However, Warp currently does not do this. It would be really awesome if this feature were added! Apologies if this has already been requested or is already known I couldn't find anything related. Thanks!
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-01-10 00:15
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by young-mmfm** [comment] 2023-01-10 17:48
For additional context: I've been using Warp for ~7 months now, this seems to have become an issue in the past 2 months or so. Currently on version:
<img width="398" alt="Screen Shot 2023-01-10 at 9 48 06 AM" src="https://user-images.githubusercontent.com/17211188/211624935-b2d6939c-7924-4f67-bcd3-ba3793b3a0f5.png">

**Comment by dlm6693** [comment] 2023-01-20 19:49
@dannyneira any updates on this?

**Comment by wzxu** [comment] 2023-02-27 16:52
Just started using Warp today (version v0.2023.02.21.08.03.stable_01) and this is the first thing I noticed.

Out of habit I usually center my window, but Warp keeps opening off-center (slightly to the upper left).
Not a major issue but I suppose it's gonna drive me crazy after a while 😅
Will subscribe to this issue and hope it'll get fixed soon!

**Comment by dannyneira** [comment] 2023-05-10 22:31
Hey folks, this is a duplicate of https://github.com/warpdotdev/Warp/issues/1399

This is something we're working on ( no ETA ).

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Closed by dannyneira** 2023-05-10 22:31 UTC
Labels: enhancement
