### ISSUE TITLE
Using tmux within Warp, option keys do not work - they print hex codes instead

### ISSUE THREAD

**Issue by dmonopoly** [warpdotdev/Warp#4699] opened 2024-04-04 23:40 UTC
### Describe the bug

When I am in tmux in Warp, and I hit option + left arrow on mac, I would prefer to go back one word. Instead, it prints "3D" to the terminal.

In iterm2 there is a place to set this setting... but I don't see how to fix it here.

Or am I using Warp the wrong way and maybe we don't need tmux anymore with Warp, is the idea (?)...

### To reproduce

1. "tmux" to enter tmux in Warp (assuming tmux is installed)
2. type a word
3. press option + left arrow

### Expected behavior

Goes back one word

### Operating system

MacOS

### Operating system and version

MacOS Sonoma 14.1

### Shell Version

zsh --version is 5.9 (x86_64-apple-darwin23.0)

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-05 21:05
Hi @dmonopoly We already have a request tracking this over at #501 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-04-05 21:05
Duplicate of #501

**Closed by dannyneira** 2024-04-05 21:05 UTC
Labels: Bugs

**Comment by dmonopoly** [comment] 2024-04-05 22:38
Thanks, I'll look there. This'll probably block my full adoption of Warp.
