### ISSUE TITLE
Continues warp output after shell Warpify

### ISSUE THREAD

**Issue by wcbrown86** [warpdotdev/Warp#4012] opened 2023-12-29 18:57 UTC
### Discord username (optional)

glorious_kiwi_86119

### Operating System

MacOS

### Operating System and Version

14.0

### Local Shell Version

zsh 5.9

### Remote Shell Version

bash 3.2.57(1)-release

### Warp Version

v0.2023.12.19.08.02.stable_00

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [X] Yes

### Screenshots

<img width="1097" alt="Screenshot 2023-12-29 at 1 44 52 PM" src="https://github.com/warpdotdev/Warp/assets/8992401/4c532cf6-76b8-4fcb-9c99-1141198b4bee">

The printout in the screenshot is constant either after each new command is submitted or randomly while sitting idle.   

### Include shell xtrace output

I use a custom script that will pass sshpass to a new tab. I need to click the Warpify shell button to bootstrap the new shell. But this is not an issue. It's the constant printout seen in the screenshot above. 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore) - linear-label:e7dfaa84-5fdb-4a00-b754-d8912da923fa

None

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by zachbai** [comment] 2023-12-29 19:01
Hey @wcbrown86 -- do you happen to have "Show background blocks" enabled?

![image](https://github.com/warpdotdev/Warp/assets/10970845/9a4ddddb-144f-4c96-a917-a55b932bc2a3)

(This is expected behavior when that setting is enabled, but this should be off by default and generally is made available only for debugging purposes)

**Comment by wcbrown86** [comment] 2023-12-29 22:20
I do, and thanks for that. This is what I get for clicking things all willy nilly. ThanksW. Chad ***@***.*** Dec 29, 2023, at 2:01 PM, Zach Bai ***@***.***> wrote:﻿
Hey @wcbrown86 -- do you happen to have "Show background blocks" enabled?
image.png (view on web)
(This is expected behavior when that setting is enabled, but this should be off by default and generally is made available only for debugging purposes)

**Comment by dannyneira** [comment] 2024-01-17 22:49
Closing as resolved, since the background block setting was enabled.

**Closed** 2024-12-06 20:29 UTC
Labels: Bugs, SSH
