### ISSUE TITLE
Option to disable Warp's Discrete Graphics mode ( work on integrated GPU and save battery )

### ISSUE THREAD

**Issue by Saleciani** [warpdotdev/Warp#2223] opened 2022-11-24 13:51 UTC
### Describe the bug

On the latest version of mac os, once you disconnect a 4k 60hz screen from your computer via USB c, warp will have a process called 'stable' that will prevent macos (16 inch later 2019) from switching to integrated graphics mode, draining the baterry very fast when not plugged in to the wall.

### To Reproduce

Connect a 4k 60hz external monitor (Not sure if you need these resolutoion, or if with any it happens) with warp turned on.
Mac will change from integrated to discret graphics mode
Unplug the screen the external monitor and use your mac normally
A process from warp called stable will preent macbook from switching back to integrated graphics
If you turn off warp, it switches back to integrated graphics.
Turning on warp again, will turn it back onto discreet graphics.

### Expected behaviour

Stable process does not prevent mac power saving routines from switching between graphics modes.

### Screenshots

<img width="759" alt="image" src="https://user-images.githubusercontent.com/47111823/203799907-3121b5d6-829e-4bbe-8696-cb65166d161b.png">

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Additional context

This only happened after update to mac os ventura

### Does this block you from using Warp daily?

Yes

**Comment by JoaoLobo94** [comment] 2022-11-24 14:18
Update:

Upon further testing, you do not need to connect an external display.

The simple action turning on warp will trigger the discrete graphics.
This is a huge battery drain, and i do not think warp must be a discrete graphics card app.

**Comment by dannyneira** [comment] 2022-11-28 22:39
Thanks for bringing this up. Adding as a feature request to disable discrete graphics mode, as currently for performance reasons Warp uses the GPU to render. We will post any updates on this here.

**Comment by dannyneira** [comment] 2022-12-02 18:03
Hi @JoaoLobo94 We are marking this as a duplicate of #76 

Please sub and 👍 that issue to track the status of the request to disable descrete gpu, at least when the laptop is unplugged.

**Closed by dannyneira** 2022-12-02 18:03 UTC
Labels: enhancement
