### ISSUE TITLE
wildcard don't work in my warp

### ISSUE THREAD

**Issue by Force1ess** [warpdotdev/Warp#3678] opened 2023-09-19 02:23 UTC
### Describe the bug

In my warp, press tab after input * don't give anything

### To reproduce

same as above

### Screenshots

<img width="341" alt="image" src="https://github.com/warpdotdev/Warp/assets/72636351/6661ff07-91eb-4feb-9205-bc2b00851fa9">
<img width="287" alt="image" src="https://github.com/warpdotdev/Warp/assets/72636351/b3404bdc-a483-47d8-b01f-39009ae5cc2c">

### Operating system

MacOS

### Operating system and version

Ventura

### Shell Version

zsh - 5.9

### Current Warp version

v0.2023.09.12.16.17.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by Force1ess** [comment] 2023-09-20 02:56
`ls *` is just an example,  all wildcard are ineffective in my warp.
`rm *` and press `tab` also don't give anything change.

**Comment by dannyneira** [comment] 2023-09-21 23:51
@Force1ess We're marking this as a duplicate of #3681 since Warp currently doesn't support wildcard expansion (or [ZSH Parameter Expansion](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion))

If you could please give it a :+1: it would help us gauge interest. We'll post any updates there if any, so stay tuned!

We'll be closing this as a duplicate.

**Closed by dannyneira** 2023-09-21 23:51 UTC
Labels: Bug
