### ISSUE TITLE
mitmproxy doesn't render properly (only shows the first line)

### ISSUE THREAD

**Issue by vorporeal** [warpdotdev/Warp#2252] opened 2022-11-29 15:41 UTC
### Discord username (optional)

matthew.m.turner

### Describe the bug

Reported by matthew.m.turner via Discord:

> has anyone tried to use mitmproxy with warp?  its supposed to go full screen but that doesnt work for me.  it gets stuck on the bottom of the screen and then starts glitching a bit if i try scrolling down.  sometimes it will stay for a second or two but then it ends up again at the bottom of screen.
> 
> i included screenshot of what it looks like on warp and terminal (where it is correct, you can see flows on top and bottom status bar which stay in those locations until closing mitmproxy)
> 
> maybe full window cli apps dont work well with warps concept of command / output blocks?

### To Reproduce

install `mitmproxy` via `brew install mitmproxy` and run it.

### Screenshots

![image](https://user-images.githubusercontent.com/211194/204574107-89d7b306-4464-46df-b292-962fee2f8473.png)
![image](https://user-images.githubusercontent.com/211194/204574143-7c5e949c-49be-40f0-a40d-41c04ca3ad8a.png)

### Operating System

MacOS

### OS Version

13.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by dannyneira** [comment] 2022-11-29 16:49
Thanks @vorporeal! We cool to close this as duplicate of #1671?

**Comment by vorporeal** [comment] 2022-11-29 23:50
Oooh, yes, sgtm!

**Closed** 2022-12-20 16:15 UTC
Labels: Bug
