### ISSUE TITLE
Linux: primary selection not populated

### ISSUE THREAD

**Issue by guy-borderless** [warpdotdev/Warp#4328] opened 2024-02-25 15:21 UTC
### Describe the bug

When selecting text on Linux the primary selection buffer is not populated.  Selected text should be automatically buffered in the primary selection (see [X11](https://en.wikipedia.org/wiki/X_Window_selection#Clipboard), [wayland](https://wayland.app/protocols/primary-selection-unstable-v1)). Certain shortcuts and middle-click paste don't work for text selected in warp .  
for reference this shell command populates the primary buffer: `echo "Hello world" | xclip -i -selection primary`

### To reproduce

select text

### Expected behavior

text can be middle click pasted

### Operating system

Linux

### Operating system and version

Manjaro Gnome

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment] 2024-03-14 15:40
Closing this as a duplicate of https://github.com/warpdotdev/Warp/issues/4329

**Closed by alokedesai** 2024-03-14 15:40 UTC
Labels: Bugs, Platform > Linux

**Comment by dannyneira** [comment] 2024-03-14 22:24
we've released middle-click paste support in today's release [v0.2024.03.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.03.14-v0.2024.03.12.08.02).

**Comment by dannyneira** [comment] 2024-03-14 22:27
Hey Folks, we've released middle-click paste support in today's release [v0.2024.03.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.03.14-v0.2024.03.12.08.02).
