### ISSUE TITLE
Render hyperlink generated by `delta` CLI when using it as the default git diff tool

### ISSUE THREAD

**Issue by hu13** [warpdotdev/Warp#4997] opened 2024-06-07 01:32 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates
- There have been mentioning of hyperlink but not sure if they are the same issues.

### Describe the solution you'd like?

I use https://github.com/dandavison/delta as my default git diff tool.
It has this feature that renders a hyperlink of each code line. When double clicking on this hyperlink it will open the code file on the default text editor.

For example, iterms support this. The dotted underline under each line number represents a hyperlink to the code file.
<img width="1270" alt="Screenshot 2024-06-06 at 9 32 12 PM" src="https://github.com/warpdotdev/Warp/assets/13399936/1ea2330c-887b-4622-87d7-6d2002371e86">

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by SearidangPa** [comment] 2024-06-07 01:41
I would love to have this too.
Warp is almost perfect. It beats iterm2 in every way, except this.

**Comment by dannyneira** [comment] 2024-06-07 21:18
Thanks for this feature request! 

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by weirdan** [comment] 2024-06-08 23:55
Isn't it a dupe of #176?

**Comment by dannyneira** [comment] 2024-06-13 17:43
Thanks for letting us know @weirdan i missed that one. We will close this as a duplicate of #176.

**Comment by dannyneira** [comment] 2024-06-13 17:43
Duplicate of #176

**Closed by dannyneira** 2024-06-13 17:43 UTC
Labels: enhancement
