### ISSUE TITLE
Selection input in Warp Windows

### ISSUE THREAD

**Issue by nanoupi42** [warpdotdev/Warp#4157] opened 2024-02-09 11:10 UTC
### Describe the solution you'd like?

Hi,
I have screen video to show you my feature request
Maybe it's already exist but I can't find it in settings...

Step :
Connect to SSH to server
Increase windows size 
If I return to wrap windows I can't Type on my shell I have to select the line where I want to type (blue selection appear and it's Ok I can Type now)
Sometimes I have the sensation that I have lost the connection on the server but it's not the case :D 

https://youtu.be/OSdEtwBI-4Y

Is it possible to disable the "blue" selection and became active whole Windows ?

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-09 22:08
Hi @nanoupi42 That is a known issue, sometimes when you click on Warp after having focus elsewhere, you have to click again in order to gain the focus. This was recently improved but not completely fixed and we're tracking it here: https://github.com/warpdotdev/Warp/issues/739

I also noticed when you're in the SSH session that Warp blocks arent working. Make sure the SSH wrapper is enabled in your settings, if that doesn't work you can also try adding the `/usr/bin/ssh` to your subshell settings and then use that to try and connect aswell.

Hope this helps! Closing as a duplicate of https://github.com/warpdotdev/Warp/issues/739

**Comment by dannyneira** [comment] 2024-02-09 22:08
Duplicate of https://github.com/warpdotdev/Warp/issues/739

**Closed** 2024-02-29 21:43 UTC
Labels: Feature requests
