### ISSUE TITLE
Ability to disable tabs and have a chromeless window

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#653] opened 2022-01-21 00:26 UTC
### Describe the solution you'd like?

```shell
I'd really like a settings/config for a "chromeless" window i.e. ability to disable tabs and remove the standard chrome (close/minimize/maxmimize/title/etc.) border from windows.
```

**Comment by hkb** [comment] 2022-04-05 21:39
This is the most excited I have been about using my terminal in a decade! 

But not having my terminal in a true full screen is the only eyesore so far - should be an option to disable the tabs bar in settings :D

**Comment by rsalmei** [comment] 2023-11-20 05:06
I don't like tabs in my terminal, I open multiple windows to be able to reposition them at will.
Thus I hate this tab decoration with my computer name and a big PLUS sign:
<img width="1017" alt="image" src="https://github.com/warpdotdev/Warp/assets/6652853/14f90304-7c3c-4ea6-a8df-1091928688a9">

For comparison, this is how I have my iTerm2:
<img width="986" alt="image" src="https://github.com/warpdotdev/Warp/assets/6652853/b136bbe7-f864-463b-9f10-f0cdac64fa3e">

Thanks.

**Comment by dannyneira** [comment] 2024-02-12 17:25
Hi Folks, We will be tracking this request for Tab bar settings/zen mode over at https://github.com/warpdotdev/Warp/issues/1009

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-12 17:25
Duplicate of #1009

**Closed by dannyneira** 2024-02-12 17:25 UTC
Labels: Feature
