### ISSUE TITLE
Support for linux arm64?

### ISSUE THREAD

**Issue by ghost** [warpdotdev/Warp#4756] opened 2024-04-14 19:32 UTC
### Discord username (optional)

oscarvarto

### Describe the solution you'd like?

Have a linux arm64 build of warp

### Is your feature request related to a problem? Please describe.

No

### Additional context

I like kitty and wezterm. kitty's maintainer shows himself as a difficult person in github issues. OTOH wezterm works OK in X11, but no in Wayland.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-15 21:46
Thanks for submitting this @

We already have a request tracking this over at #4213.

The TLDR is that we're actively working on and testing the ARM build of Warp. So far so good, but we'll post updates on the GitHub thread above when we are closer to release.

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-04-15 21:46
Duplicate of #4213

**Closed by dannyneira** 2024-04-15 21:46 UTC
Labels: enhancement
