### ISSUE TITLE
Warp Consumes Excessive Power on MacBook

### ISSUE THREAD

**Issue by AstroArbaaz** [warpdotdev/Warp#4841] opened 2024-04-28 05:11 UTC
### Describe the solution you'd like?

As a user of Warp on my MacBook, I've noticed significant power consumption when the application is running. This high power usage is causing a notable reduction in my laptop's battery life, impacting its usability throughout the day.

Steps to Reproduce:

1. Install and run Warp on a MacBook.
2. Monitor power consumption using system utilities or battery usage indicators.
3. Note the significant drain on the battery compared to other applications like their built-in Terminal application 

Suggestions for Improvement:

- Optimize Warp's resource utilization to reduce power consumption on MacBook devices.
- Provide users with options to adjust power settings or enable a low-power mode within the application.
- Conduct thorough testing and optimization to ensure Warp operates efficiently across various hardware configurations, including MacBook devices.

### Is your feature request related to a problem? Please describe.

Expected Behavior:
Warp should operate with reasonable power efficiency, ensuring minimal impact on the MacBook's battery life during normal usage.

Actual Behavior:
Warp consumes a considerable amount of power, leading to fast battery drain and reduced battery life on MacBook devices.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-29 22:30
Hi @AstroArbaaz sorry to hear about this. Since Warp is GPU accelerated it does consume more power than normal terminals. If you have system with an integrated and dedicated GPU, you should be able to prefer the [low power GPU in the Settings > Features](https://docs.warp.dev/getting-started/changelog#id-2023.10.12-v0.2023.10.10.08.06) and that should help with the issue.

That being said, we already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2319

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-04-29 22:30
Duplicate of https://github.com/warpdotdev/Warp/issues/2319

**Closed by dannyneira** 2024-04-29 22:30 UTC
Labels: Feature requests
