### ISSUE TITLE
Latest Version duplicates prompt lines

### ISSUE THREAD

**Issue by khalidabuhakmeh** [warpdotdev/Warp#4065] opened 2024-01-12 16:41 UTC
### Describe the bug

I am seeing multiple prompt lines

### To reproduce

Upgrade to v0.2024.01.09.08.02.stable_01

### Expected behavior

Show a single line for a prompt

### Screenshots

![CleanShot -2024-01-12 -11-38-10](https://github.com/warpdotdev/Warp/assets/228256/072f290d-6b5e-4758-b401-e812742dd111)

![Terminal -2024-01-12 -11-41-15](https://github.com/warpdotdev/Warp/assets/228256/80313a3f-60bc-4305-86aa-66e055a725c3)

### Operating system

MacOS

### Operating system and version

14.2.1

### Current Warp version

v0.2024.01.09.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-12 17:28
Hey Folks, thanks for letting us know. We'll be tracking this issue on #4057 going forward and are actively working on reverting the change that may have caused the prompt to repeat. We'll post updates on the parent issue above.

**Comment by dannyneira** [comment] 2024-01-12 17:28
Duplicate of #4057

**Closed by dannyneira** 2024-01-12 17:28 UTC
Labels: Bug

**Comment by dannyneira** [comment] 2024-01-12 18:46
hey Folks, Warp version `v0.2024.01.09.08.02.stable_02` has been released which reverts the change that caused this regression. Please update and stay tuned for the fix.

**Comment by khalidabuhakmeh** [comment] 2024-01-12 20:36
@dannyneira It's "better", but something weird is still happening. I'm getting a duplicate line.

![CleanShot -2024-01-12 -15-36-10](https://github.com/warpdotdev/Warp/assets/228256/65575479-659c-4de4-947c-425ae1e663af)

**Comment by dannyneira** [comment] 2024-01-12 20:41
Which prompt are you using? Could you please share the ~/.zshrc file and/or prompt config file so that we can try and reproduce it on our end?
