### ISSUE TITLE
Tab key behavior is broken

### ISSUE THREAD

**Issue by yaneshtyagi** [warpdotdev/Warp#3251] opened 2023-06-24 11:30 UTC
### Describe the bug

Partially typing the folder name and pressing tab key is supposed to open auto-complete dropdown. However, with the latest update (v0.2023.06.20.08.04.stable_03) tab key just inserts few spaces at the cursor point. For example if I have a folder engine-core and engine-hood, earlier I could just type eng and hit tab to open auto-complete. Now it just adds spaces e.g. `cd eng <tab>     `. 

### To reproduce

1. Open warp terminal
2. type `cd ` and then partially type any folder name. Hit `tab` key. Make sure that the file or folder name has more than one similar folders. For example, if you have two folders with name _engine-core_ and _engine-hood_ then type `eng` and hit tab key.
3. Spaces are inserted instead of opening auto-complete dropdown.

### Operating system

MacOS

### Operating system and version

13.4.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by CalebDu** [comment] 2023-06-24 11:53
i have same problem

**Comment by thomasburguiere** [comment] 2023-06-25 12:10
same issue

**Comment by JamieMcMillan** [comment] 2023-06-26 09:24
I have the same issue.

**Comment by yaneshtyagi** [comment] 2023-06-26 17:16
No other command is bind to tab. There is one `⇧` `Tab`. Would it cause the conflict?

_But strangely enough, it began working now._

**Comment by cristianblar** [comment] 2023-06-26 21:10
> @CalebDu @thomasburguiere @JamieMcMillan Did it began working for you? I guess that opening the keyboard shortcuts screen and closing it resolved the issue.

It solves the issue temporarily... If you open a new tab or something, it's broken again.

**Comment by cristianblar** [comment] 2023-06-26 21:12
Same issue, it's really annoying 😕 auto-completion is the most used feature (at least by me).

**Comment by JamieMcMillan** [comment] 2023-06-27 08:06
My keyboard shortcuts are the same as @yaneshtyagi.

**Comment by wraith1385** [comment] 2023-06-27 22:37
I am having the same issue. It's very intermittent

**Comment by AriJing** [comment] 2023-06-28 02:38
The same problem!
macOS :13.4.1 
zsh 5.9 (x86_64-apple-darwin22.0)
Warp:v0.2023.06.20.08.04.stable_03

**Comment by Dx-wmc** [comment] 2023-06-28 14:13
> The same problem! macOS :13.4.1 zsh 5.9 (x86_64-apple-darwin22.0) Warp:v0.2023.06.20.08.04.stable_03
> 
> ![iShot_2023-06-28_11 11 22](https://user-images.githubusercontent.com/128443168/249336234-ff067889-5d42-4b87-bcbd-4e6c81cc9a7e.gif)

The same problem!

**Comment by dannyneira** [comment] 2023-06-29 21:31
Anyone using `bindkey` in the rc files by any chance? I;ve noticed it effects TAB completion behaviour. https://docs.warp.dev/help/known-issues#list-of-incompatible-tools

Also, try enabling "Completions as you type" https://docs.warp.dev/features/completions#how-to-access-it to see if that helps.

**Comment by TheFern2** [comment] 2023-06-30 16:39
For me tab seems to be broken when I ssh into a device but works fine locally.

**Comment by cristianblar** [comment] 2023-06-30 16:41
The issue is solved now with the last update (v0.2023.06.27.19.34.stable_01).

**Comment by yaneshtyagi** [comment] 2023-06-30 17:21
I can confirm that the issue is resolved with the v0.2023.06.27.19.34.stable_01 update.

Shall I close the issue?

**Comment by dannyneira** [comment] 2023-06-30 17:23
Thanks for confirming all! Closing as resolved, but please feel free to let us know if the issue persists.

**Closed by dannyneira** 2023-06-30 17:23 UTC
Labels: Bug

**Comment by TheFern2** [comment] 2023-06-30 22:36
@dannyneira Still a little flaky for me. I'm an embedded engineer and I ssh into devices quite often. Even after the update I noticed losing the ability to tab and then it would work later on. Maybe there's a timeout for ssh connections or something. I'll keep an eye when I come back from vacations.

**Comment by Bit0r** [comment] 2024-02-25 03:47
Same issue!

KUbuntu 22.04
fish, version 3.7.0
warp, v0.2024.02.20.08.01.stable_02
Input method framework: fcitx5
Input method: rime

When I first changed the `tab key behavior`, it took effect, but after I closed warp and reopened it, I could only accept autocomplete suggestions with `Enter` again.

![image](https://github.com/warpdotdev/Warp/assets/43108543/91c428b3-407b-4d17-8905-518332956e57)
![image](https://github.com/warpdotdev/Warp/assets/43108543/c79c765d-1397-4d31-a435-8bd57ea69c8e)


https://github.com/warpdotdev/Warp/assets/43108543/d8ce2848-91cf-4ca1-8705-94ea195f16cf
