### ISSUE TITLE
Fish shell startup is slow

### ISSUE THREAD

**Issue by natdempk** [warpdotdev/Warp#1298] opened 2022-05-06 20:11 UTC
### Describe the bug

```text
Upon opening a new tab in warp with fish shell it displays `Starting fish...` for 5-10s.
```

### To Reproduce

Steps to reproduce:
1. Open a new fish shell tab and observe that `Starting fish...` takes much longer than running fish from any other terminal

### Expected behaviour

```text
Starting fish is lightning fast
```

### Operating System

MacOS

### OS Version

11.6.4

**Comment by natdempk** [comment] 2022-05-06 20:12
Not sure if there's any other info that would be helpful to provide for an issue like this as its particularly vague. Let me know if there's anything that would be helpful and I can provide it.

**Comment by alokedesai** [comment] 2022-05-13 21:52
Hey @natdempk, thanks for flagging this! This is a known issue (it's actually a Fish bug: https://github.com/fish-shell/fish-shell/issues/7296). We're actively working on fixing this on our side while we wait for the underlying issue in Fish to get resolved.

**Comment by madrus** [comment] 2022-06-05 06:10
In my case, not only `fish` does start slowly but also I get the following warning:

```text
set: Tried to change the read-only variable 'fish_private_mode'
```

**Comment by madrus** [comment] 2022-06-05 06:55
> fish_private_mode

Addition: have reinstalled Fish using the official Fish MacOS installer. The warning is gone. So, back to slow start. :smiley:

**Comment by dannyneira** [comment] 2022-08-19 16:16
@madrus Are you still experiencing issues with FISH on the latest versions of Warp?

If so, my guess is that you normally have a [customizations in fish that Warp may be taking a longer time to parse on startup](https://docs.warp.dev/features/prompt#ps1-compatibility-table).

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)

**Comment by warpdotdev-dx** [comment] 2022-08-22 22:43
Hi!



We are working to gather configuration files to further investigate the slow bootstrap times. 



If you're comfortable, please remove any personal information and attach your redacted configuration files.


Common config file locations by shell below:


Bash = `~/.bashrc`
Zsh = `~/.zshrc`
Fish = `~/.config/fish/config.fish`

Danny Neira (he/him/his)
Support Engineer
www.warp.dev

--- original message ---
On June 5, 2022 at 12:56 AM MDT ***@***.*** wrote:



> fish_private_mode


Addition: have reinstalled Fish using the official Fish MacOS installer. The warning is gone. So, back to slow start. 😃

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by warpdotdev-dx** [comment] 2022-08-22 22:59
We are working to gather configuration files to further investigate the slow bootstrap times. 



If you're comfortable, please remove any personal information and share your dot files with us by attaching your redacted configuration files to this issue or by emailing ***@***.*** Be sure to append you Github Issue # in the subject line to help us track your issue.


Common config file locations by shell below:


Bash = `~/.bashrc`
Zsh = `~/.zshrc`
Fish = `~/.config/fish/config.fish`

Danny Neira (he/him/his)
Support Engineer
www.warp.dev

--- original message ---
On June 5, 2022 at 12:56 AM MDT ***@***.*** wrote:



> fish_private_mode


Addition: have reinstalled Fish using the official Fish MacOS installer. The warning is gone. So, back to slow start. 😃

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
You received this message because you are subscribed to the Google Groups "github" group.
To unsubscribe from this group and stop receiving emails from it, send an email to ***@***.***
--- end of original message ---

**Comment by dannyneira** [comment] 2022-08-22 23:01
We are working to gather configuration files to further investigate the slow bootstrap times.

If you're comfortable, please remove any personal information and share your dot files with us by attaching your redacted configuration files to this issue or by emailing [feedback@warp.dev](mailto:feedback@warp.dev?subject=Bootstrap%20Performance%20-%20GH%20%23Your_Issue_Number_Here&body=For%20bootstrap%20performance%20troubleshooting.). Be sure to append you Github Issue # in the subject line to help us track your issue.

Common config file locations by shell below:

Bash = `~/.bashrc`
Zsh = `~/.zshrc`
Fish = `~/.config/fish/config.fish`

**Comment by madrus** [comment] 2022-09-05 20:27
Hi all, I have removed Fish completely as I love my Warp experience more.
So, I am back on Bash and everything works as expected. Not that it was
easy to clean everything properly but it was definitely worth the trouble.
One of the main reasons for me to use Fish was its intellisense with
command names. But Warp does it even better, so I was not even disappointed
to let it go. Thanks for the great job you are doing! I listened to a Warp
podcast not long ago and that helped to make this decision.
Take care,
Andre

**Comment by probablykasper** [comment] 2023-03-16 04:41
@dannyneira It's still slow for me even if I remove everything in `config.fish`. Takes around 800ms to start in Warp, while iTerm is near instant

**Comment by dannyneira** [comment] 2023-03-16 15:36
@probablykasper thanks for letting us know, are you comfortable sending a copy of your original [config.fish](https://github.com/warpdotdev/Warp/issues/1298#issuecomment-1223294874)? 

I've tried to reproduce the issue with an empty config.fish file and both iterm and warp seem to be launching around the same ( within less than a second )

I used `time open -a iterm.app && time open -a warp.app` from the terminal.app to launch them both in my example below.

https://user-images.githubusercontent.com/16809145/225668498-92fec229-3687-490a-a812-a261fe2d9abd.mp4

**Comment by probablykasper** [comment] 2023-03-16 20:23
There's still a pretty significant difference in your recording. From window is shown to fish is started, Warp takes 500ms and iTerm 80ms. That difference is much clearer when you open a new tab instead of launching the apps.

Did a proper measurement for myself: Warp takes 630-720ms, and iTerm 90ms.

**Comment by sersorrel** [comment] 2023-03-22 16:04
For me, opening a new tab in Warp takes ~2 seconds to show the prompt, but doing the same in iTerm2 takes more like half a second. Here's my (slightly redacted) config.fish:

<details><summary>Details</summary>
<p>

```fish
# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

set --prepend fish_function_path /nix/store/jqcxwc3vm0qxmjgvhrlc74x59f6jxpn0-fishplugin-foreign-env-unstable-2020-02-09/share/fish/vendor_functions.d
fenv source /Users/ah37/.nix-profile/etc/profile.d/hm-session-vars.sh > /dev/null
set -e fish_function_path[1]

function fish_greeting
end
if set -q KITTY_INSTALLATION_DIR
  set --global KITTY_SHELL_INTEGRATION enabled
  source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
  set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
end

test -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && fenv source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

function __fish_command_not_found_handler --on-event fish_command_not_found
    /nix/store/ahgiaivaijvq1h2dryiykvrm0d4881n2-command-not-found $argv
end

source /nix/store/yx1jriqxf2qs4qksi0frdnfv1m6ifyls-fzf-0.35.1/share/fzf/key-bindings.fish && fzf_key_bindings

eval (/nix/store/mzk6nmvfkzbky0d4bk68r1cl0d9bhjcs-coreutils-9.1/bin/dircolors -c ~/.dir_colors)


status --is-login; and begin

  # Login shell initialisation
  

end

status --is-interactive; and begin

  # Abbreviations
  

  # Aliases
  

  # Interactive shell intialisation
  janus | source

any-nix-shell fish --info-right | source

set -g _did_init_conda_already 0
function conda; _init_conda; conda $argv; end
function conda-env; _init_conda; conda-env $argv; end
function _init_conda
  if test "$_did_init_conda_already" -eq 0
    functions -e conda conda-env
    eval /Users/ah37/miniconda3/bin/conda "shell.fish" "hook" $argv < /dev/null | source
    set -g _did_init_conda_already 1
  end
end
export JAVA_CMD=(which java)

if test "$TERM" != "dumb"  -a \( -z "$INSIDE_EMACS"  -o "$INSIDE_EMACS" = "vterm" \)
  eval (/Users/ah37/.nix-profile/bin/starship init fish)
end

# add completions generated by Home Manager to $fish_complete_path
begin
  set -l joined (string join " " $fish_complete_path)
  set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
  set -l post_joined (string replace $prev_joined "" $joined)
  set -l prev (string split " " (string trim $prev_joined))
  set -l post (string split " " (string trim $post_joined))
  set fish_complete_path $prev "/Users/ah37/.local/share/fish/home-manager_generated_completions" $post
end

# Most modern terminals automatically rewrap text, don't try and preempt them.
set -g fish_handle_reflow 0
if test "$LC_TERMINAL" = iTerm2; and test -e ~/.iterm2_shell_integration.fish
  source ~/.iterm2_shell_integration.fish
end

/nix/store/9hhvh3c2mbnz5f5fkbgq0a0n0zfv9n89-direnv-2.32.1/bin/direnv hook fish | source


end
```

</p>
</details> 

I also use plugin-foreign-env, so I have the following at `~/.config/fish/conf.d/plugin-foreign-env.fish`:

<details><summary>Details</summary>
<p>

```fish
# Plugin foreign-env
set -l plugin_dir /nix/store/ipx2nhiiy6pyp3v04v4li44d8bi7psyi-oh-my-fish-plugin-foreign-env

# Set paths to import plugin components
if test -d $plugin_dir/functions
  set fish_function_path $fish_function_path[1] $plugin_dir/functions $fish_function_path[2..-1]
end

if test -d $plugin_dir/completions
  set fish_complete_path $fish_complete_path[1] $plugin_dir/completions $fish_complete_path[2..-1]
end

# Source initialization code if it exists.
if test -d $plugin_dir/conf.d
  for f in $plugin_dir/conf.d/*.fish
    source $f
  end
end

if test -f $plugin_dir/key_bindings.fish
  source $plugin_dir/key_bindings.fish
end

if test -f $plugin_dir/init.fish
  source $plugin_dir/init.fish
end
```

</p>
</details>

**Comment by jjairojr** [comment] 2023-04-20 05:09
Too slow here, any solution ?

https://user-images.githubusercontent.com/44951083/233263949-79462854-172e-41d7-a25f-57b07cf42c70.mov

**Comment by dannyneira** [comment] 2023-05-03 17:24
Hey Folks, There is a known issue with older versions of fish ( before 3.4.0 ) and Warp. Once fish is updated (the latest is 3.6.1 ), please comment if you're still seeing the same slow startup issues.

**Comment by probablykasper** [comment] 2023-05-03 17:36
Yes, still seeing it on Fish 3.6.1

**Comment by hazzlim** [comment] 2023-05-03 17:39
Yes same here on fish 3.6.1

**Comment by artmorozz** [comment] 2023-06-07 10:42
Also having sow Warp no matter what shell I use. I've tried `zsh`, `bash` and `fish`. All of them having delay on start for 3-4 sec using `Warp`. Other terminal apps opens instantly with no promt delay.
Using Warp  `v0.2023.05.30.08.03.stable_03` installed from `brew` on macOs v `13.4`.

**Comment by defp** [comment] 2023-06-25 06:35
<img width="794" alt="image" src="https://github.com/warpdotdev/Warp/assets/612381/d8baf85a-2a53-47f2-ab66-21683b1dd0bf">

**Comment by stouset** [comment] 2023-06-28 18:24
Also seeing 2-3s startup times on

```
❯ fish -v
fish, version 3.6.1
```

**Comment by minhnh94** [comment] 2023-08-16 03:57
chiming in, fish here takes forever to be ready (or more like it's been hanging up or stuck every time I open a new terminal window)
Switching to zsh for now

**Comment by thoth-seshat** [comment] 2023-08-17 15:06
I use fish because it's easier to script in fish so am keeping it still but it's soooooo annoying that it's this slow and it's been this way for what feels like a a year (probably just 6 months or something).

**Comment by heylookltsme** [comment] 2023-08-22 23:48
I was on fish 3.5 and just upgraded to 3.6.1 and it's actually even _slower_ now. 😞

**Comment by hungify2022** [comment] 2023-09-21 01:31
any update

**Comment by mantzas** [comment] 2023-11-26 19:28
Any update? I had to use another terminal, unfortunately.

**Comment by rrajath** [comment] 2023-12-07 05:16
I'm facing the same issue and my fish shell startup takes 7+ seconds. I'm using the latest version of Warp (v0.2023.11.28.08.02.stable_00) and fish (3.6.3)

Here's my screencast:

https://github.com/warpdotdev/Warp/assets/235614/a208ad91-4cd3-43fd-8157-8da5c2fca1e4

I even deleted everything in my config.fish and nothing helped. It sucks to be blocked for about 10 seconds every time I open a new tab or a split. Fish opens in a few milliseconds on other terminals though.

**Comment by vorporeal** [comment] 2024-01-08 19:07
Oh nice!  Great find here - invoking sed + tr once to process all of the lines is much more efficient.  We're updating the built-in script to do the same thing; we're aiming to get this perf improvement out in this week's release!

**Comment by vorporeal** [comment] 2024-01-08 20:02
Well then it was a good team effort :joy:

**Comment by dannyneira** [comment] 2024-01-17 21:11
Hey Folks, has anyone seen a noticeable performance improvement when loading `fish` shell since the bootstrap script changes have been released?

**Comment by mahtd** [comment] 2024-01-18 05:54
I just updated and I'm seeing near instant start up for fish now (down from roughly 5 seconds), so a big improvement!

**Comment by heylookltsme** [comment] 2024-01-18 22:42
Same here! Much much faster now. Many thanks!

**Comment by dannyneira** [comment] 2024-02-16 20:12
Hi Folks,
We're closing this as resolved since the issue appears to be fixed now, but please feel free to comment and let us know if the issue persists.

**Closed** 2024-02-16 20:28 UTC
Labels: Bug
