### ISSUE TITLE
Accidentally typing a single quote before pressing enter results in uneditable input

### ISSUE THREAD

**Issue by swpalmer** [warpdotdev/Warp#2461] opened 2023-01-08 22:28 UTC
### Describe the bug

Sometimes my finger slips and I type a ' followed by enter when I intended to press enter. If I do this the input editor moves to a new line and it is impossible to delete the ' or edit the previous line in any way.  I'm forced to complete the command with bad input by closing with another ' and executing that command.  This usually results in something like: "zsh: command not found: ls\n"

### To Reproduce

Type the following (followed by enter):
 ls'

Notice how you can't press delete or use the cursor keys to go back and fix it.  You can't hit Command-A to Select-All and delete it - llike I have to do all the time to git rid of warnings from starship that Warp treats as input!

### Expected behaviour

I expect the delete key to delete the accidental '

### Operating System

MacOS

### OS Version

13.2

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0

### Warp Version

v0.2023.01.03.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-01-10 00:12
Thanks for letting us know, a single quote enters the quote mode, in case you wanted to input multi-line text for example into an `echo'` it's a normal behavior you should see in other terminals as well.

https://user-images.githubusercontent.com/16809145/211433165-757c13ba-f802-4d9b-8837-fbb8920b75cf.mp4

Closing as not planned, since this is working as intended.

**Closed by dannyneira** 2023-01-10 00:12 UTC
Labels: Bug

**Comment by swpalmer** [comment] 2023-01-10 02:02
Thanks, found that ctrl-C is the key to get out of that.  Figured Warp had a fancier editor though and could do better than that UX hell.
