### ISSUE TITLE
Setting for tab bar visibility

### ISSUE THREAD

**Issue by olivernybroe** [warpdotdev/Warp#286] opened 2021-10-20 12:37 UTC
### Describe the solution you'd like?

```shell
It could be cool to have a visibility settings for the tab bar.
The options could be
- Always show
- Always hide
- Show when multiple
```

### Is your feature request related to a problem? Please describe.

```shell
I like the cleanliness of the UI and would love to clean up more stuff.
```

**Comment by ericvrp** [comment] 2022-03-17 10:43
Yes please, my small notebook could use the screen area for other things.

**Comment by mainendra** [comment] 2023-12-21 14:53
This is the last item that I'm waiting for before fully switching to warp 😬

**Comment by dannyneira** [comment] 2023-12-21 18:02
Hey folks, this one sounds a lot like the request for Zen mode ( no tab bar, or hiding tab bar in full-screen ) #1009, would you mind if we dedupe to that issue?

**Comment by mainendra** [comment] 2023-12-21 20:37
I think yes, If we can hide tab bar even when not in full-screen.

**Comment by dannyneira** [comment] 2023-12-21 20:44
I think that one is only for the fullscreen mode hiding the tab bar, so we'll keep this open as a separate request for hiding the tab bar, even in non-fullscreen windows. There is no eta on the release of this feature, but the more 👍  are on the topline issue, the higher the chance of getting priority.

**Comment by dannyneira** [comment] 2024-02-12 17:24
Hi Folks, We will be tracking this request for Tab bar settings/zen mode over at https://github.com/warpdotdev/Warp/issues/1009

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-12 17:24
Duplicate of #1009

**Closed by dannyneira** 2024-02-12 17:24 UTC
Labels: enhancement
