### ISSUE TITLE
Completions don't work in some cases (big problem for me)

### ISSUE THREAD

**Issue by SaladinoGW** [warpdotdev/Warp#4625] opened 2024-03-24 18:10 UTC
### Describe the bug

APPARENTLY in SSH only Completions cannot list files/directories in the current directory if I am in a folder where this folder or any parent path of this folder contains names with spaces. I don't have much time to investigate beyond that, so it could be another reason, but I tested it locally and it works, but in ssh it doesn't.

### To reproduce

Enter a machine via ssh and enter a folder that contains space in the name, e.g. 'My Documents' and that contains files, e.g. 'report.txt' then use 'ls re' and press shortcut to list completions (on mine I configured Tab to open these completions). As a result it will not show the 'report.txt' option but rather unrelated files and directories

### Operating system

Linux

### Operating system and version

6.6.10-1-MANJARO

### Shell Version

bash 5.2.21

### Current Warp version

v0.2024.03.19.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by acarl005** [comment] 2024-03-24 18:14
Duplicate of #4574

**Closed** 2024-05-17 01:44 UTC
Labels: Bugs
