### ISSUE TITLE
Blinking Cursor Placement

### ISSUE THREAD

**Issue by KadlagAkash** [warpdotdev/Warp#4518] opened 2024-03-09 12:26 UTC
### Describe the bug

Currently, the blinking cursor is placed on a new line, leaving extra space. I'd prefer to have it on the same line, similar to my iTerm2 setup.

### To reproduce

I'm considering making the switch from iTerm2 but encountered a customization challenge that I'd like to discuss.

### Screenshots
# iTerm 2
![iTerm2](https://github.com/warpdotdev/Warp/assets/100425384/929ab0f6-17ec-4eff-88db-e563ab513677)

# Wrap 
![Wrap](https://github.com/warpdotdev/Warp/assets/100425384/f0d51cb5-5553-4353-a723-8bb846a56b58)

### Operating system

MacOS

### Operating system and version

Sonoma 14.4

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

**Comment by dannyneira** [comment] 2024-03-14 00:28
Thanks for submitting!

We already have a request tracking this over at #2304 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-14 00:28
Duplicate of #2304

**Comment by alokedesai** [comment] 2024-03-15 16:35
Closing this in favor of the canonical issue @dannyneira linked above.

**Closed by alokedesai** 2024-03-15 16:35 UTC
Labels: Bugs
