### ISSUE TITLE
Error updating Warp using zypper on OpenSUSE Tumbleweed.

### ISSUE THREAD

**Issue by tea-in-the-snow** [warpdotdev/Warp#4303] opened 2024-02-24 03:45 UTC
### Describe the bug

Firstly I ran sudo zypper dup to upgrade the whole system. A problem came up that says it failed to find './stable/v0.2024.02.20.08.01.stable_02/warp-terminal-v0.2024.02.20.08.01.stable_02-1.x86_64.rpm' on 'https://releases.warp.dev/linux/rpm/stable'. Then I tried to use the recommended command by Warp to update, which is "sudo zypper update warp-terminal && warp_finish_update JLXHDuy", and faced the same problem.
My operating system is openSUSE Tumbleweed. And current Warp version is v0.2024.02.20.08.01.stable_01.

### To reproduce

1. Boot the openSUSE Tumbleweed system.
2. Download and install Warp v0.2024.02.20.08.01.stable_01 through an rpm package.
3. Tries to update Warp.

### Screenshots

<img width="961" alt="Screenshot_20240224_114311" src="https://github.com/warpdotdev/Warp/assets/154851942/9252b423-d9b1-4176-85be-6c761fe36ef1">

### Operating system

Linux

### Operating system and version

OnenSUSE Tumbleweed (snapshot 20240222)

### Shell Version

zsh 5.9 (x86_64-suse-linux-gnu)

### Current Warp version

v0.2024.02.20.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by Houbsi** [comment] 2024-02-24 06:05
i can reproduce this issue.

**Comment by macccorehenni** [comment] 2024-02-24 06:32
Ran into the same issue, current version of Tumbleweed is 20240222.

**Comment by macccorehenni** [comment] 2024-02-24 06:33
> Ran into the same issue, current version of Tumbleweed is 20240222. 

Also, I specifically used rpm, not sure about the OP.

**Comment by vorporeal** [comment] 2024-02-28 22:27
Hey, sorry about this!  Turns out `zypper` and `dnf`/`yum` handle relative paths differently in the repository metadata that points to the location of the package file.

This should be fixed; let me know if you're still running into issues!

**Closed** 2024-02-29 21:53 UTC
Labels: Bugs
