### ISSUE TITLE
Warp fails to return when using k9s

### ISSUE THREAD

**Issue by wpbeckwith** [warpdotdev/Warp#833] opened 2022-03-23 18:59 UTC
### Describe the bug

Using the current warp version v0.2022.03.14.08.49.stable_00 and the lates k9s version v0.25.18, if I select a pod, deployment, etc resource and the press the 'e' key to edit, it will open the yaml for the resource.  I don't have to make any edits, but typing ':q!' will cause a blank console to show with the cursor in the top left corner and then nothing.  No key combo gets back to the k9s UI.  I just have to close the tab and open a new one.  This does not happen with iTerm2 3.4.12 using the same version of k9s.  Also this use to work with warp, it's been a while since I needed to edit something live, so I don't know when this broke.

### To Reproduce

Steps to reproduce:
1. brew install k9s
2. Use k9s to connect to a kubernetes cluster
3. Select a resource and select 'e' for edit
4. Try and quit editing by using :q!
5. k9s UI is not returned

### Expected behaviour

```text
k9s UI should be available.
```

### Screenshots

![image](https://user-images.githubusercontent.com/8076086/159775214-e1ea7a0a-7cf8-4415-be20-74a653376ea3.png)
Before editing

![image](https://user-images.githubusercontent.com/8076086/159775447-7f38abb9-f18d-48dc-a737-0402df23729c.png)
After exiting the editor

### Operating System

MacOS

### OS Version

12.2.1

**Comment by dvaldivia** [comment] 2022-04-05 21:17
there's a weird coloring happening when running the latest warp with `k9s`

<img width="1392" alt="Screen Shot 2022-04-05 at 2 15 57 PM" src="https://user-images.githubusercontent.com/18384552/161850583-653803dc-7e95-46d3-81fb-a94cf3f63413.png">

**Comment by Mopper** [comment] 2022-04-07 14:36
This also happens when attaching to/logging into a running pod and then detaching from/logging out of that pod - I get a blank console with the cursor in the upper left hand corner and no key combination that I know of gets me back to k9s UI or a command prompt. The only thing I can do is close the tab. 

This does work on iterm with the same version of k9s (0.25.18).

**Comment by wpbeckwith** [comment] 2022-05-04 17:20
OK, I would love to bring more visibility to this issue.  I was just mucking around trying to see what triggers it and what doesn't.  I have a local kind cluster created with `kind create cluster --name foo` and then I selected a pod to edit and then immediately quit from editing and that worked.

However, I have a remote Platform9 cluster and an EKS cluster and just connecting, opening any thing to edit and then exiting will trigger the blank screen with the cursor in the top left corner.  Is there a way to get logs out of warp to help with debugging?

**Comment by etaham** [comment] 2022-07-01 15:20
This seems to occur on other K8s deployments when attaching to a debug shell and then running something like less in the shell.

**Comment by elviskahoro** [comment] 2022-07-08 14:10
Sorry about the all the issues with this! Will circle back when it's a work in progress.

**Comment by johnofsydney** [comment] 2022-08-01 03:03
Came here to say that I had this experience too.
Easy clean exit from k9s when using iterm
Does not return to terminal when exit k9s using warp

**Comment by MikaelWahlberg** [comment] 2022-08-15 17:19
This is the main thing preventing me from using Warp, I would love to see a fix! :)

**Comment by dannyneira** [comment] 2022-08-29 21:49
quick updated, we've been able to repro this issue and will circle back when we have and update/fix.

**Comment by wpbeckwith** [comment] 2022-09-30 02:19
I just got the latest Warp update and there is always something good in there _except_ for this issue.  While I get the drive to add more features, I feel that equal measure needs to be given to breaking changes.  This isn' a feature that never existed and we're pushing to get something new.  This was broken many moons back and it has taken forever and a day to get visibility on it.  Now that it has been reproduced, those of us waiting are hoping it won't take the same length of time to have the functionality restored.

**Comment by thezanke** [comment] 2022-12-06 02:21
This also happens to me when returning from editing a config in k9s.

### Operating System
MacOS

### OS Version
12.6

**Comment by interpeix** [comment] 2022-12-07 14:30
Same as @thezanke 

Operating System
MacOs

OS Version
12.6

K9S Version
v0.26.7

WARP Version
v0.2022.11.29.08.03.stable_03

**Comment by cfurrow** [comment] 2022-12-10 15:31
The behavior for this issue seems similar to one seen when using lazygit, https://github.com/warpdotdev/Warp/issues/1511, which currently does not have a fix.

[I saw on discord](https://discord.com/channels/851854972600451112/1047388236567289876/1047970484022685717) that there may be a fix incoming for this k9s issue (as of 2022-12-01):

> david:
> this is a known issue, unfortunately - we have an understanding of what's going wrong and are hoping to have a fix out soon.  sorry it's broken!

I'm hoping that this k9s fix may also help fix what may be going on with lazygit as well.

**Comment by dannyneira** [comment] 2022-12-15 22:31
Hi Folks, today we released some improvements that should help with returning from alt screen( k9s ) issues. Please let us know if anything changes or if the issues persist.

**Comment by wpbeckwith** [comment] 2022-12-15 22:32
Yay!! It works again.

**Comment by AndrzejOlender** [comment] 2022-12-15 22:33
Works! thanks :)

**Comment by wpbeckwith** [comment] 2022-12-15 22:34
Well now I can close my iTerm2 session.

**Comment by ammmze** [comment] 2022-12-15 22:50
🎉 I can confirm that it works as well! Thank you!

**Comment by interpeix** [comment] 2022-12-16 05:28
🎉 It works!

**Comment by azamora-zsc** [comment] 2022-12-16 08:35
It's working, yes. Thank you very much for addressing this issue. Good work!

**Comment by dannyneira** [comment] 2022-12-16 17:22
Awesome! thanks for the feedback, closing but feel free to reopen if the issue persists.

**Closed by dannyneira** 2022-12-16 17:22 UTC
Labels: Bug

**Comment by nessur** [comment] 2022-12-19 17:45
> Hi Folks, today we released some improvements that should help with returning from alt screen( k9s ) issues. Please let us know if this helped or if the issues persist.

Works great! Editing deployments in `k9s` is now flawless! Huzzah! This was my only blocker to moving to this from iTerm. <3 <3 <3

**Comment by cmditch** [comment] 2024-01-10 23:49
I'm not sure I understand how to resolve the grey background issue w/ warp and k9s. I'm still seeing this 
![image](https://github.com/warpdotdev/Warp/assets/15849320/2b7916d6-99dd-45ad-b165-da531ab8a347)

Any thoughts?

Thanks!

**Comment by dannyneira** [comment] 2024-01-12 22:11
@cmditch You most likely need to set the background as transparent for k9s so that you see Warps background instead of the grey one. It appears if you set the bg color to `default` it'll be transparent, but there are more instructions here https://k9scli.io/topics/skins/

**Comment by hellt** [comment] 2024-01-19 09:00
To expand what @dannyneira said
I had the same issue with the hazy overlay in my k9s

I had to open `~/.config/k9s/config.yaml` and set `.k9s.ui.bgColor=transparent`

Additionally, if one wants to use skinds, then again background color has to be set to transparent.

For instance for dracula theme https://github.com/derailed/k9s/blob/1a2ee1028cedda4eb1d750f1d2998cf67292c32f/skins/dracula.yaml#L7 change the actual bg color to `"transparent"`

<img width="1506" alt="image" src="https://github.com/warpdotdev/Warp/assets/5679861/74ab9f78-85d4-483a-b4d8-99b73be30e8a">

**Comment by johnofsydney** [comment] 2024-03-27 23:14
looks good, thanks for fixing!

**Comment by szgupta** [comment] 2024-10-01 18:33
Hey folks, sorry for resurrecting such an old issue but I've been investigating https://github.com/warpdotdev/Warp/issues/2373 and I want to make sure I am not regressing how Warp works with k9s. For anyone who experienced the original problem here (blank console, no way to get back to k9s UI), would you be willing to test k9s on a custom build? If so, please email me at [suraj@warp.dev](mailto:suraj@warp.dev). Much appreciated!

**Comment by szgupta** [comment] 2024-11-21 23:53
Hey folks, Suraj here again. We're planning to change our alt-screen padding defaults and want to make sure we're not regressing Warp's compatibility with alt-screen apps. I know `k9s` has been problematic in the past with our old alt-screen resize logic, so in an effort to release these changes safely, we're introducing an explicit opt-in to this change before a full rollout. If you've experienced issues with using `k9s` in Warp before, I would greatly appreciate if you try out the change here and let me know if it causes problems with `k9s`: https://github.com/warpdotdev/Warp/issues/2373#issuecomment-2492581897!

**Comment by ventsislav-georgiev** [comment] 2024-12-11 10:10
Hey, @szgupta it seems the original issue is somewhat happening again. When using exec to open an ssh session in k9s, and then exit, warp is left in blank screen and not returning to k9s UI.

https://github.com/user-attachments/assets/3f1a3fc6-dc5b-4c36-ae17-ccc7e86a38df

**Comment by bhuvansingla** [comment] 2024-12-11 13:00
> Hey, @szgupta it seems the original issue is somewhat happening again. When using exec to open an ssh session in k9s, and then exit, warp is left in blank screen and not returning to k9s UI.
> 
>  k9s-black-screen.mov

I can confirm the same behavior. 

I am running:
- Warp version: `v0.2024.12.03.08.02.stable_04`
- k9s version: `v0.32.7`

**Comment by szgupta** [comment] 2024-12-11 14:36
Hey @ventsislav-georgiev and @bhuvansingla, sorry for the issues here. We're aware of issues with k9s, and it _shouldn't_ actually respect the custom padding (to avoid exactly this issue). But our method of detecting if `k9s` was run might be off. How are y'all running `k9s`? Is it aliased?

**Comment by bhuvansingla** [comment] 2024-12-11 18:40
hey @szgupta, you guessed it right, I use aliases. After your comment, I tried it without the alias and it works fine, whereas with the aliases it does not. However, to mention, I have been using aliases since long ago, but only starting to see this behaviour now (since less than a month ago).

**Comment by ventsislav-georgiev** [comment] 2024-12-12 00:37
@szgupta I'm also using an alias and have been using it for a long time. It broke recently. Also confirm that running it without the alias works as expected.

**Comment by szgupta** [comment] 2024-12-14 19:54
Hey @ventsislav-georgiev and @bhuvansingla, the latest release should handle the aliases! Let me know if you're still running into problems.

Also, we're still looking into how to fix this for k9s in general so you don't have to deal with the padding. But this should at least make k9s usable in Warp in the meantime.

**Comment by ventsislav-georgiev** [comment] 2024-12-15 07:44
@szgupta just tested: v0.2024.12.10.15.55.stable_03
Still the same behavior for me. Using zsh with alias like:
```
alias k9="k9s --context somecontext"
```

**Comment by szgupta** [comment] 2024-12-16 15:45
Hey @ventsislav-georgiev, that's a bug on our end. Should be fixed in the next release!

**Comment by sharathkumarnp** [comment] 2025-01-13 12:09
Hey @szgupta, Do we have any ETA for the release?

**Comment by zargony** [comment] 2025-05-22 12:08
Same here. Warp v0.2025.05.14.08.11.stable_03, k9s v0.50.6, started from a bash script with `--context` parameter. Pressing `e` on a resource shows it in vim and allows editing. When saving and quitting vi with `:x`, the resource is not updated, screen turns black and becomes unresponsible. After closing the tab with Cmd-W, a `k9s` process keeps running in background with 100% CPU.

Turning off `Use custom padding in alt-screen` in appearance settings seems to fix the problem
