### ISSUE TITLE
Dock icon becomes missing

### ISSUE THREAD

**Issue by kg-currenxie** [warpdotdev/Warp#3019] opened 2023-05-05 01:43 UTC
### Describe the bug

The dock icon "disappears" and becomes a question mark.
I haven't experienced this before with any other app.

### To Reproduce

[Not rly reproducible]
This happens quite randomly. I haven't been able to identify a specific scenario on when it happens. It happens maybe once or twice a month.
This last time, I know it wasn't after an update. Maybe after a sleep, maybe not. The app was already open from what I remember, and not restarted etc..

### Expected behavior

Icon should not disappear

(FYI: Removing warp from dock, restarting it, brings back the icon every time)

### Screenshots

![image](https://user-images.githubusercontent.com/48229166/236361986-0b631a1a-0047-44d0-890a-aa11212c1579.png)

### Operating System

MacOS

### Operating System and Version

13.3.1

### Warp Version

v0.2023.04.25.08.05.stable_00

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by elviskahoro** [comment] 2023-05-05 01:46
Thanks for opening @kg-currenxie will check and see whether we have had any other reports of this so we can try to nail-down a culprit.

**Comment by dannyneira** [comment] 2023-05-05 19:11
Hey @kg-currenxie We are looking into this internally to see if it's reproducible. **_Please note that you will lose any settings you're currently set in Warp when you do this_** and I'm not 100% sure this may fix the issue, but you may want to consider [uninstalling Warp](https://docs.warp.dev/help/uninstalling-warp), deleting default settings with `defaults delete dev.warp.Warp-Stable`, and then [reinstalling Warp](https://docs.warp.dev/getting-started/getting-started-with-warp#installing-warp) to see if this helps with the issue.

**Comment by Frexuz** [comment] 2023-05-26 07:10
@dannyneira haven't seen it happening since a full reinstall. Hope it stays 👌 

But I just noticed that for every update, Warp installs/opens a new dock icon. Is this a known issue?

![image](https://github.com/warpdotdev/Warp/assets/49692/e463603a-13bd-4b72-bdcf-b23ea2fda7cb)

Tho I think we can close this issue :)

**Comment by dannyneira** [comment] 2023-05-26 16:54
Thanks for letting us know! Closing as resolved

**Closed by dannyneira** 2023-05-26 16:54 UTC
Labels: Bug
