### ISSUE TITLE
Oh My Zsh plugin for kubernetes autocompletion not working

### ISSUE THREAD

**Issue by matheuscscp** [warpdotdev/Warp#5458] opened 2024-11-08 13:52 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

The autocompletion of the `kubectl` plugin for Oh My Zsh is not working.

### To reproduce

1. First, enable the `kubectl` plugin for Oh My Zsh (using the `zsh` shell).
2. Type `kubectl dele` and press tab. Observe that the terminal does not autocomplete to `kubectl delete`.
3. Type `kubectl delete po short-prefix-of-some-pod-name` and press tab. Observe that the terminal does not autocomplete to `kubectl delete po full-pod-name` when there's only one pod with the short prefix.

### Expected behavior

I'd expect that Oh My Zsh plugins autocompletion works seamlessly. Details of expection behavior described in the steps to reproduce. However, if I start a zsh shell within the base shell, I can use the autocompletion seamlessly. That's just a workaround though, I'd like to use this feature seamlessly, without having to start a new shell in the shell.

### Screenshots

Not relevant.

### Operating system

Linux

### Operating system and version

Linux <computer-name-redacted> 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Shell Version

zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.10.29.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-11-12 20:44
Thanks for letting us know @matheuscscp This is a known limitation in Warp. Warp currently doesn't support shell-based autocompletions, this is because Warp has built its own wrapper around the shell, and completions are handled at the terminal level rather than the shell level. That being said, you should be able to accomplish your request with "Open completions as you type enabled" and we are working on improving Warps built-in kubtectl completions further. Please see my example below.

https://github.com/user-attachments/assets/706e710d-bcce-4e0e-9a3f-972e29bda160

All that being said, we're tracking the request for shell-based completion support over at https://github.com/warpdotdev/Warp/issues/1811 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-11-12 20:44
Duplicate of #1811

**Closed by dannyneira** 2024-11-12 20:44 UTC
Labels: Bugs

**Comment by funder7** [comment] 2025-09-22 08:04
Hello, is there any chance to have shell-based autocompletions "mixed" with warp terminal autocompletions? 
I'm thinking about warp being able to read the autocompletions provided by zsh/oh-my-zsh plugins: that would be great!
