### ISSUE TITLE
Colors in terminal

### ISSUE THREAD

**Issue by iwex** [warpdotdev/Warp#4565] opened 2024-03-15 08:51 UTC
### Describe the bug

I've converted this theme https://github.com/ahmadawais/Shades-of-Purple-iTerm2/blob/master/shades-of-purple.itermcolors with https://terminal-themes.com/create-theme.

And I can't get the same bright colors. Even white is not white. Compared to iterm2 it is a bit darker

![CleanShot 2024-03-15 at 10 48 27](https://github.com/warpdotdev/Warp/assets/4510068/d7e80f11-5ce5-4278-8a96-d4a6fc80ecbd)

Here is the code for it 
```yaml
accent: "#fad000"
background: "#1e1d40"
foreground: "#feffff"
details: "darker"
terminal_colors:
  normal:
    black: "#000000"
    red: "#d90429"
    green: "#3ad900"
    yellow: "#ffe700"
    blue: "#6943ff"
    magenta: "#ff2b70"
    cyan: "#00c5c7"
    white: "#c7c7c7"
  bright:
    black: "#676767"
    red: "#f9291b"
    green: "#42d425"
    yellow: "#f1d000"
    blue: "#6871ff"
    magenta: "#ff76ff"
    cyan: "#79e7fa"
    white: "#feffff"
```

### To reproduce

I've converted this theme https://github.com/ahmadawais/Shades-of-Purple-iTerm2/blob/master/shades-of-purple.itermcolors with https://terminal-themes.com/create-theme and installed to Warp

### Expected behavior

Bright colors

### Screenshots

![CleanShot 2024-03-15 at 10 52 12](https://github.com/warpdotdev/Warp/assets/4510068/91e3a7c4-49a5-4481-82e3-5406f9d5daf1)

### Operating system

MacOS

### Operating system and version

MacOS 14.4

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.03.12.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-16 05:36
Hi @iwex sorry about this, Warp does take into account the details "darker" "lighter" and adds a filter over colors based on that so try swaping to the latter and see if that helps with getting a brighter white. Also make sure you have the same font configured as the font may also be affecting the look of it.

Hope this helps!

**Comment by iwex** [comment] 2024-03-16 11:50
@dannyneira 
I copied old theme to shades-lighter and replaces darker with lighter, but as you can see - no changes.

https://github.com/warpdotdev/Warp/assets/4510068/8815780c-4f97-4895-83dd-727604fccc50

**Comment by dannyneira** [comment] 2024-03-18 16:14
Thanks for letting us know. We're looking into the dimming that's being placed on text and will post updates on this thread

**Comment by david-zamora-minderest** [comment] 2024-03-20 09:28
I have found that in comparison with other terminals, Warp paints what seems to be the blue color as purple. I use Warp with ZSH and starship with a very clean and simple configuration. I tried Ubuntu terminal and Tillix, both paint it dark blue, nor purple.
Tillix / Terminal
![image](https://github.com/warpdotdev/Warp/assets/95277922/ae1154a8-8eac-430d-994e-58bf4b7c7d08)

Warp Image
![image](https://github.com/warpdotdev/Warp/assets/95277922/896e5dc5-d0d4-43d2-86ff-e1c6f2e16906)

**Comment by jennso** [comment] 2024-04-27 12:38
Having the same issue here I copied my iterm colors theme, I believe the colors are corrrect but seems like warp add a dark overlay or dimms the colors down, maybe is a configurable setting that affects all themes? here is the example.

![image](https://github.com/warpdotdev/Warp/assets/61991816/8dabde6d-e7a1-42f9-b3f3-78ce1dff8757)

**Comment by azat-io** [comment] 2024-05-22 18:22
I have the same problem. All the colors seem dull.
My theme:

```yaml
accent: "#fabd2f"
background: "#141718"
details: lighter
foreground: "#fbf1c7"
terminal_colors:
  bright:
    black: "#1d2021"
    blue: "#83a598"
    cyan: "#8ec07c"
    green: "#b8bb26"
    magenta: "#d3869b"
    red: "#fb4934"
    white: "#fbf1c7"
    yellow: "#fabd2f"
  normal:
    black: "#1d2021"
    blue: "#458588"
    cyan: "#8ec07c"
    green: "#b8bb26"
    magenta: "#d3869b"
    red: "#fb4934"
    white: "#fbf1c7"
    yellow: "#fabd2f"
```

**Comment by dannyneira** [comment] 2024-05-22 18:23
Hi Folks, this is being worked on and should be released soon. https://github.com/warpdotdev/warp/issues/362#issuecomment-2123400075

**Comment by dannyneira** [comment] 2024-05-22 18:24
Duplicate of https://github.com/warpdotdev/warp/issues/362

**Closed by dannyneira** 2024-05-22 18:24 UTC
Labels: Bugs

**Comment by dannyneira** [comment] 2024-05-30 20:41
Hey Folks, As of the [latest release](https://docs.warp.dev/getting-started/changelog#id-2024.05.30-v0.2024.05.28.08.02),  Warp now renders terminal text ANSI colors as specified by the theme without any dimming. 

Please update and let us know if the issue persists.

**Comment by jennso** [comment] 2024-06-01 13:30
I updated and it was working, but this morning I relaunched and it's back to dimmed colors, the version I have is v0.2024.05.28.08.02.stable_00

**Comment by jennso** [comment] 2024-06-01 13:38
I just realized is not a color thing but a DPI thing, on my 4k screen the colors look slighlty diferent but on my 1440p they look the same.

**Comment by tariksetia** [comment] 2024-06-28 15:05
@dannyneira Do I need to change any settings for fixing colors?

version:

Please take a look at image below.(left one is warp and right one is hyper). There is clearly a color difference. I am not sure if it is a bug or it is behaving as intended 😅


![image](https://github.com/warpdotdev/Warp/assets/1137658/9b35517a-c15a-4a67-80af-05e90e904edd)
![image](https://github.com/warpdotdev/Warp/assets/1137658/9b35517a-c15a-4a67-80af-05e90e904edd)

**Comment by dannyneira** [comment] 2024-06-28 21:22
@iwex afaik Warp now renders terminal text ANSI colors as specified by the theme without any dimming. Even if you're using the same theme the presentation of colors may be different than other terminals (based on how they render the theme ANSI colors). Please learn more about how Warp renders text [here](https://www.warp.dev/blog/adventures-text-rendering-kerning-glyph-atlases).
