### ISSUE TITLE
Subshells don't work correctly

### ISSUE THREAD

**Issue by thomasheartman** [warpdotdev/Warp#1012] opened 2022-04-11 13:06 UTC
### Describe the bug

```text
When launching subshells (for instance by running `bash`, `zsh` or `fish`), all of Warp's fancy features disappear and you're dropped into a bog standard shell environment.
```

### To Reproduce

Steps to reproduce:
1. Open Warp
2. Run `bash`

### Expected behaviour

```text
I'd expect Warp to adapt to the new shell, keeping the command separation and everything working as usual.
```

### Screenshots

Screenshot using the default `zsh` shell with warp (running with all features):

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/17786332/162742962-2821548c-cad9-4379-8f9a-0e6c0461a145.png">

After running `zsh` and launching a subshell:

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/17786332/162743069-a83e206a-d527-41d2-9e3f-73fbd617538d.png">

### Operating System

MacOS

### OS Version

11.5.1

### Additional context

```text
First off: thank you all very much for a great product! I think it's a big step up in a lot of respects and I'm very curious to see where it goes from here!

Regarding the actual issue:

I use a Nix setup on my machine, so to start shells, I use the `nix-shell` command (both for my main environment and for project-specific shells). Sadly, this means that I lose all the fancy features that Warp provides when using shells with all the commands that I need for my workflow.

Admittedly, the Nix setup on my Mac is pretty poor, so that may be part of the problem, but I'd also expect Warp to handle subshells regardless.

I expect that (part of) the reason this happens is that when you start a new shell, the shell becomes a long-running process, so Warp probably just lets this process run as it would in any other terminal. I don't know if there's a good way around this or if Warp can recognize these commands in any way (or if it's desirable for most people). Maybe Warp could expose a user-editable list of commands that spawn new shells and that Warp should hook into somehow?
```

**Comment by dev4joel** [comment] 2022-04-11 13:47
Duplicate of #64

**Closed** 2022-04-11 17:46 UTC
