### ISSUE TITLE
Completion should be smart enough to find substrings

### ISSUE THREAD

**Issue by MiguelSOliveira** [warpdotdev/Warp#828] opened 2022-03-22 12:34 UTC
### Describe the solution you'd like?

```text
If I am in a folder with 2 directories
- testing-directory
- testing-demo

and I write "cd demo" and then tab, it would auto complete to "cd testing-demo".
```

**Comment by elviskahoro** [comment] 2022-03-22 17:32
Duplicate of:
- #149

**Closed by elviskahoro** 2022-03-22 17:32 UTC
