### ISSUE TITLE
Things keeping me from using Warp as primary instead of iTerm2

### ISSUE THREAD

**Issue by aremmell** [warpdotdev/Warp#3627] opened 2023-09-02 21:14 UTC
### Discord username (optional)

aremmell

### Describe the solution you'd like?

```Text
The following are features I rely upon heavily in iTerm2, and can't reasonably switch fully to Warp until they're implemented:

1. Profile / tab icons /colors based on rules
 - iTerm2 allows you to set rules like "when username is x and hostname is y" switch to this configuration (profile)
 - This allows you to tell at a glance, for example, which of your open tabs is an SSH session on server1, and which is a local shell session, etc. Each of my servers has its own icon so I know without checking that a particular tab is a session on that machine.
2. Status bar (see attached screenshot)
 - iTerm2 has a customizable status bar which can display active perf information and graphs like CPU usage, memory load, disk, network, etc.
```

### Is your feature request related to a problem? Please describe.

```Text
No
```

### Additional context

![image](https://github.com/warpdotdev/Warp/assets/812759/5d8ecdf9-5572-44a0-b5f9-6dff4aca6fbb)

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by elviskahoro** [comment] 2023-09-11 08:07
@aremmell Thanks for your feedback. I think we have open issues for both of the points you mentioned. I'll try to split this issue up so that they point at the right place

**Comment by heysweet** [comment] 2024-12-31 15:33
(Closing as duplicate since we have 2 other tracking issues, as was intended in 2023 😬 )

**Closed by heysweet** 2024-12-31 15:33 UTC
Labels: enhancement
