### ISSUE TITLE
Strange extra space before prompt

### ISSUE THREAD

**Issue by dhruvkb** [warpdotdev/Warp#2087] opened 2022-11-11 01:10 UTC
### Describe the bug

When using `zsh` and Starship in Warp with custom prompt enabled, there is an extra space before the prompt.

### To Reproduce

1. Use `zsh` & [Starship](https://starship.rs/).
2. Open Warp.
3. Enable "Honor user's custom prompt (PS1)".
4. See leading space.

### Expected behaviour

There shouldn't be a space before the prompt.

### Screenshots

<img width="1136" alt="Screenshot 2022-11-11 at 5 03 45 AM" src="https://user-images.githubusercontent.com/16580576/201238197-b562f2e0-55ac-4034-a354-99611845cec5.png">
^ Note the selected extra space.

---

<img width="1082" alt="Screenshot 2022-11-11 at 5 04 25 AM" src="https://user-images.githubusercontent.com/16580576/201238267-7c674e13-c8f8-4354-a5ed-dd6f855ba403.png">
^ iTerm doesn't have this extra space.

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.08.08.07.stable_02

### Does this block you from using Warp daily?

No

**Comment by Anselmoo** [comment] 2022-11-12 12:57
Can confirm for `fish`, too.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/13209783/201475022-644777a4-32bc-4f6b-b0d1-8acf64d7ec31.png">

after `> fish`

<img width="390" alt="image" src="https://user-images.githubusercontent.com/13209783/201475052-861fe56d-ee8b-4acc-ad24-d812157aa088.png">

**Comment by Anselmoo** [comment] 2022-11-12 12:58
> ### Discord username (optional)
> _No response_
> 
> ### Describe the bug
> When using `zsh` and Starship in Warp with custom prompt enabled, there is an extra space before the prompt.
> 
> ### To Reproduce
> 1. Use `zsh` & [Starship](https://starship.rs/).
> 2. Open Warp.
> 3. Enable "Honor user's custom prompt (PS1)".
> 4. See leading space.
> 
> ### Expected behaviour
> There shouldn't be a space before the prompt.
> 
> ### Screenshots
> <img alt="Screenshot 2022-11-11 at 5 03 45 AM" width="1136" src="https://user-images.githubusercontent.com/16580576/201238197-b562f2e0-55ac-4034-a354-99611845cec5.png">
> 
> ^ Note the selected extra space.
> <img alt="Screenshot 2022-11-11 at 5 04 25 AM" width="1082" src="https://user-images.githubusercontent.com/16580576/201238267-7c674e13-c8f8-4354-a5ed-dd6f855ba403.png">
> 
> ^ iTerm doesn't have this extra space.
> ### Operating System
> MacOS
> 
> ### OS Version
> 13.0.1
> 
> ### Shell Version
> zsh 5.8.1 (x86_64-apple-darwin22.0)
> 
> ### Warp Version
> v0.2022.11.08.08.07.stable_02
> 
> ### Additional context
> _No response_
> 
> ### Does this block you from using Warp daily?
> No
> 
> ### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e
> _No response_

See also https://github.com/warpdotdev/Warp/issues/580

**Comment by taco-chen** [comment] 2022-11-16 16:03
Just met the same issue here :)

**Comment by dannyneira** [comment] 2022-12-02 21:58
It looks like you're using a multi-line prompt, which isnt supported in Warp, please see more here. <https://docs.warp.dev/features/prompt>

I recommend you disable it just for Warp. You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

**Comment by dannyneira** [comment] 2022-12-02 21:58
Closing as duplicate of #580, please sub to that issue for updates.

**Closed by dannyneira** 2022-12-02 21:58 UTC
