### ISSUE TITLE
kubectl logs 不能补全pod

### ISSUE THREAD

**Issue by cx2c** [warpdotdev/Warp#4584] opened 2024-03-19 03:37 UTC
### Describe the solution you'd like?

就这么说吧，用terminal的，现在哪个不用k8s， logs 不能补全pod，给谁用？

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-19 21:22
Thanks for letting us know that `kubectl logs` doesn't complete the pod names, please workaround by adding it manually, We'll work on fixing this and let you know if anything changes.

感谢您告知我们`kubectl logs`未完成 Pod 名称，请通过手动添加来解决此问题，我们将努力修复此问题，并在发生任何变化时通知您。

**Comment by dannyneira** [comment] 2024-04-11 21:02
Duplicate of https://github.com/warpdotdev/Warp/issues/3958

**Closed by dannyneira** 2024-04-11 21:02 UTC
Labels: enhancement
