### ISSUE TITLE
"Checking for update" text doesn't reflect the current status

### ISSUE THREAD

**Issue by Moshyfawn** [warpdotdev/Warp#2434] opened 2023-01-03 16:06 UTC
### Discord username (optional)

moshyfawn#7250

### Describe the bug

The update check text in the About Warp section does not reflect the current update status and always displays `(checking for update...)`

### To Reproduce

1. Open Warp
2. Open the Settings Dialog (CMD-,) using the Command Palette or by clicking the three dots > Settings > Account.
3. See `(checking for update...)` text displayed indefinitely / click "Check for Update" button and see `(checking for update...)` text displayed indefinitely

### Expected behaviour

The text is changed to `(up to date)` if no updates are present

### Screenshots

<img width="520" alt="image" src="https://user-images.githubusercontent.com/16290753/210394976-ac09dbc2-1ef3-4cbf-b945-e328f72ed24e.png">

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.12.13.08.04.stable_01

### Additional context

It seems like the update status is actually received but the text is not updated. Hovering over the "Copy terminal version" icon forces a UI update that displays the correct update status

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-01-03 21:30
Thanks for letting us know, I was able to reproduce this issue thanks to your info. We'll post updates here if there are any updates on this.

**Comment by brian316** [comment] 2023-01-05 18:48
Agree with @Moshyfawn here. I had to manually look and try to upgrade because I thought my version was out of sync with the updates.

<img width="505" alt="image" src="https://user-images.githubusercontent.com/3878246/210857342-76c6e9c0-8102-412a-b388-db7c94cc7af1.png">

**Comment by dannyneira** [comment] 2023-03-02 23:29
Hey Folks, this fix is out on today's release v0.2023.02.28.08.03.stable_01.

Closing as completed but please let us know if the issue persists.

**Closed by dannyneira** 2023-03-02 23:29 UTC
Labels: Bug

**Comment by Moshyfawn** [comment] 2023-03-07 01:58
Looks good, thank you!
