### ISSUE TITLE
The ability to change font weight

### ISSUE THREAD

**Issue by spaceexperiment** [warpdotdev/Warp#2569] opened 2023-01-27 12:10 UTC
### Describe the solution you'd like?

```text
Is it possible to add the option to modify the font weight? I always prefer bold font as it makes reading easier for me.
```

### Is your feature request related to a problem? Please describe.

```text
increase readability
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by hundehausen** [comment] 2023-01-27 21:47
You can change it in the settings under appearance

**Comment by spaceexperiment** [comment] 2023-01-28 08:54
> You can change it in the settings under appearance
@hundehausen 
I only see the option to change the font family and font size, but not font weight. Am I missing something?

**Comment by hundehausen** [comment] 2023-01-28 08:58
you're right

**Comment by dannyneira** [comment] 2023-01-30 21:58
Thanks for submitting this @spaceexperiment, you're correct we dont have weight options, as a workaround i recommend installing the "Bold" version of your preferred font which should bold it by default.

Also, please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by mikka2061** [comment] 2023-03-18 05:54
Installing a bold version is not feasible in cases of variable size font packs like Iosevka or Hack. This is, right now, the breaker for me.

**Comment by heybigneel** [comment] 2023-06-27 07:04
Not a deal breaker but would definitely appreciate having an option to configure font weight.

**Comment by Toxicom** [comment] 2023-07-07 10:26
Shook that this isn't a feature yet

**Comment by 917huB** [comment] 2023-08-05 02:51
+1

**Comment by iamvoidcoder** [comment] 2023-08-05 09:46
+1. Can't use Warp w/o font weight control.

**Comment by moeamaya** [comment] 2023-09-01 18:15
Not a deal breaker, but definitely high up on my list

**Comment by sgmonda** [comment] 2023-10-04 06:27
+1, I need this feature

**Comment by pibo** [comment] 2023-10-30 19:36
+1

**Comment by yuritoledo** [comment] 2023-11-06 13:02
+1

**Comment by cubatic45** [comment] 2023-11-17 03:24
+1, I'll change my default terminal from iterm2 to warp if warp add text weight

**Comment by nfwyst** [comment] 2023-11-25 09:28
font is tooooo thin....

**Comment by jzuijlek** [comment] 2023-11-30 10:05
+1

**Comment by NXTaar** [comment] 2023-12-25 14:46
+1 also need a font weight control

**Comment by HakonHarnes** [comment] 2024-02-27 20:46
+1

**Comment by PaulWeinsberg** [comment] 2024-03-02 10:06
+1

**Comment by PaulWeinsberg** [comment] 2024-03-02 10:08
I've just disabled thin stroke (Never) and it's much better on my MacBook

**Comment by dannyneira** [comment] 2024-03-05 23:27
Hi Folks, Sorry about this but i'm be closing this request in favor of #280 which is an older request. We'll be tracking interest in font weight settings there, please continue to 👍 the topline issue and avoid spam comments like "+1".

Closing as duplicate.

**Comment by dannyneira** [comment] 2024-03-05 23:27
Duplicate of #280

**Closed by dannyneira** 2024-03-05 23:27 UTC
Labels: Feature requests

**Comment by okharedia** [comment] 2025-05-16 21:29
+1
