### ISSUE TITLE
Add option to pause output

### ISSUE THREAD

**Issue by mmerdes** [warpdotdev/Warp#2220] opened 2022-11-24 10:30 UTC
### Describe the solution you'd like?

```text
It would be beneficial to be able to pause (and resume) the console output in the current active block.
```

### Is your feature request related to a problem? Please describe.

```text
When tailing the log files of an active process, i.e. a running server,
it can be very difficult to study log entries when the log is always moving.
```

### How important is this feature to you?

4

**Comment by dannyneira** [comment] 2022-11-28 23:10
Thanks for this request, closing as duplicate of #1355 Please track progress there

**Closed by dannyneira** 2022-11-28 23:10 UTC
Labels: Feature
