### ISSUE TITLE
Update not fully installed Ubuntu 24

### ISSUE THREAD

**Issue by Ammar-kutubee** [warpdotdev/Warp#4955] opened 2024-05-26 04:43 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

when i press on update warp, it reopens and still update warp button showing, keep pressing repeats the issue.

### To reproduce

click on Update warp ... wait (relaunching...)... update button still shows.

### Expected behavior

the update button should disapear after updating.
also pressing Relaunch Warp button from settings , isnot helping.

### Screenshots

![Screenshot from 2024-05-26 07-41-21](https://github.com/warpdotdev/Warp/assets/114086926/a61f47e3-7709-4f51-ace7-0fc4bd5bd262)

### Operating system

Linux

### Operating system and version

Ubuntu 24

### Shell Version

zsh 5.9 (x86_64-ubuntu-linux-gnu)

### Current Warp version

v0.2024.05.14.08.01.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by krillavilla** [comment] 2024-05-29 08:50
I believe `thefuck` module is the cause of this:

![image](https://github.com/warpdotdev/Warp/assets/68208879/35b316eb-3d4c-4a3e-961c-584329d67486)

**Comment by jmarcon** [comment] 2024-05-31 14:03
> I believe `thefuck` module is the cause of this:
> 
> ![image](https://private-user-images.githubusercontent.com/68208879/334728677-35b316eb-3d4c-4a3e-961c-584329d67486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjQzODcsIm5iZiI6MTcxNzE2NDA4NywicGF0aCI6Ii82ODIwODg3OS8zMzQ3Mjg2NzctMzViMzE2ZWItM2Q0Yy00YTNlLTk2MWMtNTg0MzI5ZDY3NDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzYjgyMzI2ODA4ZDRlMzJiZDFlMzU0ZDM1M2ZjYzkwMTgzNGJiMjk1MTJlNzlmZDI4OTBlNTMxZjllN2U3MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lUTAICG327IIW1HLwaUuWEL19T6BMn8M3UBiAt5esK4)

The bug description doesn´t mention `thefuck` module. I don´t have it and I'm experiencing the same behavior.

**Comment by dannyneira** [comment] 2024-05-31 23:13
Hey @Ammar-kutubee Sorry about this, try the following.
- refresh apt repository for Warp and attempt to update
```
sudo apt-get install wget gpg
wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
rm warpdotdev.gpg
sudo apt update && sudo apt install warp-terminal
```

@jmarcon if the versions are different there is a chance the delay in updating the apt repo is the cause of this issue. I'll let the team know and we'll look into this.

**Comment by Ammar-kutubee** [comment] 2024-06-02 04:33
> Hey @Ammar-kutubee Sorry about this, try the following.
> 
> * refresh apt repository for Warp and attempt to update
> 
> ```
> sudo apt-get install wget gpg
> wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
> sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
> sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
> rm warpdotdev.gpg
> sudo apt update && sudo apt install warp-terminal
> ```
> 
> @jmarcon if the versions are different there is a chance the delay in updating the apt repo is the cause of this issue. I'll let the team know and we'll look into this.

it worked sir thanks

**Comment by Ammar-kutubee** [comment] 2024-06-02 04:33
> I believe `thefuck` module is the cause of this:
> 
> ![image](https://private-user-images.githubusercontent.com/68208879/334728677-35b316eb-3d4c-4a3e-961c-584329d67486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDMwNDIsIm5iZiI6MTcxNzMwMjc0MiwicGF0aCI6Ii82ODIwODg3OS8zMzQ3Mjg2NzctMzViMzE2ZWItM2Q0Yy00YTNlLTk2MWMtNTg0MzI5ZDY3NDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDA0MzIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NzZjNDljZGIwYmQ0NjkwZTYyYjRjNjEyODg1MDMyY2JhYTFkMjBjZDdmOTFhMzgxZjcwNmZlYzNjZmI4ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjMjg_ByVqbgAMe7U5HmjHUmSmVKvRBz-6ZcevGYP30)

i dont have that module unfortunately

**Comment by dannyneira** [comment] 2024-06-03 15:44
Thanks for letting us know @Ammar-kutubee 

If this happens again, please run the update steps, omitting the `warp_finish_update $(random_character)` part, and provide screenshots of any errors you see when trying to upgrade.

**Comment by dannyneira** [comment] 2024-08-02 21:22
Hey Folks, by any chance did you recently update Ubuntu to version 24 (from v23.1 or older)? I suspect this issue is related to Ubuntu updates not carrying over the Warp repository since the workaround seems to be manually adding the repository again.

**Comment by Ammar-kutubee** [comment] 2024-08-14 07:22
its was ubnutu version 23 ...yes
i solved the issue by uninstalling and reinstalling the warp app

**Comment by dannyneira** [comment] 2024-08-14 22:50
We're tracking this particular issue here. https://github.com/warpdotdev/Warp/issues/5201

I'll close this as a duplicate, but please let me know if the issue persists after you add the repo with the command above.

**Closed by dannyneira** 2024-08-14 22:50 UTC
Labels: Bugs

**Comment by Kaneki-Ken993** [comment] 2024-12-09 09:17
> Hey @Ammar-kutubee Sorry about this, try the following.
> 
> * refresh apt repository for Warp and attempt to update
> 
> ```
> sudo apt-get install wget gpg
> wget -qO- https://releases.warp.dev/linux/keys/warp.asc | gpg --dearmor > warpdotdev.gpg
> sudo install -D -o root -g root -m 644 warpdotdev.gpg /etc/apt/keyrings/warpdotdev.gpg
> sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/warpdotdev.gpg] https://releases.warp.dev/linux/deb stable main" > /etc/apt/sources.list.d/warpdotdev.list'
> rm warpdotdev.gpg
> sudo apt update && sudo apt install warp-terminal
> ```
> 
> @jmarcon if the versions are different there is a chance the delay in updating the apt repo is the cause of this issue. I'll let the team know and we'll look into this.

Thank you sir you solved my problem, that solution was so perfect and precise
