### ISSUE TITLE
All text and icons missing in Rocky Linux VM

### ISSUE THREAD

**Issue by RWCoding58** [warpdotdev/Warp#5433] opened 2024-11-01 09:54 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Recently tried using Warp in my Rocky Linux VM (using VMWare Workstaion Pro), but after logging in, I found that text and icons were completely missing in the app. I can technically interact with the app just fine (can send commands, click buttons), but all text is either missing or replaced with weird underscore symbols. 

Not sure what else to add except that I am quite new to Linux, so kindly be forgiving to me if I'm doing anything wrong.

### To reproduce

1. Open Warp

### Expected behavior

Text and icons show

### Screenshots

Warp screenshot
![warp](https://github.com/user-attachments/assets/69818336-f711-4290-bbee-19d5d3c84c36)

Ditto, but with "what" typed in the textbox
![warp text](https://github.com/user-attachments/assets/bdf721f3-5fa5-4b8a-8b6c-8b72062a85c1)

### Operating system

Linux

### Operating system and version

Rocky Linux 9.4 (Blue Onyx)

### Shell Version

zsh 5.8 (x86_64-redhat-linux-gnu)

### Current Warp version

v0.2024.10.29.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

Using Wayland

Unfortunately can't send the results of `RUST_LOG=wgpu_core=info,wgpu_hal=info MESA_DEBUG=1 EGL_LOG_LEVEL=debug warp-terminal` since I can't see the output.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-11-04 15:47
Thanks for letting us know, @RWCoding58. I'll link this over as a known issue with Warp not working on VMware VMs (it does not support the SVGA3D virtual GPU adapter).

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/4598 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-11-04 15:47
Duplicate of https://github.com/warpdotdev/Warp/issues/4598

**Closed by dannyneira** 2024-11-04 15:47 UTC
Labels: Bugs

**Comment by RWCoding58** [comment] 2024-11-05 00:33
I see, I thought it was a different issue since my window could render (just without the text) while those other issues seemed to not have any window at all.

Either way, thanks for the update
