### ISSUE TITLE
Python `venv` virtual environment rendering issue

### ISSUE THREAD

**Issue by zhu-yifang** [warpdotdev/Warp#4025] opened 2024-01-05 03:55 UTC
### Discord username (optional)

Gnafiy

### Describe the bug

When dragging the terminal in a Python `venv`, the name got copied.
Here is a video explaining this bug: https://github.com/warpdotdev/Warp/assets/70597936/638529fd-6b49-4bf0-9275-34531cf44b54

### To reproduce

1. Go to a random directory
2. Run `Python3 -m venv myenv`
3. Run `cd myenv`
4. Run `source bin/activate`
5. Drag the window

### Expected behavior

There should be only one `venv` name

### Screenshots

<img width="1439" alt="Screenshot 2024-01-04 at 19 50 05" src="https://github.com/warpdotdev/Warp/assets/70597936/806933c8-6666-43c5-8f04-d6e366a6d9a1">

### Operating system

MacOS

### Operating system and version

macOS 14.1.2

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.01.02.08.02.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-05 18:58
Thanks for letting us know @zhu-yifang 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/2713 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-05 18:58
Duplicate of https://github.com/warpdotdev/Warp/issues/2713

**Closed by dannyneira** 2024-01-05 18:58 UTC
Labels: Bug
