### ISSUE TITLE
New AI Agent prompt broke VScode open command

### ISSUE THREAD

**Issue by traverspinkerton** [warpdotdev/Warp#5043] opened 2024-06-18 22:19 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

the command `code .` opens VSCode with the current directory opened. This no longer works on the latest update

### To reproduce

install VSCode and make sure `code` is in your `path`. navigate to the directory you want to open, then run `code .`

### Expected behavior

opens VScode with the current directory opened

### Operating system

MacOS

### Operating system and version

14.5.0

### Current Warp version

v0.2024.06.11.08.02.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-06-18 23:05
Hi @traverspinkerton sorry to hear about this. I've heard another report of this but can't reproduce this with or without code in the path. Can you please let us know the result of this command?
```
which -a code
echo $PATH
```
Any changes besides the upgrade to Warp?

You may be able to work around the issue by removing `code` binary from the path as it may already be included in the macOS `/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin`

**Comment by traverspinkerton** [comment] 2024-06-19 00:23
Well, the issue resolved itself, it works now. not sure what happened!

**Comment by dannyneira** [comment] 2024-06-21 17:28
Thanks for letting us know. I've heard a restart fixed a similar issue with a recent update.

**Comment by dannyneira** [comment] 2024-06-21 17:28
Thanks for letting us know. I heard a restart fixed a similar issue with Agent Mode. 

Closing as resolved, but please let us know if it returns.

**Closed by dannyneira** 2024-06-21 17:28 UTC
Labels: Bugs
