### ISSUE TITLE
Current Theme is not restored after restart (when OS Dark/Light mode sync is on)

### ISSUE THREAD

**Issue by ubamrein** [warpdotdev/Warp#686] opened 2022-01-27 06:35 UTC
### Describe the bug

When the "Sync with OS" option is enabled, I can switch themes, but they are not restored when Warp is restarted.

### To Reproduce

Steps to reproduce:
1. Open theme picker
2. Select theme
3. Confirm
4. Restart

### Expected behaviour

```shell
The theme chosen should be saved somewhere, so that at new start I don't have to reselect it.
```

**Comment by elviskahoro** [comment] 2022-01-28 05:25
Can you send a video? Not able to reproduce this.

**Comment by ubamrein** [comment] 2022-01-31 07:33
https://user-images.githubusercontent.com/47777208/151754631-02c4e0ec-71c5-41f7-8192-2b7246b627a9.mov

Her you go :) It only happens when the "Sync with OS" switch is turned on.

**Comment by gagata** [comment] 2022-02-04 22:46
hey! thanks for this report, it's super helpful! i took a quick look and can reproduce this. for now, if you want to set the themes and preserve them, please access the theme picker through settings (instead of opening it with command palette). simply go to settings -> appearance and then click on the thumbnail of either themes to launch theme picker. if you set the theme this way, your settings should be preserved between restarts.

meanwhile, we'll investigate what's causing the bug when the theme picker is accessed via command palette... sorry for the inconvenience!

**Comment by elviskahoro** [comment] 2022-08-28 04:50
This should be fixed! Please comment or reopen if it isn't for you!

**Closed by elviskahoro** 2022-08-28 04:50 UTC
