### ISSUE TITLE
Block split line disable

### ISSUE THREAD

**Issue by ashertz-dev** [warpdotdev/Warp#3755] opened 2023-10-11 03:17 UTC
### Describe the solution you'd like?

```Text
I want to hide the block split line, it not means disable block, just hide vision of split line
```

### Is your feature request related to a problem? Please describe.

```Text
I can't focus on my work!
```

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-10-11 17:03
Thanks for this feature request @ashertz-dev. To anyone else interested in this feature, please add a :+1: to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-07-09 21:31
Duplicate of https://github.com/warpdotdev/Warp/issues/2177

**Closed by dannyneira** 2024-07-09 21:31 UTC
Labels: Feature requests
