### ISSUE TITLE
Allow adding more padding at the bottom of the screen

### ISSUE THREAD

**Issue by contentfree** [warpdotdev/Warp#1360] opened 2022-05-16 06:11 UTC
### Describe the solution you'd like?

```text
I like having my terminal fill the screen top-to-bottom (and often ⅓ of the screen). It would be very nice to not have the input at the very, very bottom, but instead leave some amount of room. Yes, I can resize the window but I'd rather just have some padding. This could be themeable.
```

**Comment by elviskahoro** [comment] 2022-07-09 05:51
Ah yes! great call out. thanks for opening

**Comment by elviskahoro** [comment] 2023-06-06 17:35
@kamalkech @contentfree 

We added support for customizing the behavior of the Input Editor, can you try both: Pin to the bottom and Start at the top. I think this might be what you're looking for! Gonna close this out for now, please comment if it isn't.

Settings > Appearance > Input > Input Position

There are three options:

- Pin to the bottom (Warp default)
- Start at the top (Classic mode)
- Pin to the top (Reverse mode)

![CleanShot 2023-06-06 at 10 30 34](https://github.com/warpdotdev/Warp/assets/29553206/47800beb-1f3c-4692-9399-ab559aade22b)

**Comment by kamalkech** [comment] 2023-06-06 21:26
@elviskahoro i guess u not understand the question, i am talking about space (padding) in left, right, top, button of the terminal, and change akk this input position then restart warp every time, but any thing changed

**Comment by elviskahoro** [comment] 2023-06-06 21:45
@kamalkech I'll reopen it, but did you try Start at the top? It might help somewhat

**Comment by kamalkech** [comment] 2023-06-06 22:48
@elviskahoro 
![image](https://github.com/warpdotdev/Warp/assets/1313428/b6aab0d3-be85-4d1d-b3b5-a3058dc01f4c)

**Comment by elviskahoro** [comment] 2023-06-06 23:34
We have an open issue for REMOVING the padding around Vim, Neo, etc. (alt-grids), if that's what you're looking for you can follow it here:
https://github.com/warpdotdev/Warp/issues/2373

**Comment by elviskahoro** [comment] 2023-06-06 23:35
@kamalkech let me know if I can close this in favor of #2373 after you check it out and see if that is in fact that issue you're bringing up

**Comment by kamalkech** [comment] 2023-06-09 00:06
@elviskahoro i already check this discussion https://github.com/warpdotdev/Warp/issues/2373 but no solution found there !!

**Comment by elviskahoro** [comment] 2023-06-09 01:54
@kamalkech there isn't a workaround for this, because of the trade-offs it'll likely be like this for awhile. on my warp I just edited my theme to match vim / the alt-grid

![CleanShot 2023-06-08 at 18 53 47](https://github.com/warpdotdev/Warp/assets/29553206/efe12b9b-88f2-4e93-a5d1-4e552af2c14f)

**Comment by kamalkech** [comment] 2023-06-09 10:12
@elviskahoro ok :(

**Comment by kamalkech** [comment] 2023-06-10 22:59
@elviskahoro i guess it s better to keep user to enable and disable the padding like other terminal kitty or alacritty

**Comment by elviskahoro** [comment] 2023-06-12 00:41
Tried removing the padding but if I remember correctly were some complications with the rounded window borders and also displaying the text properly. It's more involved than just adding a toggle to disable / enable

**Comment by kamalkech** [comment] 2023-06-12 01:16
hopefully found a good solution.

**Comment by dannyneira** [comment] 2024-03-21 21:14
Duplicate of #1418

**Closed by dannyneira** 2024-03-21 21:14 UTC
Labels: Feature requests

**Comment by dexwert85** [comment] 2024-07-14 20:34
so what happend
