### ISSUE TITLE
Support tab bar list vertically

### ISSUE THREAD

**Issue by AndyQ** [warpdotdev/Warp#143] opened 2021-08-25 06:55 UTC
### Is your feature request related to a problem? Please describe.

```shell
Not sure whether its just something I'm used to but I prefer having the window tab bar list display vertically and attached to the side.  They are more readable especially when you have a number of tabs open.
```

### Describe the solution you'd like?

```shell
Ability to have the tab bar list arranged vertically attached to the side rather than across the top of the screen horizontally.
```

### Additional context

<img width="902" alt="image" src="https://user-images.githubusercontent.com/1494770/130741498-aefb1add-ad4d-4c6e-9898-2823c3cec502.png">

**Comment by elviskahoro** [comment] 2022-07-05 04:25
We have a ticket open for this but not sure what the ETA is. Will follow up when it's been prioritized.

**Comment by devguydavid** [comment] 2023-02-09 22:55
"Is your feature request related to a problem? Please describe."

I'll add my thoughts. It's the same reason I use Edge instead of Chrome.

The problem is that I can't see enough of my tab title text at a glance when I have more than a handful of tabs.

More info:

Tab titles are text. Text runs horizontally. I open a lot of tabs. With a lot of horizontally-running tabs the tab width is reduced to make room for all of the tabs. This hides a lot of the text.

Windows are also usually wider than they are tall since that's the shape of most monitors, so taking up window real estate on the side is less impactful than on the top.

If tabs run vertically down the side, they can be kept at a consistent (and even configurable/draggable) width to reveal more title text and impact the shape and space in the window less.

Even if I have too many tabs for them all to fit on the screen, I wouldn't mind if some were off the screen and I have to scroll the tab container to get to them. I suppose that means tabs along the top could also be a consistent size and scrollable, but a lot more tabs can be fit vertically down the side than they can be along the top horizontally. It's all about presenting as much information as possible without me needing to interact with it which vertical tabs would allow.

**Comment by dannyneira** [comment] 2023-09-28 16:01
Hi Folks, We're closing this request in favor of #2155 as the other one has more 👍 's

We'll post any updates on the request above.

**Closed** 2023-09-28 16:01 UTC
Labels: Feature
