### ISSUE TITLE
Alternativa AI support

### ISSUE THREAD

**Issue by ShivamB25** [warpdotdev/Warp#3821] opened 2023-10-31 08:26 UTC
### Discord username (optional)

eggu. / eggu.#0000

### Describe the solution you'd like?

use of alternative ai , other than the openApi with newer dataset fed:
[mistral](https://mistral.ai/news/announcing-mistral-7b/)
[wizardLLM](https://huggingface.co/WizardLM)  [Demo](http://47.103.63.15:50085/)

### Is your feature request related to a problem? Please describe.

```Text
the outdated gpt's aren't that useful
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-10-31 15:47
Thanks for this feature request! To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

Also, there is a related request here to use LLMs other than OpenAI #3779

**Comment by dannyneira** [comment] 2024-03-06 18:55
Duplicate of https://github.com/warpdotdev/Warp/issues/3779

**Closed by dannyneira** 2024-03-06 18:55 UTC
Labels: Feature requests
