### ISSUE TITLE
Show the full command in the the history search autocomplete UI

### ISSUE THREAD

**Issue by itsrifat** [warpdotdev/Warp#4041] opened 2024-01-08 18:12 UTC
### Describe the solution you'd like?

```Text
When searching in history with `cmd+P -> history search` we can't see the full command for longer commands. makes it hard to select the one I'm looking for. It would be great if the was a way to see the preview of the command when hovered on it or the autocomplete UI is expanded to full width with no truncation
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-09 00:57
Hey @itsrifat When you press `UP`, you will see only some sections of the command, but as you select the command will be in the input so you can see the entire command. You can also use `CTRL-R` for command search and use `h:` to filter for history and increase the width of the search.

https://github.com/warpdotdev/Warp/assets/16809145/dabf74ea-255d-4f9c-bab1-6e5c6d085432

Hopefully, this helps with your use case for seeing more of the commands.

**Comment by dannyneira** [comment] 2024-01-09 00:58
Duplicate of https://github.com/warpdotdev/Warp/issues/1405

**Closed by dannyneira** 2024-01-09 00:58 UTC
Labels: Feature
