### ISSUE TITLE
Extremely Slow Shell Startup (10-20 seconds)

### ISSUE THREAD

**Issue by n00ki** [warpdotdev/Warp#4846] opened 2024-04-28 17:46 UTC
### Describe the bug

Hi everyone 👋
After two full weeks of battling extremely slow shell startup time, which includes debugging each component individually, completely uninstalling and reinstalling everything, switching possible incompatible plugins and packages, entirely clearing `zsh` dot files, and even setting everything from the ground up on a new machine, I’m exhausted😪 and I’m reaching out for help.

About a month ago, I started to notice a significant degradation in shell startup time when launched from an idle state (meaning, after not being used for over ~20-30 minutes). I’m talking 10-20 seconds initialisation on application launch.
my ZSH config was never too heavy, but at the time, I did use `OMZ` with `starship` prompt and some libs like `n`, `goenv`, etc.
I started looking for answers online and chased down every possible cause. I uninstalled/reinstalled OMZ. I also uninstalled the starship prompt and reverted to the native one. I replaced `n` with `NVM` (which made things even worse), then `fnm`. `goenv` and others were removed. `git` was installed separately by brew (due to a GitHub issue I’ve seen), then the git plugin was disabled entirely. Nothing! 
used `zprof` to monitor loading times, yet there was no correlation between the measurements and the overall shell launching time (e.g. 0.02 seconds reported when the shell took around 15 seconds to start).
I gave up and decided to set everything up from scratch on another MacBook (MBP M1 Pro Sonoma).
I was absolutely shocked when the issue persisted! Beyond `fnm`, `pnpm`, and some aliases, nothing was there...and the issue persisted.
for a while this issue was reproducing both on Warp 

and other terminals (iTerm2, native), but after removing a brew eval call in `.zprofile` - everything looked good on all others. Warp remains slow. 
Then i tried to empty both `.zshrc`, `.zshenv` and `.zprofile` - nothing. 
followed the docs and added `ZDOTDIR=/ to` `.zshenv` both in `~/` & `/etc`- no improvement. still slow.
* the issue does not reproduce on subsequent launches, only once after the application is closed for over ~20 minutes.

attached is a screen recording of warp launching with `ZDOTDIR=/`.
i would highly appreciate any kind of assistance with figuring out and possibly solving this issue!
Thanks a lot in advance🙏

### To reproduce

1. Lauch Warp
* extremely slow shell startup
2. Quit Warp
3. Relaunch Warp
* startup is normal as expected 
4. Quit Warp
5. Wait for ~20-30 minutes
6. Relaunch Warp
* extremely slow shell startup

### Screenshots

https://github.com/warpdotdev/Warp/assets/42724748/d58d1d39-287a-4974-ba20-614125fc1157

### Operating system

MacOS

### Operating system and version

14.4.1 (23E224)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.04.23.08.01.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

not sure

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-30 22:33
Hi @n00ki sorry to hear about this frustrating issue. If your still seeing the zsh loadin issue, even with a clean ~/.zshrc file, it could be something with our bootstrap script, especially if this wasn't the case a month ago as you mentioned.

Please try the following:
- Run `echo 'ZDOTDIR=/' > ~/.zshenv` This forces zsh to run with zero configs.
- Remove Warp logs with `sudo rm -r $HOME/.warp/ $HOME/Library/Logs/warp.log`
- Remove Warp database with `sudo rm -r "$HOME/Library/Application Support/dev.warp.Warp-Stable"`
- Quit and reopen Warp
- If the issue persists, then please provide us with the log file located at `~/Library/Logs/warp.log`

**Comment by n00ki** [comment] 2024-05-01 03:39
hi @dannyneira! thanks for reaching out.
I've followed the detailed steps, yet the issue persists.
The log file is attached, as requested.
Thanks🙏
[warp.log](https://github.com/warpdotdev/Warp/files/15173199/warp.log)

**Comment by n00ki** [comment] 2024-05-04 08:40
Any ideas?🙏🏼

**Comment by dannyneira** [comment] 2024-05-06 21:37
Hi @n00ki It's not clear from the logs what the issue may be, is it possible you have an older system spes or large git repos on your machine?

**Comment by n00ki** [comment] 2024-05-07 04:32
hi @dannyneira 
as mentioned, the issue persisted after switching to an entirely new machine (clean MacOS format). no large repos, either...

**Comment by n00ki** [comment] 2024-05-12 13:43
anyone? 🤯

**Comment by dannyneira** [comment] 2024-05-13 13:40
Its unclear what the underlying reason is for your zsh taking long to startup. I suspect it may be the shell binary itself. Please run `which zsh` to find the default zsh binary, then put the result into your `Settings > Features > Session > Startup shell for new sessions > Custom` after clearing your `~/.zshrc` file.

If that doesn't help, your machine specs may be part of it. What is the Model/Specs of your Mac? The minimum requirements are macOS 10.14 or above and hardware that supports [Metal](https://support.apple.com/en-us/HT205073). But that's just to run Warp, doesn't guarantee it will run fast if the machine has lower specs.

Also is it 10-20 seconds on first launch or every single new session?

After the above changes, please fresh set of logs.

**Comment by n00ki** [comment] 2024-05-22 08:40
@dannyneira thanks again for trying to help!
followed your instructions, yet the issue persists. 
i don't believe the issue is rooted in machine specs, it's a MacBook Pro 2021 (M1 Pro - 16GB Memory).
the slow shell startup is happening on first launch and subsequent new sessions if Warp is relaunched after several minutes (probably related to session cache?). startup is fast if i launch Warp > wait for the shell to start > close Warp > immediately launch Warp again.

i really can't find a reason for this issue...

**Comment by dannyneira** [comment] 2024-05-24 22:46
Sorry about this, it's not clear the cause and I can't reproduce this. 

If you're using empty zshrc and nothing in your zprofile, etc. then Warp still loading slow maybe you could a [full uninstall](https://docs.warp.dev/help/uninstalling-warp#uninstalling-warp), including any settings/user files and [reinstall the latest](https://docs.warp.dev/getting-started/getting-started-with-warp) version.

**Comment by n00ki** [comment] 2024-06-04 06:21
@dannyneira nothing yet...
is there any chance it might be related to the VPN and security software installed by my company (GlobalProtect, Endpoint Protector and Secure Endpoint Connector)?

**Comment by dannyneira** [comment] 2024-06-04 15:57
No likely, as the delay is on loading zsh not using online features like block sharing and you can login so there shouldn't be an issue with the VPN. This may be related to the memory usage, but it's not clear. #2611

**Comment by n00ki** [comment] 2024-07-05 07:08
@dannyneira a quick update:
after battling this issue for practically months now, on both of my work computers (MBP Intel 2019 & MBP M1 2021), trying absolutely anything to debug and possibly overcome the excessive load time (to the point of formatting both machines) - i'm starting to thing this must be somehow related to some security policies enforced by the software installed by my employer.
I have verified the behavior both on my own personal MBP 2018 and my wife's MBA 2020 - the issue simply does not reproduce, even when all related config files are duplicated. 
on the other hand, it reproduces immediately and in the exact same way on both of my work machines.
while continuously trying to investigate this issue, i was able to reproduce this issue with the `fish` shell as well! same as `zsh` - both work computers suffers from an extremely long initialization time when not cached, and both personal computers work flawlessly.
something is preventing Warp from loading the shell as it should, i just don't have any idea what it might be..🤷‍♂️

**Comment by n00ki** [comment] 2024-09-22 12:54
So after 5 months of countless attempts to get to the bottom of this issue, I do have a conclusion.
The extremely slow shell initialization in Warp is indeed caused by the security software installed by my employer.
As long as **Cisco Secure Endpoint** (formerly AMP for Endpoints) is running, Warp is having a very difficult time trying to initialize the shell.

Although I wasn't fortunate enough to find a security policy that isn't interfering with Warp, I now can confirm this is in fact the actual problem.

Thanks @dannyneira for trying to help!

**Comment by sunanan** [comment] 2024-09-23 15:00
> Hi @n00ki sorry to hear about this frustrating issue. If your still seeing the zsh loadin issue, even with a clean ~/.zshrc file, it could be something with our bootstrap script, especially if this wasn't the case a month ago as you mentioned.
> 
> Please try the following:
> 
> * Run `echo 'ZDOTDIR=/' > ~/.zshenv` This forces zsh to run with zero configs.
> * Remove Warp logs with `sudo rm -r $HOME/.warp/ $HOME/Library/Logs/warp.log`
> * Remove Warp database with `sudo rm -r "$HOME/Library/Application Support/dev.warp.Warp-Stable"`
> * Quit and reopen Warp
> * If the issue persists, then please provide us with the log file located at `~/Library/Logs/warp.log`

I try this way, it works for me. Thanks a lot.

**Comment by dannyneira** [comment] 2024-09-24 16:47
@n00ki Thanks for letting us know. Closing this issue since the root cause lies with Cisco Secure Endpoint and not Warp. Please don't hesitate to reopen if you happen to see the issue persist with the other security policy in place.

**Closed by dannyneira** 2024-09-24 16:47 UTC
Labels: Bugs

**Comment by MAmmarRaza** [comment] 2025-09-30 06:24
use your linux terminal to access warp-terminal the issue resolved for me
