### ISSUE TITLE
Ability to re-order tabs

### ISSUE THREAD

**Issue by jspaceface** [warpdotdev/Warp#976] opened 2022-04-08 17:00 UTC
### Describe the solution you'd like?

```text
I would like to be able to click-and-drag the tabs to change the order.
```

**Comment by samal-rasmussen** [comment] 2022-04-11 14:55
This is such a small thing I know, but I cannot live without it, because I open and close tabs regularly and keep several tabs open, and if I cannot sort them into the usual order I have then I get lost can never find the tab I am looking for.

**Comment by tanmaypatel** [comment] 2022-04-19 11:37
This can also be enhanced further by adding the ability to rename tabs or group them by color.

**Comment by berkus** [comment] 2022-04-20 22:22
Oh yeah, would totally love to drag-n-drop tabs - reordering sessions matters.

**Comment by berkus** [comment] 2022-04-20 22:26
Btw, dupe of #58

**Comment by elviskahoro** [comment] 2022-07-08 18:32
Gonna close this in favor of #58 

Also we support keybindings and also right clicking the tabs to rearrange. drag and drop for rearrangement is still in progress

**Comment by berkus** [comment] 2024-02-01 08:39
Why this got reopened? The functionality is present.

**Closed** 2024-02-12 20:56 UTC
