### ISSUE TITLE
DUP: Duplicate of #050 - Delete blocks

### ISSUE THREAD

**Issue by ultrox** [warpdotdev/warp#46] opened 2021-07-22 05:25 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I would like to have the ability to delete the block, the reason is mostly declutering.

**Comment by gagata** [comment] 2021-07-28 23:51
thanks for the report! merging it with another task - feel free to join the discussion there! :) 

Duplicate of #50

**Closed** 2021-12-06 23:30 UTC
Labels: feature-request
