### ISSUE TITLE
Warp does not redraw screen in vim when scrolling

### ISSUE THREAD

**Issue by michbsd** [warpdotdev/Warp#2965] opened 2023-04-21 08:55 UTC
### Discord username (optional)

michbsd

### Describe the bug

Whenever I am editing files in vim - and I scroll down in the document the vim status bar in not properly redrawn and is messing up the UI. 
I have to hit "ctrl-L" to redraw every single time I scroll up or down in vim... 

![image2](https://user-images.githubusercontent.com/8202334/233591926-1752d366-8f36-4431-97a1-102bdefa65e0.png)

### To Reproduce

1. Open a file with vim
2. make sure you have a status bar configured in your vimrc
3. scroll down in your document 

### Expected behavior

I should be able to use vim without having to manually redraw the screen whenever I scroll to a new section

### Operating System

MacOS

### OS Version

13.3.1

### Shell Version

zsh 5.9

### Warp Version

v0.2023.04.11.08.03.stable_00

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-04-24 18:54
Thanks for letting us know @michbsd 
We'll post any updates on this thread.
Please :+1:  and comment if you're also seeing this issue as it helps us gauge impact.

**Comment by dannyneira** [comment] 2023-05-09 15:49
Thanks for clarifying this is only an SSH issue, I was able to reproduce this in an SSH session with no changes to default vim. We'll investigate further and post any updates on this thread.

**Comment by dannyneira** [comment] 2023-05-09 19:23
@michbsd It could possibly by one of the vim plugins you're using that's causing this issue. I used the same .vimrc file you provided without the plugins ( since I didn't have them installed ) in SSH and I wasn't seeing the same issue. I suggest you try and go thru commenting out the plugins until you find the culprit. Then, you can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

**Comment by dannyneira** [comment] 2023-05-10 15:33
Thanks for confirming, I was able to repo this one briefly, but can't anymore so it appears intermittent on my end, I'll pass some steps along to the Eng team to see if they have any luck reproducing this. Appreciate your patience while we try and get to the bottom of this.

**Comment by vorporeal** [comment] 2023-05-10 17:40
@michbsd OOC - what version of vim are you running on those machines?

**Comment by michbsd** [comment] 2023-05-10 19:19
@dannyneira 

```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 11 2023 17:16:38)
Included patches: 1-1441
Compiled by root@124amd64-default-job-08
Huge version without GUI.  Features included (+) or not (-):
```

**Comment by michbsd** [comment] 2023-05-12 06:57
Just confirming that this is still an issue with Warp v0.2023.05.09.08.03.stable_01

**Comment by ctipper** [comment] 2023-12-03 09:58
+1 for this, using vi inside an SSH session is extremely unreliable and has caused me to lose data because I didn't know the shortcut to redraw the screen. I don't know about the status line, the whole view becomes corrupted

**Comment by michbsd** [comment] 2023-12-03 13:38
Still not resolved for neither.. I think it is a pretty basic use-case that one should be able to open vim in a remote session via terminal application. I am quite frankly surprised that the Warp team are working on fancy bells and whistles instead of fixing the very basics.

**Comment by ffd114** [comment] 2024-03-17 08:55
Can confirm it still happen in `v0.2024.03.12.08.02.stable_01` on MacOS, but on my linux machine it's working correctly

**Comment by michbsd** [comment] 2024-06-07 15:17
@dannyneira can we get some eyeballs on this issue open for over a year now..

**Comment by dannyneira** [comment] 2024-06-10 15:59
Hi @michbsd quick update, we're looking into this issue further and will post as we have them. Thanks for your patience folks!

**Comment by michbsd** [comment] 2024-06-25 12:13
I switched to neovim - and the issue does to occur there.. 🤷🏼

**Comment by acarl005** [comment] 2024-07-24 14:18
I'm finally taking a look at this. Possibly related to #5166?

**Comment by acarl005** [comment] 2024-07-25 16:11
@michbsd I suspect the issue has to do with the terminfo database on your remote server. Can you run echo $TERM on your host and post the value?

**Comment by michbsd** [comment] 2024-07-25 18:34
xterm-256color

I switched to neovim, which does not exhibit the behavior

**Comment by dannyneira** [comment] 2024-07-31 19:28
Hi Folks, this has been resolved in latest version of Warp. Closing as resolved, but please update and let us know if any issues.

**Closed by dannyneira** 2024-07-31 19:28 UTC
Labels: Bugs
