### ISSUE TITLE
Lag + Graphics Gliches while running ncmpcpp

### ISSUE THREAD

**Issue by xiro-codes** [warpdotdev/Warp#4858] opened 2024-04-30 19:21 UTC
### Describe the bug

Graphical Gliches in ncmpcpp visualizer 

### To reproduce

Run ncmpcpp

### Screenshots

https://youtu.be/w572_YZz154?si=JYVCzeTn8n2TC9lv

### Operating system

Linux

### Operating system and version

Linux 6.6.21 #NixOS 

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment] 2024-05-03 13:10
Hi @xiro-codes would you mind checking if this still reproduces on the latest version of Warp? We fixed a source of rendering delays in the latest release that should fix this issue. Thank you!

**Comment by xiro-codes** [comment] 2024-05-04 05:06
lag is gone, but graphics issues still present

**Comment by alokedesai** [comment] 2024-05-04 13:17
Could you share the output of your warp logs so can debug further?

**Comment by xiro-codes** [comment] 2024-05-04 14:52
No problem but where do I find them

**Comment by alokedesai** [comment] 2024-05-06 01:04
thank you! You can find info on how to access your warp logs here: https://docs.warp.dev/help/sending-us-feedback#gathering-warp-logs

**Comment by xiro-codes** [comment] 2024-05-06 03:11
but what about linux only mentions macos

**Comment by alokedesai** [comment] 2024-05-06 16:10
There should be a Linux section as well, posting it as a screenshot here as well!

<img width="1012" alt="image" src="https://github.com/warpdotdev/Warp/assets/4110292/09cbafeb-0fa0-4a57-aea9-55fb86341401">

**Comment by dannyneira** [comment] 2024-05-31 16:00
Hi @xiro-codes I'm struggling to reproduce this issue on nixos. Can you please provide a copy of your `/etc/mpd.conf` and your `~/.ncmpcpp/config`? This will help us with reproducing the issue with ncmpcpp visualizer.

**Comment by xiro-codes** [comment] 2024-05-31 18:43
it appear to be a theme issue  as it goes away on some themes. heres my configs 
ncmpcpp
```
execute_on_song_change=notify-send -i /tmp/.music_cover.png "Playing" "$(mpc --format '%title% - %album%' current)"
mpd_music_dir=/mnt/hdd/music
visualizer_data_source=/tmp/mpd.fifo
visualizer_in_stereo=yes
visualizer_look=+|
visualizer_output_name=visualizer
visualizer_type=spectrum
```
mpd
```
        audio_output {
          type "pipewire"
          name "Pipewire"
        }
        audio_output {
          type "fifo"
          name "Visualizer"
          path "/tmp/mpd.fifo"
          format "44100:16:2"
        }
```

**Comment by dannyneira** [comment] 2024-07-25 20:52
Thanks for letting us know @xiro-codes In some cases. Since you found the issue was with the ncmpcpp theme, we'll close this for now but please let us know if any related issues with the app.

**Closed by dannyneira** 2024-07-25 20:52 UTC
Labels: Bugs
