### ISSUE TITLE
Scrollable tmux panes

### ISSUE THREAD

**Issue by walkerjian** [warpdotdev/Warp#4681] opened 2024-04-03 01:27 UTC
### Describe the solution you'd like?

So I have set warp up 
sudo tmux
tmux split-window -h
tmux split-window -h (after clicking back into pane 1)
pane 1) sudo nettop -m tcp
pane 2) sudo nettop -m udp
pane 4) sudo bpytop

those sudo's are unnecessary but muscle memory:)

the issue I have is that the nettop panes are not appearing to scroll when I mouse gesture on them (iMac)

is this a thing?

### Is your feature request related to a problem? Please describe.

I don't know enough to ask the right questions :)

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-03 19:28
Hi @walkerjian Sorry about this but Warp doesn't yet have full tmux support, which we are tracking here #501. afaik scrolling with the mouse wheel is supported, but currently, it scrolls thru the command history in tmux instead of scrolling thru the pane as expected.

We'll be closing this as a duplicate of the other issue and post updates on that thread.

**Comment by dannyneira** [comment] 2024-04-03 19:28
Duplicate of #501

**Closed by dannyneira** 2024-04-03 19:28 UTC
Labels: enhancement
