### ISSUE TITLE
Key repeat only kinda works?

### ISSUE THREAD

**Issue by sdhull** [warpdotdev/Warp#3195] opened 2023-06-09 18:59 UTC
### Describe the bug

Not sure if this is configurable or not (I searched from the help menu and didn't find any settings for it), but key repeat appears to be disabled in Warp. It works for deleting text but not for pressing keys.

To repro:

### To reproduce

Just open a terminal and hold down a letter (`j` for example). You'll notice only a single "j" appears. This is particularly annoying while using `less` as I frequently press and hold `j` to scroll down. Bizarrely, it works fine in `vim`.

### Expected behavior

Pressing and holding a character should input that character at whatever rate was set at the OS-level settings.

### Operating system

MacOS

### Operating system and version

13.4.0

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.06.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-06-09 21:25
Hey @sdhull not 100% sure, but this may be an issue with a [mac setting](https://github.com/warpdotdev/Warp/issues/3184) run the following and restart Warp to see if that helps with the issue.

`defaults write -g ApplePressAndHoldEnabled -bool false`

**Comment by vogler** [comment] 2023-06-12 07:13
Duplicate of #3191.

**Closed** 2023-06-14 16:14 UTC
Labels: Bug
