### ISSUE TITLE
Remove Block

### ISSUE THREAD

**Issue by Qusea** [warpdotdev/Warp#3955] opened 2023-12-10 04:50 UTC
### Describe the solution you'd like?

```Text
Sometimes I make a mistake in a command, and when that happens, I would like to be able to remove the block from my current session and the history.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-12-11 22:29
Hey @Qusea, thanks for submitting! As a workaround, you can delete all the blocks in a current session with `CMD-K`, but for deleting just one Block, there is a request we're tracking there on here #50.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2023-12-11 22:29
Duplicate of #50

**Closed by dannyneira** 2023-12-11 22:29 UTC
Labels: enhancement
