### ISSUE TITLE
Session Logging

### ISSUE THREAD

**Issue by oceans1908** [warpdotdev/Warp#2394] opened 2022-12-22 12:21 UTC
### Describe the solution you'd like?

```text
As a system admin, it would be handy if all my sessions will be logged into a file. So that I can always get back to output that is no longer available in the current session. 

So a log file per session, as a configurable option within WARP.
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2022-12-22 17:28
Thanks @oceans1908! This sounds a bit like an infinite history idea that's been bounced around. 

Please :+1: and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by dannyneira** [comment] 2024-07-03 22:28
Hey folks, closing in favor of https://github.com/warpdotdev/Warp/issues/4833

**Comment by dannyneira** [comment] 2024-07-03 22:28
duplicate of https://github.com/warpdotdev/Warp/issues/4833

**Closed by dannyneira** 2024-07-03 22:28 UTC
Labels: Feature requests
