### ISSUE TITLE
DUP: Duplicate of #472 - IDE support

### ISSUE THREAD

**Issue by jmezzeragp** [warpdotdev/Warp#829] opened 2022-03-22 14:54 UTC
### Describe the solution you'd like?

```text
Is there a way to integrate the terminal to IDEs terminal sections?
```

### Is your feature request related to a problem? Please describe.

```text
Really liked your software, however I'm used to use terminals from within the IDE (JetBrains in my case)
```

**Comment by elviskahoro** [comment] 2022-03-22 17:31
Duplicate of:
- #427

**Closed by elviskahoro** 2022-03-22 17:31 UTC
