### ISSUE TITLE
Launcher Suggestion: Launching should replace the same window or with Cmd + Enter open a new window

### ISSUE THREAD

**Issue by cinco-de-mauro** [warpdotdev/Warp#4055] opened 2024-01-11 18:45 UTC
### Describe the solution you'd like?

Switching to a new "launch configurations" could be done faster.

If you're in a project and want to switch to a different one. Currently the launcher opens in a new window, then you have to switch back to the previous window to close it. If, by default, the launcher replaced the current window, closing the previous one wouldn't be necessary. Also, allowing the option to Cmd+Enter to open in a new window would allow users to open a new project without closing the previous one.

Visual Studio ctrl+r (launching workspaces) does this really well. Just selecting a workspace will replace the current window, or using Cmd+Enter will open in a new window.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-11 22:32
Hey @cinco-de-mauro Thanks for taking the time to submit this request. We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2490

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-11 22:32
Duplicate of https://github.com/warpdotdev/Warp/issues/2490

**Closed by dannyneira** 2024-01-11 22:32 UTC
Labels: Feature

**Comment by cinco-de-mauro** [comment] 2024-01-19 14:47
> Hey @cinco-de-mauro Thanks for taking the time to submit this request. We already have a request tracking this over at #2490
> 
> If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!
> 
> We'll be closing this as a duplicate.

Done and thank you!
