### ISSUE TITLE
zsh support: bindkey not working

### ISSUE THREAD

**Issue by mskar** [warpdotdev/Warp#2169] opened 2022-11-17 20:41 UTC
### Describe the bug

Warp does not respect my vi-insert-mode zsh keybindings.
The keybindings below work perfectly in iTerm and Terminal.
Here is the link to my .zshrc:  https://github.com/mskar/setup/blob/main/.zshrc
```
bindkey -v
bindkey -M menuselect '^o' accept-and-infer-next-history
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M viins "^['" quote-line
bindkey -M viins "^[^e" globalias
bindkey -M viins '^ ' set-mark-command
bindkey -M viins '^/' undo
bindkey -M viins '^["' quote-region
bindkey -M viins '^[-' neg-argument
bindkey -M viins '^[.' insert-last-word
bindkey -M viins '^[<' beginning-of-buffer-or-history
bindkey -M viins '^[>' end-of-buffer-or-history
bindkey -M viins '^[^h' backward-kill-word
bindkey -M viins '^[b' backward-word
bindkey -M viins '^[c' capitalize-word
bindkey -M viins '^[d' kill-word
bindkey -M viins '^[f' forward-word
bindkey -M viins '^[h' kill-region
bindkey -M viins '^[l' down-case-word
bindkey -M viins '^[n' history-search-forward
bindkey -M viins '^[p' history-search-backward
bindkey -M viins '^[t' transpose-words
bindkey -M viins '^[u' up-case-word
bindkey -M viins '^[w' copy-region-as-kill
bindkey -M viins '^[x' execute-named-cmd
bindkey -M viins '^[y' yank-pop
bindkey -M viins '^_' undo
bindkey -M viins '^a' beginning-of-line
bindkey -M viins '^b' backward-char
bindkey -M viins '^d' delete-char
bindkey -M viins '^e' end-of-line
bindkey -M viins '^f' forward-char
bindkey -M viins '^g' send-break
bindkey -M viins '^h' backward-delete-char
bindkey -M viins '^k' kill-line
bindkey -M viins '^n' down-history
bindkey -M viins '^o' accept-line-and-down-history
bindkey -M viins '^p' up-history
bindkey -M viins '^r' fzf-history-widget
bindkey -M viins '^t' transpose-chars
bindkey -M viins '^u' backward-kill-line
bindkey -M viins '^w' backward-kill-word
bindkey -M viins '^x^a' fasd-complete
bindkey -M viins '^x^b' vi-match-bracket
bindkey -M viins '^x^d' fasd-complete-d
bindkey -M viins '^x^e' edit-command-line
bindkey -M viins '^x^f' fasd-complete-f
bindkey -M viins '^x^j' fzf-cd-widget
bindkey -M viins '^x^s' fzf-file-widget
bindkey -M viins '^x^u' undo
bindkey -M viins '^x^x' exchange-point-and-mark
bindkey -M viins '^xa' fasd-complete
bindkey -M viins '^xb' vi-match-bracket
bindkey -M viins '^xd' fasd-complete-d
bindkey -M viins '^xe' edit-command-line
bindkey -M viins '^xf' fasd-complete-f
bindkey -M viins '^xj' fzf-cd-widget
bindkey -M viins '^xs' fzf-file-widget
bindkey -M viins '^xu' undo
bindkey -M viins '^xx' exchange-point-and-mark
bindkey -M viins '^y' yank
bindkey -M viins "∫" backward-word
bindkey -M viins "ƒ" forward-word
bindkey -M viins "∂" delete-word
bindkey -M viins '˙' backward-kill-word
bindkey -M viins '≥' insert-last-word
```

### To Reproduce

Start zsh, source the .zshrc, try to use any of the vi-insert-mode zsh keybindings in the .zshrc. The only ones that work are ctrl-b, ctrl-f, ctrl-d, and ctrl-h.

### Expected behaviour

The vi-insert-mode zsh keybindings in the .zshrc work as expected.

### OS Version

12.6.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin21.3.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by nichoj10** [comment] 2022-11-17 21:00
Thanks for filing this! We currently don't support bindkeys and have been monitoring the issue here: https://github.com/warpdotdev/Warp/issues/537. You can +1 it to help us gauge interest and prioritization.

Duplicate of #537.

**Comment by dannyneira** [comment] 2022-11-17 21:05
Closing as dup of #537

**Closed by dannyneira** 2022-11-17 21:05 UTC
