### ISSUE TITLE
Linux - Cut All Left keyboard shortcut does not appear to do anything

### ISSUE THREAD

**Issue by terrymunro** [warpdotdev/Warp#4567] opened 2024-03-16 04:31 UTC
### Describe the bug

The `Cut All Left` keyboard shortcut does not appear to do anything when pressed.

I wanted to unbind `Ctrl+U` from `Copy and Clear Selected Lines` and bind it to `Cut All Left`, but I also tried other bindings to no avail.

### To reproduce

1. Open settings
2. Navigate to Keyboard shortcuts
3. Search the commands for "Cut All Left"
4. Bind to `<unused-keybind>` (or Ctrl + U, and unbind it from "Copy and Clear Selected Lines")
5. Close settings
6. Type some characters at terminal prompt
7. Move cursor left (To ensure its only removing characters from the left rather than whole line)
8. Press bound key

### Expected behavior

All characters left of the cursor should be cut/deleted.

### Operating system

Linux

### Operating system and version

Fedora 39

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.03.12.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

I'm using X11 and I have the following in my `.zshrc`:

```zsh
bindkey \^u backward-kill-line
```

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-20 17:21
Hi Terry, Warp doesn't support bindkeys in your rc file yet, but we are tracking that here #537 

As a possible workaround, checkout the vim keybindings in the input editor https://docs.warp.dev/features/editor/vim, it has a lot of advanced features that may be helpful.

Hope this helps! closing as duplicate of bindkey support so please track this there.

**Closed** 2024-03-20 17:22 UTC
Labels: Bugs

**Comment by terrymunro** [comment] 2024-03-29 03:26
Sorry I didn't respond sooner.

This bug report was _not_ about bindings in RC file, that was only 'additional context'. I'm happy to remove that part if it's distracting?

The report was about binding in Warp itself, I assumed that was clear due to the reproduction steps, but my mistake if it wasn't clear.

![Example](https://github.com/warpdotdev/Warp/assets/2586778/7a7f9659-5e25-43c1-8b83-3e6e98194694)

**Comment by terrymunro** [comment] 2024-03-29 04:07
If it helps, here's what I mean...

[demo.webm](https://github.com/warpdotdev/Warp/assets/2586778/fea89804-5a64-4d3a-abfe-443041759aaa)

**Comment by terrymunro** [comment] 2024-04-12 00:16
:disappointed: issue still exists in: v0.2024.04.09.08.01.stable_01

**Comment by ahuigo** [comment] 2025-12-28 10:46
issue still exists in:  `v0.2025.09.17.08.11.stable_02`
