### ISSUE TITLE
dock icon bounces when other terminals would beep

### ISSUE THREAD

**Issue by GallagherCommaJack** [warpdotdev/Warp#1932] opened 2022-10-07 17:15 UTC
### Describe the bug

when eg pressing tab with no valid autocompletions, the dock icon will start to bounce and won't stop until I click on it, which usually creates a new window. this is an incredibly annoying visual nuisance, especially for more keyboard-driven workflows.

### To Reproduce

open a new window
type `asdfasdfasdfaasdfasdfasdff` (or any other string which won't have valid autocompletions)
hit `<TAB>`

### Expected behaviour

either terminal beeps or nothing happens

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

### Warp Version

v0.2022.09.27.08.11.stable_00

### Does this block you from using Warp daily?

No

**Comment by mcouthon** [comment] 2022-10-25 14:35
My icon is bouncing uncontrollably when I'm not even in the terminal 🤷

**Comment by paulcruse-syn** [comment] 2022-11-18 22:13
I second this... very annoying

**Comment by olliekabi** [comment] 2022-11-21 13:09
I found this also happens when scrolling too far inside an editor like vim, along with the scenarios already highlighted. Particularly annoying when it happens when not even using the terminal.

This makes the app unusable, it's too distracting

**Comment by paulcruse-syn** [comment] 2022-11-21 16:51
@olliekabi the work around I found was here: https://www.switchingtomac.com/tutorials/how-to-permanently-stop-dock-icons-from-bouncing/

But I also ran this command in my terminal (which is also in the link list above): 

```
defaults write com.apple.dock no-bouncing -bool FALSE;
```

**Comment by benje** [comment] 2022-12-14 17:56
+1 I also find this extremely annoying. I find the Dock icon bounces even when there are no new terminal events. It is really distracting and the only way to solve it is to click the Dock icon which launches a new window.. (I use the global hotkey window)

**Comment by arabyalhomsi** [comment] 2022-12-15 13:55
+1 absolutely! please fix this

**Comment by SevkiBekir** [comment] 2022-12-19 12:00
+1

**Comment by kayleg** [comment] 2022-12-28 15:25
+1

**Comment by mmackowiak** [comment] 2023-01-23 18:03
+1, indeed, very annoying. Makes you anxious when close to the end of diff or file in vim. 🙈

**Comment by derlin** [comment] 2023-02-08 08:06
This makes me crazy!!!! Please fix it until I lose my nerves, uninstall warp and throw my computer out the window ;)

**Comment by pyronaur** [comment] 2023-02-12 17:10
Please fix this! 😭

**Comment by Mariano89** [comment] 2023-02-14 19:10
+1, very distracting. Thinking of going back to iTerm because of this 🤷‍♂️

**Comment by dannyneira** [comment] 2023-02-14 21:38
Thanks for all the feedback on this folks! I'll bring it up with the team and we'll post any updates on this thread. In the meantime, if anyone else is interested in this, please 👍  the issue as it helps us gauge the impact.

**Comment by dannyneira** [comment] 2023-02-22 18:37
Hey @GallagherCommaJack @Mariano89 @pyronaur , We can't seem to replicate the issue on our end. Even tried the [listed workaround](https://www.switchingtomac.com/tutorials/how-to-permanently-stop-dock-icons-from-bouncing/) and enabled/disabled the animation in the Mac settings. 

Is it possible to get a video of the behavior happening on your machine? Trying to get a better idea of what may trigger the bounce.

**Comment by mnapoli** [comment] 2023-02-23 12:46
@dannyneira this is not a workaround! It disables bouncing animation for ALL apps on the Mac. Warp needs to be fixed instead of breaking an OS globally on the system.

I personally cannot reproduce it reliably, it's random, but it happens very very regularly and completely breaks the flow.

**Comment by mmackowiak** [comment] 2023-02-27 16:10
For me, it's 100% reproducible in such way:
1. Open hotkey window (never tried in regular window, using hotkey one exclusively)
2. `git diff` with output longer than window height (so not all output is immediately visible, one needs to scroll to the bottom)
3. Scroll to the bottom of that diff
4. Warp icon in dock will start bouncing once you reach bottom

**Comment by kanzelsberger** [comment] 2023-03-12 15:38
Any news on this? This was reported more than 5 months ago and is still present.

**Comment by arabyalhomsi** [comment] 2023-03-13 15:26
PLEASE STOP JUMPING

**Comment by injust** [comment] 2023-03-13 21:08
I ran into this when trying to use `watch -b`, but the terminal doesn't beep. Instead, if the window is unfocused when the "beep" happens, the icon will bounce in the dock.

So isn't this just a really bad feature, instead of a bug? Should be easily reproducible by running `sleep 1 && tput bel` and then immediately focusing on another window.

**Comment by thecodewarrior** [comment] 2023-03-23 18:50
The dock bouncing should probably be an option, but it definitely shouldn't occur when the hotkey window is focused. 

The behavior I've observed is that if a bell is received and warp isn't the currently focused app, the icon will start bouncing. This makes some amount of sense, however "the hotkey window being open" isn't being counted as warp being the currently open app, so if something in the hotkey window triggers a bell, the app icon will start bouncing and you'll have to ⌘-tab all the way over to warp just to make it shut up.

Regardless, the app icon bouncing should be an option, since some users may not want the effect. 

Reproduction steps:
- Non-hotkey window:
  - Run `sleep 5 && tput bel` 
  - ⌘-tab into another application and wait for the bell to be printed
    - (switching to another window in warp won't cause the icon to bounce, it has to be a different application)
- Hotkey window:
  - Have the focus on a another application
  - Open the hotkey window
  - Run `tput bel`
    - (opening the hotkey window when warp is the currently focused app won't cause the icon to bounce)

**Comment by shynsky** [comment] 2023-04-01 07:31
> video

thecodewarrior already explained it, but here's the visual representation: 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/629679/229272235-524543da-997e-4509-b89a-2b0a476ab3a9.gif)

**Comment by shynsky** [comment] 2023-04-01 07:36
@thecodewarrior explained it, here's the visual representation of the behavior when reaching end of the file in vim:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/629679/229272478-a819303e-498a-4f06-a5a6-01d4c2e1ff72.gif)

**Comment by shynsky** [comment] 2023-04-06 12:28
> Is there an easy fix for this where you can just tell Mac to _never_ bounce this app in the dock? One of the most annoying bugs right now

You can disable bouncing but only for all the apps, which isn't good solution 😵‍💫 
`defaults write com.apple.dock no-bouncing -bool TRUE`

**Comment by jameslkingsley** [comment] 2023-04-06 13:02
Ah perfect, thanks

**Comment by dsernst** [comment] 2023-04-12 10:24
Yea, this comes up about once every 15 minutes for me. Infuriating

Here's a screen recording:

![Screen Recording 2023-04-12 at 1 20 26 PM-2](https://user-images.githubusercontent.com/6340841/231430201-a5e5baa4-d0fa-4162-a263-d77648b6b46d.gif)

**Comment by ephemer** [comment] 2023-04-14 12:59
I have the same issue with the Dock bouncing when using the hotkey window. It keeps bouncing forever even if I'm in the terminal window actively doing something. It drives me nuts.

**Also,** if I click on the bouncing icon, a new random terminal window comes up!!! Even if the hotkey window is already active. That is truly infuriating UX. Please fix this

**Comment by bainch** [comment] 2023-04-24 11:33
Today I once again gave Warp a shot to replace iTerm2... almost non-stop bouncing of the dock icon. So yes, please for the love of god fix this! (Also using hot-key windows exclusively).

**Comment by Ugenx** [comment] 2023-05-09 16:38
+1 exclusive hotkey window user here experiencing this exact problem. Really considering going back to iterm until this is fixed as this is a constant nuisance.

**Comment by dsernst** [comment] 2023-05-09 19:00
@Ugenx This fix from https://github.com/warpdotdev/Warp/issues/1932#issuecomment-1498985493 above worked for me, haven't thought about the problem for the last month anymore:

`defaults write com.apple.dock no-bouncing -bool TRUE`

**Comment by vorporeal** [comment] 2023-05-09 21:42
We're working on changing this over to a visual bell indicator in tab titles and an optional audible beep!  No concrete date yet, but soon!

**Comment by dannyneira** [comment] 2023-06-23 20:32
As mentioned above, Warp [v0.2023.05.09.08.03](https://docs.warp.dev/getting-started/changelog#2023.05.11-v0.2023.05.09.08.03) and above has the option to enable (disabled by default) an audible terminal bell (Settings > Features > Terminal or “Enable/Disable Audible Terminal Bell” within the Command Palette)

**Comment by Delvien** [comment] 2023-06-25 13:02
This happens to me without bells on any terminal. 

I do not think they are related. 

Mine happens 100% of the time updates are pushed.

**Comment by terodox** [comment] 2023-06-26 13:53
Even with "Enable Audible Terminal Bell" the icon continues to bounce intermittently, even if the terminal is not doing anything. 

This is super distracting, and pushing me to the edge of uninstalling. 

Any ideas how I can just disable the bounce all together?

**Comment by sunaurus** [comment] 2023-07-17 13:20
Has anybody found any workarounds *other than completely disabling bouncing for all apps*? I'm starting to feel like the interruptions from empty terminals bouncing at me must have caused me days of lost productivity at this point 😅

**Comment by Delvien** [comment] 2023-07-17 13:49
> Has anybody discovered any better workarounds than completely disabling bouncing for all apps? I'm starting to feel like the interruptions from empty terminals bouncing at me must have caused me **days** worth of lost productivity at this point 😅

The only thing to be done is for Warp to fix it.

**Comment by danielfstefan** [comment] 2023-07-17 16:24
This hasn't been bugging me for a while, every since instead of using the Hotkey window, I decided to change to a regular window, and the Global hotkey is set to Show/Hide all windows - I'm generally using only 1 window with multiple tabs anyway. So it's pretty much the same behavior of the Hotkey Window, without the dreadful bouncing issue 
<img width="688" alt="image" src="https://github.com/warpdotdev/Warp/assets/979692/fd510302-15f7-448d-ae7a-11ef01ffd80a">

**Comment by KingMob** [comment] 2023-09-01 05:26
I see that #2384 was closed as a duplicate. The issues seem related (dock bouncing), but are we certain that's actually true?

For example, I've _never_ encountered this issue (#1932), but I deal with #2384 every day.

**Comment by vorporeal** [comment] 2023-09-01 15:50
@KingMob With yesterday's release, the dock icon only bounces once instead of bouncing until the app is brought into focus.  That should effectively fix #2384 and hopefully largely addresses this issue.

Given that the dock icon now bounces only once in response to a bell, and there is an option to turn on an audible bell, are there other terminal bell issues that we're overlooking and should track here?

**Comment by KingMob** [comment] 2023-09-02 09:22
@vorporeal As of v0.2023.08.29.08.04.stable_00 it looks like the bouncing has stopped entirely. I still get a notification in the Notification Center, but that quickly fades away. Perfect!

**Comment by dannyneira** [comment] 2023-09-12 16:19
@GallagherCommaJack and other folks on this thread.

We're closing this issue as resolved given that the dock icon now bounces only once in response to a bell, and there is an option to turn on an audible bell.https://docs.warp.dev/features/notifications#audible-bell

Feel free to let us know if any other related issues come up.

**Closed by dannyneira** 2023-09-12 16:19 UTC
Labels: Bug
