### ISSUE TITLE
Ability to delete a block

### ISSUE THREAD

**Issue by Integralist** [warpdotdev/Warp#3246] opened 2023-06-23 13:02 UTC
### Describe the solution you'd like?

```Text
There are times when I'm testing out a command, and one of the command executions might not work how I expect it, but I intended to take a screenshot of multiple blocks because I need to share them with someone else. It's at this point I'd like to be able to delete the block that I don't want to include because it happened in the middle of a bunch of other commands I did want to share in my screenshot (and I don't want to send two separate screenshots or have to repeat executing each command again).
```

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-06-23 16:56
Thanks for submitting this @Integralist 

We already have a request tracking this over at #50, It's one of the earliest requests we've had.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Closed by dannyneira** 2023-06-23 16:56 UTC
Labels: Feature

**Comment by dannyneira** [comment] 2023-12-11 22:29
Duplicate of #50
