### ISSUE TITLE
kubectl auto-complete with zsh not working, only suggesting possible flags

### ISSUE THREAD

**Issue by ryanhristovski** [warpdotdev/Warp#4043] opened 2024-01-09 17:21 UTC
### Describe the bug

I have `kubectl` auto-complete working on iterm2 but can't seem to get it working with Warp. It currently only shows possible flags instead of resources/resource types.

### To reproduce

1. Remove all zsh config (`~/.zshrc` is empty)
2. Run a fresh installation of Warp:
```
brew uninstall warp
defaults delete dev.warp.Warp-Stable
sudo rm -r $HOME/.warp/ $HOME/Library/Logs/warp.log
sudo rm -r "$HOME/Library/Application Support/dev.warp.Warp-Stable"
brew install warp
```
3. Setup `kubectl` auto-complete
```
autoload -Uz compinit
compinit
source <(kubectl completion zsh)
```

### Expected behavior

In the example, a list of possible namespaces should be listed. 

### Screenshots

<img width="500" alt="image" src="https://github.com/warpdotdev/Warp/assets/61257223/b956b8a0-6374-4de3-b823-20cb79fbab15">

### Operating system

MacOS

### Operating system and version

macOS Sonoma 14.2.1

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2024.01.02.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-11 17:45
Hey @ryanhristovski thanks for submitting. This is a known issue with Warp's lack of support for Shell-based completions. Since Warp has built a wrapper around the shell, completions are done on the terminal level, not the shell. 

That being said, we recently implemented the k8s context in the prompt so completions should work for your setup. Please see my example below:

![CleanShot 2024-01-11 at 10 33 51](https://github.com/warpdotdev/Warp/assets/16809145/f40faa44-fb59-44a8-8e58-ff913735d617)

We have a list of incompatible tools here which includes shell completions like compdef/compinit: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

We already have a request tracking this over at #434. We'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-11 17:45
Duplicate of #434

**Closed by dannyneira** 2024-01-11 17:45 UTC
Labels: Bug

**Comment by ryanhristovski** [comment] 2024-01-11 22:31
@dannyneira thanks, this gave me a clue of how to fix. Turns out I wasn't assuming an `AWS_PROFILE` in my kubeconfig so the prompt didn't know how to access my private EKS cluster.

**Comment by dannyneira** [comment] 2024-01-11 22:55
Nice, good catch I'll note that in our docs that Warp respects kubeconfig
