### ISSUE TITLE
Have to click twice if window isn't focused

### ISSUE THREAD

**Issue by WoodyWoodsta** [warpdotdev/Warp#3987] opened 2023-12-19 09:13 UTC
### Discord username (optional)

woodywoodsta

### Describe the bug

If the Warp window is not focused, clicking something in the window (like a tab, or pane) does not do anything, except focus the window. Then a second click on the UI element is required to effect a click, once the window has focus.

This is particularly annoying because it seems to be a different behaviour from all other apps.

### To reproduce

- Blur Warp window focus
- Attempt to click on the settings button
  - Observe only the window focuses
- Attempt to click on the settings button again
  - Now the button the clicked

### Expected behavior

Even if the window is unfocused, the first click to should be producing a click, as well as focusing the window.

### Screenshots

https://github.com/warpdotdev/Warp/assets/8268040/c5e83cf1-a4d7-4a38-9b18-228bc7c1a0ff

### Operating system

MacOS

### Operating system and version

14.2 (23C64)

### Current Warp version

v0.2023.12.12.08.02.stable_04

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2023-12-19 22:44
Hey @WoodyWoodsta This is a known issue with a focusing pane/tab/buttons based on click location when foregrounding in Warp. Thanks for submitting this. 

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/739 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2023-12-19 22:44
Duplicate of https://github.com/warpdotdev/Warp/issues/739

**Closed by dannyneira** 2023-12-19 22:44 UTC
Labels: Bug
