### ISSUE TITLE
The application is completely stuck

### ISSUE THREAD

**Issue by kaponi1** [warpdotdev/Warp#5031] opened 2024-06-16 08:39 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

looks like the app get stuck ( 
the app is stuck need todo a force quit 

### To reproduce

maily after the laptop is going back from sleep 

### Expected behavior

just to work without foce quit every x times 

### Screenshots

don't see noting showed a deferent window

### Operating system

MacOS

### Operating system and version

14.5.0

### Current Warp version

v0.2024.06.11.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

2004-05

### Additional context

z

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment] 2024-06-16 19:42
Hi @kaponi1. Apologies for the issues you're seeing here. Any chance the application was fullscreen when this occurred? If so, we should have a fix for this that is coming out in our next release.

**Comment by dpinol** [comment] 2024-07-31 07:47
I have a similar issue on ubuntu 24.04. When resuming from sleep, it usually gets 100% CPU forever
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
 321364 dani      20   0 7818944 316276 194792 R 100.0   1.0  26:44.35 warp-terminal 

```
Version: v0.2024.07.23.08.02.stable_01

**Comment by alokedesai** [comment] 2024-07-31 13:31
@dpinol I'm 99% sure the issue you're seeing is a dupe of https://github.com/warpdotdev/Warp/issues/5031. 

The issue here is Mac specific that has since been fixed (going to close it out to avoid confusion)

**Closed by alokedesai** 2024-07-31 13:31 UTC
Labels: Bugs
