### ISSUE TITLE
not showing my PS1 correctly

### ISSUE THREAD

**Issue by tpak** [warpdotdev/Warp#4054] opened 2024-01-10 18:35 UTC
### Describe the bug

I use a combo of zim and powerlevel10k and my existing PS1 prompt is not honored correctly
My existing PS1:
<img width="839" alt="Screenshot 2024-01-10 at 11 19 54 AM" src="https://github.com/warpdotdev/Warp/assets/21483/17d5ea8b-5ce2-4fd1-917b-c294cd2dbdd1">

What Warp setup shows me:
<img width="1013" alt="Screenshot 2024-01-10 at 11 20 13 AM" src="https://github.com/warpdotdev/Warp/assets/21483/791b384e-0bd0-4546-be77-1517f246674e">

### To reproduce

here are my .zimrc and .p10k.zsh 
[p10k.zsh.txt](https://github.com/warpdotdev/Warp/files/13891507/p10k.zsh.txt)
[zimrc.txt](https://github.com/warpdotdev/Warp/files/13891511/zimrc.txt)

### Expected behavior

prompt and icons from the supported and recommended font set for p10k should display correctly

### Screenshots

Added them above.

### Operating system

MacOS

### Operating system and version

Sonoma 14.2.1

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Current Warp version

v0.2024.01.02.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

n/a this is day 1

### Additional context

I looked in the FAQ and see the support levels for p10k and that there are some issues, it is not clear to me if this is one of them or not

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by tpak** [comment] 2024-01-10 18:35
also, FYI, restarting Warp after the initial config makes no difference

**Comment by dannyneira** [comment] 2024-01-10 20:49
hey @tpak From your description and images, it appears the issue is that you're not seeing the input in the same line as the prompt. This is a known issue, and we already have a request tracking this over at #2304 

We're actively working on it and we'll post any updates there, so stay tuned!

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-10 20:49
Duplicate of #2304

**Closed by dannyneira** 2024-01-10 20:49 UTC
Labels: Bug

**Comment by dannyneira** [comment] 2024-01-11 16:39
@tpak Thanks for clearing that up. As far as I'm aware, a [Nerd Font](https://www.nerdfonts.com/) (with icons) should be set up in Warp's [Settings > Appearance > Text](https://docs.warp.dev/appearance/text-fonts-cursor#text-and-fonts) first, then restart Warp to clear the font cache and try p10k again. That may be the issue you're having with the lack of icons in your prompt. Please see the setup guide in our [docs](https://docs.warp.dev/appearance/prompt#powerlevel10k).

For example, see my p10k prompt in Warp with the default "Hack" font:

![CleanShot 2024-01-11 at 09 34 22](https://github.com/warpdotdev/Warp/assets/16809145/45673c19-f6a6-416b-b32c-f920107aff64)

Below is the same p10k prompt with the "Hack Nerd Font" (the one with the icons built-in):

![CleanShot 2024-01-11 at 09 35 37](https://github.com/warpdotdev/Warp/assets/16809145/c39df43c-4446-4924-9173-0cddd21d6a53)

Please let me know if this helps.

**Comment by tpak** [comment] 2024-01-11 17:07
@dannyneira, thanks for that - revisiting fonts I had accidentally selected Meslo LGS DZ not MesloLGS NF which is the nerd variant I have - I'll also have to check out the  Hack variant

apologies for the extra work for you!

**Comment by dannyneira** [comment] 2024-01-11 18:19
No worries, happy to help :) hopefully, that'll get you up and running with the icons in your prompt
