### ISSUE TITLE
Highlighting text with a block 

### ISSUE THREAD

**Issue by san-msdata** [warpdotdev/Warp#4184] opened 2024-02-16 07:36 UTC
### Describe the solution you'd like?

So that text can be highlighted in a block

![Screenshot 2024-02-16](https://github.com/warpdotdev/Warp/assets/59726367/33cd6bbe-19a6-43ba-8842-617e05906f79)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-16 17:23
Thanks for submitting this @san-msdata 

We already have a request tracking this over at #1244

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-16 17:24
Duplicate of https://github.com/warpdotdev/Warp/issues/1244

**Comment by san-msdata** [comment] 2024-02-19 09:56
Thanks a lot. I'll be looking forward to this feature

**Closed** 2024-02-29 21:44 UTC
Labels: Feature requests
