### ISSUE TITLE
tail with follow option enabled in a ssh session

### ISSUE THREAD

**Issue by huwylphimet** [warpdotdev/Warp#5069] opened 2024-06-26 20:12 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

When using the `tail` command with the follow option (`-f`) enabled, the new lines appears live. When I start scrolling up, the lines are still refreshed and I constantly have to scroll up again once new lines appears.  
I would like that, when scrolling back in my log, while it is actively adding new lines, to not move the current line position I initially scrolled to.

### Is your feature request related to a problem? Please describe.

I cannot analyse logs with `tail -f` commands because my scroll position is constantly updated with new lines

### Additional context

This behaviour appears in an ssh session.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-06-26 20:43
Hi @huwylphimet Thanks for submitting this request. We are tracking this request for unlimited scrollback which is the underlying reason for the lack of being able to pause logs. https://github.com/warpdotdev/Warp/issues/610

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-26 20:43
Duplicate of https://github.com/warpdotdev/Warp/issues/610

**Closed by dannyneira** 2024-06-26 20:43 UTC
Labels: Feature requests

**Comment by huwylphimet** [comment] 2024-06-27 06:42
Not sure #610 will solve this issue. Also #610 seems to be about number of lines limit. In this issue it is about:  
when I scroll up to read the output of a long-running process, and that process outputs new lines of text, then my scroll position adjusts (as if I scrolled down); INSTEAD, I would expect my scroll position to remain static (so I can read the output).
