### ISSUE TITLE
Dropdown menu are scrolled outside of Settings window

### ISSUE THREAD

**Issue by aloworld** [warpdotdev/Warp#2897] opened 2023-04-07 08:10 UTC
### Describe the bug

This behaviour can best be seen for the "Default App" dropdown on Features tab of the Settings window:
After scrolling down on this page, the dropdown continues going upward and outside of the Settings window.

### To Reproduce

On Mac:
1. Go to '**Warp**' menu. 
2. Hover over 'Settings... >' and click on 'Settings'
3. Select 'Features' tab on the left-hand side of the 'Settings Window'
4. Find 'Default App' dropdown
5. Expand 'Default App' dropdown
6. Leave it as is
7. Scroll all the way down

### Expected behavior

Dropdown should disappear from view

### Screenshots

![DropdownIssue](https://user-images.githubusercontent.com/49758289/230569785-073efeb3-a7cb-48c3-ac55-b5c6e4ea7ffa.png)

### Operating System

MacOS

### OS Version

13.3

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.04.08.03.stable_01

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

It think so yes.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-04-07 18:52
Oof! Thanks for letting us know @aloworld, I appreciate the detailed reproduction steps as well! I'll bring this up with the team and let them know about this issue.

As a workaround, you can not scroll while you have the menu open. We'll post any updates to this issue on the thread.

**Comment by dannyneira** [comment] 2023-08-11 17:55
Closing as resolved since this issue has been fixed in latest versions of Warp.

**Closed by dannyneira** 2023-08-11 17:55 UTC
Labels: Bug
