### ISSUE TITLE
Warp prompt no longer shows python virtual environment

### ISSUE THREAD

**Issue by marcosfelt** [warpdotdev/Warp#3140] opened 2023-05-28 13:17 UTC
### Describe the bug

Previously, warp would show the currently activated python virtual environment on the left hand side of the prompt. With an update that was downloaded last week, this was taken away. I

### To reproduce

Create a python virtual environment and activate it:

```
python3 -m venv .venv
source .venv/bin/activate
```

### Expected behavior

The name of the virtual environment (e.g., .venv in the example above) should appear at the left hand side of the prompt.

### Operating system

MacOS

### Operating system and version

13.1.0

### Shell Version

5.8.1 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.05.23.08.05.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

N/A, the issue only applies to a Warp specific feature. (i.e. Warp AI, Workflows)

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by sisoe24** [comment] 2023-05-28 15:13
I might have the same issue. Warp is not displaying the user's custom prompt correctly. 

You can see on the far right a hint of a text.

![Screen Shot 2023-05-28 at 11 09 40 AM](https://github.com/warpdotdev/Warp/assets/28490646/c37b5d76-95c3-4efc-8d07-15081627b260)

When the window is resized, the prompt becomes "jammed" and reappears (although in a broken state), but this only lasts until the next command is executed.

![Screen Shot 2023-05-28 at 11 10 02 AM](https://github.com/warpdotdev/Warp/assets/28490646/900e9314-6cf9-40d9-b751-1cb126bdb7f0)

I am using the Starship prompt, but this does not happen in any other terminal (Terminal, ITerm, Alacritty), and it has been working fine before the update.

Expected output:

![Screen Shot 2023-05-28 at 11 09 09 AM](https://github.com/warpdotdev/Warp/assets/28490646/561fd9fb-cd3d-46cc-b6af-a1d2136c3d9a)

**Comment by dannyneira** [comment] 2023-05-30 15:47
Hey Folks, I was struggling to reproduce this issue, just wanted to confirm if you had the following set in `Settings > Subshells > "Added Commands"`( note you may need to run `which pipenv` to determine the correct location of the command ):
```
/opt/homebrew/bin/pipenv
/opt/homebrew/bin/pipenv shell
```

![CleanShot 2023-05-30 at 09 44 57](https://github.com/warpdotdev/Warp/assets/16809145/904fc8c4-aad2-4cc9-a090-dadac18f046e)

**Comment by divyranjan17** [comment] 2023-05-31 03:06
I'm also facing the same issue

**Comment by j1philli** [comment] 2023-05-31 04:31
Same over here!

**Comment by Keithagy** [comment] 2023-05-31 11:54
same here!

**Comment by zachbai** [comment] 2023-05-31 20:41
Hey all, a fix for this is coming out in this week's release. Just to confirm - this is only being experienced using zsh, correct? I found the cause but it is limited to zsh from what I can tell (the virtual env should be in the prompt for bash and fish shells)

**Comment by marcosfelt** [comment] 2023-05-31 22:06
I am seeing it with zsh but haven't tried bash or fish

**Comment by sisoe24** [comment] 2023-06-01 00:25
> Hey all, a fix for this is coming out in this week's release. Just to confirm - this is only being experienced using zsh, correct? I found the cause but it is limited to zsh from what I can tell (the virtual env should be in the prompt for bash and fish shells)

Yes, you are right. I have the same prompt for Bash, and it looks normal.

**Comment by elviskahoro** [comment] 2023-06-01 23:52
@marcosfelt @sisoe24 @divyranjan17 @j1philli @Keithagy @simjak @marcosfelt Hey folks, @zachbai submitted a bug fix for this and it should be out with today's release!

**Closed by elviskahoro** 2023-06-01 23:52 UTC
Labels: Bug

**Comment by divyranjan17** [comment] 2023-06-02 06:03
Working now. Thanks

**Comment by marcosfelt** [comment] 2023-06-02 06:20
Works perfectly! Thanks :)

**Comment by sisoe24** [comment] 2023-06-02 15:14
@elviskahoro 

Just a heads up: there's still an ongoing issue with the Zsh prompt. It doesn't correctly handle newlines (I've replaced the actual newline character with the string "newline" to make it visible). Could it be a different issue altogether?

![Untitled](https://github.com/warpdotdev/Warp/assets/28490646/f41e7d13-dc15-4af1-b1be-bf8fe3250bcc)

**Comment by j1philli** [comment] 2023-06-03 21:22
Looking good over here! Thanks!

**Comment by TCalyrex** [comment] 2024-09-23 10:58
Sorry , I cannot understand how to solve this problem. someone please tell me.
