### ISSUE TITLE
Not all fonts gets detected in linux.

### ISSUE THREAD

**Issue by akashdiphazra** [warpdotdev/Warp#4873] opened 2024-05-05 05:33 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I have installed nerd fonts in Ubuntu 24.04 and using warp terminal in it, all system font are not detected by warp terminal.

Font Name --> Source Code Pro ( Nerd Font )
Font Location --> /usr/local/share/fonts/SauceCodePro

## Gnome Tweaks
[Screencast from 2024-05-05 10-52-59.webm](https://github.com/warpdotdev/Warp/assets/61003681/868a0acd-ff06-4625-ac59-2218220cd6a0)

## Warp Terminal
[Screencast from 2024-05-05 10-53-30.webm](https://github.com/warpdotdev/Warp/assets/61003681/c0a6cd5a-e620-4322-b05e-db7ccf1aafe0)

### Is your feature request related to a problem? Please describe.

Font Availability Issue 

### How important is this feature to you?

1.  Very important 

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-05-08 23:29
Hey @akashdiphazra Warp doesn't yet support those font variants in light/bold, etc. It's only showing the regular version plus mono, propo.

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by alokedesai** [comment] 2024-05-16 22:39
Marking as a duplicate of https://github.com/warpdotdev/Warp/issues/4873

**Closed by alokedesai** 2024-05-16 22:39 UTC
Labels: Feature requests
