### ISSUE TITLE
Copy on Select not working under Sonoma

### ISSUE THREAD

**Issue by greggthomason** [warpdotdev/Warp#3731] opened 2023-10-05 14:47 UTC
### Describe the bug

Copy on select isn't working: when a selection is made, it is not automatically copied to the clipboard.

### To reproduce

1. Copy text in the terminal
2. go to another app
3. paste

### Expected behavior

The selection should paste.

### Operating system

MacOS

### Operating system and version

Sonoma 14.0 (23A344)

### Shell Version

GNU bash, version 5.2.15(1)-release (aarch64-apple-darwin21.6.0)

### Current Warp version

v0.2023.09.26.08.09.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Additional context

I'm actually unsure if it's a regression.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-10-10 20:29
Hi @greggthomason Thanks for letting us know, Also on Sonoma but I haven't been able to reproduce this one. Maybe you can try disable/enabling the setting in the command palette CMD-P type "copy on select" 
https://docs.warp.dev/features/editor#copy-on-select. Note: This feature has a known issue working within [alt-screens](https://github.com/warpdotdev/Warp/issues/2758) like vim, less, k9s, etc.

If you're still having issues, Are you copying from a block or the input? could you please post a video of the problem?

**Comment by greggthomason** [comment] 2023-10-10 21:44
ah, it's the alt-screen problem, dupe of #2758.

**Comment by dannyneira** [comment] 2023-10-20 18:46
closing as dupe, please track on the issue #2758

**Closed by dannyneira** 2023-10-20 18:46 UTC
Labels: Bug
