### ISSUE TITLE
Warp Autocomplete does not see soft links for `cd` command.

### ISSUE THREAD

**Issue by Pigrenok** [warpdotdev/Warp#4549] opened 2024-03-13 11:45 UTC
### Describe the bug

When I try to get autocomplete to fill in directory to `cd` in, it suggests only real directories and not the softlinks as it considers them as file.

### To reproduce

In any directory with soft linked directories inside just type `cd ` and then try to press on Tab button. It will show only real directories and not soft linked ones. If try to do the same with `ls `, it shows real directories as directories and soft-linked ones as files, although, if I run `ls soft-linked-dir`, it shows the content of it correctly.

### Expected behavior

It should suggest soft-linked directories along with real ones for any directory only operations ('cd' is a good example). 

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/18658968/30ff4d04-e531-44f4-8847-cc09ae048fc1)
![image](https://github.com/warpdotdev/Warp/assets/18658968/6e7a2ffa-4916-4b8d-bf45-050783f73738)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Shell Version

Bash 5.1.16

### Current Warp version

v0.2024.03.05.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-13 16:10
Hi @Pigrenok this is a known issue, please see the following request to support sym/soft-links on autocompletion https://github.com/warpdotdev/Warp/issues/4498

As a workaround, please enter the first part of the symlink path manually, then Tab completion should work for the remaining sub-folders.

Closing as duplicate.

**Comment by dannyneira** [comment] 2024-03-13 16:10
Duplicate of https://github.com/warpdotdev/Warp/issues/4498

**Closed as completed by dannyneira** 2024-03-13 16:10 UTC
Labels: bug
