### ISSUE TITLE
SSH Hang with ZSH on OSX 12.1

### ISSUE THREAD

**Issue by jaydeland** [warpdotdev/Warp#1052] opened 2022-04-14 13:19 UTC
### Discord username (optional)

jaydeland#6387

### Shell and Version

ZSH 5.8

### Operating System and Version

OSX 12.1

### I have tried commenting out my system & user rcfiles and warp still will not bootstrap

- [ ] Yes

### Screenshots

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/9366595/163398668-413da32b-6a81-4e6f-b315-12b16c250439.png">

### Include shell xtrace output

WARP_DEBUG_MODE=1 ssh 10.20.10.46.ws
+ set -o vi
+ set +o vi
+ HISTCONTROL=ignorespace
+ printf '

**Comment by sidpremkumar** [comment] 2022-04-14 13:52
Confirmed seeing the same behavior, some more debug logs: 
```
debug1: client_input_hostkeys: hostkeys file /Users/sidpremkumar/.ssh/known_hosts2 does not exist
debug1: client_input_hostkeys: host key found matching a different name/address, skipping UserKnownHostsFile update
debug1: Sending environment.
debug1: channel 1: setting env LC_ALL = "en_US.UTF-8"
debug1: Sending command:
                         printf '\033P$d{"hook": "SSH", "value": {"socket_path": "~/.ssh/16499442264667", "user": "%s", "machine": "%s", "remote_shell": "%s"}}\234' $(whoami) $(hostname) ${SHELL##*/}

                                                                                    if test "${SHELL##*/}" != "bash" -a "${SHELL##*/}" != "zsh"; then
                                    exec $SHELL
                                               fi

                                                 case ${SHELL##*/} in
                                                                       bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTCONTROL=ignorespace; printf '\\''\033P$d{"hook": "InitShell", "value": {"shell": "bash"}}\234'\\''')
               ;;
                   zsh) WARP_TMP_DIR=$(mktemp -d warptmp.XXXXXX)
                                                                if [[ $? == 0 ]]; then
                                                                                      echo '756e7365746f7074205a4c453b20756e736574205243533b20756e736574
                                     20474c4f42414c5f5243533b207072696e746620275c7831625c7835305c
                                                                                                 7832345c7836347b22686f6f6b223a2022496e69745368656c6c222c2022
                                          76616c7565223a207b227368656c6c223a20227a7368227d7d5c78396327' | command xxd -ps -r > $WARP_TMP_DIR/.zshenv
                                 else
                                     echo "Failed to bootstrap warp. Continuing with a non-bootstrapped shell."
                                                                                                               fi
                                                                                                                 TM
```

**Comment by sidpremkumar** [comment] 2022-04-14 13:54
Possible duplicate of : https://github.com/warpdotdev/Warp/issues/1051

**Comment by jaydeland** [comment] 2022-04-14 13:58
The downgrade to this version: https://github.com/warpdotdev/Warp/releases/tag/v0.2022.04.01.01.37.stable_03 works.

**Comment by elviskahoro** [comment] 2022-04-18 19:56
Should be fixed now!

**Closed by elviskahoro** 2022-04-18 19:56 UTC

**Comment by shivamstaq** [comment] 2022-05-01 04:22
@elviskahoro 
Not working on version `v0.2022.04.25.09.59.stable_03`

**Comment by elviskahoro** [comment] 2022-05-26 19:44
@shivamstaq @ambareeshsrja16 does this work on the latest version?
