### ISSUE TITLE
Background exec output is mixed with shell input

### ISSUE THREAD

**Issue by andig** [warpdotdev/Warp#1387] opened 2022-05-22 13:26 UTC
### Describe the bug

When running a command in background plus typing another command while the first one still executes, the second command gets garbled and somehow mixed with the output of the background command. As result, the second command errors as it doesn't exist.

### To Reproduce

Do:

    make&
    ls

### Expected behaviour

```text
Second command runs as `ls`.
```

### Screenshots

Impossible todo- you have to try for yourself ;)

### Operating System

MacOS

### OS Version

latest

### Shell Version

latest

**Comment by andig** [comment] 2022-06-09 13:29
Any feedback on this one? It's really a showstopper for using Warp...

**Comment by andig** [comment] 2022-06-30 19:35
Similarly, the history mixes commands with output. At this stage so many basic functionalities of a shell are broken that Warp is unusable for me.

**Comment by elviskahoro** [comment] 2022-07-09 06:04
@andig can you try this from the docs:
https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files

**Comment by andig** [comment] 2022-07-12 08:36
@elviskahoro not sure I follow. Are you suggesting to basically disable the shell? I don't think that mixing STDOUT with STDIN is something that depends on the shell's rc files?

**Comment by elviskahoro** [comment] 2022-07-20 16:59
@andig Are you suggesting to basically disable the shell?
Sorry didn't mean for it to come off this way.

In the scenario for make& ls, I'm confident there isn't anything to do on your end. But for the second issue:
> Similarly, the history mixes commands with output.

This happens for other people usually when they're using a plugin that doesn't work with Warp. And the example in the docs where is you set zdotdir is a quick way to run blanks rc files.

Can you share a video of the second bug, where your history mixes with output?
Or did you mean this:

<img width="554" alt="Screen Shot 2022-07-20 at 12 59 42" src="https://user-images.githubusercontent.com/29553206/180040358-8cce100b-50fe-4a39-b566-d040e0263a57.png">

**Comment by yang** [comment] 2022-08-22 22:20
Encountering the same issue.

Just running:

```
while true; do sleep 1; echo hello; done
```

keeps appending 'hello' to the current input buffer.

May be due to a conflicting rc setting, haven't debugged.

**Comment by yang** [comment] 2022-08-22 22:21
Tried disabling a bunch of my rc's including iterm but couldn't track down the issue.

**Comment by elviskahoro** [comment] 2022-08-23 02:45
Can you try this from the docs: <https://docs.warp.dev/help/known-issues>

You can quickly set up clean configs by putting ZDOTDIR=/ in a ~/.zshenv file. This forces zsh to run with zero configs.

**Comment by nicot** [comment] 2022-08-26 15:29
This is happening to me too. It's not related to RC files. The stdout from background processes is getting used as the input for future command lines.

Here's a minimal way to reproduce. Paste this into your terminal and hit enter:

```
(sleep 1; echo 'not the command I wanted to run') &
```

<img width="632" alt="Screen Shot 2022-08-26 at 9 27 52 AM" src="https://user-images.githubusercontent.com/3722365/186939909-0d40c2a4-e8de-49ab-83b6-0cba4f4bdc61.png">

Then you can see that your input is corrupted, and if you hit enter again you will get an error message.

This is very annoying because it has totally corrupted my shell history with thousands of lines of shell output that shouldn't have been used as input.

**Comment by elviskahoro** [comment] 2022-08-31 15:45
Thanks for sending this over. This is really helpful

**Comment by nicot** [comment] 2022-08-31 15:58
Of course, thanks for taking a look!

**Comment by andig** [comment] 2022-11-01 21:14
Basic shell functionality still broken after six months. Why should I care for reordering tabs and youknowwhat if I can‘t even use history? This is a total disaster :(

**Comment by nicot** [comment] 2022-11-02 12:54
@andig OK if we leave the issue open? The issue is still ongoing, and I'd like to use Warp. I agree with you that it seems like this should be a high priority.

**Comment by yozlet** [comment] 2022-12-19 19:51
There's an opportunity for a great feature here. I've always wanted to be able to `tail` a log, or run some other long process, without having to spawn a new shell/tab. If background and/or long-running processes could easily be moved to their own tabs/blocks/whatever (especially if this is doable _after_ the process starts) then that would be really valuable. Perhaps it might also be part of a solution to the subshell problem?

**Comment by andig** [comment] 2022-12-19 20:14
I would see this more as an opportunity to fix basic functionality. We can reorder tabs but not have a working history?

**Comment by wesbos** [comment] 2022-12-23 17:40
Came here to report this bug, but found this thread. Really annoything because you bascailly can't use background jobs in warp because any logged output is mixed with shell input..

Video here: https://wes.io/X6u5egP8

**Comment by nicot** [comment] 2023-01-25 17:39
@elviskahoro do you think your team will be able to prioritize/address this? In my shell usage, it's critical, and this has forced me to go back to using the macOS terminal app. I'd be really excited to restart using Warp.

**Comment by andig** [comment] 2023-01-25 17:48
To give it another angle: we are able to order tabs and do fancy stuff but basic functionality is broken.

**Comment by dannyneira** [comment] 2023-02-14 17:25
Hey Folks, this is actively being worked on and improvements in this area are coming in the not-too-distant future. No official ETA, but it's on the roadmap 🚀

**Comment by wesbos** [comment] 2023-02-14 18:21
Good timing - we were just recording the Syntax episode on warp! Thanks for the update

**Comment by andig** [comment] 2023-03-22 06:45
@dannyneira any chance to put working history on the agenda before AI and other things? Imho it would be really important to get the basics right. I've never missed AI in a terminal but have productivity impairment every time the history doesn't work...

**Comment by elviskahoro** [comment] 2023-03-22 16:19
@andig what do you mean by working history?

**Comment by nicot** [comment] 2023-03-22 18:16
When the shell runs `not the command I wanted to run` (from https://github.com/warpdotdev/Warp/issues/1387#issuecomment-1228639240), the whole command gets included into the history. Lots of times this ends up being backtraces from a crashing background process. Sometimes, this process is even Warp (I have no idea how or why), e.g.:
```
history 0 | grep warp
 9506*  read -r -d '' WAR[[200~yarn app_BOOTSTRAP_VAR << 'EOM'; eval "$WARP_BOOTSTRAP_VAR"; unset WARP_BOOTSTRAP_VAR\nif ! (( ${+WARP_SESSION_ID} )); then\n  WARP_SESSION_ID="$(date +%s)$RANDOM"\n\n  # Use printf to unescape the DCS strings, as /bin/sh doesn't support "\x##"\n  # escaping, and it might be consuming these variables as the remote shell\n  # executing the SSH bootstrap code.\n  DCS_START="$(printf '\x1b\x50\x24\x64')"\n  DCS_END="$(printf '\x9c')"\n  \n  # Attempt to cd to the desired initial working directory, swallowing any\n  # errors.  If this fails, the user will end up in their home directory.\n  if [[ ! -z "$WARP_INITIAL_WORKING_DIR" ]]; then\n    cd "$WARP_INITIAL_WORKING_DIR" >/dev/null 2>&1\n    unset WARP_INITIAL_WORKING_DIR\n  fi\n\n  # We configure history to ignore commands starting with space to avoid leaking\n  # our bootstrap script into the user's history. At this point, we unset this\n  # option to avoid turning on this behavior and potentially confusing the user.\n  # If they set it in their config files, their value will be respected.\n  unsetopt hist_ignore_space\n\n  warp_send_message () {\n      # Sends a message to the controlling terminal as a DSC control sequence.\n      # Sends a message to the controlling terminal as a DSC control sequence.\n      # Note that because the JSON string may contain characters that we don't control (including\n      # unicode), we encode it as hexadecimal string to avoid prematurely calling unhook if\n      # one of the bytes in JSON is 9c (ST) or other (CAN, SUB, ESC).\n      local msg=$(warp_escape_dcs_json "$1")\n      printf "%b%s%b" $DCS_START $msg $DCS_END\n  }\n\n  # Note that this is very performance sensitive code, so try not to\n  # invoke any external commands in here.\n  warp_preexec () {\n      warp_send_message "{\"hook\": \"Preexec\", \"value\": {}}"\n  }\n\n  # Note that this is very performance sensitive code, so try not to\n  # invoke any external commands in here.\n  warp_precmd () {\n      # $? is relative to the process so we must check this first\n      # or else the exit code will correspond to the commands\n      # executed within this block instead of the actual last\n      # command that was run.\n      local exit_code=$?\n\n      warp_send_message "{\"hook\": \"BlockFinished\", \"value\": {\"exit_code\": $exit_code}}"\n\n      # Get the value of PS1 and properly escape it\n      local escaped_ps1\n      if [[ -n $PS1 ]]; then\n          # Set the value of WARP_PS1 again, if something (script / command) restored it.\n          WARP_PS1="$PS1"\n      elif [[ -n $PROMPT ]]; then\n          # PROMPT is a synonym for PS1 in zsh\n          WARP_PS1="$PROMPT"\n      fi\n      # Clear the prompt again before the command is rendered as it could\n      # have been reset by the user's zshrc or by setting the variable\n      # on the command line.\n      unset PS1\n      unset PROMPT\n      # Also unset RPS1/RPROMPT, as it can end up injecting "typeahead" into the\n      # input after each command.\n      unset RPS1\n      unset RPROMPT\n\n      deref_ps1=$(print -P -- "$WARP_PS1")\n      escaped_ps1=$(warp_escape_ps1 "$deref_ps1")\n\n      # Reset the custom kill-buffer binding as the user's zshrc (which is sourced after zshrc_warp)\n      # could have added a bindkey. This won't have any user-impact because these shortcuts are only run\n      # in the context of the zsh line editor, which isn't displayed in Warp.\n      bindkey -r '^P'\n      bindkey '^P' kill-buffer\n\n      local escaped_pwd=$(warp_escape_json $PWD)\n      local escaped_virtual_env=""\n      local escaped_conda_env=""\n\n      if [ ! -z $VIRTUAL_ENV ]; then\n        escaped_virtual_env=$(warp_escape_json $VIRTUAL_ENV)\n      fi\n\n      if [ ! -z $CONDA_DEFAULT_ENV ]; then\n        escaped_conda_env=$(warp_escape_json $CONDA_DEFAULT_ENV)\n      fi\n\n      local escaped_git_branch=""\n\n      # `git rev-parse --abbrev-ref HEAD` fails if not in a git directory so we\n      # return the empty string in the error case.\n      escaped_git_branch=$(warp_escape_json $(command -v git >/dev/null 2>&1 && command git rev-parse --abbrev-ref HEAD 2>/dev/null))\n\n      local escaped_json="{\"hook\": \"Precmd\", \"value\": {\"pwd\": \"$escaped_pwd\", \"ps1\": \"$escaped_ps1\",  \"git_branch\": \"$escaped_git_branch\", \"virtual_env\": \"$escaped_virtual_env\", \"conda_env\": \"$escaped_conda_env\", \"exit_code\": $exit_code, \"session_id\": $WARP_SESSION_ID}}"\n      warp_send_message $escaped_json\n  }\n\n  warp_clear_on_next_block () {\n      warp_send_message '{"hook": "ClearOnNextBlock"}'\n  }\n\n\n  # Format a string value according to JSON syntax - Adapted from https://github.com/lework/script.\n  warp_escape_json () {\n      # Explanation of the sed replacements (each command is separated by a `;`):\n      # s/(["\\])/\\\1/g - Replace all double-quote (") and backslash (\) characters with the escaped versions (\" and \\)\n      # s/\b/\\b/g - Replace all backspace characters with \b\n      # s/\t/\\t/g - Replace all tab characters with \t\n      # s/\f/\\f/g - Replace all form feed characters with \f\n      # s/\r/\\r/g - Replace all carriage return characters with \r\n      # $!s/$/\\n/ - On every line except the last, insert the \n escape at the end of the line\n      #              Note: sed acts line-by-line, so it doesn't see the literal newline characters to replace\n      #\n      # tr -d '\n' - Remove the literal newlines from the final output\n      #\n      # Additional note: In a shell script between single quotes ('), no escape sequences are interpreted.\n      # To work around that and insert the literal values into the regular expressions, we stop the single-quote,\n      # then add the literal using ANSI-C syntax ($'\t'), then start a new single-quote. That is the meaning\n      # behind the various `'$'\b''` blocks in the command. All of these separate strings are then concatenated\n      # together to form the full argument to send to sed.\n      #\n      # We also use 'command sed' to ensure that we aren't accidentally executing an alias or function named 'sed'\n      command sed -E 's/(["\\])/\\\1/g; s/'$'\b''/\\b/g; s/'$'\t''/\\t/g; s/'$'\f''/\\f/g; s/'$'\r''/\\r/g; $!s/$/\\n/' <<<"$*" | command tr -d '\n'\n  }\n\n  warp_escape_ps1 () {\n      # Turns out that the processed prompt is a complicated data structure that includes lots of \n      # information that's passed to the shell (including the actual shell, version, working directory\n      # and, well, the prompt itself). What is more, prompt can also include emojis - unicode characters\n      # that sometimes contain special bytes (ie. ST, CAN or SUB) that are otherwise used as unhook\n      # triggers for the precmd. Instead of escaping those and extracting the value of the prompt itself,\n      # we simply convert the entire data structure into a single line hex string, which Warp\n      # later decodes and sends to the grid to show the prompt.\n      # Note: before converting the prompt to a hex string, we remove the multi-line newlines and replace\n      # them with a single space (to avoid prompts that span multiple empty lines).\n      command tr '\n\n' ' ' <<< "$*" | command od -An -v -tx1 | command tr -d ' \n'\n\n  }\n\n  # warp_escape_dcs_json encodes the entire DCS string (JSON) with od making it essentially\n  # a very long hexadecimal string.\n  # Afterwards it's decoded in rust and parsed as usual.\n  # Accepts one argument: DCS JSON string\n  warp_escape_dcs_json () {\n    printf '%s' "$1" | od -An -v -tx1 | command tr -d ' \n'\n  }\n\n  # Returns encoded InitShell hook\n  # Accepts one argument: shell [bash, zsh, fish (future)]\n  init_shell_hook () {\n    init_shell="{\"hook\": \"InitShell\", \"value\": {\"shell\": \"$1\"}}"\n    printf $(warp_escape_dcs_json "$init_shell")\n  }\n\n  # Title code is taken from ohmyzsh. We set precmd and preexec\n  # hooks in order to set the title for the idle terminal and the\n  # terminal running a command respectively. This is so we provide\n  # a reasonable default behavior in the case where the user doesn't\n  # have any shell scripts to set titles.\n  #\n  # If another shell script also has precmd/preexec hooks to set the title,\n  # we won't be clobbering them because our hooks will run first.\n  # If the WARP_DISABLE_AUTO_TITLE variable is set, we won't set the title at all.\n  # This way, setting the terminal title in a echo command and escape\n  # sequences will work (a single command to set the title normally will get\n  # clobbered by a precmd hook)."\n  #\n  # https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/termsupport.zsh\n  #\n  # Set terminal window and tab/icon title\n  #\n  # usage: warp_title tab_title\n  #\n  # See: http://www.faqs.org/docs/Linux-mini/Xterm-Title.html#ss3.1\n  function warp_title {\n    # Disable oh-my-zsh default title otherwise.\n    DISABLE_AUTO_TITLE="true"\n\n    setopt localoptions nopromptsubst\n\n    # Don't set the title if inside emacs, unless using vterm\n    [[ -n "$INSIDE_EMACS" && "$INSIDE_EMACS" != vterm ]] && return\n\n    title="%25<..<$1" # shorten the tab_title to 25 characters\n    print -Pn "\e]0;${title:q}\a" # set tab & window name (they're the same in Warp)\n  }\n\n  ZSH_THEME_TERM_TITLE_IDLE="%~"\n  ZSH_THEME_TERM_TAB_TITLE_IDLE_REMOTE="%m:%~"\n\n  # Runs before showing the prompt\n  function warp_set_title_idle_on_precmd {\n    # If the user wants to set the title using oh-my-zsh, they can\n    # set the WARP_DISABLE_AUTO_TITLE flag.\n    [[ "${WARP_DISABLE_AUTO_TITLE:-}" != true ]] || return\n\n    if [[ $WARP_IS_LOCAL_SHELL_SESSION == "1" ]]; then\n      warp_title "$ZSH_THEME_TERM_TITLE_IDLE"\n    else \n      warp_title "$ZSH_THEME_TERM_TAB_TITLE_IDLE_REMOTE"\n    fi\n\n  }\n\n  # Runs before executing the command\n  function warp_set_title_active_on_preexec {\n    # If the user wants to set the title using oh-my-zsh, they can\n    # set the WARP_DISABLE_AUTO_TITLE flag.\n    [[ "${WARP_DISABLE_AUTO_TITLE:-}" != true ]] || return\n\n    emulate -L zsh\n    setopt extended_glob\n\n    # split command into array of arguments\n    local -a cmdargs\n    cmdargs=("${(z)2}")\n    # if running fg, extract the command from the job description\n    if [[ "${cmdargs[1]}" = fg ]]; then\n      # get the job id from the first argument passed to the fg command\n      local job_id jobspec="${cmdargs[2]#%}"\n      # logic based on jobs arguments:\n      # http://zsh.sourceforge.net/Doc/Release/Jobs-_0026-Signals.html#Jobs\n      # https://www.zsh.org/mla/users/2007/msg00704.html\n      case "$jobspec" in\n        <->) # %number argument:\n          # use the same <number> passed as an argument\n          job_id=${jobspec} ;;\n        ""|%|+) # empty, %% or %+ argument:\n          # use the current job, which appears with a + in $jobstates:\n          # suspended:+:5071=suspended (tty output)\n          job_id=${(k)jobstates[(r)*:+:*]} ;;\n        -) # %- argument:\n          # use the previous job, which appears with a - in $jobstates:\n          # suspended:-:6493=suspended (signal)\n          job_id=${(k)jobstates[(r)*:-:*]} ;;\n        [?]*) # %?string argument:\n          # use $jobtexts to match for a job whose command *contains* <string>\n          job_id=${(k)jobtexts[(r)*${(Q)jobspec}*]} ;;\n        *) # %string argument:\n          # use $jobtexts to match for a job whose command *starts with* <string>\n          job_id=${(k)jobtexts[(r)${(Q)jobspec}*]} ;;\n      esac\n\n      # override preexec function arguments with job command\n      if [[ -n "${jobtexts[$job_id]}" ]]; then\n        1="${jobtexts[$job_id]}"\n        2="${jobtexts[$job_id]}"\n      fi\n    fi\n\n    # cmd name only, or if this is sudo or ssh, the next cmd\n    local CMD="${1[(wr)^(*=*|sudo|ssh|mosh|rake|-*)]:gs/%/%%}"\n    local LINE="${2:gs/%/%%}"\n\n    warp_title "$CMD"\n  }\n\n  function clear() {\n      warp_send_message "{\"hook\": \"Clear\", \"value\": {}}"\n  }\n\n  # The SSH logic only applies to local sessions, because we don't yet have support for bootstrapping\n  # recursive SSH sessions.\n  if [[ $WARP_IS_LOCAL_SHELL_SESSION == "1" ]]; then\n      # This helper function determines whether the user's ssh arguments imply\n      # creation of a non-interactive session or otherwise would conflict with\n      # our SSH wrapper.  Returns 0 for an interactive session; >0 otherwise.\n      function is_interactive_ssh_session() {\n          # This getopts code is adapted from https://gist.github.com/caruccio/836c2dda2bdfa5666c5f9b0230978f26.\n          ARGS=()    # this array holds any positional arguments\n          while [ $# -gt 0 ]; do\n              # Initialize this to 1 before each call, as per getopts documentation.\n              OPTIND=1\n              # Parse through all ssh options, as defined in the ssh man pages.\n              while getopts :1246AaCfgKkMNnqsTtVvXxYyb:c:D:e:F:i:L:l:m:O:o:p:R:S:W:w: OPTION; do\n                  case $OPTION in\n                      # -T disables pty allocation (aka a non-interactive session)\n                      T) return 1;;\n                      # -W implies -T\n                      W) return 1;;\n                      # The user provided an invalid option; kick it to real ssh.\n                      \?) return 1;;\n                      # The user omitted a required argument; kick it to real ssh.\n                      :) return 1;;\n                  esac\n              done\n              [ $? -eq 0 ] || return 2       # getopts failed\n              [ $OPTIND -gt $# ] && break    # we reached the end of the parameters\n\n              shift "$((OPTIND - 1))"  # skip all options processed so far\n              ARGS+=($1)               # save first non-option argument (a.k.a. positional argument)\n              shift                    # remove saved arg\n          done\n\n          # If there is more than one positional argument, the user is attempting to\n          # run a command, not start an interactive session.  If there is less than\n          # one positional argument, the user should be shown the usage text.\n          if [[ ${#ARGS[@]} -ne 1 ]]; then\n              return 1\n          fi\n      }\n\n      function warp_ssh_helper() {\n          init_shell_bash=$(init_shell_hook "bash")\n          init_shell_zsh=$(init_shell_hook "zsh")\n\n          # Hex-encode the ZSH environment script we use to bootstrap remote zsh b/c it contains control characters\n          # We decode on the SSH server using xxd if its available, otherwise fall back to a for-loop over each byte\n          # and use printf to convert back to plaintext\n          local zsh_env_script=$(printf '%s' "unsetopt ZLE; unset RCS; unset GLOBAL_RCS; printf '\x1b\x50\x24\x64$init_shell_zsh\x9c'" | command od -An -v -tx1 | command tr -d ' \n')\n\n          # Keep remote commands up-to-date with shell.rs & bash.sh.\n          # Note that in this command, we're passing a string to the remote shell. Any variable expansions need to be\n          # escaped with "''" to avoid the local shell from expanding them before they're passed to the remote shell.\n          # We check the SHELL env var and use shell string manipulation to get the contents after the last slash to\n          # determine what shell is the login shell on the remote machine.  We perform a preliminary check to see if\n          # the remote shell is the Bourne shell to avoid asking it to parse later lines that use syntax it doesn't\n          # support.\n          command ssh -o ControlMaster=yes -o ControlPath=~/.ssh/$WARP_SESSION_ID \\n          -t "${@:1}" \\n"\nexport TERM_PROGRAM='WarpTerminal'\n\n_user="'"$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER)"'"\n_hostname="'"$(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n)"'"\nhook="'$(printf "{\"hook\": \"SSH\", \"value\": {\"socket_path\": \"~/.ssh/'$WARP_SESSION_ID'\", \"user\": \"%s\", \"host\": \"%s\", \"remote_shell\": \"%s\"}}" "$_user" "$_hostname" "${SHELL##*/}" | command od -An -v -tx1 | command tr -d " \n")'"\nprintf '$DCS_START%s$DCS_END' "'$hook'"\n\nif test "'"${SHELL##*/}" != "bash" -a "${SHELL##*/}" != "zsh"'"; then\n  exec "'$SHELL'"\nfi\n\ncase "'${SHELL##*/}'" in\n  bash) exec -a bash bash --rcfile <(echo 'set -o vi; set +o vi; HISTCONTROL=ignorespace; HISTIGNORE=\" *\"; printf '\''$DCS_START$init_shell_bash$DCS_END'\''') $TRACE_FLAG_IF_WARP_DEBUG_MODE\n      ;;\n  zsh) WARP_TMP_DIR="'$(mktemp -d warptmp.XXXXXX)'"\nlocal ZSH_ENV_SCRIPT='$zsh_env_script'\nif [[ "'$?'" == 0 ]]; then\n  if command -v xxd >/dev/null 2>&1; then\n    echo "'$ZSH_ENV_SCRIPT'" | command xxd -p -r > "'$WARP_TMP_DIR'"/.zshenv\n  else\n    for i in {0..\$((\${#ZSH_ENV_SCRIPT} - 1))..2}; do\n      builtin printf "'"\x${ZSH_ENV_SCRIPT:$i:2}"'"\n    done > "'$WARP_TMP_DIR'"/.zshenv\n  fi\nelse\n  echo \"Failed to bootstrap warp. Continuing with a non-bootstrapped shell.\"\nfi\nTMPPREFIX="'$HOME/.zshtmp-'" WARP_SSH_RCFILES="'${ZDOTDIR:-$HOME}'" ZDOTDIR="'$WARP_TMP_DIR'" exec -a zsh zsh -g $TRACE_FLAG_IF_WARP_DEBUG_MODE\n      ;;\nesac\n"\n      }\n\n      function ssh() {\n          if is_interactive_ssh_session "$@"; then\n              warp_send_message "{\"hook\": \"PreInteractiveSSHSession\", \"value\": {}}"\n\n              # If the SSH wrapper is not enabled for this session, don't use it.\n              if [ "$WARP_USE_SSH_WRAPPER" = "1" ]; then\n                local TRACE_FLAG_IF_WARP_DEBUG_MODE=""\n                if [[ "$WARP_DEBUG_MODE" == "1" ]]; then\n                    TRACE_FLAG_IF_WARP_DEBUG_MODE="-x"\n                fi\n                warp_ssh_helper "$@"\n              else\n                command ssh "$@"\n              fi\n          else\n             command ssh "$@"\n          fi\n      }\n  fi\n\n  # Send a precmd message to the terminal to differentiate between the warp\n  # bootstrap logic pasted into the PTY and the output of shell startup files.\n  warp_precmd\n\n  # Before calling rcfiles, set the PS1 back to its original value so rcfiles\n  # that depend on PS1 will work correctly. This is a common pattern with bash\n  # rcfiles, but do this in zsh too, just in case users also do this in zsh.\n  # Note that we don't have to unset this because warp_precmd will do it for us.\n  PS1="$WARP_PS1"\n\n  # We need to restore the stty before any user bootstrap files are evaluated\n  # in case they ask for user input\n  setopt ZLE\n\n  # If powerlevel instant prompt is on, we need to disable it because it\n  # interferes with warp bootstrapping. The functionality is part of warp anyways.\n  typeset -g POWERLEVEL9K_INSTANT_PROMPT=off\n\n  # Add the Warp title precmd functions before the bootstrap sequence is sourced so that a user's custom tab title\n  # behavior is respected over Warp's.\n  precmd_functions+=(warp_set_title_idle_on_precmd)\n  preexec_functions+=(warp_set_title_active_on_preexec)\n\n  # Clean up after ourselves, restore ZDOTDIR, and remove the temporary directory in the ssh case.\n  # We need to do this before the rcfiles are sourced, since rcfiles can reference ZDOTDIR.\n  # In this case, we created a temp dir that starts with our template prefix and set the ZDOTDIR\n  # to that dir.\n  # Note that when called with a template, mktemp will work in the local directory, not the tmp filesystem.\n  TEMPLATE_PREFIX="warptmp."\n  if [[ -n $ZDOTDIR ]]; then\n      if [[ ${ZDOTDIR:0:${#TEMPLATE_PREFIX}} == $TEMPLATE_PREFIX ]]; then\n            rm -r "$ZDOTDIR"\n\n            # Restore ZDOTDIR. Note that if it was originally unset, it'd be home instead of unset.\n            ZDOTDIR=$WARP_SSH_RCFILES\n      fi\n  fi\n\n  # Load the EPOCHREALTIME variable from the zsh/datetime module so we can\n  # accurately measure how long it takes to source the user's rcfiles.\n  zmodload -F zsh/datetime +p:EPOCHREALTIME >/dev/null 2>&1\n  # Make sure we force the locale used for number formatting to "C", to avoid\n  # issues in locales that use a comma as the decimal separator.\n  local rcfiles_start_time="$(LC_ALL="C"; echo $EPOCHREALTIME)"\n\n  # This reflects the bootstrap sequence in a login shell. We want to\n  # Do other shell startup first so we can ensure Warp goes last.\n  if [[ -e ${ZDOTDIR:-$HOME}/.zshenv ]]; then\n      source ${ZDOTDIR:-$HOME}/.zshenv;\n  fi\n  if [[ -e /etc/zprofile ]]; then\n      source /etc/zprofile;\n  fi\n  if [[ -e ${ZDOTDIR:-$HOME}/.zprofile ]]; then\n      source ${ZDOTDIR:-$HOME}/.zprofile;\n  fi\n  if [[ -e /etc/zshrc ]]; then\n      source /etc/zshrc;\n  fi\n  if [[ -e ${ZDOTDIR:-$HOME}/.zshrc ]]; then\n      source ${ZDOTDIR:-$HOME}/.zshrc;\n  fi\n  if [[ -e /etc/zlogin ]]; then\n      source /etc/zlogin;\n  fi\n  if [[ -e ${ZDOTDIR:-$HOME}/.zlogin ]]; then\n      source ${ZDOTDIR:-$HOME}/.zlogin;\n  fi\n\n  local rcfiles_end_time="$(LC_ALL="C"; echo $EPOCHREALTIME)"\n\n  # Remove the powerlevel10k precmd hook entirely to prevent the\n  # powerlevel prompt from appearing in typeahead and in the command grid.\n  if [[ $precmd_functions[(I)_p9k_precmd] != 0 ]]; then\n    precmd_functions=(${precmd_functions:#_p9k_precmd})\n  fi\n\n  # Remove the pure precmd hook. Pure uses zsh-async to load\n  # the prompt asynchronously, which means that the prompt can be\n  # re-rendered (and entered as typeahead characters) once the async\n  # callback completes. This means that any sort of `unset PS1` or\n  # `unset PROMPT` calls in precmd don't work if the callback\n  # completes after the `precmd`.\n  if [[ $precmd_functions[(I)prompt_pure_precmd] != 0 ]]; then\n    precmd_functions=(${precmd_functions:#prompt_pure_precmd})\n  fi\n\n  precmd_functions+=(warp_precmd)\n  preexec_functions+=(warp_preexec)\n\n  WARP_BOOTSTRAPPED=1\n\n  # Unset the prompt environment variable: Warp doesn't render the user's default prompt.\n  # We explicitly unset this for performance optimizations and so that the we can read the\n  # command directly from the command grid without having to parse the prompt.\n  export CONDA_CHANGEPS1=false\n\n  # Unlike bash, the PS1 variable is sourced only once and if unset - it stays like that (unless\n  # a script/command restores it). We're preserving its value in WARP_PS1, and unsetting the rest,\n  # so it won't render in Warp automatically.\n  # Note that we check the prompt values are not null as we don't want to clobber the WARP_PS1 value\n  # set when we executed the warp_precmd function. In this case, the rcfiles did not set the prompt\n  # but we want the value set by the binary rather than an empty prompt. In bash, we handle this\n  # differently by just keeping the logic in warp_precmd, but that results in prompt being inserted\n  # as typeahead in zsh.\n  if [[ -n $PS1 ]]; then\n    export WARP_PS1="$PS1"\n  elif [[ -n $PROMPT ]]; then\n    export WARP_PS1="$PROMPT"\n  fi\n  unset PS1\n  unset PROMPT\n  # Also unset RPS1/RPROMPT, as it can end up injecting "typeahead" into the\n  # input after each command.\n  unset RPS1\n  unset RPROMPT\n\n  # Set history to flush after every command\n  setopt share_history\n\n  function warp_bootstrapped () {\n    # Note that for now we don't support dynamically changing HISTFILE within a session.\n    local escaped_histfile="$(warp_escape_json $HISTFILE)"\n\n    # The output of `alias` can include control characters that need to be escaped.\n    local escaped_aliases="$(warp_escape_json "`alias`")"\n    local env_var_names="$(warp_escape_json "`echo ${(k)parameters[(R)*export*]}`")"\n    local function_names="$(warp_escape_json "`builtin print -l -- ${(ok)functions}`")"\n    local escaped_builtins="$(warp_escape_json "`builtin print -l -- ${(ok)builtins}`")"\n    local escaped_keywords="$(warp_escape_json "`builtin print -l -- ${(ok)reswords}`")"\n\n    local escaped_path="$(warp_escape_json "$PATH")"\n\n    # The list of options enabled for the current shell.\n    local shell_options="$(warp_escape_json "`setopt`")"\n\n    # Note WARP_SESSION_ID doesn't need to be escaped since it's a number\n    local escaped_json="{\"hook\": \"Bootstrapped\", \"value\": {\"histfile\": \"$escaped_histfile\", \"session_id\": $WARP_SESSION_ID, \"shell\": \"zsh\", \"home_dir\": \"$HOME\", \"path\": \"$escaped_path\", \"env_var_names\":  \"$env_var_names\", \"aliases\": \"$escaped_aliases\", \"function_names\": \"$function_names\",  \"builtins\": \"$escaped_builtins\",  \"keywords\": \"$escaped_keywords\", \"shell_version\": \"$ZSH_VERSION\", \"shell_options\": \"$shell_options\", \"rcfiles_start_time\": \"$rcfiles_start_time\", \"rcfiles_end_time\": \"$rcfiles_end_time\"}}"\n    warp_send_message $escaped_json\n  }\n  warp_bootstrapped\nfi\nEOM[[201~\nyarn app\n
```

This totally wrecks reverse searching in my shell because there is huge lines with many words in them, so it's more likely to find those than to find the actual commands I wanted to run.

**Comment by wesbos** [comment] 2023-03-22 18:51
Yeah I get the same thing - its the problem of mixing the stdout and stdin. Doesnt happen often, but when it does, my whole history is dirtied with lines of some stdout error

**Comment by vorporeal** [comment] 2023-03-23 16:03
@andig - @bnavetta is focused on addressing this background process output issue; a different engineer was working on the Warp AI feature.  Unfortunately, I don't think we can speed up the fix here by having more engineers look at it in parallel.  I promise that we're treating this as one of our top priorities, it's just a challenging issue to fix in a way that plays nicely with blocks, works well across bash/fish/zsh, etc.  We're making good progress; hopefully we'll have a fix out soon. :)

**Comment by bnavetta** [comment] 2023-04-25 13:35
Hey all! We've got a build of Warp with improvements to how it handles typeahead and background output for you to try out:
1. Run `defaults write dev.warp.Warp-Stable EnableTypeahead 'true'`
2. Download Warp here: https://storage.googleapis.com/warp-releases/stable/v0.2023.04.25.08.05.stable_00/Warp.dmg
3. Warp will try to auto-update to the current release, downgrading and removing these changes. Make sure not to update until next week

Let us know what you think!

**Comment by nicot** [comment] 2023-04-25 16:04
Ben, this is working perfectly! Thank you so much for the fix. It's even better than the way older terminals handle this case, because the output gets added to the forked command.

**Comment by bnavetta** [comment] 2023-05-16 16:48
Hi everyone, improvements to background output handling are in Warp as of v0.2023.05.09.08.03.stable_01. We've got some documentation on how it works here: https://docs.warp.dev/features/blocks/background-blocks. Closing for now, but let us know if there are any further issues!

**Closed by bnavetta** 2023-05-16 16:48 UTC
Labels: Bug

**Comment by andig** [comment] 2023-12-22 16:20
This is still an issue with latest version:

<img width="453" alt="Screenshot 2023-12-22 at 17 18 36" src="https://github.com/warpdotdev/Warp/assets/184815/57e7e8a3-dfef-41f9-affd-0208e6839d61">

**Comment by bnavetta** [comment] 2023-12-27 22:46
@andig do you have https://github.com/djui/alias-tips installed? Trying to figure out where the extra output might be from

**Comment by andig** [comment] 2023-12-28 13:26
Yes, indeed- wasn't even aware of that.
