### ISSUE TITLE
Restrict minimal window width on macOS

### ISSUE THREAD

**Issue by JuniperPhoton** [warpdotdev/Warp#2887] opened 2023-04-06 13:21 UTC
### Describe the bug

Currently the window width is not set appearently and user can resize the window width to the unreasonable value, which looks bad.

### To Reproduce

Resize the window to be as narrow as possible.

### Expected behaviour

The window width is restrict to a specified value like 200px to make it look better.

### Screenshots

<img width="786" alt="image" src="https://user-images.githubusercontent.com/7578386/230390552-94f61f0f-d4a9-4caf-be02-a66d0e681d72.png">

### Operating System

MacOS

### OS Version

macOS 13

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.03.28.08.03.stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-04-06 16:50
Closing as a duplicate of https://github.com/warpdotdev/Warp/issues/1399

Please +1 that request as it helps us gauge interest. We will post any updates there.

**Closed by dannyneira** 2023-04-06 16:50 UTC
Labels: Bug
