### ISSUE TITLE
When Warp is updated, a new app instance is opened

### ISSUE THREAD

**Issue by alex-rantos** [warpdotdev/Warp#2278] opened 2022-12-02 12:15 UTC
### Describe the bug

Everytime I update Warp, the current app instance is closed and a new icon is popping in Dock instead of opening in the pinned one: 
<img width="103" alt="image" src="https://user-images.githubusercontent.com/22919198/205290134-58241ed1-067c-4d60-981b-095d3127f78c.png">

### To Reproduce

1. Update running app
2. See that a new instance is created in the Dock 

### Expected behaviour

I would expect the pinned Warp to be opened again, and not a new one.

### Operating System

MacOS

### OS Version

Latest but it happens since forever

### Shell Version

zsh 5.9 

### Warp Version

v0.2022.11.29.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2022-12-02 16:37
Closing as duplicate of #1535
Please sub and 👍 to track the issue there.

**Closed by dannyneira** 2022-12-02 16:37 UTC
Labels: Bug
