### ISSUE TITLE
Mouse middle button paste feature

### ISSUE THREAD

**Issue by FuriousBeast** [warpdotdev/Warp#4483] opened 2024-03-06 04:52 UTC
### Describe the solution you'd like?

I would like, selecting with mouse cursor and pasting with middle button. 

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-06 05:52
Duplicate of https://github.com/warpdotdev/Warp/issues/4329

**Closed by dannyneira** 2024-03-06 05:52 UTC
Labels: Feature requests
