### ISSUE TITLE
UI flashes too much when running commands

### ISSUE THREAD

**Issue by patrick91** [warpdotdev/Warp#760] opened 2022-02-18 18:18 UTC
### Describe the bug

```shell
this might be annoying just for me, but I thought I'd report it in case other people get the same. It might also be a configuration issue, I've tried with different settings but nothing fixed it :)

TLDR: when running any command the UI jumps quite a bit and it feels frustrating to me
```

### To Reproduce

Run any command (see the video attached)

### Expected behaviour

```shell
The ui shouldn't jump this much 😊
```

### Screenshots

![2022-02-18 12 14 51](https://user-images.githubusercontent.com/667029/154739780-dc922284-211a-43ef-87e7-7f13281d452c.gif)

### Operating System

MacOS

### OS Version

12.1

**Comment by elviskahoro** [comment] 2022-04-17 02:39
Duplicate of 
- #743

**Closed by elviskahoro** 2022-04-17 02:39 UTC
