### ISSUE TITLE
Changing key used for multiple cursors

### ISSUE THREAD

**Issue by PrajwalVandana** [warpdotdev/Warp#2580] opened 2023-01-30 01:35 UTC
### Discord username (optional)

ColtsFan10#6790

### Describe the bug

Is it possible to change the key used for multiple cursors from ⌘ (command)? VSCode uses ⌥ (option), as do most editors afaik

### To Reproduce

see above

### Operating System

MacOS

### OS Version

12.5

### Shell Version

zsh 5.8.1

### Warp Version

v0.2023.01.24.08.03.stable_01

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-01-30 18:30
closing as resolved but please let us know if this doesn't work as intended.

**Closed by dannyneira** 2023-01-30 18:30 UTC
Labels: Bug
