### ISSUE TITLE
Powerlevel 10k Prompt appears incorrectly

### ISSUE THREAD

**Issue by AVGVSTVS96** [warpdotdev/Warp#4172] opened 2024-02-13 21:01 UTC
### Describe the bug

~Doesn't display dividers between sections correctly, there is a v shaped grey space.~

<img width="483" alt="Screenshot 2024-02-13 at 3 54 46 PM" src="https://github.com/warpdotdev/Warp/assets/122117267/4e67d141-63e8-49dc-9555-949c59389534">

## *Fixed by setting enforce minimum contrast to never*

Second problem, multi line prompt doesn't seem to be working, cursor appears on the line below where it should appear. This is documented in https://github.com/warpdotdev/Warp/issues/2851#, any updates on if this can be corrected?

> By the way, I am blown away by how good this terminal is. Seriously game changing, I love it!

### To reproduce

1. Install and configure powerlevel 10k
2. Set style like in screenshots
3. Open Warp and set font to MesloLGS NF
4. Set to use current shell prompt

### Expected behavior

Dividers should render properly:
<img width="457" alt="Screenshot 2024-02-13 at 3 56 33 PM" src="https://github.com/warpdotdev/Warp/assets/122117267/b64ecf40-7ff0-46c6-9b14-334446964676">

### Operating system

MacOS

### Operating system and version

Sonoma 14.1.2

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.06.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-02-13 22:40
hey @AVGVSTVS96, please try and tweak the contrast settings to see if that helps with the rendering issue. https://docs.warp.dev/appearance/text-fonts-cursor#text-and-fonts

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-02-14 17:27
@AVGVSTVS96 any luck with the contrast setting to "never"? It's mentioned in this comment on the p10k support thread. https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1605005256

**Comment by AVGVSTVS96** [comment] 2024-02-15 05:28
> @AVGVSTVS96 any luck with the contrast setting to "never"? It's mentioned in this comment on the p10k support thread. [#2851 (comment)](https://github.com/warpdotdev/Warp/issues/2851#issuecomment-1605005256)

That worked! Are multi line prompts still not supported? Everything looks good now except the multiline prompt functionality, my cursor is on the line below the arrow, I didn't see any updates on this in that thread

**Comment by dannyneira** [comment] 2024-02-20 15:05
Multiline prompt is supported and renders, but we're also working on the ability to have the prompt in the same line as the input...currently they are separate elements. We're tracking that on #2304.

**Comment by dannyneira** [comment] 2024-02-20 15:06
Closing since the rendering issue is fixed with settings. Please feel free to track the same line prompt,which is in progress, over at #2304

**Comment by dannyneira** [comment] 2024-02-27 21:23
Duplicate of https://github.com/warpdotdev/Warp/issues/2304

**Comment by Advait-M** [comment] 2024-08-02 03:10
I believe this is fixed with the release of Same Line Prompt 😄 - check out https://github.com/warpdotdev/Warp/issues/2304#issuecomment-2223352668 for details. Closing out this issue!

**Closed by Advait-M** 2024-08-02 03:10 UTC
Labels: Bugs
