### ISSUE TITLE
Terminal image support

### ISSUE THREAD

**Issue by Minecodes** [warpdotdev/Warp#4282] opened 2024-02-23 17:07 UTC
### Discord username (optional)

minecodes

### Describe the solution you'd like?

I would like to have image protocol support in warp (like Kitty icat, iterm2, or sixel) for software like neofetch, termpdf.py, ranger, mpv, w3m, hologram.nvim, fzf, awrit, or twitch-tui.

### Additional context

![image](https://github.com/warpdotdev/Warp/assets/65566012/824bff46-9a87-4802-b48a-18aab03749bf)

Protocols:
 - https://sw.kovidgoyal.net/kitty/graphics-protocol/
 - https://iterm2.com/documentation-images.html
 - https://github.com/zellij-org/sixel-image

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by weirdan** [comment] 2024-02-23 17:20
Duplicate of #26

**Comment by Minecodes** [comment] 2024-02-23 19:40
Thanks for the info

**Closed** 2024-02-29 21:53 UTC
Labels: Feature requests
