### ISSUE TITLE
DUP: Duplicate of #163 - Shift+Home and Shift+End not working

### ISSUE THREAD

**Issue by KKSzymanowski** [warpdotdev/Warp#679] opened 2022-01-26 10:18 UTC
### Describe the bug

I have mapped the following key combinations:
Home - Start of line
End - End of line
Shift+Home - Select to start of line
Shift+End - Select to end of line
according to this answer https://apple.stackexchange.com/a/16137

Home and End work perfectly but Shift+Home and Shift+End do nothing.
This works everywhere (Intellij, Sublime Text, Chrome browser) but doesn't appear to work in Warp.

### To Reproduce

Steps to reproduce:
1. Create or overwrite `~/Library/KeyBindings/DefaultKeyBinding.dict` with the following content:
```
{
    "\UF729"  = moveToBeginningOfLine:; // home
    "\UF72B"  = moveToEndOfLine:; // end
    "$\UF729" = moveToBeginningOfLineAndModifySelection:; // shift-home
    "$\UF72B" = moveToEndOfLineAndModifySelection:; // shift-end
}
```
2. Reboot the system (logout and login should also work)
3. Open any text editor (eg. Sublime Text) and check that Shift+Home and Shift+End work according to the **Expected behaviour** description.
4. Type some command in Warp.
5. Go to the middle of the line.
6. Press Shift+Home or Shift+End.

### Expected behaviour

Shift+Home should select all text from the beginning of line to the cursor and Shift+End should select all text from the cursor to the end of line.

### Operating System

MacOS

### OS Version

11.6

**Comment by elviskahoro** [comment] 2022-01-28 05:19
We're collecting all keybinding issues here:
- https://github.com/warpdotdev/Warp/issues/579

**Comment by elviskahoro** [comment] 2022-01-28 05:20
Closing this as it's duplicate of:
- #163

**Closed** 2022-01-28 05:20 UTC
