### ISSUE TITLE
warp completions do not respect fish aliases

### ISSUE THREAD

**Issue by patrickfatrick** [warpdotdev/Warp#2281] opened 2022-12-02 17:49 UTC
### Describe the bug

This might really be a feature request, not sure.

In fish you can define a function/alias that wraps a command, which instructs fish on completions for it. ex:

```
function g --wraps "git"
  git $argv
end
```

or

```
function nr --wraps "npm run"
  npm run $argv
end
```

Note: defining an "alias" in fish is just a sugar for defining a function with the `--wraps` argument.

In terminal etc, typing `g` or `nr` and hitting tab would then show suggested commands. With warp however I do not see fish completions (which makes sense, the warp prompt has its own completions), but I also do not see warp completions because warp apparently doesn't understand that `g` is an alias for `git` and `nr` is an alias for `npm run`. The only way for me to see completions is to skip using the alias entirely, defeating the purpose of the alias.

### To Reproduce

using fish shell:

- Run `alias g "git"`
- Make sure this was done correctly by typing `functions g`, you should see something like what I put in "Describe the bug"
- Type `g` and hit tab
- The incorrect completions are displayed rather than the git command list that would be expected as if you had typed `git` 

### Expected behaviour

- warp should understand that `g` is equivalent to `git` and display the correct completions.

### Operating System

MacOS

### OS Version

12.6

### Shell Version

fish, version 3.5.1

### Warp Version

v0.2022.11.29.08.03.stable_01

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by patrickfatrick** [comment] 2022-12-02 19:55
No worries! Just spitballing but would it make sense for warp to display fish completions in its completions menu when they are available? Not sure what's possible.

**Comment by bybunni** [comment] 2022-12-06 19:06
I have this same issue with bash aliases. As an example, I alias `bat` with `alias batpp="bat --style=plain --paging=never"`, but`batpp` on the command line does not have any of the directory completion I would expect, only tab-completing one directory and never tab-completing the filename. `ls` aliases like `alias ll='ls -laht'` do not have this issue, they allow tab-completion through directories as expected.

**Comment by a8t** [comment] 2023-03-03 14:57
Duplicate of https://github.com/warpdotdev/Warp/issues/1895. Devs say tracking will be on that issue!

**Comment by a8t** [comment] 2023-03-03 14:58
actually it's not quite a duplicate, but I think ends up being close by.

**Comment by elviskahoro** [comment] 2023-06-01 23:54
This should be working now! Please comment if you're still experiencing any trouble

**Closed by elviskahoro** 2023-06-01 23:54 UTC
Labels: Bug

**Comment by mihar** [comment] 2025-01-06 22:24
@elviskahoro @dannyneira I don't think it's working yet. This is the behaviour I observe with `cat` being an alias for `bat`.

https://github.com/user-attachments/assets/08898870-aff3-4572-9f38-d99d07190c56
