### ISSUE TITLE
Support fish abbreviations

### ISSUE THREAD

**Issue by mzagaja** [warpdotdev/Warp#1895] opened 2022-09-28 18:43 UTC
### Describe the solution you'd like?

Hello, in fish shell if I type something like `be` I can have it auto-expand to `bundle exec` using the [abbreviations feature](https://fishshell.com/docs/current/cmds/abbr.html). This currently does not work in Warp.

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment] 2022-09-28 21:41
Thanks for this feature request! Please +1 this request as it helps us gauge interest. We will post any updates here.

**Comment by bmikaili** [comment] 2022-11-17 16:23
I can't use warp until this works unfortunately :( so very heavy +1

**Comment by Gorthog** [comment] 2023-01-23 10:12
isn't this a duplicate of https://github.com/warpdotdev/Warp/issues/852?

**Comment by mzagaja** [comment] 2023-01-24 15:40
@Gorthog It appears to be so, I just didn't see it.

**Comment by dannyneira** [comment] 2023-02-22 00:04
Hey Folks! This is on the roadmap and being worked on with no ETA on the release.

**Comment by danielpeng2** [comment] 2023-04-28 18:24
Hey all! As of version v0.2023.04.25.08.05.stable_00, fish abbreviations should properly auto-expand in Warp.

Going to close this out, but don't hesitate to leave a comment if you encounter any issues.

**Closed by danielpeng2** 2023-04-28 18:24 UTC
Labels: enhancement

**Comment by that70schris** [comment] 2023-04-28 18:27
@danielpeng2 does this only support fish? not zsh-abbr?

**Comment by danielpeng2** [comment] 2023-04-28 19:55
@that70schris Currently this only supports fish abbreviations. We are working on a setting that would allow expansion of bash/zsh aliases, which should be releasing soon. Would that help solve your use case?

**Comment by that70schris** [comment] 2023-04-28 21:00
@danielpeng2 yes, either expanding `zsh-abbr` (a zsh plugin) or aliases would solve my use case as I currently don't use fish.  although I'm curious about switching to fish

**Comment by danielpeng2** [comment] 2023-05-04 22:26
@that70schris Alias expansion in bash/zsh has been released in the latest version of Warp (v0.2023.05.02.08.03.stable_00)! It's an opt-in setting, so go to Settings > Features > Editor > "Expand aliases as you type" to enable it. Feel free to let us know if there are any issues.

**Comment by that70schris** [comment] 2023-05-05 01:43
this is awesome! no more plugin needed and it just augments the built in shell functionality. now i can just have one list aliases and it doesn't matter which shell I choose, it works the same 🙏🏻

**Comment by that70schris** [comment] 2023-05-05 02:33
one alias I've found that isn't expanding: `alias ls='ls -a'`

**Comment by that70schris** [comment] 2023-05-05 04:06
also, it doesn't seem to expand aliases in fish, only in zsh/bash

**Comment by that70schris** [comment] 2023-05-05 05:59
and unlike fish abbreviations "Expand aliases as you type" only expands when the spacebar is hit, not on enter

**Comment by shrugalic** [comment] 2023-05-05 07:19
May I suggest opening a new issue regarding alias expansions? This issue is/was about fish abbreviations, and is solved.

**Comment by that70schris** [comment] 2023-05-05 13:41
@shrugalic I can create another one if needed, but I had one open which was closed: https://github.com/warpdotdev/Warp/issues/1605

**Comment by that70schris** [comment] 2023-05-05 13:59
I have created 2 more: https://github.com/warpdotdev/Warp/issues/3024
