### ISSUE TITLE
When will the custom window size be supported?

### ISSUE THREAD

**Issue by sonvier** [warpdotdev/Warp#2229] opened 2022-11-25 13:06 UTC
### Describe the solution you'd like?

Currently warp does not support custom window size, I hope that the function of customizing the window size can be introduced in the future, just like Iterm. Every time you start, the warp's window size will use a predefined one, rather than an ugly large window.

### How important is this feature to you?

3

**Comment by yahiaelgamal** [comment] 2022-11-27 08:39
+1 one on this, I ended up using iterm more because it's less intrusive due to the smaller window size. Especially when I just want to run a quick command.

**Comment by dannyneira** [comment] 2022-11-28 21:24
Thanks for this request, closing as duplicate of #1399
Please +1 that request as it helps us gauge interest. We will post any updates there.

**Closed by dannyneira** 2022-11-28 21:24 UTC
Labels: Feature
