### ISSUE TITLE
Unable to pause scroll

### ISSUE THREAD

**Issue by hrdwdmrbl** [warpdotdev/Warp#1355] opened 2022-05-14 10:41 UTC
### Describe the bug

When a command is running which outputs a lot of logs, the text scrolls very quickly. I like to be able to read some samples of what is going on. To do that on iTerm, I scroll up and then I'm removed from autoscroll-mode. I can then calmly scroll up and down the still text. Below where I'm reading, new logs are continuing to be generated and so my scrollbar is continually moving up slowly as my relative position in the logs changes. If at some point my position reaches the top then yes, my text will scroll off the terminal and I'll basically be looking at the head (as opposed to the tail) of the autoscrolling logs. Am I making sense? Effectively I just want to be able to read quickly scrolling logs. In Warp though, when I scroll up from the "tail" of the logs, the text continues to scroll past me just as quickly. This is because my relative scroll position in the terminal remains fixed.

### To Reproduce

Steps to reproduce:
1. Generate a lot of logs
2. Scroll up

### Expected behaviour

```text
Relative scroll position should move so that the text does not move.
```

### Screenshots

a video would be more help but I can't be bothered.

### OS Version

666

### Shell Version

666

**Comment by szgupta** [comment] 2022-05-17 18:18
Experimented with this a bit. It seems that when the output is produced rapidly, it's hard to scroll up and read a particular line. But when the output is not produced rapidly, this seems to work well today.

```
# produce_output.py
from time import sleep

i = 0
while True:
    print(f"THIS IS LINE i={i}")
    i += 1
    # Without this sleep, it becomes impossible to read data at 
    # a fixed position line. With the sleep however, scrolling
    # to some part in the already-produced output seems to work
    # well.
    sleep(0.1)

```

**Comment by jfryman** [comment] 2022-05-19 17:34
Came here to file this bug. Enjoying the terminal - today's use case I was executing a long-running batch job interactively and I was unable to copy/paste output for debugging.  I'm aware I could send to background, but I also need the full log for other purposes so I get to watch it scroll in entirety. 

Ideally, I would like to be able to pause the buffer at the current location for introspection, and then once finished advance back to the latest stream. Even when I scroll back, the buffer is moving around and adjusting my relative location in the output stream to the viewing buffer.

Hopefully this context makes sense.

v0.2022.05.16.09.01.stable_01

**Comment by gregkonush** [comment] 2022-08-02 23:55
would love to pause logs as it is difficult to pinpoint to problems of running application

**Comment by carlosbaraza** [comment] 2022-09-23 23:00
This is quite an important feature. It seems like the problem is only really happening when there are lots of logs very quickly and the maximum block length is reached. Lines seem to be removed from the beginning of the block, causing data loss and this bug. Is it a performance tradeoff?

**Comment by macbem** [comment] 2023-01-03 13:53
Bump - this is basically the only case where iTerm 2 is better for me than Warp. When I attach to logs of a Docker container, it's impossible to stop the automatic scroll behavior to pause and read some logs while new ones keep coming in.

**Comment by ericmerrill** [comment] 2023-01-25 16:37
Agreed. This and #610, which seem to be tightly related, are real blockers for using Warp. I'm hoping with the recent comment in that ticket that it will be worked on, that this one will be fixed in tandem.

**Comment by vorporeal** [comment] 2023-01-26 22:19
So, part of the issue here might be that we currently limit the length of a block to 10k lines - this is due to performance issues, and we've got an engineer actively working on resolving those so that we can raise the limit/let users set it to values in the millions.

Would that be sufficient to address the concerns here?  Or does iTerm do anything fancy like stop reading output from the shell (effectively halting the running process) if you've paused auto-scroll but the output has reached the maximum line limit?

**Comment by ericmerrill** [comment] 2023-01-27 18:51
@vorporeal So what iTerm does, is if you are at the top or bottom of an ongoing scrollback, you will see the lines being added (at the bottom), and removed (at the top), so scrolling by however fast they are being created, but when you are in the middle, your view remains static on the lines in your view, with lines being added below your current view, and being removed above it, until you run out of scroll back buffer. This in practice means, that once you detach from the bottom, to look at a set of lines, then scroll bar on the right will slide up, showing where you are in the scroll back buffer.

Because of how Warp is handling its scrolling with blocks, no matter where you are in the scroll, if lines are being truncated, you can never get lines to stop - because they are sliding by 'in the block', and the scroll is relative to the block container (I think).

Since I don't know if that all makes sense, I made this [short screen capture of iTerm](https://youtu.be/YRZJChhyE6k), that hopefully makes sense.

**Comment by isaacpovey** [comment] 2023-03-09 16:22
+1 this is a blocker preventing from switching totally from iterm to warp.

**Comment by vasilev-alex** [comment] 2023-03-14 13:06
I completely switched to Warp, but after encountering this issue, I had to fall back.

**Comment by exotexot** [comment] 2023-03-14 18:56
Same here. I really enjoy Warp. But this feature makes me return to iTerm.

**Comment by vorporeal** [comment] 2023-03-14 22:41
Sorry for the delays here; I've watched the above video and understand the scrolling issue being described!  I'm aiming to work on improving this soon, hopefully next week.

**Comment by arnassavickas** [comment] 2023-04-13 10:47
+1 really waiting for the fix!

**Comment by yvesshum** [comment] 2023-05-12 02:49
+1 really enjoyed warp so far, but this is a very painful issue. Any updates on a fix?

**Comment by vorporeal** [comment] 2023-05-12 18:40
I have a working prototype that ties the scroll position to a line in a block (as @ericmerrill was describing), but still need to figure out a small issue leading to occasional jitter.  Aiming to get that done and launched in the next week or two!

**Comment by lupuszr** [comment] 2023-06-06 16:16
any news with this one ? :)

**Comment by dannyneira** [comment] 2023-06-08 21:23
This has been put on the back burner for now, but we'll post any updates/progress on this thread if/when we have them. Appreciate your patience folks!

**Comment by smurrayroberts** [comment] 2023-08-16 10:33
I love Warp, but I'm also on the verge of moving back to iTerm as this issue ruins my user experience

**Comment by shrey150** [comment] 2023-08-18 14:44
Also having this issue with a long-running Python task. Would appreciate a fix!

**Comment by ev01ve** [comment] 2023-08-24 18:14
This is a huge issue for my workflow.  I'll have to switch back to iTerm for now.

**Comment by iammohan01** [comment] 2023-08-25 13:50
I love Warp, but this thing makes me want to search for an alternative. It's very annoying to limit the number of lines where we have to look for live production logs.

**Comment by maxime-menant** [comment] 2023-08-29 08:07
Same issue with a GO service printing a lot of logs... it's very frustrating to not be able to have enough time to select intereting logs to at least copy them... Switching back to iTerm2 until this is fixed...

**Comment by ev01ve** [comment] 2023-08-30 16:40
iterm + fig + atuin is a pretty great replacement.  Not sure if I'll be returning to warp after finding this combo.

**Comment by elviskahoro** [comment] 2023-09-01 22:33
Gonna close this in favor of 610--which is the root issue of this problem

**Comment by djkgamc** [comment] 2024-02-27 23:34
uhhh seriously you can't make logs stop scrolling? I thought for sure it was my fault, goodbye warp

**Comment by jefaokpta** [comment] 2024-03-01 00:27
Anxious for this fix

**Comment by ziscky** [comment] 2024-04-16 12:07
Forced to uninstall, this is too frustrating

**Comment by alacret** [comment] 2024-04-29 14:19
+1 need to this to be usable

**Comment by adityabaradwaj** [comment] 2024-05-02 05:42
+1 i've been a Warp user for over a year, had to switch back to iterm2 because of this

**Comment by djkgamc** [comment] 2024-05-17 03:43
yeah this is --- unusable

**Comment by victor-jacek-simplisafe** [comment] 2024-05-30 15:09
If it's a large effort to get scrolling to pause automatically for fast/large output, would it be possible (and fast / low effort) to have a global "pause scroll" setting + hotkey?  This would be just enough to make Warp usable in these cases.  Thanks!

**Comment by ipearx** [comment] 2024-06-28 09:46
Also needing this for scrolling log files I'm trying to read. Warp is way faster for this compared to iTerm, but not being able to pause the scrolling is a dealbreaker

**Comment by dannyneira** [comment] 2024-06-28 17:28
Hey Folks, the ability to pause scroll is blocked by the full-scrollback issue we're tracking here. https://github.com/warpdotdev/Warp/issues/610

**Comment by dannyneira** [comment] 2024-07-08 17:42
Hi Folks, we're working on a fix for this pausing scroll issue. No firm ETA, but it's coming soon!

The fix will be independent of the full-scroll back issue noted in #610

**Comment by szgupta** [comment] 2024-07-08 19:31
Hey all! As @dannyneira mentioned above, this should be fixed soon (likely in the 07/18/24 release).

Here's a preview in the meantime: https://www.loom.com/share/2b353790c6b84dfba7f0a73e73354562?sid=cf5ee9d6-3fd5-4a1d-b572-e32384d85746

**Comment by exotexot** [comment] 2024-07-08 19:38
Jesus. Can't wait for this to land!
THx @szgupta !

**Comment by szgupta** [comment] 2024-07-18 17:41
Hey everyone, the stable scrolling fix has been released! Please update to `v0.2024.07.16.08.02.stable_02` or later to pick up the fix.

Please note that the block line limit is still fixed at 10k. #610 is the issue we're using to track the request to set your own finite / infinite scrollback limit.

**Closed** 2024-07-22 21:21 UTC
Labels: Feature requests, Bugs

**Comment by lupuszr** [comment] 2024-07-23 10:54
🎉

**Comment by rileyjshaw** [comment] 2024-07-28 23:24
Epic - thanks for fixing this!!

**Comment by jfryman** [comment] 2024-07-28 23:41
Excited to give Warp another shot. Thank you.
