### ISSUE TITLE
Add pipe the output to another command or workflow

### ISSUE THREAD

**Issue by mr3iscuit** [warpdotdev/Warp#5058] opened 2024-06-22 21:17 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Add pipe output to current command or to a workflow in context menu.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-06-24 23:03
Thanks for submitting this @mr3iscuit 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/3827

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-24 23:03
Duplicate of https://github.com/warpdotdev/Warp/issues/3827

**Closed by dannyneira** 2024-06-24 23:03 UTC
Labels: enhancement
