### ISSUE TITLE
Lock tabs to prevent them from getting closed

### ISSUE THREAD

**Issue by dawdmaow** [warpdotdev/Warp#2689] opened 2023-02-22 17:15 UTC
### Describe the solution you'd like?

```text
It happens too often to me that I close tabs that I didn't mean to. One way to solve it would be implementing undo (there's already an issue for that), but potentially even more convenient way would be to just lock tabs that are important to us.
```

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-02-22 23:02
Thanks for this feature request! Please :+1:  and subscribe to this request as it helps us gauge interest. We will post any updates here.

**Comment by tom-daggett-wd** [comment] 2023-06-29 15:42
iTerm has a feature like this that prevents you from accidentally click on on the 'close tab' button

**Comment by AntonAL** [comment] 2024-03-25 14:34
Must have feature!
I'm closing tabs accidentally almost every day and when I'm using "Reopen Closed Session", I'm getting "Shell process exited". So, a feature "Reopen Closed Session" does not make sense in my case.
Could you implement it like a "Pin" feature with tab groups.
<img width="901" alt="image" src="https://github.com/warpdotdev/Warp/assets/2064830/e082c186-e0fd-4dd8-8149-7e207ff896d4">

**Comment by dannyneira** [comment] 2024-05-23 20:54
Hi Folks, we have a feature request for pinned tabs and tab groups which would help with this use case of "locked" tabs that cant easily be closed. Given that we'll be closing this request in favor of https://github.com/warpdotdev/Warp/issues/2314

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment] 2024-05-23 20:55
Duplicate of https://github.com/warpdotdev/Warp/issues/2314

**Closed by dannyneira** 2024-05-23 20:55 UTC
Labels: Feature requests
