### ISSUE TITLE
Command input does not appear

### ISSUE THREAD

**Issue by joao-rod** [warpdotdev/Warp#5144] opened 2024-07-19 22:06 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

After yesterday's update, the input to enter commands no longer appears. I already reinstalled it, left the default settings and nothing works.

### To reproduce

![image](https://github.com/user-attachments/assets/c9bcd964-a903-4c4b-b7ff-73444ab7ecdf)

### Operating system

Linux

### Operating system and version

17

### Shell Version

fish 3.3.1

### Current Warp version

v0.2024.07.16.08.02.stable_02

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

18/07/2024

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by vorporeal** [comment] 2024-07-19 22:07
This is probably a duplicate of https://github.com/warpdotdev/Warp/issues/5142; we'll have a fixed build live in 5-10 minutes.

**Closed** 2024-07-19 22:16 UTC
Labels: Bugs

**Comment by vorporeal** [comment] 2024-07-19 22:20
`v0.2024.07.16.08.02.stable_03` is now live; please download the latest version and let me know if you're still experiencing the problem or if we can close this issue!
