### ISSUE TITLE
Autocomplete failed after folder with "space"

### ISSUE THREAD

**Issue by ssentanoe** [warpdotdev/Warp#2029] opened 2022-10-31 15:03 UTC
### Describe the bug

Hi, using double tab button is failed when after the folder with space

### To Reproduce

Folder structure

```
.
└── Folder1
   ├── folder-without-space
   │  └── folder2
   └── Folder with space
      └── folder2
```

try to run command `cd Folder1`  -> double tab -> select "Folder with space"  -> double tab -> nothing...
try `cd Folder` -> double tab -> select "folder-without-space" -> double tab -> shows the "folder2"

### Expected behaviour

should show "folder2"

### Screenshots

![CleanShot 2022-10-31 at 16 02 25](https://user-images.githubusercontent.com/4618600/199039953-c092c6f7-25e7-42fb-bf59-3e656b554396.png)
![CleanShot 2022-10-31 at 16 02 46](https://user-images.githubusercontent.com/4618600/199040011-9f6891f6-6cdf-4c98-9f88-e9dfc410b00a.png)

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.9 (arm-apple-darwin21.3.0)

### Warp Version

v0.2022.10.25.08.06.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment] 2022-10-31 15:05
Hey @ssentanoe, thanks for flagging! I'm actively working on a fix, we should have this fixed in a week or so.

**Comment by ssentanoe** [comment] 2022-10-31 15:06
hey @alokedesai thanks, btw I forgot to mention. Double tab from the "start" also does not show the auto complete.
For example when I just type `cd` command, and does double tab, it shows nothing. Is it intended?

**Comment by alokedesai** [comment] 2022-10-31 15:08
@ssentanoe Could you clarify what you mean by "Double tab from the "start" also does not show the auto complete"? A video or an image for this would be especially useful

**Comment by ssentanoe** [comment] 2022-10-31 15:15
https://user-images.githubusercontent.com/4618600/199042012-7f613ee1-4d94-48a0-aed9-5b26033466ad.mp4

https://user-images.githubusercontent.com/4618600/199042548-f1680ff1-9398-431c-8db8-240d377919d0.mp4


Here is a screen recording of it. I hope it is clear.
So basically, I have to type a (or some) character(s) first after `cd` command, before the autocomplete kicks in. But without any character input, then the autocomplete does not work.
With other command like `cat` or `rm` it works right away.
Does it has something to do with my zsh auto-completion plugin? I'm also using zprezto.

**Comment by dannyneira** [comment] 2022-10-31 15:20
Hi @ssentanoe It may be that the zsh autocompletion plugin is incompatible with Warps built in completion.

You can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh

if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

# <zsh auto-completion plugin code here>

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi

```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by dannyneira** [comment] 2022-10-31 15:22
Also, this is a duplicate of #669, keeping this one open as we work thru the completion plugin issue.

**Comment by ssentanoe** [comment] 2022-10-31 15:27
confirmed, when I wrap the zprezto init with the if block, now the `cd` works fine.

**Comment by dannyneira** [comment] 2022-10-31 19:07
Thanks for confirming it was an unsupported plugin. I will close this in favor of https://github.com/warpdotdev/Warp/issues/669 which is a known issue.

**Closed by dannyneira** 2022-10-31 19:07 UTC
