### ISSUE TITLE
Tag Number for easier switching

### ISSUE THREAD

**Issue by TimAnthonyAlexander** [warpdotdev/Warp#4508] opened 2024-03-08 09:45 UTC
### Discord username (optional)

.timanthony

### Describe the solution you'd like?

I have a preset of 6-8 tabs open at all times, and I switch using the CMD + 1-9 keys for that.

It would be nice to have a small number (could be optional) to indicate which tab is which. 

### Is your feature request related to a problem? Please describe.

Often I go into the wrong one as I don't know exactly which tab no. 7 is or similar.

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-08 23:44
Thanks for submitting this @TimAnthonyAlexander 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/4028

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-08 23:44
Duplicate of https://github.com/warpdotdev/Warp/issues/4028

**Closed by dannyneira** 2024-03-08 23:44 UTC
Labels: Feature requests
