### ISSUE TITLE
Can't Integrate with VSCode?

### ISSUE THREAD

**Issue by aungbobotun** [warpdotdev/Warp#1483] opened 2022-06-10 04:24 UTC
### Describe the bug

```text
Warp isn't working on my VSCode. Is it just an app level?
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### OS Version

MacOS

### Shell Version

zsh 5.8

### Warp Version

v0.2022.06.06.09.05.stable_01

**Comment by baruchiro** [comment] 2022-06-16 05:08
Maybe duplicate of https://github.com/warpdotdev/Warp/issues/257?

**Comment by elviskahoro** [comment] 2022-06-28 17:41
@baruchiro is correct. closing

**Closed by elviskahoro** 2022-06-28 17:41 UTC
