### ISSUE TITLE
bigger buffer size

### ISSUE THREAD

**Issue by geekerzhou** [warpdotdev/Warp#2056] opened 2022-11-07 04:05 UTC
### Describe the solution you'd like?

```text
make buffer size settable, big log is not complete
```

### How important is this feature to you?

5 (Can't work without it!)

**Comment by dannyneira** [comment] 2022-11-07 17:32
Hi @geekerzhou, Thanks for this feature request! Closing this in favor of #610, as they are similar requests. Please +1 that request as it helps us gauge interest. We will post any updates there.

**Closed by dannyneira** 2022-11-07 17:32 UTC

**Comment by dannyneira** [comment] 2024-05-23 16:35
Duplicate of https://github.com/warpdotdev/Warp/issues/610
