### ISSUE TITLE
psql makes spacing go weird

### ISSUE THREAD

**Issue by jpninanjohn** [warpdotdev/Warp#4484] opened 2024-03-06 06:21 UTC
### Describe the bug

I use the prompt starting at the top of the screen so my expectation on clearing screen should be that the prompt should end up at the top. Generally works but found this issue when I am using psql console.

When I open a psql console and then use clear(ctrl + L), half the screen is not utilised and is just blank. The psql prompt starts from half the screen. I have to force the console to print somethign that occupies the entire screen which then fixes it.

### To reproduce

1. Open psql console. 
2. Use ctrl+L or the shortcut to clear screen.
3. The prompt ends up a tthe bottom of the screen somewhere. 
4. Further clearing of screen still ends up with the prompt at the bottom.

To fix:

1. I use `\dt` to print something that occupies the entire screen.
2. Clearing now fixes it and the prompt is now at the top as expected. 

### Expected behavior

 My expectation is that on clearing screen, the prompt should end up at the top. Does not work for psql prompts alone.

### Screenshots

https://github.com/warpdotdev/Warp/assets/11459946/2a63b677-e18a-4d3d-a177-558fe55eef7e

### Operating system

Linux

### Operating system and version

Fedora release 37 (Thirty Seven) x86_64

### Shell Version

GNU bash, version 5.2.21(1)-release (x86_64-redhat-linux-gnu)

### Current Warp version

v0.2024.03.05.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Always been like this.

### Additional context

```

```

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-03-14 00:45
Hi @jpninanjohn This may be because Warp features like blocks arent supported in REPLS like psql. 

We already have a request tracking this over at #4082 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-14 00:46
Duplicate of #4082

**Closed by dannyneira** 2024-03-14 00:46 UTC
Labels: Bugs
