### ISSUE TITLE
Mac: Paste on mouse middle button click

### ISSUE THREAD

**Issue by upachler** [warpdotdev/Warp#416] opened 2021-11-16 10:30 UTC
### Describe the solution you'd like?

```shell
I use the MacOS terminal quite a lot. One feature I use often and that I miss in Warp is middle mouse button insertion (this is a feature inherited from X Window back in the day).

Basically, you select text in the terminal with the mouse, and then later, in some other context, press the middle mouse button, which causes that text to be inserted where the cursor is. Maybe that doesn't translate 100% to what Warp wants to do; I could imagine that Warp may also want to place the insertion cursor where the user clicked (this is not done by the MacOS terminal).
```

**Comment by rlinq** [comment] 2022-01-12 08:09
This is also a feature I'm missing in Warp, however I'm used to copy on select and paste with right mouse click. This is super efficient when working on putty terminals on remote x servers from a Windows host. Recently switched to Mac, this is the feature I miss the most. When warp introduced copy on select I was super happy, I can just hope that paste with mouse could be implemented. 

Maybe it's a good idea to make it a config option to choose, middle or right mouse button to paste content.

All the best

**Comment by mkartashev** [comment] 2022-02-09 13:00
FWIW, this is available in iTerm2 and I also use middle-click to paste a lot. Quite convenient and middle-click isn't used for anything else (not yet anyway).

**Comment by PRNDA** [comment] 2022-06-29 05:30
+1 for this awesome feature

**Comment by elviskahoro** [comment] 2022-07-06 13:37
Will reach back out to the team on this.

**Comment by alexander-beedie** [comment] 2022-10-28 09:33
This definitely needs to exist ;)

**Comment by ncri** [comment] 2023-01-09 13:14
Yep, missing this a lot as well. One important thing to note: Selecting and pasting something in this way does NOT overwrite what you have currently copied/cut in your clipboard. It will simply insert the selected text directly at the prompt.

**Comment by cdcasey** [comment] 2024-02-01 14:54
YA +1. Would love to have this.

**Comment by dannyneira** [comment] 2024-03-07 01:03
Not sure why this was closed, but we're not tracking middle-click paste support here: https://github.com/warpdotdev/Warp/issues/4329

**Comment by dannyneira** [comment] 2024-03-07 01:03
Duplicate of https://github.com/warpdotdev/Warp/issues/4329

**Comment by joey-squid** [comment] 2024-03-07 16:31
s/not/now/ I assume :)

**Comment by joey-squid** [comment] 2024-03-07 16:32
Technically this feature request was for Mac and the other one is for Linux, though it probably makes sense to have one across the board. Would it make sense to retitle/retag the other one so it's not platform-specific?

**Comment by dannyneira** [comment] 2024-03-14 22:27
Hey Folks, we've released middle-click paste support in today's release [v0.2024.03.12.08.02](https://docs.warp.dev/getting-started/changelog#id-2024.03.14-v0.2024.03.12.08.02).

**Comment by alokedesai** [comment] 2024-03-19 20:53
Keeping this open to track middle click paste support on Mac

**Comment by jeremyronking** [comment] 2024-03-19 20:56
> Keeping this open to track middle click paste support on Mac

Appreciate you!

**Comment by wandoschneider-liber** [comment] 2024-03-28 16:52
Please please please :D

**Comment by jeremyronking** [comment] 2024-06-26 14:16
Is there an ETA for this feature?  It was there for a hot minute before it was peeled out for Linux only.

**Comment by Punt13140** [comment] 2024-07-16 11:06
A coworker just said to me "For me, it's a no-go if I can't use middle button". It's the only feature missing for him to move to Warp.

**Comment by PRNDA** [comment] 2024-07-17 00:52
THREE YEARS!!! 
Is this tooooo hard to implement, or the team just don't want to do it?

**Comment by jabalsad** [comment] 2024-07-30 20:09
I don't understand why this works on Linux but not Mac OS. Middle-click paste is standard across all terminals.

**Comment by acarl005** [comment] 2024-08-15 18:02
Hey all! Warp engineer here. First, I'd like to share why this hasn't been done yet. Middle-click paste is very much a concept from the Linux world. Linux actually has separate, independent clipboards. The clipboard that you interact with when you ctrl-c/ctrl-v is separate from the one you interact with when you select/middle-click. Both can have different content concurrently, and Linux desktop environments will provide distinct slots for these.

Of course, several terminal apps have emulated this interaction on other OSes, such that its becoming standard. The complication is that MacOS just doesn't have separate clipboards. It's only got the one. So, the OS isn't providing the APIs to help back this functionality. Basically, Warp has to build its own space for the middle-click clipboard, and that is effectively mutable global state (not trivial in Rust). Middle-click paste also won't work _across apps_ like it does in Linux. For example, on Linux you can select text (without copying with ctrl-c) in Firefox and middle-click paste it into your terminal. This won't be possible on MacOS. We were hesitant to introduce a feature that didn't behave as expected.

That said, the demand for this feature is undeniable. I'm finally looking into building a version of this in Warp. Stay tuned!

**Comment by acarl005** [comment] 2024-10-14 07:47
Closing as completed as we've shipped this feature in `v0.2024.10.01.08.02.stable_00`. if anyone needs to disable this for some reason, it can be done in preferences > features > editor > middle-clock to paste.

**Closed by acarl005** 2024-10-14 07:47 UTC
Labels: Feature requests
