### ISSUE TITLE
Option + mouse click doesnt take your cursor to that place unlike iterm2 or vscode terminal

### ISSUE THREAD

**Issue by itsamrit** [warpdotdev/Warp#5114] opened 2024-07-12 07:09 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Option + mouse click doesnt take your cursor to that place unlike iterm2 or vscode terminal

### To reproduce

ssh into any server then go inside a pod or container and write some command and try to move your cursor using option + mouse click in mac. This is working in all other terminal except warp

### Expected behavior

Option + click inside a container should take your cursor to that clicked place. This is working fine outside the pods and containers

### Operating system

MacOS

### Operating system and version

Mac

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by itsamrit** [comment] 2024-07-12 07:09
Only happens in Warp

**Comment by dannyneira** [comment] 2024-07-12 22:02
Thanks for submitting this @itsamrit As a workaround, you can enable the [subshell mode](https://docs.warp.dev/features/subshells) or [ssh wrapper](https://docs.warp.dev/features/ssh) features, they will allow you to click and move the cursor within containers and ssh sessions as with local sessions in Warp.

That being said, we already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/775

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-07-12 22:03
Duplicate of https://github.com/warpdotdev/Warp/issues/775

**Closed by dannyneira** 2024-07-12 22:02 UTC
Labels: Bugs
