### ISSUE TITLE
Command output not showing after running the command

### ISSUE THREAD

**Issue by kaavee315** [warpdotdev/Warp#1963] opened 2022-10-17 07:01 UTC
### Discord username (optional)

kaavee315

### Describe the bug

When I run a command in the warp, it takes me to previous command run and am unable to see the output of the current running command.
Setup: Mac, ZSH on warp.

### To Reproduce

1. Run any long-running command on warp

### Operating System

MacOS

### OS Version

12.6

### Shell Version

zsh 5.8

### Warp Version

v0.2022.10.11.08.13.stable_01

### Does this block you from using Warp daily?

Yes

**Comment by alokedesai** [comment] 2022-10-17 16:56
Hey @kaavee315, thanks for filing! I'm trying to understand this bug a little better, would you be able to add more context and add a video? Thanks so much!

**Comment by Darrenmeehan** [comment] 2022-10-17 20:33
I believe I'm seeing the same issue on two different machines.
One slight difference is that the command being ran, along with the output is missing. I'm uploading a video that shows the issue. https://youtu.be/o6JU0KgFgFw

One is an M1 Macbook Pro running latest MacOS (12.x), the other is a Macbook Pro 2012 running 10.15.7 (Source of this video).

**Comment by alokedesai** [comment] 2022-10-17 20:40
Very strange. Just to sanity check, if you comment out your RC files does this still repro?

**Comment by Darrenmeehan** [comment] 2022-10-17 20:47
I'm using zsh, and with it all commented out it still happens.

I could try some older versions tomorrow. Where would I get them? Anything else I can share to help?

**Comment by Darrenmeehan** [comment] 2022-10-17 20:51
I remembered I recently turned on the experimental feature "Open completions menu as you type". 

I turned it off and the issue went away. Turning it back on, and the issue is still gone. Quite unusual!

**Comment by alokedesai** [comment] 2022-10-17 20:53
Thank you for the details! We're actively looking into this. @kaavee315 do have "open completions menu as you type" as well?

**Comment by alokedesai** [comment] 2022-10-17 21:03
@Darrenmeehan Are you only able to reproduce this for `sleep` or is it for any long running command?

**Comment by Darrenmeehan** [comment] 2022-10-17 21:12
> @Darrenmeehan Are you only able to reproduce this for `sleep` or is it for any long running command? 

It was any long running command, sleep was just a command that demoed it. 

It's no longer happening on my personal Macook Pro. After toggling the completion setting off and then on.

Sgould I try turning this off and then on again on my other laptop tomorrow?

**Comment by ianb-pomelo** [comment] 2022-10-17 23:03
I'm seeing similar issues where I run a command and the output is not shown or shows up a couple seconds later. I've had this happen with several commands. Also on an M1 Macbook Pro. I did not have the feature on when this was happening

**Comment by alokedesai** [comment] 2022-10-18 13:12
@Darrenmeehan @ianb-pomelo Is this a recent regression for both of you? Would you mind checking if it can repro with this build: https://storage.googleapis.com/warp-releases/stable/v0.2022.10.04.08.05.stable_00/Warp.dmg

**Comment by ianb-pomelo** [comment] 2022-10-18 19:36
It's intermittent but with that version it still happened to me. From an outside perspective it looks like the command frame for the current running command/input is hidden

**Comment by ianb-pomelo** [comment] 2022-10-26 22:26
Any updates on this? When it happens on interactive commands it makes Warp unusable

**Comment by patrickglass** [comment] 2022-11-28 23:56
I am having the same issue with long-running bazel command or git fetch. For me, the issue is only reproducible on the latest current stable. The old stable release @alokedesai mentioned did not exhibit the behavior.

Working Version (could not reproduce): `v0.2022.10.04.08.05.stable_00`
Version with Issues (latest stable): `v0.2222.11.14.14.55.stable_01`

https://youtu.be/iAJBfVVbNuY

**Update - FIXED**: I toggled the setting `Open completions menu as you type` while on version v0.2222.11.14.14.55.stable_01 and now it is working ok. I am not sure what weird state my system was in before, but it does seem to be related to a bug around that setting.

**Comment by alokedesai** [comment] 2022-11-29 00:53
@patrickglass Thanks for flagging that it is related to completions as you type? We're actively investigating this and will follow up with a fix shortly

**Comment by alokedesai** [comment] 2022-11-29 00:56
cc @szgupta

**Comment by alokedesai** [comment] 2022-12-06 14:27
Hey all, we believe this issue is now fixed with our latest release so I'm going to close this out. Please reopen if you are still experiencing issues. Thanks!

**Closed by alokedesai** 2022-12-06 14:27 UTC
