### ISSUE TITLE
Unable to process when inside a big repository/folder

### ISSUE THREAD

**Issue by IshmeetSingh06** [warpdotdev/Warp#4071] opened 2024-01-15 07:12 UTC
### Describe the bug

Warp is unable to complete the clear process when done multiple time

### To reproduce

1. Open warp
2. Go inside a big repository
3. Type clear command and press enter
4. Do this for a few time and warp will lag-out/ it goes into a unresponsive state where you can just input and not run any commands

### Expected behavior

Does not matter how many clear commands are given it should perfectly execute them

### Screenshots

<img width="985" alt="image" src="https://github.com/warpdotdev/Warp/assets/76062864/31b542b1-58d9-48ae-90dc-9c364b4bf872">
<img width="985" alt="image" src="https://github.com/warpdotdev/Warp/assets/76062864/96d1da30-9465-4163-af55-6ff092b27b45">
<img width="985" alt="image" src="https://github.com/warpdotdev/Warp/assets/76062864/ac7bba39-9245-43fe-af5d-278be0bb0e29">
<img width="1236" alt="image" src="https://github.com/warpdotdev/Warp/assets/76062864/2425080b-7bf8-402e-9058-2ac43e01a6f7">

### Operating system

MacOS

### Operating system and version

Sonoma 14.2.1

### Shell Version

zsh 5.9

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-17 23:10
Hey @IshmeetSingh06 sorry to hear about this blocker, Unable to reproduce this issue with a large repository ( I tried with the [freecodecamp](https://github.com/freeCodeCamp/freeCodeCamp) repo with 836M of files/folders ). Clear ran just fine for me, but maybe you have an alias or some other function running along with it? Can you please run `which -a clear` and see the result? Also, as a workaround to running `clear` you can press `CTRL-L` to clear the screen or `CMD-K` to clear all the blocks in the current session.

Please let me know if this was helpful or if you're still seeing the issue with the shortcuts.

To anyone else facing this issue, please add a 👍 to the original post at the top or comment with your details, and subscribe if you'd like to be notified.

**Comment by IshmeetSingh06** [comment] 2024-01-18 13:05
@dannyneira I figured out the issue this was not related to any command (eg clear), this happened because somehow permission to access Desktop folders was denied for warp, after reinstalling and setting the required permission this worked fine , but in any case this should throw a error or ask for permission again not lag-out

**Comment by dannyneira** [comment] 2024-01-18 23:26
Thanks for letting us know, I'll make sure to add a note about permissions requirements in our docs.

**Comment by dannyneira** [comment] 2024-01-18 23:32
closing as resolved.

**Closed by dannyneira** 2024-01-18 23:32 UTC
Labels: Bug
