### ISSUE TITLE
Tab close button is on the wrong side

### ISSUE THREAD

**Issue by Z2Flow** [warpdotdev/Warp#3875] opened 2023-11-16 16:23 UTC
### Describe the bug

The close button on tabs is on the right.
The Mac has close buttons on the left.
Is this a Windows app?

### To reproduce

Open a tab.

### Expected behavior

Close buttons should be on the left.

### Operating system

MacOS

### Operating system and version

14.2.0

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.11.07.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

never

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-11-16 20:31
Thanks for submitting this @Z2Flow 

We already have a request tracking this over at #3177

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Closed by dannyneira** 2023-11-16 20:31 UTC
Labels: Bug

**Comment by dannyneira** [comment] 2024-06-20 23:17
Duplicate of https://github.com/warpdotdev/Warp/issues/1847
