### ISSUE TITLE
crash  Monterey 12.4

### ISSUE THREAD

**Issue by Deniffer** [warpdotdev/Warp#1489] opened 2022-06-11 15:25 UTC
### Describe the bug

```text
<thread QoS user interactive (requested user interactive), process sudden termination clean, IO tier 0>
  20  start + 462 (dyld + 21790) [0x1100ed51e] 1-20
    20  NSApplicationMain + 817 (AppKit + 16103) [0x7ff8099dfee7] 1-20
      20  -[NSApplication run] + 586 (AppKit + 196457) [0x7ff809a0bf69] 1-20
        20  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394 (AppKit + 252090) [0x7ff809a198ba] 1-20
          20  _DPSNextEvent + 927 (AppKit + 258557) [0x7ff809a1b1fd] 1-20
            20  _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 188645) [0x7ff80fc830e5] 1-20
              20  ReceiveNextEventCommon + 594 (HIToolbox + 189258) [0x7ff80fc8334a] 1-20
                20  RunCurrentEventLoopInMode + 292 (HIToolbox + 189926) [0x7ff80fc835e6] 1-20
                  20  CFRunLoopRunSpecific + 562 (CoreFoundation + 515676) [0x7ff806fdbe5c] 1-20
                    20  __CFRunLoopRun + 1276 (CoreFoundation + 518680) [0x7ff806fdca18] 1-20
                      20  __CFRunLoopServiceMachPort + 319 (CoreFoundation + 525197) [0x7ff806fde38d] 1-20
                        20  mach_msg_trap + 10 (libsystem_kernel.dylib + 6522) [0x7ff806eda97a] 1-20
                         *20  ipc_mqueue_receive_continue + 0 (kernel + 335600) [0xffffff8000261ef0] 1-20
```

### To Reproduce

Steps to reproduce:
2. Click on '...'
3. Scroll down to '...'
4. See error '...'

### OS Version

12.4

### Shell Version

bash 3.2

### Warp Version

v0.2022.04.01.01.37.stable_03

**Comment by ryanmagoon** [comment] 2022-06-12 00:43
Duplicate of https://github.com/warpdotdev/Warp/issues/1463

**Comment by trentjones21** [comment] 2022-06-12 16:59
Same thing happening to me on Ventura 30.0 beta (`13.0 Beta (22A5266r)`)

**Comment by hrbrmstr** [comment] 2022-06-12 23:34
This is likely a dup of Duplicate #1463, even if it's Monterey. Warp was likely using forbidden APIs.

**Comment by Deniffer** [comment] 2022-06-26 03:18
**still carsh in mac os 12.4 it seems not the same as the 13.0 beta.** 
Date/Time: 2022-06-25 15:10:40.087 +0800
End time: 2022-06-25 15:11:01.043 +0800
OS Version: macOS 12.4 (Build 21F79)
Architecture: x86_64h
Report Version: 35.1
Incident Identifier: ED25081A-BF8C-460F-AA9F-E8B6EADB17F7
Share With Devs: Yes

Data Source: Stackshots
Shared Cache: 398ACFB4-57F6-31E0-BC82-E9959E5C92CE slid base address 0x7ff812d75000, slide 0x12d75000
Shared Cache: 05187957-23EA-3199-8409-676C51C59E46 slid base address 0x7ff82ab42000, slide 0x2ab42000

Command: stable
Path: /Applications/Warp.app/Contents/MacOS/stable
Identifier: dev.warp.Warp-Stable
Version: 0.1.0 (20220621.234520)
Team ID: 2BBY89MBSN
Architecture: x86_64
Parent: launchd [1]
PID: 32670
Time Since Fork: 1149s

Event: hang
Duration: 20.96s
Duration Sampled: 11.10s (process was unresponsive for 10 seconds before sampling)
Steps: 111 (100ms sampling interval)

Hardware model: MacBookPro16,1
Active cpus: 12
HW page size: 4096
VM page size: 4096
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 107849s
Time Since Wake: 9242s

Fan speed: 1839 rpm
Total CPU Time: 6.194s (11.7G cycles, 11.0G instructions, 1.06c/i)
Advisory levels: Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space: 376.22 GB/465.63 GB, low space threshold 3072 MB

Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
Heaviest stack for the main thread of the target process:
111 start + 462 (dyld + 21790) [0x1184d251e]
111 main + 41 (stable + 32799865) [0x10a25bc79]
111 std::rt::lang_start_internal::hdb19fe6764e59ca8 + 677 (stable + 32925253) [0x10a27a645]
111 std::rt::lang_start::_::hc517c7481d778f6f + 17 (stable + 32798945) [0x10a25b8e1]
111 std::sys_common::backtrace::__rust_begin_short_backtrace::h3d54cfba5cc22fe5 + 6 (stable + 32799878) [0x10a25bc86]
111 stable::main::hf5c78c46ed0eb386 + 391 (stable + 32799687) [0x10a25bbc7]
111 warp::run::h221d94c2a94ba411 + 1865 (stable + 41280169) [0x10aa722a9]
111 warp::run_with_resources::ha4fc86721b164845 + 12793 (stable + 41304313) [0x10aa780f9]
111 _::run::h363a0ec61d7664cf + 616 (stable + 43669960) [0x10acb99c8]
111 -[NSApplication run] + 586 (AppKit + 196457) [0x7ff815b8af69]
111 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1394 (AppKit + 252090) [0x7ff815b988ba]
111 _DPSNextEvent + 927 (AppKit + 258557) [0x7ff815b9a1fd]
111 _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 188645) [0x7ff81be020e5]
111 ReceiveNextEventCommon + 283 (HIToolbox + 188947) [0x7ff81be02213]
111 RunCurrentEventLoopInMode + 292 (HIToolbox + 189926) [0x7ff81be025e6]
111 CFRunLoopRunSpecific + 562 (CoreFoundation + 515676) [0x7ff81315ae5c]
111 __CFRunLoopRun + 2771 (CoreFoundation + 520175) [0x7ff81315bfef]
111 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 9 (CoreFoundation + 777991) [0x7ff81319af07]
111 _dispatch_main_queue_callback_4CF + 31 (libdispatch.dylib + 63675) [0x7ff812eeb8bb]
111 _dispatch_main_queue_drain + 943 (libdispatch.dylib + 64632) [0x7ff812eebc78]
111 _dispatch_client_callout + 8 (libdispatch.dylib + 13079) [0x7ff812edf317]
111 async_task::raw::RawTask::run::hb12f8ed2c14cabb2 + 98 (stable + 34629714) [0x10a41a852]
111 _::poll::hd167d3a601a5d412 + 113 (stable + 35755985) [0x10a52d7d1]
111 ::poll::h30e668c59c966f63 + 368 (stable + 40964912) [0x10aa25330]
111 warpui::app::MutableAppContext::relay_task_output::h513eb4d56b0059d0 + 2795 (stable + 42892779) [0x10abfbdeb]
111 warpui::app::MutableAppContext::flush_effects::habc1fc4e88983ee1 + 5457 (stable + 42885073) [0x10abf9fd1]
111 warpui::app::MutableAppContext::add_window::::h1498349c5069abf4 + 332 (stable + 38056380) [0x10a75f1bc]
111 warpui::app::MutableAppContext::add_window::redraw_window::he1631f7c111d72dd + 641 (stable + 42873265) [0x10abf71b1]
111 warpui::presenter::Presenter::invalidate::ha7f7f983149540c8 + 336 (stable + 43416784) [0x10ac7bcd0]
111 warpui::app::AppContext::render_view::h0ad8e79eb3621763 + 380 (stable + 42895676) [0x10abfc93c]
111 _::render::h2c1b7edb8e82fa9a + 4938 (stable + 39436874) [0x10a8b024a]
111 warpui::elements::img::Image::from_url::hf1a39c9d0ebc15b6 + 389 (stable + 43575701) [0x10aca2995]
111 reqwest::blocking::get::h644d0c177dbd5f92 + 242 (stable + 42812178) [0x10abe8312]
111 reqwest::blocking::client::Client::execute::h068c17cf4653fd15 + 888 (stable + 31453528) [0x10a113158]
111 reqwest::blocking::wait::timeout::hb9248e5194cb4c0d + 601 (stable + 30862825) [0x10a082de9]
111 std:🧵:park_timeout::h0b1a73a07eed38ac + 203 (stable + 32928331) [0x10a27b24b]
111 std::sys::unix::locks::pthread_condvar::Condvar::wait_timeout::h4657f35cc29e14cf + 255 (stable + 33013311) [0x10a28fe3f]
111 __psynch_cvwait + 10 (libsystem_kernel.dylib + 17386) [0x7ff81305c3ea]
*111 psynch_cvcontinue + 0 (pthread + 20893) [0xffffff800375619d]

**Comment by Deniffer** [comment] 2022-06-26 03:19
> This is likely a dup of Duplicate #1463, even if it's Monterey. Warp was likely using forbidden APIs.

it seems have no relate to the 13.0 beta crash , since i have updated to the newest version of wrap

**Comment by elviskahoro** [comment] 2022-07-09 06:46
@Deniffer is this still happening to you? please comment if so, gonna close for now

**Closed by elviskahoro** 2022-07-09 06:46 UTC
