### ISSUE TITLE
Ability to clear last block

### ISSUE THREAD

**Issue by edwardloveall** [warpdotdev/Warp#194] opened 2021-09-11 20:11 UTC
### Describe the solution you'd like?

I'd love to be able to clear the most recent block on screen. In the macOS terminal, this is `⌘-L` which clears to the last bookmark, and every new command entered creates a new bookmark. The effect is you can clear commands that you don't care about or entered in error which cleans up your screen nicely.

For example if I've entered the wrong command: `touhc foo.txt` I get an error. If I don't errant command, I have to clear the whole screen.

**Comment by elviskahoro** [comment] 2021-10-14 14:38
Linking Similar / same request: https://github.com/warpdotdev/warp/issues/49

**Comment by elviskahoro** [comment] 2021-12-02 03:03
Should be fixed with v0.2021.11.29.18.59.stable_01
please reopen or comment if it still persists

**Comment by dannyneira** [comment] 2022-12-28 22:28
We've added a clear "block" now when you run the command, but it doesn't delete the block. For that, we have an issue tracking it here: https://github.com/warpdotdev/Warp/issues/23

Closing as duplicate.

**Comment by dannyneira** [comment] 2024-01-30 18:11
Duplicate of #50

**Closed by dannyneira** 2024-01-30 18:11 UTC
Labels: enhancement

**Comment by ElijahLynn** [comment] 2025-03-01 00:49
Similar: I've tried a few times now to click the context on a block to delete it. Should be able to clear any block, especially if there was sensitive info in it.
