### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by j2is** [warpdotdev/Warp#5072] opened 2024-06-28 13:42 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

Instead of clicking update on every launch, would be handy to have auto updates if you trust the updates are always great.

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-06-28 16:09
Thanks for submitting this @j2is We're tracking a request for option to disable auto-updates here https://github.com/warpdotdev/Warp/issues/1991

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-06-28 16:09
Duplicate of https://github.com/warpdotdev/Warp/issues/1991

**Closed by dannyneira** 2024-06-28 16:09 UTC
Labels: Feature requests
