### ISSUE TITLE
Starship arrow (character) in prompt block (ZSH)

### ISSUE THREAD

**Issue by dylandifilippo** [warpdotdev/Warp#3262] opened 2023-06-26 13:22 UTC
### Describe the bug

I discovered today that the arrow of the Starship prompt is within the block and not behaving as it should.
I also looked into a previous issue but it didn't solve my bug: https://github.com/warpdotdev/Warp/issues/3066

### To reproduce

I'm on MacOS with starship and the nerd font style preset: https://starship.rs/presets/nerd-font.html

### Expected behavior

The arrow shouldn't be at this position, either at the end of the line of my repo (+ branch + programming language).

<img width="846" alt="CleanShot 2023-06-27 at 09 37 10@2x" src="https://github.com/warpdotdev/Warp/assets/53791026/9aa318ca-8855-4144-9968-1ae47b9ec98d">

### Screenshots

<img width="325" alt="CleanShot 2023-06-26 at 15 22 37@2x" src="https://github.com/warpdotdev/Warp/assets/53791026/d9a06599-7588-47a6-a9a7-44b8109b03de">

### Operating system

MacOS

### Operating system and version

13.4.1 (22F82)

### Shell Version

zsh 5.9 (x86_64-apple-darwin22.0)

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-06-26 20:38
Hey @dylandifilippo thanks for submitting. So given how the input editor works like an IDE and is separate from the prompt in Warp, I'm not how much refactoring will be needed to make them both in one line as you expect in other terminals. So I just want to set the expectation that it may be a while before this is implemented. 

That being said, there is a related request for prompt + input in one line you can track here: https://github.com/warpdotdev/Warp/issues/2304

**Comment by CaptainVincent** [comment] 2023-06-27 02:10
```bash
~
✓
echo 123
123
```

I also noticed this issue. I think he means there is an extra line break in Warp.
If your run inside tmux. You could get below
```bash
~
✓ echo 123
123
```

This is my config
```toml
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$line_break\
$character"""
```

**Comment by dylandifilippo** [comment] 2023-06-27 07:39
Hey @dannyneira, I didn't formulate my expected behaviour correctly.
I just want it to behave as it is displayed on the homepage of this repository.

<img width="846" alt="warp-starship" src="https://github.com/warpdotdev/Warp/assets/53791026/38e5687c-2f47-4ade-8bf9-1211626bc55e">

**Comment by dylandifilippo** [comment] 2023-06-27 14:25
I found out what might've caused this. 

So I see that you don't support this: https://docs.warp.dev/features/prompt#multi-line-and-right-sided-prompts

Then I added this line of code in the starship.toml config file: 

```
[line_break]
disabled = true
```

It solved what I wanted in Warp:

<img width="363" alt="CleanShot 2023-06-27 at 16 13 09@2x" src="https://github.com/warpdotdev/Warp/assets/53791026/845fe882-0a95-466e-95c7-f38723580725">

Well, now it is not what I want in VsCode's terminal, but we can't have everything 🤪

<img width="801" alt="CleanShot 2023-06-27 at 16 13 37@2x" src="https://github.com/warpdotdev/Warp/assets/53791026/a552aedc-fa64-4b31-b85d-3bef55be2ae2">

**Comment by CaptainVincent** [comment] 2023-06-27 15:42
Just as I said? I think there is an issue with an extra line break when handling prompts in warp.
The behavior in VS Code is consistent with tmux and other terminals, I believe. 🤔

**Comment by dannyneira** [comment] 2023-06-27 17:39
Hey Folks, Warp should now support multi-line and right-sided prompts in zsh and fish shells. Please let us know if that isn't the case for you.

![CleanShot 2023-06-27 at 11 38 43](https://github.com/warpdotdev/Warp/assets/16809145/84aa029b-4a49-4dad-9542-903a83f5d67a)

**Comment by dylandifilippo** [comment] 2023-06-27 17:50
Hey @dannyneira, should I do something specific, I don't understand.

**Comment by dannyneira** [comment] 2023-06-27 17:52
> Hey @dannyneira, should I do something specific, I don't understand.

Try setting line break disabled to false or comment it out
Also make sure your on the latest versions of Warp, zsh, starship.

**Comment by dylandifilippo** [comment] 2023-06-27 18:03
I just did all this and it doesn't solve the problem.

**Comment by dannyneira** [comment] 2023-06-27 18:14
If you don't mind sharing your starship.
toml I can take a look and try to reproduce the issue.

**Comment by dylandifilippo** [comment] 2023-06-27 18:17
```
[bun]
format = "via [$symbol]($style)"

[buf]
format = "via [$symbol]($style)"

[cmake]
format = "via [$symbol]($style)"

[cobol]
format = "via [$symbol]($style)"

[crystal]
format = "via [$symbol]($style)"

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"

[deno]
format = "via [$symbol]($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = 'via [$symbol]($style)'

[elm]
format = 'via [$symbol]($style)'

[erlang]
format = 'via [$symbol]($style)'

[golang]
format = 'via [$symbol]($style)'

[haxe]
format = 'via [$symbol]($style)'

[helm]
format = 'via [$symbol]($style)'

[julia]
format = 'via [$symbol]($style)'

[kotlin]
format = 'via [$symbol]($style)'

[lua]
format = 'via [$symbol]($style)'

[meson]
format = 'via [$symbol]($style)'

[nim]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[ocaml]
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
format = 'via [$symbol]($style)'

[perl]
format = 'via [$symbol]($style)'

[php]
format = 'via [$symbol]($style)'

[pulumi]
format = 'via [$symbol$stack]($style)'

[purescript]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[raku]
format = 'via [$symbol]($style)'

[red]
format = 'via [$symbol]($style)'

[rlang]
format = 'via [$symbol]($style)'

[ruby]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[swift]
format = 'via [$symbol]($style)'

[vagrant]
format = 'via [$symbol]($style)'

[vlang]
format = 'via [$symbol]($style)'

[zig]
format = 'via [$symbol]($style)'

[line_break]
disabled = false

[git_metrics]
disabled = false

[git_status]
conflicted = '🏳'
ahead = '🏎💨${count}'
behind = '😰${count}'
diverged = '😵⇕⇡${ahead_count}⇣${behind_count}'
# up_to_date = '👍'
untracked = '🤷'
stashed = '📦'
modified = '📝'
staged = '[++\($count\)](green)'
renamed = '👅'
deleted = '🗑'
```

**Comment by dannyneira** [comment] 2023-06-27 18:48
So I tried with your starship.toml file and it all was rendering properly.

![CleanShot 2023-06-27 at 12 47 02](https://github.com/warpdotdev/Warp/assets/16809145/4016f525-f094-4768-ac2f-eb21e017a6f8)

My guess is that you normally have a custom prompt, theme, or zsh plugin and Warp is unable to parse it.

You can check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`

This forces Zsh to run with zero configs, and if that works then it's certainly something in your rc files causing the issue, and I recommend you disable the unsupported/breaking parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>

If you care to share a redacted version of your rc file i can also try it as well and see what the issue may be.

**Comment by CaptainVincent** [comment] 2023-06-28 23:02
Hi ~ @dannyneira
Could you explain why the commands(the position where input is displayed when typed) in warp are not appearing after ">"? This behavior seems inconsistent with other terminals. right?

**Comment by dannyneira** [comment] 2023-06-28 23:30
@CaptainVincent This has to do with the fact that the input editor and the prompt are separated in Warp. This enables the IDE-like input editing and completions in Warp so it's unlikely to change in the future.

**Comment by CaptainVincent** [comment] 2023-06-29 01:25
Understood.

**Comment by declanchiu** [comment] 2023-11-05 02:37
![image](https://github.com/warpdotdev/Warp/assets/55419399/4720f830-792d-42d7-884e-8d3e64b67539)

I also encountered this problem, so from Dannyeira's reply, it shouldn't be easy to fix this problem with wrap later, so I can only modify the configuration by myself to solve it.

**Comment by Advait-M** [comment] 2023-11-10 02:35
Hey folks @CaptainVincent @dylandifilippo @declanchiu ! Just a note - we're actively working on supporting the ability to have the command appear on the same line as the prompt 😄 . I'm tracking updates on this in #2304. 

Gonna close this out - please head over there for keeping track of progress!

**Closed by Advait-M** 2023-11-10 02:35 UTC
Labels: Bug

**Comment by obsidian33** [comment] 2024-07-11 17:45
Now with Warp v0.2024.07.09.08.01.stable_00 you can now choose whether you'd like your prompt on a new line (Warp's default) or on the same line with commands, like a classic terminal.

When using Starship we're using a custom PS1, and Warp will use the same line prompt setting to respect theme configurations. So it will behave like any other terminal for the most part.

But unfortunately Starhip seems to be adding an "indent" to the prompt if I have:

```
[character]
success_symbol = ''
error_symbol = ''
```

![image](https://github.com/warpdotdev/Warp/assets/6493594/4a91fb87-8eb7-4ce1-b50e-193813cae9e6)

If I don't use the empty string for the character module, it then appears to line up correctly:
![image](https://github.com/warpdotdev/Warp/assets/6493594/0234a682-1f90-4d8d-a173-f524100aec45)


Let me know if I should open up another issue for this. The context here did seem somewhat relevant.

**Comment by dylandifilippo** [comment] 2024-07-12 15:26
Hello @obsidian33,
I'm not using Starship anymore, I'm using ohmyposh but it the same principle than Starship.
I can attest that the problem is solved, thanks a lot!
