### ISSUE TITLE
Drag tab to a new window (tear off tab) and drag tabs between windows

### ISSUE THREAD

**Issue by sakers** [warpdotdev/Warp#4163] opened 2024-02-10 12:09 UTC
### Discord username (optional)

bravesirrobin932ad

### Describe the solution you'd like?

I'd like to be able to drag a tab off into a new window (and or course drag tabs between windows). 

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-12 17:23
Duplicate of https://github.com/warpdotdev/Warp/issues/466

**Closed** 2024-02-29 21:43 UTC
Labels: Feature requests
