### ISSUE TITLE
Blurry Text on fractional scaling ubuntu 22.04

### ISSUE THREAD

**Issue by Santosh7017** [warpdotdev/Warp#4517] opened 2024-03-09 11:58 UTC
### Describe the bug

When I enable fractional scaling in Ubuntu, the text of Warp terminal becomes blurry.

### To reproduce

1. Go to settings.
2. Open display from sidebar
3. enable fractional scaling to 125%

### Screenshots

![Screenshot from 2024-03-09 17-25-55](https://github.com/warpdotdev/Warp/assets/73546536/5592a3fe-fd39-4499-ab08-c01a36592cc4)

### Operating system

Linux

### Operating system and version

Ubuntu 22.04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by alokedesai** [comment] 2024-03-11 14:30
Hi @Santosh7017, thanks for filing. We believe this is due to Warp's lack of support for native Wayland.

To confirm that, could you run force enable Wayland support by running with `WARP_ENABLE_WAYLAND=1 warp-terminal` to see if it fixes the issue?

**Comment by stevegy** [comment] 2024-03-12 13:02
> Hi @Santosh7017, thanks for filing. We believe this is due to Warp's lack of support for native Wayland.
> 
> To confirm that, could you run force enable Wayland support by running with `WARP_ENABLE_WAYLAND=1 warp-terminal` to see if it fixes the issue?

This is working better for my Ubuntu 22.04.4! Now the font rendering makes my eyes comfortable. Thanks.

**Comment by alokedesai** [comment] 2024-03-12 14:13
Great; we're actively working on adding native Wayland support. We expect it to be released later this week.

**Comment by Santosh7017** [comment] 2024-03-12 16:28
> Hi @Santosh7017, thanks for filing. We believe this is due to Warp's lack of support for native Wayland.
> 
> To confirm that, could you run force enable Wayland support by running with `WARP_ENABLE_WAYLAND=1 warp-terminal` to see if it fixes the issue?

Using this command fixes the blurriness of the text.Thanks for the solution.

**Comment by dannyneira** [comment] 2024-03-14 00:29
Duplicate of https://github.com/warpdotdev/Warp/issues/4234

**Comment by dannyneira** [comment] 2024-03-14 00:30
We'll continue tracking this and post updates on #4234

**Closed by dannyneira** 2024-03-14 00:30 UTC
Labels: Bugs
