### ISSUE TITLE
Warp doesn't reponde to the terminal commands anymore

### ISSUE THREAD

**Issue by saeedesmaili** [warpdotdev/Warp#3276] opened 2023-06-29 10:38 UTC
### Describe the bug

I've been using Warp on two devices for a long time. Since a few days ago, it doesn't respond to anything on one of the devices (the commands seem to stay in a pending state, even a simple `clear` command). I tried quitting the app, restarting the laptop, and even removing Warp and installing it again, but the issue still persists and I don't have any idea how to fix it.

Here is a simple demo (I interrupt the commands with cmd+c after a few seconds):

https://github.com/warpdotdev/Warp/assets/13351748/4fd7e22d-5ea2-4372-9c64-3410f00c01c0

Note that iterm is working fine on the machine.

### To reproduce

-

### Operating system

MacOS

### Operating system and version

13.4

### Shell Version

zsh 5.9

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

Yes, this bug started recently or with an X Warp version

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by MedRedha** [comment] 2023-06-29 13:01
> ### Discord username (optional)
> _No response_
> 
> ### Describe the bug
> I've been using Warp on two devices for a long time. Since a few days ago, it doesn't respond to anything on one of the devices (the commands seem to stay in a pending state, even a simple `clear` command). I tried quitting the app, restarting the laptop, and even removing Warp and installing it again, but the issue still persists and I don't have any idea how to fix it.
> 
> Here is a simple demo (I interrupt the commands with cmd+c after a few seconds):
> 
>  Screen.Recording.2023-06-29.at.12.30.22.mov 
> Note that iterm is working fine on the machine.
> 
> ### To reproduce
> 
> ### Expected behavior
> _No response_
> 
> ### Screenshots
> _No response_
> 
> ### Operating system
> MacOS
> 
> ### Operating system and version
> 13.4
> 
> ### Shell Version
> zsh 5.9
> 
> ### Current Warp version
> v0.2023.06.20.08.04.stable_03
> 
> ### Regression
> Yes, this bug started recently or with an X Warp version
> 
> ### Recent working Warp date
> _No response_
> 
> ### Additional context
> _No response_
> 
> ### Does this block you from using Warp daily?
> Yes, this issue prevents me from using Warp daily.
> 
> ### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)
> Yes, this I confirmed this only happens in Warp, not other terminals.
> 
> ### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e
> None

I have the exact same problem 😢 That's annoying because I use it everyday.

The fix that I found and can save your work temporarily is rolling back to the previous version. (I used MacOS Time Machine backup)

And unfortunately, Warp doesn't have a disable for automatic updates, so keep the working .dmg in case Warp auto-updates itself 😉 

I hope it can help 🤞

**Comment by dannyneira** [comment] 2023-06-29 15:55
Hey @saeedesmaili Sorry to hear about this blocker. I've the most common cause of this is something unsupported in your rc files. Do you mind sharing a redacted copy of your zshrc files? 

My guess is that you normally have a [custom prompt, theme, or bash/zsh/fish plugin and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

You can also quickly check whether it’s something in your dotfiles by [setting up clean configs:](https://docs.warp.dev/help/known-issues#configuring-and-debugging-your-rc-files)
Run `echo 'ZDOTDIR=/' > ~/.zshenv`
This forces Zsh to run with zero configs. Once the culprit is found you can disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```
We have a list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools>
And more info on custom prompts here: <https://docs.warp.dev/features/prompt>

**Comment by saeedesmaili** [comment] 2023-06-30 07:27
Here is my `.zshrc` file. It's strange, since Warp was working fine for me for more than a year with the same `zshrc` config (I haven't changed anything recently).

```
NPM_PACKAGES="${HOME}/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"

export PATH=$HOME/.local/bin:$PATH

export VIRTUAL_ENV_DISABLE_PROMPT=0

export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions virtualenv)

source $ZSH/oh-my-zsh.sh

export PATH=/opt/homebrew/bin:$PATH
export PATH=/usr/local/bin:"$PATH"

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PYENV_ROOT/shims:$PATH"

eval "$(pyenv init --path)"

export EDITOR=nano
export VISUAL="$EDITOR"

function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}
```

**Comment by ruudk** [comment] 2023-07-03 06:38
Same issue here, came back from holiday and all of a sudden Warp doesn't work anymore. I'm using Fish shell and have been using Warp for a very long time. Didn't make any changes.

**Comment by saeedesmaili** [comment] 2023-07-20 08:59
Hey
I haven't got any responses yet, the problem still exists, and updating Warp, uninstalling and installing it again, and so many other stuff that I tested didn't fix the issue!

**Comment by dannyneira** [comment] 2023-08-28 22:40
@saeedesmaili Sorry about this blocker and for any delays in response. I'm not seeing anything obvious in our rc file that stands out as the possible cause of the issue. I'll let the team know and we'll try and reproduce internally and post any updates/questions on this thread.

**Comment by zachbai** [comment] 2023-08-31 17:51
Hey all, sorry to hear this -- understand this must be frustrating.

Does the issue persist with a shell other than zsh? If you were to change the default shell to bash or fish, for instance. Settings > Features > Startup shell for new sessions
![image](https://github.com/warpdotdev/Warp/assets/10970845/62539b2d-0515-49d6-8769-d17aa38a9650)

**Comment by gilly87** [comment] 2023-09-11 12:36
> Hey all, sorry to hear this -- understand this must be frustrating.
> 
> Does the issue persist with a shell other than zsh? If you were to change the default shell to bash or fish, for instance. Settings > Features > Startup shell for new sessions ![image](https://user-images.githubusercontent.com/10970845/264734372-62539b2d-0515-49d6-8769-d17aa38a9650.png)

I had this issue and switching to bash was fine, so I assumed it was zsh config related as I have made changes to .zshrc recently. For me it turned out to be setop KSH_ARRAYS, once I removed this zsh worked fine again.

**Comment by zachbai** [comment] 2023-09-12 18:02
@gilly87 Oh thats interesting -- yeah, if that option is set, the shell will misinterpret our integration scripts. Thanks for the info; we should be able to get a fix in for this.

**Comment by gilly87** [comment] 2023-09-13 11:46
@zachbai 

No problem, glad to help. Love warp, keep up the good work!

**Comment by dannyneira** [comment] 2023-12-28 22:08
@saeedesmaili This has been resolved in a recent Warp release. Closing as resolved, but please update and let us know if the issue persists.

**Closed by dannyneira** 2023-12-28 22:08 UTC
Labels: Bug

**Comment by Samir-Giripunje** [comment] 2024-03-09 09:37
Hey even i am facing the same thing. Initially when i downloaded the warp-terminal it shown preset of starship which was tokyo-night for me. But i then downloaded other preset without removing the before one. From this time i cannot see the presets. I tried removing all the presets and uninstalling the warp and then downloading it again but it is not working. I can see my presets on the default terminal of the linux mint but I am not able to see it on the warp terminal.
