### ISSUE TITLE
Unable to use Warp as shell for .command files

### ISSUE THREAD

**Issue by phubbard** [warpdotdev/Warp#2309] opened 2022-12-07 03:05 UTC
### Describe the bug

As part of using Multipass, you can tell it to use another terminal app to launch shells:

https://multipass.run/docs/changing-terminal

This works with terminal and iterm2, but in Warp it seems to change the directory? It definitely doesn't run the command.

### To Reproduce

Install Multipass (free, open source, Homebrew)

Follow the directions in https://multipass.run/docs/changing-terminal to select Warp.

Try to open a shell. 

### Expected behaviour

Shell inside the container.

### Operating System

MacOS

### OS Version

12.6.1

### Shell Version

zsh 5.8.1

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2022-12-07 18:21
Thanks for submitting, this is a known issue with opening Warp from finder #102 
Closing as duplicate of #1917

**Closed by dannyneira** 2022-12-07 18:21 UTC
Labels: Bug
