### ISSUE TITLE
Start Warp window(s) with a saved launch configuration

### ISSUE THREAD

**Issue by Drallas** [warpdotdev/Warp#5377] opened 2024-10-13 07:41 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

I went through the settings but couldn’t find an option to open new Warp windows with a saved launch configuration. I think this would be a valuable feature to have available.

### Is your feature request related to a problem? Please describe.

When (re)start Warp

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-10-15 17:33
Thanks for submitting this @Drallas!

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2166

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-10-15 17:33
Duplicate of https://github.com/warpdotdev/Warp/issues/2166

**Closed by dannyneira** 2024-10-15 17:33 UTC
Labels: Feature requests
