### ISSUE TITLE
Make update checks optional

### ISSUE THREAD

**Issue by eighteyes** [warpdotdev/Warp#3058] opened 2023-05-12 17:02 UTC
### Describe the solution you'd like?

```Text
Just an option to check for updates, I work on a non-admin profile, and while it's awesome to know you're updating constantly, it's annoying to manually do it.
```

### Is your feature request related to a problem? Please describe.

```Text
I hate manually updating.
```

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-05-12 22:07
Thanks for this feature request! 

Please add a :+1: to the original post at the top to signal that you want this feature, and then hit the subscribe button if you'd like to be notified.

Also, please see some related feature requests here:
https://github.com/warpdotdev/Warp/issues/1991
https://github.com/warpdotdev/Warp/issues/1189
https://github.com/warpdotdev/Warp/issues/1723

**Comment by PheysX** [comment] 2023-06-07 08:23
I can't update it myself because i'm on a non admin profile and i can't talk to the admin every day. 😆

**Comment by dannyneira** [comment] 2024-06-28 16:34
Hi Folks, we will be tracking this request over at https://github.com/warpdotdev/Warp/issues/1991

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

Also, @PheysX you can work around this issue by manually [updating Warp](https://docs.warp.dev/help/updating-warp) if you don't have admin permission on your user account.

**Comment by dannyneira** [comment] 2024-06-28 16:38
Duplicate of #1991

**Closed by dannyneira** 2024-06-28 16:38 UTC
Labels: Feature requests
