### ISSUE TITLE
No output at all

### ISSUE THREAD

**Issue by mostlydev** [warpdotdev/Warp#4162] opened 2024-02-09 20:05 UTC
### Discord username (optional)

saltylimesoda

### Describe the bug

I see no output in terminal at all.  The commands run, but the area above the input panel is always blank.

### To reproduce

1. Open warp
2. Run any command
3. Observe nothing at all.

### Expected behavior

I should see the output of my commands.

### Screenshots

<img width="1275" alt="image" src="https://github.com/warpdotdev/Warp/assets/67087/49ad3dd7-0111-4709-a967-80cd8d21be7f">

### Operating system

MacOS

### Operating system and version

14.2.1

### Current Warp version

v0.2024.02.06.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

None

### Additional context

I'm using fish as my main shell, but letting warp use its own.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by mostlydev** [comment] 2024-02-09 20:15
I've deleted both the `Preferences` and Application Support subfolders.  No change.

**Comment by dannyneira** [comment] 2024-02-09 22:31
Hi @mostlydev Sorry to hear about this. What shell are you running? Warp only supports bash/zsh/fish currently. If using one of those, please run `which <your shell>` and put the resulting path/binary into the `Settings > Feature > Startup shell for new sessions > Custom` field. See my example with `which zsh` below.

![CleanShot 2024-02-09 at 15 30 56](https://github.com/warpdotdev/Warp/assets/16809145/72fdc9ae-df9f-4575-8f1d-48f8fb31466c)

This may help with the issue.

**Comment by elviskahoro** [comment] 2024-02-12 19:06
Can you send us a video @mostlydev

**Comment by mostlydev** [comment] 2024-02-12 19:21
Hi. Thanks for reaching out

I'm using fish installed via homebrew on macOS arm64 and I've already pasted that binary path into settings prior to opening this issue.

Im wondering if this isn't some interaction with my prompt. I'm using oh my fish. 

Here's a video:
https://www.loom.com/share/cf2f0e9f44e348eeb5f8c63f03ec1776

**Comment by dannyneira** [comment] 2024-02-12 20:10
@mostlydev You may be right about the prompt interaction as far as I'm aware, Warp doesn't support oh-my-fish prompt.

You can try disabling just the oh-my-fish prompt parts of your `config.fish` file just for Warp by using this conditional statement:

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here (oh-my-fish prompt code) <
end
```

**Comment by mostlydev** [comment] 2024-02-12 21:36
Thanks, so the issue was iTerm2 shell extensions.  This fixed it:

```
if test "$TERM_PROGRAM" != "WarpTerminal"
  test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish
end
```

Sounds like something you might want to address.  People who use both iterm2 and warp are going to be pretty common.

**Comment by dannyneira** [comment] 2024-02-13 23:47
Thanks for following up. It's good to know Warp "unofficially supports" oh-my-fish prompt, I'll make sure to add that to the list in our docs. Regarding the integration, its a common issue and we may have to develop a way to scan for and ignore such integrations in the rc files before bootstrapping Warp sessions. 

Closing as resolved since we found the culprit.

**Closed** 2024-03-01 04:17 UTC
Labels: Bugs

**Comment by tuxfamily** [comment] 2025-07-18 11:43
@mostlydev Oh, thanks for this! More than a year later, the issue is still there, and I was wondering, "Why does everyone love Warp? I can't even do a simple `ls`." 🤣 Now I'll be able to give it a real try and see if it can replace my beloved iTerm2 😉
