### ISSUE TITLE
Support non-shell (REPLs) based subshells in Warp

### ISSUE THREAD

**Issue by thegedge** [warpdotdev/Warp#64] opened 2021-07-24 18:59 UTC
** Running list of non-shell based [REPLs](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop) without Warp features ( i.e. Blocks, Autocomplete) **
-  irb, ipython, pipenv, psql, node, mongosh, rails, screen, nix-shell, etc.

** Current list of shell-based [subshells Warp supports](https://docs.warp.dev/features/subshells#how-to-warpify-the-subshell) **
- bash, zsh, fish, gcloud compute ssh, eb ssh, poetry shell, sudo su, etc.

**Comment by zachlloyd** [comment] 2021-07-24 20:16
Yeah i think the right UI for this is to continue doing blocks but with some indication that you are in a subshell, similar to how we handle ssh.  This should be doable.  Please upvote if you want it.

**Comment by elviskahoro** [comment] 2022-01-20 07:42
Differentiating User Shells And Subshells

From @shankarshastri via #220

### Describe the solution you'd like?

```shell
It would be great based on the context, to show to users that currently in shell or subshell mode (For example docker shell container id for docker exec, and in case of ssh to ssh and hostname)
```


### Is your feature request related to a problem? Please describe.

```shell
It's always a challenge to know whether we are in actual shell or any subshells.
```


### Additional context

_No response_

**Comment by elviskahoro** [comment] 2022-01-20 08:25
Poetry (python) creates a subshell. Would be nice if this was supported as well.

**Comment by Liu-Da** [comment] 2022-04-11 09:59
> Poetry (python) creates a subshell. Would be nice if this was supported as well.

Are there any plans or roadmaps for this feature?

**Comment by Liu-Da** [comment] 2022-04-11 10:01
Are there any plans or roadmaps for supporting the sub-shell feature?

**Comment by sweetyclem** [comment] 2022-04-13 12:47
Hi, in a ruby on rails console I have the same issue. Thanks for looking into it!

**Comment by elviskahoro** [comment] 2022-04-15 07:54
### Describe the bug

```text
On the MBP v12.2.1 native terminal, when I open up `psql`,I can navigate via Option + Left/Right arrow and modify my queries, but this behavior isn't compatible in Warp. Instead, I just get a space in the shell.
```


### To Reproduce

Steps to reproduce:
1. Open `psql`
2. Type out a query like `select * from users`
3. Try to navigate via Option + Left Arrow to replace `*` with specific columns.
4. See that the cursor is moved to the right for some reason 🤷.


### Expected behaviour

```text
I would expect to be moved to the next "word" in the direction of the arrow key I choose while holding Option.
```


### Screenshots

_No response_

### Operating System

MacOS

### OS Version

12.2.1

### Additional context

_No response_

**Comment by jwickers** [comment] 2022-04-19 02:22
Having Warp work with DB subshells would be huge. Those are the places where we often have to type and edit very long commands and basically where Warp would bring a lot of value.

**Comment by junyicc** [comment] 2022-06-13 10:28
Encountered the same issue in subshells:
- mongo shell
- mycli command line
- ...

Currently, we can do the same things by
- `Esc + B` to move cursor to the beginning of the current word
- `Esc + F` to move cursor to the end of the current word
- `Ctrl + W` to delete whole word

But, it's not convenient and friendly. Looking forward to the shortcuts support in subshells by `OPTION/CMD + ARROW LEFT/RIGHT or BACKSPACE`

**Comment by petrbouchal** [comment] 2022-08-05 10:03
Not sure if this is the same issue, but in `micro` some shortcuts also don't work. Notably Opt+Backspace to delete whole previous word, which only deletes one character. The shortcut works as expected in iTerm2 but not in Mac Terminal. 

Opt+Left Arrow works in all three environments inside `micro`.

**Comment by pzoomin** [comment] 2022-08-24 13:11
I think I have another use case surfacing this issue. When using `psql`, the pager appears broken.

Eg in psql, when running a `SELECT` query, or doing something like `\d <table name>`, I  very briefly see the results of the query, but then Warp scrolls downward at very quick speed (warp speed?) and all I get is a buffer full of
 
```
~
~
~
(END)
```
I can't scroll back up to see content.

If I first disable the pager in psql, eg `\pset pager 0` then I don't get this behavior.
Also, if I run this in another terminal program (eg the stock mac terminal program), I also don't get this behavior, so this does appear to be something specific to Warp and not my postgres installation.

**Comment by ToontjeM** [comment] 2022-09-02 11:16
+1

**Comment by Soromeister** [comment] 2022-09-15 19:56
Not only that, but it's tremendously slow when navigating through text after doing `exec <shell>` and trying to edit a long command.

**Comment by llam15** [comment] 2022-09-27 18:07
Just want to +1; love using Warp in general, but it's basically unusable if I'm in a subshell such as `poetry shell` or `aws-vault exec` or a tunnel into an ECS container etc

https://user-images.githubusercontent.com/10479740/192603263-844bc4f9-14ba-40a3-a569-fae0d0deac03.mov

**Comment by warpdotdev-dx** [comment] 2022-10-11 06:55
There are plans but no ETA!
- elvis

**Comment by kchawla-pi** [comment] 2022-10-27 16:59
Whenever developing (80% of my terminal use), I have to stop using Warp.
Please share some update about the progress.  A public alpha build so we can help test and give feedback.
Can we see some slow but steady progress on this.

**Comment by ocawthorne** [comment] 2022-10-29 02:56
I just heard about Warp today and started using it, but this is a pretty major setback. Definitely will try to use it as much as I can because the features are amazing, but I'd love to be able to use it 100% of the time rather than 15% of the time.

**Comment by donwlewis** [comment] 2022-10-31 16:38
I switch between shells a bit, so support for this would be great.  Example is I use fish as my default shell, but at times need to switch to zsh/bash/powershell.

**Comment by pheen** [comment] 2022-11-01 17:04
There can't be enough emphasis, this feature can make the difference whether Warp is usable as a main terminal or not.

>  ... the right UI for this is to continue doing blocks but with some indication that you are in a subshell ...

While this would be really cool, if it's possible to push out a simpler in-term build that just forwards on the keystokes to the sub-shell or something to allow the word navigation then you will have implemented 90% of what most users are after here (I believe). The sub-shell blocks can be a nice-to-have that can come later.

**Comment by kchawla-pi** [comment] 2022-11-01 17:43
> I switch between shells a bit, so support for this would be great. Example is I use fish as my default shell, but at times need to switch to zsh/bash/powershell.

I don't think this is the same thing as that being requested in this thread. You are talking about different shell programs. The issue is for different virtual environments executed via sub-shells (but using the same shell program).

**Comment by elviskahoro** [comment] 2022-11-01 19:27
@kchawla-pi 
Still no ETA on this feature. It's definitely something that's non-trivial.

@donwlewis  -> @kchawla-pi is correct here. There are plans to create a generic shell if there are other shells you'd like to see supported outside of Bash, Zsh, Fish. Here's the link to that discussion:
https://github.com/warpdotdev/Warp/discussions/64

**Comment by donwlewis** [comment] 2022-11-01 20:12
@elviskahoro  Maybe I am misunderstanding, but I think this still qualifies because in my scenario, I am executing zsh/bash as a sub-shell within fish.  Please correct me if I am wrong.

**Comment by elviskahoro** [comment] 2022-11-02 02:44
OH I see. Thanks for clarifying! This is the right issue to keep an eye on. I'll let you know if we end up making smaller more specific sub-issues.

**Comment by Soromeister** [comment] 2022-11-02 19:43
> There can't be enough emphasis, this feature can make the difference whether Warp is usable as a main terminal or not.
> 
> > ... the right UI for this is to continue doing blocks but with some indication that you are in a subshell ...
> 
> While this would be really cool, if it's possible to push out a simpler in-term build that just forwards on the keystokes to the sub-shell or something to allow the word navigation then you will have implemented 90% of what most users are after here (I believe). The sub-shell blocks can be a nice-to-have that can come later.

It would be really nice to have, but definitely not easy to implement. I believe this has the potential to break text editors (like vim) when executing so some sort of shell detection mechanism must be in place, else it will behave like any other software that takes control over the input (like emacs or vim).

**Comment by taypo** [comment] 2022-11-10 20:37
Just plain `sudo su -` is also causing this.

**Comment by James4Ever0** [comment] 2022-11-12 06:08
+1

**Comment by xyzzy314** [comment] 2022-11-13 03:17
As @taypo pointed out, this issue also impacts sudo, or su.  Sometimes I just need to sudo into zsh or bash to do many tasks as root, rather than prefacing a thousand things with sudo, but, once I do invoke "sudo zsh" or "sudo bash", warp treats everything from that point on as one block.  Defeats some of the point, and magic, of using Warp!

**Comment by jmouka** [comment] 2022-11-16 17:57
I got here from issue #807, so I'll just echo that request, to be able to use CMD or OPTION + arrow keys when in REPLs like pry, irb, etc. Blocks in subshells would be awesome! Thanks!

**Comment by Kloenk** [comment] 2022-11-20 13:32
This is also a problem with nix shell, where I install a new program only in a Childs zsh process, so the path inside of that is changed, therefor a new zsh has to be created.

**Comment by dannyneira** [comment] 2022-11-23 22:21
Comment from #2217 
> Pretty enjoy the IDE-style editor, especially the ability of selecting the text to delete it. 
So I'm wondering is it possible to support this feature in REPLs, e.g., python, psql, ... 🤔

**Comment by oleg-savko** [comment] 2022-12-02 09:17
+1
without this feature, warp become useless in 90% of work

**Comment by siw36** [comment] 2022-12-16 07:51
As mentioned by others before sub shell support is desperately needed.
I use containers running on my mac that provide me various tools with a fixed version and included dependencies for my daily work.
Sadly Warp loses all its glory as soon as I enter a container shell (docker exec -it toolbox bash).

+1 to increase the priority of this feature.

By the way I'm a big fan and I would love to use warp as my go-to terminal.

**Comment by dshpindler** [comment] 2022-12-18 09:50
+1 this is probably the most important feature that Warp is missing

**Comment by volopivoshenko** [comment] 2022-12-19 11:33
+1 without this is very important feature for the `warp`

**Comment by wiktormarchewka** [comment] 2022-12-21 07:50
+1

**Comment by LeEnno** [comment] 2022-12-21 11:13
Here’s a suggestion:

- Let’s not create any more “I also need this (because of X)” comments. This is one of 3 pinned issues. The team is very well aware of its popularity. No more use cases needed. It only creates noise in people’s inboxes. 
- Promote warp to people who might like it. Also tell them they need to upvote this issue. This way we get subshell support prioritized which is probably what you want to achieve by posting a comment.

**Comment by dannyneira** [comment] 2022-12-22 18:29
Hi Folks, this is officially on the roadmap! We appreciate all the interest in this feature and want to make the dream a reality. No firm ETA, but it's being investigated.

**Comment by aryan-jain** [comment] 2023-02-08 19:31
I know it's already been mentioned that we should no longer post use-cases on this thread. But since there's no firm timeline on when we would actually get sub shell support, I want to try using a workaround for my use-case in the meanwhile. 
I have a bash script that queries a database of machine IPs, usernames and passwords and executes an ssh command to log me into any machine that I name in args when executing the script. Something like: 
```sh login.sh -i machine1```
This logs me in to the machine but of course since the `ssh` command is being invoked within the bash script, the `warp_ssh_helper` never gets called and I go back to having an almost unusable shell experience. I was wondering if any of the devs can point me to where the `warp_ssh_helper` is defined and possibly a way for me to directly invoke it within my bash script.

**Comment by joelee** [comment] 2023-02-13 19:21
I've been evaluating `warp` for the last 2 hours. I can only switch from iTerm once this feature is available. On iTerm, I can set different shell sessions. I also use NuShell and PowerShell (for work 🤦 ) on iTerm.

**Comment by zachbai** [comment] 2023-02-13 20:04
There is no firm timeline at the moment, but blocks and input editor integration for nested zsh/bash/fish sessions (spawned as a result of `poetry shell`, `gcloud ssh`, `docker exec` and the like)  is under active development.

@aryan-jain Warp's ssh wrapper function is declared and sourced as part of Warp's startup script when a new session created (e.g. new tab/window/pane creation).  You should be able to directly call it with the same arguments as you'd supply to `ssh` if calling directly from the command line.  However, shell scripts are executed in a sub-shell (where Warp's startup script never ran and thus warp_ssh_helper isn't declared). This is kind of a hacky workaround, but you could alternatively `source` your script, in which case it would run within the current session where the ssh wrapper is decleared (e.g. `source login.sh -i machine1`)

**Comment by kchawla-pi** [comment] 2023-02-28 03:00
I was looking into using [direnv](http://direnv.net) to modify the python executable path to have the functionality of a sub-shell without  spawning a sub-shell, thinking that will allow me to use Warp's features for my dev work.

But before I did that, on a whim, I tried:
```bash
mamba init warp
```
(`mamba` is an alternate implementation of `conda`).
Then I didn't source or start a new terminal o I don't think the above did anything, but I am documenting what I did.
Then I proceeded with
```bash
mamba activate <env-name>
```
And It activated the new env, while retaining all Warp functionality.

What's going on? Has the support been included, piecemeal?

**Comment by zachbai** [comment] 2023-02-28 18:04
@kchawla-pi as far as I can tell, you're not actually spawning a subshell; instead you're activating a virtual environment within a top-level shell session, which has always been supported by Warp.  This issue is tracking Warp integration with nested `bash`/`fish`/`zsh` shell sessions. One of the use cases for a nested shell session is [Poetry's](https://python-poetry.org/) `poetry shell` command, which spawns a subshell and activates a virtual environment within it. Let me know if you need any further clarification!

**Comment by cmolina** [comment] 2023-03-12 20:41
I think this is also happening when running `nix-shell` https://nixos.org/guides/nix-language.html#reading-nix-language

**Comment by therealpaulgg** [comment] 2023-03-13 19:45
Also getting poor navigation experience with [chatgpt-wrapper](https://github.com/mmabrouk/chatgpt-wrapper)

**Comment by duttaoindril** [comment] 2023-03-17 08:59
> I've been evaluating `warp` for the last 2 hours. I can only switch from iTerm once this feature is available. On iTerm, I can set different shell sessions. I also use NuShell and PowerShell (for work 🤦 ) on iTerm.

I'm in a similar situation. Would really love nushell #2419 and other subshell support.

**Comment by VirrageS** [comment] 2023-03-19 12:06
The same problem when using [ET](https://eternalterminal.dev/), navigation and support for blocks is lost.

**Comment by generalpiston** [comment] 2023-03-21 05:05
#2796 was closed in favor of this ticket. Copying over the description of the other ticket...

> When using psql with Left option as meta, I expect that I can move forward 1 word and backwards 1 word using Option-f and Option-b, respectively. It does not do that. Instead I get ƒ and ∫.

And...

> It works outside of psql.

I haven no work around.

My understanding is that `psql` is readline based and I may be able to use `.inputrc` to get it working. I have no existing solution though.

**Comment by uzaxirr-fam** [comment] 2023-04-01 04:20
And when I do `poetry shell` in warp, I stop receiving autocomplete and AI features of warp. Hope supporting this is also in plans

**Comment by dannyneira** [comment] 2023-04-03 16:20
adding `nix-shell` to the list 🤞

**Comment by dannyneira** [comment] 2023-04-17 21:58
adding `julia` to the list

**Comment by AbhimanyuAryan** [comment] 2023-04-17 23:29
I would appreciate it if Julia subshell could be supported. Thanks 🙏

**Comment by xaviRodri** [comment] 2023-04-20 20:25
Could we add Elixir's `iex` to the list too? 🙏

**Comment by evelant** [comment] 2023-05-08 20:44
Aw man, this is disappointing. I just discovered Warp, got excited, and now find out that it doesn't support nushell. The rusty terminal should work with the rusty shell! As cool as Warp is I can't give up nushell so it's back to iterm for now.

**Comment by miohtama** [comment] 2023-05-12 22:54
Good work guys! Warp is the best thing happened to UNIX command line since zsh.

Another command not yet mentioned is `sudo`.

I am working on a server and often I need to use `sudo -i -u` to switch users. When sudo spawns a new shell, the Warp block mode is lost.

**Comment by llam15** [comment] 2023-05-19 14:38
The new subshell capability is hands down the best feature! A few things I have noticed:
-  When I'm in a subshell of my subshell, such as running `python manage.py` inside of a `docker exec`, the `^D` shortcut for `exit` does not seem to register. I can only exit the sub-sub-shell by typing `exit()` explicitly.
- If I try to warpify the following command: `docker compose exec my-container python manage.py shell_plus` , I get `IndentationError: unexpected indent`

```
[ -z $WARP_BOOTSTRAPPED ] && echo $0 | grep -q zsh && unsetopt ZLE && eval 'unsetopt ZLE;WARP_SESSION_ID="$(date +%s)$RANDOM";_hostname=$(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null
 || uname -n);_user=$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);_msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"zsh\", \"
user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;unset _hostname _user _msg;' || [ -z $WARP_BOOTST
RAPPED ] && echo $0 | grep -q bash && eval 'stty raw;unset PROMPT_COMMAND;HISTCONTROL=ignorespace;HISTIGNORE=" *";WARP_SESSION_ID="$(date +%s)$RANDOM";_hostname=$(command -v hostname >/dev/null 2>&1 && command
hostname 2>/dev/null || uname -n);_user=$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);_msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"
shell\": \"bash\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;unset _hostname _user _msg;'
 || [ -z $WARP_BOOTSTRAPPED ] && [ $FISH_VERSION ] && eval 'set -g WARP_SESSION_ID (random);set _hostname $(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n);set _user $(command -
v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);set _msg $(echo -n "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"user\": \"$_user\", \"hostname\": \"$_hostname
\", \"shell\": \"fish\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");echo -n \u1b\u50\u24"d$_msg"\u9c;set -e _hostname _user _msg;'
  File "<bpython-input-3>", line 1
    [ -z $WARP_BOOTSTRAPPED ] && echo $0 | grep -q zsh && unsetopt ZLE && eval 'unsetopt ZLE;WARP_SESSION_ID="$(date +%s)$RANDOM";_hostname=$(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null
|| uname -n);_user=$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);_msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"zsh\", \"u
ser\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;unset _hostname _user _msg;' || [ -z $WARP_BOOTSTR
APPED ] && echo $0 | grep -q bash && eval 'stty raw;unset PROMPT_COMMAND;HISTCONTROL=ignorespace;HISTIGNORE=" *";WARP_SESSION_ID="$(date +%s)$RANDOM";_hostname=$(command -v hostname >/dev/null 2>&1 && command h
ostname 2>/dev/null || uname -n);_user=$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);_msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"s
hell\": \"bash\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;unset _hostname _user _msg;'
|| [ -z $WARP_BOOTSTRAPPED ] && [ $FISH_VERSION ] && eval 'set -g WARP_SESSION_ID (random);set _hostname $(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n);set _user $(command -v
 whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);set _msg $(echo -n "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"user\": \"$_user\", \"hostname\": \"$_hostname\
", \"shell\": \"fish\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");echo -n \u1b\u50\u24"d$_msg"\u9c;set -e _hostname _user _msg;'
    ^
IndentationError: unexpected indent
>>>
```

Happy to open separate issues if that's preferred! None of these are blocking, of course.

**Comment by zachbai** [comment] 2023-05-19 17:27
Hi all, some exciting news:

Support for "Warpifying" bash, zsh, and fish subshells is launched in the latest release (v0.2023.05.18.01.08.stable_04)! 

In Warpified subshell sessions, Warp's features like blocks, input editor, completions, etc work the same way they do in 'top-level' shell sessions.

By default, Warp recognizes the following commands and displays a banner prompting you for Warpification: 
*  `docker exec ... (zsh|bash|fish)`
* `gcloud ssh ...`
* `eb ssh ... `
* `poetry shell`
There's more detail on how to use and configure the feature in our docs: https://docs.warp.dev/features/subshells.

For the sake of clarity - Warpifying non-shell REPLs like `python` , `irb`, `psql` etc is not yet supported -- this is on the long term roadmap but includes a whole new set of challenges and likely won't be built for a while.  That being said, I'm hearing from this thread that the big pain point is keyboard navigation, and I think we can improve this in the near term, short of full-on Warpification/block integration.

**Comment by zachbai** [comment] 2023-05-19 17:32
@llam15 Thanks for the feedback!  

> When I'm in a subshell of my subshell, such as running python manage.py inside of a docker exec, the ^D shortcut for exit does not seem to register. I can only exit the sub-sub-shell by typing exit() explicitly.
Mind filing a separate GH issue for this? We should be able to prioritize a fix for this shortly.

Additionally, just to be clear, is `python manage.py shell_plus` dropping you into a Python REPL? If so -- I think your second bullet point is to be expected. At this point, only bash, fish, and zsh shells are eligible for Warpification.

**Comment by Slawikus** [comment] 2023-05-19 17:59
> Support for "Warpifying" bash, zsh, and fish subshells is launched in the latest release (v0.2023.05.18.01.08.stable_04)! 
>
> By default, Warp recognizes the following commands and displays a banner prompting you for Warpification: 
> 
> * `poetry shell`

Wow, that's great news!!! Will it work with `pipenv shell` similar to poetry?

**Comment by dannyneira** [comment] 2023-05-19 18:33
@Slawikus Warp automatically recognizes the commands [Zach mentioned above](https://github.com/warpdotdev/Warp/issues/64#issuecomment-1555005863) as subshell-compatible. We'll update our docs and this thread if/when any others are added to the supported list. https://docs.warp.dev/features/subshells#how-to-warpify-the-subshell

**Comment by Evian-Zhang** [comment] 2023-05-20 01:33
It seems like subshells spawned by `sudo su` does not be warpified in the latest v0.2023.05.18.01.08.stable_04 release. Switching to root user is frequently used for network engineers where most commands need administrator privilege, and currently using Warp with `sudo su` is just like a normal terminal which does not do anything magical.

**Comment by zachbai** [comment] 2023-05-20 02:39
@Evian-Zhang thanks for the feedback --

For commands that are not automatically recognized for Warpification (including `sudo su`), you can follow the directions in our docs [here](https://docs.warp.dev/features/subshells#automatically-warpify-subshells) to manually mark it as a 'Warpifiable' command.

On subsequent executions, the Warpify banner will be shown and you'll be able to Warpify the session.

Feel free to follow up on the thread if you encounter any issues!

**Comment by Athorcis** [comment] 2023-05-24 07:19
Are subshells supposed to work on a remote machine?

**Comment by sebdanielsson** [comment] 2023-05-24 08:46
I'm getting the following error when clicking on Warpify after adding sudo su to the commands:

```sh
sh-3.2#  [ -z $WARP_BOOTSTRAPPED ] && echo $0 | grep -q zsh && unsetopt ZLE && eval 'unsetopt ZLE;WARP_SESSION_ID="$(date +%s)$RANDOM";_hostname=$(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n);_user=$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);_msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"zsh\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;unset _hostname _user _msg;' || [ -z $WARP_BOOTSTRAPPED ] && echo $0 | grep -q bash && eval 'stty raw;unset PROMPT_COMMAND;HISTCONTROL=ignorespace;HISTIGNORE=" *";WARP_SESSION_ID="$(date +%s)$RANDOM";_hostname=$(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n);_user=$(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);_msg=$(printf "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"shell\": \"bash\", \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");printf '"'"'\x1b\x50\x24\x64%s\x9c'"'"' $_msg;unset _hostname _user _msg;' || [ -z $WARP_BOOTSTRAPPED ] && [ $FISH_VERSION ] && eval 'set -g WARP_SESSION_ID (random);set _hostname $(command -v hostname >/dev/null 2>&1 && command hostname 2>/dev/null || uname -n);set _user $(command -v whoami >/dev/null 2>&1 && command whoami 2>/dev/null || echo $USER);set _msg $(echo -n "{\"hook\": \"InitShell\", \"value\": {\"session_id\": $WARP_SESSION_ID, \"user\": \"$_user\", \"hostname\": \"$_hostname\", \"shell\": \"fish\", \"is_subshell\": true}}" | od -An -v -tx1 | command tr -d " \n");echo -n \u1b\u50\u24"d$_msg"\u9c;set -e _hostname _user _msg;'
```

**Comment by zachbai** [comment] 2023-05-24 18:44
Hey @sebdanielsson,

It looks like this is because the login shell for the root user in your machine is `/bin/sh`, which isn't one of Warp's supported shells.  Switching that login shell for root via `sudo chsh -s $(which <fish|bash|zsh>)` should change the root login shell to whichever shell you specify (fish/bash/zsh), all of which are supported by Warp. Let us know if this doesn't work for you.

That being said, we can probably do a better job of messaging that only bash/fish/zsh are supported. Or possibly look at ways to detect an unsupported shell while Warpifying and then notify you if so.

**Comment by shumkov** [comment] 2023-05-27 02:59
Thank you for this fantastic feature! Looking forward to an option in settings to automatically warpify all supported (whitelisted) shells. Updating RC files is fine for local shells but when you work with docker or ssh subshells a lot it's not very feasible.

**Comment by zachbai** [comment] 2023-05-30 15:38
Hey @shumkov, 

Makes sense that the RC file update isn't always practical with docker containers/remote hosts.

Automatic Warpification without an RC file is tough because, under the hood, Warpification is done by executing an initialization command that performs all the necessary setup for blocks, input editor, completions etc to work.

Basically, without the RC file update, Warp would have to know _if_ and _when_ it's ok to Warpify purely based on the executed subshell command. This is hard to do in a reliable way because the executed command doesn't always encode the shell (bash vs fish vs tcsh vs nushell) that is being spawned, and some of these shells are unsupported -- so it would put the subshell in a bad state if we just automatically tried to Warpify by executing the initialization command (which might contain invalid syntax or make assumptions that don't hold true in unsupported shells).

There might be some non-RC file-based workaround here, but it would still likely involve installation of some small binary or creation of some config file on the remote hosts where the subshells are being spawned, both of which I'm thinking are as intrusive (or more intrusive) than updating an RC file.  I could be wrong here, though! Also open to other suggestions, since it's obvious that automatic Warpification for all subshells would be the most ideal UX.

**Comment by evelant** [comment] 2023-05-30 16:59
Now that feature has landed is it more feasible to add first class support for nushell? Is that on the roadmap? Warp looks awesome but I can't leave nushell for an old style shell, it's just too good. Nushell combined with Warp would be the most amazing experience!

**Comment by zachbai** [comment] 2023-05-30 17:07
@evelant We're aware of the demand for nushell -- feel free to upvote #880! For the sake of transparency, it's not yet on the near-term roadmap (next 3 months or so), but agree it would be awesome to support and we're always re-evaluating what to build every quarter.

**Comment by Evian-Zhang** [comment] 2023-06-06 06:50
It is interesting that, I can't directly ssh into a FreeBSD machine with warpified shell (I use `/usr/bin/ssh` to work around), however, after I get into the FreeBSD, I invoke such Warpification command, and I can use Warp features in FreeBSD!

I just feel confused that what is the different between a subshell and a shell spawned by ssh. Why don't use the same technologies to enable Warp features across ssh-target and subshells spawned by other common commands?

**Comment by elviskahoro** [comment] 2023-06-06 16:59
Closing this out. We'll start taking follow up issues and requests as separate tickets (GitHub issues). Please create a new issue if something isn't working for you

**Comment by llam15** [comment] 2023-06-08 13:38
> @llam15 Thanks for the feedback!
> 
> > When I'm in a subshell of my subshell, such as running python manage.py inside of a docker exec, the ^D shortcut for exit does not seem to register. I can only exit the sub-sub-shell by typing exit() explicitly.
> 
> Mind filing a separate GH issue for this? We should be able to prioritize a fix for this shortly.


Sorry for the late reply, I did not get a notification for your reply 😓 

- I opened another issue for the first bullet point, with some more specific replication instructions: https://github.com/warpdotdev/Warp/issues/3186

> Additionally, just to be clear, is `python manage.py shell_plus` dropping you into a Python REPL? If so -- I think your second bullet point is to be expected. At this point, only bash, fish, and zsh shells are eligible for Warpification.

Yes you're correct, `python manage.py shell_plus` is a Python REPL. Thanks for the explanation! Hope Python REPLs be supported soon :)

**Comment by dannyneira** [comment] 2023-06-27 16:58
Locking this issue to help with notifications. We are aware of the demand for non-shell based subshells (REPLs). Any further updates will be posted on this thread by the Warp team.

**Comment by dannyneira** [comment] 2024-01-17 18:43
Hey folks, since this issue was originally for sh based subshell, we're closing as resolved.

We'll be tracking the REPLs non-shell based subshell in a new meta issue which will also contain comments for tracking each REPL (irb, ipython, pipenv, psql, node, mongosh, rails, nix-shell, etc.) here https://github.com/warpdotdev/Warp/issues/4082

Closing as completed since [Subshell support](https://docs.warp.dev/features/subshells) has been 
released and is working well.

**Closed by dannyneira** 2024-01-17 18:43 UTC
Labels: Feature
