### ISSUE TITLE
Shortcuts for Window Management Tool Magnets not working anymore /  Magnet shortcuts stop working

### ISSUE THREAD

**Issue by spren9er** [warpdotdev/Warp#776] opened 2022-02-24 07:33 UTC
### Describe the bug

I use an app called *Magnet* as window management tool.
It works for all my macOS applications and used to work also for *warp*.
Since updating *warp* to v0.2022.02.21.08.55.stable_00, all shortcuts for moving a warp window to a certain position on the screen don't work anymore.

Keyboard shortcuts used for *Magnet* are

- CTRL-Left-Arrow
- CTRL-Right-Arrow
- SHIFT-CTRL-Left-Arrow
- SHIFT-CTRL-Right-Arrow

### Operating System

MacOS

### OS Version

12.2.1

**Comment by elviskahoro** [comment] 2022-02-25 05:31
Can you try remapping magnet to a keybinding that doesn't exist in warp and seeing if that works? Like CTRL-ALT-CMD-H or something.

**Comment by sdaveas** [comment] 2022-02-25 16:06
Having the same issue. I think it started after the latest update. It doesn't seem to be a key binding collision. Magnet's options are generally inactive for Wrap.

<img width="1130" alt="Screenshot 2022-02-25 at 6 01 23 PM" src="https://user-images.githubusercontent.com/48155711/155747585-174eb4ac-64b6-4c23-ac42-04a4e6ab7187.png">

**Comment by estephinson** [comment] 2022-02-27 12:18
It is temperamental as well - after a fresh restart of Warp magnet works fine. Then in a flury of keypresses sometimes, when trying to do things potentially a little too quick, it get's stuck.

Is there any listening for keys Warp locks and then perhaps doesn't unlock?

**Comment by jdongelmans** [comment] 2022-03-02 10:12
Can confirm this issue. Same version(s) as above.

However I haven't managed to get a new instance of Warp to behave correctly again, so I'm a bit stuck managing by hand for now 🙂

**Comment by stephencweiss** [comment] 2022-03-02 15:28
@elviskahoro - are you saying that you expect Magnet's keybindings to be overwritten by Warp's?

**Comment by beet** [comment] 2022-03-03 23:58
Can reproduce consistently:

* open a new Warp window, and while ZSH is starting quickly:
* confirm that Magent's keyboard shortcuts can move the window around **while ZSH is starting**
* confirm that once it has a prompt, the window is frozen in place, and Magnet ceases being able to move it

**Comment by erikstorm** [comment] 2022-03-09 07:51
Also having this issue. None of my other applications seems to be affected by this.

I had just updated my macOS to `12.2.1` and Warp to `v0.2022.02.28.08.45.stable_02`. Magnet just seems to be disabled for this app.

**Comment by norman784** [comment] 2022-03-10 09:19
I have the same issue, but solved by using [rectangle](https://rectangleapp.com) instead of magnet, it offers the same behaviours and default shortcuts. I know isn't a proper fix, but at least I could continue using warp without disrupting my workflow.

**Comment by jjpiv** [comment] 2022-03-14 17:24
+1 for this issue.

**Comment by vorporeal** [comment] 2022-03-30 19:22
Hey all, this should be fixed in the release that just went out today.  Please let me know if you're still seeing any issues!

**Comment by beet** [comment] 2022-03-30 21:55
Awesome, working well with Magnet, thank you!

**Closed** 2022-03-31 06:55 UTC
