### ISSUE TITLE
poe ai integration

### ISSUE THREAD

**Issue by hbakhtiyor** [warpdotdev/Warp#3824] opened 2023-10-31 13:43 UTC
### Describe the solution you'd like?

```Text
integrate poe ai chatbot, instead of your outdated ai
```

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2024-03-06 18:55
Duplicate of https://github.com/warpdotdev/Warp/issues/3779

**Closed by dannyneira** 2024-03-06 18:55 UTC
Labels: Feature requests
