### ISSUE TITLE
Cannot log in to Windows system via ssh.

### ISSUE THREAD

**Issue by tetsuyasu** [warpdotdev/Warp#2027] opened 2022-10-31 01:32 UTC
### Describe the bug

When I try to log in to a Windows system via ssh, it fails with the following error.

```
ssh windowsmachine
ParserError:
Line |
   4 |  if test ${SHELL##*/} != bash -a ${SHELL##*/} != zsh; then
     |    ~
     | Missing '(' after 'if' in if statement.
Connection to windowsmachine closed.
```

### To Reproduce

Connect via ssh to a Windows machine running an OpenSSH server (Microsoft).

### Expected behaviour

I think this hook is superfluous.
```
ssh -vvv windowsmachine
debug1: Sending command:
                         hook=$(printf "{\\"hook\\": \\"SSH\\", \\"value\\": {\\"socket_path\\": \\"~/.ssh/166717896624683\\", \\"user\\": \\"%s\\", \\"machine\\": \\"%s\\", \\"remote_shell\\": \\"%s\\"}}" $(whoami) $(hostname) ${SHELL##*/} | command od -An -v -tx1 | command tr -d " \\n")
```

### Operating System

MacOS

### OS Version

13.0

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.10.25.08.06.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by dannyneira** [comment] 2022-10-31 22:39
Hi @tetsuyasu, Sorry to hear about this issue, I will set up my windows box with OpenSSH and attempt to repro this. I appreciate your patience and will provide updates here.

**Comment by dannyneira** [comment] 2022-11-01 20:20
Closing this as it's a duplicate of #1729, please subscribe to that issue and we will provide updates there. We appreciate your patience.

**Closed by dannyneira** 2022-11-01 20:20 UTC
