### ISSUE TITLE
New Window does not open to set size when app first launched

### ISSUE THREAD

**Issue by Depicus** [warpdotdev/Warp#4186] opened 2024-02-16 12:53 UTC
### Describe the bug

Opening the app gives a different window size to when app already open and new window open

### To reproduce

1. open app and window is normal size
2. set the column and rows in settings > appearance and turn on toggle to open custom size
3. close the app completely
4. open the app and the window is normal size
5. open menu and open a new window and it is the expected size

### Expected behavior

Both new windows should be exactly the same size

### Screenshots

<img width="1668" alt="Screenshot 2024-02-16 at 12 52 13" src="https://github.com/warpdotdev/Warp/assets/343795/efb72129-887d-49f1-bb04-bf6566b262f3">

### Operating system

MacOS

### Operating system and version

14.3.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.02.13.08.02.stable_00

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-02-16 16:47
Hi @Depicus Thanks for submitting. As far as I know the last window closed when you quit Warp with `CMD-Q` will retain the size that it's set to when opening Warp again. So if you close a custom-sized window last, then it will open with that same size. The setting is for opening new windows to custom size, but Warp still retains the memory of the last window closed in case you want to keep that size. Once you open a new window with `CMD-N`, it will be the custom size you set.

I'll make sure to add something in our docs to this effect so that it's clear that the setting doesn't set the size for the first window opened after closing Warp, that one will retain the size and not use the custom size. Hope this helps clear up the behavior.

https://github.com/warpdotdev/Warp/assets/16809145/241b7b43-8ca8-4445-beeb-d666f340dfa6

**Comment by dannyneira** [comment] 2024-02-16 16:50
Closing as this isn't a bug, but a specific behavior of Warp on macOS. You'll notice the same on iterm2 and other terminals.

**Comment by Depicus** [comment] 2024-02-16 16:53
It is a bug and you can close the large window last and it still not open large so no it's not specific to osx as Terminal does remember the set size, it's only Warp that has this issue.

**Comment by dannyneira** [comment] 2024-02-16 16:57
Yes you're correct, we have a duplicate issue tracking this here: https://github.com/warpdotdev/Warp/issues/4011

I'll bring this up with the team and we'll post updates there.Sorry if this is a blocker for you.

**Comment by dannyneira** [comment] 2024-02-16 16:58
Duplicate of https://github.com/warpdotdev/Warp/issues/4011

**Closed** 2024-02-29 21:44 UTC
Labels: Bugs
