### ISSUE TITLE
Global hotkeys not working when switching to 'Chinese - Pinyin' input source

### ISSUE THREAD

**Issue by mingyoung** [warpdotdev/Warp#5488] opened 2024-11-18 05:26 UTC
### Dupe Check

- [X] I have [searched Warp feature requests](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3A%22Feature+requests%22) and there are no duplicates

### Describe the solution you'd like?

When I switch input sources (Chinese - Pinyin), the global hotkeys do not work, they only work under the English input method.

My hotkey settings are: `

---

Settings:
<img width="663" alt="image" src="https://github.com/user-attachments/assets/1d3f7e5d-db46-47cd-ae1f-fe1d5c815f53">

Input sources:
<img width="259" alt="image" src="https://github.com/user-attachments/assets/5f170fff-23c6-402c-8813-714b85196478">

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by litian-98** [comment] 2024-11-20 06:44
This question is the same as question #341.

**Comment by dannyneira** [comment] 2024-11-25 18:30
Hi there @mingyoung you should track #341 as this is a duplicate of the issue. You may be able to work around this by rebinding your Global Hotkey while the Pinyin input source is enabled. This may help with the issue.

Closing as a duplicate, but please continue to track the other issue #341.

**Comment by dannyneira** [comment] 2024-11-25 18:31
Duplicate of #341

**Closed by dannyneira** 2024-11-25 18:31 UTC
Labels: Feature requests
