### ISSUE TITLE
Emoji Flags Not Displaying Correctly in Warp

### ISSUE THREAD

**Issue by Lendersmark** [warpdotdev/Warp#5454] opened 2024-11-06 11:57 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

I’m experiencing an issue with the display of emoji flags in Warp when using the MesloLGS Nerd Font. Specifically, emoji flags such as 🇮🇹 (Italy) are not rendering correctly in Warp, while the same setup works perfectly in iTerm2.

### To reproduce

	1.	Set Warp’s font to MesloLGS Nerd Font (the same font I use in iTerm2).
	2.	Run a Python command that prints an emoji flag, for example:

`print("\U0001F1EE\U0001F1F9")  # Unicode for 🇮🇹`

	3. Alternatively, use the command-line tool countryflag (use `pip install countryflag` to get it) to output an emoji flag directly:

`countryflag Italy`

### Expected behavior

The emoji flag 🇮🇹 should display correctly, as it does in iTerm2 with the same font.

Actual Behavior:

In Warp, instead of displaying the emoji flag 🇮🇹, it shows the letters “IT” as a placeholder, indicating that the flag emoji is not rendered correctly.

<img width="34" alt="image" src="https://github.com/user-attachments/assets/7a6a61cb-96b5-4c4e-9874-fdbb602c3259">

### Operating system

MacOS

### Operating system and version

Mac Os Sequoia 15.1

### Shell Version

zsh 5.9 (arm64-apple-darwin24.0)

### Current Warp version

v0.2024.10.29.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

	•	OS: macOS
	•	Font: MesloLGS Nerd Font (works correctly in iTerm2)
	•	Warp Version: v0.2024.10.29.08.02.stable_02
	•	Python Version: 3

This issue appears specific to Warp’s handling of emoji, as iTerm2 on the same system with the same font renders emoji flags correctly.

Possible Related Issues:

	•	Unicode handling for regional indicators
	•	Font rendering or emoji compatibility in Warp

Let me know if any additional details are needed!

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-11-08 22:15
Hi @Lendersmark thanks for the detailed bug report. This is a known issue we're tracking here. https://github.com/warpdotdev/Warp/issues/1995

I recommend you subscribe to that post for updates. I'll also copy your report there for more details on the thread.

Closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-11-08 22:16
Duplicate of #1995

**Closed by dannyneira** 2024-11-08 22:16 UTC
Labels: Bugs
