### ISSUE TITLE
Drag tabs outside the current window

### ISSUE THREAD

**Issue by drpiou** [warpdotdev/Warp#4204] opened 2024-02-21 13:50 UTC
### Describe the solution you'd like?

Hello!

I would love to drag tabs outside of their current windows. More than sometime but less than often, I want to "create" or merge Warp windows from tabs, the same way Chrome tabs works for example.

Thank you :)

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-02-21 23:16
Hey @drpiou Thanks for submitting this. We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/466

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-21 23:17
Duplicate of https://github.com/warpdotdev/Warp/issues/466

**Closed** 2024-02-29 21:45 UTC
Labels: Feature requests
