### ISSUE TITLE
Support double tapping (consecutive clicks) within the keybinding schema

### ISSUE THREAD

**Issue by elviskahoro** [warpdotdev/Warp#1410] opened 2022-05-26 22:05 UTC
### Describe the solution you'd like?

```text
Ability to double press a key and register it as a keybinding.
```

**Comment by dannyneira** [comment] 2023-05-16 19:08
We have a request tracking this over at #1240 

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Closed by dannyneira** 2023-05-16 19:08 UTC
Labels: Feature

**Comment by dannyneira** [comment] 2024-02-06 20:40
Duplicate of #2809
