### ISSUE TITLE
Warp automatically remove all the carriage return of prompt from starship

### ISSUE THREAD

**Issue by singlewind** [warpdotdev/Warp#2145] opened 2022-11-17 00:23 UTC
### Describe the bug

Warp prompt removed all the carriage return when combine use starship. For example, when we have the format as follow.

```toml
format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$rust$package
[└─>](bold green) """
```

Display as

```shell
┌───────────────────> | ~ └─>
``` 

### To Reproduce

Put following code in `~/.config/starship.toml` file. Then use choose `use my own prompt` in warp.

```toml
format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$rust$package
[└─>](bold green) """
```
 

### Expected behaviour

Display prompt as below

```shell
┌───────────────────> 
| ~ 
└─>
``` 

### Screenshots

<img width="341" alt="Screenshot 2022-11-17 at 10 10 45 am" src="https://user-images.githubusercontent.com/7637/202323609-ed2a5af1-1541-4896-a6f2-01da25e61077.png">

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.14.14.55.stable_01

### Does this block you from using Warp daily?

No

**Comment by elviskahoro** [comment] 2022-11-18 19:51
@singlewind We don't have support for multi-line prompts. tldr; the Input Editor and Prompt are both their own natively built GUI elements. We do have an open issue for multi-line prompt support, i'll try to merge this into that issue, at some point in the future.

**Comment by agluck91** [comment] 2022-11-23 16:32
Just wanted to plus one this, I am not able to use Starship's $line_break. This would make things a lot better for my prompt, I have a lot of info about my projects in my prompt that are important to my workflow. I am not the only one that wishes this would work as well. I have many friends that I convinced to come to warp that would love to see this option as well.

**Comment by dannyneira** [comment] 2022-11-28 23:44
Thanks for this request, closing as duplicate of #1015

**Closed by dannyneira** 2022-11-28 23:44 UTC
