### ISSUE TITLE
Setting the line-height

### ISSUE THREAD

**Issue by dominiquevilain** [warpdotdev/Warp#1294] opened 2022-05-06 08:23 UTC
### Describe the solution you'd like?

```text
Setting the font is a must of course, but some fonts have a large x-height and others a small one. Keeping the same line-height for every font can make it challenging to read especially with large x-heights. Lines look too close to each other and the whole display looks messy. 

I’d like to be able to set the amount of space between two lines of text, by setting the line-height or better, by setting some top padding and some bottom padding like in sublime-text.
```

**Comment by vorporeal** [comment] 2022-05-06 19:28
I see this as slightly different from #317 - to me, #317 is about the default values being incorrect (bug), whereas this is more focused on configurability (feature request).

**Comment by elviskahoro** [comment] 2022-07-09 05:23
Will use this as the line height issue!

**Comment by Advait-M** [comment] 2022-09-08 23:03
Hey @dominiquevilain @jamespearson @nicolasbinet 👋!

Advait from Warp here - thanks for the feature request, happy to say that we've just released it in our latest release! Please download Warp `v0.2022.09.07.14.56.stable_00` for this feature.

You can head over to Settings > Appearance to configure the line height (right beside the font customization). Note that this value represents the ratio of the line height to the font size (the default is 1.2). 

![image](https://user-images.githubusercontent.com/12927474/189218991-802bfb28-4b39-496f-bf9e-74eea3711e58.png)

You'll then see the changes applied instantly (in my case, changing it to be a more compact 1.0 below):

![image](https://user-images.githubusercontent.com/12927474/189220412-7d17b1ad-aacd-4d75-9764-f609dbdd8a8a.png)

Let us know if you have any questions or feedback on the feature! 😄 

Note that we've chosen to support line height for now since we felt it was most appropriate - if you'd still like individual top/bottom padding please open a separate issue on that front.

**Comment by nicolasbinet** [comment] 2022-09-09 08:44
@Advait-M Downloaded it. Tested it. Spacing makes me breath :)
That said when I compare with my previous iTerm theme. In warp line-height seems to impact the upper part of the text, not equally. It's visible with background colors.

Here are two screenshots of Webpack outputs with Warp & iTerm.

Warp :
![CleanShot 2022-09-09 at 10 42 48@2x](https://user-images.githubusercontent.com/867710/189309798-4c95f8f6-1f36-4d92-882c-92481fc688f4.png)

iTerm :
![CleanShot 2022-09-09 at 10 42 22@2x](https://user-images.githubusercontent.com/867710/189309686-5e7d92be-ec8c-4f12-993f-bae6a56c166f.png)

**Comment by Advait-M** [comment] 2022-09-09 11:45
Ah yep @nicolasbinet - thanks for bringing that up, you've got a sharp eye 😄. This was a conscious choice we made on text spacing: within the em-box for the line, we have 80% above the baseline and 20% below the baseline. We also match the spacing in the input editor with the block grid. http://www.dalaifelinto.com/?p=1343 goes into some of the discussion around baselines for text rendering, with respect to the font ascent/descent. If you think that we should instead be centering text - feel free to open a new issue, thanks!

**Comment by nicolasbinet** [comment] 2022-09-11 16:25
@Advait-M personally, I'd prefer the text to be centered vertically.
That said, I'm no designer. I'd like to see others share their thoughts.

**Comment by colepeters** [comment] 2022-10-07 17:42
I'm having an issue which I believe is related to the way text spacing is being computed, so this seems like the right place for this report, but let me know if I should open a new issue instead.

The text spacing configuration in Warp appears to be messing with ASCII box drawing. For example, here's some Neovim UI which uses box drawing characters in iTerm (see the borders on completion and signature popovers, and the box drawing characters used in the status line and file explorer):
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1713932/194616787-588c8123-eafc-46f6-80e3-f78b0dcea011.png">

Here's the same UI in Warp, with line height set to the default 1.2:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/1713932/194617131-e1c585b6-b89d-4231-b031-dba381f4d786.png">

Even with the line height set to 1 (which makes for really cramped reading), gaps still exist, and it also creates misalignment in the status bar:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/1713932/194616835-636105be-b3fe-438d-9072-06d59fad0781.png">

Aside from the noticeable vertical gaps, there's also some strange horizontal collisions, like this:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/1713932/194617351-f40dfdf2-52e0-40cd-9b8e-5ed40248066b.png">

Hope this helps, please let me know if I can provide further info!

**Comment by Advait-M** [comment] 2022-10-10 03:14
> I'm having an issue which I believe is related to the way text spacing is being computed, so this seems like the right place for this report, but let me know if I should open a new issue instead.
> ...
> Hope this helps, please let me know if I can provide further info!

Hey @colepeters - thanks for bringing this up and providing the screenshots! Hmm, this sounds somewhat similar to https://github.com/warpdotdev/Warp/issues/317 which we'd tackled in May. Since this is a bit different from being able to configure custom line heights, could you please open a new issue for this, so we don't lose track of it? Thanks!

**Comment by Advait-M** [comment] 2022-10-10 03:16
and for tracking purposes - closing this issue, pertaining to custom line heights specifically, as we've launched the feature (noted above)!

**Closed by Advait-M** 2022-10-10 03:16 UTC

**Comment by vorporeal** [comment] 2022-10-10 17:08
@colepeters Two questions about your issue:

1. Which font are you using?
2. Does this reproduce in iTerm if you turn off iTerm's custom box drawing logic?  (search for "box" in iTerm's advanced preferences pane, select "Yes" to use the characters from the font, then restart iTerm and see what it looks like).

**Comment by colepeters** [comment] 2022-10-10 23:41
New issue's been opened!

@vorporeal apologies, I just caught your questions after opening the new issue, however I've replied there!

**Comment by resetheadhard** [comment] 2024-06-01 22:13
> This was a conscious choice we made on text spacing: within the em-box for the line, we have 80% above the baseline and 20% below the baseline

Any chance this will be configurable? Settings like this butcher TUI layouts.

**Comment by iamjaredwalters** [comment] 2024-06-01 22:15
> This was a conscious choice we made on text spacing: within the em-box for the line, we have 80% above the baseline and 20% below the baseline.

Any chance this will become configurable? Settings like this butcher TUI's ☹️
