### ISSUE TITLE
Typeahead - Allow writing a new command when another is still running

### ISSUE THREAD

**Issue by MiguelSOliveira** [warpdotdev/Warp#827] opened 2022-03-22 11:20 UTC
### Describe the solution you'd like?

```text
I would like to be able to "prepare" another command while another is still executing.

For example:

I write "git checkout master".. It takes a couple of seconds..

I would like to be able to write "git pull", before the "checkout" command finishes, so it executes immediately after it's finished. I use this a lot in iterm and works quite well.
```

**Comment by elviskahoro** [comment] 2022-03-22 17:34
Duplicate of:
- #258

**Comment by elviskahoro** [comment] 2022-08-28 03:43
Gonna close since this seems to be working.

**Closed by elviskahoro** 2022-08-28 03:43 UTC
