### ISSUE TITLE
Support for groups of sessions

### ISSUE THREAD

**Issue by fahslaj** [warpdotdev/Warp#4666] opened 2024-03-31 20:38 UTC
### Describe the solution you'd like?

I'd love to see a way to organize open console sessions into "groups" or "folders". I find myself with 8+ tabs open at once when doing full stack development, and it would be great to be able to sort them and name the groups for easier access.

### Is your feature request related to a problem? Please describe.

I find myself with many tabs open at once relating to different problems and technologies. Keeping them in separate windows is annoying.

### How important is this feature to you?

2

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-01 16:30
Thanks for submitting this @fahslaj, as a possible stopgap, look into the [Launch Configurations](https://docs.warp.dev/features/sessions/launch-configurations), which lets you save a set of windows/tabs/panes.

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2314

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-04-01 16:30
Duplicate of https://github.com/warpdotdev/Warp/issues/2314

**Closed by dannyneira** 2024-04-01 16:30 UTC
Labels: enhancement
