### ISSUE TITLE
DUP: Duplicate of #058 - Move tabs like a browser's

### ISSUE THREAD

**Issue by kernelsoe** [warpdotdev/warp#549] opened 2021-12-27 02:30 UTC
### Describe the solution you'd like?

```shell
Thanks for this awesome warp.dev. I've been using it daily since I've received the early access.

---

It'd be great if we could arrange(click, drag and move) tabs around.

Because, when we called a new tab, most of the time we would like to rearrange tabs according what paths/projects we are currently working right now. 🙂
```

**Comment by elviskahoro** [comment] 2021-12-27 07:33
Closing, as this is a duplicate of:
- https://github.com/warpdotdev/warp/issues/58

**Closed** 2021-12-27 12:13 UTC
