### ISSUE TITLE
SSH Controlmaster is invalid

### ISSUE THREAD

**Issue by syymo** [warpdotdev/Warp#3269] opened 2023-06-28 08:20 UTC
### Describe the bug

`~/.ssh/config` set `ControlMaster auto`, but new tab Still need to log in

### To reproduce

tab1
```
ssh root@123.123.123.123
password:
// login success
```
new tab2
```
ssh root@123.123.123.123
password:
```
`~/.ssh/config`：
```
host *
ControlPersist yes
ControlMaster auto
ControlPath ~/.ssh/master-%r@%h:%p
```
ControlMaster is invalid

### Screenshots

![image](https://github.com/warpdotdev/Warp/assets/26571594/78548341-9669-4a17-9b05-6c9a44570839)
![image](https://github.com/warpdotdev/Warp/assets/26571594/fdf0b014-eb02-4004-afdd-c7e1086765cc)

### Operating system

MacOS

### Operating system and version

MacOS 13.4

### Current Warp version

v0.2023.06.20.08.04.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-08-28 22:35
Thanks for confirming. I'll let the team know and we'll post updates on this thread. 🙏

**Comment by micaww** [comment] 2023-09-28 15:41
This does happen to be a blocker for me and my team using Warp unfortunately 😢 

Almost all of our work is done via SSH and we have 2FA set up as well, which means every new session I have to start a new connection, get the 2FA code and plug it in. We have a lot of services running at once which means I usually have a lot of tabs/split screens open connected to various things. I would expect to `ssh blahblah` one time and have every other session share that connection.

Disabling the SSH Wrapper "works" but takes away the cool Warp features that I'm trying to use it for.

Warp looks really exciting and I'm hoping this will get resolved soon so I can come back to it!

**Comment by micaww** [comment] 2023-10-16 18:30
this _seems_ to not be an issue as of the last update. @dannyneira @syymo can you confirm if this has been fixed?

**Comment by dannyneira** [comment] 2023-10-16 19:05
I'm not able to reproduce the issue so closing as resolved, but please feel free to let us know if the issue persists @syymo

**Closed by dannyneira** 2023-10-16 19:05 UTC
Labels: Bug
