### ISSUE TITLE
DUP: Duplicate of #197 - No warning when trying to close window or quit Warp with processes currently running

### ISSUE THREAD

**Issue by fishcharlie** [warpdotdev/warp#556] opened 2021-12-31 02:14 UTC
### Describe the solution you'd like?

```shell
Warp to show a confirmation to ensure you want to close the window or Warp itself when a process is currently running.

Steps to reproduce:

1. Run `sleep 60`
2. Hit Command + W or Command + Q

Compare these steps with Terminal.app vs Warp.
```

### Is your feature request related to a problem? Please describe.

```shell
When you accidentally close Warp when a process is currently running absolutely **no** warning, alert, or confirmation is displayed.
```

### Additional context

What Terminal.app does:

<img width="697" alt="Screen Shot 2021-12-30 at 7 12 36 PM" src="https://user-images.githubusercontent.com/860375/147799118-99559f78-8300-4cd3-aa3c-d76e78c18004.png">

**Comment by elviskahoro** [comment] 2021-12-31 20:09
Gonna close this as it's a duplicate of:
- https://github.com/warpdotdev/warp/issues/197

**Closed by elviskahoro** 2021-12-31 20:09 UTC
