### ISSUE TITLE
DUP: Duplicate of #106 - Copy the build version to clipboard

### ISSUE THREAD

**Issue by mittalyashu** [warpdotdev/warp#109] opened 2021-08-08 08:12 UTC
**Is your feature request related to a problem? Please describe.**

Even after clicking "Check for update..." there is no clear way to know if it's even checking the app updates in background or not.

![CleanShot 2021-08-08 at 13 39 53](https://user-images.githubusercontent.com/29014463/128625590-2e524851-11e9-40c3-8d90-eabebaf07ee9.gif)

**Comment by rswerve** [comment] 2021-08-09 22:33
Duplicate of #70

**Comment by elviskahoro** [comment] 2021-11-07 23:03
Should stay reopen until it's actually finished.

**Comment by elviskahoro** [comment] 2021-11-10 16:38
Closed: v0.2021.11.09.19.46.stable_00

**Closed** 2021-11-12 18:54 UTC
Labels: feature-request
