### ISSUE TITLE
Option to disable the window controls on linux for people using tiling window managers.

### ISSUE THREAD

**Issue by Spelis** [warpdotdev/Warp#4307] opened 2024-02-24 08:55 UTC
### Discord username (optional)

spelis

### Describe the solution you'd like?

an option to disable window controls

### Is your feature request related to a problem? Please describe.

i use a tiling window manager so i dont use a titlebar in the traditional sense (i still might use tabs but i most often drag my windows with SUPER+Mouse1 anywhere and i have keybinds for maximizing and closing windows)

### Additional context

![image](https://github.com/warpdotdev/Warp/assets/152774420/40271442-43e1-4f01-acd0-6bd35fb025dc)

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by diegodario88** [comment] 2024-02-24 10:09
I would like to see that feature

**Comment by nevdelap** [comment] 2024-02-24 11:18
Started using Warp today on Arch. Liking it a lot.

I use i3wm with focus following the mouse, so I don't want tabs. It would be good to have a config that turns them off, along with not having minimise, maximise, and close buttons.

**Comment by HakonHarnes** [comment] 2024-02-27 12:43
+1. I use i3wm on arch and would like to disable tabs, minimize, maximize and close buttons, as well as the rounded corners.

**Comment by dannyneira** [comment] 2024-02-27 23:40
This may be related to the request for Zen mode ( no tab bars, titles, buttons, etc. ) which we already have a request tracking over at #1009

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-27 23:41
Duplicate of #1009

**Closed** 2024-02-29 21:53 UTC
Labels: enhancement

**Comment by Krawette** [comment] 2025-07-24 11:14
Why does "Windows OS" users have by discord built in window functions alongside discord window, although - Linux users -have native bar, and under it the mostly useless bar (which wastes the overall window height) with: help, inbox and channel name?
