### ISSUE TITLE
Cursor Missing

### ISSUE THREAD

**Issue by ramitkoul** [warpdotdev/Warp#1709] opened 2022-08-11 13:05 UTC
### Discord username (optional)

rkwap

### Describe the bug

Cursor not showing up in python console or irb/rails console.

### To Reproduce

python3

OR

irb

### Expected behaviour

A cursor should be there to move across text

### Screenshots

<img width="1552" alt="Screenshot 2022-08-11 at 6 32 13 PM" src="https://user-images.githubusercontent.com/87069330/184139396-f88f25e0-8ef3-48ff-adc0-337da26fa21f.png">

<img width="1282" alt="Screenshot 2022-08-11 at 6 32 48 PM" src="https://user-images.githubusercontent.com/87069330/184139499-7921a51a-85a4-48f1-a391-91d66bf1ea7b.png">

### Operating System

MacOS

### OS Version

12.3.1

### Shell Version

5.8

### Warp Version

 v0.2022.08.08.09.21.stable_00

### Does this block you from using Warp daily?

Yes

**Comment by zheng** [comment] 2022-08-11 15:55
Interesting, I am not seeing this issue when I run python3.

Does this still happen if you start with no shell configs? You can do this quickly by putting editing ~/.zshenv to set ZDOTDIR=/

I'd also wonder if your python & rails CLIs could be configured in a certain way.

Let us know if these correspond to the issue. It definitely seems like Warp might have a bug, given it works fine in the other terminal. We need a repro though, to fix the issue.

**Comment by rkwap** [comment] 2022-08-11 20:12
I tried with no shell configs and it worked fine

**Comment by rkwap** [comment] 2022-08-11 20:17
there is one more thing, even when the cursor is visible, navigating to text with keyboard shortcuts like option+left/right and cmd+left/right is also not working in those consoles.

**Comment by ramitkoul** [comment] 2022-08-11 20:19
just noticed, sry for posting those above comments with my secondary account.

**Comment by elviskahoro** [comment] 2022-08-14 05:52
that's a great profile picture on your @rkwap account.
The best way to debug what's causing this--it's likely something in your config if blank ones worked--is to put disable everything just for Warp by placing it behind this flag:

```sh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
##### WHAT YOU WANT TO DISABLE FOR WARP - BELOW

    # POWERLEVEL10K

##### WHAT YOU WANT TO DISABLE FOR WARP - ABOVE
fi
```

Then repeatedly / iteratively re-enable things by moving them out of the conditional until you drill down on the culprit.

**Comment by alokedesai** [comment] 2022-08-19 18:44
@ramitkoul Friendly ping on this!

**Comment by alokedesai** [comment] 2022-08-26 18:27
@ramitkoul @rkwap  Following up again--are you still able to repro this? If so, seeing if the test @elviskahoro mentioned above fixes the issue? It would be useful for us to help identify what's causing the issue. Thanks!

**Comment by rkwap** [comment] 2022-08-27 15:01
@elviskahoro @alokedesai Sorry for the very late reply but I was quite busy the past few days.
I think I have identified the bug. It is not related to any config, as per the previous findings. It is a bug you can reproduce without even having any config defined.

Steps to reproduce:

1. open `irb/python3` shell.
2. exit the shell (`exit` or `exit()` in case of python)
3. clear the terminal using cmd+k.

now, you have the bug. If you ever try to reopen the shell in the exact same terminal again, the cursor will be missing.

if you have any difficulties reproducing the bug, maybe I can even upload a video for reference.

**Comment by elviskahoro** [comment] 2022-08-31 15:58
@rkwap thanks for the help.

> Sorry for the very late reply but I was quite busy the past few days.
It's a marathon not a sprint.

**Comment by dannyneira** [comment] 2023-08-18 19:44
Hey Folks, Closing as resolved since the cursor is showing up in ipython/irb. Please let us know if this isn't the case for you in the most recent version of Warp.

**Closed** 2023-08-18 19:44 UTC
Labels: Bug
