### ISSUE TITLE
Not showing colors in  unicode emojis for print statements

### ISSUE THREAD

**Issue by Ayanrocks** [warpdotdev/Warp#4843] opened 2024-04-28 08:06 UTC
### Describe the bug

On Warp, emojis in print statements are not colored while the default terminal has it colored

### To reproduce

In rust
```rust
print!("♠️")
```

### Expected behavior

On Warp ⬇️ 
<img width="745" alt="Screenshot 2024-04-28 at 1 32 49 PM" src="https://github.com/warpdotdev/Warp/assets/11027998/fe4ed99a-3bdd-46cf-a0e3-a9a6851be5c6">

On default Terminal Macos
<img width="830" alt="Screenshot 2024-04-28 at 1 33 27 PM" src="https://github.com/warpdotdev/Warp/assets/11027998/da755fc8-059c-49e9-bd5a-5dab16395140">

### Operating system

MacOS

### Operating system and version

Macos 14.4.1

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-30 22:18
Hi @Ayanrocks I think this may be related to #239 , since Warp doesn't render pretty emojis by default, instead it falls back to the font version of emojis.

We'll continue to track that issue for updates.

**Comment by dannyneira** [comment] 2024-05-24 22:48
Duplicate of #239

**Closed by dannyneira** 2024-05-24 22:48 UTC
Labels: Bugs
