### ISSUE TITLE
History search command hover should display the complete command

### ISSUE THREAD

**Issue by gulshan-dream11** [warpdotdev/Warp#4597] opened 2024-03-19 18:11 UTC
### Describe the solution you'd like?

Currently, history search Ctrl+R and then searching a keyword shows the history commands, but when I want to view a command completely, I have to click on that command since the display pane has limited width and long commands are truncated. 
It would be cool if, in some way, you could show the complete command when I hover over it.

### Is your feature request related to a problem? Please describe.

I'm always frustrated when I want to view a command in history but only way is to click and see it

### How important is this feature to you?

3

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-19 22:10
Hey @gulshan-dream11 thanks for submitting, as a possible workaround you can enter the command you want to find in history and press `UP` to show the full command, also if you want to use CTRL-R history search, you can expand the search panel to see more of the command. Another possible workaround is to run `history | grep <your search here>` which should show the full command run.

https://github.com/warpdotdev/Warp/assets/16809145/0a4ef9c8-0144-4aa2-a9bd-4b5c7bdeed3d

Also, there is a duplicate request we are tracking for this here https://github.com/warpdotdev/Warp/issues/1405

Please upvote that one with a 👍  to show interest.

We'll close this one as a duplicate.

**Comment by dannyneira** [comment] 2024-03-19 22:11
Duplicate of #1405

**Closed by dannyneira** 2024-03-19 22:11 UTC
Labels: Feature requests
