### ISSUE TITLE
Warp is not persisting history between sessions

### ISSUE THREAD

**Issue by zlwaterfield** [warpdotdev/Warp#2302] opened 2022-12-06 03:44 UTC
### Describe the bug

Warp is not persisting history between sessions. Every time I open a new session the history is empty and I can't access any commands from my previous session. I also need to re-run `source /.zshrc` in order to load in my config.

I've looked at `/.zsh_history` and my command history is present. 

I've been using Warp for ~6 months and it's been working fine. This started happening out of no where and I'm unsure what is happening.

### To Reproduce

N/A

### Expected behaviour

- History should be persisted between sessions.
- I shouldn't need to run `source ./zshrc` on each session.

### Screenshots

Loom walkthrough: https://www.loom.com/share/6ad1d5bc08094f1baba07bae5fb8ad1b

### Operating System

MacOS

### OS Version

13.0 Beta (22A5358e)

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2022.11.29.08.03.stable_03

### Does this block you from using Warp daily?

Yes

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by szgupta** [comment] 2022-12-06 04:51
Hi @zlwaterfield, thanks for flagging. This definitely seems broken. A couple of questions:
- Could you try commenting out everything in your `.zshrc` file (except maybe the `fe` and `be` aliases) and see if the issue still repros?
- For some closer debugging, would you be comfortable sharing your (redacted) `Console.log` file for Warp with me @ `suraj@warp.dev`? 
- I'd also love to confirm if this issue repros on an older build for you (to see if something regressed with Warp or if there's some new, external state causing the issue) -- if you're open to trying that, I can send an older dmg over email :)

**Comment by zlwaterfield** [comment] 2022-12-06 13:12
Thanks for the quick reply @szgupta!

1. Commenting everything out does not fix the issue.
2. Sure what do you need from me?
3. I already upgraded and that didn't fix the issue but happy to try an older build. Feel free to email me at zlwaterfield@gmail.com.

**Comment by szgupta** [comment] 2022-12-06 14:44
@zlwaterfield followed up over email!

**Comment by unbreakabl3** [comment] 2022-12-06 15:40
"I also need to re-run source /.zshrc in order to load in my config." - I have the same problem.

Warp version: v0.2022.11.29.08.03.stable_03

**Comment by szgupta** [comment] 2022-12-06 17:02
@zlwaterfield confirmed that the issue also occurred on other terminal apps (e.g. the default Terminal.app that ships with MacOS) and was unrelated to Warp. Turned out to be an issue with `ZDOTDIR` not being set correctly.

**Comment by szgupta** [comment] 2022-12-06 17:03
@unbreakabl3 could you confirm if the issue you're experiencing is reproducible on other terminal apps (e.g. the default terminal)?

**Comment by unbreakabl3** [comment] 2022-12-06 17:12
> @unbreakabl3 could you confirm if the issue you're experiencing is reproducible on other terminal apps (e.g. the default terminal)?

Confirmed.

**Comment by szgupta** [comment] 2022-12-06 18:11
@unbreakabl3 if it's not a problem with Warp, it might also have to do with your `ZDOTDIR` not being set properly. Is your `.zprofile` being sourced on session start? To test this, you can add an `echo 'in .zprofile'` in your `.zprofile` file

**Comment by szgupta** [comment] 2022-12-07 21:01
@unbreakabl3 Ah yeah that sounds like it's not related to Warp. It might be worth checking your `$ZDOTDIR` (and also seeing if a test `.zprofile` file is being sourced)

**Comment by szgupta** [comment] 2022-12-14 21:36
Closing out since this seems unrelated to Warp itself.

**Closed by szgupta** 2022-12-14 21:36 UTC
Labels: Bug

**Comment by SilentGlasses** [comment] 2025-08-08 02:49
# Here's hoping this helps understand the issue you all are seeing and solve this once and for all..

>[!IMPORTANT]
> 1. This **is not** a Warp issue
> 2. This **is not** a bug
> 3. This **is** a shell issue. 
> 
> Bash and ZSH on Linux and macOS have made it so each session has it's own history for that specific session.

If you follow my instructions and use the settings for properly setting your shell for session sharing, this issue will go away.

There is **nothing** really that Warp can do as they do not install your shell as part of the app.

## The Fix

Please make a backup of your profile (`~/.zshrc`, `~/.bashrc`, etc) then start fresh with my base history settings:

```
# Better History
#=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt APPEND_HISTORY             # Write to history
setopt HIST_EXPIRE_DUPS_FIRST     # Expire duplicate entries first when trimming history.
setopt HIST_FIND_NO_DUPS          # Do not display a line previously found.
setopt HIST_IGNORE_ALL_DUPS       # Delete old recorded entry if new entry is a duplicate.
setopt HIST_IGNORE_DUPS           # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_SPACE          # Don't record an entry starting with a space.
setopt HIST_NO_STORE              # Don't store history commands
setopt HIST_REDUCE_BLANKS         # Remove superfluous blanks before recording entry.
setopt HIST_SAVE_NO_DUPS          # Older duplicates are omitted.
setopt INC_APPEND_HISTORY         # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY              # Share history between all sessions.
SHELL_SESSION_HISTORY=0           # Disable per-terminal-session
```

Once that works for you, start adding back your other settings one by one and to see what setting could potentially be breaking your history.
