### ISSUE TITLE
Status Bar Customization

### ISSUE THREAD

**Issue by KadlagAkash** [warpdotdev/Warp#4541] opened 2024-03-12 11:24 UTC
### Describe the solution you'd like?

iTerm2 provides a status bar at the bottom, displaying real-time information like RAM consumption, CPU usage, and network speed. 

It would be great if Wrap could offer similar customization options for the status bar.

### Is your feature request related to a problem? Please describe.

I believe implementing these features would enhance the user experience and make Wrap an even more compelling choice for users like me transitioning from iTerm2.

### iTerm2 Status Bar
![iTerm2](https://github.com/warpdotdev/Warp/assets/100425384/cdbfa08c-f15d-4186-871c-4e71be13562f)

### Wrap (with no Status bar)
![image](https://github.com/warpdotdev/Warp/assets/100425384/c5a85cf5-eabe-4090-a3e9-50fe95ca2f03)

### How important is this feature to you?

3

**Comment by dannyneira** [comment] 2024-03-12 16:54
Thanks for this feature request! 

To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by dannyneira** [comment] 2024-03-12 21:33
Duplicate of https://github.com/warpdotdev/Warp/issues/2157

**Closed by dannyneira** 2024-03-12 21:33 UTC
Labels: Feature requests
