### ISSUE TITLE
invisible cursor when customizing theme

### ISSUE THREAD

**Issue by ivan-robert** [warpdotdev/Warp#4502] opened 2024-03-07 15:39 UTC
### Describe the solution you'd like?

More customization in the theme. Especially for the cursor, it's been invisible in the last 3 themes I created.

### Is your feature request related to a problem? Please describe.

FRUSTRATION : INVISIBLE CURSOR.

### Additional context

There have been 3 issues (at least, including one of mine) about this. Please fix this, you are adding some crazy AI stuff all the time, being able to choose a color and an opacity should be trivial.

### How important is this feature to you?

5 (Can't work without it!)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-07 19:59
Duplicate of https://github.com/warpdotdev/Warp/issues/3210

**Closed by dannyneira** 2024-03-07 19:59 UTC
Labels: Feature requests

**Comment by dannyneira** [comment] 2024-08-22 21:54
Hey Folks, this feature has launched with the latest release of Warp.
You can now add `cursor: '#<hex color value>'` to your custom theme yaml files to customize your cursor! Please see an example in our [docs](https://docs.warp.dev/appearance/custom-themes#create-your-custom-theme-manually).

Closing as resolved, but please update and let us know what you think or any issues.
