### ISSUE TITLE
Unexpected behaviour of the 'clear' command - when using the ; operator

### ISSUE THREAD

**Issue by mgiugliano** [warpdotdev/Warp#4027] opened 2024-01-05 17:15 UTC
### Describe the bug

Although typing
`echo ciao; echo wof`

correctly executes `echo ciao` and then `echo wof`, sequentially (as expected given the use of ; operator) this is NOT the case when the first command is `clear`.

### To reproduce

When "Input Position" is set to "Start at the top (Classic mode)"

typing: 
`clear; ls`

does NOT display the output of the command (here in the example `ls`).

### Expected behavior

The expected behaviour should be first clearing the screen, bringing the cursor at the top of the window and then display the output of the command.

### Operating system

MacOS

### Operating system and version

14.2.1 (23C71)

### Shell Version

GNU bash, version 5.2.21(1)-release (x86_64-apple-darwin23.0.0)

### Current Warp version

v0.2023.12.19.08.02.stable_00 AND v0.2024.01.02.08.02.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

Never worked

### Additional context

Any alias / script that clears the screen to prepare for an output (in my case Task Warrior) fails to work as intended.

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-01-05 22:23
Hey @mgiugliano thank you for submitting this, we have a workaround listed [here](https://github.com/warpdotdev/Warp/issues/2382#issuecomment-1863600790).

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/2382 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-05 22:24
Duplicate of https://github.com/warpdotdev/Warp/issues/2382

**Closed** 2024-01-05 22:24 UTC
Labels: Bug
