### ISSUE TITLE
Launch configuration bug.

### ISSUE THREAD

**Issue by muhannad-hash** [warpdotdev/Warp#4787] opened 2024-04-19 13:29 UTC
### Describe the bug

after updating yesterday to the latest version, I open my warp terminal as ususal and open the pallet (Ctl + Shft + P) and search for my launch configuration which  I have been using for the past months.
the launch template start the new warp terminal with my tabs and panes.
I close the windown which I started the template from and it close my template terminal.

![Screenshot from 2024-04-19 09-18-41](https://github.com/warpdotdev/Warp/assets/65446820/75c33058-ccb1-4884-9dd4-537b257dfb82)

in the background is the main terminal where I started my launch template.
in the front in my launch template.
when I close the main terminal after a sec my launch template closes.

### To reproduce

1. update to the latest version  v0.2024.04.16.08.02.stable_00
2. create a launch template
3. open only one warp terminal window first
4. launch your luanch template
5. close the main warp terminal which you launched the template from.
6. you launch template would close also leaving not any terminal windo open

### Expected behavior

the launch configuration template window panes and tabs should stay open.

### Operating system

Linux

### Operating system and version

Linux Aorus 6.5.0-27-generic #28-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar  7 18:21:00 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Shell Version

zsh 5.9 (x86_64-ubuntu-linux-gnu), 

### Current Warp version

  v0.2024.04.16.08.02.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

04/16/2024

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by ken-kuro** [comment] 2024-04-20 02:51
Could you please check your `warp-terminal` log by `RUST_LOG=wgpu_core=info,wgpu_hal=info MESA_DEBUG=1 EGL_LOG_LEVEL=debug warp-terminal` to see if the `main` thread is panicked like mine in #4780.
I got something like:
```
13:50:54 [INFO] dispatching global action for workspace:save_app
13:50:54 [WARN] Tried to update block filter query without active_filter_editor_block_index set
13:50:54 [INFO] dispatching global action for workspace:save_app
13:50:54 [WARN] No alert dialog was set for the native modal
13:50:54 [WARN] Tried to render share modal without a model
libEGL debug: EGL user error 0x3008 (EGL_BAD_DISPLAY) in eglMakeCurrent

thread 'main' panicked at /home/runner/.cargo/git/checkouts/wgpu-163ac9f6133c4ea6/70ade4c/wgpu-hal/src/gles/egl.rs:305:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by vorporeal** [comment] 2024-04-22 19:52
I'm pretty sure this is the same root cause as https://github.com/warpdotdev/Warp/issues/4780.  We're going to push out an updated build today with a fix.

Will close this one as a duplicate of that issue, but if it persists after today's update, please re-open!

**Closed by vorporeal** 2024-04-22 19:52 UTC
Labels: Bugs

**Comment by vorporeal** [comment] 2024-04-22 20:37
Hey @muhannad-hash, we just pushed a new version of Warp that should fix this issue. Would you mind confirming that you can no longer repro this crash? Thanks!
