### ISSUE TITLE
Missing last output line

### ISSUE THREAD

**Issue by padamban** [warpdotdev/Warp#2995] opened 2023-04-29 09:44 UTC
### Describe the bug

I run the same command in both iTerm2 and warp but got different result.

I have seen this in my personal project. 
It is a relatively long running vitest test command.

##### End of the output
Iterm
```
 Test Files  6 passed (6)
 Tests  30 passed (30)
 Start at  11:20:26
 Duration  7.40s (transform 135ms, setup 0ms, collect 289ms, tests 24.98s, environment 1ms, prepare 373ms)
```

Warp (missing the last line)
```
 Test Files  6 passed (6)
 Tests  30 passed (30)
 Start at  11:20:26
```

### To Reproduce

Checkout: https://github.com/padamban/pulchritude-cli

```
pnpm i
```

Run this in iterm and warp:
```
pnpm test:e2e
```

### Expected behavior

Should see the last line with the duration.

### Operating System

MacOS

### Operating System and Version

Ventura 13.1

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin22.0)

### Warp Version

v0.2023.04.25.08.05.stable_00

### Additional context

Running `pnpm test:unit` is a similar but much faster command and I can see the last line. (not sure if related) 

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-05-01 17:07
Thanks for letting us know @padamban
I'll bring this up with the team and a blocker that works correctly in other terminals. We'll post any updates on this thread.

Please add a :+1: to the original post at the top or comment with your details to signal that you're also having the same issue, and then hit the subscribe button if you'd like to be notified.

**Comment by JoeFirebaugh** [comment] 2023-05-05 17:53
I think the problem is worse than just one line.

I'm seeing a whole block of output disappear with my Gradle build.  Interestingly enough I see it for a split second and then it's gone.

<img width="1707" alt="image" src="https://user-images.githubusercontent.com/930703/236532103-485bcfcd-71de-4231-bc0d-6add6e9e9b70.png">

There's a side by side comparison of the output from my Gradle build and the last task run output is completely missing.

**Comment by dannyneira** [comment] 2023-05-05 19:39
hey Folks, we are generally tracking this here: https://github.com/warpdotdev/warp/issues/2556 and have marked this issue as related. We have an engineer working on this quality issue and will post updates on #2556 once we've made progress. 

We appreciate your patience with us as we fix these product quality issues.

**Comment by JoeFirebaugh** [comment] 2023-05-05 19:51
I'm so sorry that I didn't see that other issue.  I just happened to see this one first and thought I should add to it.  Thanks!

**Comment by dannyneira** [comment] 2023-07-07 15:23
Hi all! this has been resolved in the most recent version of Warp. Please update and let us know.

**Closed by dannyneira** 2023-07-07 15:23 UTC
Labels: Bug
