### ISSUE TITLE
Changing git branch does not update branch name in Warp

### ISSUE THREAD

**Issue by arbyruns** [warpdotdev/Warp#2366] opened 2022-12-14 19:03 UTC
### Discord username (optional)

rbevans#4472

### Describe the bug

I use github mac app and if I change to a different branch to mange my repo's, but I also use command line for other tasks. If I change the branch in github mac app the name does not reflect in warp.

### To Reproduce

1. Have Github Mac app installed
2. Have git installed for command line
3. From Warp browse to the project (my case it is Xcode\iOS project) that is currently in use on the Github mac app
4. Change branches or create a new one from Mac app

### Expected behaviour

Warp would pick up the change, but remains on the old branch. Running `git status` seems to reset it.

### Screenshots

![image](https://user-images.githubusercontent.com/2520545/207688511-31aa287f-6331-48b1-8e85-bf822337f091.png)

### Operating System

MacOS

### OS Version

13.0.1

### Shell Version

bash 3.2.57

### Warp Version

0.2022.12.06.08.03 stable_02

### Does this block you from using Warp daily?

No

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2022-12-14 20:02
Thanks for letting us know! We've been able to reproduce this known issue we're tracking here #1657
Please :+1: and comment there if you're also seeing the issue, as it helps us gauge the impact of the bug.

Closing as duplicate.

**Closed by dannyneira** 2022-12-14 20:02 UTC
Labels: Bug

**Comment by arbyruns** [comment] 2022-12-14 21:15
@dannyneira is this just a UI issue where Warp does not update the branch name and under the covers the branch changed? I would hate to push code to the wrong branch.

**Comment by dannyneira** [comment] 2022-12-14 21:56
You're right, it's just a UI bug, once you run any actual git commands like `git push`, `git status`, etc. it will update the UI to reflect the correct branch, not push to the branch that's presented in the prompt. 

I've noticed the same with custom prompts and other terminals (Terminal.app & iTerm2) as well. It looks like they don't update the UI unless some action is taken as well.

**Comment by arbyruns** [comment] 2022-12-14 22:08
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
