### ISSUE TITLE
Shortcut Keys Issue in Warp Terminal

### ISSUE THREAD

**Issue by De54** [warpdotdev/Warp#4729] opened 2024-04-10 20:39 UTC
### Discord username (optional)

developer54

### Describe the bug

Hi, I have encountered a software bug where the keyboard shortcuts work perfectly when the keyboard language is set to English. However, when I switch my keyboard language to another language such as Farsi(Persian), the shortcuts stop functioning.

### To reproduce

1. First, navigate to the system settings. (Linux System Settings)
2. Select Keyboard from the Input & Output section.
3. Choose Keyboard once again.
4. Navigate to the Layouts tab.
5. Enable the "configure layouts" option.
6. Click on Add.
7. Select the "Persian (with Persian Keypad)" language.
8. Click OK to confirm.
9. Apply the settings to take effect.
10. Now, open the Warp Terminal.
11. Change the keyboard language to Persian.
12. You will notice that certain shortcuts like "copy (Ctrl + Shift + C)" and "paste (Ctrl + Shift + V)" do not function as expected.

### Expected behavior

I expected that like all other terminals, including Konsole which is the default terminal of my operating system, the shortcuts in Warp Terminal would still work when I switch my keyboard language to Persian.

### Operating system

Linux

### Operating system and version

Parch Linux (Arch-based Linux)

### Shell Version

GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)

### Current Warp version

v0.2024.04.02.08.02.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Additional context

It is recommended that the Warp team hardcodes the terminal shortcuts to ensure consistent functionality across different keyboard languages.

Your prompt attention to this matter is greatly appreciated. Thank you! 🙏

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-10 20:51
Hi @De54 Sorry about this. This is a known issue we are tracking here. https://github.com/warpdotdev/Warp/issues/341

The input from sources other than ABC arent immediately converted in Warp. So if you decide to use an international input source, you will need to rebind the keys again from scratch with the new input source as a workaround. 

We'll post updates on that thread above if/when international input sources are supported by default.

I'll be closing this as a duplicate but please let us know of any other issues.

**Comment by dannyneira** [comment] 2024-04-10 20:51
Duplicate of https://github.com/warpdotdev/Warp/issues/341

**Closed by dannyneira** 2024-04-10 20:51 UTC
Labels: Bugs
