### ISSUE TITLE
Move Cursor Word by Word inside tmux

### ISSUE THREAD

**Issue by EslamElHusseiny** [warpdotdev/Warp#3974] opened 2023-12-15 17:05 UTC
### Describe the bug

Moving the cursor Word by Word works fine in Warp, but it stops working when I'm inside tmux session in Warp (works fine inside tmux session in ITerm) 

### To reproduce

open Warp terminal 
Type tmux 
write a command that has words 
try to move backward/forward using (option + right/left arrow)

### Expected behavior

cursor to move word by word. 

### Screenshots

![render1702659761897](https://github.com/warpdotdev/Warp/assets/910187/259b6b00-3d82-4a7e-912a-ef4128181ce0)

### Operating system

MacOS

### Operating system and version

14.2 (23C64)

### Shell Version

zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.12.12.08.02.stable_04

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

No, this same issue happens in Warp and other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by dannyneira** [comment] 2023-12-15 22:55
Hey @EslamElHusseiny Sorry about this issue, It's known that Warp doesn't have full support for tmux ( warp features in tmux sessions ). As a possible workaround, we recently released VIM keybindings in Warp's input editor, which includes movement by word! https://docs.warp.dev/features/editor/vim#basic

That being said, we have a request tracking full TMUX support in Warp over at #501.

If you could please give it a :+1: and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned!

**Comment by dannyneira** [comment] 2023-12-15 22:55
Duplicate of #501

**Closed by dannyneira** 2023-12-15 22:55 UTC
Labels: Bug

**Comment by jorgetoh** [comment] 2025-03-10 14:54
I can’t fully use Warp at the moment due to its lack of compatibility with tmux. I’d really love to see support for it.
