### ISSUE TITLE
MacOs: Warp loses permissions to access files following inactivity

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [warpdotdev/Warp#5417] opened 2024-10-25 04:34 UTC
### Dupe Check

- [X] I have [searched Warp bugs](https://github.com/warpdotdev/warp/issues?q=is%3Aissue+label%3ABugs) and there are no duplicates

### Describe the bug

Similar bug: https://github.com/warpdotdev/Warp/issues/3009

Every morning, on starting to work Warp needs to be restarted as is has lost permissions to access any files on the drive. I have assigned it full drive access.

This started following the latest update.

v0.2024.10.23.14.49.stable_00

### To reproduce

Wait.

### Expected behavior

To not have to restart warp every morning.

### Operating system

MacOS

### Operating system and version

15.0.1 (24A348)

### Shell Version

zsh 5.9 (arm64-apple-darwin24.0)

### Current Warp version

v0.2024.10.23.14.49.stable_00

### Regression

Yes, this bug started recently or with an X Warp version

### Recent working Warp date

Pre update

### Additional context

Although this doesn't currently stop me using warp, it will do because it is not just in the morning. Any significant, but untimed, period of inactivitly causes this and it is annoying.

### Does this block you from using Warp daily?

No

### Is this an issue only in Warp?

Yes, I confirmed that this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-10-25 21:33
Hi @mark-jordanovic-lewis sorry to hear about this issue. Make sure you go to Mac > System Settings > Privacy & Security > Files and Folders > Warp, and then toggle on Downloads / Documents / Desktop Folders. Restart Warp to apply and see if the issue persists. Please let us know if that helps with the issue.

**Comment by ryanbreen** [comment] 2024-10-26 17:57
I've selected Full Desk Access, and I have the same issue.  I need to restart Warp periodically to pick up that setting.

<img width="517" alt="image" src="https://github.com/user-attachments/assets/299e6b7f-5903-4aa0-8ba9-1c791aaaf73a">

This is pretty annoying when coupled with the fact that I typically have 6 Warp windows open, each on different workspaces, and Warp never remembers the workspace a terminal is on.  So, I restart and then need to drag my Warps back to their workspaces.

**Comment by zain-mansuri** [comment] 2024-10-30 05:42
Going throw the same issue, found any solution?
I have to open all my tabs again. And restarting wrap is the only thing I can find.
Running using sudo also won't work

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/db30dafc-9aca-4e70-9f43-7f51714c2960">

**Comment by dannyneira** [comment] 2024-10-31 21:37
hey Folks, as a possible workaround/stopgap measure, please grant "old" Warp permission in [Mac > System Settings > Privacy & Security > Full Disk Access](https://github.com/warpdotdev/Warp/issues/5415).

![image](https://github.com/user-attachments/assets/d421c5c4-e293-46d1-acf4-81b40b792540)

We're tracking this issue over at https://github.com/warpdotdev/Warp/issues/3009 and would appreciate it if you could 👍 and comment there if you're also experiencing the same bug. This helps us gauge the impact of the issue. 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-10-31 21:37
Duplicate of https://github.com/warpdotdev/Warp/issues/3009

**Closed by dannyneira** 2024-10-31 21:37 UTC
Labels: Bugs

**Comment by mark-jordanovic-lewis** [comment] 2024-11-01 11:31
As in comments in #3009, I don't have the "old" Warp in Mac > System Settings > Privacy & Security > Full Disk Access. 

I had already set Warp to have full disk access as I edit files everywhere.

**Comment by mark-jordanovic-lewis** [comment] 2024-11-11 05:42
@dannyneira As requested. On Thursday and Friday there was no loss of permissions in warp. This morning, Monday 11th Nov 2024, permissions to read directories in already open warp sessions have been lost. No changes in OS settings related to Full Disk access of the application.
