### ISSUE TITLE
Let me select text from my prompt

### ISSUE THREAD

**Issue by manewitz** [warpdotdev/Warp#4111] opened 2024-01-29 21:49 UTC
### Describe the solution you'd like?

<img width="537" alt="image" src="https://github.com/warpdotdev/Warp/assets/441642/828dfb51-a602-41e3-aa4c-f630eabdd41e">

I use powerlevel10k for my prompt which lists my current git branch. In iTerm, I copy the branch name from there a lot for things like `git reset --hard CURRENT_BRANCH_NAME`. It would be great if the whole prompt was selectable for copying to support this workflow.

### Is your feature request related to a problem? Please describe.

I can SEE the branch name but have to manually type it if it's not in my paste buffer or the command I'm running isn't autocomplete-able.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-01-29 22:17
Hi @manewitz Thanks for submitting! A possible workaround to this is to use a custom prompt, and then once the command is run, you can select/copy the prompt. 

Unfortunately Warps prompt isn't selectable, but you can right-click on a previously run block and "Copy Prompt". You can also, right-click and "Copy git branch" among other options. https://docs.warp.dev/appearance/prompt

That being said, it's something we are tracking over at https://github.com/warpdotdev/Warp/issues/36

Please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-01-29 22:17
Duplicate of https://github.com/warpdotdev/Warp/issues/36

**Closed by dannyneira** 2024-01-29 22:17 UTC
Labels: enhancement
