### ISSUE TITLE
Open new tab in home directory

### ISSUE THREAD

**Issue by neelmehta247** [warpdotdev/warp#558] opened 2022-01-03 17:40 UTC
Right now when I open a new tab it opens in the directory I have open on the previous tab. I would prefer opening it in the home directory. 

Since this is a matter of preference maybe this is something that should be configurable in settings?

**Comment by elviskahoro** [comment] 2022-01-03 21:19
Closing it's duplicate of:
- https://github.com/warpdotdev/warp/issues/105

**Closed by elviskahoro** 2022-01-03 21:19 UTC
