### ISSUE TITLE
exiting zellij breaks terminal window

### ISSUE THREAD

**Issue by Takkaryx** [warpdotdev/Warp#4361] opened 2024-02-27 08:02 UTC
### Discord username (optional)

Takkaryx#5249

### Describe the bug

open a new Zellij instance.  then use the exit command to leave it.

The terminal will now fail every command having bracketed pastes, as shown in the video.

I've noticed this can also occur if an SSH session is disconnected.  (say, hibernate laptop while an ssh session is active, and leave the area so you lose connection, open laptop again, terminal that had the ssh session will have bracketed paste)

### To reproduce

open terminal
open zellij
type exit into zellij

### Expected behavior

terminal returns to normal state.

### Screenshots

https://github.com/warpdotdev/Warp/assets/87953442/5032409f-94a2-447f-bf37-79ed560f517a

### Operating system

MacOS

### Operating system and version

Sonoma 14.2.1

### Shell Version

GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23) Copyright (C) 2007 Free Software Foundation, Inc.

### Current Warp version

v0.2024.02.20.08.01.stable_02

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

unclear

### Additional context

I was trying out zellij for the first time to determine if I would like to incorporate it into my workflow.  I noticed that upon exit, the terminal used to open/exit zellij was stuck with the bracketed pastes.

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-02-28 18:34
Thanks for submitting this @Takkaryx 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/3935

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-02-28 18:34
Duplicate of https://github.com/warpdotdev/Warp/issues/3935

**Closed** 2024-02-29 21:55 UTC
Labels: Bugs
