### ISSUE TITLE
DUP: Duplicate of #425 - Tap complition instead of using arrow keys

### ISSUE THREAD

**Issue by sebhs** [warpdotdev/Warp#583] opened 2022-01-08 14:58 UTC
### Describe the solution you'd like?

```shell
Would like if there is a setting to select the auto-suggestion with a `tab` instead of the arrow keys
```

**Comment by elviskahoro** [comment] 2022-01-09 08:37
Duplicate of:
- #425

**Closed by elviskahoro** 2022-01-09 08:37 UTC
