### ISSUE TITLE
Add the ability to disable automatic updates

### ISSUE THREAD

**Issue by Ceneka** [warpdotdev/Warp#4526] opened 2024-03-10 12:14 UTC
### Describe the solution you'd like?

A tick on the options menu to disable auto updates on startup

### Is your feature request related to a problem? Please describe.

I'm using Warp on NixOS, so every time I open it, I have a big red flag on top that says that there is a new version and it can't update itself because the Nix package manager doesn't allow it. It's a little annoying

### Additional context

![Screenshot_20240310_090927](https://github.com/warpdotdev/Warp/assets/11842166/8793d25b-063a-4b2a-b180-2722647039b1)

Thanks! :smile: 

### How important is this feature to you?

1 (Not too important)

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-12 17:26
We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/1991

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-12 17:26
Duplicate of https://github.com/warpdotdev/Warp/issues/1991

**Closed by dannyneira** 2024-03-12 17:26 UTC
Labels: Feature requests
