### ISSUE TITLE
Drag tab out of window to create new window

### ISSUE THREAD

**Issue by terrisgit** [warpdotdev/Warp#2610] opened 2023-02-04 18:47 UTC
### Describe the solution you'd like?

This is probably a duplicate.

Tab drag and drop behavior like Chrome etc..

1. Dragging a tab out of a Warp window and releasing the mouse on an empty space in the desktop creates a new Warp window containing the tab

2. Dragging a tab out of a Warp and releasing the mouse in a second Warp window moves the tab to the second Warp window

### Is your feature request related to a problem? Please describe.

This is particularly needed for multiple monitor setups

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:770f6576-d6c0-4e4f-a259-fc64b5156087

None

**Comment by dannyneira** [comment] 2023-02-06 22:51
Thanks for submitting this, it's a duplicate of #1223, closing this one, but please do 👍  and sub to that issue for updates on this feature.

**Closed by dannyneira** 2023-02-06 22:51 UTC
Labels: enhancement
