### ISSUE TITLE
Command history unique to each split

### ISSUE THREAD

**Issue by pencilcheck** [warpdotdev/Warp#4762] opened 2024-04-16 02:57 UTC
### Describe the solution you'd like?

In tmux or any terminal app, each split/window has unique history (I know they are shared) but it would be very nice if I hit arrow up and it show the last command being done in that split instead of the global command being used in across multiple splits/terminal windows/tabs.

### Is your feature request related to a problem? Please describe.

I'm a bit frustrated when hitting arrow up doesn't show the last command I run in that specific split/tab, instead it just show a global list of command instead

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-04-16 22:16
Hey @pencilcheck thanks for submitting. Afaik, when a new session is started it maintains its own history, once there is a new session started it will contain a previous sessions history.


To anyone else interested in this feature, please add a 👍 to the original post at the top to signal that you want this feature, and subscribe if you'd like to be notified.

**Comment by pencilcheck** [comment] 2024-04-24 17:10
Well, until it is supported I will keep using tmux but it would be nice if this is actually in Warp.

**Comment by dannyneira** [comment] 2024-06-06 21:49
Hi @pencilcheck We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/3692

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate. Also keep an eye on https://github.com/warpdotdev/Warp/discussions/501 support as it's related to your comment.

**Comment by dannyneira** [comment] 2024-06-06 21:49
Duplicate of #3692

**Closed by dannyneira** 2024-06-06 21:49 UTC
Labels: Feature requests
