### ISSUE TITLE
SSH connection management

### ISSUE THREAD

**Issue by sfkmk** [warpdotdev/Warp#4618] opened 2024-03-22 20:54 UTC
### Describe the solution you'd like?

I connect to several servers via ssh. It would be great to be able to manage servers to connect to inside warp. Workflows work for that, but that's not as smooth as it could be. Something more advanced than the ssh connect management in vs code would be great.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-22 21:55
Thanks for submitting this @sfkmk 

We already have a request tracking this over at #442 

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-22 21:55
Duplicate of #442

**Closed by dannyneira** 2024-03-22 21:55 UTC
Labels: Feature requests
