### ISSUE TITLE
Direnv messages are not pasted in the prompt area

### ISSUE THREAD

**Issue by johnuopini** [warpdotdev/Warp#920] opened 2022-04-06 16:28 UTC
### Discord username (optional)

RichardBlaney#4445

### Describe the bug

```text
When direnv loads the .envrc file it writes some message and that message is written in the prompt bar where i write the command rather then being printed in the terminal area.
```

### To Reproduce

Steps to reproduce:
- Install direnv
- Create an .envrc with any exported var (es export FOO=1)
- Enable it via "direnv allow"
- Cd into the directory
- Direnv will write "loading direnv at..."
- That message will be in the prompt area and if you press enter WARP will execute it as a command

### Expected behaviour

```text
Direnv messages should be seen on the terminal
```

### Screenshots

<img width="173" alt="image" src="https://user-images.githubusercontent.com/2204736/162022738-8ebe0926-1dfe-4989-8fd3-2ec5a364d7ac.png">

### Operating System

MacOS

### OS Version

12.3.1

### Additional context

```text
Direnv latest installed via brew
```

**Comment by markwatson** [comment] 2022-04-10 02:11
A workaround to this is to disable direnv output by putting `export DIRENV_LOG_FORMAT=` in your shell rc file. This will stop showing you what variable change though, so it's not ideal. I prefer it over having to hit "ctrl-c" each time I cd though.

**Comment by johnuopini** [comment] 2022-04-10 06:41
> I prefer it over having to hit "ctrl-c" each time I cd though.

Yeah that's what I am doing but it annoys me as i don't know when direnv is actually exporting something

**Comment by elviskahoro** [comment] 2022-07-08 15:24
Sorry that this isn't supported!

**Comment by elviskahoro** [comment] 2022-07-08 15:24
Will circle back when it's WIP!

**Comment by elviskahoro** [comment] 2022-07-08 15:24
Can you share a video of what it looks like working (in another terminal)?

**Comment by hovsater** [comment] 2022-11-02 14:35
@elviskahoro this is related to https://github.com/warpdotdev/Warp/issues/1142. See https://github.com/warpdotdev/Warp/issues/1142#issuecomment-1300337275 for a reproduce. The problem here seem to be that any function executed by `PROMPT_COMMAND` that `echo` output to stdout will end up on the same line as the prompt.

**Comment by ericsampson** [comment] 2023-02-09 18:15
@elviskahoro should we merge/close this issue in favor of #1142 ?

**Comment by elviskahoro** [comment] 2023-02-09 20:31
Yeah we can do that! Thanks @ericsampson

**Closed by elviskahoro** 2023-02-09 20:31 UTC
Labels: Bug
