### ISSUE TITLE
Theme selection in launch configuration

### ISSUE THREAD

**Issue by josh-unwin** [warpdotdev/Warp#4561] opened 2024-03-14 15:55 UTC
### Describe the solution you'd like?

I would like the ability to set a theme in Launch Configurations so different windows can have different themes.
This is very useful when using configurations to remote into different machines, so you can easily tell what machine you're remoted to from the theme.

### How important is this feature to you?

4

### Warp Internal (ignore) - linear-label:39cc6478-1249-4ee7-950b-c428edfeecd1

None

**Comment by dannyneira** [comment] 2024-03-14 18:40
Thanks for submitting this @josh-unwin 

We already have a request tracking this over at https://github.com/warpdotdev/Warp/issues/2618

If you could please give it a 👍 and subscribe to that request, it would help us gauge interest. We'll post any updates there, so stay tuned! 

We'll be closing this as a duplicate.

**Comment by dannyneira** [comment] 2024-03-14 18:40
Duplicate of https://github.com/warpdotdev/Warp/issues/2618

**Closed by dannyneira** 2024-03-14 18:40 UTC
Labels: Feature requests
