### ISSUE TITLE
Session restoration does not work

### ISSUE THREAD

**Issue by vasilev-alex** [warpdotdev/Warp#2447] opened 2023-01-05 20:26 UTC
### Describe the bug

It doesn't restore the previous if Warp is closed by the close button . However, if you close it using the context menu it works just fine.

### To Reproduce

1. Make sure "Restore windows, tabs..." option is on
2. Rename a tab/open a few more tabs
3. Close the app by the close button
4. The session is not restored. All tabs are gone

### Screenshots

<img width="511" alt="Screenshot 2023-01-06 at 01 50 52" src="https://user-images.githubusercontent.com/4973437/210872801-95d2821f-71cf-4e06-b9e4-d36b52517d0e.png">

<img width="231" alt="Screenshot 2023-01-06 at 01 57 45" src="https://user-images.githubusercontent.com/4973437/210873770-ec9bf151-f5b6-410d-8adb-dd4474abf33a.png">

### Operating System

MacOS

### OS Version

13.0.1 (22A400)

### Shell Version

not applicable

### Warp Version

v0.2022.12.13.08.04.stable_01

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by alokedesai** [comment] 2023-01-05 20:30
Hey @vasilev-alex! I believe this is working as intended; pressing the red "close" button in MacOS doesn't actually close the app, it only closes the window--the app continues to run even if there are no other open windows. We only restore sessions when the app quits (which can be done via the dock in the context menu, via `cmd-q`, or from finder).

**Comment by dannyneira** [comment] 2023-01-05 20:36
Closing as not planned given this working.

**Closed by dannyneira** 2023-01-05 20:36 UTC
Labels: Bug

**Comment by dannyneira** [comment] 2023-01-05 20:37
Thanks for submitting @vasilev-alex , closing this one as not planned since the feature is working as intended.

**Comment by vasilev-alex** [comment] 2023-01-06 12:02
@dannyneira @alokedesai, thanks for clarifying. Does it make sense to add a confirmation dialog on exit to prevent the active session from being lost then?

**Comment by alokedesai** [comment] 2023-01-06 13:41
We're building that right now :) it should launch in the next week or two

**Comment by dannyneira** [comment] 2023-01-09 16:35
@vasilev-alex You can track the quit modal progress here 🚀  https://github.com/warpdotdev/Warp/issues/197
