### ISSUE TITLE
Live logs scrolls window output when scrolled back looking through history 

### ISSUE THREAD

**Issue by gflujan** [warpdotdev/Warp#4772] opened 2024-04-17 20:42 UTC
### Describe the bug

When I'm viewing live logs (a server, tailed, etc.) and when I've scrolled back/up to look at the previous history, new output that comes in below shifts the "old" lines that I'm looking at. 

This is not desired behavior and it makes me re-scroll to where/what I was looking at previously. 

If the bottom of the window/output is focused, then yes it makes sense to live update. But if I'm looking back through history, I would like the scrolled output to stay in place. 

I'm not sure about other users, but this is a deviation from other terminals that I've used in the past. 

### To reproduce

Start any long running process that generates live output (e.g. a server with logs). 

Scroll back/up to view previous logs & history. Wait whatever amount of time it takes for your new log output to come in. 

Notice that spot you were viewing has shifted X number of lines. 

### Expected behavior

When scrolled back and looking through previous output, the text/lines stay in place when new, live output comes in. 

### Operating system

MacOS

### Operating system and version

Sonoma 14.4.1

### Shell Version

zsh 5.9

### Current Warp version

v0.2024.04.09.08.01.stable_01

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

I can't recall if this worked before or not. 

### Does this block you from using Warp daily?

No

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b9d78064-c89e-4973-b153-5178a31ee54e

None

**Comment by dannyneira** [comment] 2024-04-23 16:04
Hi @gflujan i believe this issue has to do with the lack of support for full scrollback in Warp. We are tracking this here #610 

Please continue to track that request for any updates.

**Comment by dannyneira** [comment] 2024-04-23 16:04
Duplicate of #610

**Closed by dannyneira** 2024-04-23 16:04 UTC
Labels: Bugs
