### ISSUE TITLE
DUP: Duplicate of #209 - Tab completion for cd command does not work from a folder with regional characters

### ISSUE THREAD

**Issue by robinhultman** [warpdotdev/warp#335] opened 2021-11-01 13:00 UTC
### Describe the bug

```shell
I have a folder with the regional characters 'ø' and 'æ' in it's name. Inside of this folder tab completion for cd command stops working.
```

### To Reproduce

Steps to reproduce:
1. cd folder-with-regional-character
2. cd [tab]

### Operating System

MacOS

### OS Version

12.0.1

**Comment by kevinyang372** [comment] 2021-11-05 16:10
Closing as this is a duplicate of #348

**Comment by elviskahoro** [comment] 2021-11-10 16:56
Linking:
- #209

**Closed** 2021-12-07 04:56 UTC
Labels: bug
