### ISSUE TITLE
Hotkey binding for window show and hide is not working anymore

### ISSUE THREAD

**Issue by RaviH** [warpdotdev/Warp#1239] opened 2022-04-29 21:23 UTC
### Describe the bug

```text
Version: v0.2022.04.25.09.59.stable_03

I had setup F2 as the key to have Guake like terminal and it worked before most recent update. After the update it's stopped working.
```

### To Reproduce

Steps to reproduce:
1. Go to 'Preferences -> Features'

And set the preferences to:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/141136/166070782-96e2dad8-1e39-4bfb-ab0a-374bb2f4b598.png">

2. Save the settings
3. Press F2. 
4. Warp window does not show/hide.

### Expected behaviour

```text
Warp window should show/hide.
```

### Screenshots

![image](https://user-images.githubusercontent.com/141136/166070918-ffc7a229-4384-4083-a6bc-1d38c43b328f.png)

### OS Version

Mac OS 12.3.1

**Comment by fonylew** [comment] 2022-04-30 09:19
It doesn't work for me to after update to the latest version.

**Comment by simerlec** [comment] 2022-04-30 16:34
Duplicate of https://github.com/warpdotdev/Warp/issues/1232 I believe

**Comment by AnandDev006** [comment] 2022-05-02 08:28
Hotkey broken since latest update, I assumed it was because i started using a 2nd monitor, but issue pesists on single monitor too

**Comment by AxisZql** [comment] 2022-05-02 09:12
I have the same problem. Install warp_stable.dmg on Github will not have this problem,but after reopening this version of Warp,it will automatically upgrade to the latest version.The hotkey I bind is F12. In the latest version,I tried to change the hotkey to Shift+Enter.It can be used for a period of time,but it will still fail in the end.

**Comment by AxisZql** [comment] 2022-05-02 09:15
OS Version:
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
macOS Monterey 12.3.1

**Comment by kevinyang372** [comment] 2022-05-04 21:28
This should be fixed in the latest release!

**Closed** 2022-05-05 14:35 UTC

**Comment by RaviH** [comment] 2022-05-09 20:21
@kevinyang372 It's still not working for me with Max and F2 as the hot key.
