### ISSUE TITLE
Unable to return to k9s from pod exec

### ISSUE THREAD

**Issue by johnnyhuy** [warpdotdev/Warp#1705] opened 2022-08-10 22:37 UTC
### Describe the bug

I cannot run `kubectl exec` commands as it silently fails to open up a shell in a pod. However, when using tools like [`k9s`](https://k9scli.io/) exec works but then exiting with `ctrl + D`, the window becomes blank and unusable, which requires a restart of the tab.

### To Reproduce

If we don't have a Kubernetes cluster ready. Use [Minikube](https://minikube.sigs.k8s.io/docs/) to spin one up locally - [installation](https://minikube.sigs.k8s.io/docs/start/) (Homebrew works as well), [guide](https://kubernetes.io/docs/tutorials/hello-minikube/).

[Create a deployment](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-deployment) and exec into the pod.

```bash
$ kubectl exec deploy/hello-node -- /bin/sh
```

When using `k9s` exec into a pod by selecting a pod and press `s`, then exit with `ctrl + D`

### Expected behaviour

We should see an interactive shell open up with `kubectl exec`

`k9s` should come back when exiting the shell.

### Operating System

MacOS

### OS Version

11.6.1

### Shell Version

zsh 5.8 (x86_64-apple-darwin20.0)

### Warp Version

v0.2022.08.01.09.12.stable_02

### Does this block you from using Warp daily?

Yes

**Comment by zheng** [comment] 2022-08-10 22:53
Do you have a list of steps I can get up and running with kubernetes and create a kubernetes pod? I've tried to look online, but it seems really nontrivial

**Comment by johnnyhuy** [comment] 2022-08-10 22:57
Hey @zheng good call, I've put some steps on how to run `kubectl` locally with Minikube. Requires [Docker](https://www.docker.com/).

**Comment by johnnyhuy** [comment] 2022-08-12 08:30
> Hey @johnnyhuy,
> 
>     * for the `kubectl` part of the issue, I think you can get an interactive shell by specifying the `-i` and `-t` options when running `exec`. So something like `kubectl exec -it deploy/hello-node -- /bin/sh` should work!
> 
>     * for the `k9s` issue, we were able to repro inconsistently. Does this happen everytime for you when exiting `k9s` via `CTRL-D`?

Awesome, using `-it` worked 🚀 

For k9s `v0.25.18` I'm using `kubectl create deployment hello-node --image=nginx` since I'm on an M1, echo server doesn't work.

```bash
minikube start
😄  minikube v1.25.2 on Darwin 11.6.1 (arm64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

This is what it looks like when I `CTRL-D`, I can't press anything to go back to the shell. I have to create a new tab and close that one to recover.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/27847622/184315948-9d90872c-54ee-4616-9655-c7f49c7b6ab9.png">

**Comment by johnnyhuy** [comment] 2022-08-12 08:40
I got a few bits and pieces that might help in my `zshrc`

```bash
export DISABLE_MAGIC_FUNCTIONS=true
export GIT_EDITOR=vim
export KUBE_EDITOR=vim
export VISUAL=vim

source "$HOME/antigen.zsh"

antigen use oh-my-zsh
antigen bundle git
antigen bundle lukechilds/zsh-nvm
antigen bundle command-not-found
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle vkolagotla/zsh-random-quotes
antigen bundle b4b4r07/enhancd
antigen theme denysdovhan/spaceship-prompt
antigen apply

SPACESHIP_KUBECONTEXT_COLOR="blue"
SPACESHIP_GIT_BRANCH_PREFIX=""
SPACESHIP_PROMPT_ORDER=(
  time
  user
  dir
  host
  git
  kubectl_context
  exec_time
  line_sep
  jobs
  exit_code
  char
)

precmd () { echo -n "\x1b]1337;CurrentDir=$(pwd)\x07" }
```

**Comment by szgupta** [comment] 2022-08-12 19:18
@johnnyhuy does it happen on a new tab as well? When I tried this the first time, the problem happened but it doesn't happen when I open a new tab and try `k9s`

**Comment by johnnyhuy** [comment] 2022-08-12 23:25
> @johnnyhuy does it happen on a new tab as well? When I tried this the first time, the problem happened but it doesn't happen when I open a new tab and try `k9s`

Weirdly enough I was able to exit back into k9s the first time but the following times I got the same issue.

![Screen Recording 2022-08-13 at 9 08 16 am](https://user-images.githubusercontent.com/27847622/184456399-73208b60-1b32-486d-9878-dbf66ff72e38.gif)

**Comment by amitpaz** [comment] 2022-08-13 07:11
Getting the same issues 
Logs contain the following error:
/Application Support/k9s/views.yml: no such file or directory

**Comment by johnnyhuy** [comment] 2022-08-18 00:29
FYI, tested this with other terminals out in the wild like Tabby, VSCode and iTerm2, and they all behave correctly at all times 😬

**Comment by dannyneira** [comment] 2022-08-18 17:30
We've been able to repro this issue reliably with k9s, we will provide updates as soon as we can

**Comment by johnnyhuy** [comment] 2022-08-18 23:57
> We've been able to repro the shell/edit issue with k9s, we will provide updates as soon as we can.
> 
> also, `kubectl exec deploy/<deployment_name> -- /bin/sh` doesn't work on iTerm, terminal.app, VS Code Terminal either. Only works with the `-it` flag

That's right, that's on me. I missed the `-it` flag :P

**Comment by mrfrsh** [comment] 2022-09-30 06:32
Same Here! this is the only thing keeping me from using your amazing product 100% of the time.

**Comment by derlin** [comment] 2022-10-27 11:28
@dannyneira any news on this ?

**Comment by amitpaz** [comment] 2022-10-27 12:28
> @dannyneira any news on this?

Still occurring on the latest version
<img width="312" alt="image" src="https://user-images.githubusercontent.com/644619/198284155-d513db4c-a015-4925-8321-a6f4c7dc5f54.png">

**Comment by derlin** [comment] 2022-10-27 12:58
@amitpaz yes I know, this is why I would like to know if warp plans on addressing the issue soon, or if there is any changes on their side regarding this bug

**Comment by iochagov** [comment] 2022-11-18 08:51
Still happens to me also

**Comment by md-fid** [comment] 2022-11-21 09:06
Same here when using k9s (v0.2022.11.14.14.55.stable_01)

**Comment by ventsislav-georgiev** [comment] 2022-11-23 19:02
Maybe caused by same issue report here:
* https://github.com/warpdotdev/Warp/issues/833
* https://github.com/warpdotdev/Warp/issues/1315

**Comment by janeklb** [comment] 2022-11-25 13:08
There's also https://github.com/warpdotdev/Warp/issues/2133

**Comment by dannyneira** [comment] 2022-11-29 00:01
Hi all, sorry about this issue, we know this is a huge blocker for many so we appreciate your patience. 

Closing as duplicate, please track this issue there > of #833

**Closed by dannyneira** 2022-11-29 00:01 UTC

**Comment by dannyneira** [comment] 2022-12-19 17:22
We recently made performance/compatibility updates to alt-screen apps like emacs, please let us know if you're still seeing the issues with the latest version of Warp.
