### ISSUE TITLE
Can't see my current git branch in my prompt

### ISSUE THREAD

**Issue by FlorianTousch** [warpdotdev/Warp#3229] opened 2023-06-21 13:10 UTC
### Describe the bug

I search in internet and what I undersrand is that sith the default prompt, we have: path + branch + nb of changes.
I did have this configuration, but for some reason I can't find a way to see my git infos.

### To reproduce

1: Go to a file with a git repository
2: Watch the prompt

### Expected behavior

For exemple in my screenshot
`~/iOS/GL/gl-ios [feat/client-16086-sorts]2`

### Screenshots

![CleanShot 2023-06-21 at 15 02 42@2x](https://github.com/warpdotdev/Warp/assets/5923142/220fe7a8-9700-4f1a-b8e4-74e9581f5224)

### Operating system

MacOS

### Operating system and version

14.0.0

### Shell Version

GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin23) zsh 5.9 (x86_64-apple-darwin23.0)

### Current Warp version

v0.2023.06.13.08.03.stable_03

### Regression

No, this bug or issue has existed throughout my experience using Warp

### Recent working Warp date

~15/06/23

### Does this block you from using Warp daily?

Yes, this issue prevents me from using Warp daily.

### Is this a Warp specific issue? (i.e. does it happen in Terminal, iTerm, Kitty, etc.)

Yes, this I confirmed this only happens in Warp, not other terminals.

### Warp Internal (ignore): linear-label:b8107fdf-ba31-488d-b103-d271c89cac3e

None

**Comment by vinayk406** [comment] 2023-06-21 14:23
With the latest update even i'm not seeing the git branch in my warp terminal.

**Comment by dannyneira** [comment] 2023-06-21 16:48
Hey Folks, sorry to hear about this issue. I can't seem to reproduce this on my end. There are a few questions that may help us narrow down the root of the issue.

- Is there any custom prompt you're using or [Warp default prompt](https://docs.warp.dev/features/prompt)? If default, as a workaround, you can try using a custom prompt like Starship.rs so that you can see the git branch.
- When you right-click on the prompt and "Copy git branch", then paste it into the input editor, does it paste the branch or nothing? 
- Also, care to share your redacted (make sure to not include any personal information on these files. i.e. logins, IPs, etc.) gitconfig or rcfiles so that we can try and reproduce this issue?

**Comment by wagenet** [comment] 2023-06-21 23:50
When I right click on the prompt there is no "Copy git branch" option.

**Comment by adithyaakrishna** [comment] 2023-06-22 07:37
I am also facing this issue. Not able to see the current branch in the terminal

<img width="778" alt="Screenshot 2023-06-22 at 1 06 35 PM" src="https://github.com/warpdotdev/Warp/assets/23498248/49cfa17b-c652-47ba-95be-67535fd8bd32">

**Comment by terrisgit** [comment] 2023-06-22 14:14
I wish I couldn't reproduce it! I can't imagine a worse bug. I really don't use many Warp features. This is a deal kller.

1) I use zsh with warpify enabled
2) I'm using the default prompt but using custom prompt doesn't work either
3) Changing .zprofile and .zshrc per these instructions doesn't work [either](https://www.themoderncoder.com/add-git-branch-information-to-your-zsh-prompt/) 
4) It used to work before I upgraded to v0.2023.06.13.08.03.stable_03

**Comment by terrisgit** [comment] 2023-06-22 14:31
I was able to get a custom prompt working by adding this to ~/.zshrc:

```sh
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' formats "%F{010}(%b)%f "

precmd() { vcs_info }
setopt prompt_subst
PROMPT='%n in ${PWD/#$HOME/~} ${vcs_info_msg_0_}
%# '
```

**Comment by filipminev** [comment] 2023-06-25 12:28
The latest update broke it for me as well

**Comment by GenadiKozarev** [comment] 2023-06-27 14:01
Had an update pending and did it today. Now it's broken...

MacBook Pro
Chip: Apple M1 Pro
macOS Ventura 13.3.1

**Comment by AlonsoCN** [comment] 2023-06-27 16:56
I having the same issue here. Branch name is not displayed anymore.

**Comment by SHF-Tim** [comment] 2023-06-27 17:41
I'm also seeing the same issue, after the latest update

**Comment by FlorianTousch** [comment] 2023-06-28 15:27
I fix the issue by deleting the `.zshrc` and other related files 🤷🏽‍♂️
Didn't know why because I didn't use it previously.

Not sure it will work for everyone. 

Thanks for all the sharings

**Comment by edwincoronado** [comment] 2023-06-28 17:28
This issue is also happening to me since latest update. Deleting the `.zshrc` files is not an actual solution. I have stuff in `.zshrc` that I rely on.

**Comment by dannyneira** [comment] 2023-06-28 18:19
I agree that deleting the .zshrc file isn't the right solution, but in @FlorianTousch 's case it resolved the issue because they more than likely had a [custom prompt, theme, or bash/zsh/fish plugin, and Warp is unable to parse it.](https://docs.warp.dev/features/prompt#custom-prompt-compatibility-table)

For your to resolve the issue @edwincoronado, you'd have to check out the list of incompatible tools here: <https://docs.warp.dev/help/known-issues#list-of-incompatible-tools> 

Then disable parts of your dotfiles just for Warp by using this conditional statement:

```sh
# Bash and Zsh
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
# > What you want to disable here <
fi
```

```sh
# Fish
if test "$TERM_PROGRAM" != "WarpTerminal"
# > What you want to disable here <
end
```

**Comment by abartolo** [comment] 2023-06-29 14:40
Having the same issue :( I really enjoyed this feature.

**Comment by wagenet** [comment] 2023-06-30 19:06
@dannyneira Why would it have stopped working when it worked previously?

**Comment by charlespierce** [comment] 2023-06-30 22:58
Hi all! Apologies you're running into this regression 😦 I have a hypothesis about what is causing it, related to how we locate the `git` executable to populate that portion of the default prompt. If you're seeing this behavior, can you share:

1. How `git` was installed on your machine (if you can recall)
2. The output of `which -a git`

That should help confirm if what I'm seeing is in fact the root cause of this issue, or if we need more investigation. Thanks!

**Comment by SHF-Tim** [comment] 2023-06-30 23:02
```
which -a git
/opt/homebrew/bin/git
/usr/bin/git
```

**Comment by charlespierce** [comment] 2023-06-30 23:12
Thanks @SHF-Tim, I think that confirms my hypothesis! We should have a fix out for this in the next release—it may be tight given the holiday, in which case it would be the release after.

**Comment by goyalprashant** [comment] 2023-07-04 05:41
I was also facing same issue, but when I right clicked on prompt ans selected 'use my own prompt' it started working.

I use below in my .zshrc
```
# Prompt Change
source /opt/homebrew/etc/bash_completion.d/git-prompt.sh
setopt PROMPT_SUBST ; PS1='%~$(__git_ps1 " git:(%s)")\$ '
```

**Comment by SHF-Tim** [comment] 2023-07-06 21:09
The newest update fixed this issue for me.

**Comment by wagenet** [comment] 2023-07-07 00:00
The latest release also resolved it for me. Thanks!

**Comment by charlespierce** [comment] 2023-07-07 00:31
Excellent, glad to hear it! Thanks all for reporting and helping to debug 🚀

**Comment by edwincoronado** [comment] 2023-07-07 05:03
Same, working for me with new update!

**Comment by VonOzen** [comment] 2023-07-07 13:29
Same, everything seems to work with the latest update (v0.2023.07.04.08.03.stable_02)
Thank you for the great work and reactivity 🚀

**Comment by dannyneira** [comment] 2023-07-07 15:12
Great! Thanks for confirming folks. Closing as resolved.

**Closed by dannyneira** 2023-07-07 15:12 UTC
Labels: Bug

**Comment by adithyaakrishna** [comment] 2023-07-07 17:59
LFG 🚀

**Comment by abartolo** [comment] 2023-07-07 18:00
Thanks, confirmed it worked 😁👍
