### ISSUE TITLE
Yarn output not visible

### ISSUE THREAD

**Issue by mikehurl** [warpdotdev/Warp#1393] opened 2022-05-23 11:38 UTC
### Describe the bug

```text
I ran `yarn install` in a project I am working on. Following that, Yarn issues a warning that my current version of Yarn is out of date and prints a command that will upgrade it. Unfortunately, for some reason, that command is not visible unless I hover over or highlight the area where the command is printed.
```

### To Reproduce

Steps to reproduce:
1. Install packages with an out of date version of Yarn

### Expected behaviour

```text
I would expect to be able to see the command I need to run.
```

### Screenshots

No hover:
<img width="1418" alt="Screenshot 2022-05-23 at 12 35 56" src="https://user-images.githubusercontent.com/18559606/169810792-3cdffeb7-b4d7-4a72-a028-0012c360f221.png">

With command highlighted:
<img width="1408" alt="Screenshot 2022-05-23 at 12 37 28" src="https://user-images.githubusercontent.com/18559606/169811085-0263a465-b266-4681-9454-18222c81995e.png">

### Operating System

MacOS

### OS Version

12.4

### Shell Version

zsh 5.8.1 (x86_64-apple-darwin21.0)

**Comment by charlespierce** [comment] 2022-07-08 19:08
@mikehurl Thanks for reporting! Can you share which theme you are using? If it's a custom theme, can you share the `.yaml` file that defines it? I'm not able to reproduce this using the default `Light` theme.

**Comment by charlespierce** [comment] 2022-07-08 19:14
Also: Which version of Warp are you using? If you click the three dots menu in the top-right of Warp, there should be a line that says "Current version is v0.2022..."

**Comment by mikehurl** [comment] 2022-07-11 10:31
The current version is v0.2022.06.27.09.14.stable_01 (although I've probably updated since reporting the issue so might not be so relevant?). The theme I use is the Light theme provided and I use Fira Code for my terminal font.

**Comment by dannyneira** [comment] 2022-09-02 20:33
Hi @mikehurl, I'm Danny a Support Engineer at Warp. I'll be helping with this issue so that we can work on a fix for you. 

I've installed yarn 1.22.18 via npm and ran `yarn install`, but I'm unable to get the white text under the `info: To upgrade` prompt you're seeing. Despite, I was able to reproduce the white text you're seeing so will post updates here or request more info if needed.

Thanks for your patience while we work on this issue.

**Comment by elviskahoro** [comment] 2022-11-10 23:28
Sharing this across various color related issues. The team fixed one of the core issues with colors and there's a new toggle under Settings > Appearance that let's you configure whether to enforce a minimum contrast (one of the issues). Please check if you're still having color issues again and test tweaking the toggle:

<img width="505" alt="CleanShot 2022-11-10 at 15 17 22@2x" src="https://user-images.githubusercontent.com/29553206/201227106-64005c9c-cbab-446b-84c6-665b80205000.png">

**Closed** 2022-11-10 23:29 UTC
